include::./index.adoc[]

[[v48-5-0]]
=== Aos Gálatas, 5
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* D. PAULO EXPLICA O QUE A LIBERDADE CRISTÃ SIGNIFICA (4:21–6:10)
* Paulo usa um drama simbólico para explicar a liberdade cristã (4:21–5:1)
* Insistir na circuncisão não traz liberdade (5:2-12)
* A luta contínua entre carne e espírito (5:13-26)
* Cumprir a lei do Cristo envolve levar os fardos uns dos outros (6:1-6)
* Cada um colherá aquilo que semear (6:7-10)
****

[[v48-5-1]]

^<<v48-5-1,1>>^ Para tal liberdade é que Cristo nos libertou. Portanto, mantenham-se firmes e não se deixem submeter novamente a um jugo de escravidão.

[TIP]
====
- *Para tal liberdade é que Cristo nos libertou*: Nesta carta, Paulo usa as palavras gregas para “liberdade” e “libertar” várias vezes para destacar “a liberdade . . . em união com Cristo Jesus” que os ungidos têm. (Gál 2:4) Ele faz um contraste entre essa liberdade e a escravidão que ele menciona no capítulo anterior. As palavras de Paulo aqui também poderiam ser traduzidas como “Com a liberdade dela é que Cristo nos libertou”. Essa tradução destacaria que os únicos que podem ter essa liberdade são os filhos “dela”, ou seja, da “Jerusalém de cima”, que é livre. — Gál 4:26.
- *um jugo de escravidão*: A Lei que tinha sido dada à nação de Israel era justa e santa. (Ro 7:12) Mas, para humanos imperfeitos, era impossível seguir a Lei perfeitamente. Se um cristão quisesse ficar debaixo da Lei, ele estaria ‘se submetendo novamente a um jugo de escravidão’, porque a Lei o condenaria como pecador e escravo do pecado. O sacrifício de resgate de Cristo libertou as pessoas desse “jugo”. — At 15:10; Gál 5:1-6; veja o Glossário, “Jugo”.
====

[[v48-5-2]]

^<<v48-5-2,2>>^ Prestem atenção! Eu, Paulo, digo-lhes que, se vocês forem circuncidados, Cristo não terá nenhum valor para vocês.

[[v48-5-3]]

^<<v48-5-3,3>>^ A todo homem que se submete à circuncisão, declaro novamente que ele está sob a obrigação de cumprir toda a Lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Vocês que tentam ser declarados justos por meio de lei estão separados de Cristo; excluíram-se^&#42;1^ da bondade imerecida dele.

[NOTE]
====
. Ou: “decaíram”.
====

[[v48-5-5]]

^<<v48-5-5,5>>^ Quanto a nós, por espírito aguardamos ansiosamente a esperada justiça^&#42;1^ que resulta da fé.

[NOTE]
====
. Lit.: “esperança da justiça”.
====

[[v48-5-6]]

^<<v48-5-6,6>>^ Pois, em união com Cristo Jesus, nem a circuncisão nem a incircuncisão são de valor algum, mas sim a fé que age por meio do amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vocês estavam correndo bem. Quem os impediu de continuar obedecendo à verdade?

[TIP]
====
- *Vocês estavam correndo bem*: Aqui, Paulo usa uma corrida como metáfora para dizer que os cristãos na Galácia antes estavam se saindo bem em seu esforço de levar uma vida cristã. Ele faz comparações parecidas várias vezes em suas cartas. (Compare com Gál 2:2; veja a nota de estudo em 1Co 9:24.) A Bíblia muitas vezes usa a ideia de andar e correr para se referir a levar um certo tipo de vida. — Gên 5:22; 6:9; Ef 4:17; 5:2.
====

[[v48-5-8]]

^<<v48-5-8,8>>^ Esse tipo de persuasão não vem Daquele que os chama.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda a massa toda.

[TIP]
====
- *fermento*: Veja o Glossário e a nota de estudo em 1Co 5:6.
- *leveda a*: Ou: “se espalha pela; tem efeito sobre a”. O verbo grego usado aqui, zymóo (“fermentar”), está relacionado com o substantivo zýme (“fermento”), que também foi usado neste versículo. Em 1Co 5:6, Paulo usou essa mesma frase (“Um pouco de fermento leveda a massa toda”), que pelo visto era um ditado popular. Paulo está destacando que, assim como um pouco de fermento leveda a massa toda, instrutores falsos (nesse caso, os defensores da circuncisão) são capazes de corromper uma congregação inteira com seus ensinos.
====

[[v48-5-10]]

^<<v48-5-10,10>>^ Estou confiante em que vocês que estão em união com o Senhor não pensarão de outro modo; mas aquele que os perturba, não importa quem seja, terá o julgamento que merece.

[[v48-5-11]]

^<<v48-5-11,11>>^ Quanto a mim, irmãos, se eu ainda prego a circuncisão, por que ainda estou sendo perseguido? Nesse caso, a pedra de tropeço da estaca foi eliminada.

[TIP]
====
- *a pedra de tropeço*: Ou: “a ofensa”. — Veja as notas de estudo em Mt 13:57; 18:7.
- *a pedra de tropeço da estaca*: A morte de Jesus na estaca deu base para que a Lei mosaica fosse eliminada. Paulo e os outros cristãos pregavam que o único modo de alcançar a salvação era ter fé no sacrifício de Cristo. (Col 2:13, 14; veja a nota de estudo em Gál 5:1.) Muitos judeus tropeçaram, ou se ofenderam, com essa mensagem; eles insistiam que era necessário seguir a Lei, incluindo a lei da circuncisão, para ter a aprovação de Deus. — Veja a nota de estudo em 1Co 1:23.
- *estaca*: Ou: “estaca de tortura; estaca de execução”. — Veja a nota de estudo em 1Co 1:17.
====

[[v48-5-12]]

^<<v48-5-12,12>>^ Eu queria que os homens que estão perturbando vocês castrassem a si mesmos.

[TIP]
====
- *castrassem a si mesmos*: Ou: “se tornassem (se fizessem) eunucos”. Lit.: “se decepassem”. Aqui, Paulo usa uma expressão forte, e até sarcástica, que obviamente não deve ser levada ao pé da letra. Ao dizer que queria que esses homens castrassem a si mesmos, ele estava usando uma hipérbole. (Veja o Glossário, “Eunuco”.) Se os defensores da circuncisão realmente se castrassem, eles ficariam desqualificados para cumprir a própria Lei que defendiam. (De 23:1) Além disso, alguns comentaristas bíblicos sugerem que Paulo esteja fazendo referência a rituais de castração de religiões pagãs, comparando os defensores da circuncisão com idólatras pagãos.
====

[[v48-5-13]]

^<<v48-5-13,13>>^ Vocês foram chamados à liberdade, irmãos. Somente não usem essa liberdade como uma oportunidade para buscar os desejos da carne; ao contrário, por meio do amor, trabalhem como escravos uns para os outros.

[TIP]
====
- *Vocês foram chamados à liberdade*: Aqui, Paulo está dando um alerta: os cristãos que cedem aos desejos da carne (ou seja, aos desejos errados) estão abusando da liberdade que têm com Cristo. (Gál 2:4; 4:24-31) Por outro lado, aqueles que dão valor a essa liberdade a usam para trabalhar como escravos uns para os outros por amor, servindo humildemente a outros. — Veja as notas de estudo em Gál 5:1, 14.
- *para buscar os desejos da carne*: Lit.: “para a carne”. A palavra grega sarx (“carne”) aparece várias vezes nos próximos versículos. (Gál 5:16-19) Aqui, ela se refere à natureza pecaminosa dos humanos. — Veja a nota de estudo em Gál 5:19.
- *por meio do amor, trabalhem como escravos uns para os outros*: Neste versículo, Paulo incentiva os cristãos a não usarem sua vida para buscar objetivos egoístas. Em vez disso, motivados por amor, eles deveriam trabalhar como escravos para seus companheiros cristãos. O verbo grego traduzido aqui como “trabalhar como escravos” talvez tenha sido usado por Paulo para indicar que os cristãos deveriam tratar uns aos outros com dignidade e respeito, mostrando a mesma humildade que um escravo teria ao servir seu senhor. As palavras “trabalhem como escravos uns para os outros” também poderiam ser traduzidas como “sirvam uns aos outros de maneira humilde”.
====

[[v48-5-14]]

^<<v48-5-14,14>>^ Pois a Lei inteira se cumpre num só mandamento: “Ame o seu próximo como a si mesmo.”

[TIP]
====
- *se cumpre*: A palavra grega que aparece aqui poderia ser entendida de duas formas: ela pode indicar que a Lei mosaica “encontra seu cumprimento” nesse mandamento, ou que a Lei é “expressa plenamente” por meio desse mandamento. Seja como for, as duas formas passam a ideia de que uma pessoa cumpre a Lei inteira quando mostra amor, porque o amor é a base da Lei. O mandamento que Paulo está citando aqui é o de Le 19:18. Paulo cita esse mesmo versículo em Ro 13:9, onde ele diz que todos os mandamentos da Lei “se resumem nestas palavras” sobre amar o próximo como a si mesmo. Aqui em Gálatas, algumas Bíblias usam a tradução “se resume”, o que também seria aceitável.
====

[[v48-5-15]]

^<<v48-5-15,15>>^ Se vocês, porém, continuarem mordendo e devorando uns aos outros, cuidado para não serem destruídos uns pelos outros.

[[v48-5-16]]

^<<v48-5-16,16>>^ Mas eu digo: Continuem andando por espírito, e não executarão nenhum desejo carnal.

[TIP]
====
- *Continuem andando por espírito*: Neste contexto, a expressão “andar por espírito” passa a ideia de que a pessoa busca a orientação do espírito de Deus e permite que ele influencie seus pensamentos e ações. Essa pessoa talvez ainda tenha desejos errados; mas, quando eles surgem, ela os rejeita imediatamente, recusando-se a pensar neles. Assim, ela não se torna praticante do pecado. (Ro 8:4-6; Tg 1:14, 15) Aqui, Paulo faz um contraste entre a conduta da pessoa que anda por espírito e a conduta da pessoa que permite que desejos carnais a dominem.
====

[[v48-5-17]]

^<<v48-5-17,17>>^ Pois a carne é contra o espírito no seu desejo, e o espírito contra a carne; eles se opõem um ao outro, de modo que vocês não fazem as coisas que querem fazer.

[TIP]
====
- *a carne . . . o espírito*: Neste capítulo, Paulo fala várias vezes da “carne” e do “espírito” como forças em oposição uma à outra. Aqui, “a carne” se refere à natureza pecaminosa dos humanos. Por outro lado, “o espírito” se refere ao espírito santo de Deus, mas também poderia incluir a força interior que motiva a pessoa que é guiada pelo espírito santo. (Veja o Glossário, “Espírito”.) O espírito santo estimula os servos de Deus a praticar a justiça, mas a carne pecaminosa luta continuamente contra a influência dele. Em Gál 5:19-23, Paulo faz um contraste entre as obras da carne e o fruto do espírito santo. — Compare com Ro 7:18-20.
====

[[v48-5-18]]

^<<v48-5-18,18>>^ Além disso, se vocês estão sendo conduzidos por espírito, não estão debaixo de lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ As obras da carne são claramente vistas. Elas são: imoralidade sexual, impureza, conduta insolente,

[TIP]
====
- *As obras da carne*: Nos versículos anteriores, Paulo fala da luta constante entre “a carne” e “o espírito”. (Gál 5:13, 17) Nos versículos 19-21, ele alista 15 obras, ou práticas, relacionadas com “a carne”, ou seja, a natureza pecaminosa dos humanos. (Veja as notas de estudo em Mt 26:41; Gál 5:13, 17.) “As obras” que Paulo menciona nesses versículos são o resultado da influência negativa da carne sobre os pensamentos e ações da pessoa. (Ro 1:24, 28; 7:21-25) Paulo termina a lista com a expressão “e coisas como essas”, mostrando que ele estava dando apenas exemplos de obras da carne, e não uma lista completa. — Veja a nota de estudo em Gál 5:21.
- *imoralidade sexual*: A Bíblia usa a palavra grega porneía como um termo genérico para se referir a todas as formas de relação sexual condenadas por Deus. Um léxico define porneía como “prostituição, falta de castidade, fornicação” e acrescenta que essa palavra é usada para se referir a “toda espécie de relação sexual ilícita”. As formas de relação sexual que as Escrituras condenam incluem não apenas adultério, prostituição e sexo entre pessoas não casadas, mas também sexo com animais e entre pessoas do mesmo sexo. (Le 18:6, 22, 23; 20:15, 16; 1Co 6:9; veja o Glossário.) Jesus mostrou que a imoralidade sexual é um pecado sério, colocando-a no mesmo nível de pecados como roubo, assassinato e blasfêmia. — Mt 15:19, 20; Mr 7:21-23.
- *impureza*: Ou: “imundice; depravação”. Das palavras gregas usadas para se referir às três primeiras “obras da carne”, akatharsía (“impureza”) é a que tem o sentido mais amplo. Ela aparece dez vezes nas Escrituras Gregas Cristãs e, em sentido literal, se refere a algo impuro ou imundo. (Mt 23:27) Em sentido figurado, ela inclui todos os tipos de impureza — em assuntos sexuais, em assuntos espirituais (por exemplo, adorar deuses falsos), em palavra ou em ação. (Ro 1:24; 6:19; 2Co 6:17; 12:21; Ef 4:19; 5:3; Col 3:5; 1Te 2:3; 4:7) Assim, “impureza” pode se referir a diferentes tipos de comportamentos errados e pode ter diferentes níveis de gravidade. (Veja a nota de estudo em Ef 4:19.) A palavra grega dá destaque ao fato de que a conduta errada ou a condição da pessoa é repugnante em sentido moral. — Veja o Glossário, “Impuro”.
- *conduta insolente*: Ou: “conduta desavergonhada; licenciosidade”. Na Bíblia, a palavra grega asélgeia é usada para se referir a um tipo de conduta que viola gravemente as leis de Deus e que reflete uma atitude descarada ou atrevida de desrespeito. Ela aparece dez vezes nas Escrituras Gregas Cristãs. (Mr 7:22; Ro 13:13; 2Co 12:21; Gál 5:19; Ef 4:19; 1Pe 4:3; 2Pe 2:2, 7, 18; Ju 4) Um léxico define asélgeia como “devassidão, licenciosidade, lascívia, i.e., ausência de limites morais nas atitudes e nos comportamentos”. O historiador judeu Josefo usou essa palavra ao falar da ocasião em que a rainha pagã Jezabel fez um altar para Baal em Israel. O ato dela foi chocante. De forma descarada, Jezabel desprezou a opinião pública e agiu contra toda a decência. — Jewish Antiquities, livro 8, capítulo 13, parágrafo 1 (Loeb 8.318); veja o Glossário.
====

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria, ocultismo, inimizades, brigas, ciúme, acessos de ira, discórdias, divisões, formação de seitas,

[TIP]
====
- *ocultismo*: Ou: “feitiçaria; espiritismo; uso de drogas”. O substantivo grego que aparece aqui, farmakía, tem o sentido básico de “uso de drogas”. Essa palavra com o tempo passou a ser ligada com o ocultismo e a magia, possivelmente porque as pessoas usavam drogas quando invocavam o poder de demônios para praticar feitiçaria. Ela foi usada na Septuaginta para traduzir as palavras hebraicas para “magia” (Êx 7:11 [“artes mágicas”, nota de rodapé]), “artes secretas” (Êx 7: 22; 8:7, 18) e “feitiçarias” (Is 47:9, 12). O fato de Paulo ter alistado farmakía logo depois de idolatria apoia a conclusão de que aqui ele usou a palavra para se referir a práticas ocultas. (Veja o Glossário, “Ídolo; Idolatria”.) Em Ap 21:8, o substantivo grego relacionado farmakós é traduzido como “os que praticam ocultismo”. — Ap 22:15; veja o Glossário, Ocultismo; Espiritismo.
- *ciúme*: A palavra grega que aparece aqui, zélos, passa a ideia de um sentimento forte que pode ser positivo ou negativo. Neste versículo, Paulo inclui zélos em sua lista de obras da carne. Assim, neste contexto, ela se refere a um sentimento negativo que uma pessoa tem em relação a alguém que ela encara como rival ou a alguém que parece ter uma vantagem sobre ela. Os cristãos do século 1 d.C. foram aconselhados fortemente a lutar contra esse tipo de ciúme. — 1Co 3:3; 2Co 12:20; Tg 3:14, 16; veja a nota de estudo em 1Co 13:4.
- *acessos de ira*: Ou: “ataques de raiva”. Lit.: “iras”. Aqui, Paulo usa a palavra grega para “ira” no plural. Essa palavra pode se referir não apenas a explosões de ira repentinas, mas também a acessos de ira causados pela raiva que a pessoa foi nutrindo aos poucos no coração. Aqui, a ira é mencionada junto com outras obras da carne detestáveis, como imoralidade sexual, conduta insolente, idolatria, ocultismo e embriaguez.
- *formação de seitas*: Veja a nota de estudo em At 24:5.
====

[[v48-5-21]]

^<<v48-5-21,21>>^ inveja, embriaguez, festas descontroladas e coisas como essas. Eu estou advertindo vocês a respeito dessas coisas, do mesmo modo como já os adverti: os que praticam tais coisas não herdarão o Reino de Deus.

[TIP]
====
- *festas descontroladas*: Veja a nota de estudo em Ro 13:13.
- *e coisas como essas*: Estas palavras mostram que Paulo não estava dando uma lista completa com todas as coisas que poderiam ser consideradas obras “da carne”, ou seja, da natureza pecaminosa dos humanos. (Veja a nota de estudo em Gál 5:19.) Em 1Ti 1:10, Paulo termina uma lista de forma semelhante. Os cristãos da Galácia precisariam usar sua “capacidade de discernimento” para identificar outras coisas parecidas com os pecados que Paulo menciona nestes versículos. (He 5:14) Por exemplo, apesar de ele não ter incluído a calúnia em sua lista, ela muitas vezes anda de mãos dadas com pecados como “inimizades, brigas, ciúme, acessos de ira, discórdias”, que foram mencionados em Gál 5:20. Os que praticam “obras da carne” ou “coisas como essas” e não se arrependem não receberão as bênçãos do Reino de Deus.
====

[[v48-5-22]]

^<<v48-5-22,22>>^ Por outro lado, o fruto do espírito é: amor, alegria, paz, paciência, bondade, benignidade, fé,

[TIP]
====
- *o fruto do espírito é*: Ou: “o espírito produz”. A palavra grega karpós (“fruto”) é um termo agrícola que aparece muitas vezes nas Escrituras. Aqui, ela é usada em sentido figurado para se referir às qualidades que o espírito santo, ou força ativa, de Deus pode produzir nos humanos. (Gál 5:16) Assim como uma árvore produz fruto quando é cultivada corretamente, uma pessoa produz “o fruto do espírito” quando deixa que o espírito santo influencie seus pensamentos e ações. (Compare com o Sal 1:1-3.) As qualidades desse fruto são um reflexo da personalidade de Jeová Deus, que é a Fonte do espírito santo. (Col 3:9, 10) A lista dos versículos 22 e 23 não inclui todas as qualidades que o espírito santo produz nos cristãos e que, juntas, formam a nova personalidade. (Ef 4:24; veja a nota de estudo em Gál 5:23.) Aqui, Paulo usa a palavra grega karpós no singular, falando de um único “fruto”. Alguns comentaristas bíblicos acreditam que isso pode indicar que as qualidades mencionadas especificamente nesses versículos formam um todo, todas elas sendo importantes e não podendo existir separadas umas das outras.
- *amor*: A palavra grega que aparece aqui é agápe. A melhor forma de explicar o amor cristão é descrever como ele age, assim como Paulo faz em 1Co 13:4-8. (Veja a nota de estudo em 1Co 13:4.) João usa essa mesma palavra em 1Jo 4:8-10, onde ele fala sobre “o amor de Deus”. Ele chega a dizer que “Deus é amor”, o que significa que Jeová é a personificação do amor, ou o amor em pessoa. (Veja a nota de estudo em Jo 3:16.) Jesus disse que amar a Deus e amar ao próximo são os dois maiores mandamentos. — Mt 22:37-39; veja a nota de estudo em Mt 22:37.
- *alegria*: A palavra grega que aparece aqui se refere ao sentimento agradável que a pessoa tem quando consegue algo muito bom ou está na expectativa disso; um estado de verdadeira felicidade. Não se trata de algo passageiro, mas de um sentimento profundo do coração. Jeová, o “Deus feliz”, é a Fonte da alegria e quer que seu povo seja alegre também. (1Ti 1:11) Com a ajuda do espírito santo, um cristão pode manter a alegria mesmo ao enfrentar situações tristes, dificuldades ou perseguição. — Col 1:11; He 12:2; Tg 1:2-4.
- *paz*: A palavra grega para “paz” tem um sentido bem amplo. Aqui, ela se refere à tranquilidade que a pessoa sente por ter uma amizade forte com Jeová, o “Deus de paz”. (Fil 4:9; 1Te 5:23; He 13:20; veja a nota de estudo em 1Co 14:33.) Na Bíblia, o espírito santo é muitas vezes mencionado junto com a “paz”. (At 9:31; Ro 8:6; 15:13) Com a ajuda desse espírito, a pessoa que está em paz com Deus promove harmonia, união e bons relacionamentos. — Mt 5:9; 2Co 13:11; Tg 3:18.
- *paciência*: Ou: “longanimidade”. A tradução literal da palavra grega que aparece aqui é “longura de espírito”. (Kingdom Interlinear) Ela passa a ideia de perseverar com tranquilidade, ser tolerante e demorar para ficar irritado. Ninguém demonstra essa qualidade num grau maior do que Jeová Deus. (Ro 2:4; 9:22; 1Ti 1:16; 1Pe 3:20; 2Pe 3:9, 15) Em 1Co 13:4, Paulo cita a paciência como uma das principais características do amor cristão. — Veja o Apêndice A2.
- *bondade*: A qualidade mencionada por Paulo aqui envolve se interessar pelo bem-estar de outros e agir de modo amigável para ajudá-los no que precisam. Jeová Deus é bondoso até mesmo com os ingratos e maus. (Lu 6:35; Ro 2:4; 11:22; Tit 3:4, 5) Uma forma da palavra grega para “bondade” foi usada no Evangelho de Mateus, na passagem em que Jesus descreve seu jugo como “suave” ou “fácil de carregar; agradável”. (Mt 11:30, nota de rodapé) Os que aceitam o jugo de Jesus e se tornam cristãos devem se revestir de bondade. — Ef 4:32; Col 3:12.
- *benignidade*: A palavra grega que aparece aqui se refere a excelência moral; virtude; aquilo que é bom. Na Tradução do Novo Mundo da Bíblia Sagrada em português, a ideia de “benignidade” geralmente é traduzida por palavras ou expressões que são mais comuns, como “bondade”, “fazer o bem”, “ser bom” e assim por diante. Um léxico define essa palavra grega como “qualidade moral positiva que se caracteriza especialmente pelo interesse no bem-estar de outros”. Assim, o cristão não pode apenas ter essa qualidade, ele também precisa agir de acordo com ela. Mesmo sendo imperfeitos, os cristãos podem cultivar a benignidade por obedecer aos mandamentos de Jeová e imitar a benignidade e a generosidade dele ao lidar com outros. (At 9:36, 39; 16:14, 15; Ro 7:18; Ef 5:1) Jeová é benigno em sentido absoluto. (Sal 25:8; Za 9:17; Mr 10:18 e a nota de estudo) Ele é extremamente generoso e está profundamente interessado no bem-estar dos humanos. — At 14:17.
- *fé*: A palavra grega que aparece aqui é pístis. A ideia principal que essa palavra passa é a de “convicção; confiança; firme persuasão”. Em He 11:1, Paulo, sob inspiração, explica o significado de “fé”. Assim como acontece com o amor, a fé é expressa em ações. (Tg 2:18, 22; veja a nota de estudo em Jo 3:16.) As Escrituras indicam que a fé do cristão deve crescer com o tempo. Isso está de acordo com o pedido que os discípulos de Jesus fizeram a ele: “Dê-nos mais fé.” (Lu 17:5) E, ao elogiar os cristãos em Tessalônica, Paulo disse: “A sua fé está crescendo extraordinariamente.” (2Te 1:3; veja também 2Co 10:15.) O livro de Gálatas menciona a “fé” mais de 20 vezes. Na maioria delas, ela se refere à confiança em Deus ou em Cristo, como acontece neste versículo. (Gál 3:6, 11) Em 2Te 3:2, Paulo diz: “A fé não é propriedade de todos.” Para ter uma fé forte, a pessoa precisa do espírito santo de Jeová.
====

[[v48-5-23]]

^<<v48-5-23,23>>^ brandura, autodomínio. Contra tais coisas não há lei.

[TIP]
====
- *brandura*: A palavra grega que aparece aqui, praýtes, envolve a pessoa que o cristão é por dentro. Ela se refere a uma atitude calma e pacífica que se manifesta no seu relacionamento com Deus e na sua maneira de tratar os outros. (Gál 6:1; Ef 4:1-3; Col 3:12) Visto que a brandura é um dos aspectos do fruto do espírito de Deus, é necessário mais do que simples força de vontade para desenvolver essa qualidade. Para cultivar a brandura, os cristãos precisam se achegar a Deus, orar pedindo espírito santo e agir de acordo com a influência desse espírito. Ser brando não significa ser covarde ou fraco. Na verdade, praýtes passa a ideia de mansidão combinada com poder ou de força sob controle. Uma palavra grega relacionada (praýs) é traduzida como “de temperamento brando” e “brando”. (Mt 21:5; 1Pe 3:4) Jesus, que jamais poderia ser considerado alguém fraco, descreveu a si mesmo em Mt 11:29 como uma pessoa de temperamento brando. — Veja Mt 5:5 e a nota de estudo.
- *autodomínio*: A palavra grega traduzida aqui como “autodomínio” aparece quatro vezes nas Escrituras Gregas Cristãs. (At 24:25; 2Pe 1:6) Essa qualidade já foi definida como “controle das próprias emoções, impulsos ou desejos”. O verbo grego relacionado aparece em 1Co 9:25 (veja a nota de estudo), onde Paulo diz o seguinte sobre as competições de atletismo: “Todos os que participam numa competição exercem autodomínio em todas as coisas.” Esse mesmo verbo grego foi usado na Septuaginta em Gên 43:31, que diz que José ‘se controlou’. O verbo hebraico que aparece no texto original de Gên 43:31 também foi usado em Is 42:14, onde Isaías cita Jeová dizendo: “Me contive.” Em vez de punir imediatamente os maus, Jeová tem dado tempo para que eles abandonem seu comportamento errado e, assim, possam ter o favor dele. — Je 18:7-10; 2Pe 3:9.
- *Contra tais coisas não há lei*: Não existe nenhuma lei que limite o quanto os cristãos podem cultivar as qualidades produzidas pelo espírito de Deus. Todas essas qualidades estão em perfeita harmonia com a lei do amor, que pode ser vista tanto na Lei mosaica (Le 19:18; De 6:5) como na “lei do Cristo” (Gál 6:2; Jo 13:34). A palavra grega traduzida aqui como “tais coisas” também pode passar a ideia de “coisas como essas”. Isso indica que o fruto do espírito de Jeová não inclui apenas as nove qualidades citadas aqui em Gálatas. A personalidade cristã é formada por essas e outras qualidades, e todas elas são produzidas com a ajuda do espírito santo. — Ef 4:24, 32; 5:9; Col 3:12-15; Tg 3:17, 18.
====

[[v48-5-24]]

^<<v48-5-24,24>>^ Além disso, os que pertencem a Cristo Jesus pregaram na estaca a carne com as suas paixões e desejos.

[TIP]
====
- *pregaram na estaca*: O verbo grego que aparece aqui é stauróo. Nos Evangelhos, esse verbo é usado para falar da execução de Jesus Cristo. Mas, aqui, Paulo usa stauróo em sentido figurado. (Compare com a nota de estudo em Ro 6:6.) Ao usar esse verbo, Paulo mostra que os cristãos precisam tomar medidas drásticas e definitivas para fazer morrer a carne, ou seja, a natureza pecaminosa dos humanos. Quando um cristão consegue dominar as “paixões e desejos” da “carne”, é como se esses desejos tivessem morrido e não tivessem mais poder sobre ele. (Gál 5:16) As palavras de Paulo aqui estão ligadas ao que ele tinha dito nos versículos anteriores. Elas destacam que os que pertencem a Cristo precisam abandonar completamente “as obras da carne” mencionadas em Gál 5:19-21.
====

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos por espírito, continuemos também andando^&#42;1^ de acordo com o espírito.

[NOTE]
====
. Ou: “andando ordeiramente”.
====

[[v48-5-26]]

^<<v48-5-26,26>>^ Não nos tornemos presunçosos, atiçando competição uns contra os outros, invejando uns aos outros.

[TIP]
====
- *Não nos tornemos presunçosos*: Depois de fazer um contraste entre “as obras da carne” e “o fruto do espírito” (Gál 5:19-23), Paulo dá aqui mais um conselho aos gálatas. A palavra grega traduzida neste versículo como “presunçosos” é kenódoxos. Esta é a única vez que essa palavra aparece nas Escrituras Gregas Cristãs. O sentido literal dela é o de “glória vã; glória vazia”. Um léxico define kenódoxos como “aquele que tem um conceito exagerado de si mesmo, presunçoso, arrogante”. Assim, a palavra passa a ideia de que a pessoa tem um forte desejo de receber elogios por realizações sem valor ou importância. Uma palavra grega relacionada foi traduzida como “presunção” em Fil 2:3.
- *atiçando competição uns contra os outros*: Ou: “forçando uns aos outros a um confronto”. De acordo com um léxico, a palavra grega traduzida aqui como “atiçar competição” significa literalmente “chamar para frente, frequentemente com intenções hostis; provocar; desafiar”. Outro léxico define essa palavra como “desafiar para um combate ou competição”.
====

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]