include::./index.adoc[]

[[v48-6-0]]
=== Aos Gálatas, 6
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* D. PAULO EXPLICA O QUE A LIBERDADE CRISTÃ SIGNIFICA (4:21–6:10)
* Paulo usa um drama simbólico para explicar a liberdade cristã (4:21–5:1)
* Insistir na circuncisão não traz liberdade (5:2-12)
* A luta contínua entre carne e espírito (5:13-26)
* Cumprir a lei do Cristo envolve levar os fardos uns dos outros (6:1-6)
* Cada um colherá aquilo que semear (6:7-10)
* E. COMENTÁRIOS FINAIS (6:11-18)
* Paulo está escrevendo com sua própria mão (6:11)
* A circuncisão não é importante; o que importa é ser uma nova criação (6:12-16)
* Paulo, um escravo genuíno de Jesus, deseja que os gálatas mostrem o espírito correto (6:17, 18)
****

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, mesmo que um homem, sem perceber, dê um passo em falso, vocês que têm qualificações espirituais tentem reajustar esse homem num espírito de brandura. Mas olhe cada um para si mesmo, para que não seja tentado também.

[TIP]
====
- *um passo em falso*: A palavra grega que aparece aqui é paráptoma. Ela significa literalmente “queda ao lado” e pode se referir a qualquer tipo de falha, desde uma decisão equivocada até um pecado grave contra a lei de Deus. (Mt 6:14; Ro 5:15, 17; Ef 1:7; 2:1, 5) A pessoa que dá um passo em falso não está andando nos caminhos justos de Deus. Em vez disso, ela está indo na direção errada, mesmo que ainda não tenha cometido um pecado grave.
- *vocês que têm qualificações espirituais*: Ou: “vocês que são espirituais (espiritualmente maduros)”. A palavra grega traduzida aqui como “que têm qualificações espirituais” (pneumatikós) está relacionada com a palavra grega para “espírito” (pneúma), que é usada na expressão “espírito santo [ou: “força ativa”] de Deus”. (Ef 4:30) Para que um cristão maduro esteja qualificado para reajustar outros na congregação, não basta que ele tenha conhecimento, sabedoria e experiência. Também deve ficar claro que ele sempre se deixa guiar pelo espírito santo de Deus. — Gál 5:16, 18, 25.
- *tentem reajustar*: O verbo grego que aparece aqui, katartízo, passa a ideia de restaurar algo a uma condição correta, colocar algo no alinhamento correto. Neste versículo, esse verbo foi usado para se referir à necessidade de reajustar em sentido espiritual um irmão que ‘deu um passo em falso’. O verbo katartízo aparece aqui em uma forma que pode passar a ideia de “tentar reajustar”. Isso indica que, por mais que os irmãos “que têm qualificações espirituais” façam o seu melhor para ajudar a pessoa a voltar para o caminho correto, o sucesso desse reajuste depende de ela aceitar os conselhos que recebeu. O mesmo verbo foi usado em Mt 4:21, para falar de “consertar” redes. O substantivo relacionado katartismós, traduzido como “reajustamento” em Ef 4:12, era usado às vezes em textos médicos para se referir a colocar um osso, um membro ou uma articulação no lugar. — Veja as notas de estudo em 2Co 13:9; Ef 4:12.
- *olhe cada um para si mesmo*: Ou: “preste atenção a si mesmo; tome cuidado”. No início do versículo, Paulo dirigiu suas palavras a todos os que tinham qualificações espirituais, mas aqui ele muda seu foco e passa a se dirigir a eles individualmente. Paulo mostra que o cristão que aconselha outros precisa tomar bastante cuidado para não acabar caindo nas mesmas tentações que ele aconselha outros a evitar. Essas palavras também são um alerta para que o cristão não se considere melhor ou mais justo do que os outros. — 1Co 10:12.
====

[[v48-6-2]]

^<<v48-6-2,2>>^ Continuem levando os fardos uns dos outros e, dessa maneira, vocês cumprirão a lei do Cristo.

[TIP]
====
- *Continuem levando os fardos uns dos outros*: A palavra grega traduzida aqui como “fardos” é o plural de báros. Neste versículo, ela significa literalmente “coisas pesadas” e também poderia ser traduzida como “coisas aflitivas”. Logo antes de dizer estas palavras, Paulo tinha falado sobre a importância de tentar reajustar quem desse “um passo em falso” em sentido espiritual. As consequências do erro podem ser como um fardo, ou seja, pesadas demais para que a pessoa consiga carregar sem ajuda. Quando um cristão cria o hábito de ajudar seus irmãos a carregarem seus fardos, ele mostra amor e, assim, cumpre a lei do Cristo. (Jo 13:34, 35) Mas, como explicam os versículos 3 a 5, isso não significa levar a “carga” (em grego, fortíon) deles, ou seja, as responsabilidades cristãs que Deus espera que seus servos cumpram individualmente. — Veja a nota de estudo em Gál 6:5.
- *a lei do Cristo*: Esta lei inclui não apenas aquilo que Jesus ensinou, mas também as coisas que o espírito santo de Deus orientou os seguidores de Cristo a registrar nas Escrituras Gregas Cristãs. Assim como Jeremias tinha predito, essa lei substituiu o pacto da Lei mosaica. (Je 31:31-34; He 8:6-13) Apesar de ser chamada de “a lei do Cristo”, as leis e princípios que fazem parte dela foram criados pelo grandioso Legislador, Jeová. (Jo 14:10) Essa é a única vez que a expressão “a lei do Cristo” aparece nas Escrituras Gregas Cristãs, mas uma expressão parecida, “lei para com Cristo”, foi usada em 1Co 9:21. Essa lei também é chamada de “lei perfeita que pertence à liberdade” (Tg 1:25), “lei de um povo livre” (Tg 2:12) e “lei da fé”. — Ro 3:27.
====

[[v48-6-3]]

^<<v48-6-3,3>>^ Pois, se alguém acha que é alguma coisa, quando não é nada, está enganando a si mesmo.

[[v48-6-4]]

^<<v48-6-4,4>>^ Mas examine cada um suas próprias ações, e então terá motivo para se alegrar apenas com respeito a si mesmo, e não em comparação com outra pessoa.

[[v48-6-5]]

^<<v48-6-5,5>>^ Pois cada um levará a sua própria carga.

[TIP]
====
- *a sua própria carga*: Ou: “a sua própria carga de responsabilidade”. A palavra grega traduzida aqui como “carga” é fortíon. Ela se refere a algo que precisa ser carregado, sem fazer nenhuma referência ao seu peso. Essa “carga” é diferente dos “fardos” mencionados no versículo 2, que a pessoa talvez precise de ajuda para carregar. (Veja a nota de estudo.) Aqui, fortíon se refere às responsabilidades cristãs que Deus espera que cada um de seus servos cumpra. Uma obra de referência diz o seguinte sobre essa palavra grega: “Ela era usada como um termo militar para se referir à mochila de um homem ou ao equipamento de um soldado.”
====

[[v48-6-6]]

^<<v48-6-6,6>>^ Além disso, todo aquele a quem a palavra estiver sendo ensinada, partilhe todas as coisas boas com quem lhe ensina.

[TIP]
====
- *a quem a palavra estiver sendo ensinada*: Aqui, a expressão “a palavra” se refere à palavra de Deus e aos ensinamentos de Jesus Cristo. Em suas cartas, Paulo dá bastante destaque ao ensino dentro da congregação cristã. Ao fazer isso, ele muitas vezes usa o verbo grego didásko, que se refere a instruir, explicar, dar argumentos convincentes e provar o que se diz. (Ro 2:21; 12:7; 1Co 4:17; Col 3:16; 2Ti 2:2; veja a nota de estudo em Mt 28:20.) Mas, neste versículo, Paulo usa um verbo mais específico, katekhéo, tanto ao falar de quem está sendo ensinado quanto ao falar de quem está ensinando. Esse verbo significa literalmente “fazer ressoar” e às vezes pode incluir a ideia de instruir oralmente. (Veja a nota de estudo em At 18:25.) Depois que as verdades da palavra “ressoam” na mente e no coração de alguém, ou seja, tocam profundamente sua mente e coração, ele se torna qualificado para ensinar outros. — 2Ti 2:2.
- *partilhe todas as coisas boas com quem lhe ensina*: Aqui, Paulo incentiva “aquele a quem a palavra estiver sendo ensinada” a partilhar tanto coisas materiais como espirituais com seu instrutor. Esse mesmo princípio aparece em vários outros versículos das Escrituras. (Mt 10:9, 10; Ro 15:27 e a nota de estudo; 1Co 9:11, 13, 14; 1Ti 5:17, 18; He 13:16) A palavra grega traduzida aqui como “partilhar” também pode passar a ideia de “participar” em algo. Quando um estudante escuta e aplica as coisas que seu instrutor lhe ensina, ele passa a expressar nas suas próprias palavras a sua fé e convicção. Assim, ele também se torna um instrutor das boas novas. Dessa forma, o estudante participa com seu instrutor em “coisas boas”. — 2Ti 2:2.
====

[[v48-6-7]]

^<<v48-6-7,7>>^ Não se enganem: de Deus não se zomba. Pois o que a pessoa semear, isso também colherá;

[TIP]
====
- *se zomba*: A palavra grega que aparece aqui se refere literalmente a fazer um movimento com o nariz para indicar desprezo. Algo equivalente, em algumas culturas, seria torcer o nariz para alguém ou sorrir de maneira sarcástica. Em sentido figurado, a palavra pode se referir a falar coisas que mostram desprezo ou que ridicularizam alguém, talvez chegando a ponto de desafiar essa pessoa. Aqui, Paulo deixa claro que é perigoso desprezar os princípios da Palavra de Deus ou achar que é possível desconsiderá-los sem sofrer consequências.
- *o que a pessoa semear, isso também colherá*: O provérbio que Paulo cita aqui era bem conhecido nos seus dias. Pelo visto, ele teve origem em sociedades agrícolas da antiguidade. Esse provérbio expressa um fato: aquilo que se planta no solo é o que vai crescer. Nos tempos antigos, esse provérbio geralmente era aplicado com um sentido negativo, indicando que a pessoa colheria consequências ruins se fizesse coisas erradas. Mas, no versículo seguinte, Paulo mostra que o provérbio também pode ter uma aplicação positiva, ou seja, fazer coisas boas pode trazer uma consequência muito boa, a “vida eterna”. (Gál 6:8) Esse princípio imutável também aparece em outras partes da Bíblia. — Pr 11:18; 22:8; Os 8:7; 10:12; 2Co 9:6; veja as notas de estudo em Gál 6:8.
====

[[v48-6-8]]

^<<v48-6-8,8>>^ porque aquele que semeia visando a sua carne colherá da carne destruição,^&#42;1^ mas aquele que semeia visando o espírito colherá do espírito vida eterna.

[NOTE]
====
. Lit.: “corrupção”.
====

[TIP]
====
- *aquele que semeia visando a sua carne*: Aqui, Paulo está se referindo a uma pessoa que se entrega às “obras da carne”, que são resultado dos desejos errados ligados à imperfeição humana. (Gál 5:19-21) O fruto, ou a consequência, de se ‘semear visando a carne’ é colher da carne destruição. Quando o primeiro humano pecou, ele e seus descendentes se tornaram escravos da decadência, que levou à imperfeição. (Ro 5:12; 8:21 e a nota de estudo) Essa escravidão causa não apenas doença, envelhecimento e morte, mas também decadência moral e espiritual. Assim, “aquele que semeia visando a sua carne” não receberá a vida eterna. — Compare com 2Pe 2:12, 18, 19.
- *aquele que semeia visando o espírito*: Aqui, Paulo está se referindo a uma pessoa que vive de um modo que permite que o espírito santo atue livremente em sua vida. Com essa ajuda, ela consegue ter qualidades que fazem parte do fruto do espírito. Esse tipo de pessoa “colherá do espírito vida eterna”. — Mt 19:29; 25:46; Jo 3:14-16; Ro 2:6, 7; Ef 1:7.
====

[[v48-6-9]]

^<<v48-6-9,9>>^ Assim, não desistamos de fazer o que é bom, pois colheremos no tempo devido, se não desanimarmos.

[TIP]
====
- *desistamos*: Ou: “desanimemos”. A palavra grega que aparece aqui também pode passar a ideia de desanimar ou perder o entusiasmo. — Veja a nota de estudo em 2Co 4:1.
====

[[v48-6-10]]

^<<v48-6-10,10>>^ Então, enquanto tivermos oportunidade, façamos o bem a todos, mas especialmente aos que fazem parte da nossa família na fé.

[TIP]
====
- *tivermos oportunidade*: Ou: “a época for favorável”. A palavra grega que aparece aqui, kairós, é às vezes traduzida como “época” ou “tempo determinado”. Essa palavra aparece em Ef 5:16 (veja a nota de estudo), onde Paulo fala sobre usar o “tempo do melhor modo possível”.
- *aos que fazem parte da nossa família na fé*: Ou: “aos que pertencem à casa (família) da fé”. A palavra grega traduzida aqui como “que fazem parte da nossa família” era usada para se referir aos membros de uma casa, ou família, literal. (1Ti 5:8) No mundo greco-romano, a palavra “casa” também podia se referir a pessoas que faziam parte de um grupo unido que compartilhava as mesmas crenças, ideias ou objetivos. Essa palavra se aplica bem às congregações do século 1 d.C., já que os cristãos consideravam uns aos outros como irmãos em sentido espiritual (Ef 2:19) e geralmente usavam a casa de um deles para realizar suas reuniões. — Ro 16:3-5.
====

[[v48-6-11]]

^<<v48-6-11,11>>^ Vejam com que grandes letras^&#42;1^ lhes escrevi com a minha própria mão.

[NOTE]
====
. Ou, possivelmente: “com que carta comprida”.
====

[TIP]
====
- *lhes escrevi com a minha própria mão*: Paulo normalmente ditava suas cartas para um secretário. Mas, pelo visto, foi o próprio Paulo quem escreveu esta carta. — Veja Ro 16:22 e a nota de estudo.
====

[[v48-6-12]]

^<<v48-6-12,12>>^ Aqueles que querem causar uma boa impressão segundo padrões humanos são os que tentam obrigar vocês a ser circuncidados, e eles fazem isso só para não serem perseguidos por causa da estaca do Cristo.

[TIP]
====
- *que querem causar uma boa impressão segundo padrões humanos*: Lit.: “que querem mostrar uma boa aparência na carne”. Aqui, a palavra grega para “carne” está relacionada ao corpo físico e, por consequência, ao que pode ser visto por outros. Alguns que se diziam cristãos ensinavam que, para ter a aprovação de Deus, era necessário ser circuncidado e seguir a Lei mosaica. Mas o motivo real de eles ensinarem isso era o seu desejo de causar uma boa impressão aos judeus. Eles defendiam a circuncisão para “não serem perseguidos” pelos judeus que odiavam o cristianismo. Por se preocuparem demais com as aparências e insistirem em dizer que os cristãos deviam ser circuncidados, eles na verdade estavam negando que a morte de Jesus fosse a única base para a salvação.
- *da estaca*: Ou: “da estaca de tortura; da estaca de execução”. — Veja o Glossário.
- *da estaca do Cristo*: Aqui, a palavra “estaca” (em grego, staurós) foi usada para se referir à morte de Jesus na estaca. Jesus morreu dessa forma para que os humanos pudessem ser libertados da escravidão ao pecado, ser reconciliados com Deus e ter uma forte amizade com Ele. Paulo foi perseguido pelos judeus porque acreditava e proclamava que a morte de Jesus na estaca era a única base para a salvação.
====

[[v48-6-13]]

^<<v48-6-13,13>>^ Pois mesmo os que se submetem à circuncisão não cumprem a Lei, mas querem que vocês sejam circuncidados para que eles tenham motivo para se gabar do corpo de vocês.^&#42;1^

[NOTE]
====
. Lit.: “na carne de vocês”.
====

[[v48-6-14]]

^<<v48-6-14,14>>^ No entanto, que eu nunca me orgulhe de nada, a não ser da estaca do nosso Senhor Jesus Cristo; por meio dele o mundo, para mim, está morto, e eu estou morto para o mundo.

[TIP]
====
- *está morto*: Ou: “foi morto na estaca”. Paulo ensinava que a morte de Jesus na estaca era a base para a salvação. Por isso, o mundo odiava Paulo e o via como um criminoso que merecia estar “morto”. Para Paulo, por outro lado, era o mundo que estava condenado à morte.
====

[[v48-6-15]]

^<<v48-6-15,15>>^ Pois o que importa não é a circuncisão nem a incircuncisão, mas ser uma nova criação.

[TIP]
====
- *mas ser uma nova criação*: Cada cristão ungido é, individualmente, uma nova criação, ou seja, um filho de Deus gerado por espírito que tem a esperança de reinar com Cristo no céu. (Gál 4:6, 7) Além disso, os ungidos fazem parte da congregação cristã, “o Israel de Deus” (Gál 6:16 e a nota de estudo), que também é uma nova criação espiritual. (Veja a nota de estudo em 2Co 5:17.) Assim, para Deus não faz nenhuma diferença se um cristão é circuncidado ou não.
====

[[v48-6-16]]

^<<v48-6-16,16>>^ Que haja paz e misericórdia sobre todos os que vivem^&#42;1^ de acordo com essa regra, sim, sobre o Israel de Deus.

[NOTE]
====
. Ou: “andam ordeiramente”.
====

[TIP]
====
- *de acordo com essa regra*: A palavra grega kanón, traduzida aqui como “regra”, vem da palavra hebraica qanéh, que significa “cana”. No passado, a cana era usada como régua ou instrumento de medir. (Ez 40:5) Aqui, Paulo usa essa palavra em sentido figurado para se referir à “regra”, ou norma de conduta, que os que fazem parte do “Israel de Deus” deveriam usar para medir, ou avaliar, suas ações. Eles precisavam aceitar a bondade imerecida de Deus que tinha sido expressa por meio de Cristo e exercer fé nela, vivendo de uma forma que mostrasse isso. Assim, eles experimentariam “paz e misericórdia” num grau que até então era impossível para humanos pecadores. — Gál 3:24, 25; compare com o Glossário, “Cânon da Bíblia”.
- *o Israel de Deus*: Esta é a única vez que esta expressão aparece nas Escrituras. Ela se refere ao Israel espiritual, e não aos descendentes literais de Jacó, que mais tarde recebeu o nome de Israel. (Gên 32:22-28) O versículo anterior (Gál 6:15) mostra que Deus não exigia que os cristãos que faziam parte do “Israel de Deus” fossem circuncidados. O profeta Oseias predisse que Deus mostraria favor a um povo que incluiria não judeus. Deus disse: “Vou dizer aos que não são o meu povo: ‘Vocês são o meu povo.’” (Os 2:23; Ro 9:22-25) Apesar de o Israel espiritual incluir judeus e prosélitos (At 1:13-15; 2:41; 4:4), eles representavam “apenas um restante” daquela nação que tinha sido rejeitada (Is 10:21, 22; Ro 9:27). Paulo mais tarde escreveu aos romanos: “Nem todos os que são descendentes de Israel são realmente ‘Israel’.” — Ro 9:6; veja também as notas de estudo em At 15:14; Ro 2:29; 9:27; 11:26.
- *Israel*: O nome Israel significa “aquele que luta (persevera) com Deus; Deus luta”. Jacó recebeu esse nome depois de ter lutado com um anjo para receber uma bênção. Ao contrário de Esaú, Jacó tinha apreço pelas coisas sagradas e estava disposto a dar tudo de si para ter o favor de Deus. (Gên 32:22-28; He 12:16) Aqueles que fazem parte do “Israel de Deus” imitam a Jacó, mostrando a mesma fé e a mesma determinação que ele tinha em obedecer a Deus. — Veja a nota de estudo em o Israel de Deus neste versículo.
====

[[v48-6-17]]

^<<v48-6-17,17>>^ De agora em diante,^&#42;1^ que ninguém me cause dificuldades, pois trago no corpo as marcas de um escravo de Jesus.

[NOTE]
====
. Ou: “Por fim”.
====

[TIP]
====
- *as marcas de um escravo de Jesus*: A palavra grega traduzida aqui como “marcas de um escravo” é o plural de stígma. Esta é a única vez que essa palavra aparece nas Escrituras Gregas Cristãs. Na literatura grega, ela era usada para se referir a letras e símbolos que às vezes eram marcados a ferro quente nos escravos para identificar seu dono, mas ela também era usada para se referir a cicatrizes. Pode ser que aqui Paulo esteja se referindo a cicatrizes literais que ele talvez tivesse por causa do que sofreu às mãos de perseguidores e que seriam prova de que ele era um escravo fiel de Cristo. (2Co 4:10; 11:23-27; Fil 3:10) Mas também é possível que Paulo tenha usado a palavra stígma em sentido figurado. Ele talvez estivesse pensando em seu ministério, nas qualidades do fruto do espírito que demonstrava e em seu modo de vida. Essas coisas eram como marcas que o identificavam como um escravo que pertencia a Cristo.
====

[[v48-6-18]]

^<<v48-6-18,18>>^ Que a bondade imerecida do nosso Senhor Jesus Cristo esteja com o espírito que vocês mostram, irmãos. Amém.

[TIP]
====
- *com o espírito que vocês mostram*: Lit.: “com o espírito de vocês”. Neste contexto, a palavra “espírito” se refere à força interior ou maneira de pensar que leva a pessoa a dizer ou fazer as coisas de certo modo. Por exemplo, as Escrituras falam do “espírito calmo e brando” (1Pe 3:4) e do “espírito de brandura” (Gál 6:1). Em 2Ti 1:7, Paulo faz um contraste entre um espírito “de poder, de amor e de bom senso” e “um espírito de covardia”. E, ao concluir sua carta a Timóteo, Paulo diz: “O Senhor esteja com o espírito que você mostra.” (2Ti 4:22) Assim como uma pessoa pode mostrar um certo tipo de espírito, o mesmo pode acontecer com um grupo de pessoas. Tanto aqui em Gálatas como em Filipenses, Paulo usa em suas palavras finais o pronome “vocês” (plural). Ele queria que todos os cristãos dessas congregações continuassem unidos no mesmo espírito: um espírito que estivesse em harmonia com a vontade de Deus e com o exemplo deixado por Cristo. — Fil 4:23.
====

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]