include::./index.adoc[]

[[v50-4-0]]
=== Aos Filipenses, 4
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* F. O EXEMPLO DE PAULO PARA OS FILIPENSES (3:12–4:1)
* Esquecendo-se das coisas atrás, Paulo agora se estica para alcançar as coisas à frente (3:12-16)
* Aviso contra os “inimigos da estaca”; a verdadeira cidadania dos cristãos está nos céus (3:17–4:1)
* G. CONSELHO PARA SEREM UNIDOS E SE ALEGRAREM; O DEUS DE PAZ VAI DAR PAZ MENTAL (4:2-9)
* Evódia e Síntique aconselhadas a ter a mesma mentalidade no Senhor (4:2, 3)
* Alegrem-se no Senhor e sejam razoáveis; não fiquem ansiosos por causa de coisa alguma (4:4-7)
* Concentrem-se no que é justo, casto e amável; pratiquem as coisas que vocês aprenderam (4:8, 9)
* H. CONTENTAMENTO E GRATIDÃO DE PAULO (4:10-23)
* Paulo tem forças para todas as coisas graças ao poder de Deus (4:10-13)
* Paulo dá valor à generosidade dos filipenses; ele garante aos filipenses que eles terão as bênçãos de Deus (4:14-20)
* Saudações; Paulo deseja que os filipenses mostrem a disposição correta (4:21-23)
****

[[v50-4-1]]

^<<v50-4-1,1>>^ Portanto, meus irmãos, a quem eu amo e de quem tenho saudades, minha alegria e coroa, mantenham-se assim firmes no Senhor, meus amados.

[TIP]
====
- *no Senhor*: Neste contexto, o título “Senhor” poderia se referir tanto a Jeová Deus como a Jesus Cristo, já que aqui Paulo não usou o artigo definido em grego antes da palavra “Senhor”. No entanto, várias traduções das Escrituras Gregas Cristãs para o hebraico e outros idiomas usam o nome de Deus aqui, o que parece apoiar a ideia de que “Senhor” está se referindo a Jeová. — Veja também a nota de estudo em Fil 4:4.
====

[[v50-4-2]]

^<<v50-4-2,2>>^ Exorto Evódia e exorto Síntique a terem a mesma mentalidade no Senhor.

[TIP]
====
- *a terem a mesma mentalidade no Senhor*: A carta de Paulo aos filipenses está cheia de elogios e encorajamento. Mas, neste versículo, Paulo dá um conselho. Pelo visto, as duas irmãs cristãs mencionadas neste versículo, Evódia e Síntique, tiveram um desentendimento grave. O problema devia ser tão sério que ameaçava a paz e a união da congregação e chamou a atenção de Paulo, que estava bem distante, preso em Roma. O conselho de Paulo não dá a entender que essas duas irmãs não eram cristãs maduras. (Veja a nota de estudo em Fil 4:3.) Paulo sabia por experiência própria que até cristãos experientes podem ter desentendimentos. (At 15:37-39) Qualquer que fosse o problema entre essas duas irmãs, Paulo não ficou do lado nem de uma nem de outra. Em vez disso, ele amorosamente aconselhou as duas a serem unidas e a terem o mesmo modo de pensar, já que as duas amavam o Senhor. — Veja a nota de estudo em Jo 17:21.
====

[[v50-4-3]]

^<<v50-4-3,3>>^ E peço a você também, como meu verdadeiro colaborador, que persista em ajudar essas mulheres que se esforçaram lado a lado comigo pelas boas novas, junto com Clemente e também com os outros colaboradores meus, cujos nomes estão no livro da vida.

[TIP]
====
- *verdadeiro colaborador*: A expressão “verdadeiro colaborador” traduz uma expressão grega que literalmente significa “genuíno companheiro de jugo”. Aqui, Paulo está falando com um cristão da congregação em Filipos que a Bíblia não menciona o nome. Mas é a ele que o apóstolo pede para ajudar Evódia e Síntique a ter “a mesma mentalidade no Senhor” e resolver o desentendimento que tinham. (Veja a nota de estudo em Fil 4:2.) É interessante notar que Paulo, que era um apóstolo designado por Jesus Cristo, via a si mesmo como um colaborador dos seus irmãos cristãos, não como o senhor deles. (At 9:15; Ro 11:13) Em vez de dominar a congregação, Paulo seguia as palavras de Cristo: “Todos vocês são irmãos.” — Mt 23:8; 1Pe 5:3; veja a nota de estudo em 2Co 1:24.
- *que se esforçaram lado a lado*: Ou: “que lutaram arduamente lado a lado”. Parece que Evódia e Síntique tiveram um desentendimento, e a congregação ficou sabendo disso. Apesar desse problema entre elas, Paulo elogiou essas duas irmãs por terem trabalhado com ele na pregação das boas novas. Para falar da ajuda que essas irmãs deram para ele, Paulo usou aqui o mesmo verbo grego de Fil 1:27, onde esse verbo também transmite a ideia de se esforçar junto de; trabalhar duro lado a lado; cooperar de coração com.
- *cujos nomes estão no livro da vida*: Esse livro é um livro de recordação simbólico de Deus. Ele é uma garantia amorosa de que os servos fiéis que têm seu nome nesse livro estão na memória perfeita de Deus e de que ele vai recompensá-los com a vida eterna, quer na Terra quer no céu. (Ap 3:5; 20:15) A forma como a expressão “livro da vida” é usada nas Escrituras Hebraicas mostra que existem condições para uma pessoa continuar com o seu nome escrito nesse livro e receber a prometida recompensa: ela precisa permanecer fiel e obediente. (Êx 32:32, 33; Sal 69:28, nota de rodapé; Mal 3:16) Antes de falar desse livro, Paulo tinha mencionado Evódia e Síntique, duas irmãs ungidas e zelosas da congregação em Filipos que estavam tendo algum tipo de desentendimento. Mesmo assim, Paulo as menciona junto com outros de seus colaboradores como estando incluídas nesse livro simbólico. Paulo não achava que elas perderiam sua prometida recompensa por causa de pequenos erros e imperfeições. Se elas continuassem fiéis até o fim, seriam recompensadas. (Veja também 2Ti 2:11, 12.) Visto que Filipos era uma colônia romana, a ideia de ter nomes escritos em um livro talvez tenha lembrado os cristãos ali do registro público da cidade, que trazia os nomes daqueles que tinham cidadania romana.
====

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrem-se sempre no Senhor. Novamente direi: Alegrem-se!

[TIP]
====
- *Alegrem-se sempre no Senhor*: Paulo novamente incentiva os filipenses a ‘se alegrar no Senhor’. (Veja a nota de estudo em Fil 3:1.) É verdade que neste contexto o título “Senhor” poderia se referir tanto a Jeová Deus como a Jesus Cristo. Mas, pelo visto, Paulo aqui está se referindo a conselhos parecidos encontrados nas Escrituras Hebraicas e que se relacionam a Jeová. — Sal 32:11; 97:12.
====

[[v50-4-5]]

^<<v50-4-5,5>>^ Que a sua razoabilidade seja conhecida de todos os homens. O Senhor está perto.

[TIP]
====
- *razoabilidade*: A palavra grega traduzida como “razoabilidade” é bem abrangente e transmite a ideia de estar disposto a ceder, ser educado ou ser tolerante. A pessoa que tem essa qualidade não fica insistindo em aplicar a lei ao pé da letra nem fica exigindo os seus direitos. Em vez disso, ela está disposta a se adaptar às circunstâncias e se esforça para ser gentil e mostrar consideração por outros. Essa qualidade do cristão deve ser conhecida por todos os homens, ou seja, até mesmo por pessoas de fora da congregação. Uma Bíblia traduz essa parte do versículo da seguinte maneira: “Tenha a reputação de ser razoável.” Embora todos os cristãos se esforcem para ter essa qualidade, isso é especialmente necessário para os superintendentes na congregação. — 1Ti 3:3; Tit 3:2; Tg 3:17; veja a nota de estudo em 2Co 10:1.
- *O Senhor está perto*: Neste contexto, o título “Senhor” poderia se referir tanto a Jeová Deus como a Jesus Cristo. Mas, pelo visto, Paulo aqui está fazendo referência a declarações parecidas encontradas nas Escrituras Hebraicas e que se referem a Jeová, como por exemplo, as palavras do Sal 145:18: “Jeová está perto de todos os que o invocam.” (Veja também Sal 34:18.) Deus se achega a todos que se achegam a ele. Ele está perto dos seus servos no sentido de que ouve as orações deles e os protege. (At 17:27; Tg 4:8) Saber disso pode ajudar os cristãos a se alegrar e a ser razoáveis; a não ficar ansiosos demais, como mostra Fil 4:6. Deus também está perto no sentido de que em breve ele vai substituir este velho sistema por um novo mundo governado pelo seu Reino. (1Jo 2:17) Algumas traduções das Escrituras Gregas Cristãs para o hebraico e outros idiomas usam o nome de Deus neste versículo.
====

[[v50-4-6]]

^<<v50-4-6,6>>^ Não fiquem ansiosos por causa de coisa alguma, mas em tudo, por orações e súplicas, junto com agradecimentos, tornem os seus pedidos conhecidos a Deus;

[TIP]
====
- *Não fiquem*: A expressão grega traduzida aqui como “Não fiquem ansiosos” também pode ser traduzida como “Parem de estar ansiosos” ou “Parem de se preocupar tanto”. — Veja a nota de estudo em Lu 12:22.
- *Não fiquem ansiosos*: O verbo grego traduzido aqui como ‘ficar ansiosos’ (merimnáo) pode indicar uma preocupação excessiva ou o tipo de ansiedade que divide e distrai a mente da pessoa, tirando sua alegria. Jesus também disse várias vezes para seus discípulos não ficarem ansiosos ou não se preocuparem tanto. (Veja as notas de estudo em Mt 6:25; Lu 12:22.) Paulo tinha vários motivos para ficar ansioso. Por exemplo, ele escreveu esta carta enquanto estava preso pela primeira vez em Roma. (Fil 1:7, 13, 14) Além disso, ele podia estar preocupado com passar necessidade (Fil 4:12) e com o bem-estar dos seus companheiros cristãos. (2Co 11:28 e a nota de estudo.) Paulo incentivou seus irmãos a, em qualquer circunstância, ‘tornar os pedidos deles conhecidos a Deus’. — Veja também Sal 55:2, 22; 1Pe 5:7.
- *em tudo*: Qualquer coisa que afete a amizade de um cristão com Deus ou a vida dele como servo de Deus pode ser assunto de oração. Além disso, nossas orações podem incluir praticamente qualquer outro assunto que esteja em harmonia com a vontade de Deus. Um cristão pode se sentir à vontade para falar com Jeová sobre suas necessidades, medos, ansiedades e sentimentos mais profundos. — Mt 6:9-13; Jo 14:13 (veja a nota de estudo), 14; 16:23, 24; 1Pe 5:7; 1Jo 5:14.
- *orações e súplicas, junto com agradecimentos*: A palavra grega para “oração” é um termo bem abrangente e se refere a falar com Deus como forma de adoração. As “súplicas” são mais específicas; essa é uma palavra forte que indica um apelo sincero e fervoroso, normalmente acompanhado de emoções intensas e até mesmo de lágrimas. (He 5:7) Uma obra de referência diz que “súplica” é quando uma pessoa ‘implora por uma necessidade pessoal’. Por dizer “junto com agradecimentos”, Paulo mostrou que sempre é apropriado agradecer a Deus. Mesmo em épocas de muita necessidade, existem razões para mostrar gratidão, e Paulo sabia disso por experiência própria. (At 16:22-25; Ef 5:19, 20) Paulo também falou de pedidos, se referindo às coisas que um cristão pode pedir em oração. Ele tinha acabado de explicar que esses pedidos podem ser sobre praticamente qualquer necessidade. — Veja a nota de estudo em tudo neste versículo.
====

[[v50-4-7]]

^<<v50-4-7,7>>^ e a paz de Deus, que está além de toda compreensão,^&#42;1^ guardará o seu coração e a sua mente por meio de Cristo Jesus.

[NOTE]
====
. Ou: “que supera todo pensamento”.
====

[TIP]
====
- *a paz de Deus*: A expressão “a paz de Deus” se refere à calma e à tranquilidade que um cristão sente por causa da sua preciosa amizade com Jeová Deus. Um cristão pode sentir essa paz mesmo enfrentando situações difíceis e provadoras. Não é possível conseguir “a paz de Deus” por meio de mera meditação ou algum esforço pessoal; ela é dada pelo próprio Jeová Deus, “o Deus de paz”. (Fil 4:9; Núm 6:26; Sal 4:8; 29:11; Ro 15:33; veja a nota de estudo em Gál 5:22.) Para se conseguir “a paz de Deus”, é necessário ter uma amizade achegada com Jeová e fazer o que é certo aos olhos dele. (Pr 3:32) Jeová dá para os seus servos a certeza de que conhece suas necessidades e circunstâncias e de que responde suas orações. Ter essa certeza dá para o cristão paz na mente e no coração. — Sal 34:18; 94:14; 2Pe 2:9; veja a nota de estudo em guardará neste versículo.
- *que está além de toda compreensão*: A paz de Deus não pode ser obtida por meio de raciocínio ou planejamento humano. Na verdade, ter mais “compreensão” de uma situação pode levar a mais ansiedade e aflição. (Ec 1:18) No entanto, a paz de Deus “está além” de tudo o que os humanos podem imaginar. Pode ser que um servo de Deus não veja saída para os seus problemas. É verdade que Deus pode agir de forma inesperada e salvar seus servos de uma provação. (Mr 10:27; 2Pe 2:9) Mas há situações em que tudo o que se pode fazer é perseverar com paciência. (Tg 5:11) Mesmo em situações assim, Jeová sempre vai dar sua paz para os que confiam totalmente nele. (Is 26:3) Aqueles que não conhecem a Jeová não conseguem entender plenamente como o povo de Deus pode ter paz e tranquilidade mesmo enfrentando sérios problemas, agressões físicas ou, até mesmo, a morte.
- *guardará*: O verbo grego traduzido aqui como ‘guardar’ é um termo militar. Ele podia se referir a um soldado ou a um grupo de soldados que tinha a tarefa de proteger uma cidade fortificada. (2Co 11:32) Aqui e em outros lugares das Escrituras Gregas Cristãs, ele é usado em sentido figurado. (Gál 3:23; 1Pe 1:5) Filipos era uma cidade militar, e seus habitantes podiam dormir tranquilos porque sabiam que soldados protegiam os portões da cidade. De maneira similar, “a paz de Deus” guarda, ou protege, o coração e a mente dos cristãos fiéis. Dessa forma, eles podem ter paz mental e segurança espiritual, ou seja, proteção para que sua forte amizade com Deus não seja abalada. Eles sabem que Jeová cuida deles e quer o seu melhor. (Sal 4:8; 145:18; 1Co 10:13; 1Pe 5:10) Por isso, eles não ficam excessivamente ansiosos ou desanimados. — Veja a nota de estudo em a paz de Deus neste versículo.
- *seu coração*: Quando a Bíblia usa a palavra “coração” em sentido figurado, normalmente se refere a tudo o que uma pessoa é por dentro, incluindo seus pensamentos, sentimentos e atitudes. Mas, quando a palavra “coração” é usada junto com “mente”, ou “faculdades mentais”, ela pelo visto assume um significado mais específico e se refere principalmente às emoções, desejos e motivações da pessoa. — Veja a nota de estudo em Mt 22:37.
- *sua mente*: Ou: “suas faculdades mentais; seus pensamentos”. A palavra grega que Paulo usou aqui se refere à capacidade de raciocínio de uma pessoa. Ela é traduzida como “mente” em 2Co 3:14; 4:4; 11:3 e como “pensamento” em 2Co 10:5. Por mencionar tanto o “coração” como a “mente”, Paulo destaca que “a paz de Deus” guarda, ou protege, tudo o que um cristão é por dentro, incluindo seus pensamentos, sentimentos, atitudes e motivações.
- *por meio de Cristo Jesus*: Os cristãos só podem receber a paz de Deus se tiverem fé em Jesus e entenderem o papel dele no propósito de Deus. Isso porque é o sacrifício de resgate de Jesus que abre o caminho para o perdão de pecados, o que permite ter uma amizade achegada com Jeová. Essa amizade é a base para a verdadeira paz na mente e no coração. (At 3:19; Gál 1:3-5; 1Jo 2:12) Os cristãos também podem ter paz por lembrar que Jesus, como Rei do Reino de Deus, vai acabar com todo o sofrimento causado por Satanás e seu sistema. (Is 65:17; 1Jo 3:8; Ap 21:3, 4) Além disso, Jesus prometeu estar com os seus discípulos, dando a eles ajuda mesmo durante os últimos dias deste sistema. Isso contribui para a paz mental deles. — Mt 28:19, 20; Fil 1:18, 19.
====

[[v50-4-8]]

^<<v50-4-8,8>>^ Por fim, irmãos, tudo^&#42;1^ que é verdadeiro, tudo que é de séria preocupação, tudo que é justo, tudo que é casto, tudo que é amável, tudo de que se fala bem, tudo que é virtuoso e tudo que é digno de louvor, continuem a considerar essas coisas.

[NOTE]
====
. Lit.: “todas (as coisas)”.
====

[TIP]
====
- *justo*: Veja o Glossário, “Justiça”.
- *casto*: Ou: “puro”. A palavra grega traduzida aqui como “casto” significa ser puro e santo não só na conduta (sexual ou de outro tipo), mas também nos pensamentos e nas motivações. — Sal 24:3, 4; Ef 5:3; 1Ti 4:12; 5:2; Tg 3:17; 1Pe 3:2.
- *continuem a considerar*: A palavra grega traduzida aqui como “continuem a considerar” transmite a ideia de “pensar sobre”; “meditar em”; “ficar pensando em”. O tempo verbal que Paulo usou indica uma ação contínua. Por isso, outras traduções da Bíblia dizem “nunca parem de pensar sobre” ou “encham a mente de vocês com” os assuntos alistados por Paulo. Pensar nessas coisas positivas vai motivar o cristão a agir, influenciando assim o seu modo de vida. — Fil 4:9.
====

[[v50-4-9]]

^<<v50-4-9,9>>^ Pratiquem as coisas que vocês aprenderam, receberam e ouviram de mim, bem como o que me viram fazer, e o Deus de paz estará com vocês.

[[v50-4-10]]

^<<v50-4-10,10>>^ Eu me alegro muito no Senhor de que agora, por fim, vocês renovaram o seu interesse por mim. Embora vocês se preocupassem comigo, faltava-lhes a oportunidade de demonstrar isso.

[TIP]
====
- *no Senhor*: Neste contexto, o título “Senhor” poderia se referir tanto a Jeová Deus como a Jesus Cristo, já que aqui Paulo não usou o artigo definido em grego antes da palavra “Senhor”. No entanto, várias traduções das Escrituras Gregas Cristãs para o hebraico e outros idiomas usam o nome de Deus aqui, o que parece apoiar a ideia de que “Senhor” está se referindo a Jeová. — Veja a nota de estudo em Fil 4:4.
====

[[v50-4-11]]

^<<v50-4-11,11>>^ Não estou dizendo isso por estar passando necessidade, pois aprendi a ter contentamento em qualquer circunstância.

[TIP]
====
- *contentamento*: As palavras gregas traduzidas como “contentamento” (Fil 4:11; 1Ti 6:6) ou “autossuficientes” (2Co 9:8) podem transmitir duas ideias: (1) estar contente e satisfeito com o que se tem; (2) ter o suficiente, sem ter que ficar dependendo de outros. Paulo aprendeu por experiência própria a se adaptar a qualquer circunstância que encontrasse durante suas viagens. Ele tinha contentamento e ficava feliz com qualquer designação que Jeová desse para ele. (Fil 4:12, 13) Paulo imitava a Jesus, que não quis acumular riquezas ou alcançar estabilidade na vida. (Mt 8:20) Assim como Jesus, Paulo se concentrou em fazer a vontade de Deus e confiou que Jeová cuidaria de suas necessidades básicas. — He 13:5.
====

[[v50-4-12]]

^<<v50-4-12,12>>^ Eu sei viver com pouco e sei viver com muito. Em tudo e em todas as circunstâncias aprendi o segredo tanto de estar saciado como de ter fome, tanto de ter fartura como de passar necessidade.

[[v50-4-13]]

^<<v50-4-13,13>>^ Para todas as coisas tenho forças graças àquele que me dá poder.

[[v50-4-14]]

^<<v50-4-14,14>>^ Contudo, vocês fizeram bem em me ajudar na minha aflição.

[[v50-4-15]]

^<<v50-4-15,15>>^ De fato, vocês, filipenses, também sabem que, depois de vocês terem ouvido as boas novas pela primeira vez, quando parti da Macedônia, nenhuma congregação tomou parte comigo na questão de dar e receber, a não ser vocês;

[TIP]
====
- *Macedônia*: Veja o Glossário.
- *na questão de dar e receber*: A expressão grega traduzida como “dar e receber” normalmente era usada em transações comerciais para transmitir a ideia de “débitos e créditos”. Com certeza, Paulo estava se referindo à ajuda financeira que tinha recebido dos cristãos de Filipos. A ajuda material que aqueles irmãos enviaram para o apóstolo era uma forma de agradecer por toda a ajuda e instrução espirituais que Paulo tinha dado para eles. (Veja também 1Co 9:11.) Desde o início da congregação em Filipos, quando Lídia foi muito hospitaleira com Paulo e seus companheiros, os filipenses ganharam a reputação de ser generosos. (At 16:14, 15) A congregação em Filipos enviou recursos financeiros para ajudar Paulo em seu ministério em pelo menos quatro ocasiões. A mais recente delas foi quando enviaram recursos por meio de Epafrodito, enquanto Paulo estava preso em Roma. Essa foi uma das razões de Paulo ter escrito esta carta. (2Co 11:9; Fil 4:14, 16, 18) Em suas cartas, Paulo elogiou várias congregações por sua generosidade, o que incentivou todos os discípulos a desenvolver esse mesmo espírito. — Ro 15:26; 2Co 8:1-6.
====

[[v50-4-16]]

^<<v50-4-16,16>>^ pois, enquanto eu estava em Tessalônica, vocês me enviaram algo para as minhas necessidades não só uma vez, mas duas.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não é que eu esteja buscando ganhar presentes, mas busco o fruto que resulta em mais crédito para a sua conta.

[[v50-4-18]]

^<<v50-4-18,18>>^ No entanto, tenho tudo de que preciso, e até mais do que isso. Estou suprido, agora que recebi de Epafrodito o que vocês me enviaram — um sacrifício aceitável, de aroma suave, agradável a Deus.

[TIP]
====
- *Deus*: Algumas traduções das Escrituras Gregas Cristãs para o hebraico e outros idiomas usam o nome de Deus aqui.
====

[[v50-4-19]]

^<<v50-4-19,19>>^ Meu Deus, por sua vez, lhes suprirá plenamente todas as necessidades segundo as Suas gloriosas riquezas, por meio de Cristo Jesus.

[[v50-4-20]]

^<<v50-4-20,20>>^ Ao nosso Deus e Pai seja dada a glória para todo o sempre. Amém.

[TIP]
====
- *Amém*: Veja a nota de estudo em Ro 1:25.
====

[[v50-4-21]]

^<<v50-4-21,21>>^ Transmitam minhas saudações a todos os santos em união com Cristo Jesus. Os irmãos que estão comigo mandam saudações a vocês.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todos os santos, mas especialmente os da casa de César, lhes mandam saudações.

[TIP]
====
- *casa de César*: Naquela época (cerca de 61 d.C.), o imperador romano, ou César, era Nero. (Veja o Glossário, “César”.) A expressão “casa de César” não se refere necessariamente à família imediata do imperador. Essa expressão poderia incluir uma grande variedade de servos, talvez chegando a milhares de pessoas. Entre elas estavam escravos, homens livres e até pessoas que trabalhavam nos mais variados setores do governo romano e das províncias, além de suas esposas e filhos. O escritor judeu Fílon de Alexandria, em sua obra Flaco (parágrafo 35), usou a mesma expressão grega para se referir a esse grande grupo de pessoas. Paulo não diz que ligação tinha com os cristãos da casa de César enquanto estava preso em Roma, nem se teve alguma participação na conversão deles. Também não se sabe qual era a ligação dos cristãos em Filipos com esses cristãos da casa de César. Pode ser que alguns irmãos filipenses fossem parentes ou amigos de alguns cristãos que trabalhavam para o imperador, ou seja, que eram da casa de César. Alguns deles talvez estivessem entre os cristãos fiéis a quem Paulo mandou suas saudações no fim da sua carta aos romanos. — Ro 16:3-16.
====

[[v50-4-23]]

^<<v50-4-23,23>>^ Que a bondade imerecida do Senhor Jesus Cristo esteja com o espírito que vocês mostram.

[TIP]
====
- *com o espírito que vocês mostram*: Veja a nota de estudo em Gál 6:18.
- *mostram*: Alguns manuscritos bem antigos adicionam a palavra “Amém” no final, mas existe boa base para não se acrescentar essa palavra. Além disso, muitos estudiosos acreditam que ela também não aparecia no texto original.
====

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]