include::./index.adoc[]

[[v50-2-0]]
=== Aos Filipenses, 2
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. CONSELHOS SOBRE O MODO DE VIDA CRISTÃO (1:27–2:18)
* Comportem-se de uma maneira digna das boas novas; mantenham-se firmes (1:27-30)
* Conselho para serem unidos e humildes (2:1-4)
* Grande exemplo de Cristo em servir de modo humilde (2:5-11)
* Persistam em produzir a sua própria salvação; Deus está agindo em vocês (2:12, 13)
* Brilhando como iluminadores no mundo e se mantendo firmemente agarrados à palavra da vida (2:14-18)
* D. TIMÓTEO E EPAFRODITO SERÃO ENVIADOS A FILIPOS (2:19-30)
* Timóteo vai cuidar genuinamente dos filipenses (2:19-24)
* Fidelidade de Epafrodito, sua doença; “continuem a prezar homens como ele” (2:25-30)
****

[[v50-2-1]]

^<<v50-2-1,1>>^ Se há, pois, algum encorajamento em Cristo, algum consolo de amor, algum companheirismo espiritual, algum terno sentimento e compaixão,

[TIP]
====
- *encorajamento . . . consolo*: Paulo usou aqui dois substantivos gregos que têm um significado parecido. A palavra traduzida como “encorajamento” (paráklesis) é bem abrangente. Ela pode ser traduzida como “encorajamento”, assim como acontece aqui e em outros lugares (At 13:15; He 6:18). Também pode ser traduzida como “exortação” (1Te 2:3; 1Ti 4:13; He 12:5) ou como “consolo” (Ro 15:4; 2Co 1:3, 4; 2Te 2:16). (Veja a nota de estudo em Ro 12:8.) A outra palavra grega (paramýthion), traduzida como “consolo”, vem de um verbo grego que significa “consolar; animar” ou “falar com alguém de modo positivo e bondoso”. (Veja também a nota de estudo em 1Co 14:3.) Paulo parece indicar que, se os filipenses encorajassem e consolassem uns aos outros, eles iriam fortalecer a união da congregação. — Fil 2:2.
- *algum companheirismo espiritual*: Ou: “algum compartilhamento de espírito”. Essa expressão se refere a uma forte amizade em que as pessoas têm os mesmos interesses e estão dispostas a compartilhar coisas com outros. (Veja a nota de estudo em At 2:42, que explica a palavra grega para “partilhar; ter companheirismo”.) Neste versículo e no próximo, Paulo indica que, quando os cristãos se empenham juntos por alvos espirituais e agem de acordo com a orientação do espírito santo de Deus, eles desenvolvem uma união que o mundo não pode destruir. (Veja a nota de estudo em Fil 2:2.) Um dicionário bíblico comenta o seguinte sobre a palavra grega usada neste versículo: “Esse compartilhamento requer uma atitude mental que coloque a outra pessoa acima de si mesmo.” — 2Co 13:14; veja a nota de estudo em Jo 17:21.
- *terno sentimento*: Neste contexto, o termo grego traduzido como “terno sentimento” (splágkhnon) se refere a sentimentos bem profundos, a emoções intensas. — Veja a nota de estudo em 2Co 6:12.
====

[[v50-2-2]]

^<<v50-2-2,2>>^ tornem plena a minha alegria por terem o mesmo modo de pensar e o mesmo amor, sendo plenamente unidos, tendo o mesmo pensamento.

[TIP]
====
- *sendo plenamente unidos*: A palavra grega usada aqui (sýnpsykhos) é formada pelas palavras syn (com; junto) e psykhé (algumas vezes traduzida como “alma”) e poderia ser traduzida como “unidos (unificados) na alma”. Paulo usou essa expressão e várias outras relacionadas à união para destacar que os cristãos em Filipos deveriam se esforçar para ser unidos. — Veja a nota de estudo em Fil 2:1.
====

[[v50-2-3]]

^<<v50-2-3,3>>^ Não façam nada por rivalidade nem por presunção; mas, com humildade, considerem os outros superiores a vocês,

[TIP]
====
- *presunção*: Um conceito exagerado sobre si mesmo. — Veja a nota de estudo em Gál 5:26, onde uma palavra grega relacionada é traduzida como “presunçosos”.
- *humildade*: Ou: “humildade mental”. — Veja a nota de estudo em At 20:19.
- *considerem os outros superiores a vocês*: Ou: “considerem os outros mais importantes do que vocês mesmos”. — Ro 12:3; 1Co 10:24; Fil 2:4.
====

[[v50-2-4]]

^<<v50-2-4,4>>^ buscando não somente os seus próprios interesses, mas também os interesses dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Mantenham a mesma atitude que Cristo Jesus teve:

[TIP]
====
- *Mantenham a mesma atitude*: Ou: “Tenham o mesmo modo de pensar”. O contexto mostra que a atitude de Jesus era de humildade. — Fil 2:3, 4.
====

[[v50-2-6]]

^<<v50-2-6,6>>^ embora ele existisse em forma de Deus, nem mesmo chegou a pensar na ideia de tentar ser igual a Deus.

[TIP]
====
- *embora ele existisse em forma de Deus*: A palavra grega traduzida como “forma” (morfé) significa basicamente “natureza; aparência; formato; semelhança”. Jesus era um ser espiritual, assim como “Deus é espírito”. (Jo 4:24; veja também a nota de estudo.) Essa mesma palavra grega é usada para falar de quando Jesus “assumiu a forma de escravo” e “se tornou carne”, ou seja, se tornou humano. — Fil 2:7; Jo 1:14.
- *nem mesmo chegou a pensar na ideia de tentar ser igual a Deus*: Ou: “nunca pensou que ser igual a Deus fosse algo que ele pudesse tomar (usurpar)”. Aqui, Paulo incentivou os filipenses a desenvolver a mesma atitude excelente de Jesus. Em Fil 2:3, Paulo disse para eles: “Com humildade, considerem os outros superiores a vocês.” E, no versículo 5, ele continuou: “Mantenham a mesma atitude que Cristo Jesus teve.” Jesus, que encarava a Deus como sendo superior a ele, nunca tentou ser igual a Deus. Em vez disso, ele “se humilhou e se tornou obediente a ponto de enfrentar a morte”. (Fil 2:8; Jo 5:30; 14:28; 1Co 15:24-28) Jesus não pensava como o Diabo, que incentivou Eva a se tornar como Deus, ou seja, a ser igual a Deus. (Gên 3:5) Jesus foi um exemplo perfeito do ponto que Paulo está destacando aqui — a importância da humildade e da obediência ao Criador, Jeová Deus. — Veja a nota de estudo em tentar ser neste versículo.
- *tentar ser*: O substantivo grego usado aqui (harpagmós; lit.: “uma coisa a ser usurpada”) vem do verbo harpázo, que significa basicamente “usurpar; arrancar; apoderar-se”. Alguns sugerem que esse termo significa reter algo que já se possui. Mas a Bíblia nunca usa esse termo grego no sentido de a pessoa se apegar a algo que já tem. Em vez disso, ele é muitas vezes traduzido como “apoderar-se”, “arrancar” ou outras expressões como essas. (Mt 11:12; 12:29; 13:19; Jo 6:15; 10:12, 28, 29; At 8:39; 23:10; 2Co 12:2, 4; 1Te 4:17; Ju 23; Ap 12:5) Se Jesus “nem mesmo chegou a pensar na ideia de tentar ser igual a Deus”, é lógico concluir que ele nunca foi igual a Deus.
====

[[v50-2-7]]

^<<v50-2-7,7>>^ Pelo contrário, ele abriu mão de tudo que tinha, assumiu a forma de escravo e se tornou humano.^&#42;1^

[NOTE]
====
. Lit.: “veio a ser na semelhança de humanos”.
====

[TIP]
====
- *ele abriu mão de tudo que tinha*: Lit.: “ele se esvaziou”. A palavra grega para “esvaziar” significa literalmente remover o conteúdo de algo. Aqui, Paulo usou essa palavra em sentido figurado para se referir a Jesus, que abriu mão de sua vida espiritual para viver e sofrer como humano na Terra. É verdade que os anjos às vezes eram vistos pelos humanos em corpos de carne e osso, mas eles nunca deixaram de ser criaturas espirituais. Por outro lado, Jesus realmente abriu mão de seu corpo espiritual e da glória e dos privilégios que tinha no céu. Nenhum humano jamais sacrificou algo que chegue perto do que Jesus abriu mão para agradar a Deus.
====

[[v50-2-8]]

^<<v50-2-8,8>>^ Mais do que isso, quando veio como homem, ele se humilhou e se tornou obediente a ponto de enfrentar a morte, sim, morte numa estaca.

[TIP]
====
- *quando veio como homem*: Lit.: “quando foi achado em aparência como um homem (humano)”. — Veja a nota de estudo em Fil 2:6.
- *numa estaca*: Ou: “numa estaca de tortura; numa estaca de execução”. Ao aceitar a “morte numa estaca”, sendo condenado falsamente como criminoso e blasfemador, Jesus deu a mais poderosa lição de humildade e obediência. (Mt 26:63-66; Lu 23:33; veja o Glossário, “Madeiro; Estaca”; “Estaca de tortura”.) Ele provou além de qualquer dúvida que humanos podem se manter leais a Jeová mesmo quando testados ao extremo. — Jo 5:30; 10:17; He 12:2.
====

[[v50-2-9]]

^<<v50-2-9,9>>^ Por essa razão, Deus o enalteceu a uma posição superior e lhe deu bondosamente o nome que está acima de todo outro nome,

[TIP]
====
- *deu bondosamente*: O verbo grego usado aqui (kharízomai) está relacionado ao termo grego que geralmente é traduzido como “bondade imerecida”, mas que também pode ser traduzido como “favor divino”. (Jo 1:14; veja também a nota de estudo.) Neste contexto, o termo transmite a ideia de que Deus, por amor, generosidade e misericórdia, deu a Jesus um nome enaltecido, “que está acima de todo outro nome”. Já que Deus pode dar um nome assim para seu Filho, Jesus, o Pai tem que ser maior que Jesus, e Jesus tem que estar sob a autoridade do Pai. (Jo 14:28; 1Co 11:3) Sendo assim, qualquer honra dada a Jesus por causa de sua posição elevada é “para a glória de Deus, o Pai”. — Fil 2:11.
- *o nome*: Na Bíblia, a palavra “nome” às vezes não se refere apenas ao modo como alguém ou alguma coisa é identificada. (Veja a nota de estudo em Mt 24:9.) Por exemplo, aqui “o nome” que Deus deu a Jesus se refere à autoridade e à posição que Jesus recebeu de seu Pai. O contexto do capítulo 2 de Filipenses mostra que Jesus recebeu esse nome elevado depois de sua ressurreição. — Mt 28:18; Fil 2:8, 10, 11; He 1:3, 4.
- *todo outro nome*: A tradução literal do texto grego (“todo nome”, Kingdom Interlinear), usada por muitas traduções da Bíblia, poderia dar a impressão de que o nome de Jesus está acima do próprio nome de Deus. Só que essa ideia não está de acordo com o contexto, já que Paulo diz que foi Deus quem “enalteceu [Jesus] a uma posição superior e lhe deu bondosamente” esse nome. Além disso, a palavra grega para “todo” pode, em alguns casos, ter o sentido de “todos os outros” ou “todas as outras”, como acontece em Lu 13:2; 21:29 e Fil 2:21. Então, tanto o contexto como a forma como essa palavra grega é usada em outros textos apoiam o uso de “todo outro”. Paulo aqui explica que o nome de Jesus está acima de todo outro nome, menos do nome de Jeová, que foi quem deu esse nome para ele. — Veja também 1Co 15:28.
====

[[v50-2-10]]

^<<v50-2-10,10>>^ a fim de que, diante do nome de Jesus, se dobre todo joelho — dos que estão no céu, na terra e debaixo do chão —

[TIP]
====
- *diante do nome de Jesus, se dobre todo joelho*: Toda criatura inteligente no céu e na Terra dobra o joelho “diante do nome de Jesus” por reconhecer a posição de Jesus e aceitar sua autoridade. — Veja a nota de estudo em Mt 28:19.
- *dos que estão . . . debaixo do chão*: Pelo visto, se refere aos mortos que Jesus disse que estão “nos túmulos memoriais”. (Jo 5:28, 29) Quando forem ressuscitados da Sepultura, eles também vão ter que aceitar a autoridade de Jesus e ‘reconhecer abertamente que Jesus Cristo é Senhor, para a glória de Deus, o Pai’. — Fil 2:11.
====

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua reconheça abertamente que Jesus Cristo é Senhor, para a glória de Deus, o Pai.

[TIP]
====
- *reconheça abertamente*: Ou: “declare publicamente; confesse”. O contexto mostra que esse reconhecimento está relacionado com a plena certeza de que Jeová ressuscitou Jesus. — Veja também a nota de estudo em Ro 10:9.
- *que Jesus Cristo é Senhor*: Veja a nota de estudo em Ro 10:9.
- *Senhor*: Alguns afirmam que a frase “Jesus Cristo é Senhor” significa que ele e o Pai dele, Jeová, são a mesma pessoa. Mas o contexto deixa claro que esse não pode ser o caso, já que foi Deus quem “enalteceu [Jesus] a uma posição superior e lhe deu bondosamente o nome que está acima de todo outro nome”. — Fil 2:9; veja as notas de estudo em Ro 10:9.
====

[[v50-2-12]]

^<<v50-2-12,12>>^ Portanto, meus amados, assim como vocês sempre obedeceram, não somente durante a minha presença, porém com muito mais prontidão agora durante a minha ausência, persistam em produzir a sua própria salvação com temor e tremor.

[TIP]
====
- *presença . . . ausência*: Aqui, Paulo usou a palavra grega parousía para falar de quando estaria com os cristãos em Filipos, ou seja, do período de tempo em que estaria presente ali. Neste versículo, Paulo nos ajuda a entender o sentido dessa palavra grega por contrastar a sua “presença” com a sua “ausência” (em grego, apousía), ou seja, com o período de tempo em que estaria longe dos filipenses. A palavra grega parousía também é usada em um sentido especial para se referir à presença invisível de Jesus Cristo como Rei messiânico, que começou quando ele se tornou Rei no céu no início dos últimos dias deste sistema de coisas. — Veja as notas de estudo em Mt 24:3; 1Co 15:23; Fil 1:26.
- *persistam em produzir*: A palavra grega usada aqui significa basicamente “alcançar; realizar; executar”. O tempo verbal usado neste versículo indica um esforço contínuo, transmitindo a ideia de persistir em fazer algo até que esteja terminado.
====

[[v50-2-13]]

^<<v50-2-13,13>>^ Pois Deus é aquele que, segundo o que lhe agrada, está agindo em vocês, e lhes dá tanto o desejo como o poder de agir.

[TIP]
====
- *está agindo em vocês*: Ou: “enche vocês de energia”. A palavra grega energéo aparece duas vezes neste versículo. Na primeira, é traduzida como “está agindo” e, na segunda, como “lhes dá . . . o poder de agir”. O espírito santo, ou a força ativa, de Deus é a maior fonte de poder, ou energia, do Universo. Deus usou o espírito santo para criar todas as coisas. (Gên 1:2; Sal 104:30; Is 40:26) Quando os servos de Jeová estão perdendo as forças, é por meio desse espírito que Jeová dá a eles a energia necessária, ou “o poder de agir”. (Is 40:31) O espírito de Jeová também pode melhorar, conforme a necessidade, as habilidades que a pessoa já tem. (Lu 11:13; 2Co 4:7) A vida do apóstolo Paulo está cheia de exemplos do que o esforço da pessoa junto com o poder de Deus podem realizar. — Fil 4:13; Col 1:29.
- *lhes dá . . . o desejo*: Por causa do desânimo, das próprias falhas e de outros fatores, alguns servos de Deus no passado perderam o desejo de servir a ele, e até de continuar vivos. (1Rs 19:4; Sal 73:13, 14; Jon 4:2, 3) Aqui, Paulo mostra que, quando a pessoa perde esse desejo, Deus fica feliz de motivá-la, especialmente quando ela busca a ajuda Dele. — Sal 51:10, 11; 73:17, 18.
====

[[v50-2-14]]

^<<v50-2-14,14>>^ Continuem fazendo todas as coisas sem queixas nem discussões,

[TIP]
====
- *sem queixas*: Ficar se queixando envolve reclamar ou falar de modo negativo de alguém ou de alguma coisa. Geralmente isso não é feito abertamente, mas às escondidas. Quem tem o hábito de reclamar tenta influenciar outros e pode dar importância demais aos seus sentimentos ou à sua posição, chamando atenção para si mesmo em vez de para Deus. Esse hábito pode causar divisão entre os irmãos, atrapalhando os esforços deles de servir a Jeová em união. Por volta de 55 d.C., Paulo lembrou aos cristãos em Corinto que Jeová tinha ficado irado com os israelitas por eles terem se queixado no deserto. (Veja a nota de estudo em 1Co 10:10.) Mas nem todo tipo de reclamação desagrada a Deus. A palavra grega usada aqui também é usada em At 6:1, onde diz que os judeus que falavam grego em Jerusalém “começaram a reclamar” porque suas viúvas estavam sendo deixadas de lado em sentido material. Por causa disso, os apóstolos providenciaram que a situação fosse resolvida. — At 6:1-6.
====

[[v50-2-15]]

^<<v50-2-15,15>>^ para que venham a ser irrepreensíveis e inocentes, filhos de Deus sem defeito no meio de uma geração pervertida e corrompida, no meio da qual vocês estão brilhando como iluminadores no mundo,

[[v50-2-16]]

^<<v50-2-16,16>>^ mantendo-se firmemente agarrados à palavra da vida. Então terei motivo para me alegrar no dia de Cristo, por saber que eu não corri em vão nem me esforcei tanto em vão.

[[v50-2-17]]

^<<v50-2-17,17>>^ Contudo, mesmo que eu esteja sendo derramado como oferta de bebida sobre o sacrifício e o serviço sagrado que provém da sua fé,^&#42;1^ me alegro e compartilho a minha alegria com todos vocês.

[NOTE]
====
. Ou: “serviço sagrado a que a sua fé os conduziu”.
====

[TIP]
====
- *eu esteja*: Ou: “minha vida esteja”. — Veja a nota de estudo em eu esteja sendo derramado como oferta de bebida neste versículo.
- *eu esteja sendo derramado como oferta de bebida*: Os israelitas apresentavam vinho como oferta de bebida junto com a maioria das outras ofertas, derramando o vinho sobre o altar. (Le 23:18, 37; Núm 15:2, 5, 10; 28:7) Aqui, Paulo fala de si mesmo como sendo uma oferta de bebida. Com isso, ele mostrou que estava disposto a “ser derramado”, ou seja, a se gastar tanto em sentido físico como emocional a favor dos irmãos em Filipos. Em outras palavras, Paulo estava disposto a dar tudo de si para apoiar os filipenses e outros cristãos que estavam apresentando seus sacrifícios espirituais e realizando seu “serviço sagrado” a Deus. (Veja também 2Co 12:15.) Pouco antes de morrer, Paulo escreveu a Timóteo: “Eu já estou sendo derramado como oferta de bebida, e a hora do meu livramento está próxima.” — 2Ti 4:6.
- *o serviço sagrado*: Ou: “o serviço público”. Paulo usou esse termo para se referir ao ministério cristão. O serviço que ele prestou com amor e dedicação a favor dos seus irmãos em Filipos foi de grande ajuda para eles. O resultado foi que a fé dos cristãos em Filipos os motivou a também participar nesse serviço em benefício de outros. A palavra grega usada aqui, leitourgía, deve ter feito os cristãos em Filipos, que era uma colônia romana, se lembrar dos serviços prestados ao governo e às autoridades civis em benefício da comunidade. (Veja a nota de estudo em 2Co 9:12.) Esses serviços envolviam gastos, o que lembrava aos filipenses que um serviço fiel envolve sacrifícios. Nas Escrituras Gregas Cristãs, esse termo grego e outros relacionados são muito usados com relação ao serviço no templo e ao ministério cristão. Para outros detalhes sobre esse uso, veja as notas de estudo em Lu 1:23; At 13:2; Ro 13:6; 15:16.
====

[[v50-2-18]]

^<<v50-2-18,18>>^ Do mesmo modo, vocês também devem se alegrar e compartilhar a sua alegria comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Espero no Senhor Jesus lhes enviar em breve Timóteo, para que eu fique encorajado ao receber notícias de vocês.

[TIP]
====
- *Espero . . . lhes enviar . . . Timóteo*: O relato não diz se Timóteo faria essa viagem de Roma para Filipos por terra ou por mar. Quem viajava de Roma em direção ao leste usava a ampla rede de estradas do Império Romano ou usava embarcações. Mas as duas opções traziam dificuldades. Nos dias de Timóteo, era difícil conseguir uma viagem de barco, e os passageiros viajavam e dormiam no convés, expostos a qualquer tipo de clima. O mar revolto causava enjoos e, às vezes, naufrágios. Quem decidisse ir a pé para Filipos tinha que fazer uma viagem de uns 40 dias. No trajeto, a pessoa provavelmente passava primeiro pela Via Ápia, depois fazia uma curta travessia pelo mar de Ádria e então continuava a viagem por terra, talvez pela Via Egnácia (uma importante estrada romana). (Veja o Apêndice B13.) O viajante tinha que enfrentar coisas como sol, chuva, calor ou frio e corria o risco de ser assaltado. Naquela época, as hospedarias para passar a noite eram frequentadas por pessoas da pior espécie, além de serem locais sujos, superlotados e infestados de pulgas. (Compare com a nota de estudo em At 28:15.) Mesmo assim, Paulo confiava que Timóteo estava disposto não só a fazer a viagem de ida, mas também a de volta, para que o apóstolo pudesse “receber notícias” do bem-estar espiritual dos cristãos de Filipos.
====

[[v50-2-20]]

^<<v50-2-20,20>>^ Pois não tenho a nenhum outro de disposição igual à dele, que cuidará genuinamente de vocês.

[[v50-2-21]]

^<<v50-2-21,21>>^ Pois todos os outros estão buscando os seus próprios interesses, não os de Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas vocês conhecem a prova que ele deu de si mesmo: ele trabalhou como escravo comigo na promoção das boas novas, como um filho junto ao pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ Portanto, é a ele que espero enviar assim que eu souber o que vai acontecer comigo.

[[v50-2-24]]

^<<v50-2-24,24>>^ De fato, estou confiante^&#42;1^ no Senhor em que eu mesmo irei também em breve.

[NOTE]
====
. Ou: “eu confio”.
====

[[v50-2-25]]

^<<v50-2-25,25>>^ Mas, no momento, acho necessário lhes enviar Epafrodito, meu irmão, colaborador e companheiro de batalha, aquele que vocês enviaram para servir às minhas necessidades pessoais,

[TIP]
====
- *Epafrodito*: Um cristão muito confiável da congregação em Filipos que é mencionado apenas nesta carta. Ele foi enviado a Roma para entregar um presente para Paulo, que estava preso na época. Epafrodito provavelmente pretendia ficar em Roma tempo suficiente para poder ajudar mais Paulo. No entanto, Epafrodito ficou doente “quase a ponto de morrer”, e por isso precisou voltar para Filipos mais cedo do que esperado. — Fil 2:27, 28; veja as notas de estudo em Fil 2:26, 30.
- *colaborador*: Veja as notas de estudo em Ro 16:3; 1Co 3:9.
- *aquele que . . . enviaram*: Ou: “apóstolo”. Paulo usou aqui a palavra grega para “apóstolo” (apóstolos) no seu sentido básico, que pode ser “enviado”, “emissário” ou “mensageiro”. Epafrodito tinha sido enviado como um representante da congregação em Filipos com um presente para Paulo, que estava preso em Roma.
====

[[v50-2-26]]

^<<v50-2-26,26>>^ visto que ele deseja muito ver a todos vocês e está deprimido por terem ouvido que ele ficou doente.

[TIP]
====
- *deseja muito ver a todos vocês*: Alguns manuscritos bem antigos dizem “tem saudade de todos vocês”, e muitas traduções da Bíblia usam essa opção. Mas a opção usada aqui no texto principal tem o apoio de manuscritos bem antigos e confiáveis. Não importa qual das opções seja usada, o sentido básico das palavras de Paulo permanece o mesmo: Epafrodito estava sentindo falta de todos os cristãos em Filipos. — Veja o Apêndice A3.
- *deprimido*: O termo grego que Paulo usou aqui é traduzido como “muito aflito” nos relatos que falam sobre a angústia de Jesus no jardim de Getsêmani. (Mt 26:37; Mr 14:33) Uma obra de referência define esse termo como “ansioso, angustiado, aflito”. Epafrodito ficou profundamente angustiado quando os irmãos da congregação em Filipos ficaram sabendo que ele tinha ficado doente. Talvez a preocupação de Epafrodito fosse que os irmãos tivessem a impressão de que ele tinha falhado em ajudar Paulo, sendo um peso para ele. Logo depois que Epafrodito se recuperou, Paulo o enviou de volta a Filipos com uma carta para a congregação. Nessa carta (Fil 2:25-29), Paulo explicou o motivo de Epafrodito estar retornando mais cedo. Com isso, Paulo garantiu para a congregação — e com certeza também para Epafrodito — que aquele cristão era alguém fiel e de grande valor. — Veja as notas de estudo em Fil 2:25, 30.
====

[[v50-2-27]]

^<<v50-2-27,27>>^ De fato, ele adoeceu quase a ponto de morrer. Mas Deus teve misericórdia dele; na verdade, não só dele, mas também de mim, para que eu não tivesse uma tristeza após outra.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso eu o envio com a maior urgência, para que, quando o virem, vocês se alegrem novamente, e eu fique menos ansioso.

[[v50-2-29]]

^<<v50-2-29,29>>^ Portanto, acolham-no como é de costume no Senhor, com toda a alegria, e continuem a prezar homens como ele,

[[v50-2-30]]

^<<v50-2-30,30>>^ porque ele quase morreu por causa da obra de Cristo, arriscando a vida para compensar o fato de que vocês não estavam aqui para prestar serviço a mim.

[TIP]
====
- *da obra de Cristo*: Ou, possivelmente: “da obra do Senhor”. Alguns manuscritos bem antigos usam a expressão “do Senhor”. Mas a opção usada aqui no texto principal tem o apoio de manuscritos bem antigos e confiáveis.
- *arriscando a vida*: Ou: “expondo a sua alma ao perigo”. Pelo visto, cumprir a designação de ir a Roma e levar um presente para Paulo na prisão envolvia algum risco para Epafrodito. Por exemplo, as condições de higiene durante uma viagem e nas hospedarias para passar a noite eram muito precárias naquela época. Essa pode ter sido uma das possíveis causas de Epafrodito ter ficado doente “quase a ponto de morrer”. (Fil 2:26, 27) De qualquer modo, Paulo disse que Epafrodito “quase morreu por causa da obra de Cristo”. Paulo tinha bons motivos para elogiar Epafrodito e para dar o seguinte incentivo à congregação em Filipos: “Acolham-no como é de costume no Senhor, . . . e continuem a prezar homens como ele.” — Fil 2:29; veja as notas de estudo em Fil 2:25, 26 e o Glossário, “Alma”.
====

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]