include::./index.adoc[]

[[v42-14-0]]
=== As Boas Novas Segundo Lucas, 14
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. Jesus se dirige para Jerusalém; Jesus continua seu ministério, principalmente na Judeia e na Pereia (9:51–19:27)
* Aldeia samaritana rejeita Jesus (9:51-56)
* Requisitos para seguir Jesus (9:57-62)
* Jesus envia os 70 (10:1-12)
* Corazim, Betsaida e Cafarnaum são repreendidas por não se arrependerem (10:13-16)
* Os 70 voltam (10:17-20)
* Jesus louva seu Pai por favorecer os humildes (10:21-24)
* Ilustração do bom samaritano (10:25-37)
* Jesus visita Marta e Maria (10:38-42)
* Jesus ensina a oração-modelo (11:1-4)
* Ilustração do amigo persistente (11:5-13)
* Jesus explica que os demônios são expulsos “por meio do dedo de Deus” (11:14-23)
* Jesus fala da volta de um espírito impuro (11:24-26)
* Explicação sobre a verdadeira felicidade (11:27, 28)
* Sinal de Jonas (11:29-32)
* Olho é a lâmpada do corpo (11:33-36)
* Jesus come com um fariseu; ai dos religiosos hipócritas (11:37-54)
* “Tomem cuidado com o fermento dos fariseus” (12:1-3)
* Temer a Deus, não a homens (12:4-7)
* Declarar que está em união com Cristo (12:8-12)
* Ilustração do rico insensato (12:13-21)
* “Parem de se preocupar tanto com a sua vida” (12:22-31)
* “Não tema, pequeno rebanho” (12:32-34)
* Manter a vigilância (12:35-40)
* Identificação do administrador fiel e características de um escravo infiel (12:41-48)
* Não paz, mas divisão (12:49-53)
* Necessidade de examinar os tempos (12:54-56)
* Resolver disputas (12:57-59)
* Arrepender-se ou ser destruído (13:1-5)
* Ilustração da figueira infrutífera (13:6-9)
* Jesus cura no sábado uma mulher encurvada (13:10-17)
* Ilustrações do grão de mostarda e do fermento (13:18-21)
* É preciso esforço para entrar pela porta estreita (13:22-30)
* Jesus chama Herodes de ‘aquela raposa’ (13:31-33)
* Jesus lamenta por Jerusalém (13:34, 35)
* Jesus cura no sábado um homem com hidropisia (14:1-6)
* Ser um convidado humilde (14:7-11)
* Convidar os que não podem recompensar (14:12-14)
* Ilustração dos convidados que recusam o convite (14:15-24)
* Custo de ser discípulo (14:25-33)
* Sal que perde a força (14:34, 35)
* Ilustração da ovelha perdida (15:1-7)
* Ilustração da moeda perdida (15:8-10)
* Ilustração do filho pródigo (15:11-32)
* Ilustração do administrador injusto (16:1-13)
* A Lei e o Reino de Deus (16:14-18)
* Ilustração do rico e Lázaro (16:19-31)
* Jesus ensina sobre tropeços, perdão e fé (17:1-6)
* Ilustração do escravo que serve primeiro seu senhor (17:7-10)
* Jesus cura dez leprosos (17:11-19)
* Vinda do Reino de Deus (17:20-37)
* Ilustração da viúva persistente (18:1-8)
* Ilustração do fariseu e do cobrador de impostos (18:9-14)
* Jesus e as criancinhas (18:15-17)
* Líder rico pergunta sobre a vida eterna (18:18-30)
* Jesus prediz novamente sua morte e ressurreição (18:31-34)
* Jesus cura um mendigo cego perto de Jericó (18:35-43)
* Jesus visita o cobrador de impostos Zaqueu (19:1-10)
* Ilustração das dez minas (19:11-27)
****

[[v42-14-1]]

^<<v42-14-1,1>>^ Em outra ocasião, ele foi tomar uma refeição na casa de um líder dos fariseus, no sábado, e eles o estavam observando atentamente.

[[v42-14-2]]

^<<v42-14-2,2>>^ E na frente dele estava um homem que sofria de hidropisia.

[TIP]
====
- *hidropisia*: Ou: “edema”. Um acúmulo excessivo de líquido no corpo, que causa inchaço. Esse termo foi usado por médicos da antiguidade a partir de Hipócrates, um médico grego que viveu nos séculos 5 e 4 a.C. A hidropisia talvez fosse um sintoma de que os órgãos vitais estavam em um estado avançado de falência. Ela era temida porque muitas vezes significava que a pessoa podia morrer a qualquer momento. Alguns acreditam que o homem foi levado pelos fariseus até Jesus em um sábado como uma armadilha, já que o versículo 1 diz que ‘eles estavam observando Jesus atentamente’. Pelo menos seis milagres foram registrados apenas por Lucas, e esse é um deles. — Veja a “Introdução a Lucas”.
====

[[v42-14-3]]

^<<v42-14-3,3>>^ Em vista disso, Jesus perguntou aos peritos na Lei e aos fariseus: “É permitido ou não curar no sábado?”

[[v42-14-4]]

^<<v42-14-4,4>>^ Mas eles ficaram calados. Assim, ele tocou no homem, o curou e o mandou embora.

[[v42-14-5]]

^<<v42-14-5,5>>^ Então ele lhes disse: “Quem de vocês não puxará imediatamente para fora o seu filho ou o seu touro se ele cair num poço no dia de sábado?”

[[v42-14-6]]

^<<v42-14-6,6>>^ E eles ficaram sem resposta.

[[v42-14-7]]

^<<v42-14-7,7>>^ Ele contou então aos convidados uma ilustração, quando notou que eles escolhiam os lugares mais destacados. Ele lhes disse:

[TIP]
====
- *uma ilustração*: Ou: “uma parábola”. — Veja a nota de estudo em Mt 13:3.
- *lugares mais destacados*: Nas grandes refeições e banquetes realizados no tempo de Jesus, as pessoas se deitavam em divãs colocados junto a três lados da mesa. O quarto lado era deixado livre para os servos servirem os convidados. O número de divãs variava de acordo com o tamanho da mesa. As pessoas deitavam com a cabeça perto da mesa, apoiavam o cotovelo esquerdo em uma almofada e usavam a mão direita para pegar comida. Quatro ou cinco pessoas chegavam a ocupar um divã, mas normalmente eram apenas três. De acordo com os costumes da época, as três posições de um divã tinham níveis diferentes de importância e indicavam a honra que o convidado tinha recebido.
====

[[v42-14-8]]

^<<v42-14-8,8>>^ “Quando você for convidado por alguém para uma festa de casamento, não se recoste no lugar mais destacado. Talvez uma pessoa de mais destaque do que você também tenha sido convidada.

[[v42-14-9]]

^<<v42-14-9,9>>^ Então aquele que convidou a ambos chegará e dirá a você: ‘Dê o seu lugar a este homem.’ Então você irá, envergonhado, ocupar o último lugar.

[[v42-14-10]]

^<<v42-14-10,10>>^ Mas, quando você for convidado, vá se recostar no último lugar, para que, quando chegar o homem que o convidou, ele lhe diga: ‘Amigo, passe para um lugar mais importante.’ Então você terá honra na frente de todos os outros convidados.^&#42;1^

[NOTE]
====
. Ou: “todos os que estiverem recostados à mesa com você”.
====

[[v42-14-11]]

^<<v42-14-11,11>>^ Porque todo aquele que se enaltecer será humilhado, e aquele que se humilhar será enaltecido.”

[[v42-14-12]]

^<<v42-14-12,12>>^ A seguir ele disse também ao homem que o havia convidado: “Quando você oferecer um almoço ou um jantar, não chame seus amigos, nem seus irmãos, nem seus parentes, nem seus vizinhos ricos. Pois eles, por sua vez, poderiam convidá-lo também, e isso seria para você uma retribuição.

[[v42-14-13]]

^<<v42-14-13,13>>^ Mas, quando oferecer um banquete, convide os pobres, os aleijados, os mancos, os cegos;

[[v42-14-14]]

^<<v42-14-14,14>>^ e você será feliz, porque eles não têm nada com que recompensá-lo. Pois você será recompensado na ressurreição dos justos.”

[[v42-14-15]]

^<<v42-14-15,15>>^ Ao ouvir essas coisas, um dos outros convidados lhe disse: “Feliz é aquele que participa do banquete no Reino de Deus.”

[TIP]
====
- *participa do banquete*: Lit.: “come pão”. Nos tempos bíblicos, o pão era tão importante que tanto em grego como em hebraico a expressão “comer pão” era usada com o sentido de “comer (uma refeição)”. A palavra hebraica para “comer pão” é traduzida muitas vezes como “comer” (Gên 37:25; 2Sa 9:7; 2Rs 4:8) ou ‘comer alimento’ (Ec 9:7). Em Lu 14:1, a expressão grega para “comer pão” foi traduzida como “tomar uma refeição”.
====

[[v42-14-16]]

^<<v42-14-16,16>>^ Jesus lhe disse: “Um homem estava oferecendo um grande banquete,^&#42;1^ e convidou muitas pessoas.

[NOTE]
====
. Ou: “uma grande ceia”.
====

[[v42-14-17]]

^<<v42-14-17,17>>^ Ele enviou seu escravo, na hora do banquete,^&#42;1^ para dizer aos convidados: ‘Venham, porque já está tudo pronto.’

[NOTE]
====
. Ou: “da ceia”.
====

[[v42-14-18]]

^<<v42-14-18,18>>^ Mas todos, sem exceção, começaram a dar desculpas. O primeiro disse: ‘Comprei um campo, e preciso sair e vê-lo. Peço-lhe que me desculpe.’^&#42;1^

[NOTE]
====
. Ou: “me dispense”.
====

[[v42-14-19]]

^<<v42-14-19,19>>^ E outro disse: ‘Comprei cinco juntas^&#42;1^ de bois e vou examiná-las. Peço-lhe que me desculpe.’

[NOTE]
====
. Ou: “pares”.
====

[[v42-14-20]]

^<<v42-14-20,20>>^ Ainda outro disse: ‘Acabei de me casar e por isso não posso ir.’

[[v42-14-21]]

^<<v42-14-21,21>>^ Assim, o escravo voltou e contou essas coisas ao seu senhor. O dono da casa ficou então irado e disse ao seu escravo: ‘Vá depressa às ruas principais e aos becos da cidade, e traga para cá os pobres, os aleijados, os cegos e os mancos.’

[[v42-14-22]]

^<<v42-14-22,22>>^ Mais tarde, o escravo disse: ‘Senhor, foi feito o que ordenou, mas ainda há lugar.’

[[v42-14-23]]

^<<v42-14-23,23>>^ Então o senhor disse ao escravo: ‘Vá para as estradas e os caminhos, e obrigue-os a vir para dentro, a fim de que a minha casa fique cheia.

[[v42-14-24]]

^<<v42-14-24,24>>^ Pois eu digo a vocês: Nenhum daqueles homens que foram convidados provará o meu banquete.’”^&#42;1^

[NOTE]
====
. Ou: “a minha ceia”.
====

[[v42-14-25]]

^<<v42-14-25,25>>^ Grandes multidões viajavam então com ele, e ele se virou e lhes disse:

[[v42-14-26]]

^<<v42-14-26,26>>^ “Se alguém vem a mim e não odeia o pai, a mãe, a esposa, os filhos, os irmãos, as irmãs, sim, e até mesmo a própria vida, não pode ser meu discípulo.

[TIP]
====
- *odeia*: Na Bíblia, a palavra “odiar” tem diversas variações de sentido. Ela pode indicar um sentimento maldoso de hostilidade que leva a pessoa a prejudicar outros ou pode se referir a um forte sentimento de aversão que leva a pessoa a evitar totalmente alguém ou alguma coisa. Mas em alguns casos ela pode significar simplesmente amar menos. Por exemplo, quando a Bíblia diz que Jacó ‘odiava’ Leia e amava Raquel, isso quer dizer que ele amava Leia menos do que amava Raquel. (Veja as notas de rodapé em Gên 29:31 e De 21:15.) E outras obras da literatura judaica antiga também usam a palavra “odiar” nesse sentido. Jesus com certeza não queria que seus seguidores odiassem literalmente a si mesmos e a seus parentes, já que isso iria contra o restante da Bíblia. (Compare com Mr 12:29-31 e Ef 5:28, 29, 33.) Assim, neste contexto, a palavra para “odiar” poderia ser traduzida como “amar menos”.
- *vida*: Ou: “alma”. O significado da palavra grega psykhé, que foi traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, varia de acordo com o contexto. Aqui, a palavra se refere à vida da pessoa. Assim, o que Jesus queria dizer era que seus verdadeiros discípulos precisavam amar a ele mais do que a si mesmos, chegando a ponto de dar sua vida se necessário. — Veja o Glossário, “Alma”.
====

[[v42-14-27]]

^<<v42-14-27,27>>^ Quem não carrega sua estaca de tortura e não me segue, não pode ser meu discípulo.

[TIP]
====
- *estaca de tortura*: Ou: “estaca de execução”. No grego clássico, a palavra staurós era usada principalmente para se referir a uma estaca ou a um poste. Na Bíblia, essa palavra é às vezes usada em sentido figurado para se referir ao que os seguidores de Jesus enfrentam por serem seus discípulos: sofrimento, vergonha, tortura ou até mesmo a morte. Esta foi a terceira vez que Jesus disse que seus discípulos precisariam carregar uma estaca de tortura. As duas ocasiões anteriores estão registradas em (1) Mt 10:38 e (2) Mt 16:24; Mr 8:34 e Lu 9:23. — Veja o Glossário.
====

[[v42-14-28]]

^<<v42-14-28,28>>^ Por exemplo, quem de vocês, querendo construir uma torre, não se senta primeiro e calcula a despesa, para ver se tem o suficiente para completá-la?

[[v42-14-29]]

^<<v42-14-29,29>>^ Senão, ele lançará o alicerce dela, mas não conseguirá terminá-la, e todos os observadores começarão a zombar dele,

[[v42-14-30]]

^<<v42-14-30,30>>^ dizendo: ‘Este homem começou a construir, mas não conseguiu terminar.’

[[v42-14-31]]

^<<v42-14-31,31>>^ Ou que rei, antes de marchar para guerrear contra outro rei, não se senta e se aconselha para ver se consegue com 10.000 soldados enfrentar o que vem contra ele com 20.000?

[[v42-14-32]]

^<<v42-14-32,32>>^ De fato, se ele vê que não consegue, envia um grupo de embaixadores e propõe um acordo de paz, enquanto o outro ainda está longe.

[[v42-14-33]]

^<<v42-14-33,33>>^ Da mesma forma, podem estar certos de que nenhum de vocês que não se despedir^&#42;1^ de todos os seus bens poderá ser meu discípulo.

[NOTE]
====
. Ou: “não abrir mão”.
====

[[v42-14-34]]

^<<v42-14-34,34>>^ “O sal, certamente, é bom. Mas, se o sal perder a sua força, como se recuperará o seu sabor?

[TIP]
====
- *O sal*: Um mineral usado para dar sabor aos alimentos e conservá-los. — Veja a nota de estudo em Mt 5:13.
- *perder a sua força*: Veja a nota de estudo em Mt 5:13.
====

[[v42-14-35]]

^<<v42-14-35,35>>^ Não serve nem para o solo, nem para o estrume. As pessoas o jogam fora. Quem tem ouvidos para escutar, escute.”

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]