include::./index.adoc[]

[[v42-19-0]]
=== As Boas Novas Segundo Lucas, 19
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. Jesus se dirige para Jerusalém; Jesus continua seu ministério, principalmente na Judeia e na Pereia (9:51–19:27)
* Aldeia samaritana rejeita Jesus (9:51-56)
* Requisitos para seguir Jesus (9:57-62)
* Jesus envia os 70 (10:1-12)
* Corazim, Betsaida e Cafarnaum são repreendidas por não se arrependerem (10:13-16)
* Os 70 voltam (10:17-20)
* Jesus louva seu Pai por favorecer os humildes (10:21-24)
* Ilustração do bom samaritano (10:25-37)
* Jesus visita Marta e Maria (10:38-42)
* Jesus ensina a oração-modelo (11:1-4)
* Ilustração do amigo persistente (11:5-13)
* Jesus explica que os demônios são expulsos “por meio do dedo de Deus” (11:14-23)
* Jesus fala da volta de um espírito impuro (11:24-26)
* Explicação sobre a verdadeira felicidade (11:27, 28)
* Sinal de Jonas (11:29-32)
* Olho é a lâmpada do corpo (11:33-36)
* Jesus come com um fariseu; ai dos religiosos hipócritas (11:37-54)
* “Tomem cuidado com o fermento dos fariseus” (12:1-3)
* Temer a Deus, não a homens (12:4-7)
* Declarar que está em união com Cristo (12:8-12)
* Ilustração do rico insensato (12:13-21)
* “Parem de se preocupar tanto com a sua vida” (12:22-31)
* “Não tema, pequeno rebanho” (12:32-34)
* Manter a vigilância (12:35-40)
* Identificação do administrador fiel e características de um escravo infiel (12:41-48)
* Não paz, mas divisão (12:49-53)
* Necessidade de examinar os tempos (12:54-56)
* Resolver disputas (12:57-59)
* Arrepender-se ou ser destruído (13:1-5)
* Ilustração da figueira infrutífera (13:6-9)
* Jesus cura no sábado uma mulher encurvada (13:10-17)
* Ilustrações do grão de mostarda e do fermento (13:18-21)
* É preciso esforço para entrar pela porta estreita (13:22-30)
* Jesus chama Herodes de ‘aquela raposa’ (13:31-33)
* Jesus lamenta por Jerusalém (13:34, 35)
* Jesus cura no sábado um homem com hidropisia (14:1-6)
* Ser um convidado humilde (14:7-11)
* Convidar os que não podem recompensar (14:12-14)
* Ilustração dos convidados que recusam o convite (14:15-24)
* Custo de ser discípulo (14:25-33)
* Sal que perde a força (14:34, 35)
* Ilustração da ovelha perdida (15:1-7)
* Ilustração da moeda perdida (15:8-10)
* Ilustração do filho pródigo (15:11-32)
* Ilustração do administrador injusto (16:1-13)
* A Lei e o Reino de Deus (16:14-18)
* Ilustração do rico e Lázaro (16:19-31)
* Jesus ensina sobre tropeços, perdão e fé (17:1-6)
* Ilustração do escravo que serve primeiro seu senhor (17:7-10)
* Jesus cura dez leprosos (17:11-19)
* Vinda do Reino de Deus (17:20-37)
* Ilustração da viúva persistente (18:1-8)
* Ilustração do fariseu e do cobrador de impostos (18:9-14)
* Jesus e as criancinhas (18:15-17)
* Líder rico pergunta sobre a vida eterna (18:18-30)
* Jesus prediz novamente sua morte e ressurreição (18:31-34)
* Jesus cura um mendigo cego perto de Jericó (18:35-43)
* Jesus visita o cobrador de impostos Zaqueu (19:1-10)
* Ilustração das dez minas (19:11-27)
* I. Começo da última semana do ministério de Jesus em Jerusalém e perto dali (19:28–21:4)
* Entrada triunfal de Jesus em Jerusalém (19:28-40)
* Jesus chora por Jerusalém (19:41-44)
* Jesus purifica o templo (19:45-48)
* Autoridade de Jesus é questionada (20:1-8)
* Ilustração dos lavradores maus (20:9-19)
* Deus e César (20:20-26)
* Pergunta sobre a ressurreição (20:27-40)
* O Cristo é filho de Davi? (20:41-44)
* Alerta contra os escribas (20:45-47)
* Duas pequenas moedas da viúva necessitada (21:1-4)
****

[[v42-19-1]]

^<<v42-19-1,1>>^ Ele entrou então em Jericó e estava atravessando a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Um homem chamado Zaqueu estava ali; ele era chefe de cobradores de impostos e era rico.

[TIP]
====
- *Zaqueu*: De um nome hebraico, que possivelmente vem de uma raiz que significa “limpo; puro”. Lucas diz que Zaqueu era chefe de cobradores de impostos. Assim, parece que ele supervisionava outros cobradores de impostos em Jericó e na região ao redor. O distrito em torno de Jericó era fértil e produtivo, o que gerava uma boa arrecadação de impostos. Zaqueu era rico e, de acordo com suas próprias palavras (Lu 19:8), acumulou pelo menos parte da sua riqueza por meios desonestos.
====

[[v42-19-3]]

^<<v42-19-3,3>>^ Pois bem, ele estava tentando ver quem era esse Jesus, mas não conseguia por causa da multidão, pois era baixo.

[[v42-19-4]]

^<<v42-19-4,4>>^ De modo que correu na frente e subiu num sicômoro^&#42;1^ a fim de vê-lo, pois ele estava para passar por ali.

[NOTE]
====
. Ou: “numa figueira-brava”.
====

[[v42-19-5]]

^<<v42-19-5,5>>^ Então, quando Jesus chegou ao lugar, olhou para cima e lhe disse: “Zaqueu, desça depressa, pois hoje tenho de ficar na sua casa.”

[[v42-19-6]]

^<<v42-19-6,6>>^ Com isso, ele desceu depressa e o recebeu alegremente como hóspede.

[[v42-19-7]]

^<<v42-19-7,7>>^ Quando viram isso, todos começaram a resmungar: “Ele foi se hospedar na casa de um homem que é pecador.”

[[v42-19-8]]

^<<v42-19-8,8>>^ Mas Zaqueu se levantou e disse ao Senhor: “Senhor, escute, vou dar aos pobres a metade dos meus bens e, o que quer que eu tenha extorquido de alguém, vou restituir quatro vezes mais.”

[TIP]
====
- *tenha extorquido*: Ou: “tenha extorquido por acusação falsa”. — Veja a nota de estudo em Lu 3:14.
- *quatro vezes mais*: É provável que Zaqueu pudesse usar seus registros fiscais para calcular o quanto ele tinha recebido de cada pessoa. Ele prometeu devolver quatro vezes o valor que tinha extorquido. Pela Lei, quando um extorsor se arrependia e admitia sua culpa, ele devia devolver o valor completo do que tinha extorquido ‘acrescido de um quinto’, ou seja, o valor mais 20 por cento. (Le 6:2-5; Núm 5:7) Assim, o valor que Zaqueu prometeu devolver era bem maior do que o exigido. Ele provou que estava realmente arrependido, mostrando amor aos pobres e tratando com justiça os que ele tinha prejudicado.
====

[[v42-19-9]]

^<<v42-19-9,9>>^ Então Jesus lhe disse: “Hoje entrou a salvação nesta casa, porque ele também é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Pois o Filho do Homem veio procurar e salvar o que estava perdido.”

[[v42-19-11]]

^<<v42-19-11,11>>^ Enquanto escutavam essas coisas, ele contou outra ilustração, porque estava perto de Jerusalém e eles achavam que o Reino de Deus ia aparecer instantaneamente.

[TIP]
====
- *ilustração*: Ou: “parábola”. — Veja a nota de estudo em Mt 13:3.
====

[[v42-19-12]]

^<<v42-19-12,12>>^ Assim ele disse: “Um homem de origem nobre viajou para um país distante, a fim de se tornar rei e voltar.

[TIP]
====
- *a fim de se tornar rei*: Ou: “a fim de assegurar o reino”. A palavra grega basileía, geralmente traduzida como “reino”, pode ter mais de um sentido e muitas vezes se refere ao tipo de governo que tem um rei ou ao território e aos povos governados por um rei. (Veja as notas de estudo em Mt 3:2; 25:34.) Ela também pode significar realeza, ou seja, o cargo ou a posição que o rei ocupa, com a dignidade, o poder e a autoridade dessa posição. No Império Romano, um nobre que queria ser rei às vezes viajava até Roma com o objetivo de ser aprovado pelo imperador. É bem provável que a ilustração de Jesus tenha lembrado aos seus ouvintes o que tinha acontecido com Arquelau, um dos filhos de Herodes, o Grande. Antes de morrer, Herodes nomeou Arquelau como herdeiro de seu governo sobre a Judeia e outras regiões. Mas, para garantir seu governo, Arquelau primeiro fez a longa viagem até Roma para obter a aprovação de César Augusto.
====

[[v42-19-13]]

^<<v42-19-13,13>>^ Chamando dez escravos seus, deu a eles dez minas e lhes disse: ‘Façam negócios com essas minas até eu voltar.’

[TIP]
====
- *minas*: A mina grega era uma unidade de peso e de valor monetário, e não uma moeda. Uma mina grega equivalia a 340 gramas e, de acordo com escritores gregos antigos, valia o mesmo que 100 dracmas. Como uma dracma valia quase tanto quanto um denário, uma mina tinha um valor considerável. (Veja o Glossário, “Denário”.) A mina grega era diferente da mina hebraica. — Veja o Glossário, “Mina”, e o Apêndice B14-B.
====

[[v42-19-14]]

^<<v42-19-14,14>>^ Mas seus conterrâneos o odiavam e enviaram um grupo de embaixadores atrás dele, para dizer: ‘Não queremos que este homem se torne rei sobre nós.’

[[v42-19-15]]

^<<v42-19-15,15>>^ “Por fim, quando ele voltou depois de se tornar rei, convocou esses escravos a quem tinha dado o dinheiro, a fim de saber o que tinham ganhado com sua atividade comercial.

[TIP]
====
- *se tornar rei*: Ou: “assegurar o reino”. — Veja a nota de estudo em Lu 19:12.
- *dinheiro*: Veja a nota de estudo em Mt 25:18.
====

[[v42-19-16]]

^<<v42-19-16,16>>^ Então o primeiro se aproximou e disse: ‘Senhor, a sua mina rendeu dez minas.’

[[v42-19-17]]

^<<v42-19-17,17>>^ Ele lhe disse: ‘Muito bem, escravo bom! Visto que você se mostrou fiel num assunto muito pequeno, receba autoridade sobre dez cidades.’

[[v42-19-18]]

^<<v42-19-18,18>>^ Então chegou o segundo, dizendo: ‘Senhor, a sua mina produziu cinco minas.’

[[v42-19-19]]

^<<v42-19-19,19>>^ Ele disse também a este: ‘Você também, tome conta de cinco cidades.’

[[v42-19-20]]

^<<v42-19-20,20>>^ Mas outro chegou, dizendo: ‘Senhor, aqui está a sua mina, que deixei escondida num pano.

[[v42-19-21]]

^<<v42-19-21,21>>^ Pois eu tive medo do senhor, visto que é homem severo; retira o que não depositou e colhe o que não semeou.’

[[v42-19-22]]

^<<v42-19-22,22>>^ Ele lhe disse: ‘Pelas suas próprias palavras eu o julgo, escravo mau. Quer dizer que você sabia que sou homem severo, que retiro o que não depositei e colho o que não semeei?

[[v42-19-23]]

^<<v42-19-23,23>>^ Então, por que você não pôs meu dinheiro num banco? Assim, na minha vinda, eu o teria cobrado com juros.’

[TIP]
====
- *dinheiro*: Veja a nota de estudo em Mt 25:18.
- *banco*: Tanto nesta ilustração sobre as minas (Lu 19:12-27) quanto na ilustração sobre os talentos (Mt 25:14-30), Jesus falou sobre a possibilidade de deixar dinheiro com um banco ou com banqueiros para receber juros. A palavra grega trápeza, traduzida aqui como “banco”, significa literalmente “mesa”. (Mt 15:27) Quando a palavra está ligada com operações financeiras, como as dos cambistas, ela se refere a uma mesa ou balcão onde moedas ficavam expostas. (Mt 21:12; Mr 11:15; Jo 2:15) No século 1 d.C., havia muitas pessoas que emprestavam dinheiro (banqueiros) em Israel e nas nações vizinhas.
- *juros*: A Lei proibia que os israelitas cobrassem juros ao emprestar dinheiro para um israelita que estivesse passando necessidade. (Êx 22:25) Mas era permitido cobrar juros de estrangeiros, que provavelmente pediam empréstimos para fins comerciais. (De 23:20) Pelo visto, nos dias de Jesus era comum que as pessoas deixassem dinheiro com banqueiros e depois o recebessem de volta com juros.
====

[[v42-19-24]]

^<<v42-19-24,24>>^ “Com isso, ele disse aos que estavam ali: ‘Tirem dele a mina e deem-na àquele que tem dez minas.’

[[v42-19-25]]

^<<v42-19-25,25>>^ Mas eles lhe disseram: ‘Senhor, ele já tem dez minas!’

[[v42-19-26]]

^<<v42-19-26,26>>^ Ele respondeu: ‘Eu lhes digo que a todo aquele que tem, mais será dado; mas daquele que não tem, até mesmo o que tem será tirado.

[[v42-19-27]]

^<<v42-19-27,27>>^ Além disso, tragam para cá esses meus inimigos, que não quiseram que eu me tornasse rei sobre eles, e matem-nos na minha frente.’”

[[v42-19-28]]

^<<v42-19-28,28>>^ Depois de dizer essas coisas, ele foi adiante, subindo para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ E, quando chegou perto de Betfagé e de Betânia, no chamado monte das Oliveiras, enviou dois dos discípulos,

[TIP]
====
- *Betfagé*: Veja a nota de estudo em Mt 21:1.
- *Betânia*: Veja a nota de estudo em Mt 21:17.
====

[[v42-19-30]]

^<<v42-19-30,30>>^ dizendo: “Vão à aldeia que está ao alcance da vista e, depois de entrarem lá, acharão um jumentinho amarrado, no qual ninguém jamais montou. Desamarrem-no e tragam-no para cá.

[TIP]
====
- *um jumentinho*: Veja as notas de estudo em Mt 21:2; Mr 11:2.
====

[[v42-19-31]]

^<<v42-19-31,31>>^ Mas, se alguém lhes perguntar: ‘Por que vocês o estão desamarrando?’, digam: ‘O Senhor precisa dele.’”

[[v42-19-32]]

^<<v42-19-32,32>>^ Então os que tinham sido enviados partiram e o acharam exatamente como ele lhes tinha dito.

[[v42-19-33]]

^<<v42-19-33,33>>^ Mas, quando estavam desamarrando o jumentinho, os donos dele lhes perguntaram: “Por que vocês estão desamarrando o jumentinho?”

[[v42-19-34]]

^<<v42-19-34,34>>^ Responderam: “O Senhor precisa dele.”

[[v42-19-35]]

^<<v42-19-35,35>>^ Então o levaram a Jesus, lançaram suas capas sobre o jumentinho e fizeram que Jesus montasse nele.

[[v42-19-36]]

^<<v42-19-36,36>>^ Enquanto ele prosseguia, estendiam suas capas na estrada.

[[v42-19-37]]

^<<v42-19-37,37>>^ Assim que chegou perto da estrada que desce do monte das Oliveiras, toda a multidão dos discípulos começou a se alegrar e a louvar a Deus em alta voz por todas as obras poderosas que tinham visto,

[[v42-19-38]]

^<<v42-19-38,38>>^ dizendo: “Bendito é aquele que vem como Rei em nome de Jeová! Paz no céu e glória nas maiores alturas!”^&#42;1^

[NOTE]
====
. Ou: “nos lugares mais altos”.
====

[TIP]
====
- *de Jeová*: Esta é uma citação direta do Sal 118:26. No texto hebraico original desse salmo, aparecem as quatro letras hebraicas que formam o nome de Deus (que equivalem a YHWH). — Veja o Apêndice C1.
====

[[v42-19-39]]

^<<v42-19-39,39>>^ No entanto, alguns dos fariseus que estavam no meio da multidão lhe disseram: “Instrutor, censure os seus discípulos.”

[[v42-19-40]]

^<<v42-19-40,40>>^ Mas ele disse em resposta: “Eu lhes digo que, se eles ficassem calados, as pedras clamariam.”

[TIP]
====
- *as pedras clamariam*: O contexto mostra o que Jesus queria dizer. (Lu 19:37-39) Seus discípulos estavam declarando as palavras registradas no Sal 118:26, que era profético. Como as palavras de Jeová nunca voltam para ele “sem resultados” (Is 55:11), de uma forma ou de outra, aquele salmo iria se cumprir naquela ocasião. Assim, se os discípulos tivessem sido forçados a se calar, como queriam os fariseus, as pedras literais teriam clamado para cumprir a profecia.
====

[[v42-19-41]]

^<<v42-19-41,41>>^ E, quando chegou perto, observou a cidade e chorou por ela,

[TIP]
====
- *chorou*: Muitas vezes, a palavra grega traduzida aqui como “chorou” não se refere ao choro silencioso, mas ao choro que pode ser ouvido.
====

[[v42-19-42]]

^<<v42-19-42,42>>^ dizendo: “Se você, sim, você, tivesse discernido neste dia as coisas que têm a ver com a paz . . . Mas agora elas foram escondidas dos seus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Porque virão para você os dias em que os seus inimigos construirão em sua volta uma fortificação de estacas pontiagudas, cercarão você e a sitiarão,^&#42;1^ por todos os lados.

[NOTE]
====
. Ou: “rodearão; afligirão”.
====

[TIP]
====
- *fortificação de estacas pontiagudas*: Ou: “paliçada”. Esta é a única ocorrência da palavra grega khárax nas Escrituras Gregas Cristãs. Ela é definida como “vara ou bastão pontiagudos usados para cercar uma área; estaca”. Ela também pode se referir a uma “fortificação militar feita com estacas; paliçada”. As palavras de Jesus se cumpriram em 70 d.C. Naquele ano, os romanos, comandados pelo general Tito, construíram uma paliçada para cercar Jerusalém. Tito tinha três objetivos em mente: (1) impedir que os judeus fugissem, (2) causar pressão psicológica e (3) impedir a entrada de suprimentos para fazer os habitantes passar fome e se render. Para construir essa fortificação de madeira em volta de Jerusalém, as tropas romanas cortaram todas as árvores da região.
====

[[v42-19-44]]

^<<v42-19-44,44>>^ Eles lançarão por terra você e seus filhos no seu meio, e não deixarão em você pedra sobre pedra, porque não discerniu o tempo de ser inspecionada.”

[TIP]
====
- *não deixarão em você pedra sobre pedra*: Veja a nota de estudo em Mt 24:2.
- *o tempo de ser inspecionada*: Ou: “o tempo designado para sua inspeção”. A palavra grega episkopé (inspeção; vistoria) está relacionada com as palavras epískopos (superintendente) e episkopéo (proteger; vigiar cuidadosamente). Ela pode ser usada tanto em sentido positivo quanto negativo. Os judeus infiéis, que não perceberam que uma inspeção estava em andamento durante o ministério de Jesus, seriam condenados por Deus. Mas os que perceberam que aquele era um tempo de inspeção e aproveitaram a chance para se arrepender e mostrar fé em Deus seriam aprovados por ele. A palavra episkopé é usada na Septuaginta em Is 10:3 e Je 10:15 para traduzir a expressão hebraica para “dia do ajuste de contas (da punição)”.
====

[[v42-19-45]]

^<<v42-19-45,45>>^ Então ele entrou no templo e começou a expulsar os que vendiam,

[TIP]
====
- *templo*: Veja a nota de estudo em Mt 21:12.
- *expulsar os que vendiam*: Esta foi a segunda vez que Jesus purificou o templo, expulsando os vendedores. Esse acontecimento, que ocorreu no dia 10 de nisã de 33 d.C., foi registrado por Mateus (21:12-17), Marcos (11:15-18) e Lucas. Jesus purificou o templo pela primeira vez quando foi a Jerusalém para a Páscoa do ano 30 d.C., conforme descrito em Jo 2:13-17.
====

[[v42-19-46]]

^<<v42-19-46,46>>^ dizendo-lhes: “Está escrito: ‘Minha casa será casa de oração’, mas vocês fizeram dela um abrigo de ladrões.”

[TIP]
====
- *abrigo de ladrões*: Veja a nota de estudo em Mt 21:13.
====

[[v42-19-47]]

^<<v42-19-47,47>>^ Ele continuava ensinando diariamente no templo. Mas os principais sacerdotes, os escribas e os líderes do povo procuravam matá-lo;

[[v42-19-48]]

^<<v42-19-48,48>>^ contudo, não encontravam um meio de fazer isso, pois o povo todo o escutava com muita atenção.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]