include::./index.adoc[]

[[v42-18-0]]
=== As Boas Novas Segundo Lucas, 18
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. Jesus se dirige para Jerusalém; Jesus continua seu ministério, principalmente na Judeia e na Pereia (9:51–19:27)
* Aldeia samaritana rejeita Jesus (9:51-56)
* Requisitos para seguir Jesus (9:57-62)
* Jesus envia os 70 (10:1-12)
* Corazim, Betsaida e Cafarnaum são repreendidas por não se arrependerem (10:13-16)
* Os 70 voltam (10:17-20)
* Jesus louva seu Pai por favorecer os humildes (10:21-24)
* Ilustração do bom samaritano (10:25-37)
* Jesus visita Marta e Maria (10:38-42)
* Jesus ensina a oração-modelo (11:1-4)
* Ilustração do amigo persistente (11:5-13)
* Jesus explica que os demônios são expulsos “por meio do dedo de Deus” (11:14-23)
* Jesus fala da volta de um espírito impuro (11:24-26)
* Explicação sobre a verdadeira felicidade (11:27, 28)
* Sinal de Jonas (11:29-32)
* Olho é a lâmpada do corpo (11:33-36)
* Jesus come com um fariseu; ai dos religiosos hipócritas (11:37-54)
* “Tomem cuidado com o fermento dos fariseus” (12:1-3)
* Temer a Deus, não a homens (12:4-7)
* Declarar que está em união com Cristo (12:8-12)
* Ilustração do rico insensato (12:13-21)
* “Parem de se preocupar tanto com a sua vida” (12:22-31)
* “Não tema, pequeno rebanho” (12:32-34)
* Manter a vigilância (12:35-40)
* Identificação do administrador fiel e características de um escravo infiel (12:41-48)
* Não paz, mas divisão (12:49-53)
* Necessidade de examinar os tempos (12:54-56)
* Resolver disputas (12:57-59)
* Arrepender-se ou ser destruído (13:1-5)
* Ilustração da figueira infrutífera (13:6-9)
* Jesus cura no sábado uma mulher encurvada (13:10-17)
* Ilustrações do grão de mostarda e do fermento (13:18-21)
* É preciso esforço para entrar pela porta estreita (13:22-30)
* Jesus chama Herodes de ‘aquela raposa’ (13:31-33)
* Jesus lamenta por Jerusalém (13:34, 35)
* Jesus cura no sábado um homem com hidropisia (14:1-6)
* Ser um convidado humilde (14:7-11)
* Convidar os que não podem recompensar (14:12-14)
* Ilustração dos convidados que recusam o convite (14:15-24)
* Custo de ser discípulo (14:25-33)
* Sal que perde a força (14:34, 35)
* Ilustração da ovelha perdida (15:1-7)
* Ilustração da moeda perdida (15:8-10)
* Ilustração do filho pródigo (15:11-32)
* Ilustração do administrador injusto (16:1-13)
* A Lei e o Reino de Deus (16:14-18)
* Ilustração do rico e Lázaro (16:19-31)
* Jesus ensina sobre tropeços, perdão e fé (17:1-6)
* Ilustração do escravo que serve primeiro seu senhor (17:7-10)
* Jesus cura dez leprosos (17:11-19)
* Vinda do Reino de Deus (17:20-37)
* Ilustração da viúva persistente (18:1-8)
* Ilustração do fariseu e do cobrador de impostos (18:9-14)
* Jesus e as criancinhas (18:15-17)
* Líder rico pergunta sobre a vida eterna (18:18-30)
* Jesus prediz novamente sua morte e ressurreição (18:31-34)
* Jesus cura um mendigo cego perto de Jericó (18:35-43)
* Jesus visita o cobrador de impostos Zaqueu (19:1-10)
* Ilustração das dez minas (19:11-27)
****

[[v42-18-1]]

^<<v42-18-1,1>>^ Depois lhes contou uma ilustração a respeito da necessidade de sempre orarem e de nunca desistirem,

[TIP]
====
- *uma ilustração*: Ou: “uma parábola”. — Veja a nota de estudo em Mt 13:3.
- *da necessidade de sempre orarem*: Lucas é o único escritor dos Evangelhos que registrou a ilustração que está nos versículos 2 a 8. Este é mais um exemplo de como o Evangelho de Lucas dá destaque para as orações. — Lu 1:10, 13; 2:37; 3:21; 6:12; 9:28, 29; 11:1; 18:1-8; 22:39-46; 23:46.
====

[[v42-18-2]]

^<<v42-18-2,2>>^ dizendo: “Em certa cidade havia um juiz que não temia a Deus nem respeitava homem algum.

[TIP]
====
- *um juiz*: Entre os judeus, os casos jurídicos eram decididos em conjunto por pelo menos três juízes, mas parece que o juiz da ilustração de Jesus podia tomar as decisões sozinho. Além disso, o juiz não temia a Deus nem respeitava homem algum, ou seja, ele não se preocupava com o que os outros iriam pensar. Assim, pelo visto, Jesus estava se referindo a um juiz ou magistrado nomeado pelos romanos.
====

[[v42-18-3]]

^<<v42-18-3,3>>^ Havia também naquela cidade uma viúva, e ela persistia em ir a ele e a dizer: ‘Faça-me justiça contra o meu adversário.’

[[v42-18-4]]

^<<v42-18-4,4>>^ Pois bem, por um tempo ele não estava disposto a fazer isso, mas depois disse para si mesmo: ‘Eu não temo a Deus nem respeito nenhum homem,

[TIP]
====
- *nem respeito nenhum homem*: Aqui, essa expressão passa a ideia de que o juiz não se deixava intimidar pela opinião pública e que não se importava muito com o que os outros iriam pensar. — Veja a nota de estudo em Lu 18:2.
====

[[v42-18-5]]

^<<v42-18-5,5>>^ mas, visto que essa viúva fica me incomodando, farei justiça a ela para que não continue vindo me importunar com seu pedido até eu não suportar mais.’”

[TIP]
====
- *me importunar com seu pedido até eu não suportar mais*: Ou: “me dar socos até o fim.” Lit.: “me atingir debaixo [do olho] até o fim.” O verbo grego usado aqui, hypopiázo, pode ser definido como “dar um golpe no rosto; deixar com o olho roxo”. Aqui, ele é usado em sentido figurado e, pelo visto, transmite a ideia de incomodar alguém continuamente ou deixar alguém exausto. Alguns estudiosos acreditam que esse verbo passa a ideia de manchar a reputação de alguém. Do modo como foi usado aqui, ele descreve os sentimentos do juiz, que a princípio não queria dar atenção ao pedido da viúva, mas decidiu agir por causa da persistência dela. (Lu 18:1-4) Com essa ilustração, Jesus não estava dizendo que Deus era como o juiz injusto. Na verdade, Jesus queria mostrar o quanto Deus era diferente daquele juiz. O ponto era: se até um juiz injusto acabaria fazendo o que é certo, quanto mais Deus! Assim como a viúva da ilustração, os servos de Jeová devem persistir em pedir a ajuda dele. Ele é justo e vai atender aos pedidos deles, fazendo justiça. — Lu 18:6, 7.
====

[[v42-18-6]]

^<<v42-18-6,6>>^ O Senhor disse então: “Ouçam o que o juiz, embora injusto, disse!

[[v42-18-7]]

^<<v42-18-7,7>>^ Certamente, então, será que Deus não providenciará que seja feita justiça aos seus escolhidos, que clamam a ele dia e noite, ao passo que é paciente com eles?

[[v42-18-8]]

^<<v42-18-8,8>>^ Eu lhes digo: Ele providenciará que seja feita justiça a eles rapidamente. Contudo, quando o Filho do Homem chegar, achará realmente essa fé na terra?”

[TIP]
====
- *essa fé*: Ou: “esse tipo de fé”. Lit.: “a fé”. Aqui o texto grego usa o artigo definido antes da palavra “fé”. Isso indica que Jesus não estava se referindo à fé em geral, mas a um tipo específico de fé, uma fé como a da viúva da ilustração. (Lu 18:​1-8) Esse tipo de fé inclui confiar no poder da oração e no fato de que ‘Deus vai providenciar que seja feita justiça aos seus escolhidos’. Pelo visto, Jesus deixou no ar a pergunta sobre a fé para que seus discípulos avaliassem a qualidade da fé que tinham. Esse foi um bom momento para Jesus contar essa ilustração sobre oração e fé, já que ele tinha acabado de descrever os testes de fé que os discípulos enfrentariam. — Lu 17:22-​37.
====

[[v42-18-9]]

^<<v42-18-9,9>>^ Ele também contou a seguinte ilustração a alguns que confiavam na sua própria justiça e consideravam os outros como nada:

[[v42-18-10]]

^<<v42-18-10,10>>^ “Dois homens subiram ao templo para orar: um era fariseu, o outro era cobrador de impostos.

[TIP]
====
- *ao templo*: As pessoas que iam ao templo para orar não tinham permissão para entrar no Santo ou no Santíssimo, mas podiam ficar nos pátios em volta deles. Nesta ilustração de Jesus, os dois homens judeus evidentemente estão em um dos pátios do templo. — Veja o Apêndice B11.
====

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu ficou em pé e começou a orar o seguinte no íntimo: ‘Ó Deus, eu te agradeço que não sou como todos os outros: extorsores, injustos, adúlteros; nem mesmo como este cobrador de impostos.

[TIP]
====
- *extorsores*: Na época em que os romanos governavam Israel, os cobradores de impostos judeus com frequência extorquiam as pessoas. O seu cargo lhes dava muitas oportunidades para serem desonestos e, à custa do povo, enriquecer a si mesmos e aos romanos para quem trabalhavam. Jesus talvez estivesse fazendo referência a essa prática dos cobradores de impostos quando disse que o fariseu, que se considerava justo, agradeceu a Deus por não ser um extorsor.
====

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes por semana, dou o décimo de tudo que adquiro.’

[TIP]
====
- *Jejuo duas vezes por semana*: A palavra “jejum” não aparece nenhuma vez na Lei mosaica. Mas os estudiosos em geral entendem que, quando a Lei dizia que os israelitas ‘deviam afligir a si mesmos’ no Dia da Expiação, isso envolvia jejuar. (Le 16:29, nota de rodapé; Núm 29:7, nota de rodapé; Sal 35:13) Mais tarde, os israelitas passaram a jejuar em determinadas datas do ano em que a nação tinha sofrido calamidades. Mas os fariseus costumavam jejuar “duas vezes por semana”, no segundo e no quinto dias da semana. Eles queriam mostrar para os outros que eram muito dedicados a Deus. (Mt 6:16) De acordo com algumas fontes, os dias que os fariseus escolheram para jejuar eram os dias em que as pessoas normalmente faziam compras e as ruas da cidade ficavam cheias. Eles também jejuavam quando havia reuniões especiais nas sinagogas e quando os tribunais locais se reuniam.
====

[[v42-18-13]]

^<<v42-18-13,13>>^ Mas o cobrador de impostos, parado à distância, não queria nem levantar os olhos para o céu, mas batia no peito, dizendo: ‘Ó Deus, tem misericórdia de mim, um pecador.’

[TIP]
====
- *tem misericórdia de mim*: Ou: “sê benevolente comigo”. A palavra grega traduzida aqui como “tem misericórdia” aparece apenas duas vezes nas Escrituras Gregas Cristãs. Ela está relacionada com a ideia de fazer propiciação, ou expiação. Em He 2:17, ela foi traduzida no texto principal como “oferecer um sacrifício propiciatório” e na nota de rodapé como “oferecer um sacrifício de expiação; fazer expiação”.
====

[[v42-18-14]]

^<<v42-18-14,14>>^ Eu lhes digo: Este homem desceu para casa mais justo do que aquele fariseu. Porque todo aquele que se enaltecer será humilhado, mas quem se humilhar será enaltecido.”

[[v42-18-15]]

^<<v42-18-15,15>>^ As pessoas também lhe traziam suas crianças de colo, para que ele tocasse nelas; mas, quando viram isso, os discípulos começaram a repreender as pessoas.

[TIP]
====
- *crianças de colo*: Ou: “bebês”. A palavra grega usada aqui, bréfos, pode se referir a crianças de colo ou a bebês, incluindo os que ainda não nasceram. (Lu 1:41; 2:12; At 7:19; 2Ti 3:15, “infância”; 1Pe 2:2) Os relatos paralelos em Mt 19:13 e Mr 10:13 usam outra palavra grega, paidíon, que é usada na Bíblia para se referir tanto a recém-nascidos e crianças de colo (Mt 2:8; Lu 1:59) como à filha de Jairo, uma criança que já tinha 12 anos (Mr 5:39-42). O fato de Mateus e Marcos terem usado a palavra paidíon pode indicar que as pessoas levaram crianças de várias idades até Jesus. Se esse for o caso, Lucas pode ter usado a palavra bréfos apenas porque se concentrou nas crianças menores.
====

[[v42-18-16]]

^<<v42-18-16,16>>^ No entanto, Jesus mandou trazer a si as crianças de colo, dizendo: “Deixem as criancinhas vir a mim e não tentem impedi-las, pois o Reino de Deus pertence aos que são como elas.

[[v42-18-17]]

^<<v42-18-17,17>>^ Eu lhes digo a verdade: Quem não receber o Reino de Deus como uma criancinha, de modo algum entrará nele.”

[TIP]
====
- *como uma criancinha*: Veja a nota de estudo em Mr 10:15.
====

[[v42-18-18]]

^<<v42-18-18,18>>^ E um dos líderes dos judeus lhe perguntou: “Bom Instrutor, o que devo fazer para herdar a vida eterna?”

[TIP]
====
- *Bom Instrutor*: Veja a nota de estudo em Mr 10:17.
====

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus lhe disse: “Por que você me chama de bom? Ninguém é bom, a não ser um só, Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Você conhece os mandamentos: ‘Não cometa adultério, não assassine, não furte, não dê falso testemunho, honre seu pai e sua mãe.’”

[[v42-18-21]]

^<<v42-18-21,21>>^ O homem disse então: “Tenho cumprido todos esses desde bem jovem.”

[[v42-18-22]]

^<<v42-18-22,22>>^ Ao ouvir isso, Jesus lhe disse: “Ainda há uma coisa que falta a seu respeito: venda tudo o que você tem e distribua o dinheiro aos pobres, e você terá um tesouro nos céus; e venha ser meu seguidor.”

[TIP]
====
- *Jesus lhe disse*: Jesus notou que o jovem líder estava sendo sincero e, de acordo com Mr 10:21, Jesus ‘sentiu amor’ por ele. Mas Jesus talvez tenha percebido que o jovem precisava ser mais abnegado para se tornar seu discípulo. Assim, ele lhe disse: venda tudo o que você tem e distribua o dinheiro aos pobres. Antes disso, Pedro e outros já tinham deixado para trás tudo o que tinham para seguir Jesus, mas o jovem não teve coragem de fazer o mesmo. — Mt 4:20, 22; Lu 18:23, 28.
====

[[v42-18-23]]

^<<v42-18-23,23>>^ Quando ouviu isso, ele ficou profundamente triste, porque era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ Jesus olhou para ele e disse: “Como será difícil para os que têm dinheiro entrar no Reino de Deus!

[[v42-18-25]]

^<<v42-18-25,25>>^ De fato, é mais fácil um camelo passar pelo buraco de uma agulha de costura, do que um rico entrar no Reino de Deus.”

[TIP]
====
- *mais fácil um camelo passar pelo buraco de uma agulha de costura*: Aqui, Jesus usou uma hipérbole para ensinar uma lição importante. Assim como é impossível que um camelo passe pelo buraco de uma agulha, é impossível para uma pessoa rica entrar no Reino de Deus se ela continuar amando mais as riquezas do que a Jeová. Mas Jesus não quis dizer que ninguém que fosse rico poderia entrar no Reino, pois ele disse: “As coisas impossíveis para os homens são possíveis para Deus.” (Lu 18:27) Esta é a única vez que a palavra grega belóne, traduzida aqui como “agulha de costura”, aparece nas Escrituras Gregas Cristãs. Essa palavra era às vezes usada para se referir a agulhas cirúrgicas. Os relatos paralelos em Mt 19:24 e Mr 10:25 usam uma palavra grega diferente, rhafís, que foi traduzida como “agulha” e que vem de um verbo que significa “costurar”.
====

[[v42-18-26]]

^<<v42-18-26,26>>^ Os que ouviram isso disseram: “Quem é que pode ser salvo?”

[[v42-18-27]]

^<<v42-18-27,27>>^ Ele disse: “As coisas impossíveis para os homens são possíveis para Deus.”

[[v42-18-28]]

^<<v42-18-28,28>>^ Mas Pedro disse: “Veja, deixamos tudo que tínhamos e seguimos o senhor.”

[[v42-18-29]]

^<<v42-18-29,29>>^ Ele lhes disse: “Eu lhes garanto: Não há ninguém que tenha deixado casa, esposa, irmãos, pais ou filhos por causa do Reino de Deus

[[v42-18-30]]

^<<v42-18-30,30>>^ que não receba muitas vezes mais neste tempo^&#42;1^ e, no futuro sistema de coisas, a vida eterna.”

[NOTE]
====
. Ou: “no presente”.
====

[TIP]
====
- *no futuro sistema de coisas*: Ou: “na época futura”. A palavra grega usada aqui, aión, tem o sentido básico de “época”. Ela pode se referir também a uma situação existente ou a características marcantes de certo período ou época. Neste versículo, Jesus estava se referindo à época futura em que os que forem fiéis terão vida eterna debaixo do Reino de Deus. — Mr 10:29, 30; veja o Glossário, “Sistema(s) de coisas”.
====

[[v42-18-31]]

^<<v42-18-31,31>>^ Então ele chamou os Doze à parte e lhes disse: “Escutem, estamos subindo para Jerusalém, e se realizarão^&#42;1^ todas as coisas escritas por meio dos profetas a respeito do Filho do Homem.

[NOTE]
====
. Ou: “se completarão”.
====

[TIP]
====
- *subindo para Jerusalém*: Veja a nota de estudo em Mt 20:17.
====

[[v42-18-32]]

^<<v42-18-32,32>>^ Por exemplo, ele será entregue a homens das nações, e zombarão dele, o maltratarão e cuspirão nele.

[TIP]
====
- *cuspirão nele*: Veja a nota de estudo em Mr 10:34.
====

[[v42-18-33]]

^<<v42-18-33,33>>^ E, depois de açoitá-lo, o matarão, mas no terceiro dia ele será levantado.”

[[v42-18-34]]

^<<v42-18-34,34>>^ No entanto, eles não compreenderam o significado de nada disso, pois o sentido dessas palavras estava escondido deles, e eles não entenderam o que foi dito.

[[v42-18-35]]

^<<v42-18-35,35>>^ Quando Jesus estava chegando perto de Jericó, um cego estava sentado à beira da estrada, mendigando.

[TIP]
====
- *Jericó*: A primeira cidade cananeia ao oeste do rio Jordão a ser conquistada pelos israelitas. (Núm 22:1; Jos 6:1, 24, 25) Essa cidade com o tempo foi abandonada. Mas, depois que os judeus voltaram do exílio em Babilônia, eles construíram uma nova cidade no local, por causa de uma fonte de água que existia ali chamada ‘Ein es-Sultan. Na época de Jesus, os romanos já tinham construído uma nova Jericó cerca de 2 quilômetros ao sul da Jericó judaica. Isso talvez explique por que Mateus e Marcos dizem que Jesus fez aquele milagre quando estava ‘saindo de Jericó’ (Mt 20:29; Mr 10:46), enquanto Lucas diz que Jesus estava chegando perto de Jericó. É possível que Jesus tenha curado o homem cego quando estava saindo da Jericó judaica (a antiga) e indo para a romana (a nova). — Veja os Apêndices B4 e B10.
- *um cego*: O relato paralelo em Mateus (20:30) fala de dois cegos, mas Marcos (10:46) e Lucas mencionam apenas um. Pelo visto, Marcos e Lucas se concentraram apenas em Bartimeu, que é mencionado por nome apenas no Evangelho de Marcos.
====

[[v42-18-36]]

^<<v42-18-36,36>>^ Visto que ouviu uma multidão passando, ele perguntou o que estava acontecendo.

[[v42-18-37]]

^<<v42-18-37,37>>^ Disseram-lhe: “Jesus, o Nazareno, está passando!”

[[v42-18-38]]

^<<v42-18-38,38>>^ Em vista disso, ele gritou: “Jesus, Filho de Davi, tenha misericórdia de mim!”

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que estavam na frente começaram a censurá-lo, mandando que ficasse calado, mas ele gritava ainda mais: “Filho de Davi, tenha misericórdia de mim!”

[TIP]
====
- *Filho de Davi*: Ao chamar Jesus de “Filho de Davi”, aquele homem cego declarou abertamente que acreditava que Jesus era o Messias. — Veja as notas de estudo em Mt 1:1, 6.
====

[[v42-18-40]]

^<<v42-18-40,40>>^ Jesus parou, então, e ordenou que o homem lhe fosse trazido. Depois que ele se aproximou, Jesus lhe perguntou:

[[v42-18-41]]

^<<v42-18-41,41>>^ “O que você quer que eu faça por você?” Ele disse: “Senhor, deixe-me recuperar a visão.”

[[v42-18-42]]

^<<v42-18-42,42>>^ De modo que Jesus lhe disse: “Recupere a visão. A sua fé fez você ficar bom.”^&#42;1^

[NOTE]
====
. Ou: “salvou você”.
====

[[v42-18-43]]

^<<v42-18-43,43>>^ E ele recuperou instantaneamente a visão e começou a segui-lo, glorificando a Deus. Também todas as pessoas, ao verem isso, deram louvor a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]