include::./index.adoc[]

[[v42-8-0]]
=== As Boas Novas Segundo Lucas, 8
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* G. Jesus continua seu ministério na Galileia e inclui outras regiões (7:1–9:50)
* Oficial do exército demonstra fé (7:1-10)
* Jesus ressuscita o filho de uma viúva em Naim (7:11-17)
* João Batista pergunta se Jesus é “Aquele Que Vem” (7:18-23)
* Jesus elogia João Batista (7:24-30)
* Geração indiferente é condenada (7:31-35)
* Mulher pecadora derrama óleo perfumado sobre os pés de Jesus (7:36-50)
* Mulheres acompanham Jesus (8:1-3)
* Ilustração do semeador (8:4-8)
* Por que Jesus usa ilustrações (8:9, 10)
* Jesus explica a ilustração do semeador (8:11-15)
* Lâmpada não deve ser coberta (8:16-18)
* Mãe e irmãos de Jesus (8:19-21)
* Jesus acalma uma tempestade no mar da Galileia (8:22-25)
* Jesus cura um homem possesso e permite que demônios entrem em porcos (8:26-39)
* Filha de Jairo é ressuscitada; mulher toca na roupa de Jesus (8:40-56)
* Os Doze são instruídos para o ministério (9:1-6)
* Herodes fica perplexo com Jesus (9:7-9)
* Jesus alimenta cerca de 5.000 homens (9:10-17)
* Pedro identifica Jesus como o Cristo (9:18-20)
* Jesus prediz sua morte e ressurreição (9:21, 22)
* Requisitos para ser um verdadeiro discípulo (9:23-27)
* Transfiguração de Jesus (9:28-36)
* Jesus cura um menino possesso de demônio (9:37-43a)
* Jesus prediz pela segunda vez sua morte (9:43b-45)
* Discípulos discutem sobre quem é o maior (9:46-48)
* “Quem não é contra vocês é a favor de vocês” (9:49, 50)
****

[[v42-8-1]]

^<<v42-8-1,1>>^ Pouco tempo depois, ele começou a viajar de cidade em cidade e de aldeia em aldeia, pregando e declarando as boas novas do Reino de Deus. E os Doze estavam com ele,

[TIP]
====
- *pregando*: Veja a nota de estudo em Mt 3:1.
====

[[v42-8-2]]

^<<v42-8-2,2>>^ bem como algumas mulheres que tinham sido curadas de espíritos maus e de doenças: Maria, que era chamada Madalena, de quem saíram sete demônios;

[TIP]
====
- *Maria, que era chamada Madalena*: Essa Maria, muitas vezes chamada de Maria Madalena, é mencionada pela primeira vez no Evangelho de Lucas neste relato sobre o segundo ano do ministério de Jesus. O nome Madalena (que significa “de Magdala; pertencente a Magdala”) provavelmente vem do nome da cidade de Magdala e servia para diferenciá-la de outras Marias. Essa cidade ficava na margem oeste do mar da Galileia, mais ou menos no meio do caminho entre Cafarnaum e Tiberíades. Alguns sugerem que Maria nasceu em Magdala ou que morava ali. Todas as outras vezes em que Maria Madalena é mencionada na Bíblia estão ligadas à morte e ressurreição de Jesus. — Mt 27:55, 56, 61; Mr 15:40; Lu 24:10; Jo 19:25.
====

[[v42-8-3]]

^<<v42-8-3,3>>^ Joana, esposa de Cuza, encarregado da casa de Herodes; Susana; e muitas outras mulheres que, com os seus próprios bens, ajudavam a eles.

[TIP]
====
- *Joana*: Forma feminina mais curta do nome hebraico Jeoanã, que significa “Jeová mostrou favor; Jeová foi bondoso”. Joana, uma das mulheres que foram curadas por Jesus, só é mencionada duas vezes nas Escrituras Gregas Cristãs, as duas vezes no Evangelho de Lucas. — Lu 24:10.
- *Cuza*: Ele era encarregado, ou administrador, da casa de Herodes Antipas, o que possivelmente envolvia supervisionar assuntos domésticos.
- *ajudavam a eles*: Ou: “apoiavam a eles; faziam provisões para eles”. A palavra grega diakonéo pode se referir a cuidar do bem-estar de outros por obter, preparar e servir alimentos, entre outras coisas. Ela é usada com um sentido parecido em Lu 10:40 (“cuidar das coisas”), Lu 12:37; 17:8 (‘servir’) e At 6:2 (“servir alimento”), mas também pode se referir a qualquer outro serviço de natureza pessoal. Aqui, a palavra diakonéo é usada para descrever como as mulheres mencionadas nos versículos 2 e 3 apoiavam Jesus e seus discípulos, ajudando-os a cumprir a designação que tinham recebido de Deus. Ao fazer isso, aquelas mulheres davam honra a Jeová. E Jeová mostrou que valorizava a bondade e a generosidade delas fazendo com que os escritores da Bíblia registrassem o que elas fizeram, para que as futuras gerações pudessem ler. (Pr 19:17; He 6:​10) Os textos de Mt 27:55 e Mr 15:41 também usam essa palavra para falar da ajuda que algumas mulheres davam a Jesus. — Para informações sobre o substantivo relacionado, diákonos, veja a nota de estudo em Lu 22:26.
====

[[v42-8-4]]

^<<v42-8-4,4>>^ Quando uma grande multidão se juntou aos que vinham a ele de uma cidade após outra, ele falou por meio de uma ilustração:

[TIP]
====
- *uma ilustração*: Veja a nota de estudo em Mt 13:3.
====

[[v42-8-5]]

^<<v42-8-5,5>>^ “Um semeador saiu para semear as suas sementes. Ao passo que semeava, algumas delas caíram à beira da estrada e foram pisadas, e as aves do céu as comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Algumas caíram sobre a rocha e, depois de brotar, secaram, porque não tinham umidade.

[TIP]
====
- *sobre a rocha*: Veja a nota de estudo em Mt 13:5.
====

[[v42-8-7]]

^<<v42-8-7,7>>^ Outras caíram entre os espinhos, e os espinhos que cresceram com elas as sufocaram.

[TIP]
====
- *entre os espinhos*: Veja a nota de estudo em Mt 13:7.
====

[[v42-8-8]]

^<<v42-8-8,8>>^ Mas outras caíram em solo bom e, depois de brotar, produziram fruto cem vezes mais.” Depois de lhes dizer isso, falou bem alto: “Quem tem ouvidos para escutar, escute.”

[[v42-8-9]]

^<<v42-8-9,9>>^ Mas os seus discípulos lhe perguntaram o que significava essa ilustração.

[[v42-8-10]]

^<<v42-8-10,10>>^ Ele disse: “A vocês é concedido entender^&#42;1^ os segredos sagrados do Reino de Deus, mas aos demais tudo é apresentado em ilustrações, para que olhem, mas olhem em vão, e ouçam, mas não compreendam.

[NOTE]
====
. Ou: “Foi permitido que vocês entendessem”.
====

[TIP]
====
- *segredos sagrados*: Veja a nota de estudo em Mt 13:11.
====

[[v42-8-11]]

^<<v42-8-11,11>>^ A ilustração significa o seguinte: a semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ Aquelas à beira da estrada representam os que ouviram, e depois vem o Diabo e tira do coração deles a palavra, a fim de que não creiam e não sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ Aquelas sobre a rocha representam os que, quando ouvem a palavra, a recebem com alegria, mas não têm raiz. Creem por um tempo, mas numa época de prova se desviam.

[[v42-8-14]]

^<<v42-8-14,14>>^ Aquelas que caíram entre os espinhos representam os que ouviram, mas, por se deixarem levar pelas ansiedades, pelas riquezas e pelos prazeres desta vida, ficam completamente sufocados e não produzem frutos maduros.

[[v42-8-15]]

^<<v42-8-15,15>>^ Aquelas em solo bom representam os que, depois de ouvirem a palavra com um coração sincero e bom, a retêm e dão fruto com perseverança.

[[v42-8-16]]

^<<v42-8-16,16>>^ “Ninguém, depois de acender uma lâmpada, a cobre com um recipiente ou a coloca debaixo de uma cama, mas a coloca em cima de um suporte, para que os que entram possam ver a luz.

[TIP]
====
- *uma lâmpada*: Veja a nota de estudo em Mt 5:15.
====

[[v42-8-17]]

^<<v42-8-17,17>>^ Pois não há nada escondido que não venha a ser revelado, nem há nada cuidadosamente oculto que nunca se torne conhecido e nunca venha à tona.

[[v42-8-18]]

^<<v42-8-18,18>>^ Portanto, prestem atenção a como escutam; pois àquele que tem, mais será dado, mas daquele que não tem, até mesmo o que imagina ter será tirado.”

[[v42-8-19]]

^<<v42-8-19,19>>^ E sua mãe e seus irmãos chegaram, mas não conseguiram se aproximar dele por causa da multidão.

[TIP]
====
- *irmãos*: Veja a nota de estudo em Mt 12:46.
====

[[v42-8-20]]

^<<v42-8-20,20>>^ Então, foi-lhe dito: “Sua mãe e seus irmãos estão lá fora, querendo vê-lo.”

[[v42-8-21]]

^<<v42-8-21,21>>^ Ele lhes respondeu: “Minha mãe e meus irmãos são estes que ouvem a palavra de Deus e a praticam.”

[TIP]
====
- *Minha mãe e meus irmãos*: Jesus fez aqui um contraste entre seus irmãos de sangue e seus irmãos espirituais, os discípulos. Pelo visto, alguns dos meios-irmãos de Jesus não tinham fé nele. (Jo 7:5) Jesus mostrou que, por mais que amasse os membros de sua família, o amor que sentia pelos que ouvem a palavra de Deus e a praticam era ainda maior.
====

[[v42-8-22]]

^<<v42-8-22,22>>^ Certo dia, ele e seus discípulos entraram num barco, e ele lhes disse: “Passemos para a outra margem do lago.” Assim, partiram.

[TIP]
====
- *a outra margem*: Ou seja, a margem leste do mar da Galileia.
====

[[v42-8-23]]

^<<v42-8-23,23>>^ Mas, enquanto navegavam, ele adormeceu. Então uma violenta tempestade desabou sobre o lago; o barco começou a ficar inundado e estava em perigo.

[TIP]
====
- *uma violenta tempestade*: Essa expressão, que em grego é formada por duas palavras, poderia ser traduzida literalmente como “um furacão de vento”. (Veja a nota de estudo em Mr 4:37.) Tempestades assim são comuns no mar da Galileia. A superfície desse lago fica uns 210 metros abaixo do nível do mar. O ar sobre ele é mais quente do que o ar das planícies e montes que ficam em volta. Essa diferença de temperatura causa perturbações atmosféricas e ventos fortes que, de uma hora para outra, podem levantar grandes ondas.
====

[[v42-8-24]]

^<<v42-8-24,24>>^ Por isso o acordaram, dizendo: “Instrutor, Instrutor, estamos prestes a morrer!” Ele se levantou e censurou o vento e a fúria da água; eles pararam, e houve uma calmaria.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então ele lhes disse: “Onde está a sua fé?” Mas eles ficaram com muito medo e espantados, e diziam uns aos outros: “Quem é realmente este homem? Pois dá ordens até mesmo aos ventos e à água, e eles lhe obedecem.”

[[v42-8-26]]

^<<v42-8-26,26>>^ E chegaram à margem, na região dos gerasenos, que fica no lado oposto à Galileia.

[TIP]
====
- *região dos gerasenos*: Uma região no lado oposto (a margem leste) do mar da Galileia. Não se sabe ao certo os limites exatos dessa região e o local a que ela corresponderia hoje em dia. Alguns sugerem que a “região dos gerasenos” seja a região em volta de Kursi, perto das encostas íngremes que ficam na margem leste do mar da Galileia. Outros acreditam que ela fosse maior, e começasse na cidade de Gerasa (Jerash), uns 55 quilômetros ao sudeste, se estendendo dali até o mar da Galileia. O texto de Mt 8:​28 usa o nome “região dos gadarenos”. (Veja as notas de estudo em Mt 8:28; Mr 5:1.) Embora os Evangelhos usem nomes de regiões diferentes para indicar o local onde Jesus desembarcou, eles se referem basicamente à mesma área na costa leste do mar da Galileia. Esse local talvez fosse considerado parte das duas regiões. Assim, os relatos não entram em contradição. — Veja “Acontecimentos no mar da Galileia” no Mapa 3B do Apêndice A7-D e o Apêndice B10.
- *gerasenos*: Veja a nota de estudo em Mr 5:1.
====

[[v42-8-27]]

^<<v42-8-27,27>>^ Quando Jesus desembarcou em terra, um homem da cidade possesso de demônios foi ao encontro dele. Fazia bastante tempo que ele não usava roupa, e ele não ficava em uma casa, mas sim entre os túmulos.^&#42;1^

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[TIP]
====
- *um homem . . . possesso de demônios*: Mateus (8:28) menciona dois homens, mas Marcos (5:2) e Lucas mencionam apenas um. Pelo visto, Marcos e Lucas concentraram seus relatos em apenas um dos homens possessos de demônios porque foi com ele que Jesus falou e porque a situação dele era mais grave. É possível que aquele homem fosse o mais violento ou estivesse sendo controlado por demônios por mais tempo. Também é possível que, depois de os dois homens terem sido curados, apenas um deles quisesse acompanhar Jesus. — Lu 8:37-39.
- *túmulos*: Veja a nota de estudo em Mt 8:28.
====

[[v42-8-28]]

^<<v42-8-28,28>>^ Ao ver Jesus, gritou e se prostrou diante dele, e disse bem alto: “O que você quer comigo, Jesus, Filho do Deus Altíssimo? Eu lhe suplico que não me atormente.”

[TIP]
====
- *O que você quer comigo, . . . ?*: Veja a nota de estudo em Mr 5:7.
- *me atormente*: A expressão grega usada aqui está relacionada com uma palavra que foi traduzida em Mt 18:34 como “carcereiros”. Assim, quando pediram para Jesus não “atormentá-los”, os demônios pelo visto estavam pedindo para Jesus não prendê-los no “abismo” mencionado em Lu 8:31. — Veja a nota de estudo em Mt 18:34.
====

[[v42-8-29]]

^<<v42-8-29,29>>^ (Pois Jesus tinha ordenado ao espírito impuro que saísse do homem. O espírito tinha se apoderado dele em muitas ocasiões,^&#42;1^ e ele havia sido preso repetidas vezes com correntes nas mãos e nos pés, e era vigiado, mas arrebentava as correntes e era levado pelo demônio para os lugares isolados.)

[NOTE]
====
. Ou, possivelmente: “O espírito o tinha segurado por muito tempo”.
====

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus lhe perguntou: “Qual é o seu nome?” Ele disse: “Legião”, pois muitos demônios haviam entrado nele.

[TIP]
====
- *Legião*: Veja a nota de estudo em Mr 5:9.
====

[[v42-8-31]]

^<<v42-8-31,31>>^ E lhe suplicavam que não os mandasse para o abismo.

[TIP]
====
- *o abismo*: Ou: “o lugar profundo”. A palavra grega ábyssos significa “extremamente profundo” ou “insondável; ilimitado”, e se refere a um lugar ou condição de confinamento ou prisão. Ela é usada nove vezes nas Escrituras Gregas Cristãs: uma vez neste versículo, uma vez em Ro 10:7 e sete vezes em Apocalipse. Em Ap 20:1-3, a Bíblia mostra que Satanás será lançado no abismo e ficará preso ali por 1.000 anos. Pode ser que a legião de demônios estivesse pensando nesse acontecimento futuro quando suplicou que Jesus não a mandasse “para o abismo”. No versículo 28, um dos demônios pediu para Jesus não “atormentá-lo”. O relato paralelo em Mt 8:29 diz que os demônios perguntaram a Jesus: “Veio aqui nos atormentar antes do tempo determinado?” Assim, parece que o ‘tormento’ de que os demônios estavam falando era serem aprisionados ‘no abismo’. — Veja o Glossário e a nota de estudo em Mt 8:29.
====

[[v42-8-32]]

^<<v42-8-32,32>>^ Uma grande manada de porcos estava pastando ali no monte; por isso lhe suplicaram que lhes permitisse entrar nos porcos, e ele lhes deu permissão.

[TIP]
====
- *porcos*: Os porcos eram animais impuros de acordo com a Lei. (Le 11:7) O relato não diz se “os que cuidavam dos porcos” (Lu 8:34) eram judeus que estavam desobedecendo a Lei ou se eram pessoas de outras nações. O que se sabe é que a carne de porco era comercializada na região de Decápolis. Muitos gregos e romanos moravam ali e consideravam a carne de porco uma iguaria.
====

[[v42-8-33]]

^<<v42-8-33,33>>^ Os demônios saíram então do homem e entraram nos porcos, e a manada se jogou despenhadeiro^&#42;1^ abaixo, para dentro do lago, e se afogou.

[NOTE]
====
. Ou: “encosta íngreme”.
====

[[v42-8-34]]

^<<v42-8-34,34>>^ Mas, quando os que cuidavam dos porcos viram o que tinha acontecido, fugiram e contaram isso na cidade e na zona rural.

[[v42-8-35]]

^<<v42-8-35,35>>^ As pessoas saíram então para ver o que havia acontecido. Quando se aproximaram de Jesus, encontraram o homem de quem haviam saído os demônios, vestido e em perfeito juízo, sentado aos pés de Jesus; e ficaram com medo.

[[v42-8-36]]

^<<v42-8-36,36>>^ Os que tinham visto tudo aquilo contaram a eles como o homem possesso de demônios havia ficado bom.^&#42;1^

[NOTE]
====
. Ou: “havia sido salvo”.
====

[[v42-8-37]]

^<<v42-8-37,37>>^ E muitas pessoas da região dos gerasenos, ao redor, pediram a Jesus que se afastasse deles, porque estavam tomados de grande medo. Então ele entrou no barco para partir.

[[v42-8-38]]

^<<v42-8-38,38>>^ No entanto, o homem de quem os demônios haviam saído implorava para continuar com ele, mas ele mandou o homem embora, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ “Volte para casa e sempre fale sobre o que Deus fez por você.” Assim, ele foi embora, proclamando em toda a cidade o que Jesus havia feito por ele.

[TIP]
====
- *sempre fale sobre o que Deus fez por você*: Jesus geralmente pedia que as pessoas não falassem a outros sobre seus milagres. (Mr 1:44; 3:12; 7:36; Lu 5:14) Mas nessa ocasião ele orientou o homem a contar a seus parentes o que tinha acontecido. Talvez Jesus tenha feito isso porque não pregaria mais naquela região, já que as pessoas dali tinham pedido que ele fosse embora. O bom testemunho daquele homem também serviria para contradizer comentários negativos que talvez surgissem por causa da morte dos porcos.
- *toda a cidade*: O relato paralelo em Mr 5:20 diz “em Decápolis”. Assim, ao que tudo indica, a cidade mencionada aqui ficava na região de Decápolis. — Veja o Glossário, “Decápolis”.
====

[[v42-8-40]]

^<<v42-8-40,40>>^ Quando Jesus voltou, a multidão o recebeu bondosamente, pois todos o esperavam.

[[v42-8-41]]

^<<v42-8-41,41>>^ Chegou então um homem chamado Jairo; esse homem era presidente da sinagoga. E ele se prostrou aos pés de Jesus e começou a lhe suplicar que fosse à sua casa,

[[v42-8-42]]

^<<v42-8-42,42>>^ porque sua filha única, que tinha cerca de 12 anos, estava morrendo.
Enquanto Jesus ia, as multidões se apertavam em volta dele.

[TIP]
====
- *única*: A palavra grega monogenés foi traduzida como “unigênito; unigênita” em todas as ocorrências nas edições anteriores da Tradução do Novo Mundo. Ela pode ser definida como “único de sua espécie; sem igual; único de uma classe ou espécie; ímpar”. Aqui, ela se refere a uma “filha única”, mas pode ser usada para se referir tanto a filhos como a filhas. Essa mesma palavra grega é usada para falar do filho “único” de uma viúva em Naim e de um menino a quem Jesus curou que era o filho “único” de um homem. (Lu 7:12; 9:38) A Septuaginta usa monogenés para se referir à filha de Jefté em Jz 11:34, que diz: “Ela era sua filha única; além dela, ele não tinha nem filho nem filha.” Nos livros bíblicos que o apóstolo João escreveu, ele usou monogenés cinco vezes ao falar de Jesus. — Para informações sobre o significado desse termo quando usado para se referir a Jesus, veja as notas de estudo em Jo 1:14; 3:16.
====

[[v42-8-43]]

^<<v42-8-43,43>>^ Havia uma mulher que por 12 anos sofria de um fluxo de sangue e não havia conseguido cura da parte de ninguém.

[TIP]
====
- *fluxo de sangue*: Veja a nota de estudo em Mt 9:20.
====

[[v42-8-44]]

^<<v42-8-44,44>>^ Ela se aproximou dele por trás e tocou na borda^&#42;1^ da sua roupa, e o seu fluxo de sangue parou imediatamente.

[NOTE]
====
. Ou: “extremidade; franja; borla”.
====

[[v42-8-45]]

^<<v42-8-45,45>>^ De modo que Jesus perguntou: “Quem me tocou?” Como todos negavam, Pedro disse: “Instrutor, as multidões rodeiam e apertam o senhor.”

[[v42-8-46]]

^<<v42-8-46,46>>^ Mas Jesus disse: “Alguém me tocou, pois eu sei^&#42;1^ que saiu poder de mim.”

[NOTE]
====
. Ou: “eu percebi”.
====

[[v42-8-47]]

^<<v42-8-47,47>>^ Vendo que não havia passado despercebida, a mulher se aproximou trêmula, se prostrou diante dele e declarou perante todos por que o havia tocado e como tinha sido curada imediatamente.

[[v42-8-48]]

^<<v42-8-48,48>>^ Mas ele disse a ela: “Filha, a sua fé fez você ficar boa.^&#42;1^ Vá em paz.”

[NOTE]
====
. Ou: “salvou você”.
====

[TIP]
====
- *Filha*: Veja a nota de estudo em Mr 5:34.
- *Vá em paz*: Veja a nota de estudo em Mr 5:34.
====

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto ele ainda falava, chegou um representante do presidente da sinagoga, dizendo: “Sua filha morreu. Não incomode mais o Instrutor.”

[[v42-8-50]]

^<<v42-8-50,50>>^ Ouvindo isso, Jesus lhe respondeu: “Não tenha medo, apenas tenha fé, e ela será salva.”

[[v42-8-51]]

^<<v42-8-51,51>>^ Quando chegou à casa, não deixou ninguém entrar com ele, a não ser Pedro, João e Tiago, e o pai e a mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ Mas todos choravam e batiam no peito de pesar por ela. De modo que ele disse: “Parem de chorar, pois ela não morreu; está dormindo.”

[TIP]
====
- *não morreu; está dormindo*: Veja a nota de estudo em Mr 5:39.
====

[[v42-8-53]]

^<<v42-8-53,53>>^ Em vista disso, começaram a rir dele com desprezo, porque sabiam que ela havia morrido.

[[v42-8-54]]

^<<v42-8-54,54>>^ Mas ele a pegou pela mão e a chamou: “Menina, levante-se!”^&#42;1^

[NOTE]
====
. Ou: “acorde!”
====

[[v42-8-55]]

^<<v42-8-55,55>>^ E o espírito dela voltou e ela se levantou imediatamente, e ele ordenou que lhe dessem algo para comer.

[TIP]
====
- *o espírito*: Ou: “a força de vida; o fôlego”. Neste contexto, a palavra grega pneúma provavelmente se refere à força que mantém vivas todas as criaturas terrestres, ou simplesmente ao fôlego. — Veja a nota de estudo em Mt 27:50.
====

[[v42-8-56]]

^<<v42-8-56,56>>^ Os pais dela estavam fora de si, mas ele lhes ordenou que não dissessem a ninguém o que tinha acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]