include::./index.adoc[]

[[v42-10-0]]
=== As Boas Novas Segundo Lucas, 10
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. Jesus se dirige para Jerusalém; Jesus continua seu ministério, principalmente na Judeia e na Pereia (9:51–19:27)
* Aldeia samaritana rejeita Jesus (9:51-56)
* Requisitos para seguir Jesus (9:57-62)
* Jesus envia os 70 (10:1-12)
* Corazim, Betsaida e Cafarnaum são repreendidas por não se arrependerem (10:13-16)
* Os 70 voltam (10:17-20)
* Jesus louva seu Pai por favorecer os humildes (10:21-24)
* Ilustração do bom samaritano (10:25-37)
* Jesus visita Marta e Maria (10:38-42)
* Jesus ensina a oração-modelo (11:1-4)
* Ilustração do amigo persistente (11:5-13)
* Jesus explica que os demônios são expulsos “por meio do dedo de Deus” (11:14-23)
* Jesus fala da volta de um espírito impuro (11:24-26)
* Explicação sobre a verdadeira felicidade (11:27, 28)
* Sinal de Jonas (11:29-32)
* Olho é a lâmpada do corpo (11:33-36)
* Jesus come com um fariseu; ai dos religiosos hipócritas (11:37-54)
* “Tomem cuidado com o fermento dos fariseus” (12:1-3)
* Temer a Deus, não a homens (12:4-7)
* Declarar que está em união com Cristo (12:8-12)
* Ilustração do rico insensato (12:13-21)
* “Parem de se preocupar tanto com a sua vida” (12:22-31)
* “Não tema, pequeno rebanho” (12:32-34)
* Manter a vigilância (12:35-40)
* Identificação do administrador fiel e características de um escravo infiel (12:41-48)
* Não paz, mas divisão (12:49-53)
* Necessidade de examinar os tempos (12:54-56)
* Resolver disputas (12:57-59)
* Arrepender-se ou ser destruído (13:1-5)
* Ilustração da figueira infrutífera (13:6-9)
* Jesus cura no sábado uma mulher encurvada (13:10-17)
* Ilustrações do grão de mostarda e do fermento (13:18-21)
* É preciso esforço para entrar pela porta estreita (13:22-30)
* Jesus chama Herodes de ‘aquela raposa’ (13:31-33)
* Jesus lamenta por Jerusalém (13:34, 35)
* Jesus cura no sábado um homem com hidropisia (14:1-6)
* Ser um convidado humilde (14:7-11)
* Convidar os que não podem recompensar (14:12-14)
* Ilustração dos convidados que recusam o convite (14:15-24)
* Custo de ser discípulo (14:25-33)
* Sal que perde a força (14:34, 35)
* Ilustração da ovelha perdida (15:1-7)
* Ilustração da moeda perdida (15:8-10)
* Ilustração do filho pródigo (15:11-32)
* Ilustração do administrador injusto (16:1-13)
* A Lei e o Reino de Deus (16:14-18)
* Ilustração do rico e Lázaro (16:19-31)
* Jesus ensina sobre tropeços, perdão e fé (17:1-6)
* Ilustração do escravo que serve primeiro seu senhor (17:7-10)
* Jesus cura dez leprosos (17:11-19)
* Vinda do Reino de Deus (17:20-37)
* Ilustração da viúva persistente (18:1-8)
* Ilustração do fariseu e do cobrador de impostos (18:9-14)
* Jesus e as criancinhas (18:15-17)
* Líder rico pergunta sobre a vida eterna (18:18-30)
* Jesus prediz novamente sua morte e ressurreição (18:31-34)
* Jesus cura um mendigo cego perto de Jericó (18:35-43)
* Jesus visita o cobrador de impostos Zaqueu (19:1-10)
* Ilustração das dez minas (19:11-27)
****

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso, o Senhor designou mais 70 e os enviou de dois em dois, na sua frente, a toda cidade e lugar aonde ele mesmo estava para ir.

[TIP]
====
- *Depois disso*: Os acontecimentos relatados em Lu 10:1 a 18:14 não aparecem em nenhum outro Evangelho. Mas em outras ocasiões, pelo visto mais cedo em seu ministério, Jesus tratou de alguns dos mesmos assuntos mencionados nesses capítulos, e isso foi registrado nos outros Evangelhos. Tudo indica que os acontecimentos descritos em Lu 10:1 a 18:14 ocorreram depois da Festividade das Tendas (Barracas) de 32 d.C. (Veja o Apêndice A7-E.) Parece que, nessa época, Jesus passou a concentrar suas atividades na região de Jerusalém e dos distritos da Judeia e da Pereia. Nos últimos seis meses de sua vida na Terra, Jesus passou a maior parte do tempo pregando ali.
- *70*: Alguns dos manuscritos mais antigos dizem “72”, e há traduções da Bíblia que seguem esses manuscritos. Mas vários outros dizem “70”, incluindo alguns dos mais confiáveis, como o Códice Sinaítico (século 4 d.C.), o Códice Alexandrino (século 5 d.C.) e o Códice Ephraemi Syri rescriptus (século 5 d.C.). Os estudiosos dão várias explicações possíveis para essa pequena diferença entre os manuscritos. De qualquer forma, ela não afeta o sentido do que é dito neste versículo. Os muitos manuscritos e traduções antigas de Lucas concordam no ponto principal, que Jesus enviou um grande número de discípulos de dois em dois (em pares) para pregar.
- *mais 70*: Tudo indica que se refere a 70 discípulos além dos 12 apóstolos, que já tinham sido treinados por Jesus e enviados numa ocasião anterior. — Lu 9:1-6.
====

[[v42-10-2]]

^<<v42-10-2,2>>^ Ele lhes disse então: “A colheita, realmente, é grande, mas os trabalhadores são poucos. Por isso, peçam ao Senhor da colheita que mande trabalhadores para a Sua colheita.

[[v42-10-3]]

^<<v42-10-3,3>>^ Vão! Eu os envio como cordeiros no meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não levem bolsa de dinheiro, nem bolsa de provisões, nem sandálias, e não cumprimentem ninguém ao longo da estrada.

[TIP]
====
- *sandálias*: Jesus não queria dizer que seus discípulos não deviam usar sandálias em sua viagem. Em vez disso, ele disse para eles não levarem sandálias, provavelmente se referindo a um par além daquele que eles estavam calçando. Naquele tempo, era comum levar sandálias extras quando se fazia uma viagem longa, para o caso de a sola se gastar ou dos cordões arrebentarem. Em uma ocasião anterior, quando Jesus deu uma orientação parecida com essa, ele ordenou que seus discípulos “calçassem [ou, “amarrassem”]” suas sandálias, ou seja, as que já tinham. (Mr 6:8, 9) Além disso, em Mt 10:9, 10 Jesus disse que eles não deviam ‘adquirir sandálias’, ou seja, não deviam comprar um par extra.
- *não cumprimentem ninguém*: Ou: “não abracem a ninguém em cumprimento”. Em algumas situações, a palavra grega aspázomai (“cumprimentar”) podia se referir a mais do que simplesmente dizer “olá” ou “bom dia”. Ela também podia incluir os abraços e as longas conversas que são comuns quando amigos se encontram. Jesus não estava dizendo que seus discípulos deviam ser rudes. Em vez disso, ele estava destacando que eles deviam aproveitar seu tempo da melhor forma possível, evitando qualquer distração desnecessária. O profeta Eliseu certa vez deu instruções parecidas a seu ajudante, Geazi. (2Rs 4:29) Tanto Geazi quanto os discípulos de Jesus tinham uma missão urgente. Assim, eles não tinham tempo a perder.
====

[[v42-10-5]]

^<<v42-10-5,5>>^ Em qualquer casa onde entrarem, digam primeiro: ‘Haja paz nesta casa.’

[[v42-10-6]]

^<<v42-10-6,6>>^ E, se ali houver um amigo da paz, a paz de vocês descansará sobre ele. Mas, se não houver, ela voltará para vocês.

[TIP]
====
- *amigo da paz*: Lit.: “filho da paz”. Lucas escreveu seu Evangelho em grego, mas essas palavras pelo visto vêm de uma expressão idiomática hebraica que transmite a ideia de alguém que ama a paz, uma pessoa pacífica. Aqui, a expressão se refere a alguém que deseja se reconciliar com Deus e que escuta e aceita com alegria “as boas novas de paz”. Por fazer isso, ele passa a estar em paz com Deus. — At 10:36.
====

[[v42-10-7]]

^<<v42-10-7,7>>^ Assim, fiquem naquela casa, comendo e bebendo as coisas que lhes oferecerem, porque o trabalhador é digno do seu salário. Não fiquem mudando de uma casa para outra.

[TIP]
====
- *Não fiquem mudando de uma casa para outra*: Em uma ocasião anterior, Jesus tinha dado aos 12 apóstolos instruções parecidas com as que deu aqui aos 70 discípulos. (Mt 10:11; Mr 6:10; Lu 9:4) Quando chegassem numa cidade, eles deveriam ficar na casa de quem oferecesse hospedagem a eles, em vez de mudar de uma casa para outra. Eles não deviam ficar procurando uma casa em que o anfitrião pudesse oferecer mais conforto, diversão ou coisas materiais. Assim eles mostrariam que essas coisas eram menos importantes para eles do que o trabalho de pregação.
====

[[v42-10-8]]

^<<v42-10-8,8>>^ “Também, onde quer que vocês entrarem numa cidade e as pessoas os receberem, comam o que for colocado diante de vocês,

[[v42-10-9]]

^<<v42-10-9,9>>^ curem os doentes nela e digam-lhes: ‘O Reino de Deus está próximo de vocês.’

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas, onde quer que entrarem numa cidade e as pessoas não os receberem, saiam para as suas ruas principais e digam:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Nós sacudiremos até mesmo o pó da sua cidade que grudou nos nossos pés, em testemunho contra vocês. Contudo, saibam do seguinte: o Reino de Deus está próximo.’

[[v42-10-12]]

^<<v42-10-12,12>>^ Eu lhes digo que naquele dia será mais suportável para Sodoma do que para essa cidade.

[TIP]
====
- *será mais suportável*: Pelo visto, essa comparação era uma hipérbole, e Jesus não esperava que suas palavras fossem entendidas literalmente. (Compare com outras vezes em que Jesus usou hipérboles, como em Mt 5:18; Lu 16:17 e 21:33.) Quando Jesus disse que “naquele dia [o dia do julgamento] será mais suportável para Sodoma” (Mt 10:15; 11:22, 24; Lu 10:14), ele não estava afirmando que os habitantes de Sodoma estarão presentes no dia do julgamento. (Veja Judas 7.) Pode ser que Jesus estivesse apenas querendo mostrar o tamanho da culpa dos que não reagiam à mensagem do Reino. Essa era a situação da maioria das pessoas das cidades de Corazim, Betsaida e Cafarnaum. (Lu 10:13-15) O que aconteceu com a cidade de Sodoma se tornou muito conhecido e, com frequência, era citado quando se falava de julgamentos de Deus e de sua ira. — De 29:23; Is 1:9; La 4:6.
====

[[v42-10-13]]

^<<v42-10-13,13>>^ “Ai de você, Corazim! Ai de você, Betsaida! Porque, se as obras poderosas que ocorreram em vocês tivessem ocorrido em Tiro e Sídon, há muito tempo elas teriam se arrependido, sentadas em pano de saco e em cinzas.

[TIP]
====
- *Tiro e Sídon*: Essas duas cidades, que não faziam parte de Israel, ficavam na Fenícia, uma região na costa do mar Mediterrâneo. — Veja o Apêndice B10.
====

[[v42-10-14]]

^<<v42-10-14,14>>^ Por isso, no julgamento, será mais suportável para Tiro e Sídon do que para vocês.

[[v42-10-15]]

^<<v42-10-15,15>>^ E você, Cafarnaum, será por acaso enaltecida ao céu? Até a Sepultura você descerá!

[TIP]
====
- *céu*: Veja a nota de estudo em Mt 11:23.
- *a Sepultura*: Veja a nota de estudo em Mt 11:23.
====

[[v42-10-16]]

^<<v42-10-16,16>>^ “Quem escuta vocês escuta a mim. E quem desconsidera vocês desconsidera também a mim. Além disso, quem desconsidera a mim desconsidera também Aquele que me enviou.”

[[v42-10-17]]

^<<v42-10-17,17>>^ Os 70 voltaram então com alegria, dizendo: “Senhor, até mesmo os demônios nos obedecem pelo uso do seu nome.”

[TIP]
====
- *70*: Veja a nota de estudo em Lu 10:1.
====

[[v42-10-18]]

^<<v42-10-18,18>>^ Em vista disso, ele lhes disse: “Vejo Satanás já caído como relâmpago do céu.

[TIP]
====
- *Vejo Satanás já caído como relâmpago do céu*: Tudo indica que Jesus estava profetizando, dizendo que podia ver Satanás sendo expulso do céu, como se isso já tivesse acontecido. O texto de Ap 12:7-9 descreve a guerra no céu, e o contexto mostra que a queda de Satanás estaria ligada ao nascimento do Reino messiânico. Jesus estava mostrando que a vitória sobre Satanás e seus demônios nessa futura guerra no céu já estava garantida, pois Deus tinha acabado de dar para aqueles 70 discípulos, simples humanos imperfeitos, o poder de expulsar demônios. — Lu 10:17.
====

[[v42-10-19]]

^<<v42-10-19,19>>^ Escutem: Eu dei a vocês autoridade para pisar serpentes e escorpiões, e sobre todo o poder do inimigo, e absolutamente nada lhes fará mal.

[TIP]
====
- *serpentes e escorpiões*: Jesus não estava falando de serpentes e escorpiões literais. Aqui, ele usou esses animais para representar coisas que são prejudiciais. — Compare com Ez 2:6.
====

[[v42-10-20]]

^<<v42-10-20,20>>^ Contudo, não se alegrem porque os espíritos estão sendo sujeitos a vocês, mas alegrem-se porque os nomes de vocês foram escritos nos céus.”

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela mesma hora ele ficou cheio de alegria por meio do espírito santo e disse: “Eu te louvo publicamente, Pai, Senhor do céu e da terra, porque escondeste cuidadosamente essas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos. Sim, ó Pai, porque tu te agradaste de fazer as coisas dessa maneira.

[TIP]
====
- *aos pequeninos*: Veja a nota de estudo em Mt 11:25.
====

[[v42-10-22]]

^<<v42-10-22,22>>^ Tudo me foi entregue por meu Pai. E ninguém sabe quem o Filho é, exceto o Pai; e ninguém sabe quem o Pai é, exceto o Filho e aquele a quem o Filho quiser revelá-lo.”

[[v42-10-23]]

^<<v42-10-23,23>>^ Com isso, ele se virou para os discípulos e lhes disse em particular: “Felizes são os olhos que veem as coisas que vocês estão vendo.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu lhes digo: Muitos profetas e reis desejaram ver as coisas que vocês estão observando, mas não as viram, e ouvir as coisas que vocês estão ouvindo, mas não as ouviram.”

[[v42-10-25]]

^<<v42-10-25,25>>^ Então, um homem perito na Lei se levantou para prová-lo e perguntou: “Instrutor, o que devo fazer para herdar a vida eterna?”

[[v42-10-26]]

^<<v42-10-26,26>>^ Ele lhe disse: “O que está escrito na Lei? Como você lê?”

[[v42-10-27]]

^<<v42-10-27,27>>^ Em resposta, ele disse: “‘Ame a Jeová, seu Deus, de todo o seu coração, de toda a sua alma, de toda a sua força e de toda a sua mente’ e ‘o seu próximo como a si mesmo’.”

[TIP]
====
- *Jeová*: Esta é uma citação direta de De 6:5. No texto hebraico original de Deuteronômio, aparecem as quatro letras hebraicas que formam o nome de Deus (que equivalem a YHWH). — Veja o Apêndice C1.
- *coração . . . alma . . . força . . . mente*: Neste versículo, um perito na Lei citou De 6:5. O texto hebraico original de Deuteronômio usa três palavras que significam coração, alma e força. Mas Lucas, que escreveu seu Evangelho em grego, usa quatro palavras ao citar o que o homem disse: coração, alma, força e mente. Isso indica que, na época de Jesus, as pessoas entendiam que essas quatro ideias expressas em grego estavam incluídas nas três palavras usadas em Deuteronômio. — Para mais detalhes sobre esse assunto, veja a nota de estudo em Mr 12:30.
- *toda a sua alma*: Ou: “todo o seu ser; toda a sua vida”. — Veja o Glossário, “Alma”.
- *o seu próximo*: Veja a nota de estudo em Mt 22:39.
====

[[v42-10-28]]

^<<v42-10-28,28>>^ Ele lhe disse: “Você respondeu corretamente; persista em fazer isso e obterá a vida.”

[[v42-10-29]]

^<<v42-10-29,29>>^ Mas, querendo se mostrar justo, o homem perguntou a Jesus: “Quem é realmente o meu próximo?”

[[v42-10-30]]

^<<v42-10-30,30>>^ Em resposta, Jesus disse: “Um homem descia de Jerusalém para Jericó e caiu nas mãos de assaltantes, que lhe arrancaram tudo, o espancaram e foram embora, deixando-o quase morto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Por coincidência, um sacerdote descia por aquela estrada, mas, quando o viu, passou pelo lado oposto.

[[v42-10-32]]

^<<v42-10-32,32>>^ Do mesmo modo, um levita, quando chegou ao lugar e o viu, passou pelo lado oposto.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas certo samaritano, viajando pela estrada, o encontrou e, ao vê-lo, teve pena.

[TIP]
====
- *certo samaritano*: Os judeus geralmente desprezavam os samaritanos e se recusavam a ter qualquer contato com eles. (Jo 4:9) Alguns judeus até usavam a palavra “samaritano” para humilhar e ofender outros. (Jo 8:​48) A Mishná relata que certo rabino disse: “Aquele que come o pão de um samaritano é como aquele que come carne de porco.” (Sheviit 8:10) Muitos judeus não acreditavam no testemunho de samaritanos nem aceitavam serviços prestados por eles. Jesus sabia que os judeus geralmente desprezavam os samaritanos e ensinou uma lição importante com essa ilustração, que é conhecida por muitos como a parábola do bom samaritano.
====

[[v42-10-34]]

^<<v42-10-34,34>>^ De modo que se aproximou dele e enfaixou seus ferimentos, derramando neles azeite e vinho. Então o pôs no seu próprio animal, o levou a uma hospedaria e cuidou dele.

[TIP]
====
- *enfaixou seus ferimentos, derramando neles azeite e vinho*: Lucas, que era médico, registrou em detalhes a ilustração de Jesus, relatando métodos de tratar ferimentos que refletem o que era usado na época. As pessoas costumavam usar azeite e vinho como remédios caseiros para tratar ferimentos. Às vezes se usava azeite para hidratar o local dos ferimentos e, possivelmente, para aliviar a dor (veja Is 1:6), e o vinho tem certo valor medicinal como antisséptico, podendo ser usado para limpar ferimentos e combater infecções. O relato de Lucas também diz que o samaritano enfaixou os ferimentos da vítima para que não piorassem.
- *uma hospedaria*: A palavra grega usada aqui significa literalmente “lugar em que todos são recebidos ou acolhidos”. Os viajantes podiam ficar hospedados nesses lugares, que também ofereciam abrigo para seus animais. O dono da hospedaria oferecia alguns itens básicos aos viajantes e, por um preço, podia dar assistência aos que fossem deixados aos seus cuidados.
====

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte tirou dois denários, deu-os ao hospedeiro e disse: ‘Cuide dele e, tudo o que você gastar além disso, eu lhe pagarei quando voltar.’

[TIP]
====
- *denários*: Veja o Glossário e o Apêndice B14-B.
====

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual desses três você acha que mostrou ser o próximo do homem que caiu nas mãos de assaltantes?”

[[v42-10-37]]

^<<v42-10-37,37>>^ Ele respondeu: “Aquele que agiu misericordiosamente com ele.” Jesus lhe disse então: “Vá e faça você o mesmo.”

[TIP]
====
- *Aquele que agiu misericordiosamente com ele*: Pode ser que o perito na Lei tenha, de propósito, evitado usar a palavra “samaritano”. De qualquer forma, a resposta que ele deu e o comentário que Jesus fez em seguida deixaram claro qual era a aplicação daquela ilustração: para alguém mostrar que realmente ama o seu próximo, ele precisa agir com misericórdia.
====

[[v42-10-38]]

^<<v42-10-38,38>>^ Ao prosseguirem, ele entrou em certa aldeia. Ali, uma mulher chamada Marta o recebeu como hóspede em sua casa.

[TIP]
====
- *certa aldeia*: Aparentemente se refere à Betânia, que ficava na encosta leste do monte das Oliveiras, a uns 3 quilômetros de distância de Jerusalém. (Veja a nota de estudo em Jo 11:18.) Marta, Maria e Lázaro moravam em Betânia. Essa cidade era a base de Jesus quando ele estava na Judeia, assim como Cafarnaum era a sua base na Galileia. — Mr 2:1.
- *Marta*: Lucas não menciona outros membros da família de Marta recebendo Jesus, apenas ela. Como era Marta quem geralmente tomava a frente nos assuntos (Lu 10:40; Jo 11:20), pode ser que ela fosse mais velha do que sua irmã, Maria. — Lu 10:39.
====

[[v42-10-39]]

^<<v42-10-39,39>>^ Ela tinha também uma irmã, chamada Maria, que se sentou aos pés do Senhor e ficou escutando o que ele dizia.^&#42;1^

[NOTE]
====
. Ou: “o que ele ensinava; sua mensagem”. Lit.: “sua palavra”.
====

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, por outro lado, estava distraída, cuidando de muitos afazeres. Assim, ela se aproximou dele e disse: “Senhor, não se importa que minha irmã me deixou sozinha para cuidar das coisas? Diga a ela que venha me ajudar.”

[[v42-10-41]]

^<<v42-10-41,41>>^ Em resposta, o Senhor lhe disse: “Marta, Marta, você está ansiosa e preocupada com muitas coisas.

[[v42-10-42]]

^<<v42-10-42,42>>^ Mas poucas coisas são necessárias, ou apenas uma. Maria, por sua vez, escolheu a boa porção, e essa não será tirada dela.”

[TIP]
====
- *Mas poucas coisas são necessárias, ou apenas uma*: Em alguns manuscritos bem antigos, aparece uma frase mais curta: “Mas apenas uma coisa é necessária.” E algumas traduções da Bíblia usam essa opção. Mas a opção usada aqui no texto principal também tem o apoio de manuscritos bem antigos e confiáveis. Não importa qual das opções seja usada, o sentido do conselho de Jesus permanece o mesmo: as coisas espirituais devem vir em primeiro lugar. Em seguida, Jesus elogiou Maria por ter escolhido “a boa porção” ao dar prioridade para as coisas espirituais.
- *a boa porção*: Ou: “a melhor parte”. A palavra grega merís, traduzida aqui como “porção”, é usada na Septuaginta para se referir tanto a uma porção de alimento (Gên 43:34; De 18:8) como a uma “porção” em sentido espiritual (Sal 16:5; 119:57). No caso de Maria, “a boa porção” incluía o privilégio de receber alimento espiritual diretamente do Filho de Deus.
====

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]