include::./index.adoc[]

[[v42-15-0]]
=== As Boas Novas Segundo Lucas, 15
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. Jesus se dirige para Jerusalém; Jesus continua seu ministério, principalmente na Judeia e na Pereia (9:51–19:27)
* Aldeia samaritana rejeita Jesus (9:51-56)
* Requisitos para seguir Jesus (9:57-62)
* Jesus envia os 70 (10:1-12)
* Corazim, Betsaida e Cafarnaum são repreendidas por não se arrependerem (10:13-16)
* Os 70 voltam (10:17-20)
* Jesus louva seu Pai por favorecer os humildes (10:21-24)
* Ilustração do bom samaritano (10:25-37)
* Jesus visita Marta e Maria (10:38-42)
* Jesus ensina a oração-modelo (11:1-4)
* Ilustração do amigo persistente (11:5-13)
* Jesus explica que os demônios são expulsos “por meio do dedo de Deus” (11:14-23)
* Jesus fala da volta de um espírito impuro (11:24-26)
* Explicação sobre a verdadeira felicidade (11:27, 28)
* Sinal de Jonas (11:29-32)
* Olho é a lâmpada do corpo (11:33-36)
* Jesus come com um fariseu; ai dos religiosos hipócritas (11:37-54)
* “Tomem cuidado com o fermento dos fariseus” (12:1-3)
* Temer a Deus, não a homens (12:4-7)
* Declarar que está em união com Cristo (12:8-12)
* Ilustração do rico insensato (12:13-21)
* “Parem de se preocupar tanto com a sua vida” (12:22-31)
* “Não tema, pequeno rebanho” (12:32-34)
* Manter a vigilância (12:35-40)
* Identificação do administrador fiel e características de um escravo infiel (12:41-48)
* Não paz, mas divisão (12:49-53)
* Necessidade de examinar os tempos (12:54-56)
* Resolver disputas (12:57-59)
* Arrepender-se ou ser destruído (13:1-5)
* Ilustração da figueira infrutífera (13:6-9)
* Jesus cura no sábado uma mulher encurvada (13:10-17)
* Ilustrações do grão de mostarda e do fermento (13:18-21)
* É preciso esforço para entrar pela porta estreita (13:22-30)
* Jesus chama Herodes de ‘aquela raposa’ (13:31-33)
* Jesus lamenta por Jerusalém (13:34, 35)
* Jesus cura no sábado um homem com hidropisia (14:1-6)
* Ser um convidado humilde (14:7-11)
* Convidar os que não podem recompensar (14:12-14)
* Ilustração dos convidados que recusam o convite (14:15-24)
* Custo de ser discípulo (14:25-33)
* Sal que perde a força (14:34, 35)
* Ilustração da ovelha perdida (15:1-7)
* Ilustração da moeda perdida (15:8-10)
* Ilustração do filho pródigo (15:11-32)
* Ilustração do administrador injusto (16:1-13)
* A Lei e o Reino de Deus (16:14-18)
* Ilustração do rico e Lázaro (16:19-31)
* Jesus ensina sobre tropeços, perdão e fé (17:1-6)
* Ilustração do escravo que serve primeiro seu senhor (17:7-10)
* Jesus cura dez leprosos (17:11-19)
* Vinda do Reino de Deus (17:20-37)
* Ilustração da viúva persistente (18:1-8)
* Ilustração do fariseu e do cobrador de impostos (18:9-14)
* Jesus e as criancinhas (18:15-17)
* Líder rico pergunta sobre a vida eterna (18:18-30)
* Jesus prediz novamente sua morte e ressurreição (18:31-34)
* Jesus cura um mendigo cego perto de Jericó (18:35-43)
* Jesus visita o cobrador de impostos Zaqueu (19:1-10)
* Ilustração das dez minas (19:11-27)
****

[[v42-15-1]]

^<<v42-15-1,1>>^ Todos os cobradores de impostos e os pecadores se juntavam em volta dele para ouvi-lo.

[[v42-15-2]]

^<<v42-15-2,2>>^ E tanto os fariseus como os escribas resmungavam: “Este homem acolhe pecadores e come com eles.”

[[v42-15-3]]

^<<v42-15-3,3>>^ Então ele lhes contou a seguinte ilustração:

[TIP]
====
- *ilustração*: Ou: “parábola”. — Veja a nota de estudo em Mt 13:3.
====

[[v42-15-4]]

^<<v42-15-4,4>>^ “Que homem entre vocês que, tendo 100 ovelhas e perdendo uma delas, não deixa as 99 para trás no deserto e vai em busca da perdida, até achá-la?

[[v42-15-5]]

^<<v42-15-5,5>>^ E, quando a acha, ele a põe nos ombros e se alegra.

[[v42-15-6]]

^<<v42-15-6,6>>^ E, ao chegar em casa, ele reúne seus amigos e seus vizinhos, e diz a eles: ‘Alegrem-se comigo, porque achei a minha ovelha que estava perdida.’

[[v42-15-7]]

^<<v42-15-7,7>>^ Eu lhes digo que, da mesma forma, haverá mais alegria no céu por causa de um pecador que se arrepende do que por causa de 99 justos que não precisam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ “Ou que mulher que, tendo dez dracmas e perdendo uma dracma, não acende uma lâmpada, varre a casa e procura cuidadosamente até achá-la?

[TIP]
====
- *dez*: Uma dracma valia aproximadamente o salário de um dia de um trabalhador. (Veja a nota de estudo em dracmas neste versículo.) Mas a moeda perdida talvez tivesse um valor especial para aquela mulher. Pode ser que as dez moedas formassem um conjunto especial que ela tinha recebido como herança de família ou fizessem parte de uma corrente usada como joia. A mulher precisou acender uma lâmpada. Naquela época, muitas casas não tinham janelas e, quando tinham uma, ela costumava ser bem pequena. Varrer a casa poderia ajudar a encontrar a moeda, já que o chão geralmente era de terra batida.
- *dracmas*: A dracma era uma moeda grega de prata. Na época de Jesus, é provável que a dracma pesasse aproximadamente 3,4 gramas. Naquele tempo, os gregos consideravam que uma dracma valia o mesmo que um denário, mas o governo romano calculava o valor oficial da dracma como três quartos de um denário. Os judeus pagavam ao templo um imposto anual de duas dracmas (uma didracma). — Veja a nota de estudo em Mt 17:24; o Glossário, “Dracma”; e o Apêndice B14-B.
====

[[v42-15-9]]

^<<v42-15-9,9>>^ E, quando a acha, ela reúne as suas amigas e vizinhas, e diz: ‘Alegrem-se comigo, porque achei a dracma que havia perdido.’

[TIP]
====
- *a dracma*: Veja a nota de estudo em Lu 15:8; o Glossário, “Dracma”; e o Apêndice B14-B.
====

[[v42-15-10]]

^<<v42-15-10,10>>^ Eu lhes digo que, da mesma forma, há alegria entre os anjos de Deus por causa de um pecador que se arrepende.”

[[v42-15-11]]

^<<v42-15-11,11>>^ Ele disse então: “Um homem tinha dois filhos.

[TIP]
====
- *Um homem tinha dois filhos*: A ilustração do filho pródigo (também chamada de “parábola do filho perdido”) é bem diferente das outras ilustrações de Jesus em alguns aspectos. Ela é uma das suas ilustrações mais longas. Um detalhe muito interessante é o relacionamento familiar que Jesus descreveu. Em outras ilustrações, Jesus muitas vezes citou coisas inanimadas, como diferentes tipos de sementes ou de solos, ou mencionou as relações formais entre o senhor e seus escravos. (Mt 13:18-​30; 25:14-​30; Lu 19:12-​27) Mas nessa ilustração Jesus destacou o amor de um pai por seus filhos. Muitos que ouviram Jesus talvez não tivessem um pai bondoso e carinhoso como o da ilustração. Ela mostra quanto amor e compaixão nosso Pai celestial sente por seus filhos na Terra, tanto os que permanecem ao lado dele como os que se desviam, mas depois voltam.
====

[[v42-15-12]]

^<<v42-15-12,12>>^ E o mais novo disse ao seu pai: ‘Pai, dê-me a parte dos bens a que tenho direito.’ Então ele dividiu os seus bens entre eles.

[TIP]
====
- *o mais novo*: De acordo com a Lei mosaica, o primogênito recebia “uma porção dupla” (duas partes) da herança. (De 21:17) Assim, nessa ilustração a herança do filho mais novo era metade da herança do filho mais velho.
====

[[v42-15-13]]

^<<v42-15-13,13>>^ Poucos dias depois, o filho mais novo juntou tudo que tinha e viajou para um país distante, e ali esbanjou os seus bens levando uma vida devassa.

[TIP]
====
- *esbanjou*: A palavra grega usada aqui significa literalmente “espalhar; dispersar”. (Mt 25:24, 26; Lu 1:​51; At 5:​37) Aqui, ela é usada com o sentido de desperdiçar ou gastar de modo imprudente.
- *uma vida devassa*: Ou: “uma vida de desperdício (irresponsável; desregrada)”. Uma palavra grega relacionada é usada com um sentido parecido em Ef 5:18, Tit 1:6 e 1Pe 4:4. Visto que a palavra usada aqui inclui a ideia de um estilo de vida esbanjador, essa ilustração é conhecida como “a parábola do filho pródigo [esbanjador]”.
====

[[v42-15-14]]

^<<v42-15-14,14>>^ Quando já tinha gastado tudo, ocorreu uma fome severa em todo aquele país, e ele começou a passar necessidade.

[[v42-15-15]]

^<<v42-15-15,15>>^ Ele até mesmo se pôs a serviço de um dos cidadãos daquele país, que o enviou aos seus campos para cuidar de porcos.

[TIP]
====
- *para cuidar de porcos*: Os porcos eram animais impuros de acordo com a Lei. Por isso, os judeus consideravam que esse era um trabalho humilhante e desprezível. — Le 11:​7, 8.
====

[[v42-15-16]]

^<<v42-15-16,16>>^ E ele desejava matar a fome com as alfarrobas que os porcos comiam, mas ninguém lhe dava nada.

[TIP]
====
- *alfarrobas*: Os frutos ou vagens da alfarrobeira possuem uma casca rígida e brilhosa de cor castanho-escura. Seu nome em grego é kerátion, que significa “pequeno chifre”, porque as alfarrobas têm a forma curva de um chifre. Elas são muito usadas até hoje como alimento para cavalos, bois e porcos. A situação do filho mais novo na ilustração era tão humilhante que ele chegou a ponto de querer comer o alimento dos porcos. — Veja a nota de estudo em Lu 15:15.
====

[[v42-15-17]]

^<<v42-15-17,17>>^ “Quando caiu em si, ele disse: ‘Quantos empregados do meu pai têm fartura de pão, enquanto eu estou aqui morrendo de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Vou partir e voltar para a casa do meu pai e lhe dizer: “Pai, pequei contra o céu e contra o senhor.

[TIP]
====
- *contra o senhor*: Ou: “à vista do senhor”. Embora a preposição grega usada aqui, enópion, signifique literalmente “diante de; à vista de”, aqui ela tem o sentido de “contra”. Em 1Sa 20:1 a Septuaginta usa enópion com esse mesmo sentido na pergunta que Davi fez a Jonatã: “Que pecado cometi contra o seu pai?”
====

[[v42-15-19]]

^<<v42-15-19,19>>^ Não sou mais digno de ser chamado seu filho. Trate-me como um dos seus empregados.”’

[TIP]
====
- *empregados*: Enquanto voltava para casa, o filho mais novo pensou em pedir que seu pai o aceitasse como um empregado, não como um filho. Os empregados não faziam parte da casa de seu senhor, como os escravos faziam. Eles eram pessoas de fora, muitas vezes contratadas para trabalhar um dia por vez. — Mt 20:​1, 2, 8.
====

[[v42-15-20]]

^<<v42-15-20,20>>^ Assim, levantou-se e foi ao encontro do seu pai. Enquanto ele ainda estava longe, seu pai o avistou e teve pena; então correu, e o abraçou^&#42;1^ e beijou ternamente.

[NOTE]
====
. Lit.: “se lançou ao pescoço dele”.
====

[TIP]
====
- *beijou ternamente*: Ou: “beijou com amor”. Alguns acreditam que a palavra grega traduzida aqui como “beijou ternamente” seja uma forma intensificada do verbo filéo, que às vezes é traduzido como “beijar” (Mt 26:48; Mr 14:44; Lu 22:47), mas é mais usado no sentido de “amar” (Jo 5:​20; 11:3; 16:27). Na ilustração, o modo carinhoso como o pai tratou o filho arrependido mostra que ele queria aceitá-lo de volta.
====

[[v42-15-21]]

^<<v42-15-21,21>>^ O filho lhe disse então: ‘Pai, pequei contra o céu e contra o senhor. Não sou mais digno de ser chamado seu filho.’

[TIP]
====
- *ser chamado seu filho*: Alguns manuscritos acrescentam aqui: “Trate-me como um dos seus empregados.” Mas a opção sem essa frase tem o apoio de vários dos manuscritos mais antigos e confiáveis. Alguns estudiosos acham que o trecho foi acrescentado para harmonizar este versículo com Lu 15:19.
====

[[v42-15-22]]

^<<v42-15-22,22>>^ Mas o pai disse aos seus escravos: ‘Depressa! Tragam uma veste comprida, a melhor, e vistam-no com ela, e ponham-lhe um anel na mão e sandálias nos pés.

[TIP]
====
- *veste comprida . . . anel . . . sandálias*: Essa veste comprida não era uma peça de roupa qualquer; era a melhor — talvez uma roupa bordada, do tipo que na época era dada para um convidado ou hóspede por quem o dono da casa tinha muita consideração. O gesto de colocar um anel na mão do filho mostra o amor e a aprovação do pai. Indica também a dignidade e a honra que o filho estava recebendo. Os escravos não costumavam usar anéis e sandálias. Dessa forma, o pai estava deixando claro que acolhia o filho de volta como membro da família.
====

[[v42-15-23]]

^<<v42-15-23,23>>^ Tragam também o bezerro gordo, abatam-no,^&#42;1^ e vamos comer e festejar,

[NOTE]
====
. Ou: “sacrifiquem-no”.
====

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto e voltou a viver, estava perdido e foi achado.’ E começaram a festejar.

[[v42-15-25]]

^<<v42-15-25,25>>^ “O filho mais velho estava no campo e, ao voltar, quando se aproximava da casa, ouviu o som de música e dança.

[[v42-15-26]]

^<<v42-15-26,26>>^ De modo que chamou um dos servos e perguntou o que estava acontecendo.

[[v42-15-27]]

^<<v42-15-27,27>>^ Este lhe disse: ‘Seu irmão chegou, e seu pai abateu o bezerro gordo porque o recebeu de volta com boa saúde.’^&#42;1^

[NOTE]
====
. Ou: “em segurança”.
====

[[v42-15-28]]

^<<v42-15-28,28>>^ Mas ele ficou irado e se recusou a entrar. Então seu pai saiu e começou a lhe suplicar que entrasse.

[[v42-15-29]]

^<<v42-15-29,29>>^ Em resposta, ele disse ao pai: ‘Trabalhei tantos anos como escravo para o senhor e nunca desobedeci às suas ordens. Mesmo assim, nem uma vez o senhor me deu um cabrito para eu festejar com os meus amigos.

[[v42-15-30]]

^<<v42-15-30,30>>^ Mas assim que chegou esse seu filho, que esbanjou os bens do senhor com as prostitutas, o senhor abateu o bezerro gordo para ele.’

[TIP]
====
- *esbanjou*: Lit.: “devorou”. A palavra grega usada aqui destaca o modo irresponsável como o filho mais novo gastou os bens de seu pai.
====

[[v42-15-31]]

^<<v42-15-31,31>>^ Ele lhe disse então: ‘Meu filho, você sempre esteve comigo e todas as minhas coisas são suas.

[[v42-15-32]]

^<<v42-15-32,32>>^ Mas nós simplesmente tivemos de festejar e nos alegrar, porque seu irmão estava morto e voltou a viver, estava perdido e foi achado.’”

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]