include::./index.adoc[]

[[v42-5-0]]
=== As Boas Novas Segundo Lucas, 5
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* E. Começo do ministério de Jesus, principalmente na Galileia (4:14–6:11)
* Jesus começa a pregar na Galileia (4:14, 15)
* Jesus é rejeitado em Nazaré (4:16-30)
* Jesus ensina na sinagoga em Cafarnaum (4:31-37)
* Jesus cura a sogra de Simão e outras pessoas (4:38-41)
* Multidões encontram Jesus num lugar isolado (4:42-44)
* Pesca milagrosa; Jesus chama os primeiros discípulos (5:1-11)
* Jesus cura um homem que está coberto de lepra (5:12-16)
* Jesus perdoa os pecados de um paralítico e o cura (5:17-26)
* Jesus chama Levi para ser seu seguidor (5:27-32)
* Pergunta sobre o jejum (5:33-39)
* Jesus é “Senhor do sábado” (6:1-5)
* Jesus cura no sábado um homem que tem a mão atrofiada (6:6-11)
****

[[v42-5-1]]

^<<v42-5-1,1>>^ Em certa ocasião, ele estava à beira do lago de Genesaré,  e a multidão se apertava em volta dele para escutar a palavra de Deus.

[TIP]
====
- *lago de Genesaré*: Outro nome do mar da Galileia, um lago de água doce no norte de Israel. (Mt 4:18) Ele também já foi chamado de mar de Quinerete (Núm 34:11) e de mar de Tiberíades. (Veja a nota de estudo em Jo 6:1.) Ele fica uns 210 metros abaixo do nível do mar e tem 21 quilômetros de comprimento (de norte a sul) e 12 quilômetros de largura (de leste a oeste). Sua profundidade máxima é de cerca de 48 metros. Genesaré é o nome de uma pequena planície que mede cerca de 5 quilômetros por 2,5 quilômetros e fica na margem noroeste do mar da Galileia. Alguns estudiosos acreditam que Genesaré seja a forma grega de Quinerete, o antigo nome hebraico do local. — Veja a nota de estudo em Mt 14:34 e “Acontecimentos no mar da Galileia” no Mapa 3B do Apêndice A7-D.
====

[[v42-5-2]]

^<<v42-5-2,2>>^ Ele viu dois barcos atracados à beira do lago, mas os pescadores tinham desembarcado e estavam lavando as suas redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrando num dos barcos, que era o de Simão, pediu-lhe que o afastasse um pouco da terra. Sentou-se então e, do barco, começou a ensinar as multidões.

[TIP]
====
- *do barco, começou a ensinar as multidões*: Veja a nota de estudo em Mt 13:2.
====

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando parou de falar, ele disse a Simão: “Vá para onde é fundo, e abaixem as suas redes para uma pesca.”

[[v42-5-5]]

^<<v42-5-5,5>>^ Simão, porém, disse em resposta: “Instrutor, trabalhamos arduamente a noite toda e não apanhamos nada, mas, como o senhor pediu, abaixarei as redes.”

[[v42-5-6]]

^<<v42-5-6,6>>^ Pois bem, quando fizeram isso, apanharam uma quantidade tão grande de peixes que suas redes começaram a se romper.

[TIP]
====
- *apanharam*: Lit.: “cercaram”. Ou seja, cercaram com as redes.
====

[[v42-5-7]]

^<<v42-5-7,7>>^ Então, fizeram sinal para os seus sócios no outro barco, para que se aproximassem e os auxiliassem; e eles vieram e encheram ambos os barcos, de modo que esses começaram a afundar.

[[v42-5-8]]

^<<v42-5-8,8>>^ Vendo isso, Simão Pedro se prostrou aos joelhos de Jesus, dizendo: “Afaste-se de mim, Senhor, porque sou homem pecador.”

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois tanto ele como os que estavam com ele foram tomados de espanto em vista da quantidade de peixes que tinham apanhado,

[[v42-5-10]]

^<<v42-5-10,10>>^ e o mesmo aconteceu com Tiago e João, filhos de Zebedeu, que eram sócios de Simão. Mas Jesus disse a Simão: “Pare de ter medo. De agora em diante você apanhará^&#42;1^ a homens.”^&#42;2^

[NOTE]
====
. Ou: “apanhará vivos”.
. Ou: “pessoas”.
====

[[v42-5-11]]

^<<v42-5-11,11>>^ Assim, levaram os barcos de volta a terra, abandonaram tudo e o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Em outra ocasião, ele estava numa das cidades quando apareceu um homem coberto de lepra. Quando ele viu Jesus, prostrou-se com o rosto por terra e lhe implorou: “Senhor, se apenas quiser, pode me purificar.”

[TIP]
====
- *um homem coberto de lepra*: A lepra mencionada aqui era uma grave doença de pele. Mas, na Bíblia, essa palavra não se refere apenas à doença que hoje é chamada de lepra (hanseníase). Se uma pessoa tivesse lepra, ela era excluída da sociedade até que ficasse curada. (Le 13:2, segunda nota de rodapé, 45, 46; veja o Glossário, “Lepra; Leproso”.) Os Evangelhos de Mateus e Marcos, que relatam esse mesmo acontecimento, dizem apenas que o homem era “um leproso”. (Mt 8:2; Mr 1:40) Mas, como médico, Lucas sabia que essa doença tem vários estágios. (Col 4:14) Neste caso, Lucas diz que o homem estava “coberto de lepra”, pelo visto se referindo a um estágio avançado dessa doença. — Para ver outra ocasião em que Lucas fala de modo específico sobre uma doença, veja a nota de estudo em Lu 4:38.
====

[[v42-5-13]]

^<<v42-5-13,13>>^ Assim, ele estendeu a mão e tocou no homem, dizendo: “Eu quero! Seja purificado.” Imediatamente a lepra desapareceu dele.

[TIP]
====
- *tocou no homem*: Veja a nota de estudo em Mt 8:3.
- *Eu quero*: Veja a nota de estudo em Mt 8:3.
====

[[v42-5-14]]

^<<v42-5-14,14>>^ Então ele ordenou ao homem que não contasse nada a ninguém, e acrescentou: “Mas vá e mostre-se ao sacerdote, e faça uma oferta pela sua purificação, assim como Moisés determinou, em testemunho para eles.”

[TIP]
====
- *mostre-se ao sacerdote*: Veja a nota de estudo em Mr 1:44.
====

[[v42-5-15]]

^<<v42-5-15,15>>^ Mas as notícias sobre ele continuavam se espalhando, e grandes multidões se reuniam para escutar e para ser curadas de suas doenças.

[[v42-5-16]]

^<<v42-5-16,16>>^ No entanto, ele muitas vezes ia a lugares desertos para orar.

[TIP]
====
- *ele muitas vezes ia a lugares desertos para orar*: Esta é uma das várias vezes em que apenas Lucas relata que Jesus estava orando. (Veja as notas de estudo em Lu 3:21; 9:28.) A forma como os verbos gregos foram usados neste versículo mostra que Jesus tinha o hábito de orar. A palavra grega éremos, traduzida aqui como “lugares desertos”, geralmente se refere a um ermo ou deserto, mas pode ser usada para se referir a qualquer “lugar isolado”. (Mt 14:13; Mr 1:45; 6:31; Lu 4:42; 8:29) Jesus não queria viver isolado. Ele gostava muito de passar tempo com outras pessoas. (Mt 9:35, 36; Lu 8:1; 19:7-10; Jo 11:5) Mas gostava ainda mais de passar tempo com seu Pai, e por isso procurava ficar a sós com Jeová para se sentir à vontade para se expressar. — Mt 14:23; Mr 1:35.
====

[[v42-5-17]]

^<<v42-5-17,17>>^ Num daqueles dias, quando ele estava ensinando, fariseus e instrutores da Lei, que haviam chegado de todas as aldeias da Galileia e da Judeia, e de Jerusalém, estavam sentados ali; e o poder de Jeová estava com ele para fazer curas.

[TIP]
====
- *o poder de Jeová*: Os manuscritos gregos disponíveis usam aqui a palavra Kýrios (Senhor), mas há bons motivos para se usar o nome de Deus no texto principal. O contexto mostra claramente que a palavra Kýrios é usada aqui para se referir a Deus. Além disso, a palavra grega dýnamis (traduzida aqui como “poder”) é usada na Septuaginta em passagens onde o texto hebraico se refere ao poder ou força de Jeová e usa o Tetragrama. — Sal 21:1, 13; 93:1; 118:15; veja o Apêndice C3 (introdução e Lu 5:17).
====

[[v42-5-18]]

^<<v42-5-18,18>>^ Nisto, chegaram alguns homens carregando um homem paralítico numa maca, e eles tentavam levá-lo para dentro e colocá-lo diante de Jesus.

[[v42-5-19]]

^<<v42-5-19,19>>^ Assim, visto que não encontraram um meio de levá-lo para dentro por causa da multidão, subiram ao telhado e o baixaram em sua maca, entre as telhas, bem no meio dos que estavam diante de Jesus.

[TIP]
====
- *entre as telhas*: O relato sobre a cura desse homem paralítico aparece nos Evangelhos de Mateus (9:1-8), Marcos (2:1-12) e Lucas. Os três relatos se complementam. Mateus não menciona o telhado e diz apenas que o homem foi levado até Jesus. Marcos diz que os amigos do homem removeram o telhado e fizeram uma abertura para baixarem sua maca. E Lucas diz que ele foi baixado “entre as telhas”. (Veja a nota de estudo em Mr 2:4.) A palavra grega traduzida aqui como “telhas” (kéramos) também pode significar “barro” (o material do qual as telhas eram feitas). Mas parece que neste caso Lucas se referia a “telhas”, porque a palavra grega está no plural. Há evidências de que no antigo Israel algumas casas tinham telhas. Não é possível saber exatamente como era o telhado mencionado por Marcos e Lucas, mas pode ser que as telhas estivessem apoiadas ou presas de algum modo no teto feito de barro. De qualquer forma, o relato mostra o grande esforço que os amigos do homem paralítico fizeram para que ele chegasse até Jesus, revelando o tamanho de sua fé. Os três relatos registram que Jesus “viu a fé que tinham”. — Lu 5:20.
====

[[v42-5-20]]

^<<v42-5-20,20>>^ Quando ele viu a fé que tinham, disse: “Homem, seus pecados estão perdoados.”

[TIP]
====
- *viu a fé que tinham*: Veja a nota de estudo em Mt 9:2.
====

[[v42-5-21]]

^<<v42-5-21,21>>^ Então, os escribas e os fariseus começaram a raciocinar, dizendo: “Quem é este que fala blasfêmias? Quem pode perdoar pecados a não ser somente Deus?”

[[v42-5-22]]

^<<v42-5-22,22>>^ Mas Jesus, discernindo o raciocínio deles, disse-lhes em resposta: “O que vocês estão raciocinando no coração?

[[v42-5-23]]

^<<v42-5-23,23>>^ O que é mais fácil dizer: ‘Seus pecados estão perdoados’, ou: ‘Levante-se e ande’?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas, a fim de que vocês saibam que o Filho do Homem tem autoridade na terra para perdoar pecados . . .”, ele disse ao paralítico: “Eu lhe digo: Levante-se, apanhe a sua maca e vá para casa.”

[TIP]
====
- *Filho do Homem*: Veja a nota de estudo em Mt 8:20.
- *para perdoar pecados . . . *: Veja a nota de estudo em Mt 9:6.
====

[[v42-5-25]]

^<<v42-5-25,25>>^ Com isso, ele se levantou diante deles, apanhou aquilo em que se deitava e foi para casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Então, todos foram tomados de admiração, começaram a glorificar a Deus e, cheios de temor, diziam: “Vimos coisas maravilhosas hoje!”

[[v42-5-27]]

^<<v42-5-27,27>>^ Depois disso, ele saiu e viu um cobrador de impostos, chamado Levi, sentado na coletoria, e lhe disse: “Seja meu seguidor.”

[TIP]
====
- *Levi*: No relato paralelo em Mt 9:9, esse discípulo é chamado de Mateus. Tanto Marcos como Lucas o chamam de “Levi” quando mencionam que ele era cobrador de impostos (Mr 2:14), mas o chamam de “Mateus” quando o mencionam como um dos apóstolos (Mr 3:18; Lu 6:15; At 1:13). A Bíblia não explica se Levi já era chamado de Mateus antes de se tornar discípulo de Jesus. — Veja a nota de estudo em Mr 2:14.
- *coletoria*: Veja a nota de estudo em Mr 2:14.
- *Seja meu seguidor*: Veja a nota de estudo em Mr 2:14.
====

[[v42-5-28]]

^<<v42-5-28,28>>^ E Levi, deixando tudo para trás, se levantou e começou a segui-lo.

[[v42-5-29]]

^<<v42-5-29,29>>^ Então Levi lhe ofereceu um grande banquete para recepcioná-lo na sua casa, e havia uma grande multidão de cobradores de impostos e de outros, que estavam comendo com eles.

[TIP]
====
- *cobradores de impostos*: Veja a nota de estudo em Mt 5:46.
- *comendo*: Veja a nota de estudo em Mr 2:15.
====

[[v42-5-30]]

^<<v42-5-30,30>>^ Em vista disso, os fariseus e os seus escribas começaram a resmungar, dizendo aos discípulos dele: “Por que vocês comem e bebem com cobradores de impostos e pecadores?”

[[v42-5-31]]

^<<v42-5-31,31>>^ Em resposta, Jesus lhes disse: “Os que têm saúde não precisam de médico, mas sim os doentes.

[[v42-5-32]]

^<<v42-5-32,32>>^ Eu não vim chamar os justos ao arrependimento, mas os pecadores.”

[[v42-5-33]]

^<<v42-5-33,33>>^ Eles lhe disseram: “Os discípulos de João jejuam frequentemente e oferecem súplicas, e o mesmo fazem os dos fariseus, mas os seus comem e bebem.”

[TIP]
====
- *jejuam*: Veja a nota de estudo em Mt 6:16.
====

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus lhes disse: “Será que vocês podem fazer os amigos do noivo jejuar enquanto o noivo está com eles?

[TIP]
====
- *amigos do noivo*: Veja a nota de estudo em Mt 9:15.
====

[[v42-5-35]]

^<<v42-5-35,35>>^ Mas virão dias em que o noivo realmente será tirado deles; então, naqueles dias, eles jejuarão.”

[[v42-5-36]]

^<<v42-5-36,36>>^ Contou-lhes também uma ilustração: “Ninguém corta um pedaço de uma roupa nova para remendar uma roupa velha. Se fizer isso, o remendo novo se soltará e o remendo da roupa nova não combinará com a velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ Também, ninguém põe vinho novo em odres velhos. Se fizer isso, o vinho novo arrebentará os odres e se derramará, e os odres ficarão arruinados.

[TIP]
====
- *vinho . . . em odres*: Veja a nota de estudo em Mt 9:17.
====

[[v42-5-38]]

^<<v42-5-38,38>>^ Mas vinho novo tem de ser posto em odres novos.

[[v42-5-39]]

^<<v42-5-39,39>>^ Ninguém, depois de beber vinho velho, quer o novo, pois diz: ‘O velho é bom.’”

[TIP]
====
- *bom*: Ou, possivelmente: “melhor” (como aparece em alguns manuscritos).
====

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]