include::./index.adoc[]

[[v40-26-0]]
=== As Boas Novas Segundo Mateus, 26
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* M. Jesus é traído, morto e sepultado (26:1–27:66)
* Sacerdotes planejam matar Jesus (26:1-5)
* Mulher derrama óleo perfumado em Jesus (26:6-13)
* Última Páscoa de Jesus; Judas trai Jesus (26:14-25)
* Primeira Ceia do Senhor (26:26-30)
* Jesus prediz que Pedro vai negá-lo (26:31-35)
* Jesus ora em Getsêmani (26:36-46)
* Jesus é detido e levado ao Sinédrio (26:47-68)
* Pedro nega Jesus três vezes e chora amargamente (26:69-75)
* Sacerdotes e anciãos entregam Jesus a Pilatos (27:1, 2)
* Judas sente remorso e se enforca (27:3-10)
* Pilatos interroga Jesus (27:11-26)
* Soldados zombam de Jesus em público (27:27-31)
* Jesus é pregado numa estaca em Gólgota (27:32-44)
* Jesus morre (27:45-56)
* Jesus é sepultado (27:57-61)
* Sepultura de Jesus é lacrada e vigiada (27:62-66)
****

[[v40-26-1]]

^<<v40-26-1,1>>^ Então, quando Jesus terminou de falar todas essas coisas, ele disse aos seus discípulos:

[TIP]
====
- *Então, quando*: Os acontecimentos descritos em Mt 26:1-5 ocorreram no dia 12 de nisã, porque o versículo 2 diz que a Páscoa (realizada em 14 de nisã) seria dali “a dois dias”. — Veja os Apêndices A7-G, B12-B e a nota de estudo em Mt 26:6.
====

[[v40-26-2]]

^<<v40-26-2,2>>^ “Vocês sabem que daqui a dois dias é a Páscoa, e o Filho do Homem será entregue para ser morto na estaca.”

[TIP]
====
- *Páscoa*: A palavra grega páskha vem da palavra hebraica pésahh, derivada do verbo hebraico pasáhh, que significa “passar por alto; passar direto”. A primeira Páscoa judaica foi celebrada em 14 de nisã, na noite antes de os israelitas começarem o Êxodo do Egito. A Páscoa comemorava a libertação dos israelitas da escravidão no Egito, e também o fato de Jeová ter ‘passado por alto’ os primogênitos israelitas quando matou os primogênitos egípcios. — Êx 12:14, 24-47; veja o Glossário.
- *Filho do Homem*: Veja a nota de estudo em Mt 8:20.
- *para ser morto na estaca*: Ou: “para ser preso numa estaca (num poste)”. — Veja a nota de estudo em Mt 20:19 e o Glossário, “Madeiro; Estaca”; “Estaca de tortura”.
====

[[v40-26-3]]

^<<v40-26-3,3>>^ Então os principais sacerdotes e os anciãos do povo se reuniram no pátio do sumo sacerdote, que se chamava Caifás,

[TIP]
====
- *principais sacerdotes*: Veja a nota de estudo em Mt 2:4 e o Glossário.
- *anciãos*: Veja a nota de estudo em Mt 16:21.
- *sumo sacerdote*: Quando Israel era uma nação independente, o sumo sacerdote continuava no cargo a vida toda. (Núm 35:25) Mas, durante o tempo em que o Império Romano dominava sobre Israel, os governantes designados por esse império tinham autoridade para nomear ou remover o sumo sacerdote. — Veja o Glossário.
- *Caifás*: Sumo sacerdote nomeado pelos romanos. Ele era um diplomata habilidoso que conseguiu ficar no cargo de sumo sacerdote por mais tempo do que todos os outros que ocuparam o cargo pouco antes dele. Foi nomeado por volta de 18 d.C. e continuou no cargo até por volta de 36 d.C. — Veja a possível localização da casa de Caifás no Apêndice B12-A.
====

[[v40-26-4]]

^<<v40-26-4,4>>^ e fizeram planos para, com astúcia,^&#42;1^ prender^&#42;2^ Jesus e matá-lo.

[NOTE]
====
. Ou: “por meio de uma trama”.
. Ou: “pegar”.
====

[[v40-26-5]]

^<<v40-26-5,5>>^ No entanto, diziam: “Não durante a festividade, para que não haja um alvoroço entre o povo.”

[[v40-26-6]]

^<<v40-26-6,6>>^ Enquanto Jesus estava em Betânia, na casa de Simão, o leproso,

[TIP]
====
- *Enquanto Jesus estava em Betânia*: Os acontecimentos descritos em Mt 26:6-13 pelo visto ocorreram depois do pôr do sol que marcou o começo do dia 9 de nisã. Isso é indicado pelo relato paralelo de João, que diz que Jesus chegou em Betânia “seis dias antes da Páscoa”. (Jo 12:1) Ele deve ter chegado por volta da hora do pôr do sol que marcou o começo do sábado, 8 de nisã, um dia antes da refeição na casa de Simão, que aconteceu no dia 9. — Jo 12:2-11; veja os Apêndices A7-G e B12-A.
- *Simão, o leproso*: Esse Simão só é mencionado aqui e no relato paralelo em Mr 14:3. Talvez fosse um leproso que Jesus curou. — Veja a nota de estudo em Mt 8:2 e o Glossário, “Lepra; Leproso”.
====

[[v40-26-7]]

^<<v40-26-7,7>>^ aproximou-se dele uma mulher com um frasco de alabastro que continha óleo perfumado muito caro, e ela começou a derramá-lo sobre a cabeça dele, enquanto ele estava comendo.^&#42;1^

[NOTE]
====
. Ou: “recostado à mesa”.
====

[TIP]
====
- *uma mulher*: De acordo com Jo 12:3, essa mulher é Maria, irmã de Marta e Lázaro.
- *frasco de alabastro*: Veja o Glossário, “Alabastro”.
- *óleo perfumado muito caro*: Os relatos de Marcos e de João especificam que o frasco continha quase meio quilo de “nardo genuíno”, que valia 300 denários. Um trabalhador comum teria que juntar todo o salário de um ano para conseguir esse valor. (Mr 14:3-5; Jo 12:3-5) Acredita-se que esse óleo vinha de uma planta aromática (Nardostachys jatamansi) encontrada nas montanhas do Himalaia. Por ser muito caro, o nardo era muitas vezes adulterado e até mesmo falsificado, mas tanto Marcos como João dizem que esse óleo era “genuíno”.
- *derramá-lo sobre a cabeça dele*: Mateus e Marcos dizem que a mulher derramou o óleo na cabeça de Jesus. (Mr 14:3) João, que escreveu seu Evangelho anos mais tarde, diz que ela derramou óleo também nos pés de Jesus. (Jo 12:3) Jesus explicou que, com aquele ato bondoso, a mulher estava como que preparando o corpo dele para o sepultamento. — Veja a nota de estudo em Mt 26:12.
====

[[v40-26-8]]

^<<v40-26-8,8>>^ Ao verem isso, os discípulos ficaram indignados e disseram: “Por que esse desperdício?

[TIP]
====
- *os discípulos*: O relato paralelo de João é o único que menciona especificamente Judas Iscariotes como a pessoa que criticou Maria por usar aquele óleo tão caro. (Jo 12:4-7) Pelo visto, outros apóstolos acharam que Judas tinha razão e simplesmente concordaram com ele.
====

[[v40-26-9]]

^<<v40-26-9,9>>^ Pois isso poderia ter sido vendido por uma grande soma, e o dinheiro dado aos pobres.”

[TIP]
====
- *uma grande soma*: Veja a nota de estudo em Mr 14:5.
====

[[v40-26-10]]

^<<v40-26-10,10>>^ Percebendo isso, Jesus lhes disse: “Por que vocês estão perturbando a mulher? Ela me fez uma coisa muito boa.

[[v40-26-11]]

^<<v40-26-11,11>>^ Porque vocês sempre têm consigo os pobres, mas nem sempre terão a mim.

[[v40-26-12]]

^<<v40-26-12,12>>^ Quando essa mulher derramou esse óleo perfumado sobre o meu corpo, fez isso a fim de me preparar para o sepultamento.

[TIP]
====
- *essa mulher derramou esse óleo perfumado sobre o meu corpo*: A mulher (veja a nota de estudo em Mt 26:7) fez esse ato generoso porque sentia amor e gratidão por Jesus. Era costume passar aromas e óleos perfumados no corpo de pessoas falecidas. (2Cr 16:14) Por isso, Jesus explicou que a mulher, mesmo sem saber, já estava preparando o corpo dele para o sepultamento.
====

[[v40-26-13]]

^<<v40-26-13,13>>^ Eu lhes digo a verdade: Onde quer que se preguem as boas novas em todo o mundo, o que essa mulher fez também será relatado, em memória dela.”

[TIP]
====
- *Eu lhes digo a verdade*: Veja a nota de estudo em Mt 5:18.
- *preguem as boas novas em todo o mundo*: Jesus estava dizendo aqui que as boas novas seriam pregadas em todo o mundo, como também disse na profecia registrada em Mt 24:14. E essas boas novas incluiriam o ato de fé e amor daquela mulher. Deus fez com que três dos quatro Evangelhos registrassem o que ela tinha feito por Jesus. — Mr 14:8, 9; Jo 12:7; veja a nota de estudo em Mt 24:14.
====

[[v40-26-14]]

^<<v40-26-14,14>>^ Então um dos Doze, o chamado Judas Iscariotes, se dirigiu aos principais sacerdotes

[TIP]
====
- *Então*: Ou seja, em 12 de nisã, o mesmo dia em que ocorreram os acontecimentos descritos em Mt 26:1-5. — Veja os Apêndices A7-G, B12-B e as notas de estudo em Mt 26:1, 6.
- *Judas Iscariotes*: Veja a nota de estudo em Mt 10:4.
====

[[v40-26-15]]

^<<v40-26-15,15>>^ e disse: “O que me darão para entregá-lo^&#42;1^ a vocês?” Estipularam-lhe 30 moedas de prata.

[NOTE]
====
. Ou: “traí-lo”.
====

[TIP]
====
- *30 moedas de prata*: O Evangelho de Mateus é o único que menciona o valor pelo qual Jesus foi traído. Essas 30 moedas talvez fossem 30 siclos de prata produzidos em Tiro. Esse preço parece mostrar o quanto os principais sacerdotes desprezavam Jesus porque, de acordo com a Lei, 30 siclos era o valor de um escravo. (Êx 21:32) Do mesmo modo, quando Zacarias pediu que os israelitas infiéis pagassem o seu salário pelo trabalho de profeta, eles deram “30 peças de prata”, mostrando que para eles Zacarias não valia mais do que um escravo. — Za 11:12, 13.
====

[[v40-26-16]]

^<<v40-26-16,16>>^ De modo que daquele momento em diante ele procurava uma boa oportunidade para traí-lo.

[[v40-26-17]]

^<<v40-26-17,17>>^ No primeiro dia da Festividade dos Pães sem Fermento, os discípulos se aproximaram de Jesus e perguntaram: “Onde o senhor quer que façamos os preparativos para tomar a refeição pascoal?”

[TIP]
====
- *No primeiro dia da Festividade dos Pães sem Fermento*: A Festividade dos Pães sem Fermento começava no dia 15 de nisã, um dia depois da Páscoa (14 de nisã), e durava sete dias. (Veja o Apêndice B15.) Mas, na época de Jesus, as duas celebrações já estavam tão relacionadas que os oito dias (incluindo o dia 14) às vezes eram chamados de “a Festividade dos Pães sem Fermento”. (Lu 22:1) Além disso, neste versículo, a expressão “No primeiro dia da” poderia ser traduzida como “Um dia antes da”. (Compare com Jo 1:15, 30, onde a palavra grega para “primeiro” [prótos] é traduzida como “antes de” na expressão “existia antes de [prótos] mim”.) Assim, com base no costume judaico e no texto grego original, pode-se concluir que os discípulos fizeram a pergunta em 13 de nisã. Foi no período de luz do dia 13 de nisã que os discípulos fizeram os preparativos para a Páscoa, que foi comemorada mais tarde, “depois de anoitecer”, no começo de 14 de nisã. — Mr 14:16, 17.
====

[[v40-26-18]]

^<<v40-26-18,18>>^ Ele disse: “Vão à cidade, a um certo homem, e digam-lhe: ‘O Instrutor diz: “Está próximo o meu tempo determinado; celebrarei a Páscoa com os meus discípulos na sua casa.”’”

[[v40-26-19]]

^<<v40-26-19,19>>^ Então os discípulos fizeram conforme as instruções de Jesus e prepararam a refeição pascoal.

[[v40-26-20]]

^<<v40-26-20,20>>^ Quando anoiteceu, ele estava recostado à mesa com os 12 discípulos.

[TIP]
====
- *Quando anoiteceu*: Ou seja, no anoitecer que marcou o começo de 14 de nisã. — Veja os Apêndices A7-G e B12-B.
====

[[v40-26-21]]

^<<v40-26-21,21>>^ Enquanto comiam, ele disse: “Digo-lhes a verdade: Um de vocês me trairá.”

[[v40-26-22]]

^<<v40-26-22,22>>^ Eles ficaram muito tristes com isso, e cada um começou a lhe perguntar: “Senhor, por acaso sou eu?”

[[v40-26-23]]

^<<v40-26-23,23>>^ Em resposta, ele disse: “Aquele que põe a mão na tigela junto comigo é o que me trairá.

[TIP]
====
- *põe a mão . . . junto comigo*: As pessoas costumavam comer com as mãos, ou então usavam um pedaço de pão como se fosse uma colher. Essas palavras de Jesus também podem ser uma expressão idiomática para “compartilhar a comida”. Comer com uma pessoa indicava o desejo de passar tempo na companhia dela. Aquele que se virava contra um amigo tão achegado assim cometia a pior forma de traição possível. — Sal 41:9; Jo 13:18.
====

[[v40-26-24]]

^<<v40-26-24,24>>^ É verdade, o Filho do Homem vai embora, assim como está escrito a respeito dele, mas ai daquele que trai o Filho do Homem! Seria melhor para esse homem que não tivesse nascido.”

[[v40-26-25]]

^<<v40-26-25,25>>^ Judas, que estava prestes a traí-lo, perguntou: “Por acaso sou eu, Rabi?” Jesus lhe respondeu: “Você mesmo está dizendo isso.”

[TIP]
====
- *Você mesmo está dizendo isso*: Expressão idiomática judaica usada para confirmar uma informação apresentada numa pergunta. Era como se Jesus estivesse dizendo: “Você acabou de dizer isso, e o que você diz é verdade.” Pelo visto, Jesus quis dizer que o próprio Judas, com sua pergunta, estava reconhecendo que era o traidor. Comparando o relato de Mateus com Jo 13:21-30, é razoável concluir que Judas deve ter saído dali antes de Jesus realizar a primeira Ceia do Senhor. No relato de Mateus, Judas só é mencionado novamente em Mt 26:47, quando chega no jardim de Getsêmani com uma multidão para trair Jesus.
====

[[v40-26-26]]

^<<v40-26-26,26>>^ Ao continuarem a comer, Jesus pegou um pão e, depois de proferir uma bênção, partiu-o e deu aos discípulos, dizendo: “Peguem, comam. Isto representa o meu corpo.”

[TIP]
====
- *pegou um pão . . . partiu-o*: O verbo grego traduzido como “partir” significa literalmente “quebrar”. No Antigo Oriente Próximo, os pães geralmente eram finos e, se fossem feitos sem fermento, ficavam quebradiços. O fato de Jesus ter partido, ou quebrado, os pães não tem nenhum significado especial. Esse era apenas o jeito normal de dividir aquele tipo de pão. — Veja a nota de estudo em Mt 14:19.
- *proferir uma bênção*: Pelo visto, se refere a fazer uma oração de louvor e agradecimento a Deus.
- *representa*: Lit.: “é”. Aqui o verbo grego estín é usado com o sentido de “significa; simboliza”. Isso era bem claro para os apóstolos porque, naquela ocasião, o corpo perfeito de Jesus estava ali na frente deles, e também o pão sem fermento que iam comer. Assim, o pão não podia ser o corpo literal de Jesus. É interessante que a mesma palavra grega estín é usada em Mt 12:7, e muitas Bíblias a traduzem como “significa”.
====

[[v40-26-27]]

^<<v40-26-27,27>>^ E, pegando um cálice, ele deu graças e o deu a eles, dizendo: “Bebam dele, todos vocês,

[[v40-26-28]]

^<<v40-26-28,28>>^ pois isto representa o meu ‘sangue do pacto’, que será derramado em benefício de muitos, para o perdão de pecados.

[TIP]
====
- *sangue do pacto*: O novo pacto, entre Jeová e os cristãos ungidos, começou a vigorar por meio do sacrifício de Jesus. (He 8:10) Jesus usou aqui a mesma expressão que Moisés, como mediador, tinha usado quando inaugurou o pacto da Lei com Israel no monte Sinai. (Êx 24:8; He 9:19-21) Assim como o pacto entre Deus e a nação de Israel se tornou válido por meio do sangue dos novilhos e dos bodes, o pacto entre Jeová e o Israel espiritual se tornou válido por meio do sangue de Jesus. Esse novo pacto entrou em vigor no Pentecostes de 33 d.C. — He 9:14, 15.
====

[[v40-26-29]]

^<<v40-26-29,29>>^ Eu lhes digo, porém: Eu de modo algum beberei novamente deste produto da videira até aquele dia em que beberei vinho novo com vocês, no Reino do meu Pai.”

[TIP]
====
- *beberei vinho novo*: Na Bíblia, o vinho às vezes representa alegria. — Sal 104:15; Ec 10:19.
====

[[v40-26-30]]

^<<v40-26-30,30>>^ Por fim, depois de cantarem louvores, saíram para o monte das Oliveiras.

[TIP]
====
- *depois de cantarem louvores*: Ou: “depois de cantarem hinos (salmos)”. De acordo com certa tradição judaica, os judeus cantavam ou recitavam os dois primeiros Salmos de Halel (113 e 114) durante a refeição da Páscoa e, no final da refeição, os quatro últimos (115 a 118). Esses últimos contêm algumas profecias relacionadas ao Messias. O Salmo 118 começa e termina com as palavras: “Agradeçam a Jeová, pois ele é bom; o seu amor leal dura para sempre.” (Sal 118:1, 29) É provável que essas tenham sido as últimas palavras de louvor que Jesus cantou com seus apóstolos fiéis na noite antes de morrer.
====

[[v40-26-31]]

^<<v40-26-31,31>>^ Jesus lhes disse então: “Esta noite, todos vocês tropeçarão no que diz respeito a mim, pois está escrito: ‘Ferirei o pastor, e as ovelhas do rebanho serão espalhadas.’

[[v40-26-32]]

^<<v40-26-32,32>>^ Mas, depois que eu for levantado, irei adiante de vocês para a Galileia.”

[[v40-26-33]]

^<<v40-26-33,33>>^ No entanto, Pedro lhe disse em resposta: “Ainda que todos os outros tropecem no que diz respeito ao senhor, eu nunca tropeçarei!”

[[v40-26-34]]

^<<v40-26-34,34>>^ Jesus lhe disse: “Digo-lhe a verdade: Esta noite, antes de o galo cantar, você me negará três vezes.”

[TIP]
====
- *antes de o galo cantar*: Os quatro Evangelhos mencionam esta declaração de Jesus, mas o Evangelho de Marcos é o único que acrescenta o detalhe de que o galo cantaria duas vezes. (Mt 26:74, 75; Mr 14:30, 72; Lu 22:34, 60, 61; Jo 13:38; 18:27) A Mishná indica que nos dias de Jesus as pessoas criavam galos em Jerusalém, e isso apoia o relato da Bíblia. É provável que o galo tenha cantado bem cedo de manhã.
====

[[v40-26-35]]

^<<v40-26-35,35>>^ Pedro lhe disse: “Mesmo que eu tenha de morrer com o senhor, de modo algum o negarei.” Todos os outros discípulos disseram a mesma coisa.

[[v40-26-36]]

^<<v40-26-36,36>>^ Jesus chegou então com eles a um lugar chamado Getsêmani e disse aos discípulos: “Sentem-se aqui enquanto eu vou ali para orar.”

[TIP]
====
- *Getsêmani*: Esse jardim pelo visto ficava no monte das Oliveiras, do outro lado do vale do Cédron, ao leste de Jerusalém. É provável que existisse ali um lagar de azeitonas, porque o nome Getsêmani vem da expressão hebraica ou aramaica gath shemanéh, que significa “lagar de azeite”. Não se sabe exatamente onde esse jardim ficava, mas alguns acreditam que Getsêmani seja um jardim que fica no sopé do monte das Oliveiras, na bifurcação da estrada, na encosta oeste do monte. — Veja o Apêndice B12-A.
====

[[v40-26-37]]

^<<v40-26-37,37>>^ E, levando consigo Pedro e os dois filhos de Zebedeu, começou a ficar triste e muito aflito.

[TIP]
====
- *dois filhos de Zebedeu*: Ou seja, os apóstolos Tiago e João. — Mt 4:21; 10:2.
====

[[v40-26-38]]

^<<v40-26-38,38>>^ Disse-lhes então: “Estou profundamente triste, a ponto de morrer. Fiquem aqui e mantenham-se vigilantes comigo.”

[TIP]
====
- *Estou*: Ou: “Minha alma está”. A palavra grega psykhé, que foi traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, aqui se refere à pessoa como um todo. Assim, a expressão original para “minha alma” pode ser traduzida como “todo o meu ser” ou simplesmente “eu”. — Veja o Glossário, “Alma”.
- *mantenham-se vigilantes*: Lit.: “fiquem acordados”. Jesus já tinha avisado seus discípulos sobre a importância de continuar espiritualmente acordados, pois eles não sabiam em que dia e hora ele viria. (Veja as notas de estudo em Mt 24:42; 25:13.) Ele repete esse aviso aqui neste versículo e em Mt 26:41, onde diz que é importante perseverar em oração para continuar espiritualmente acordado. Outros livros das Escrituras Gregas Cristãs contêm avisos parecidos, mostrando que continuar espiritualmente desperto é vital para os verdadeiros cristãos. — 1Co 16:13; Col 4:2; 1Te 5:6; 1Pe 5:8; Ap 16:15.
====

[[v40-26-39]]

^<<v40-26-39,39>>^ E, indo um pouco mais adiante, ele se prostrou com o rosto por terra e orou: “Meu Pai, se for possível, deixa que este cálice se afaste de mim. Contudo, não como eu quero, mas como tu queres.”

[TIP]
====
- *se prostrou com o rosto por terra*: Ou: “se jogou para baixo com o rosto voltado para o chão”, talvez se apoiando com as mãos ou os cotovelos. A Bíblia menciona várias posturas diferentes em que as pessoas oravam, como de pé ou de joelhos. Mas ao fazer uma oração fervorosa a pessoa talvez se deitasse de bruços no chão, com o corpo estendido e o rosto voltado para baixo.
- *deixa que este cálice se afaste*: A Bíblia muitas vezes usa a palavra “cálice” para representar a “porção” que Deus dá a alguém, ou seja, a vontade de Deus para aquela pessoa. (Veja a nota de estudo em Mt 20:22.) Jesus sem dúvida ficou muito preocupado porque morrer acusado de blasfêmia e sedição poderia manchar o nome de Deus. Por isso, Jesus orou para que esse “cálice” se afastasse dele.
====

[[v40-26-40]]

^<<v40-26-40,40>>^ Ele voltou aos discípulos e os encontrou dormindo, e disse a Pedro: “Vocês não conseguiram se manter vigilantes comigo nem mesmo por uma hora?

[TIP]
====
- *Vocês não conseguiram*: Em grego, o verbo traduzido aqui como “vocês . . . conseguiram” está na segunda pessoa do plural. Isso indica que Jesus não estava falando apenas com Pedro, mas também com os outros discípulos.
====

[[v40-26-41]]

^<<v40-26-41,41>>^ Mantenham-se vigilantes e orem continuamente para que não caiam em tentação. Naturalmente, o espírito está disposto,^&#42;1^ mas a carne é fraca.”

[NOTE]
====
. Ou: “pronto”.
====

[TIP]
====
- *espírito*: Aqui, a palavra “espírito” se refere à força que vem do coração figurativo de uma pessoa e que a motiva a falar e fazer coisas de certo modo. — Veja o Glossário.
- *carne*: Na Bíblia, a palavra “carne” muitas vezes representa o homem em seu estado imperfeito e pecador.
====

[[v40-26-42]]

^<<v40-26-42,42>>^ Novamente, pela segunda vez, se afastou e orou: “Meu Pai, se não é possível que isto se afaste de mim sem que eu o beba, seja feita a tua vontade.”

[[v40-26-43]]

^<<v40-26-43,43>>^ E voltou novamente e os encontrou dormindo, pois estavam com os olhos pesados.

[[v40-26-44]]

^<<v40-26-44,44>>^ Portanto, deixando-os, se afastou novamente e orou pela terceira vez, dizendo mais uma vez a mesma coisa.

[[v40-26-45]]

^<<v40-26-45,45>>^ Voltou então aos discípulos e lhes disse: “Numa ocasião como esta, vocês estão dormindo e descansando! Vejam! Está se aproximando a hora de o Filho do Homem ser entregue^&#42;1^ às mãos de pecadores.

[NOTE]
====
. Ou: “traído”.
====

[TIP]
====
- *Vejam!*: Veja a nota de estudo em Mt 1:23.
====

[[v40-26-46]]

^<<v40-26-46,46>>^ Levantem-se, vamos embora. Vejam! Aquele que me trai está chegando.”

[[v40-26-47]]

^<<v40-26-47,47>>^ Naquele momento, enquanto ele ainda falava, aproximou-se Judas, um dos Doze, e com ele uma grande multidão com espadas e bastões. Eles tinham sido enviados pelos principais sacerdotes e pelos anciãos do povo.

[[v40-26-48]]

^<<v40-26-48,48>>^ O traidor havia lhes dado um sinal, dizendo: “Aquele que eu beijar é ele; prendam-no.”

[[v40-26-49]]

^<<v40-26-49,49>>^ E, dirigindo-se diretamente a Jesus, disse: “Olá, Rabi!” e o beijou ternamente.

[TIP]
====
- *o beijou ternamente*: O verbo grego traduzido como “beijar ternamente” é uma forma intensificada do verbo “beijar”, que aparece em Mt 26:48. O cumprimento tão carinhoso e amigável de Judas mostra como ele era falso e hipócrita.
====

[[v40-26-50]]

^<<v40-26-50,50>>^ Mas Jesus lhe disse: “Amigo, com que objetivo você está aqui?” Então eles avançaram, agarraram Jesus e o prenderam.

[[v40-26-51]]

^<<v40-26-51,51>>^ Mas, de repente, um dos que estavam com Jesus estendeu a mão, puxou a espada e atacou o escravo do sumo sacerdote, decepando-lhe a orelha.

[TIP]
====
- *um dos que estavam com Jesus*: O relato paralelo em Jo 18:10 mostra que foi Simão Pedro quem puxou a espada e que o nome do escravo do sumo sacerdote era Malco. Os relatos em Lu 22:50 e Jo 18:10 acrescentam o detalhe de que a orelha cortada foi a “orelha direita”. — Veja a nota de estudo em Jo 18:10.
- *atacou o escravo do sumo sacerdote*: Veja a nota de estudo em Jo 18:10.
====

[[v40-26-52]]

^<<v40-26-52,52>>^ Jesus lhe disse então: “Devolva a espada ao seu lugar, pois todos os que tomarem a espada morrerão pela espada.

[[v40-26-53]]

^<<v40-26-53,53>>^ Ou você pensa que não posso apelar ao meu Pai, para que ele me forneça neste momento mais de 12 legiões de anjos?

[TIP]
====
- *legiões*: Principais divisões do exército romano. No século 1 d.C., uma legião geralmente tinha cerca de 6.000 soldados. Aqui, a expressão “12 legiões” parece representar um número grande e indeterminado. Jesus estava dizendo que podia pedir que seu Pai enviasse quantos anjos fossem necessários, ou até mais, para protegê-lo.
====

[[v40-26-54]]

^<<v40-26-54,54>>^ Nesse caso, como se cumpririam as Escrituras que dizem que as coisas têm de acontecer deste modo?”

[TIP]
====
- *as Escrituras*: Expressão muitas vezes usada para se referir às Escrituras Hebraicas como um todo.
====

[[v40-26-55]]

^<<v40-26-55,55>>^ Jesus disse à multidão, naquela hora: “Vocês vieram me prender com espadas e bastões, como se eu fosse um bandido? Dia após dia eu ficava sentado no templo, ensinando; contudo, vocês não me prenderam.

[[v40-26-56]]

^<<v40-26-56,56>>^ Mas tudo isso aconteceu para que se cumprissem os escritos^&#42;1^ dos profetas.” Então, todos os discípulos o abandonaram e fugiram.

[NOTE]
====
. Ou: “as Escrituras”.
====

[TIP]
====
- *para que se cumprissem os escritos dos profetas*: Veja a nota de estudo em Mt 1:22.
====

[[v40-26-57]]

^<<v40-26-57,57>>^ Os que prenderam Jesus o levaram a Caifás, o sumo sacerdote, onde estavam reunidos os escribas e os anciãos.

[TIP]
====
- *Caifás, o sumo sacerdote*: Veja a nota de estudo em Mt 26:3.
====

[[v40-26-58]]

^<<v40-26-58,58>>^ Mas Pedro o seguiu de uma boa distância, até o pátio do sumo sacerdote, e, depois de entrar, se sentou com os criados para ver o que ia acontecer.

[[v40-26-59]]

^<<v40-26-59,59>>^ Os principais sacerdotes e todo o Sinédrio estavam procurando falsos testemunhos contra Jesus, para entregá-lo à morte.

[TIP]
====
- *principais sacerdotes*: Expressão que se refere aos homens mais importantes do sacerdócio. — Veja a nota de estudo em Mt 2:4 e o Glossário, “Principal sacerdote”.
- *Sinédrio*: Ou seja, o supremo tribunal judaico em Jerusalém. A palavra grega traduzida como “Sinédrio” (synédrion) significa literalmente “sentar-se com”. Embora fosse uma palavra genérica para uma assembleia ou reunião, em Israel ela podia se referir a um tribunal religioso. — Veja a nota de estudo em Mt 5:22 e o Glossário; veja a possível localização do Sinédrio no Apêndice B12-A.
====

[[v40-26-60]]

^<<v40-26-60,60>>^ Mas não encontraram nenhum, embora muitas testemunhas falsas se apresentassem. Mais tarde, se apresentaram duas

[[v40-26-61]]

^<<v40-26-61,61>>^ e disseram: “Este homem disse: ‘Eu posso derrubar o templo de Deus e reconstruí-lo em três dias.’”

[[v40-26-62]]

^<<v40-26-62,62>>^ Em vista disso, o sumo sacerdote se levantou e lhe disse: “Você não diz nada em resposta? O que diz do testemunho destes homens contra você?”

[[v40-26-63]]

^<<v40-26-63,63>>^ Mas Jesus continuou calado. Então o sumo sacerdote lhe disse: “Pelo Deus vivente, eu ponho você sob juramento para que nos diga se você é o Cristo, o Filho de Deus!”

[TIP]
====
- *o Cristo*: Veja a nota de estudo em Mt 11:2.
====

[[v40-26-64]]

^<<v40-26-64,64>>^ Jesus lhe disse: “O senhor mesmo está dizendo isso. Contudo, eu lhes digo: De agora em diante vocês verão o Filho do Homem sentado à direita de poder e vindo nas nuvens do céu.”

[TIP]
====
- *O senhor mesmo está dizendo isso*: Jesus não estava fugindo da pergunta de Caifás, pois ele reconhecia que o sumo sacerdote tinha autoridade para colocá-lo sob juramento. (Mt 26:63) Pelo visto, tratava-se de uma expressão idiomática que os judeus usavam para confirmar uma informação apresentada numa pergunta. Isso é apoiado pelo relato paralelo de Marcos, que diz que a resposta de Jesus foi: “Sou.” — Mr 14:62; veja as notas de estudo em Mt 26:25; 27:11.
- *o Filho do Homem . . . vindo nas nuvens do céu*: Jesus aqui fez referência à profecia de Da 7:13, 14, que fala sobre o Messias, e assim afirmou que ele seria a pessoa que ‘obteria acesso’ à presença de Deus e receberia um reino no céu. — Veja o Glossário, “Filho do Homem”.
- *à direita de poder*: Estar à direita de um rei significava ser a pessoa mais importante depois do próprio rei. (Sal 110:1; At 7:55, 56) É possível que a palavra grega usada aqui para “poder” se refira ao próprio Deus. Nesse caso, ela poderia ser traduzida como “o Poder” ou “o Poderoso”. A expressão grega para “direita de poder” aparece também no relato paralelo de Lu 22:69, mas junto com a palavra grega para “Deus”. Assim, a expressão é traduzida como “direita poderosa de Deus”. A expressão “direita de poder” também pode indicar que Jesus receberia poder, ou autoridade, por estar à direita do Poderoso, ou seja, Deus.
====

[[v40-26-65]]

^<<v40-26-65,65>>^ O sumo sacerdote rasgou então suas vestes, dizendo: “Ele blasfemou! Que necessidade temos ainda de testemunhas? Vejam! Agora vocês ouviram a blasfêmia.

[TIP]
====
- *rasgou então suas vestes*: Neste contexto, é um gesto que expressa indignação. Caifás provavelmente rasgou a parte da roupa que cobria o peito para mostrar de forma dramática que ele era muito devoto e estava furioso com as palavras de Jesus.
====

[[v40-26-66]]

^<<v40-26-66,66>>^ Qual é a opinião de vocês?” Eles responderam: “Ele merece morrer.”

[[v40-26-67]]

^<<v40-26-67,67>>^ Cuspiram-lhe então no rosto e o esmurraram. Outros o esbofetearam,

[[v40-26-68]]

^<<v40-26-68,68>>^ dizendo: “Profetize-nos, ó Cristo. Quem bateu em você?”

[TIP]
====
- *Profetize-nos . . . Quem bateu em você?*: Aqueles homens não estavam pedindo que Jesus fizesse uma profecia sobre o futuro, mas sim que ele dissesse, por revelação de Deus, quem tinha batido nele. Os relatos paralelos de Mr 14:65 e Lu 22:64 mostram que os inimigos de Jesus tinham coberto o rosto dele. Isso explica por que eles zombaram de Jesus, perguntando: “Quem bateu em você?”
====

[[v40-26-69]]

^<<v40-26-69,69>>^ Pedro estava sentado do lado de fora, no pátio, e uma serva se aproximou dele e disse: “Você também estava com Jesus, o galileu!”

[[v40-26-70]]

^<<v40-26-70,70>>^ Mas ele negou perante todos, dizendo: “Não sei do que você está falando.”

[[v40-26-71]]

^<<v40-26-71,71>>^ Quando ele saiu para a entrada do pátio, outra moça o notou e disse aos que estavam ali: “Este homem estava com Jesus, o Nazareno.”

[TIP]
====
- *entrada do pátio*: Lit.: “portão”. O relato paralelo de Marcos usa uma palavra que pode significar “entrada” ou “vestíbulo”, o que indica que não se tratava de um simples portão. (Mr 14:68) Pelo visto, devia ser algo construído, como um corredor ou um saguão, que ia do pátio até as portas que davam para a rua.
====

[[v40-26-72]]

^<<v40-26-72,72>>^ Ele novamente negou, com um juramento: “Não conheço esse homem!”

[[v40-26-73]]

^<<v40-26-73,73>>^ Pouco depois, os que estavam ali se aproximaram e disseram a Pedro: “Certamente você também é um deles, pois, de fato, seu dialeto o trai.”

[TIP]
====
- *seu dialeto*: Ou: “seu sotaque; seu jeito de falar”. O dialeto ou o sotaque de Pedro mostravam que ele era galileu, talvez porque o vocabulário ou a pronúncia dele eram diferentes do hebraico falado na Judeia. Alguns estudiosos sugerem que os idiomas de outras nações influenciaram o vocabulário e o sotaque da Galileia, causando a diferença.
====

[[v40-26-74]]

^<<v40-26-74,74>>^ Então ele começou a amaldiçoar a si mesmo e a jurar: “Eu não conheço esse homem!” E imediatamente um galo cantou.

[TIP]
====
- *jurar*: Ou: “fazer um juramento”. Como estava com medo, Pedro tentou convencer a todos os presentes que ele realmente não conhecia Jesus. Por ter feito um juramento, era como se Pedro dissesse: ‘Eu juro que o que eu disse é verdade. Que uma tragédia aconteça comigo se não for!’
- *um galo cantou*: Veja a nota de estudo em Mr 14:72.
====

[[v40-26-75]]

^<<v40-26-75,75>>^ E Pedro se lembrou do que Jesus tinha dito: “Antes de o galo cantar, você me negará três vezes.” Então ele saiu e chorou amargamente.

'''

xref:040-mateus/040-mateus-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-mateus/040-mateus-027.adoc#v40-27-0[Próximo Capítulo &#62;]