include::./index.adoc[]

[[v40-25-0]]
=== As Boas Novas Segundo Mateus, 25
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* L. A profecia de Jesus sobre o sinal de sua presença (24:1–25:46)
* Discípulos perguntam a Jesus qual será o sinal da presença dele (24:1-3)
* Acontecimentos que fazem parte do sinal e da grande tribulação (24:4-22)
* Falsos cristos (24:23-28)
* Vinda do Filho do Homem (24:29-31)
* Ilustração da figueira (24:32, 33)
* Esta geração não passará (24:34, 35)
* Ninguém sabe o dia e a hora; a presença de Jesus será como os dias de Noé (24:36-39)
* Mantenham-se vigilantes (24:40-44)
* Escravo fiel e prudente; características do escravo mau (24:45-51)
* Ilustração das dez virgens (25:1-13)
* Ilustração dos talentos (25:14-30)
* Ilustração das ovelhas e dos cabritos (25:31-46)
****

[[v40-25-1]]

^<<v40-25-1,1>>^ “Então o Reino dos céus pode ser comparado a dez virgens que pegaram suas lâmpadas e saíram ao encontro do noivo.

[TIP]
====
- *dez virgens . . . ao encontro do noivo*: Nos tempos bíblicos, uma parte importante da cerimônia de casamento era o cortejo que levava a noiva da casa de seu pai para a casa do noivo ou do pai dele. Tudo começava no início da noite, quando o noivo saía de sua casa vestindo sua melhor roupa e, acompanhado por seus amigos, ia até a casa dos pais da noiva para buscá-la. Na volta, músicos, cantores e, muitas vezes, pessoas carregando lâmpadas também acompanhavam o casal. As pessoas ao longo do caminho gostavam de assistir à passagem do cortejo. (Is 62:5; Je 7:34; 16:9) Pelo visto, jovens mulheres carregando lâmpadas costumavam estar entre os que se juntavam ao grupo. O cortejo seguia o trajeto sem pressa e podia demorar mais do que o esperado. Por isso, alguns dos que estavam aguardando no caminho podiam ficar com sono e acabar dormindo. Dependendo da demora, eles talvez tivessem que colocar mais óleo nas lâmpadas que seriam levadas no cortejo. As músicas e os gritos de alegria podiam ser ouvidos de longe. Depois que o noivo e seus acompanhantes entravam na casa e fechavam a porta, nenhum outro convidado podia entrar. — Mt 25:5-12; veja a nota de estudo em Mt 1:20.
====

[[v40-25-2]]

^<<v40-25-2,2>>^ Cinco delas eram tolas e cinco eram prudentes.

[TIP]
====
- *prudentes*: Ou: “sábias”. — Veja a nota de estudo em Mt 24:45.
====

[[v40-25-3]]

^<<v40-25-3,3>>^ As tolas pegaram suas lâmpadas, mas não levaram óleo,

[[v40-25-4]]

^<<v40-25-4,4>>^ ao passo que as prudentes levaram óleo em frascos, junto com suas lâmpadas.

[[v40-25-5]]

^<<v40-25-5,5>>^ Como o noivo estava demorando, todas elas ficaram com sono e adormeceram.

[[v40-25-6]]

^<<v40-25-6,6>>^ Bem no meio da noite se ouviu um grito: ‘Aqui está o noivo! Saiam ao encontro dele.’

[[v40-25-7]]

^<<v40-25-7,7>>^ Todas as virgens se levantaram então e puseram suas lâmpadas em ordem.

[TIP]
====
- *puseram suas lâmpadas em ordem*: Pelo visto, se refere a seguir alguns passos necessários, como aparar os pavios e pôr mais óleo para que as lâmpadas ficassem bem acesas.
====

[[v40-25-8]]

^<<v40-25-8,8>>^ As tolas disseram às prudentes: ‘Deem-nos um pouco do seu óleo, porque nossas lâmpadas estão quase apagando.’

[[v40-25-9]]

^<<v40-25-9,9>>^ As prudentes responderam: ‘Talvez não haja suficiente para nós e para vocês. Em vez disso, vão aos que vendem óleo e comprem um pouco para vocês.’

[[v40-25-10]]

^<<v40-25-10,10>>^ Enquanto foram comprar o óleo, veio o noivo. As virgens que estavam prontas entraram com ele para a festa de casamento, e a porta foi fechada.

[[v40-25-11]]

^<<v40-25-11,11>>^ Depois chegaram também as outras virgens, dizendo: ‘Senhor, senhor, abra para nós!’

[[v40-25-12]]

^<<v40-25-12,12>>^ Ele disse em resposta: ‘Eu lhes digo a verdade: Não conheço vocês.’

[[v40-25-13]]

^<<v40-25-13,13>>^ “Portanto, mantenham-se vigilantes, porque vocês não sabem nem o dia nem a hora.

[TIP]
====
- *mantenham-se vigilantes*: Lit.: “fiquem acordados”. Esse aviso para ficar acordado em sentido espiritual é a mensagem básica da ilustração das dez virgens. — Veja as notas de estudo em Mt 24:42; 26:38.
====

[[v40-25-14]]

^<<v40-25-14,14>>^ “Pois é como um homem que, antes de viajar para fora, convocou seus escravos e lhes confiou os seus bens.

[[v40-25-15]]

^<<v40-25-15,15>>^ A um deu cinco talentos, a outro dois e a ainda outro um, a cada um segundo a sua capacidade, e viajou para fora.

[TIP]
====
- *talentos*: O talento grego era uma unidade de peso e também uma unidade monetária, mas não existia uma moeda com esse valor. Um talento grego de prata equivalia a 20,4 quilos de prata, e valia cerca de 6.000 dracmas gregas ou 6.000 denários romanos. Um trabalhador comum teria que juntar todo o salário de uns 20 anos para conseguir um talento. — Veja o Apêndice B14-B.
====

[[v40-25-16]]

^<<v40-25-16,16>>^ Aquele que recebeu cinco talentos foi imediatamente negociar com o dinheiro, e ganhou mais cinco.

[[v40-25-17]]

^<<v40-25-17,17>>^ Do mesmo modo, aquele que recebeu dois ganhou mais dois.

[[v40-25-18]]

^<<v40-25-18,18>>^ Mas o escravo que recebeu apenas um foi embora, cavou um buraco no chão e escondeu o dinheiro do seu senhor.

[TIP]
====
- *o dinheiro*: Lit.: “a prata”. Ou seja, a prata usada como dinheiro.
====

[[v40-25-19]]

^<<v40-25-19,19>>^ “Depois de muito tempo o senhor daqueles escravos voltou e ajustou contas com eles.

[[v40-25-20]]

^<<v40-25-20,20>>^ Então o que havia recebido os cinco talentos se apresentou e trouxe outros cinco talentos, dizendo: ‘O senhor me confiou cinco talentos; veja, ganhei mais cinco talentos.’

[[v40-25-21]]

^<<v40-25-21,21>>^ Seu senhor lhe disse: ‘Muito bem, escravo bom e fiel! Você foi fiel ao cuidar de poucas coisas. Vou encarregá-lo de muitas coisas. Participe da alegria do seu senhor.’^&#42;1^

[NOTE]
====
. Ou: “Alegre-se com o seu senhor; Venha e fique feliz junto com o seu senhor”.
====

[[v40-25-22]]

^<<v40-25-22,22>>^ A seguir, aquele que havia recebido dois talentos se apresentou e disse: ‘O senhor me confiou dois talentos; veja, ganhei mais dois talentos.’

[[v40-25-23]]

^<<v40-25-23,23>>^ Seu senhor lhe disse: ‘Muito bem, escravo bom e fiel! Você foi fiel ao cuidar de poucas coisas. Vou encarregá-lo de muitas coisas. Participe da alegria do seu senhor.’

[[v40-25-24]]

^<<v40-25-24,24>>^ “Por fim, o escravo que havia recebido um talento se apresentou e disse: ‘Eu sabia que o senhor é um homem exigente,^&#42;1^ que colhe onde não semeou e ajunta onde não espalhou.^&#42;2^

[NOTE]
====
. Ou: “duro; severo”.
. Ou: “padejou”.
====

[[v40-25-25]]

^<<v40-25-25,25>>^ Por isso fiquei com medo e fui esconder no chão o seu talento. Aqui está o que é seu.’

[TIP]
====
- *esconder no chão o seu talento*: Arqueólogos e agricultores em terras bíblicas encontraram muitas moedas e objetos valiosos enterrados. Isso mostra que aquilo que o escravo da ilustração fez era algo comum.
====

[[v40-25-26]]

^<<v40-25-26,26>>^ Em resposta, seu senhor lhe disse: ‘Escravo mau e preguiçoso,^&#42;1^ quer dizer que você sabia que eu colho onde não semeei e ajunto onde não espalhei?^&#42;2^

[NOTE]
====
. Ou: “negligente; ocioso”.
. Ou: “padejei”.
====

[[v40-25-27]]

^<<v40-25-27,27>>^ Então, você devia ter entregado meu dinheiro aos banqueiros, e, na minha vinda, eu o teria recebido com juros.

[TIP]
====
- *banqueiros . . . juros*: No século 1 d.C., havia muitos banqueiros (pessoas que emprestavam dinheiro) em Israel e nas nações vizinhas. A Lei mosaica proibia que um israelita cobrasse juros ao emprestar dinheiro para outro israelita que estivesse passando necessidade. (Êx 22:25) Mas a Lei permitia cobrar juros de estrangeiros, provavelmente para empreendimentos comerciais. (De 23:20) Pelo visto, era comum nos dias de Jesus que as pessoas entregassem seu dinheiro aos banqueiros e depois o recebessem de volta com juros.
====

[[v40-25-28]]

^<<v40-25-28,28>>^ “‘Portanto, tirem dele o talento e deem-no àquele que tem dez talentos.

[[v40-25-29]]

^<<v40-25-29,29>>^ Pois a todo aquele que tem, mais será dado, e ele terá abundância. Mas daquele que não tem, até mesmo o que tem será tirado.

[[v40-25-30]]

^<<v40-25-30,30>>^ E lancem o escravo imprestável na escuridão lá fora. Ali é que haverá o seu choro e o ranger dos seus dentes.’

[TIP]
====
- *ranger dos seus dentes*: Veja a nota de estudo em Mt 8:12.
====

[[v40-25-31]]

^<<v40-25-31,31>>^ “Quando o Filho do Homem vier na sua glória, e com ele todos os anjos, então se sentará no seu trono glorioso.

[TIP]
====
- *Filho do Homem*: Veja a nota de estudo em Mt 8:20.
- *vier*: Veja a nota de estudo em Mt 24:30.
====

[[v40-25-32]]

^<<v40-25-32,32>>^ Todas as nações serão reunidas diante dele, e ele separará as pessoas umas das outras, assim como o pastor separa as ovelhas dos cabritos.

[TIP]
====
- *assim como o pastor separa as ovelhas dos cabritos*: Jesus falou aqui de algo que seus ouvintes conheciam bem. Nos tempos bíblicos, pastores muitas vezes tomavam conta de rebanhos mistos. (Gên 30:32, 33; 31:38) No Oriente Médio, era comum formar rebanhos de ovelhas e cabritos, e era fácil para o pastor identificar e separar os dois tipos de animais quando quisesse. Os animais podiam ser separados por diversos motivos, como, por exemplo, para procriar ou pastar, ou para que fossem ordenhados, tosquiados ou abatidos. Outras vezes, isso era feito para incentivar os animais de cada espécie a se agruparem e se manterem aquecidos durante a noite. Seja como for, a ilustração descreve muito bem a clara separação que ocorrerá quando “o Filho do Homem vier na sua glória”. — Mt 25:31.
====

[[v40-25-33]]

^<<v40-25-33,33>>^ E porá as ovelhas à sua direita, mas os cabritos à sua esquerda.

[TIP]
====
- *à sua direita . . . à sua esquerda*: Em alguns contextos, as duas posições indicam honra e autoridade (Mt 20:21, 23), só que a posição de maior honra é sempre a da direita (Sal 110:1; At 7:55, 56; Ro 8:34). Mas aqui e em Mt 25:34, 41, há uma diferença bem clara entre o lado direito, que indica que a pessoa tem o favor do Rei, e o lado esquerdo, que indica que a pessoa não tem o favor dele. — Compare com as notas de rodapé em Ec 10:2.
- *os cabritos*: Em sua ilustração, Jesus usou “cabritos” para representar as pessoas que não apoiam seus irmãos espirituais. Mas parece que ele não fez isso pensando em alguma característica negativa dos cabritos. Apesar de esses animais serem mais independentes e, às vezes, mais teimosos do que as ovelhas, eles eram considerados pela Lei como animais puros e podiam ser usados no lugar das ovelhas na celebração da Páscoa. (Êx 12:5; De 14:4) Além disso, a Lei exigia que, no Dia da Expiação, o sangue de um bode (cabrito) fosse usado para fazer expiação pelos pecados da nação de Israel. (Le 16:7-27) Assim, parece que Jesus usou dois tipos diferentes de animais simplesmente porque queria representar dois tipos diferentes de pessoas. — Mt 25:32.
====

[[v40-25-34]]

^<<v40-25-34,34>>^ “O Rei dirá então aos à sua direita: ‘Venham vocês, abençoados por meu Pai, herdem o Reino preparado para vocês desde a fundação do mundo.

[TIP]
====
- *herdem*: O verbo grego usado aqui tem o sentido básico de receber algo por direito, geralmente por parentesco, como por exemplo, um filho que recebe uma herança de seu pai. (Gál 4:30) Mas aqui, e na maioria das vezes em que esse verbo aparece nas Escrituras Gregas Cristãs, ele tem um sentido mais amplo: refere-se a ganhar uma recompensa de Deus. — Mt 19:29; 1Co 6:9.
- *o Reino*: A Bíblia usa a palavra “reino” com vários sentidos, por exemplo: “região ou país governado por um rei”, “autoridade real” e “condição de ser súdito de um rei”. Aqui, a palavra “Reino” pelo visto se refere a receber as bênçãos de viver em um mundo governado pelo Reino de Deus.
- *fundação do mundo*: A palavra grega para “fundação” é traduzida como “conceber” em He 11:11, onde aparece junto com a palavra “descendente”. Aqui, na expressão “fundação do mundo”, a palavra grega parece se referir à época em que Adão e Eva geraram filhos. Em Lu 11:50, 51, Jesus relacionou “a fundação do mundo” com Abel. Pelo visto, Abel foi o primeiro humano a receber a oportunidade de ser salvo pelo resgate e de ter, desde “a fundação do mundo”, o nome escrito no rolo da vida. — Ap 17:8.
====

[[v40-25-35]]

^<<v40-25-35,35>>^ Pois fiquei com fome, e vocês me deram algo para comer; fiquei com sede, e vocês me deram algo para beber. Eu era um estranho, e vocês me receberam hospitaleiramente;

[[v40-25-36]]

^<<v40-25-36,36>>^ estava nu, e vocês me vestiram. Fiquei doente, e vocês cuidaram de mim. Eu estava na prisão, e vocês me visitaram.’

[TIP]
====
- *nu*: Ou: “sem roupa suficiente”. A palavra grega gymnós pode significar “pouco vestido; só com a roupa de baixo”. — Tg 2:15, nota de rodapé.
====

[[v40-25-37]]

^<<v40-25-37,37>>^ Então, os justos lhe responderão: ‘Senhor, quando foi que o vimos com fome e o alimentamos, ou com sede e lhe demos algo para beber?

[[v40-25-38]]

^<<v40-25-38,38>>^ Quando o vimos como um estranho e o recebemos hospitaleiramente, ou nu e o vestimos?

[[v40-25-39]]

^<<v40-25-39,39>>^ Quando o vimos doente ou na prisão e fomos visitá-lo?’

[[v40-25-40]]

^<<v40-25-40,40>>^ O Rei lhes dirá, em resposta: ‘Eu lhes digo a verdade: O que vocês fizeram a um dos menores destes meus irmãos, a mim o fizeram.’

[TIP]
====
- *Eu lhes digo a verdade*: Veja a nota de estudo em Mt 5:18.
- *irmãos*: Quando a palavra grega para “irmão” está no plural, ela pode incluir homens e mulheres.
====

[[v40-25-41]]

^<<v40-25-41,41>>^ “Então dirá aos à sua esquerda: ‘Afastem-se de mim, amaldiçoados; vão para o fogo eterno preparado para o Diabo e seus anjos.

[[v40-25-42]]

^<<v40-25-42,42>>^ Pois fiquei com fome, mas vocês não me deram nada para comer; e fiquei com sede, mas vocês não me deram nada para beber.

[[v40-25-43]]

^<<v40-25-43,43>>^ Eu era um estranho, mas vocês não me receberam hospitaleiramente; estava nu, mas vocês não me vestiram; doente e na prisão, mas vocês não cuidaram de mim.’

[[v40-25-44]]

^<<v40-25-44,44>>^ Então eles também responderão: ‘Senhor, quando foi que o vimos com fome, ou com sede, ou como um estranho, ou nu, ou doente, ou na prisão, e não o servimos?’

[[v40-25-45]]

^<<v40-25-45,45>>^ Então ele lhes responderá: ‘Eu lhes digo a verdade: O que vocês não fizeram a um destes menores, a mim não o fizeram.’

[[v40-25-46]]

^<<v40-25-46,46>>^ Estes partirão para o decepamento eterno; mas os justos, para a vida eterna.”

[TIP]
====
- *decepamento*: Aqui se refere a ser decepado, ou cortado, da vida. A palavra grega kólasis é usada com o sentido de “podar” ou “cortar” galhos de uma árvore. O “decepamento” seria “eterno” porque a pessoa seria ‘decepada’ da vida sem ter a esperança de uma ressurreição.
====

'''

xref:040-mateus/040-mateus-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-mateus/040-mateus-026.adoc#v40-26-0[Próximo Capítulo &#62;]