include::./index.adoc[]

[[v40-2-0]]
=== As Boas Novas Segundo Mateus, 2
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* B. Do nascimento ao batismo de Jesus (1:18–3:17)
* Maria fica grávida por espírito santo; reação de José (1:18-25)
* Visita dos astrólogos; plano de Herodes (2:1-12)
* José e Maria fogem com seu filho para o Egito (2:13-15)
* Herodes mata meninos em Belém e nos arredores (2:16-18)
* Família de Jesus se muda para Nazaré (2:19-23)
* Pregação de João Batista (3:1-12)
* Batismo de Jesus (3:13-17)
****

[[v40-2-1]]

^<<v40-2-1,1>>^ Depois que Jesus nasceu em Belém da Judeia, nos dias do rei Herodes, astrólogos vindos do Oriente chegaram a Jerusalém,

[TIP]
====
- *Belém da Judeia*: Em Israel, havia duas cidades chamadas Belém. Uma ficava no território de Zebulão (Jos 19:10, 15) e a outra em Judá (Judeia). Por isso, esta última era muitas vezes chamada de “Belém de Judá”. (Jz 17:7-9; 19:1, 2, 18) Tudo indica que o nome anterior dessa cidade era Efrata. Isso explica por que Miq 5:2 diz que o Messias viria de “Belém Efrata”. — Gên 35:19; 48:7.
- *Herodes*: Refere-se a Herodes, o Grande. — Veja o Glossário.
- *astrólogos*: Em grego, mágoi (plural de mágos). Pelo visto se refere a pessoas peritas em astrologia e em outras práticas de ocultismo que as Escrituras Sagradas condenam. (De 18:10-12) A Bíblia não diz quantos astrólogos eram. A mesma palavra grega foi traduzida como “feiticeiro” em At 13:6, 8 e foi usada pela Septuaginta em Da 2:2, 10 como equivalente às palavras hebraica e aramaica para “adivinho”.
====

[[v40-2-2]]

^<<v40-2-2,2>>^ dizendo: “Onde está aquele que nasceu para ser rei dos judeus? Pois vimos a sua estrela quando estávamos no Oriente e viemos lhe prestar homenagem.”

[TIP]
====
- *estrela*: É bem provável que não fosse realmente uma estrela nem um alinhamento de planetas. Os astrólogos foram os únicos que “viram” a estrela.
- *quando estávamos no Oriente*: A palavra grega traduzida como “Oriente” significa literalmente “nascente”. Alguns acham que essa palavra indica que os astrólogos viram a estrela na parte oriental (leste) do céu, ou que viram a estrela “nascendo”, ou surgindo no horizonte. Mas, neste contexto, é mais provável que essa palavra se refira ao lugar em que os astrólogos estavam quando viram a estrela.
- *lhe prestar homenagem*: Ou: “nos curvar diante dele”. Quando o verbo grego proskynéo é usado em relação a um deus, ele é traduzido como “adorar”. Mas, neste relato, os astrólogos queriam saber onde estava “aquele que nasceu para ser rei dos judeus”. Então fica claro que o verbo grego aqui se refere a prestar homenagem a um rei humano, e não a adorar um deus. O texto de Mr 15:18, 19 usa esse verbo de um jeito parecido. Lá diz que, para zombar de Jesus, os soldados “se curvaram” diante dele e o chamaram de “Rei dos judeus”. — Veja a nota de estudo em Mt 18:26.
====

[[v40-2-3]]

^<<v40-2-3,3>>^ Ao ouvir isso, o rei Herodes ficou agitado e, com ele, toda a cidade de Jerusalém.

[[v40-2-4]]

^<<v40-2-4,4>>^ Ele convocou então todos os principais sacerdotes e os escribas do povo e perguntou a eles onde o Cristo nasceria.

[TIP]
====
- *principais sacerdotes*: Quando a palavra grega aparece no singular e se refere ao principal representante do povo diante de Deus, ela é traduzida como “sumo sacerdote”. Aqui, a palavra grega aparece no plural e se refere aos homens mais importantes do sacerdócio, incluindo ex-sumos sacerdotes e, possivelmente, os cabeças das 24 turmas de sacerdotes.
- *escribas*: Inicialmente, essa palavra era usada para se referir aos copistas das Escrituras. Na época de Jesus, a palavra era usada para se referir a homens que eram peritos na Lei mosaica e que a ensinavam a outros.
- *o Cristo*: Aqui, Mateus usou o artigo definido em grego antes do título “Cristo”. Provavelmente, ele fez isso para destacar o papel de Jesus como o Messias.
====

[[v40-2-5]]

^<<v40-2-5,5>>^ Disseram-lhe: “Em Belém da Judeia, pois é assim que se escreveu por meio do profeta:

[TIP]
====
- *Belém*: Nome de origem hebraica que significa “casa de pão”. Belém era a cidade onde Davi nasceu e, às vezes, era chamada de “cidade de Davi”. — Lu 2:4, 11; Jo 7:42.
====

[[v40-2-6]]

^<<v40-2-6,6>>^ ‘E você, ó Belém da terra de Judá, de modo algum é a cidade mais insignificante entre os governadores^&#42;1^ de Judá, pois de você sairá um governante^&#42;2^ que pastoreará o meu povo, Israel.’”

[NOTE]
====
. Ou: “governantes; líderes”.
. Ou: “governador; líder”.
====

[TIP]
====
- *de modo algum é a cidade mais insignificante*: Mateus cita aqui a profecia de Miq 5:2. Belém tinha uma população bem pequena (em Jo 7:42 ela é até chamada de aldeia) e não tinha influência política. Apesar disso, Belém se tornaria uma cidade muito importante, porque o maior governante de todos sairia de lá para pastorear o povo de Deus, Israel.
====

[[v40-2-7]]

^<<v40-2-7,7>>^ Então, Herodes convocou secretamente os astrólogos e procurou saber deles o tempo exato do aparecimento da estrela.

[[v40-2-8]]

^<<v40-2-8,8>>^ Ao enviá-los a Belém, ele disse: “Vão, procurem cuidadosamente a criancinha e, quando a encontrarem, avisem-me, para que eu também possa ir e lhe prestar homenagem.”

[TIP]
====
- *lhe prestar homenagem*: Ou: “honrá-lo”. Ao dizer isso, Herodes estava se referindo a um ato de respeito a um rei humano, e não à adoração de um Deus. — Para saber mais sobre a palavra grega, veja a nota de estudo em Mt 2:2.
====

[[v40-2-9]]

^<<v40-2-9,9>>^ Depois de ouvirem o rei, partiram, e observaram que a estrela que tinham visto quando estavam no Oriente ia adiante deles, até que parou sobre o lugar onde estava a criancinha.

[[v40-2-10]]

^<<v40-2-10,10>>^ Quando viram a estrela, ficaram cheios de alegria.

[[v40-2-11]]

^<<v40-2-11,11>>^ Ao entrarem na casa, viram a criancinha com Maria, sua mãe, e, prostrando-se, prestaram homenagem à criancinha. Abriram também seus tesouros e lhe deram presentes: ouro, olíbano e mirra.

[TIP]
====
- *casa*: O fato de os astrólogos visitarem Jesus numa casa mostra que essa visita não aconteceu quando Jesus era um bebê recém-nascido na manjedoura de um estábulo.
- *a criancinha*: Nessa ocasião Jesus não é mais chamado de “bebê”, palavra usada em Lu 2:12, 16.
- *prestaram homenagem à*: Ou: “curvaram-se diante da”. Essa expressão muitas vezes se refere a um ato de respeito a um humano (por exemplo, um rei), e não de adoração a um deus. — Veja as notas de estudo em Mt 2:2; 18:26.
- *presentes*: Tudo indica que Jesus não ganhou os presentes logo que nasceu. Quando José e Maria levaram Jesus 40 dias depois do nascimento para apresentá-lo no templo, a oferta que eles fizeram mostra que eles eram pobres. (Lu 2:22-24; Le 12:6-8) Assim, a visita dos astrólogos deve ter acontecido algum tempo depois disso. Os presentes devem ter ajudado a cobrir as despesas que a família teve no Egito.
- *olíbano*: Veja o Glossário.
- *mirra*: Veja o Glossário.
====

[[v40-2-12]]

^<<v40-2-12,12>>^ No entanto, visto que receberam em sonho um aviso divino para não voltarem a Herodes, partiram para a sua terra por outro caminho.

[[v40-2-13]]

^<<v40-2-13,13>>^ Depois que eles partiram, o anjo de Jeová apareceu a José num sonho, dizendo: “Levante-se, pegue a criancinha e a mãe dela, fuja para o Egito e fique ali até eu avisá-lo, porque Herodes está prestes a procurar a criancinha para matá-la.”

[TIP]
====
- *anjo de Jeová*: Veja a nota de estudo em Mt 1:20 e o Apêndice C3 (introdução e Mt 2:13).
- *Egito*: Naquela época, o Egito era uma província de Roma, e muitos judeus moravam lá. Herodes emitiu seu decreto em Jerusalém, que ficava uns 9 quilômetros ao nordeste de Belém, mas o Egito ficava ao sudoeste de Belém. Assim, José e Maria podiam viajar em segurança para o Egito sem passar por Jerusalém, e então escapar do decreto de Herodes.
====

[[v40-2-14]]

^<<v40-2-14,14>>^ Assim, José se levantou, pegou a criancinha e a mãe dela à noite e foi para o Egito.

[TIP]
====
- *foi para o Egito*: A distância entre Belém e o Egito era de pelo menos 120 quilômetros.
====

[[v40-2-15]]

^<<v40-2-15,15>>^ Ele ficou lá até a morte de Herodes. Isso cumpriu o que Jeová tinha dito por meio do seu profeta: “Do Egito chamei o meu filho.”

[TIP]
====
- *morte de Herodes*: Herodes provavelmente morreu no ano 1 a.C.
- *cumpriu o que Jeová tinha dito por meio do seu profeta*: Veja a nota de estudo em Mt 1:22.
- *Jeová*: Este versículo faz uma citação direta de Os 11:1, e o contexto (Os 11:1-11) deixa claro que é Jeová Deus quem está falando. — Veja o Apêndice C3 (introdução e Mt 2:15).
====

[[v40-2-16]]

^<<v40-2-16,16>>^ Vendo então que tinha sido enganado pelos astrólogos, Herodes ficou furioso e mandou matar, em Belém e nos arredores, todos os meninos de dois anos de idade para baixo, segundo o tempo exato que tinha verificado com os astrólogos.

[TIP]
====
- *mandou matar . . . todos os meninos*: Registros históricos mostram que Herodes, o Grande, era mesmo uma pessoa violenta. Ele matou pelo menos 45 pessoas que apoiavam um inimigo dele. Ele suspeitava tanto das pessoas ao seu redor que mandou matar sua esposa Mariana I, três filhos, o irmão de sua esposa, o avô de sua esposa (Hircano), vários amigos bem próximos e muitos outros. Algumas fontes dizem que, para impedir que os judeus ficassem felizes com a morte dele, Herodes deu uma ordem: quando ele morresse, os judeus de destaque também deveriam ser mortos. Essa ordem não foi cumprida.
====

[[v40-2-17]]

^<<v40-2-17,17>>^ Cumpriram-se assim as palavras de Jeremias, o profeta, que disse:

[[v40-2-18]]

^<<v40-2-18,18>>^ “Ouviu-se uma voz em Ramá, choro e muito lamento. Era Raquel chorando por seus filhos, e ela não queria ser consolada, porque eles já não existem.”

[TIP]
====
- *Ramá*: Cidade no território de Benjamim, ao norte de Jerusalém. Pelo que parece, quando Jerusalém foi destruída em 607 a.C., os babilônios juntaram todos os judeus cativos em Ramá antes de os levarem a Babilônia e, possivelmente, mataram alguns judeus ali. Alguns comentaristas bíblicos acreditam que o texto de Je 31:15, citado aqui por Mateus, se refere a essa ocasião.
- *Raquel*: Na profecia de Jeremias, Raquel, que foi enterrada perto de Belém, representa todas as mães em Israel. Raquel chora pelos seus filhos que foram levados para o exílio na terra do inimigo. Mas essa profecia traz uma promessa consoladora: eles iam ‘voltar da terra do inimigo’. (Je 31:16) Mateus foi inspirado por Deus a explicar que o choro de Raquel teve outro cumprimento na matança dos meninos em Belém. Nesse cumprimento, os meninos foram levados pelo inimigo da humanidade, a morte. Assim, a ‘volta da terra do inimigo’ teria que ser por meio da ressurreição.
====

[[v40-2-19]]

^<<v40-2-19,19>>^ Após a morte de Herodes, o anjo de Jeová apareceu a José num sonho, no Egito,

[TIP]
====
- *anjo de Jeová*: Veja a nota de estudo em Mt 1:20 e o Apêndice C3 (introdução e Mt 2:19).
====

[[v40-2-20]]

^<<v40-2-20,20>>^ e disse: “Levante-se, pegue a criancinha e a mãe dela, e vá para a terra de Israel, porque os que procuravam tirar a vida da criancinha já morreram.”

[TIP]
====
- *vida*: Esta é a primeira vez que aparece a palavra grega psykhé. Em algumas Bíblias, essa palavra é traduzida “alma”. Neste versículo, ela se refere à vida de uma pessoa. — Veja o Glossário, “Alma”.
====

[[v40-2-21]]

^<<v40-2-21,21>>^ Então ele se levantou, pegou a criancinha e a mãe dela, e entrou na terra de Israel.

[[v40-2-22]]

^<<v40-2-22,22>>^ Mas, ao ouvir que Arquelau reinava na Judeia no lugar de seu pai, Herodes, José ficou com medo de ir para lá. Além disso, após receber em sonho um aviso divino, partiu para o território da Galileia.

[TIP]
====
- *Arquelau*: Filho de Herodes, o Grande. Assim como o pai, ele era um governante cruel, e os judeus o odiavam. Ao tentar acabar com uma rebelião, Arquelau matou 3.000 judeus na área do templo. Quando José estava voltando do Egito, Deus o avisou sobre o perigo de voltar para a Judeia. Por isso, José e sua família foram morar em Nazaré da Galileia, uma região sobre a qual Arquelau não tinha autoridade.
====

[[v40-2-23]]

^<<v40-2-23,23>>^ E ele foi morar numa cidade chamada Nazaré, para que se cumprissem as palavras dos profetas: “Ele será chamado Nazareno.”

[TIP]
====
- *Nazaré*: Provavelmente significa “cidade do renovo” (ou: “cidade do broto”). Ficava na Baixa Galileia e foi a cidade onde Jesus morou na maior parte de sua vida na Terra.
- *as palavras dos profetas*: “Ele será chamado Nazareno”: Pelo visto, é uma referência ao livro do profeta Isaías. (Is 11:1) O livro de Isaías se refere ao Messias prometido como ‘um renovo [em hebraico, nétser] que sairia das raízes de Jessé’. Como Mateus menciona “profetas” no plural, é possível que ele estivesse fazendo também referência a Jeremias e a Zacarias. Jeremias escreveu sobre “um renovo justo” que nasceria de Davi (Je 23:5; 33:15), e Zacarias falou de um rei que serviria como sacerdote e que se chamaria “Renovo”. (Za 3:8; 6:12, 13) Com o tempo, a palavra “Nazareno” foi usada para se referir a Jesus e, mais tarde, aos seus discípulos.
====

'''

xref:040-mateus/040-mateus-001.adoc#v40-1-0[&#60; Capítulo Anterior] | <<v40-2-0,Topo>> | xref:040-mateus/040-mateus-003.adoc#v40-3-0[Próximo Capítulo &#62;]