include::./index.adoc[]

[[v40-20-0]]
=== As Boas Novas Segundo Mateus, 20
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* J. Jesus prega na Pereia e na região de Jericó (19:1–20:34)
* Casamento e divórcio (19:1-9)
* Dom do estado de solteiro (19:10-12)
* Jesus abençoa as crianças (19:13-15)
* Pergunta de um jovem rico (19:16-26)
* Quem fizer sacrifícios pelo Reino será recompensado (19:27-30)
* Trabalhadores no vinhedo recebem o mesmo salário de um denário (20:1-16)
* Jesus fala mais uma vez sobre sua morte e ressurreição (20:17-19)
* Pedido para ter posições de destaque no Reino (20:20-28)
* Jesus cura dois cegos perto de Jericó (20:29-34)
****

[[v40-20-1]]

^<<v40-20-1,1>>^ “Pois o Reino dos céus é semelhante a um proprietário,^&#42;1^ que saiu de manhã cedo para contratar trabalhadores para o seu vinhedo.

[NOTE]
====
. Ou: “dono de uma casa”.
====

[TIP]
====
- *para contratar trabalhadores*: Alguns trabalhadores eram contratados para todo o período da colheita. Outros eram contratados para trabalhar por apenas um dia de cada vez, de acordo com a necessidade.
====

[[v40-20-2]]

^<<v40-20-2,2>>^ Depois de combinar com os trabalhadores um denário por dia, mandou-os ao seu vinhedo.

[TIP]
====
- *denário*: Uma moeda romana de prata que pesava 3,85 gramas e tinha a imagem de César em um dos lados. Como mostra o versículo, os trabalhadores rurais dos dias de Jesus geralmente ganhavam um denário por um dia de trabalho (12 horas). — Veja o Glossário e o Apêndice B14-B.
====

[[v40-20-3]]

^<<v40-20-3,3>>^ Por volta da terceira hora, ao sair novamente, viu outros que estavam na praça principal sem trabalhar,

[TIP]
====
- *Por volta da terceira hora*: Ou seja, por volta das 9 horas da manhã. No século 1 d.C., os judeus dividiam o período de luz do dia em 12 horas. (Jo 11:9) Esse período começava com o nascer do sol, por volta das 6 horas da manhã. Assim, a terceira hora seria por volta das 9 da manhã, a sexta hora seria por volta do meio-dia e a nona hora seria por volta das 3 da tarde. As pessoas daquela época não tinham instrumentos precisos para marcar o tempo. Por isso, os relatos bíblicos geralmente mencionam apenas o horário aproximado dos eventos. — Jo 1:39; 4:6; 19:14; At 10:3, 9.
====

[[v40-20-4]]

^<<v40-20-4,4>>^ e disse a eles: ‘Vão vocês também ao vinhedo, e eu lhes darei o que for justo.’

[[v40-20-5]]

^<<v40-20-5,5>>^ De modo que eles foram. Ele saiu novamente por volta da sexta hora e da nona hora, e fez o mesmo.

[TIP]
====
- *por volta da sexta hora*: Ou seja, por volta do meio-dia. — Veja a nota de estudo em Mt 20:3.
- *da nona hora*: Ou seja, por volta das 3 horas da tarde. — Veja a nota de estudo em Mt 20:3.
====

[[v40-20-6]]

^<<v40-20-6,6>>^ Finalmente, por volta da décima primeira hora, ele saiu e encontrou outros parados ali, e lhes perguntou: ‘Por que ficaram aqui o dia todo sem trabalhar?’

[TIP]
====
- *por volta da décima primeira hora*: Ou seja, por volta das 5 horas da tarde. — Veja a nota de estudo em Mt 20:3.
====

[[v40-20-7]]

^<<v40-20-7,7>>^ Eles responderam: ‘Porque ninguém nos contratou.’ Disse-lhes: ‘Vão também ao vinhedo.’

[[v40-20-8]]

^<<v40-20-8,8>>^ “Quando anoiteceu, o dono do vinhedo disse ao seu administrador: ‘Chame os trabalhadores e pague-lhes seu salário, começando com os últimos e terminando com os primeiros.’

[[v40-20-9]]

^<<v40-20-9,9>>^ Quando os homens da décima primeira hora chegaram, cada um deles recebeu um denário.

[[v40-20-10]]

^<<v40-20-10,10>>^ Então, quando os primeiros chegaram, concluíram que receberiam mais, mas eles também receberam o pagamento de um denário cada um.

[[v40-20-11]]

^<<v40-20-11,11>>^ Após recebê-lo, começaram a reclamar contra o proprietário

[[v40-20-12]]

^<<v40-20-12,12>>^ e disseram: ‘Esses últimos homens trabalharam só uma hora; ainda assim o senhor os igualou a nós, que suportamos o fardo do dia e o calor intenso!’

[[v40-20-13]]

^<<v40-20-13,13>>^ Mas ele disse, em resposta, a um deles: ‘Amigo, não lhe faço nenhuma injustiça. Você não concordou comigo em um denário?

[[v40-20-14]]

^<<v40-20-14,14>>^ Pegue o que é seu e vá. Eu quero dar a esse último o mesmo que a você.

[[v40-20-15]]

^<<v40-20-15,15>>^ Não tenho o direito de fazer o que quero com as minhas próprias coisas? Ou você ficou com inveja porque eu fui bom com eles?’

[TIP]
====
- *você ficou com inveja*: Lit.: “o seu olho é mau (perverso)”. (Veja a nota de estudo em Mt 6:23.) O grego usa aqui a palavra para “olho” para representar as emoções, atitudes e intenções de uma pessoa. — Compare com a expressão “olho invejoso” usada em Mr 7:22.
- *bom*: Ou: “generoso”. Neste contexto, a bondade está diretamente relacionada com um ato de generosidade.
====

[[v40-20-16]]

^<<v40-20-16,16>>^ Desse modo, os últimos serão primeiros; e os primeiros, últimos.”

[[v40-20-17]]

^<<v40-20-17,17>>^ Ao subir para Jerusalém, Jesus chamou os 12 discípulos à parte e lhes disse na estrada:

[TIP]
====
- *Ao subir*: Alguns poucos manuscritos apoiam a opção “prestes a subir”, mas muitos dos manuscritos mais antigos e confiáveis apoiam a opção “ao subir”. Por isso, esta revisão da Tradução do Novo Mundo diz “ao subir”.
- *subir para Jerusalém*: Jerusalém ficava uns 750 metros acima do nível do mar. Por isso, a Bíblia muitas vezes diz que as pessoas ‘subiam para Jerusalém’. (Mr 10:32; Jo 2:13; At 11:2) Jesus e seus discípulos estavam saindo do vale do Jordão. (Veja a nota de estudo em Mt 19:1.) O ponto mais baixo desse vale fica uns 400 metros abaixo do nível do mar. Assim, eles teriam que subir uns 1.000 metros para chegar em Jerusalém.
====

[[v40-20-18]]

^<<v40-20-18,18>>^ “Escutem, estamos subindo para Jerusalém, e o Filho do Homem será entregue aos principais sacerdotes e aos escribas. Eles o condenarão à morte

[TIP]
====
- *Filho do Homem*: Veja a nota de estudo em Mt 8:20.
====

[[v40-20-19]]

^<<v40-20-19,19>>^ e o entregarão a homens das nações para que zombem dele, o açoitem, e o matem na estaca; e no terceiro dia ele será levantado.”

[TIP]
====
- *matem na estaca*: Ou: “prendam numa estaca (num poste)”. Esta é a primeira das mais de 40 vezes em que aparece o verbo grego stauróo nas Escrituras Gregas Cristãs. Ele está relacionado com o substantivo grego staurós, que é traduzido como “estaca de tortura”. (Veja as notas de estudo em Mt 10:38; 16:24; 27:32 e o Glossário, “Madeiro; Estaca”; “Estaca de tortura”.) A Septuaginta grega usa o verbo stauróo em Est 7:9, no relato em que o rei Assuero mandou pendurar Hamã num madeiro que tinha mais de 20 metros de altura. No grego clássico, o verbo stauróo significava “cercar com estacas, construir uma paliçada”.
====

[[v40-20-20]]

^<<v40-20-20,20>>^ Aproximou-se dele então a mãe dos filhos de Zebedeu com seus filhos e, curvando-se diante dele, pediu-lhe algo.

[TIP]
====
- *mãe dos filhos de Zebedeu*: Ou seja, a mãe dos apóstolos Tiago e João. O relato paralelo em Marcos diz que quem falou com Jesus foram Tiago e João. (Mr 10:35) Pelo visto, a ideia foi deles, mas eles fizeram o pedido por meio de Salomé, sua mãe. É possível que Salomé fosse tia de Jesus. — Mt 27:55, 56; Mr 15:40, 41; Jo 19:25.
- *curvando-se diante dele*: Ou: “prestando-lhe homenagem; ajoelhando-se respeitosamente diante dele”. — Veja as notas de estudo em Mt 8:2; 18:26.
====

[[v40-20-21]]

^<<v40-20-21,21>>^ Ele lhe perguntou: “O que você quer?” Ela respondeu: “Declare que estes dois filhos meus se sentarão um à sua direita e outro à sua esquerda, no seu Reino.”

[TIP]
====
- *um à sua direita e outro à sua esquerda*: Veja a nota de estudo em Mr 10:37.
====

[[v40-20-22]]

^<<v40-20-22,22>>^ Jesus disse em resposta: “Vocês não sabem o que estão pedindo. Será que podem beber o cálice que eu estou para beber?” Disseram-lhe: “Podemos.”

[TIP]
====
- *Vocês não sabem o que estão pedindo*: Em grego, os dois verbos estão no plural. Isso, além do contexto, indica que Jesus não estava mais falando com Salomé, e sim com os dois filhos dela. — Mr 10:35-38.
- *beber o cálice*: A Bíblia muitas vezes usa a palavra “cálice” (ou: “copo”) para representar a “porção” que Deus dá a alguém, ou seja, a vontade de Deus para aquela pessoa. (Sal 11:6, nota de rodapé; 16:5; 23:5) Aqui, “beber o cálice” significa aceitar a vontade de Deus. E o “cálice” de Jesus não envolvia apenas sofrer maus-tratos e morrer por causa da acusação falsa de blasfêmia, mas também ser ressuscitado para a vida imortal no céu.
====

[[v40-20-23]]

^<<v40-20-23,23>>^ Ele lhes disse: “De fato, vocês beberão o meu cálice, mas sentar-se à minha direita e à minha esquerda não cabe a mim conceder; esses lugares pertencem àqueles para quem o meu Pai os preparou.”

[[v40-20-24]]

^<<v40-20-24,24>>^ Quando os outros dez souberam disso, ficaram indignados com os dois irmãos.

[[v40-20-25]]

^<<v40-20-25,25>>^ Mas Jesus os chamou e disse: “Vocês sabem que os governantes das nações dominam sobre elas e que os grandes homens exercem autoridade sobre elas.

[TIP]
====
- *dominam sobre elas*: Veja a nota de estudo em Mr 10:42.
====

[[v40-20-26]]

^<<v40-20-26,26>>^ Não deve ser assim entre vocês; mas quem quiser se tornar grande entre vocês tem de ser o seu servo,

[TIP]
====
- *servo*: Ou: “ministro”. A Bíblia muitas vezes usa a palavra grega diákonos para se referir a uma pessoa que presta serviço a outros de modo humilde e perseverante. A Bíblia usa essa palavra para descrever Jesus (Ro 15:8); os ministros, ou servos, de Cristo (1Co 3:5-7; Col 1:23); e os servos ministeriais (Fil 1:1; 1Ti 3:8). A palavra também é usada para se referir a servos domésticos (Jo 2:5, 9) e a autoridades do governo (Ro 13:4).
====

[[v40-20-27]]

^<<v40-20-27,27>>^ e quem quiser ser o primeiro entre vocês tem de ser o seu escravo,

[[v40-20-28]]

^<<v40-20-28,28>>^ assim como o Filho do Homem veio, não para ser servido, mas para servir e dar a sua vida como resgate em troca de muitos.”

[TIP]
====
- *não para ser servido, mas para servir*: Ou: “não para que ministrassem a ele, mas para ministrar”. — Veja a nota de estudo em Mt 20:26.
- *vida*: A palavra grega psykhé, que foi traduzida como “alma” em todas as ocorrências nas edições anteriores da Tradução do Novo Mundo, aqui se refere à vida. — Veja o Glossário, “Alma”.
- *resgate*: A palavra grega lýtron vem do verbo lýo, que significa “soltar; libertar”. Ela não aparece apenas no grego bíblico. Outros escritores usaram lýtron para se referir ao preço pago para libertar escravos ou prisioneiros de guerra. A palavra lýtron aparece duas vezes nas Escrituras Gregas Cristãs: aqui e em Mr 10:45. Uma palavra relacionada (antílytron) aparece em 1Ti 2:6 e é traduzida como “resgate correspondente”. Outras palavras relacionadas são lytróomai, que significa “libertar; resgatar” (Tit 2:14; 1Pe 1:18; veja também as notas de rodapé), e apolýtrosis, que muitas vezes é traduzida como “livramento por resgate” (Ef 1:7; Col 1:14; He 9:15; Ro 3:24; 8:23). — Veja o Glossário.
====

[[v40-20-29]]

^<<v40-20-29,29>>^ Ao saírem de Jericó, uma grande multidão o seguiu.

[TIP]
====
- *Jericó*: A primeira cidade cananeia ao oeste do rio Jordão a ser conquistada pelos israelitas. (Núm 22:1; Jos 6:1, 24, 25) Na época de Jesus, existia uma nova Jericó cerca de 2 quilômetros ao sul da Jericó antiga. Isso talvez explique por que Mateus diz que Jesus fez aquele milagre quando estava saindo de Jericó, mas o relato paralelo em Lu 18:35 diz que foi quando “estava chegando perto de Jericó”. É possível que Jesus estivesse saindo da Jericó judaica (a antiga) e indo para a romana (a nova), ou o contrário. — Veja a nota de estudo em Lu 18:35 e os Apêndices B4 e B10.
====

[[v40-20-30]]

^<<v40-20-30,30>>^ Então, dois cegos sentados à beira da estrada ouviram que Jesus estava passando por ali e gritaram: “Senhor, Filho de Davi, tenha misericórdia de nós!”

[TIP]
====
- *dois cegos*: Os relatos paralelos em Marcos e em Lucas falam de apenas um cego. Pelo visto, eles se concentram apenas em Bartimeu, que é mencionado por nome no Evangelho de Marcos. (Mr 10:46; Lu 18:35) O relato de Mateus é mais específico quanto ao número de cegos que estavam ali naquela ocasião.
- *Filho de Davi*: Ao chamar Jesus de “Filho de Davi”, os dois cegos declararam abertamente que acreditavam que Jesus era o Messias. — Veja as notas de estudo em Mt 1:1, 6; 15:25.
====

[[v40-20-31]]

^<<v40-20-31,31>>^ Mas a multidão os censurou, mandando que ficassem calados. Contudo, gritaram ainda mais alto, dizendo: “Senhor, Filho de Davi, tenha misericórdia de nós!”

[[v40-20-32]]

^<<v40-20-32,32>>^ Então Jesus parou, chamou-os e perguntou: “O que vocês querem que eu faça por vocês?”

[[v40-20-33]]

^<<v40-20-33,33>>^ Responderam-lhe: “Senhor, faça com que nossos olhos se abram.”

[[v40-20-34]]

^<<v40-20-34,34>>^ Jesus teve pena e tocou nos olhos deles, e eles recuperaram imediatamente a visão e o seguiram.

[TIP]
====
- *pena*: Ou: “compaixão”. — Veja a nota de estudo em Mt 9:36.
====

'''

xref:040-mateus/040-mateus-019.adoc#v40-19-0[&#60; Capítulo Anterior] | <<v40-20-0,Topo>> | xref:040-mateus/040-mateus-021.adoc#v40-21-0[Próximo Capítulo &#62;]