include::./index.adoc[]

[[v40-7-0]]
=== As Boas Novas Segundo Mateus, 7
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* D. Sermão do Monte (5:1–7:29)
* Jesus começa o Sermão do Monte (5:1, 2)
* Nove felicidades (5:3-12)
* “Sal da terra” e “luz do mundo” (5:13-16)
* Jesus vai cumprir a Lei (5:17-20)
* Conselhos sobre controlar a ira e sobre resolver problemas com outros (5:21-26)
* Conselhos sobre não cometer adultério e sobre divórcio (5:27-32)
* Conselhos sobre cumprir juramentos, não revidar, amar os inimigos (5:33-48)
* Não pratiquem a justiça só para chamar atenção (6:1-4)
* Modo certo de orar e oração-modelo (6:5-15)
* Não jejuem como os hipócritas (6:16-18)
* Tesouros na terra e no céu (6:19-24)
* Parem de se preocupar tanto; busquem primeiro o Reino (6:25-34)
* Parem de julgar (7:1-6)
* Persistam em pedir, buscar e bater (7:7-11)
* Regra de Ouro (7:12)
* Portão estreito (7:13, 14)
* Falsos profetas; árvores reconhecidas pelos seus frutos (7:15-23)
* Casa sobre rocha e casa sobre areia (7:24-27)
* Multidões ficam maravilhadas com ensino de Jesus (7:28, 29)
****

[[v40-7-1]]

^<<v40-7-1,1>>^ “Parem de julgar, para que não sejam julgados;

[TIP]
====
- *Parem de julgar*: Ou: “Parem de condenar”. Jesus sabia que humanos imperfeitos têm a tendência de julgar os outros, e muitos fariseus dos dias de Jesus davam um mau exemplo nesse sentido. Eles julgavam de forma dura os que não viviam de acordo com a Lei mosaica e os que não seguiam as tradições humanas que eles defendiam. Jesus disse que qualquer pessoa que tivesse o costume de julgar os outros devia parar de fazer isso. Em vez de ficar procurando defeitos nas pessoas, os discípulos de Jesus devem ‘continuar a perdoar’ as falhas delas. Ao fazer isso, eles motivam outros a ser perdoadores também. — Veja a nota de estudo em Lu 6:37.
====

[[v40-7-2]]

^<<v40-7-2,2>>^ pois, com o julgamento com que julgam, vocês serão julgados, e com a medida com que medem, medirão a vocês.

[[v40-7-3]]

^<<v40-7-3,3>>^ Então, por que você olha para o cisco no olho do seu irmão, mas não percebe que há uma trave no seu próprio olho?

[TIP]
====
- *cisco . . . trave*: Jesus usou esta hipérbole para expor a tolice de uma pessoa que critica seu irmão. Ele comparou uma pequena falha a um “cisco”. A palavra grega traduzida como “cisco” (kárfos) também pode se referir a uma palha ou a um pedaço bem pequeno de madeira. Por isso, algumas traduções em outros idiomas usam aqui “cavaco” ou “serragem”. A pessoa crítica dá a entender que a visão espiritual de seu irmão está comprometida a ponto de afetar seu conceito do que é certo e errado e sua capacidade de tomar decisões. Ela mostra orgulho quando se oferece para “tirar o cisco”, porque acha que pode ajudar seu irmão a ver as coisas de forma mais clara e a tomar boas decisões. Mas Jesus disse que ela mesma está com um problema em sua visão espiritual. Em seu olho, ela tem uma “trave”, uma longa viga que poderia ser usada para sustentar o telhado de uma casa. (Mt 7:4, 5) Neste contraste, que chega a ter um toque de humor, Jesus usou elementos que, segundo alguns, indicam que ele conhecia bem o trabalho de carpinteiro.
- *do seu irmão*: Aqui, a palavra grega adelfós (irmão) se refere a um irmão em sentido espiritual, um companheiro de adoração. Essa palavra também pode ser usada em um sentido mais amplo para se referir a uma pessoa em geral, ou seja, ao próximo. — Veja a nota de estudo em Mt 5:23.
====

[[v40-7-4]]

^<<v40-7-4,4>>^ Ou, como você pode dizer ao seu irmão: ‘Deixe-me tirar o cisco do seu olho’, quando há uma trave no seu próprio olho?

[[v40-7-5]]

^<<v40-7-5,5>>^ Hipócrita! Tire primeiro a trave do seu próprio olho e depois verá claramente como tirar o cisco do olho do seu irmão.

[TIP]
====
- *Hipócrita!*: Em Mt 6:2, 5, 16, Jesus usou essa palavra para se referir aos líderes religiosos judaicos. Mas, neste versículo, o “hipócrita” é o discípulo que fica apontando os erros dos outros em vez de enxergar seus próprios erros.
====

[[v40-7-6]]

^<<v40-7-6,6>>^ “Não deem aos cães o que é santo, nem lancem suas pérolas diante dos porcos, para que eles nunca as pisem com os pés e, voltando-se, dilacerem vocês.

[TIP]
====
- *Não deem aos cães o que é santo, nem lancem suas pérolas diante dos porcos*: De acordo com a Lei mosaica, os porcos e os cães eram impuros. (Le 11:7, 27) Os israelitas podiam jogar aos cães a carne de um animal morto por um animal selvagem. (Êx 22:31) Mas a tradição judaica dizia que era proibido dar aos cães “carne sagrada”, ou seja, a carne de animais sacrificados a Jeová. Em Mt 7:6, os “cães” e os “porcos” representam pessoas que não reconhecem o valor das verdades preciosas da Palavra de Deus. Assim como um porco não dá nenhum valor às pérolas, esse tipo de pessoa não dá valor às verdades da Palavra de Deus. Essas pessoas podem até tratar mal aqueles que querem compartilhar essa mensagem preciosa com elas.
====

[[v40-7-7]]

^<<v40-7-7,7>>^ “Persistam em pedir, e lhes será dado; persistam em buscar, e acharão; persistam em bater, e lhes será aberto;

[TIP]
====
- *Persistam em pedir, . . . buscar, . . . bater*: A expressão “persistam em” é usada aqui porque o tempo verbal grego indica uma ação contínua. Essa expressão mostra que a pessoa nunca deve desistir de orar. O uso de “pedir”, “buscar” e “bater” em sequência intensifica a ação que ela deve tomar. Jesus disse algo parecido na ilustração em Lu 11:5-8.
====

[[v40-7-8]]

^<<v40-7-8,8>>^ pois todo aquele que pede, recebe; e todo aquele que busca, acha; e a todo aquele que bate, se abrirá.

[[v40-7-9]]

^<<v40-7-9,9>>^ Realmente, quem de vocês, se o seu filho lhe pedir pão, lhe entregará uma pedra?

[TIP]
====
- *pão . . . pedra*: Jesus deve ter usado o pão em sua ilustração porque era um alimento básico dos judeus e dos povos vizinhos. É possível que Jesus tenha comparado pães com pedras porque o tamanho e o formato de um pão podiam lembrar os de uma pedra. A resposta óbvia para a pergunta retórica de Jesus era: “Seria um absurdo um pai fazer uma coisa dessas!” — Veja a nota de estudo em Mt 7:10.
====

[[v40-7-10]]

^<<v40-7-10,10>>^ Ou, se lhe pedir um peixe, lhe entregará uma serpente?

[TIP]
====
- *peixe . . . serpente*: O peixe era um alimento básico das pessoas que moravam perto do mar da Galileia. Algumas serpentes pequenas talvez se parecessem com os peixes que geralmente eram comidos com pão. Com essa pergunta retórica, Jesus estava dizendo que um pai que ama o filho jamais faria uma coisa dessas.
====

[[v40-7-11]]

^<<v40-7-11,11>>^ Portanto, se vocês, embora maus, sabem dar boas coisas aos seus filhos, quanto mais o seu Pai, que está nos céus, dará boas coisas aos que lhe pedirem!

[TIP]
====
- *vocês, embora maus*: Como todos os humanos herdaram o pecado, todos são imperfeitos e, de certa forma, são maus.
- *quanto mais*: Jesus usava muito esse tipo de raciocínio. Primeiro, ele falava de um fato bem óbvio ou de algo que todos conheciam bem. Depois, ele usava esse fato para ajudar seus ouvintes a entender uma verdade maior e mais importante. — Mt 10:25; 12:12; Lu 11:13; 12:28.
====

[[v40-7-12]]

^<<v40-7-12,12>>^ “Portanto, todas as coisas que querem que os homens façam a vocês, façam também a eles. De fato, isso é o que a Lei e os Profetas querem dizer.

[TIP]
====
- *a Lei e os Profetas*: Veja a nota de estudo em Mt 5:17.
====

[[v40-7-13]]

^<<v40-7-13,13>>^ “Entrem pelo portão estreito, porque largo é o portão e espaçosa é a estrada que conduz à destruição, e muitos entram por ele;

[TIP]
====
- *Entrem pelo portão estreito*: Antigamente, as pessoas chegavam às cidades muradas por estradas que davam nos portões da cidade. A Bíblia usa expressões como estrada ou “caminho” para descrever o tipo de vida que a pessoa leva. Quando Jesus falou que existem duas estradas diferentes, ele indicou que existem dois estilos de vida: um que agrada a Deus e outro que não agrada. Uma pessoa só vai poder entrar no Reino de Deus se andar pela estrada certa. — Sal 1:1, 6; Je 21:8; Mt 7:21.
- *largo é o portão e espaçosa é a estrada*: Alguns manuscritos dizem apenas “larga e espaçosa é a estrada”. Mas a frase mais longa, que inclui “é o portão”, aparece em um número maior de manuscritos mais antigos. Além disso, as expressões “largo é o portão” e “espaçosa é a estrada” fazem um paralelo com as expressões “estreito é o portão” e “apertada é a estrada”, usadas no versículo seguinte (Mt 7:14). — Veja o Apêndice A3.
====

[[v40-7-14]]

^<<v40-7-14,14>>^ ao passo que estreito é o portão e apertada a estrada que conduz à vida, e poucos a acham.

[[v40-7-15]]

^<<v40-7-15,15>>^ “Tomem cuidado com os falsos profetas, que se chegam a vocês em pele de ovelha, mas que por dentro são lobos vorazes.

[TIP]
====
- *em pele de ovelha*: Ou: “vestidos de ovelha”. Essas pessoas tentam parecer mansas e inocentes para fazer todos pensarem que são ovelhas inofensivas do “rebanho” de Deus.
- *lobos vorazes*: Jesus citou lobos ferozes e famintos como uma metáfora para se referir aos falsos profetas, que são extremamente gananciosos e tentam tirar vantagem das pessoas.
====

[[v40-7-16]]

^<<v40-7-16,16>>^ Pelos seus frutos vocês os reconhecerão. Será que se colhem uvas dos espinheiros ou figos dos abrolhos?

[TIP]
====
- *frutos*: Neste contexto, essa palavra representa o que as pessoas fazem ou dizem. Também pode se referir aos resultados do que elas fazem ou dizem.
====

[[v40-7-17]]

^<<v40-7-17,17>>^ Do mesmo modo, toda árvore boa produz fruto bom, mas toda árvore ruim^&#42;1^ produz fruto imprestável.

[NOTE]
====
. Ou: “podre”.
====

[[v40-7-18]]

^<<v40-7-18,18>>^ A árvore boa não pode dar fruto imprestável, nem pode a árvore ruim produzir fruto bom.

[[v40-7-19]]

^<<v40-7-19,19>>^ Toda árvore que não produz fruto bom é cortada e lançada no fogo.

[[v40-7-20]]

^<<v40-7-20,20>>^ Realmente, então, pelos seus frutos vocês reconhecerão esses homens.

[[v40-7-21]]

^<<v40-7-21,21>>^ “Nem todo o que me disser: ‘Senhor, Senhor’, entrará no Reino dos céus, mas apenas aquele que fizer a vontade do meu Pai, que está nos céus.

[[v40-7-22]]

^<<v40-7-22,22>>^ Muitos me dirão naquele dia: ‘Senhor, Senhor, não profetizamos em seu nome, não expulsamos demônios em seu nome e não fizemos muitas obras poderosas^&#42;1^ em seu nome?’

[NOTE]
====
. Ou: “muitos milagres”.
====

[[v40-7-23]]

^<<v40-7-23,23>>^ Mas eu lhes declararei, então: ‘Nunca os conheci!^&#42;1^ Afastem-se de mim, vocês que fazem o que é contra a lei!’

[NOTE]
====
. Ou: “reconheci”.
====

[TIP]
====
- *o que é contra a lei*: Veja a nota de estudo em Mt 24:12.
====

[[v40-7-24]]

^<<v40-7-24,24>>^ “Portanto, todo aquele que ouve essas minhas palavras e as pratica será como um homem prudente, que construiu sua casa sobre a rocha.

[TIP]
====
- *prudente*: Veja a nota de estudo em Mt 24:45.
====

[[v40-7-25]]

^<<v40-7-25,25>>^ E caiu a chuva, vieram as inundações, e os ventos sopraram com força contra aquela casa, mas ela não desmoronou, pois tinha sido fundada sobre a rocha.

[TIP]
====
- *chuva . . . inundações . . . ventos*: Tempestades repentinas são comuns em Israel durante o inverno (principalmente no mês de tebete, que corresponde a dezembro/janeiro). Essas tempestades trazem ventanias, chuvas torrenciais e enxurradas. — Veja o Apêndice B15.
====

[[v40-7-26]]

^<<v40-7-26,26>>^ Além disso, todo aquele que ouve essas minhas palavras e não as pratica será como um homem tolo, que construiu sua casa sobre a areia.

[[v40-7-27]]

^<<v40-7-27,27>>^ E caiu a chuva, vieram as inundações, e os ventos sopraram e bateram contra aquela casa, e ela desmoronou, e foi grande a sua queda.”

[[v40-7-28]]

^<<v40-7-28,28>>^ Quando Jesus terminou de falar essas palavras, o efeito foi que as multidões ficaram maravilhadas com seu modo de ensinar,

[TIP]
====
- *ficaram maravilhadas*: O verbo grego usado aqui pode significar “estar tão impressionado a ponto de ficar fora de si”. No grego, o tempo verbal indica algo contínuo, dando a entender que as palavras de Jesus foram inesquecíveis para seus ouvintes.
- *seu modo de ensinar*: Essa expressão, que também pode ser traduzida como “seus ensinos”, se refere não apenas ao modo como Jesus ensinou, mas também às coisas que ele ensinou no Sermão do Monte.
====

[[v40-7-29]]

^<<v40-7-29,29>>^ pois ele as ensinava como quem tinha autoridade, e não como seus escribas.

[TIP]
====
- *não como seus escribas*: Os escribas tinham o costume de citar rabinos respeitados para apoiar seus ensinos. Mas Jesus citava a Palavra de Deus quando ensinava. Ele falava como um representante de Jeová e, por isso, ensinava como quem tinha autoridade. — Jo 7:16.
====

'''

xref:040-mateus/040-mateus-006.adoc#v40-6-0[&#60; Capítulo Anterior] | <<v40-7-0,Topo>> | xref:040-mateus/040-mateus-008.adoc#v40-8-0[Próximo Capítulo &#62;]