include::./index.adoc[]

[[v40-13-0]]
=== As Boas Novas Segundo Mateus, 13
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. Jesus usa ilustrações para ensinar sobre o Reino (13:1-58)
* Jesus entra num barco para ensinar as multidões (13:1, 2)
* Sementes caem em quatro tipos de solo (13:3-9)
* Por que Jesus usa ilustrações (13:10-17)
* Jesus explica ilustração do semeador (13:18-23)
* O trigo e o joio (13:24-30)
* O grão de mostarda e o fermento (13:31-33)
* Jesus contar ilustrações cumpre profecia (13:34, 35)
* Jesus explica a ilustração do trigo e do joio (13:36-43)
* O tesouro escondido e a pérola de grande valor (13:44-46)
* A rede de arrasto (13:47-50)
* Instrutor público tira do seu tesouro coisas novas e velhas (13:51, 52)
* Jesus é rejeitado em sua própria cidade (13:53-58)
****

[[v40-13-1]]

^<<v40-13-1,1>>^ Naquele dia, Jesus saiu da casa e se sentou à beira do mar.

[[v40-13-2]]

^<<v40-13-2,2>>^ E as multidões que se reuniram em volta dele eram tão grandes que ele entrou num barco e se sentou, e toda a multidão ficou na praia.

[TIP]
====
- *se sentou*: Esse era o costume dos instrutores judaicos. — Mt 5:1, 2.
- *na praia*: Existe um lugar na margem do mar da Galileia, perto de Cafarnaum, que forma um anfiteatro natural, pois a praia tem o formato de uma ferradura e o terreno em volta tem uma leve inclinação. Esse formato contribui para que o local tenha boa acústica. Isso permitiria que a multidão ouvisse o que Jesus falava lá do barco.
====

[[v40-13-3]]

^<<v40-13-3,3>>^ Falou-lhes então muitas coisas por meio de ilustrações. Ele disse: “Escutem: Um semeador saiu para semear.

[TIP]
====
- *ilustrações*: Ou: “parábolas”. A palavra grega parabolé significa literalmente “colocar ao lado (junto)”, e pode se referir a uma parábola, um provérbio ou uma comparação. Jesus muitas vezes explicava uma coisa por ‘colocá-la ao lado’ de algo, ou seja, por compará-la com outra coisa parecida. (Mr 4:30) As ilustrações de Jesus eram curtas, e muitas vezes eram histórias fictícias que ensinavam uma lição de moral ou uma verdade espiritual.
- *Escutem*: Ou: “Vejam”. Veja a nota de estudo em Mt 1:23.
====

[[v40-13-4]]

^<<v40-13-4,4>>^ Ao passo que semeava, algumas sementes caíram à beira da estrada, e vieram as aves e as comeram.

[[v40-13-5]]

^<<v40-13-5,5>>^ Outras caíram em solo rochoso, onde não havia muita terra, e brotaram imediatamente porque o solo não era profundo.

[TIP]
====
- *solo rochoso*: Jesus não estava falando aqui de um terreno com muitas pedras espalhadas. Ele se referia a uma camada de rocha com pouca terra por cima para a semente brotar. O relato paralelo em Lu 8:6 menciona que as sementes “caíram sobre a rocha”. Em terrenos assim, as raízes das sementes não conseguem ir muito fundo no solo. Por isso, não conseguem a umidade que precisam.
====

[[v40-13-6]]

^<<v40-13-6,6>>^ Mas, quando o sol se levantou, ficaram queimadas e murcharam, porque não tinham raiz.

[[v40-13-7]]

^<<v40-13-7,7>>^ Outras caíram entre os espinhos, e os espinhos cresceram e as sufocaram.

[TIP]
====
- *entre os espinhos*: Pelo visto, Jesus não estava falando aqui de espinheiros crescidos, mas de plantas daninhas com espinhos que não foram removidas depois de se arar o solo. Quando as plantas daninhas crescessem, sufocariam as sementes que foram plantadas.
====

[[v40-13-8]]

^<<v40-13-8,8>>^ Ainda outras caíram em solo bom e começaram a dar fruto, esta 100 vezes mais, aquela 60 vezes mais, outra 30 vezes mais.

[[v40-13-9]]

^<<v40-13-9,9>>^ Quem tem ouvidos, escute.”

[[v40-13-10]]

^<<v40-13-10,10>>^ Assim, os seus discípulos vieram e lhe perguntaram: “Por que o senhor lhes fala usando ilustrações?”

[[v40-13-11]]

^<<v40-13-11,11>>^ Em resposta, ele disse: “A vocês é concedido^&#42;1^ entender os segredos sagrados do Reino dos céus, mas a eles não é concedido.

[NOTE]
====
. Ou: “Vocês receberam permissão para”.
====

[TIP]
====
- *segredos sagrados*: A palavra grega mystérion, que aparece aqui no plural, foi traduzida 25 vezes na Tradução do Novo Mundo como “segredo(s) sagrado(s)”. Essa expressão se refere a detalhes do propósito de Deus que são mantidos em segredo até que ele decida torná-los conhecidos. Daí, esses detalhes são completamente revelados, mas apenas para quem Deus escolhe dar entendimento. (Col 1:25, 26) Depois disso, eles são proclamados para o maior número de pessoas possível. Isso fica claro pelo uso que a Bíblia faz de expressões como “declarar”, “fazer saber”, “pregar”, “revelação” e “revelado” junto com a expressão “segredo sagrado”. (1Co 2:1; Ef 1:9; 3:3; Col 1:25, 26; 4:3) O principal “segredo sagrado de Deus” tem a ver com a identificação de Jesus como o “descendente” prometido, ou Messias. (Col 2:2; Gên 3:15) Mas dentro desse segredo sagrado também há muitos detalhes, incluindo o papel de Jesus no propósito de Deus. (Col 4:3) Neste versículo, Jesus mostrou que “os segredos sagrados” também estão ligados ao Reino dos céus, ou “Reino de Deus”, o governo celestial que tem Jesus como Rei. (Mr 4:11; Lu 8:10; veja a nota de estudo em Mt 3:2.) As Escrituras Gregas Cristãs usam a palavra mystérion de maneira diferente das antigas religiões místicas. Essas religiões com frequência se baseavam em cultos de fertilidade, que se tornaram comuns durante o século 1 d.C. Elas diziam que, por meio de rituais místicos, seus fiéis receberiam imortalidade e revelações divinas e se aproximariam dos deuses. Os “segredos” que as pessoas aprendiam nessas religiões obviamente não se baseavam na verdade. Ao se tornar um membro de uma religião mística, a pessoa se comprometia a não revelar os segredos que aprendesse, ajudando a manter o mistério sobre suas práticas. Isso era bem diferente do que acontecia com os segredos sagrados que os cristãos aprendiam e que eram declarados abertamente. Na Tradução do Novo Mundo, quando o contexto se relaciona com a religião falsa, a palavra mystérion é traduzida como “mistério”. — Para ver os três lugares em que a palavra mystérion foi traduzida como “mistério”, veja as notas de estudo em 2Te 2:7; Ap 17:5, 7. 
====

[[v40-13-12]]

^<<v40-13-12,12>>^ Pois àquele que tem, mais será dado, e se fará que ele tenha em abundância; mas, daquele que não tem, até mesmo o que tem será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ É por isso que falo a eles usando ilustrações; porque olham, mas olham em vão, e ouvem, mas ouvem em vão, e não compreendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ E está se cumprindo no caso deles a profecia de Isaías, que diz: ‘Vocês realmente ouvirão, mas de modo algum compreenderão; e realmente olharão, mas de modo algum verão.

[[v40-13-15]]

^<<v40-13-15,15>>^ Pois o coração deste povo ficou insensível,^&#42;1^ eles taparam os ouvidos^&#42;2^ e fecharam os olhos, para que nunca vissem com os olhos, nem ouvissem com os ouvidos, nem compreendessem com o coração e dessem meia-volta, e eu os curasse.’

[NOTE]
====
. Lit.: “foi tornado grosso (gordo)”.
. Ou: “seus ouvidos ouviram sem reação (de má vontade)”.
====

[[v40-13-16]]

^<<v40-13-16,16>>^ “No entanto, felizes são os olhos de vocês porque veem e os seus ouvidos porque ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Pois, digo-lhes a verdade: Muitos profetas e homens justos desejaram ver as coisas que vocês estão observando, mas não as viram, e ouvir as coisas que vocês estão ouvindo, mas não as ouviram.

[TIP]
====
- *digo-lhes a verdade*: Veja a nota de estudo em Mt 5:18.
====

[[v40-13-18]]

^<<v40-13-18,18>>^ “Escutem agora a ilustração do homem que semeou.

[[v40-13-19]]

^<<v40-13-19,19>>^ Quando alguém ouve a palavra do Reino, mas não a entende, vem o Maligno e arranca o que foi semeado no seu coração; essa é a que foi semeada à beira da estrada.

[[v40-13-20]]

^<<v40-13-20,20>>^ A que foi semeada em solo rochoso representa aquele que ouve a palavra e imediatamente a aceita com alegria.

[[v40-13-21]]

^<<v40-13-21,21>>^ Contudo, ele não tem raiz em si mesmo, mas continua por algum tempo e, quando surge dificuldade ou perseguição por causa da palavra, imediatamente tropeça.

[[v40-13-22]]

^<<v40-13-22,22>>^ A que foi semeada entre os espinhos representa aquele que ouve a palavra, mas as ansiedades deste mundo e o poder enganoso das riquezas^&#42;1^ sufocam a palavra, e ela^&#42;2^ se torna infrutífera.

[NOTE]
====
. Ou: “a tentação (o prazer enganoso) de ser rico”.
. Ou, possivelmente: “ele”, ou seja, “aquele que ouve a palavra”.
====

[TIP]
====
- *mundo*: Ou: “sistema de coisas”. A palavra grega usada aqui, aión, tem o sentido básico de “época”. Ela pode se referir também a uma situação existente ou a características marcantes de certo período ou época. Aqui, Jesus mostrou que a vida neste mundo governado pelo Diabo seria cheia de ansiedades e problemas. — Veja o Glossário, “Sistema(s) de coisas”.
====

[[v40-13-23]]

^<<v40-13-23,23>>^ A que foi semeada em solo bom representa aquele que ouve a palavra e compreende o sentido dela, que realmente dá fruto e produz, este 100 vezes mais, aquele 60 vezes mais, outro 30 vezes mais.”

[[v40-13-24]]

^<<v40-13-24,24>>^ Apresentou-lhes outra ilustração, dizendo: “O Reino dos céus pode ser comparado a um homem que semeou boa semente no seu campo.

[[v40-13-25]]

^<<v40-13-25,25>>^ Enquanto os homens dormiam, seu inimigo veio, semeou joio no meio do trigo e foi embora.

[TIP]
====
- *semeou*: Há registros de que, no Antigo Oriente Próximo, às vezes uma pessoa mal-intencionada semeava plantas daninhas por cima da plantação de outro.
- *joio*: Acredita-se que a palavra grega usada aqui se refira ao joio (Lolium temulentum), uma planta venenosa da família das gramíneas. O joio é muito parecido com o trigo enquanto o trigo ainda está na fase de crescimento, antes de amadurecer.
====

[[v40-13-26]]

^<<v40-13-26,26>>^ Quando a haste cresceu e produziu fruto, apareceu também o joio.

[[v40-13-27]]

^<<v40-13-27,27>>^ Então, os escravos do dono da casa vieram e lhe perguntaram: ‘O senhor não semeou boa semente no seu campo? De onde veio então o joio?’

[[v40-13-28]]

^<<v40-13-28,28>>^ Ele lhes respondeu: ‘Um inimigo, um homem, fez isso.’ Os escravos lhe disseram: ‘O senhor quer então que vamos ajuntar o joio?’

[TIP]
====
- *Os escravos lhe disseram*: Alguns poucos manuscritos dizem apenas “eles lhe disseram”, mas a maior parte dos manuscritos mais antigos dizem “os escravos lhe disseram”.
====

[[v40-13-29]]

^<<v40-13-29,29>>^ Ele disse: ‘Não, pois, ao ajuntarem o joio, poderiam arrancar também o trigo.

[TIP]
====
- *arrancar também o trigo*: Mesmo que os escravos conseguissem identificar o joio, não seria bom arrancá-lo nessa fase. Se fizessem isso, poderiam arrancar o trigo junto, porque as suas raízes estavam entrelaçadas com as do joio.
====

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixem ambos crescer juntos até a colheita, e na época da colheita eu direi aos ceifeiros: Ajuntem primeiro o joio e amarrem-no em feixes para ser queimado; depois ajuntem o trigo no meu celeiro.’”

[TIP]
====
- *ajuntem . . . o joio*: Quando o joio fica maduro, é fácil ver a diferença entre ele e o trigo. — Veja a nota de estudo em Mt 13:25.
====

[[v40-13-31]]

^<<v40-13-31,31>>^ Apresentou-lhes outra ilustração, dizendo: “O Reino dos céus é semelhante a um grão de mostarda, que um homem pegou e plantou no seu campo.

[TIP]
====
- *grão de mostarda*: Embora existam várias espécies silvestres de pé de mostarda em Israel, a mostarda-preta (Brassica nigra) é a variedade geralmente cultivada na região. A semente da mostarda-preta é redonda, mede entre 1 e 1,6 milímetro e pesa 1 miligrama. Apesar de ser bem pequena, a semente de mostarda pode se tornar uma planta do tamanho de uma árvore. Algumas variedades de pé de mostarda podem chegar a 4,5 metros de altura.
====

[[v40-13-32]]

^<<v40-13-32,32>>^ De fato, essa é a menor de todas as sementes, mas, depois de crescida, é a maior das hortaliças e se torna uma árvore, de modo que as aves do céu vêm e acham abrigo entre os seus ramos.”

[TIP]
====
- *a menor de todas as sementes*: Existem outras sementes menores do que a de mostarda, mas parece que a semente de mostarda era a menor semente que os lavradores galileus plantavam e colhiam. Em alguns textos judaicos antigos, a semente de mostarda era usada como figura de linguagem para se referir a algo extremamente pequeno.
====

[[v40-13-33]]

^<<v40-13-33,33>>^ Contou-lhes outra ilustração: “O Reino dos céus é semelhante ao fermento que uma mulher pegou e misturou com três grandes medidas de farinha, até que a massa inteira ficou fermentada.”

[TIP]
====
- *fermento*: Jesus estava se referindo aqui ao processo normal de fazer pão. Era comum pegar um pequeno pedaço de massa já fermentada e guardá-lo para servir de fermento. Quando a pessoa ia fazer mais pães, ela misturava esse fermento com a nova massa para fazê-la crescer. Embora a Bíblia muitas vezes use o fermento para representar o pecado e a maldade (veja a nota de estudo em Mt 16:6), ela nem sempre menciona o fermento em sentido negativo (Le 7:11-15). Tudo indica que, aqui, o processo de fermentação representa o crescimento de algo bom.
- *grandes medidas*: A palavra grega usada aqui, sáton, corresponde à palavra hebraica para seá. Um seá equivalia a 7,33 litros. — Veja a nota de rodapé em Gên 18:6; o Glossário, “Seá”, e o Apêndice B14-A.
====

[[v40-13-34]]

^<<v40-13-34,34>>^ Jesus falou tudo isso às multidões por meio de ilustrações. Realmente, nada lhes falava sem ilustração,

[[v40-13-35]]

^<<v40-13-35,35>>^ para que se cumprissem as palavras do profeta, que disse: “Abrirei a minha boca com ilustrações; proclamarei as coisas escondidas desde a fundação.”

[TIP]
====
- *para que se cumprissem as palavras do profeta*: “As palavras do profeta” citadas por Mateus foram tiradas do Sal 78:2. Nesse salmo, o “profeta” (o escritor do Sal 78) usou linguagem figurada para descrever as coisas que Deus fez para ajudar e disciplinar a nação de Israel. Da mesma forma, Jesus usou muitas figuras de linguagem nas ilustrações que contou a seus discípulos e às multidões que o seguiam. — Veja a nota de estudo em Mt 1:22.
- *desde a fundação*: Ou, possivelmente: “desde a fundação do mundo”. (Veja a nota de estudo em Mt 25:34.) Alguns manuscritos bem antigos contêm a palavra grega que significa “mundo”. Mas há também outros manuscritos bem antigos em que essa palavra não aparece neste versículo.
====

[[v40-13-36]]

^<<v40-13-36,36>>^ Então, depois de dispensar as multidões, ele entrou na casa. Seus discípulos se chegaram a ele e disseram: “Explique-nos a ilustração do joio no campo.”

[[v40-13-37]]

^<<v40-13-37,37>>^ Em resposta, ele disse: “O semeador da boa semente é o Filho do Homem;

[TIP]
====
- *Filho do Homem*: Veja a nota de estudo em Mt 8:20.
====

[[v40-13-38]]

^<<v40-13-38,38>>^ o campo é o mundo. Quanto à boa semente, são os filhos do Reino, mas o joio são os filhos do Maligno,

[TIP]
====
- *mundo*: Aqui se refere à humanidade como um todo.
====

[[v40-13-39]]

^<<v40-13-39,39>>^ e o inimigo que o semeou é o Diabo. A colheita é o final de um sistema de coisas, e os ceifeiros são os anjos.

[TIP]
====
- *o final*: A palavra grega syntéleia, traduzida aqui como “final”, também aparece em Mt 13:40, 49; 24:3; 28:20 e He 9:26. — Veja a nota de estudo em Mt 24:3 e o Glossário, “Final do sistema de coisas”.
- *um sistema de coisas*: Ou: “uma época”. — Veja as notas de estudo em Mt 13:22; 24:3 e o Glossário, “Final do sistema de coisas”; “Sistema(s) de coisas”.
====

[[v40-13-40]]

^<<v40-13-40,40>>^ Portanto, assim como o joio é ajuntado e queimado no fogo, assim será no final do sistema de coisas.

[[v40-13-41]]

^<<v40-13-41,41>>^ O Filho do Homem enviará seus anjos, e eles ajuntarão dentre o seu Reino todas as coisas que causam tropeço e os que praticam o que é contra a lei,

[TIP]
====
- *o que é contra a lei*: Veja a nota de estudo em Mt 24:12.
====

[[v40-13-42]]

^<<v40-13-42,42>>^ e os lançarão na fornalha ardente. Ali é que haverá o seu choro e o ranger dos seus dentes.

[TIP]
====
- *ranger dos seus dentes*: Veja a nota de estudo em Mt 8:12.
====

[[v40-13-43]]

^<<v40-13-43,43>>^ Naquele tempo, os justos brilharão tão claramente como o sol, no Reino do seu Pai. Quem tem ouvidos, escute.

[[v40-13-44]]

^<<v40-13-44,44>>^ “O Reino dos céus é semelhante a um tesouro escondido no campo, que um homem achou e escondeu novamente; e, na sua alegria, ele foi, vendeu todas as coisas que tinha e comprou aquele campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ “Também, o Reino dos céus é semelhante a um comerciante viajante que buscava pérolas de boa qualidade.

[[v40-13-46]]

^<<v40-13-46,46>>^ Ao achar uma pérola de grande valor, foi, vendeu prontamente todas as coisas que tinha e a comprou.

[TIP]
====
- *pérola*: Nos tempos bíblicos, era possível encontrar pérolas de boa qualidade no Mar Vermelho, no golfo Pérsico e no oceano Índico — lugares distantes de Israel. Isso explica por que Jesus usou em sua ilustração um comerciante viajante que fez sacrifícios muito grandes para conseguir uma pérola dessas.
====

[[v40-13-47]]

^<<v40-13-47,47>>^ “Também, o Reino dos céus é semelhante a uma rede de arrasto baixada ao mar e que apanhou peixes de todo tipo.

[[v40-13-48]]

^<<v40-13-48,48>>^ Quando ela ficou cheia, arrastaram-na para a praia, sentaram-se e juntaram os peixes bons em recipientes, mas jogaram fora os imprestáveis.

[TIP]
====
- *imprestáveis*: Jesus talvez se referisse aqui a peixes sem escamas e barbatanas. De acordo com a Lei mosaica, esses peixes eram impuros e os israelitas não podiam comê-los. (Le 11:9-12; De 14:9, 10) Ou talvez Jesus estivesse falando de peixes que, por outros motivos, não podiam ser usados como alimento.
====

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim será no final do sistema de coisas. Os anjos sairão e separarão os maus dos justos,

[TIP]
====
- *final do sistema de coisas*: Veja as notas de estudo em Mt 13:39; 24:3 e o Glossário, “Final do sistema de coisas”; “Sistema(s) de coisas”.
====

[[v40-13-50]]

^<<v40-13-50,50>>^ e os lançarão na fornalha ardente. Ali é que haverá o seu choro e o ranger dos seus dentes.

[[v40-13-51]]

^<<v40-13-51,51>>^ “Compreenderam o sentido de tudo isso?” Eles responderam: “Sim.”

[[v40-13-52]]

^<<v40-13-52,52>>^ Então ele lhes disse: “Sendo assim, todo instrutor público que é ensinado a respeito do Reino dos céus é semelhante a um homem, dono de uma casa, que tira do seu tesouro coisas novas e coisas velhas.”

[TIP]
====
- *instrutor público*: Ou: “pessoa instruída”. Em grego, grammateús. Quando essa palavra se refere a um dos instrutores judaicos que eram peritos na Lei, ela é traduzida como “escriba”. Mas neste versículo ela se refere aos discípulos de Jesus que foram treinados para ensinar outros.
====

[[v40-13-53]]

^<<v40-13-53,53>>^ Quando Jesus terminou de contar essas ilustrações, partiu dali.

[[v40-13-54]]

^<<v40-13-54,54>>^ Chegando à sua própria cidade, começou a ensinar ao povo na sinagoga deles, de modo que ficaram maravilhados e disseram: “Onde este homem obteve essa sabedoria e essa habilidade de realizar obras poderosas?

[TIP]
====
- *sua própria cidade*: Lit.: “lugar do seu pai”. Refere-se a Nazaré, cidade da família imediata de Jesus.
====

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é este o filho do carpinteiro? Sua mãe não se chama Maria e seus irmãos Tiago, José, Simão e Judas?

[TIP]
====
- *filho do carpinteiro*: A palavra grega tékton, traduzida como “carpinteiro”, é bem abrangente e pode se referir a qualquer artesão ou construtor. Quando essa palavra é usada para se referir a alguém que trabalha com madeira, ela pode descrever alguém que constrói casas, fabrica móveis ou faz outros itens de madeira. Justino, o Mártir, que viveu no século 2 d.C., escreveu que Jesus, “enquanto estava entre os homens, trabalhava como carpinteiro, fabricando arados e jugos”. As primeiras traduções da Bíblia em idiomas antigos também passam a ideia de alguém que trabalha com madeira. Jesus era conhecido como “o filho do carpinteiro” e como “o carpinteiro”. (Mr 6:3) Pelo visto, Jesus aprendeu a carpintaria com seu pai adotivo, José. Naquela época, os filhos começavam a aprender a profissão do pai quando tinham entre 12 e 15 anos, e esse treinamento levava muitos anos.
- *irmãos*: Embora a palavra grega usada aqui, adelfós, também seja usada na Bíblia para se referir a irmãos em sentido espiritual, neste contexto ela é usada para se referir aos meios-irmãos de Jesus: os filhos que José e Maria tiveram depois de Jesus. Alguns acreditam que Maria continuou virgem depois de Jesus nascer e afirmam que neste versículo a palavra adelfós se refere a primos. Mas as Escrituras Gregas Cristãs usam outras palavras, não adelfós, para se referir a primos e parentes. Por exemplo, Col 4:10 usa a palavra anepsiós para se referir a um “primo”. E Lu 21:16 usa a palavra syggenés para se referir a parentes (o que pode incluir primos) na mesma lista em que aparece a palavra adelfós (irmão). Esses exemplos mostram que as Escrituras Gregas Cristãs usam palavras específicas para se referir a graus diferentes de parentesco.
- *Tiago*: Tudo indica que esse meio-irmão de Jesus seja o Tiago mencionado em At 12:17 (veja a nota de estudo) e em Gál 1:19, e o escritor do livro bíblico de Tiago. — Tg 1:1.
- *Judas*: Tudo indica que esse meio-irmão de Jesus seja o escritor do livro bíblico de Judas. — Ju 1.
====

[[v40-13-56]]

^<<v40-13-56,56>>^ E não estão todas as suas irmãs conosco? Então, onde ele obteve tudo isso?”

[[v40-13-57]]

^<<v40-13-57,57>>^ Assim, começaram a tropeçar por causa dele. Mas Jesus lhes disse: “Um profeta não fica sem honra a não ser na sua própria terra e na sua própria casa.”

[TIP]
====
- *começaram a tropeçar por causa dele*: Ou: “ficaram ofendidos com ele”. Neste contexto, a palavra grega skandalízo se refere a tropeçar em sentido figurado, e significa “ficar ofendido”. Ela também poderia ser traduzida aqui como “se recusaram a acreditar nele”. Em outros contextos, skandalízo inclui a ideia de pecar ou levar alguém a pecar. — Veja a nota de estudo em Mt 5:29.
====

[[v40-13-58]]

^<<v40-13-58,58>>^ E não fez ali muitas obras poderosas, por causa da falta de fé deles.

[TIP]
====
- *não fez ali muitas obras poderosas*: Jesus não fez muitos milagres em Nazaré por causa das circunstâncias que existiam ali, não por falta de poder. O povo de Nazaré não tinha fé. (Veja a nota de estudo em Mr 6:5.) Ele não devia desperdiçar o poder divino com pessoas que não queriam acreditar nele nem aceitar sua mensagem. — Veja também Mt 10:14; Lu 16:29-31.
====

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]