include::./index.adoc[]

[[v41-10-0]]
=== As Boas Novas Segundo Marcos, 10
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* F. Ministério de Jesus na Pereia e na região de Jericó (10:1-52)
* Jesus ensina sobre casamento e divórcio (10:1-12)
* Jesus abençoa criancinhas (10:13-16)
* Pergunta de um homem rico (10:17-27)
* Quem fizer sacrifícios pelo Reino será recompensado (10:28-31)
* Jesus prediz pela terceira vez sua morte e ressurreição (10:32-34)
* Tiago e João pedem posições de destaque no Reino (10:35-45)
* Jesus cura o cego Bartimeu perto de Jericó (10:46-52)
****

[[v41-10-1]]

^<<v41-10-1,1>>^ Dali ele se levantou e foi para as fronteiras^&#42;1^ da Judeia, do outro lado do Jordão, e novamente multidões se ajuntaram em volta dele. Ele começou a ensiná-las de novo, como costumava fazer.

[NOTE]
====
. Ou: “os limites”.
====

[TIP]
====
- *as fronteiras da Judeia, do outro lado do Jordão*: Pelo visto se refere à Pereia, uma região que ficava ao leste do rio Jordão, especialmente à parte da Pereia que fazia fronteira com a Judeia. — Veja a nota de estudo em Mt 19:1 e o Mapa 5 no Apêndice A7-F.
====

[[v41-10-2]]

^<<v41-10-2,2>>^ Alguns fariseus se aproximaram e, querendo pô-lo à prova, perguntaram se era permitido que um homem se divorciasse da esposa.

[[v41-10-3]]

^<<v41-10-3,3>>^ Ele lhes respondeu: “O que Moisés lhes ordenou?”

[[v41-10-4]]

^<<v41-10-4,4>>^ Disseram: “Moisés permitiu que o homem escrevesse um certificado de divórcio e a mandasse embora.”

[TIP]
====
- *certificado de divórcio*: Veja a nota de estudo em Mt 19:7.
====

[[v41-10-5]]

^<<v41-10-5,5>>^ Mas Jesus lhes disse: “Foi por causa da dureza do coração de vocês que ele lhes escreveu esse mandamento.

[[v41-10-6]]

^<<v41-10-6,6>>^ No entanto, no princípio da criação ‘Ele os fez homem e mulher.

[TIP]
====
- *princípio da criação*: Pelo visto se refere à criação dos humanos. Jesus estava explicando que o Criador instituiu o casamento entre um homem e uma mulher, formando assim a base da sociedade humana.
- *Ele*: Alguns manuscritos bem antigos dizem “Deus”.
====

[[v41-10-7]]

^<<v41-10-7,7>>^ Por essa razão o homem deixará seu pai e sua mãe,

[[v41-10-8]]

^<<v41-10-8,8>>^ e os dois serão uma só carne’, de modo que não são mais dois, mas uma só carne.

[TIP]
====
- *uma só carne*: Veja a nota de estudo em Mt 19:5.
====

[[v41-10-9]]

^<<v41-10-9,9>>^ Portanto, o que Deus pôs sob o mesmo jugo, o homem não deve separar.”

[[v41-10-10]]

^<<v41-10-10,10>>^ Quando estavam novamente na casa, os discípulos lhe perguntaram sobre isso.

[[v41-10-11]]

^<<v41-10-11,11>>^ Ele lhes disse: “Quem se divorcia da sua esposa e se casa com outra comete adultério contra ela,

[TIP]
====
- *se divorcia da sua esposa*: Ou “manda sua esposa embora”. Para entender corretamente as palavras de Jesus registradas por Marcos, deve-se levar em conta a declaração mais completa registrada em Mt 19:9, que inclui a frase “a não ser por causa de imoralidade sexual”. (Veja a nota de estudo em Mt 5:​32.) O que Marcos escreveu se aplica aos casos em que a pessoa se divorcia por outros motivos, e não porque o marido ou a esposa cometeu “imoralidade sexual” (em grego, porneía).
- *comete adultério contra ela*: Jesus estava rejeitando o ensino rabínico mais aceito naquela época sobre divórcio. Esse ensino dava ao homem o direito de se divorciar da esposa “por qualquer motivo”. (Mt 19:​3, 9) A maioria dos judeus achava que não era possível o marido cometer adultério contra a esposa. Os rabinos ensinavam que, mesmo que o marido tivesse relações sexuais com outra mulher, ele não estava sendo infiel; só a mulher podia ser considerada infiel ao marido. Ao mostrar que o marido tinha a mesma obrigação moral que a esposa, Jesus dignificou as mulheres e ensinou como elas deviam ser encaradas.
====

[[v41-10-12]]

^<<v41-10-12,12>>^ e, se uma mulher, depois de se divorciar do seu marido, se casa com outro, comete adultério.”

[TIP]
====
- *se uma mulher, depois de se divorciar do seu marido*: Ao dizer isso, Jesus reconheceu o direito de a mulher se divorciar do marido se ele fosse infiel. Pelo que parece, os judeus daquela época não reconheciam que as mulheres tinham esse direito. Mas Jesus deixou claro que, entre os cristãos, as mesmas normas se aplicariam a homens e mulheres.
====

[[v41-10-13]]

^<<v41-10-13,13>>^ As pessoas começaram então a trazer a ele criancinhas, para que tocasse nelas, mas os discípulos repreenderam as pessoas.

[TIP]
====
- *criancinhas*: Essas crianças talvez fossem de várias idades, visto que a palavra grega paidíon, traduzida aqui como “criancinhas”, é usada na Bíblia para se referir tanto a recém-nascidos e crianças de colo (Mt 2:8; Lu 1:​59) como à filha de Jairo, uma criança maior que já tinha 12 anos (Mr 5:​39-​42). Mas no relato paralelo em Lu 18:15, que descreve o encontro de Jesus com esse grupo de crianças, Lucas usa a palavra grega bréfos, que se refere apenas a bebês ou a crianças bem pequenas. — Lu 1:​41; 2:​12.
====

[[v41-10-14]]

^<<v41-10-14,14>>^ Vendo isso, Jesus ficou indignado e lhes disse: “Deixem as criancinhas vir a mim. Não tentem impedi-las, pois o Reino de Deus pertence aos que são como elas.

[[v41-10-15]]

^<<v41-10-15,15>>^ Eu lhes digo a verdade: Quem não receber o Reino de Deus como uma criancinha, de modo algum entrará nele.”

[TIP]
====
- *como uma criancinha*: Ou seja, tendo qualidades que as criancinhas geralmente têm. Por exemplo, elas são humildes, gostam de aprender e têm facilidade em confiar nos outros. — Mt 18:5.
====

[[v41-10-16]]

^<<v41-10-16,16>>^ E pegou as crianças nos braços e começou a abençoá-las, pondo as mãos sobre elas.

[TIP]
====
- *pegou as crianças nos braços*: Apenas o Evangelho de Marcos inclui esse detalhe. A palavra grega para “pegar nos braços” só ocorre aqui e em Mr 9:​36, e também pode ser traduzida como “abraçar”. Além de abraçar as crianças, o relato diz que Jesus começou a abençoá-las. A palavra grega usada aqui é uma forma intensificada da palavra para “abençoar”, o que pode indicar que ele tratou as crianças com carinho. Jesus superou as expectativas das pessoas que trouxeram aquelas crianças. Elas esperavam que Jesus apenas “tocasse” nas crianças. (Mr 10:13) Mas Jesus fez mais do que isso porque conhecia bem as necessidades das crianças pequenas, já que ele era o filho mais velho de sua família e tinha pelo menos seis irmãos e irmãs. — Mt 13:55, 56.
====

[[v41-10-17]]

^<<v41-10-17,17>>^ Quando ele estava saindo, um homem chegou correndo, pôs-se de joelhos diante dele e lhe perguntou: “Bom Instrutor, o que devo fazer para herdar a vida eterna?”

[TIP]
====
- *Bom Instrutor*: Pelo visto, o homem estava usando a expressão “Bom Instrutor” como um título formal para bajular Jesus, já que os líderes religiosos costumavam exigir esse tipo de honra. Jesus não via problema em ser chamado de “Instrutor” e “Senhor” (Jo 13:13), mas ele direcionava toda a honra para seu Pai.
====

[[v41-10-18]]

^<<v41-10-18,18>>^ Jesus lhe disse: “Por que você me chama de bom? Ninguém é bom, a não ser um só, Deus.

[TIP]
====
- *Ninguém é bom, a não ser um só, Deus*: Jesus destacou aqui que Jeová é o padrão mais elevado do que é ser bom. Ele é o único que tem o direito supremo de determinar o que é bom e o que é mau. Adão e Eva quiseram tomar para eles esse direito quando foram rebeldes e comeram do fruto da árvore do conhecimento do que é bom e do que é mau. (Gên 2:17; 3:4-6) Mas Jesus é diferente. Ele é humilde e reconhece que somente o seu Pai pode estabelecer esses padrões. Deus nos ensina o que é bom por meio das orientações que ele dá na sua Palavra, a Bíblia. — Mr 10:19.
====

[[v41-10-19]]

^<<v41-10-19,19>>^ Você conhece os mandamentos: ‘Não assassine; não cometa adultério; não furte; não dê falso testemunho; não defraude; honre seu pai e sua mãe.’”

[[v41-10-20]]

^<<v41-10-20,20>>^ O homem lhe disse: “Instrutor, eu tenho cumprido todas essas coisas desde bem jovem.”

[[v41-10-21]]

^<<v41-10-21,21>>^ Jesus olhou para ele e, sentindo amor por ele, disse: “Falta uma coisa a seu respeito: vá, venda o que você tem e dê o dinheiro aos pobres, e você terá um tesouro no céu; e venha ser meu seguidor.”

[TIP]
====
- *sentindo amor por ele*: Apenas Marcos relata o que Jesus sentiu pelo jovem governante rico. (Mt 19:16-​26; Lu 18:18-​30) Essa informação talvez tenha sido dada por Pedro, que também era um homem de fortes sentimentos. — Veja a “Introdução a Marcos”.
====

[[v41-10-22]]

^<<v41-10-22,22>>^ Mas ele ficou triste com a resposta e foi embora abatido, porque tinha muitas posses.

[[v41-10-23]]

^<<v41-10-23,23>>^ Depois de olhar em volta, Jesus disse aos seus discípulos: “Como será difícil para os que têm dinheiro entrar no Reino de Deus!”

[[v41-10-24]]

^<<v41-10-24,24>>^ Mas os discípulos ficaram surpresos com as suas palavras. Jesus disse então: “Filhos, como é difícil entrar no Reino de Deus!

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais fácil um camelo passar pelo buraco de uma agulha do que um rico entrar no Reino de Deus.”

[TIP]
====
- *mais fácil um camelo passar pelo buraco de uma agulha*: Aqui Jesus usou uma hipérbole para ensinar uma lição importante. Assim como é impossível que um camelo passe pelo buraco de uma agulha, é impossível para uma pessoa rica entrar no Reino de Deus se ela continuar amando mais as riquezas do que a Jeová. Mas Jesus não quis dizer que ninguém que fosse rico poderia entrar no Reino, pois ele disse: “Para Deus todas as coisas são possíveis.” — Mr 10:27.
====

[[v41-10-26]]

^<<v41-10-26,26>>^ Eles ficaram ainda mais admirados e lhe perguntaram: “Quem é que pode ser salvo?”

[TIP]
====
- *lhe perguntaram*: Alguns manuscritos dizem “perguntaram uns aos outros”.
====

[[v41-10-27]]

^<<v41-10-27,27>>^ Jesus olhou diretamente para eles e disse: “Para os homens é impossível, mas não é assim para Deus, pois para Deus todas as coisas são possíveis.”

[[v41-10-28]]

^<<v41-10-28,28>>^ Pedro começou a lhe dizer: “Veja, deixamos tudo e seguimos o senhor.”

[[v41-10-29]]

^<<v41-10-29,29>>^ Jesus disse: “Eu lhes garanto: Ninguém deixou casa, irmãos, irmãs, mãe, pai, filhos ou campos, por minha causa e por causa das boas novas,

[[v41-10-30]]

^<<v41-10-30,30>>^ que não receba cem vezes mais agora, neste tempo,^&#42;1^ casas, irmãos, irmãs, mães, filhos e campos, com perseguições, e, no futuro sistema de coisas, a vida eterna.

[NOTE]
====
. Ou: “na época atual”.
====

[TIP]
====
- *no futuro sistema de coisas*: Ou: “na época futura”. A palavra grega aión tem o sentido básico de “época”. Ela pode se referir também a uma situação existente ou a características marcantes de certo período ou época. Neste versículo, Jesus estava se referindo à época futura em que o Reino de Deus assumirá o controle da Terra e as pessoas terão vida eterna. — Lu 18:29, 30; veja o Glossário, “Sistema(s) de coisas”.
====

[[v41-10-31]]

^<<v41-10-31,31>>^ Mas muitos que são primeiros serão últimos; e os últimos, primeiros.”

[[v41-10-32]]

^<<v41-10-32,32>>^ Estavam então indo pela estrada, subindo para Jerusalém, e Jesus ia na frente deles, e eles estavam admirados; mas os que os seguiam estavam com medo. Novamente, ele chamou os Doze à parte e começou a lhes dizer as coisas que estavam para acontecer com ele:

[TIP]
====
- *subindo para Jerusalém*: A cidade de Jerusalém ficava uns 750 metros acima do nível do mar. Por isso, a Bíblia muitas vezes diz que as pessoas ‘subiam para Jerusalém’. (Jo 2:​13; At 11:2) Jesus e seus discípulos estavam saindo do vale do Jordão. (Veja a nota de estudo em Mr 10:1.) O ponto mais baixo desse vale fica uns 400 metros abaixo do nível do mar. Assim, eles teriam que subir uns 1.000 metros para chegar em Jerusalém.
====

[[v41-10-33]]

^<<v41-10-33,33>>^ “Escutem, estamos subindo para Jerusalém, e o Filho do Homem será entregue aos principais sacerdotes e aos escribas. Eles o condenarão à morte e o entregarão a homens das nações,

[[v41-10-34]]

^<<v41-10-34,34>>^ e esses zombarão dele, cuspirão nele, o açoitarão e o matarão, mas três dias depois ele será levantado.”

[TIP]
====
- *cuspirão nele*: Cuspir numa pessoa, ou no rosto dela, era um ato de extremo desprezo, inimizade ou indignação, que humilhava a pessoa. (Núm 12:14; De 25:9) Jesus estava dizendo que sofreria esse tipo de humilhação, que cumpriria uma profecia sobre o Messias: “Não escondi o rosto das humilhações e dos cuspes.” (Is 50:6) Ele passou por isso quando cuspiram nele no julgamento diante do Sinédrio (Mr 14:65) e quando os soldados romanos cuspiram nele depois que ele foi julgado por Pilatos (Mr 15:19).
====

[[v41-10-35]]

^<<v41-10-35,35>>^ Tiago e João, os filhos de Zebedeu, se aproximaram dele e lhe disseram: “Instrutor, queremos que o senhor faça para nós o que lhe pedirmos.”

[TIP]
====
- *filhos*: Alguns poucos manuscritos dizem “dois filhos”, mas a palavra “dois” não aparece na maioria dos manuscritos mais antigos.
- *Tiago e João, os filhos de Zebedeu, se aproximaram dele*: O relato paralelo em Mateus diz que quem fez o pedido a Jesus foi a mãe de Tiago e João, mas pelo visto a ideia foi dos dois filhos. O relato de Mateus apoia essa conclusão dizendo que, quando os outros dez apóstolos souberam disso, “ficaram indignados” com os dois irmãos, não com a mãe deles. — Mt 20:20-​24; veja as notas de estudo em Mt 4:​21; 20:20.
====

[[v41-10-36]]

^<<v41-10-36,36>>^ Ele lhes perguntou: “O que querem que eu faça para vocês?”

[[v41-10-37]]

^<<v41-10-37,37>>^ Eles responderam: “Conceda-nos que nos sentemos um à sua direita e outro à sua esquerda, na sua glória.”

[TIP]
====
- *um à sua direita e outro à sua esquerda*: Neste contexto, as duas posições indicam honra e autoridade, mas a posição de maior honra é sempre a da direita. — Sal 110:1; At 7:55,56; Ro 8:34; veja a nota de estudo em Mt 25:33.
====

[[v41-10-38]]

^<<v41-10-38,38>>^ Mas Jesus lhes disse: “Vocês não sabem o que estão pedindo. Será que podem beber o cálice que eu estou bebendo ou ser batizados com o batismo com que eu estou sendo batizado?”

[TIP]
====
- *beber o cálice*: Veja a nota de estudo em Mt 20:22.
- *ser batizados com o batismo com que eu estou sendo batizado*: Ou: “ser imersos com a mesma imersão pela qual eu estou passando”. Jesus usou aqui a palavra “batismo” em paralelo com “cálice”. (Veja a nota de estudo em Mt 20:22.) Ele estava falando de seu batismo na morte. Quando Jesus foi batizado em água, ele aceitou seguir um caminho que o levaria à morte. Assim, o seu batismo na morte já estava em andamento durante seu ministério. Jesus seria totalmente batizado ou imerso quando ele morresse na estaca em 14 de nisã de 33 d.C. Da mesma forma que o batismo literal se completa quando a pessoa é levantada da água, o batismo de Jesus na morte se completou quando ele foi levantado dentre os mortos. (Ro 6:​3, 4) Assim, há uma clara diferença entre o batismo de Jesus na morte e seu batismo na água. Ao passo que o batismo na água foi realizado de forma completa no começo de seu ministério, esse batismo era apenas o início de seu batismo na morte.
====

[[v41-10-39]]

^<<v41-10-39,39>>^ Disseram-lhe: “Podemos.” Então Jesus lhes disse: “Vocês beberão o cálice que eu estou bebendo e serão batizados com o batismo com que eu estou sendo batizado.

[[v41-10-40]]

^<<v41-10-40,40>>^ No entanto, sentar-se à minha direita ou à minha esquerda não cabe a mim conceder; esses lugares pertencem àqueles para quem foram preparados.”

[[v41-10-41]]

^<<v41-10-41,41>>^ Quando os outros dez souberam disso, ficaram indignados com Tiago e João.

[[v41-10-42]]

^<<v41-10-42,42>>^ Mas Jesus os chamou e lhes disse: “Vocês sabem que os que são considerados governantes das^&#42;1^ nações dominam sobre elas, e seus grandes exercem autoridade sobre elas.

[NOTE]
====
. Ou: “os que parecem governar as”.
====

[TIP]
====
- *dominam sobre elas*: Ou: “têm poder sobre elas; são donos delas”. Essa palavra grega só é usada quatro vezes nas Escrituras Gregas Cristãs. (Mt 20:25; Mr 10:42; At 19:16; 1Pe 5:3) O conselho de Jesus deve ter feito seus ouvintes lembrar da opressão do governo romano, que os judeus odiavam, e também da dinastia dos Herodes, que governavam com tirania. (Mt 2:​16; Jo 11:48) Pelo visto, Pedro entendeu o conselho. Anos mais tarde, ele orientou os anciãos cristãos a liderar dando o exemplo, não dominando os irmãos. (1Pe 5:3) Um verbo relacionado com essa palavra grega aparece em Lu 22:25, onde Jesus deu um conselho parecido. O mesmo verbo aparece em 2Co 1:​24, onde Paulo disse que os cristãos não devem ser os “donos” da fé de seus irmãos.
====

[[v41-10-43]]

^<<v41-10-43,43>>^ Não deve ser assim entre vocês; mas quem quiser se tornar grande entre vocês tem de ser o seu servo,^&#42;1^

[NOTE]
====
. Ou: “ministro”.
====

[[v41-10-44]]

^<<v41-10-44,44>>^ e quem quiser ser o primeiro entre vocês tem de ser o escravo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Pois até mesmo o Filho do Homem veio, não para ser servido, mas para servir^&#42;1^ e dar a sua vida como resgate em troca de muitos.”

[NOTE]
====
. Ou: “ministrar”.
====

[TIP]
====
- *vida*: Veja a nota de estudo em Mt 20:28.
====

[[v41-10-46]]

^<<v41-10-46,46>>^ Eles entraram então em Jericó. Mas, quando ele, seus discípulos e uma multidão considerável estavam saindo de Jericó, Bartimeu (filho de Timeu), um mendigo cego, estava sentado à beira da estrada.

[TIP]
====
- *Jericó*: Veja a nota de estudo em Mt 20:29.
- *um mendigo cego*: O relato paralelo de Mt 20:30 diz que havia dois cegos nessa ocasião. Mas Marcos e Lucas falam de apenas um cego. (Lu 18:35) Pelo visto, eles se concentraram em Bartimeu, que só é mencionado por nome no Evangelho de Marcos.
====

[[v41-10-47]]

^<<v41-10-47,47>>^ Ao ouvir que era Jesus, o Nazareno, ele começou a gritar: “Filho de Davi, Jesus, tenha misericórdia de mim!”

[TIP]
====
- *o Nazareno*: Expressão usada para se referir a Jesus e, mais tarde, aos seus discípulos. (At 24:5) Alguns nomes eram comuns entre os judeus, incluindo o nome Jesus, e por isso muitos acrescentavam ao nome alguma palavra ou expressão para identificar a pessoa. Nos tempos bíblicos, era costume associar a pessoa com seu lugar de origem. (2Sa 3:​2, 3; 17:27; 23:25-​39; Na 1:1; At 13:1; 21:29) Visto que Jesus passou a maior parte da sua vida na Terra em Nazaré, na Galileia, era natural que o chamassem de “o Nazareno”. Várias pessoas usavam essa expressão para se referir a ele, em diversas situações. (Mr 1:​23, 24; 10:46, 47; 14:66-​69; 16:​5, 6; Lu 24:13-​19; Jo 18:​1-7) O próprio Jesus aceitou esse nome e o usou. (Jo 18:​5-8; At 22:​6-8) Na placa que Pilatos colocou na estaca de Jesus, ele escreveu em hebraico, latim e grego: “Jesus, o Nazareno, Rei dos judeus”. (Jo 19:19, 20) A partir do Pentecostes de 33 d.C., os apóstolos e outros muitas vezes chamaram Jesus de “o Nazareno” ou disseram que ele era de Nazaré. — At 2:​22; 3:6; 4:​10; 6:​14; 10:38; 26:9; veja também a nota de estudo em Mt 2:​23.
- *Filho de Davi*: Ao chamar Jesus de “Filho de Davi”, Bartimeu declarou abertamente que acreditava que Jesus era o Messias. — Veja as notas de estudo em Mt 1:​1, 6; 15:25.
====

[[v41-10-48]]

^<<v41-10-48,48>>^ Em vista disso, muitos começaram a censurá-lo, mandando que se calasse, mas ele gritava ainda mais: “Filho de Davi, tenha misericórdia de mim!”

[[v41-10-49]]

^<<v41-10-49,49>>^ Então Jesus parou e disse: “Chamem-no.” E chamaram o cego, dizendo-lhe: “Coragem! Levante-se, ele está chamando você.”

[[v41-10-50]]

^<<v41-10-50,50>>^ Jogando a capa para o lado, ele se levantou rapidamente e foi ao encontro de Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ Então Jesus lhe perguntou: “O que você quer que eu faça por você?” O cego lhe disse: “Rabôni, deixe-me recuperar a visão.”

[TIP]
====
- *Rabôni*: Palavra semítica que significa “meu instrutor”. Pode ser que a palavra “Rabôni” originalmente fosse considerada mais respeitosa do que sua forma mais simples “Rabi”, que significa “instrutor” (Jo 1:​38), ou fosse usada para se dirigir a um instrutor de maneira carinhosa. Mas, quando João escreveu seu Evangelho, o significado especial da forma “Rabôni” talvez já tivesse se perdido, já que ele a traduziu simplesmente como “Instrutor”. — Jo 20:16.
====

[[v41-10-52]]

^<<v41-10-52,52>>^ E Jesus lhe disse: “Vá, sua fé fez você ficar bom.”^&#42;1^ E ele recuperou imediatamente a visão e começou a segui-lo pela estrada.

[NOTE]
====
. Ou: “salvou você”.
====

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]