include::./index.adoc[]

[[v41-11-0]]
=== As Boas Novas Segundo Marcos, 11
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* G. Últimos dias da pregação de Jesus em Jerusalém (11:1–14:16)
* Entrada triunfal de Jesus em Jerusalém (11:1-11)
* Jesus amaldiçoa uma figueira no caminho para Jerusalém (11:12-14)
* Jesus purifica o templo (11:15-18)
* Lição da figueira que secou (11:19-25)
* Autoridade de Jesus é questionada (11:27-33)
* Ilustração dos lavradores maus (12:1-12)
* Deus e César (12:13-17)
* Pergunta sobre a ressurreição (12:18-27)
* Dois maiores mandamentos (12:28-34)
* O Cristo é filho de Davi? (12:35-37a)
* Alerta contra os escribas (12:37b-40)
* Duas moedas da viúva pobre (12:41-44)
* Pergunta sobre “o sinal de que todas essas coisas” vão “chegar a um final” (13:1-4)
* Acontecimentos que fazem parte do sinal; tribulação sem precedentes (13:5-20)
* Perigo de ser desencaminhado por falsos Cristos (13:21-23)
* Vinda do Filho do Homem (13:24-27)
* Ilustração da figueira (13:28, 29)
* Esta geração não passará (13:30, 31)
* Ninguém sabe o dia e a hora, nem os anjos (13:32)
* Mantenham-se vigilantes (13:33-37)
* Sacerdotes tramam matar Jesus (14:1, 2)
* Mulher derrama óleo perfumado em Jesus (14:3-9)
* Judas planeja traição de Jesus (14:10, 11)
* Preparativos para a última Páscoa (14:12-16)
****

[[v41-11-1]]

^<<v41-11-1,1>>^ Então, quando estavam chegando perto de Jerusalém, de Betfagé e de Betânia, no monte das Oliveiras, ele enviou dois dos seus discípulos

[TIP]
====
- *Então*: Os acontecimentos descritos em Mr 11:​1-​11 ocorreram durante o período de luz do dia 9 de nisã. — Veja os Apêndices A7-G e B12-A.
- *Betfagé*: Aldeia que ficava no monte das Oliveiras. Seu nome vem do hebraico e provavelmente significa “casa dos primeiros figos”. Acredita-se que ela ficava na encosta sudeste do monte das Oliveiras, perto do topo, a cerca de 1 quilômetro de Jerusalém, no caminho para Betânia. — Mt 21:1; Lu 19:29; veja o Mapa 6 no Apêndice A7-G.
- *Betânia*: Veja a nota de estudo em Mt 21:17.
====

[[v41-11-2]]

^<<v41-11-2,2>>^ e lhes disse: “Vão à aldeia que está ao alcance da vista e, assim que entrarem lá, acharão um jumentinho amarrado, no qual ninguém ainda montou. Desamarrem-no e tragam-no para cá.

[TIP]
====
- *um jumentinho*: Os Evangelhos de Marcos, Lucas (19:35) e João (12:14, 15) falam apenas do jumentinho ao relatar esse acontecimento. Mateus (21:​2-7) acrescenta o detalhe de que o jumentinho estava com a mãe. — Veja as notas de estudo em Mt 21:​2, 5.
====

[[v41-11-3]]

^<<v41-11-3,3>>^ E, se alguém lhes perguntar: ‘Por que estão fazendo isso?’, digam: ‘O Senhor precisa dele, e logo o mandará de volta para cá.’”

[[v41-11-4]]

^<<v41-11-4,4>>^ Assim partiram e acharam o jumentinho amarrado junto a uma porta, do lado de fora, na rua, e o desamarraram.

[[v41-11-5]]

^<<v41-11-5,5>>^ Mas alguns dos que estavam ali perguntaram a eles: “O que vocês estão fazendo, desamarrando o jumentinho?”

[[v41-11-6]]

^<<v41-11-6,6>>^ Disseram a eles o que Jesus tinha dito, e eles os deixaram ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ Trouxeram então a Jesus o jumentinho e colocaram sobre este suas capas, e ele se sentou nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Também, muitos estenderam suas capas na estrada, mas outros cortaram ramos dos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ E os que iam na frente e os que vinham atrás gritavam: “Salva, rogamos! Bendito é aquele que vem em nome de Jeová!

[TIP]
====
- *Salva, rogamos*: Lit.: “Hosana”. A palavra grega usada aqui vem de uma expressão hebraica que significa “salva, rogamos” ou “salva, por favor”. Com o tempo, ela passou a ser usada tanto em orações como em louvores. Neste versículo, ela é uma súplica para que Deus dê salvação ou vitória, e poderia ser traduzida como “por favor, dá salvação para”. A expressão hebraica pode ser encontrada no Sal 118:25, que faz parte dos Salmos de Halel. Os israelitas sempre cantavam esses salmos na época da Páscoa, e por isso essas palavras vieram à mente das pessoas que receberam Jesus. Uma das maneiras de Deus responder a esse pedido e salvar Jesus, o Filho de Davi, foi quando o ressuscitou. Em Mr 12:10, 11, o próprio Jesus citou o Sal 118:22, 23 e deu a entender que essas palavras se cumpririam no Messias.
- *Jeová*: Esta é uma citação direta do Sal 118:25, 26. No texto hebraico original desse salmo, aparecem as quatro letras hebraicas que formam o nome de Deus (que equivalem a YHWH). — Veja o Apêndice C1.
====

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito é o Reino que virá, do nosso pai Davi! Salva, rogamos, nas maiores alturas!”^&#42;1^

[NOTE]
====
. Ou: “nos lugares mais altos”.
====

[TIP]
====
- *o Reino que virá, do nosso pai Davi*: Essa tradução está de acordo com os manuscritos mais antigos e mais confiáveis, mas alguns poucos manuscritos bem antigos dizem “o reino do nosso pai Davi, que vem em nome do Senhor”. Algumas Bíblias em português seguiram esses poucos manuscritos. Várias traduções das Escrituras Gregas Cristãs para o hebraico (chamadas de J7, 8, 10-12, 14, 16, 17 no Apêndice C) usam aqui o Tetragrama ou uma forma abreviada dele e dizem “o reino de nosso pai Davi, que vem em nome de Jeová”.
====

[[v41-11-11]]

^<<v41-11-11,11>>^ E ele entrou em Jerusalém, foi ao templo e olhou tudo em volta, mas, visto que já estava tarde, saiu com os Doze para Betânia.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, quando estavam saindo de Betânia, ele sentiu fome.

[TIP]
====
- *No dia seguinte*: Ou seja, 10 de nisã. — Veja os Apêndices A7-G e B12-A.
====

[[v41-11-13]]

^<<v41-11-13,13>>^ De certa distância viu uma figueira que tinha folhas e foi ver se achava algo nela. Mas, ao chegar perto dela, não encontrou nada, exceto folhas, pois não era a estação dos figos.

[TIP]
====
- *não encontrou nada, exceto folhas*: As figueiras não costumavam ter folhas ou dar fruto naquela época do ano, mas aquela tinha folhas. Isso normalmente indicaria que a figueira teria produzido figos temporãos. A aparência daquela figueira era enganosa, porque ela tinha folhas, mas não tinha frutos. Jesus sabia que isso queria dizer que ela não daria nenhum fruto e, por isso, amaldiçoou a figueira e a fez secar. — Mr 11:19-21.
====

[[v41-11-14]]

^<<v41-11-14,14>>^ Então ele lhe disse: “Nunca mais ninguém coma do seu fruto.” E os seus discípulos estavam escutando.

[[v41-11-15]]

^<<v41-11-15,15>>^ Chegaram então a Jerusalém. Ali ele entrou no templo e começou a expulsar os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas;

[TIP]
====
- *templo*: Veja a nota de estudo em Mt 21:12.
- *expulsar os que vendiam e compravam*: Veja a nota de estudo em Lu 19:45.
- *cambistas*: Veja a nota de estudo em Mt 21:12.
====

[[v41-11-16]]

^<<v41-11-16,16>>^ e não deixava ninguém carregar nenhum utensílio através do templo.

[TIP]
====
- *carregar nenhum utensílio através do templo*: Pelo visto, algumas pessoas usavam o pátio do templo para cortar caminho quando transportavam coisas para uso pessoal ou comercial. Jesus não permitiu isso, porque essa ação mostrava falta de respeito pela santidade da casa de Deus. Apenas o Evangelho de Marcos menciona esse fato.
====

[[v41-11-17]]

^<<v41-11-17,17>>^ Ele ensinava, dizendo-lhes: “Não está escrito: ‘Minha casa será chamada casa de oração para todas as nações’? Mas vocês fizeram dela um abrigo de ladrões.”

[TIP]
====
- *casa de oração para todas as nações*: Dos três Evangelhos que citam Is 56:7, apenas Marcos inclui a expressão “para todas as nações [todos os povos]”. (Mt 21:13; Lu 19:46) O templo em Jerusalém deveria ser um lugar para adorar e orar a Jeová, tanto para israelitas como para estrangeiros que temessem a Deus. (1Rs 8:41-43) Por isso Jesus condenou os judeus que faziam comércio ali e transformavam o templo em um abrigo de ladrões. As ações deles desmotivavam as pessoas, criando um obstáculo para que pessoas de todas as nações adorassem a Jeová em sua casa de oração. Esses comerciantes estavam impedindo aquelas pessoas de conhecerem a Jeová.
- *abrigo de ladrões*: Veja a nota de estudo em Mt 21:13.
====

[[v41-11-18]]

^<<v41-11-18,18>>^ Os principais sacerdotes e os escribas ouviram isso, e começaram a procurar um meio de matá-lo, pois tinham medo dele, porque toda a multidão estava maravilhada com o seu ensino.

[[v41-11-19]]

^<<v41-11-19,19>>^ Quando ficou tarde no dia, saíram da cidade.

[TIP]
====
- *tarde no dia*: Ou seja, tarde no dia 10 de nisã. Jesus e seus discípulos saíram de Jerusalém e voltaram para Betânia, que ficava na encosta leste do monte das Oliveiras. Jesus provavelmente passou a noite na casa de seus amigos Lázaro, Maria e Marta. — Veja os Apêndices A7-G e B12-A.
====

[[v41-11-20]]

^<<v41-11-20,20>>^ Mas, de manhã cedo, quando estavam passando pela figueira, viram que ela estava seca desde as raízes.

[TIP]
====
- *de manhã cedo*: Ou seja, na manhã do dia 11 de nisã. Jesus e seus discípulos estavam voltando a Jerusalém para o último dia de pregação antes de Jesus celebrar a Páscoa, instituir a Celebração de sua morte e ser julgado e morto. — Veja os Apêndices A7-G e B12-A.
====

[[v41-11-21]]

^<<v41-11-21,21>>^ Pedro se lembrou e lhe disse: “Rabi, veja! A figueira que o senhor amaldiçoou secou.”

[[v41-11-22]]

^<<v41-11-22,22>>^ Jesus lhe disse em resposta: “Tenham fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Eu lhes digo a verdade: Quem disser a este monte: ‘Levante-se e jogue-se no mar’, e não duvidar no coração, mas tiver fé em que aquilo que disser vai acontecer, assim acontecerá.

[TIP]
====
- *Eu lhes digo a verdade*: Veja a nota de estudo em Mt 5:18.
====

[[v41-11-24]]

^<<v41-11-24,24>>^ É por isso que lhes digo: Todas as coisas que vocês pedirem em oração, tenham fé em que já as receberam, e as terão.

[[v41-11-25]]

^<<v41-11-25,25>>^ E, quando vocês estiverem em pé, orando, perdoem o que tiverem contra alguém, para que o seu Pai, que está nos céus, também perdoe as falhas de vocês.”

[TIP]
====
- *estiverem em pé, orando*: Os hebreus e as pessoas de muitas das nações mencionadas na Bíblia não tinham regras sobre a posição em que a pessoa deveria estar para orar. Mas a postura escolhida era sempre muito respeitosa. Era comum ficar de pé para orar.
====

[[v41-11-26]]

^<<v41-11-26,26>>^ ——

[TIP]
====
- *Alguns manuscritos bem antigos dizem neste versículo*: “Mas, se vocês não perdoarem, o Pai de vocês que está no céu não perdoará os pecados de vocês.” Essa frase não aparece nos manuscritos mais antigos e mais confiáveis, e pelo visto não faz parte do relato inspirado de Marcos. Mas uma frase semelhante aparece no relato inspirado em Mt 6:​15. — Veja o Apêndice A3.
====

[[v41-11-27]]

^<<v41-11-27,27>>^ Chegaram novamente a Jerusalém. E enquanto ele andava pelo templo, os principais sacerdotes, os escribas e os anciãos vieram

[TIP]
====
- *principais sacerdotes*: Veja a nota de estudo em Mt 2:4.
- *escribas*: Veja a nota de estudo em Mt 2:4.
- *anciãos*: Veja a nota de estudo em Mr 8:​31.
====

[[v41-11-28]]

^<<v41-11-28,28>>^ e lhe perguntaram: “Com que autoridade você faz essas coisas? E quem lhe deu autoridade para fazer essas coisas?”

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus lhes disse: “Eu lhes farei uma pergunta. Respondam-me, e eu lhes direi com que autoridade faço essas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu ou dos homens?^&#42;1^ Respondam-me.”

[NOTE]
====
. Ou: “de origem humana”.
====

[[v41-11-31]]

^<<v41-11-31,31>>^ Então eles começaram a raciocinar entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Então, por que vocês não acreditaram nele?’

[[v41-11-32]]

^<<v41-11-32,32>>^ Mas nos atrevemos a dizer: ‘Dos homens’?” Eles tinham medo da multidão, pois todos achavam que João realmente tinha sido um profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Assim, responderam a Jesus: “Não sabemos.” Jesus lhes disse: “Então eu também não lhes digo com que autoridade faço essas coisas.”

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]