include::./index.adoc[]

[[v41-4-0]]
=== As Boas Novas Segundo Marcos, 4
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. Jesus ensina usando ilustrações (4:1-34)
* De um barco, Jesus ensina grandes multidões (4:1, 2)
* Ilustração do semeador e dos quatro tipos de solo (4:3-9)
* Por que Jesus usou ilustrações (4:10-13)
* Explicação da ilustração do semeador (4:14-20)
* Não se coloca uma lâmpada debaixo de um cesto (4:21-23)
* “A mesma medida com que vocês medem” (4:24, 25)
* Ilustração do semeador que dorme (4:26-29)
* Ilustração do grão de mostarda (4:30-32)
* Uso de ilustrações (4:33, 34)
* D. Jesus faz vários milagres, no mar da Galileia e na região ao redor (4:35–5:43)
* Jesus acalma uma tempestade violenta (4:35-41)
* Jesus cura um homem possesso de demônios; permite que os demônios entrem nos porcos (5:1-20)
* Ressuscita filha de Jairo; uma mulher toca na roupa de Jesus (5:21-43)
****

[[v41-4-1]]

^<<v41-4-1,1>>^ Ele começou novamente a ensinar à beira do mar, e uma multidão muito grande se reuniu perto dele. Então ele entrou num barco e se sentou, e ficou a certa distância da margem, mas toda a multidão estava em terra, à beira do mar.

[TIP]
====
- *a certa distância da margem*: Veja a nota de estudo em Mt 13:2.
====

[[v41-4-2]]

^<<v41-4-2,2>>^ E ele começou a ensinar-lhes muitas coisas com ilustrações. Ensinava-lhes dizendo:

[TIP]
====
- *ilustrações*: Veja a nota de estudo em Mt 13:3.
====

[[v41-4-3]]

^<<v41-4-3,3>>^ “Escutem: O semeador saiu para semear.

[[v41-4-4]]

^<<v41-4-4,4>>^ Ao passo que semeava, algumas sementes caíram à beira da estrada, e vieram as aves e as comeram.

[[v41-4-5]]

^<<v41-4-5,5>>^ Outras caíram em solo rochoso, onde não havia muita terra, e brotaram imediatamente porque o solo não era profundo.

[TIP]
====
- *em solo rochoso*: Veja a nota de estudo em Mt 13:5.
====

[[v41-4-6]]

^<<v41-4-6,6>>^ Mas, quando o sol se levantou, ficaram queimadas e murcharam, porque não tinham raiz.

[[v41-4-7]]

^<<v41-4-7,7>>^ Outras sementes caíram entre os espinhos, e os espinhos cresceram e as sufocaram, e elas não deram fruto.

[TIP]
====
- *entre os espinhos*: Veja a nota de estudo em Mt 13:7.
====

[[v41-4-8]]

^<<v41-4-8,8>>^ Mas outras caíram em solo bom e, depois de brotar e crescer, começaram a dar fruto; e produziram 30, 60 e 100 vezes mais.”

[[v41-4-9]]

^<<v41-4-9,9>>^ Ele acrescentou então: “Quem tem ouvidos para escutar, escute.”

[TIP]
====
- *Quem tem ouvidos para escutar, escute*: Antes de contar a ilustração do semeador, Jesus disse: “Escutem.” (Mr 4:3) Aqui, no fim da ilustração, ele aconselha novamente seus seguidores a ‘escutar’, mostrando que é muito importante prestar atenção e agir de acordo com o que ele diz. Podemos encontrar frases bem parecidas com essa em Mt 11:15; 13:​9, 43; Mr 4:​23; Lu 8:8; 14:35; Ap 2:​7, 11, 17, 29; 3:​6, 13, 22; 13:9.
====

[[v41-4-10]]

^<<v41-4-10,10>>^ Então, quando ficou sozinho, os que estavam em volta dele vieram com os Doze e começaram a lhe perguntar sobre as ilustrações.

[[v41-4-11]]

^<<v41-4-11,11>>^ Ele lhes disse: “A vocês foi dado o segredo sagrado do Reino de Deus, mas para os de fora tudo é apresentado em ilustrações,

[[v41-4-12]]

^<<v41-4-12,12>>^ para que eles olhem, mas ainda assim não vejam, e ouçam, mas ainda assim não compreendam; e eles jamais darão meia-volta e receberão perdão.”

[[v41-4-13]]

^<<v41-4-13,13>>^ Além disso, ele lhes disse: “Vocês não compreendem essa ilustração; portanto, como entenderão todas as outras ilustrações?

[[v41-4-14]]

^<<v41-4-14,14>>^ “O semeador semeia a palavra.

[[v41-4-15]]

^<<v41-4-15,15>>^ Então, aquelas sementes à beira da estrada, onde se semeia a palavra, representam os que ouvem a palavra, mas logo vem Satanás e tira a palavra que foi semeada neles.

[[v41-4-16]]

^<<v41-4-16,16>>^ Do mesmo modo, aquelas semeadas em solo rochoso representam os que ouvem a palavra e logo a aceitam com alegria.

[[v41-4-17]]

^<<v41-4-17,17>>^ Contudo, não têm raiz em si mesmos, mas continuam por algum tempo; então, assim que surge dificuldade ou perseguição por causa da palavra, tropeçam.

[[v41-4-18]]

^<<v41-4-18,18>>^ Ainda há outras que são semeadas entre os espinhos. Essas representam os que ouvem a palavra,

[[v41-4-19]]

^<<v41-4-19,19>>^ mas as ansiedades deste mundo, o poder enganoso das riquezas^&#42;1^ e os desejos de todas as outras coisas interferem e sufocam a palavra, e ela se torna infrutífera.

[NOTE]
====
. Ou: “a tentação (o prazer enganoso) de ser rico”.
====

[TIP]
====
- *mundo*: Veja a nota de estudo em Mt 13:22.
====

[[v41-4-20]]

^<<v41-4-20,20>>^ Finalmente, aquelas que foram semeadas em solo bom representam os que escutam a palavra, a aceitam e dão fruto: 30, 60 e 100 vezes mais.”

[[v41-4-21]]

^<<v41-4-21,21>>^ Disse-lhes também: “Será que se pega uma lâmpada para colocá-la debaixo de um cesto ou debaixo de uma cama? Não é para colocá-la em cima de um suporte?

[TIP]
====
- *uma lâmpada*: Veja a nota de estudo em 5:15.
- *um cesto*: Veja a nota de estudo em Mt 5:​15.
====

[[v41-4-22]]

^<<v41-4-22,22>>^ Pois não há nada escondido que não venha a ser exposto; nada cuidadosamente oculto que não venha à tona.

[[v41-4-23]]

^<<v41-4-23,23>>^ Escute quem tem ouvidos para escutar.”

[[v41-4-24]]

^<<v41-4-24,24>>^ Disse-lhes ainda: “Prestem atenção ao que estão ouvindo. A mesma medida com que vocês medem será usada com vocês, e mais lhes será acrescentado.

[TIP]
====
- *A mesma medida com que vocês medem*: O contexto nos versículos 23 a 25 indica que, se os discípulos dessem pouca atenção e mostrassem falta de interesse, eles tirariam pouco proveito dos ensinos de Jesus. Mas, se dessem a Jesus toda a sua atenção, ele corresponderia dando ainda mais informações e esclarecimentos. Esse entendimento enriqueceria suas vidas, e eles ficariam mais preparados para ensinar outros. Jesus, na sua generosidade, superaria as expectativas deles.
====

[[v41-4-25]]

^<<v41-4-25,25>>^ Pois àquele que tem, mais será dado; mas daquele que não tem, até mesmo o que tem será tirado.”

[[v41-4-26]]

^<<v41-4-26,26>>^ Assim, acrescentou: “Portanto, o Reino de Deus é como quando um homem lança sementes no solo.

[TIP]
====
- *Portanto, o Reino de Deus é como quando um homem lança sementes*: O Evangelho de Marcos é o único que registra a ilustração encontrada nos versículos 26 a 29.
====

[[v41-4-27]]

^<<v41-4-27,27>>^ Ele dorme à noite e se levanta de dia, e as sementes brotam e crescem alto, embora ele não saiba exatamente como.

[[v41-4-28]]

^<<v41-4-28,28>>^ O solo, por si mesmo, dá fruto aos poucos: primeiro a haste, depois a espiga, e finalmente o grão maduro na espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ Mas, assim que os grãos ficam maduros, ele passa a foice, porque chegou o tempo da colheita.”

[[v41-4-30]]

^<<v41-4-30,30>>^ E acrescentou: “A que podemos comparar o Reino de Deus, ou com que ilustração podemos explicá-lo?

[[v41-4-31]]

^<<v41-4-31,31>>^ É semelhante a um grão de mostarda que, quando é semeado no solo, é a menor de todas as sementes da terra.

[TIP]
====
- *grão de mostarda*: Veja a nota de estudo em Mt 13:31.
- *a menor de todas as sementes*: Veja a nota de estudo em Mt 13:32.
====

[[v41-4-32]]

^<<v41-4-32,32>>^ Mas, depois de semeado, cresce e se torna maior do que todas as outras hortaliças e produz grandes ramos, de modo que as aves do céu podem achar abrigo sob a sua sombra.”

[[v41-4-33]]

^<<v41-4-33,33>>^ Com muitas ilustrações desse tipo, ele lhes falava a palavra, até onde eram capazes de entender.^&#42;1^

[NOTE]
====
. Lit.: “ouvir”.
====

[TIP]
====
- *entender*: Ou: “escutar”. A palavra grega para “escutar” pode passar a ideia de “prestar atenção por escutar” ou de “entender (compreender)”. — Compare com as notas de estudo em At 9:7; 22:9.
====

[[v41-4-34]]

^<<v41-4-34,34>>^ Realmente, nada lhes falava sem ilustração, mas explicava tudo em particular aos seus discípulos.

[[v41-4-35]]

^<<v41-4-35,35>>^ E naquele dia, ao cair a noite, ele lhes disse: “Passemos para a outra margem.”

[TIP]
====
- *a outra margem*: Veja a nota de estudo em Mt 8:18.
====

[[v41-4-36]]

^<<v41-4-36,36>>^ Assim, depois de terem dispensado a multidão, eles o levaram, assim como estava, no barco; e havia outros barcos com ele.

[[v41-4-37]]

^<<v41-4-37,37>>^ Levantou-se então uma violenta tempestade, e as ondas se lançavam sobre o barco, de modo que o barco estava ficando inundado.

[TIP]
====
- *uma violenta tempestade*: Essa expressão traduz três palavras gregas que poderiam ser traduzidas literalmente como “um grande furacão de vento”. (Veja a nota de estudo em Mt 8:​24.) Visto que Marcos não estava presente naquela ocasião, essa descrição da força da tempestade e outros detalhes mencionados nesse relato talvez indiquem que foi Pedro quem contou para Marcos o que aconteceu. — Para mais informações sobre a contribuição de Pedro para o Evangelho de Marcos, veja a “Introdução a Marcos”.
====

[[v41-4-38]]

^<<v41-4-38,38>>^ Mas ele estava na popa, dormindo sobre o travesseiro. Assim, eles o acordaram e lhe disseram: “Instrutor, o senhor não se importa que estejamos prestes a morrer?”

[TIP]
====
- *o travesseiro*: Ou: “a almofada”. Esta é a única ocorrência dessa palavra grega nas Escrituras Gregas Cristãs. Aqui foi usado o artigo definido em grego, o que talvez indique que o travesseiro era um item específico que fazia parte do equipamento do barco. Talvez fosse um saco de areia que ficava debaixo do convés da popa para dar estabilidade, um assento revestido de couro para o timoneiro, ou uma almofada ou um velo de lã onde um remador podia sentar.
====

[[v41-4-39]]

^<<v41-4-39,39>>^ Com isso ele se levantou, censurou o vento e disse ao mar: “Silêncio! Cale-se!” E o vento parou, e houve uma grande calmaria.

[[v41-4-40]]

^<<v41-4-40,40>>^ Então ele lhes disse: “Por que vocês estão com tanto medo?^&#42;1^ Ainda não têm nenhuma fé?”

[NOTE]
====
. Ou: “são tão inseguros”.
====

[[v41-4-41]]

^<<v41-4-41,41>>^ Mas eles sentiram um medo incomum e disseram uns aos outros: “Quem é realmente este homem? Até mesmo o vento e o mar lhe obedecem.”

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]