include::./index.adoc[]

[[v41-6-0]]
=== As Boas Novas Segundo Marcos, 6
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* E. Jesus expande seu ministério na Galileia e visita regiões ao norte e ao leste (6:1–9:50)
* Jesus é rejeitado em sua própria cidade (6:1-6)
* Jesus dá instruções aos Doze sobre o ministério e os envia (6:7-13)
* Morte de João, o Batizador (6:14-29)
* Jesus alimenta cerca de 5.000 homens (6:30-44)
* Jesus anda sobre a água (6:45-52)
* Curas em Genesaré (6:53-56)
* Tradições de homens são expostas por Jesus (7:1-13)
* Impureza vem do coração (7:14-23)
* Jesus cura a filha da mulher siro-fenícia (7:24-30)
* Jesus cura um surdo em Decápolis (7:31-37)
* Jesus alimenta cerca de 4.000 homens (8:1-10)
* Fariseus pedem um sinal do céu (8:11-13)
* Jesus avisa sobre o fermento dos fariseus e de Herodes (8:14-21)
* Cego é curado em Betsaida (8:22-26)
* No caminho para Cesareia de Filipe, Pedro identifica Jesus como o Cristo (8:27-30)
* Jesus prediz sua morte e ressurreição (8:31-33)
* Requisitos para ser um verdadeiro discípulo (8:34–9:1)
* Transfiguração de Jesus (9:2-8)
* Vinda de Elias (9:9-13)
* Jesus cura um menino possesso de demônio (9:14-29)
* Jesus prediz pela segunda vez sua morte e ressurreição (9:30-32)
* Discípulos discutem sobre quem é o maior (9:33-37)
* “Quem não é contra nós é a favor de nós” (9:38-41)
* Pedras de tropeço (9:42-48)
* “Tenham sal em vocês mesmos” (9:49, 50)
****

[[v41-6-1]]

^<<v41-6-1,1>>^ Ele partiu dali e entrou na sua própria cidade, e seus discípulos o seguiram.

[TIP]
====
- *sua própria cidade*: Veja a nota de estudo em Mt 13:54.
====

[[v41-6-2]]

^<<v41-6-2,2>>^ Quando chegou o sábado, ele começou a ensinar na sinagoga, e a maioria dos que o ouviram ficaram maravilhados e disseram: “Onde este homem obteve essas coisas? Por que foi dada essa sabedoria a ele, e por que essas obras poderosas são realizadas pelas suas mãos?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é este o carpinteiro, filho de Maria e irmão de Tiago, José, Judas e Simão? E não estão as suas irmãs aqui conosco?” Assim, começaram a tropeçar por causa dele.

[TIP]
====
- *o carpinteiro*: Jesus era conhecido como “o carpinteiro” e também como “o filho do carpinteiro”. Essas expressões nos dão uma ideia da criação de Jesus e do que ele fez entre sua visita ao templo, aos 12 anos, e o início de seu ministério. (Veja a nota de estudo em Mt 13:55.) Os relatos de Mateus e de Marcos se complementam.
- *filho de Maria*: Este é o único texto que descreve Jesus dessa maneira. Visto que José não é mencionado, é possível que ele já tivesse morrido. O fato de Jesus, quando estava morrendo, ter pedido para João cuidar de Maria também sugere que Maria era viúva. — Jo 19:26, 27.
- *irmão*: Embora a palavra grega usada aqui, adelfós, também seja usada na Bíblia para se referir a irmãos em sentido espiritual, neste contexto ela é usada para se referir aos meios-irmãos de Jesus: os filhos que José e Maria tiveram depois de Jesus. Alguns acreditam que Maria continuou virgem depois de Jesus nascer e afirmam que neste versículo a palavra adelfós se refere a primos. Mas as Escrituras Gregas Cristãs usam outras palavras, não adelfós, para se referir a primos e parentes. Por exemplo, Col 4:10 usa a palavra anepsiós para se referir a um “primo”. E Lu 21:16 usa a palavra syggenés para se referir a parentes (o que pode incluir primos) na mesma lista em que aparece a palavra adelfós (irmão). Esses exemplos mostram que as Escrituras Gregas Cristãs usam palavras específicas para se referir a graus diferentes de parentesco.
- *Tiago*: Veja a nota de estudo em Mt 13:55.
- *Judas*: Veja a nota de estudo em Mt 13:55.
====

[[v41-6-4]]

^<<v41-6-4,4>>^ Mas Jesus lhes disse: “Um profeta não fica sem honra a não ser na sua própria terra, entre os seus parentes e na sua própria casa.”

[[v41-6-5]]

^<<v41-6-5,5>>^ E não pôde fazer nenhuma obra poderosa ali, a não ser pôr as mãos sobre alguns doentes e curá-los.

[TIP]
====
- *não pôde fazer nenhuma obra poderosa ali*: Jesus não pôde fazer muitos milagres ali porque as circunstâncias não eram favoráveis, não por falta de poder. O povo de Nazaré não tinha fé, e isso impediu Jesus de fazer “ali muitas obras poderosas”. (Mt 13:58) Ele não devia desperdiçar o poder divino com pessoas que não queriam acreditar nele nem aceitar sua mensagem. — Veja também Mt 10:14; Lu 16:29-​31.
====

[[v41-6-6]]

^<<v41-6-6,6>>^ Realmente, admirou-se com a sua falta de fé. E percorreu todas as aldeias nas redondezas, ensinando.

[TIP]
====
- *admirou-se com a sua falta de fé*: O Evangelho de Marcos é o único que menciona como Jesus se sentiu por causa da atitude das pessoas de “sua própria terra”. (Mt 13:57, 58; veja também a “Introdução a Marcos”.) O verbo grego traduzido como “admirou-se” muitas vezes é usado para descrever a reação das pessoas aos milagres e aos ensinos de Jesus. (Mr 5:​20; 15:5) Mas ele também é usado para descrever a reação de Jesus em duas ocasiões: quando ele ficou impressionado com a grande fé de um oficial do exército (Mt 8:​10; Lu 7:9) e aqui, quando ele ficou decepcionado com a falta de fé do povo de Nazaré.
- *percorreu todas as aldeias nas redondezas*: Ou: “percorreu as aldeias num circuito”. Esse foi o começo da terceira viagem de pregação de Jesus na Galileia. (Mt 9:​35; Lu 9:1) A expressão grega usada aqui parece indicar que Jesus cobriu completamente aquele território. De acordo com alguns, essa expressão também indica que Jesus terminou sua viagem no mesmo lugar em que tinha começado. Um aspecto importante do ministério de Jesus era ensinar. — Veja a nota de estudo em Mt 4:​23.
====

[[v41-6-7]]

^<<v41-6-7,7>>^ Ele convocou então os Doze e começou a enviá-los de dois em dois, e lhes deu autoridade sobre os espíritos impuros.

[[v41-6-8]]

^<<v41-6-8,8>>^ Também lhes deu ordens para não levarem nada para a viagem, a não ser um bastão — nem pão, nem bolsa de provisões, nem dinheiro^&#42;1^ no cinto —,

[NOTE]
====
. Lit.: “cobre”.
====

[[v41-6-9]]

^<<v41-6-9,9>>^ mas ordenou que eles calçassem sandálias e que não levassem roupa extra.^&#42;1^

[NOTE]
====
. Lit.: “vestissem duas túnicas”.
====

[[v41-6-10]]

^<<v41-6-10,10>>^ Além disso, ele lhes disse: “Em qualquer casa em que entrarem, fiquem ali até saírem daquele lugar.

[TIP]
====
- *fiquem ali até saírem daquele lugar*: Jesus estava dizendo a seus discípulos que, quando chegassem numa cidade, eles deveriam ficar na casa de quem oferecesse hospedagem a eles em vez de ficar “mudando de uma casa para outra”. (Lu 10:​1-7) Eles não deviam ficar procurando uma casa em que o anfitrião pudesse oferecer mais conforto, diversão ou coisas materiais. Assim eles mostrariam que essas coisas eram menos importantes para eles do que o trabalho de pregação.
====

[[v41-6-11]]

^<<v41-6-11,11>>^ E qualquer lugar que não os receber nem os ouvir, ao saírem dali sacudam a poeira que está nos seus pés, em testemunho para eles.”

[TIP]
====
- *sacudam a poeira que está nos seus pés*: É possível que os discípulos já conhecessem esse tipo de gesto. Quando judeus devotos viajavam por outros países, eles sacudiam o pó supostamente impuro de suas sandálias antes de entrar de novo no território dos judeus. Mas o significado da instrução de Jesus era diferente. Ao sacudir o pó de seus pés, os discípulos mostrariam que não eram responsáveis pelo que aconteceria com aquelas pessoas quando fossem julgadas por Deus. Uma expressão parecida é usada em Mt 10:14 e em Lu 9:5. Marcos e Lucas acrescentam as palavras em testemunho para [ou: contra] eles. Paulo e Barnabé seguiram essa instrução em Antioquia da Pisídia (At 13:51), e Paulo fez algo parecido em Corinto, quando sacudiu sua roupa. Nessa ocasião, Paulo explicou seu gesto dizendo: “Que o sangue de vocês recaia sobre a sua própria cabeça. Eu estou limpo.” — At 18:6.
====

[[v41-6-12]]

^<<v41-6-12,12>>^ Assim, partiram e pregaram que as pessoas deveriam se arrepender;

[[v41-6-13]]

^<<v41-6-13,13>>^ eles expulsavam muitos demônios, passavam azeite em muitos doentes e os curavam.

[TIP]
====
- *passavam azeite em muitos doentes*: Os discípulos passavam azeite nos doentes, mas esse ato era apenas simbólico. Embora naquela época o azeite fosse usado para fins medicinais (veja Lu 10:34), os discípulos de Jesus curavam os doentes com o poder milagroso do espírito santo de Deus, não com azeite. — Lu 9:​1, 6.
====

[[v41-6-14]]

^<<v41-6-14,14>>^ E o rei Herodes ouviu falar disso, pois o nome de Jesus havia se tornado bem conhecido, e as pessoas diziam: “João, o Batizador, foi levantado dentre os mortos, e é por isso que ele realiza obras poderosas.”^&#42;1^

[NOTE]
====
. Ou: “que operam nele os milagres”.
====

[TIP]
====
- *rei Herodes*: Ou seja, Herodes Antipas, filho de Herodes, o Grande. (Veja o Glossário.) Mateus e Lucas descrevem Antipas usando o título romano oficial “tetrarca”, ou “governador distrital”. (Veja as notas de estudo em Mt 14:1; Lu 3:1.) Herodes Antipas era governador das regiões da Galileia e da Pereia. Mas as pessoas em geral o chamavam de “rei”. Mateus usa o título “rei” uma vez para se referir a Herodes Antipas (Mt 14:9) e, todas as vezes que Marcos se refere a Herodes com um título, ele o chama de “rei”. — Mr 6:​22, 25, 26, 27.
- *as pessoas diziam*: Lit.: “eles diziam”. Alguns manuscritos dizem: “ele dizia”.
- *o Batizador*: Veja a nota de estudo em Mr 1:4.
====

[[v41-6-15]]

^<<v41-6-15,15>>^ Mas outros diziam: “É Elias.” Ainda outros diziam: “É um profeta semelhante a um dos profetas antigos.”

[[v41-6-16]]

^<<v41-6-16,16>>^ Mas, ao ouvir isso, Herodes disse: “João, aquele que eu decapitei, foi levantado.”

[[v41-6-17]]

^<<v41-6-17,17>>^ De fato, o próprio Herodes anteriormente havia mandado prender João e o havia amarrado na prisão por causa de Herodias, esposa de Filipe, seu irmão, porque tinha se casado com ela.

[TIP]
====
- *havia mandado prender João e o havia amarrado na prisão*: Veja a nota de estudo em Mt 14:3.
- *Herodias, esposa de Filipe, seu irmão*: Veja a nota de estudo em Mt 14:3.
====

[[v41-6-18]]

^<<v41-6-18,18>>^ Pois João dizia a Herodes: “Não é permitido que o senhor tenha a esposa do seu irmão.”

[[v41-6-19]]

^<<v41-6-19,19>>^ Por isso, Herodias nutria ressentimento contra ele e queria matá-lo, mas não podia.

[[v41-6-20]]

^<<v41-6-20,20>>^ Pois Herodes tinha temor de João, sabendo que era homem justo e santo, e o protegia. Sempre que o ouvia, ficava perplexo, sem saber o que fazer; contudo, ouvia-o com prazer.

[TIP]
====
- *sabendo que era homem justo e santo*: Herodes Antipas escutava João e o protegia, reconhecendo que ele era justo e santo. Herodes tinha temor de João, mas seu medo de perder o respeito de seus convidados e sua falta de fé falaram mais alto. Ele permitiu que outros o manipulassem e acabou assassinando João. O historiador judeu Josefo se referiu a João Batista como “um homem bom”.
====

[[v41-6-21]]

^<<v41-6-21,21>>^ Mas chegou um dia conveniente, quando Herodes, no seu aniversário, ofereceu um banquete aos altos funcionários, aos comandantes militares e aos homens mais importantes da Galileia.

[TIP]
====
- *seu aniversário*: A festa foi provavelmente na residência de Herodes Antipas em Tiberíades, cidade que ficava na margem oeste do mar da Galileia. Um motivo para essa conclusão é que Marcos diz aqui que os homens mais importantes da Galileia estavam presentes na ocasião. (Veja as notas de estudo em Mt 14:​3, 6.) A Bíblia só menciona duas festas de aniversário: essa de Herodes, em que João Batista foi decapitado, e a do Faraó do Egito, em que o chefe dos padeiros foi executado. (Gên 40:18-​22) Os relatos têm pontos em comum: nas duas ocasiões houve uma grande festa e nas duas ocasiões uma pessoa foi morta.
- *comandantes militares*: A palavra grega khilíarkhos (quiliarca) significa literalmente “governante de 1.000”, ou seja, comandante de 1.000 soldados. O quiliarca era um tribuno militar romano. Havia seis tribunos em cada legião romana, mas a legião não era dividida em seis grupos. Em vez disso, os seis tribunos se revezavam em comandar a legião inteira. Esses comandantes militares tinham grande autoridade, o que incluía indicar e nomear centuriões. A palavra khilíarkhos também podia se referir de modo geral a oficiais de alta patente. Por estar na presença de homens com tanta autoridade, Herodes se sentiu na obrigação de cumprir seu juramento e por isso mandou decapitar João, o Batizador.
====

[[v41-6-22]]

^<<v41-6-22,22>>^ E a filha de Herodias entrou e dançou, e ela agradou a Herodes e aos que comiam com ele.^&#42;1^ O rei disse à moça: “Peça-me o que quiser, e eu darei a você.”

[NOTE]
====
. Ou: “aos seus convidados para o banquete; aos que estavam recostados à mesa com ele”.
====

[TIP]
====
- *filha de Herodias*: Filha de Herodias com Herodes Filipe (meio-irmão de Herodes Antipas). A Bíblia não diz o nome dela, mas os escritos de Josefo mencionam que ela se chamava Salomé. Enquanto os pais de Salomé ainda estavam casados, sua mãe se envolveu com Herodes Antipas e mais tarde eles se casaram. A mãe de Salomé não teve outros filhos.
====

[[v41-6-23]]

^<<v41-6-23,23>>^ Sim, ele lhe jurou: “O que for que você me pedir, até a metade do meu reino, eu darei a você.”

[[v41-6-24]]

^<<v41-6-24,24>>^ Então ela saiu e perguntou à sua mãe: “O que devo pedir?” Ela respondeu: “A cabeça de João, o Batizador.”

[TIP]
====
- *o Batizador*: Veja a nota de estudo em Mr 1:4.
====

[[v41-6-25]]

^<<v41-6-25,25>>^ Imediatamente, ela correu até o rei e fez o seu pedido, dizendo: “Quero que o senhor me dê sem demora, numa bandeja, a cabeça de João Batista.”

[[v41-6-26]]

^<<v41-6-26,26>>^ Embora isso o entristecesse profundamente, o rei não quis desconsiderar o pedido dela, por causa dos juramentos que tinha feito e por causa dos seus convidados.^&#42;1^

[NOTE]
====
. Ou: “dos que estavam recostados à mesa”.
====

[TIP]
====
- *juramentos que tinha feito*: O uso do plural “juramentos” talvez indique que Herodes reforçou ou confirmou com repetidos juramentos a promessa que tinha feito à filha de Herodias. — Mr 6:​23; veja a nota de estudo em Mt 14:9.
====

[[v41-6-27]]

^<<v41-6-27,27>>^ Assim, o rei enviou imediatamente um soldado da sua guarda com ordens para que trouxesse a cabeça de João. Então ele foi, decapitou-o na prisão

[TIP]
====
- *um soldado da sua guarda*: A palavra grega usada aqui é spekoulátor, que vem da palavra latina speculator. Ela podia se referir a um guarda pessoal, um mensageiro e às vezes a um carrasco. As Escrituras Gregas Cristãs usam cerca de 30 palavras gregas (termos militares, jurídicos, monetários e domésticos) que vêm de palavras latinas, a maioria delas em Marcos e em Mateus. Marcos usa essas palavras mais do que qualquer outro escritor bíblico, o que apoia a opinião de que ele escreveu seu Evangelho em Roma e principalmente para os não judeus, mais especificamente para os romanos. — Veja a nota de estudo em Jo 19:20.
====

[[v41-6-28]]

^<<v41-6-28,28>>^ e trouxe a cabeça numa bandeja. Ele a deu à moça, e a moça a deu à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Quando os discípulos dele ouviram isso, foram pegar o seu corpo e o colocaram num túmulo.

[TIP]
====
- *túmulo*: Ou: “túmulo memorial”. — Veja o Glossário.
====

[[v41-6-30]]

^<<v41-6-30,30>>^ Os apóstolos se reuniram em volta de Jesus e lhe contaram tudo o que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ E ele lhes disse: “Venham comigo, vamos sozinhos a um lugar isolado para descansar um pouco.” Pois havia muitos que iam e vinham, e eles não tinham folga nem para tomar uma refeição.

[[v41-6-32]]

^<<v41-6-32,32>>^ Por isso partiram no barco para um lugar isolado, para ficarem sozinhos.

[[v41-6-33]]

^<<v41-6-33,33>>^ Mas as pessoas os viram partir, e muitos ficaram sabendo disso. E afluíram para lá a pé, de todas as cidades, e chegaram primeiro que eles.

[[v41-6-34]]

^<<v41-6-34,34>>^ Pois bem, ao desembarcar, ele viu uma grande multidão e teve pena deles, porque eram como ovelhas sem pastor. E começou a lhes ensinar muitas coisas.

[TIP]
====
- *teve pena*: Ou: “teve compaixão”. — Veja a nota de estudo em Mt 9:​36.
====

[[v41-6-35]]

^<<v41-6-35,35>>^ Já era tarde, e seus discípulos se aproximaram dele e disseram: “Este lugar é isolado e já é tarde.

[[v41-6-36]]

^<<v41-6-36,36>>^ Dispense-os, para que possam ir à zona rural e às aldeias ao redor comprar algo para comer.”

[[v41-6-37]]

^<<v41-6-37,37>>^ Ele lhes respondeu: “Deem-lhes vocês algo para comer.” Perguntaram-lhe então: “Devemos ir comprar pães no valor de 200 denários, e dá-los às pessoas para comer?”

[TIP]
====
- *Deem-lhes vocês algo para comer*: O milagre de Jesus descrito a seguir é o único que foi registrado por todos os escritores dos Evangelhos. — Mt 14:15-​21; Mr 6:​35-​44; Lu 9:​10-​17; Jo 6:​1-​13.
- *denários*: Veja o Glossário e o Apêndice B14-B.
====

[[v41-6-38]]

^<<v41-6-38,38>>^ Ele lhes disse: “Quantos pães vocês têm? Vão ver!” Depois de verificarem, disseram: “Cinco, além de dois peixes.”

[TIP]
====
- *peixes*: Veja a nota de estudo em Mt 14:17.
====

[[v41-6-39]]

^<<v41-6-39,39>>^ E ele mandou que todos se sentassem em grupos na grama verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ Assim eles se sentaram em grupos de cem e de cinquenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ Pegando então os cinco pães e os dois peixes, ele olhou para o céu e proferiu uma bênção. Depois partiu os pães e começou a dá-los aos discípulos, para que os servissem às pessoas, e repartiu os dois peixes entre todos.

[TIP]
====
- *partiu os pães*: O verbo grego traduzido como “partir” significa literalmente “quebrar”. Naquela época, os pães tinham o formato achatado e eram assados até ficarem duros. Por isso, as pessoas tinham o costume de quebrar o pão para comer. — Mt 14:19; 15:36; 26:26; Mr 8:6; Lu 9:​16.
====

[[v41-6-42]]

^<<v41-6-42,42>>^ Assim, todos comeram e ficaram satisfeitos;

[[v41-6-43]]

^<<v41-6-43,43>>^ e recolheram 12 cestos cheios de pedaços de pão, além das sobras de peixes.

[TIP]
====
- *cestos*: Os cestos mencionados aqui talvez fossem pequenos cestos de vime com uma alça de corda. Esses cestos podiam ser levados em viagens, e acredita-se que tinham a capacidade de aproximadamente 7,5 litros. — Veja as notas de estudo em Mr 8:​19, 20.
====

[[v41-6-44]]

^<<v41-6-44,44>>^ Os que comeram os pães foram 5.000 homens.

[TIP]
====
- *5.000 homens*: Esse é o único milagre de Jesus que foi registrado por todos os escritores dos Evangelhos. (Mt 14:15-​21; Mr 6:​35-​44; Lu 9:​10-​17; Jo 6:​1-​13) É possível que Jesus tenha alimentado de modo milagroso bem mais de 15.000 pessoas, visto que Mateus menciona que havia também mulheres e crianças.
====

[[v41-6-45]]

^<<v41-6-45,45>>^ Então, sem demora, ele mandou os discípulos entrar no barco e partir na frente, para a margem oposta, em direção a Betsaida, enquanto ele mesmo dispensava a multidão.

[[v41-6-46]]

^<<v41-6-46,46>>^ Mas, depois de se despedir deles, foi a um monte para orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ Quando anoiteceu, o barco estava no meio do mar, mas ele estava sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ Então, ao ver que tinham grandes dificuldades para remar por causa do vento contrário, ele se dirigiu a eles por volta da quarta vigília da noite, andando sobre o mar, mas parecia que ele ia passar direto por eles.

[TIP]
====
- *quarta vigília*: Veja a nota de estudo em Mt 14:25.
- *parecia que ele ia*: Lit.: “ele estava inclinado a”. Ou: “ele estava prestes a”. Do ponto de vista dos discípulos, parecia que Jesus ia passar direto por eles.
====

[[v41-6-49]]

^<<v41-6-49,49>>^ Quando o viram andando sobre o mar, pensaram: “É uma aparição!”^&#42;1^ e gritaram,

[NOTE]
====
. Ou: “ilusão”.
====

[[v41-6-50]]

^<<v41-6-50,50>>^ pois todos eles o viram e ficaram assustados. Mas ele lhes disse imediatamente: “Coragem! Sou eu; não tenham medo.”

[[v41-6-51]]

^<<v41-6-51,51>>^ Então subiu no barco com eles, e o vento parou. Em vista disso, ficaram muito espantados,

[[v41-6-52]]

^<<v41-6-52,52>>^ porque não tinham compreendido o significado dos pães; o coração deles continuava fechado ao entendimento.

[TIP]
====
- *não tinham compreendido o significado dos pães*: Poucas horas antes, os discípulos tinham visto Jesus fazer o milagre de multiplicar os pães. Aquele milagre mostrou claramente o grande poder que Jesus tinha recebido por meio do espírito santo. Mas os discípulos não tinham compreendido que, com esse poder, Jesus podia fazer outros milagres impressionantes e ficaram muito espantados ao ver Jesus andar sobre a água e acalmar a tempestade. Quando viram Jesus andando sobre água, eles chegaram a pensar que fosse “uma aparição”, ou seja, algo que não era real, uma ilusão. — Mr 6:​49.
====

[[v41-6-53]]

^<<v41-6-53,53>>^ Quando terminaram a travessia, chegaram a Genesaré e ancoraram o barco ali.

[TIP]
====
- *Genesaré*: Veja a nota de estudo em Mt 14:34.
====

[[v41-6-54]]

^<<v41-6-54,54>>^ Mas, assim que saíram do barco, as pessoas o reconheceram.

[[v41-6-55]]

^<<v41-6-55,55>>^ Elas percorreram toda aquela região e começaram a levar os doentes em macas, para onde ouviam falar que ele estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ E onde quer que ele entrasse — em aldeias, em cidades ou na zona rural —, colocavam os doentes nas praças e lhe imploravam que pudessem tocar pelo menos na borda da sua roupa. E todos os que tocavam nela ficavam bons.^&#42;1^

[NOTE]
====
. Ou: “eram salvos”.
====

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]