include::./index.adoc[]

[[v43-10-0]]
=== As Boas Novas Segundo João, 10
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* I. Da época da Festividade da Dedicação de 32 d.C. a 10 de nisã de 33 d.C. (10:1–12:50)
* Ilustração do pastor e dos apriscos (10:1-18)
* Muitos judeus se recusam a acreditar (10:19-26)
* Jesus e seu Pai estão unidos em cuidar das ovelhas (10:27-30)
* Judeus tentam prender Jesus (10:31-39)
* Muitas pessoas do outro lado do Jordão depositam fé em Jesus (10:40-42)
* Morte de Lázaro (11:1-16)
* Jesus consola Marta e Maria (11:17-37)
* Jesus ressuscita Lázaro (11:38-44)
* Líderes religiosos planejam matar Jesus (11:45-57)
* Maria derrama óleo perfumado nos pés de Jesus (12:1-11)
* Entrada triunfal de Jesus em Jerusalém (12:12-19)
* Jesus prediz que sua morte está próxima (12:20-27)
* Uma voz do céu (12:28)
* Falta de fé dos judeus cumpre profecia (12:29-43)
* Jesus veio salvar o mundo (12:44-50)
****

[[v43-10-1]]

^<<v43-10-1,1>>^ “Digo-lhes com toda a certeza: Quem não entra no aprisco das ovelhas pela porta, mas sobe por outro lugar, é ladrão e saqueador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Mas quem entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ O porteiro abre para ele, e as ovelhas escutam a sua voz. Ele chama por nome as suas ovelhas e as leva para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de retirar todas as suas ovelhas, ele vai à frente delas, e elas o seguem, porque conhecem a sua voz.

[TIP]
====
- *conhecem a sua voz*: Relatos de pessoas que viram pastores no Oriente Médio interagindo com suas ovelhas comprovam que as ovelhas têm a incrível habilidade de diferenciar a voz do seu pastor da voz de outros pastores ou de estranhos. Como Jesus indicou no versículo 3, os pastores davam um nome para cada uma de suas ovelhas, mesmo no caso de rebanhos maiores. (Jo 10:3, 27) As ovelhas se acostumavam desde bem novas com a voz de seu pastor chamando seus nomes enquanto ele as guiava e treinava. Além disso, cada pastor fazia sons específicos que o diferenciavam dos outros pastores. Ele ensinava as ovelhas a obedecer a diferentes comandos de voz. Dessa forma, ficava mais fácil para o pastor proteger as ovelhas de perigos e conduzi-las a boas pastagens e à água. Assim, pode-se dizer que as ovelhas conhecem a voz de seu pastor, não apenas porque conseguem diferenciar a voz dele de outras vozes, mas também porque reconhecem o amor com que ele cuida delas e as protege, individualmente e como rebanho.
====

[[v43-10-5]]

^<<v43-10-5,5>>^ De modo algum seguirão um estranho, mas fugirão dele, porque não conhecem a voz de estranhos.”

[TIP]
====
- *De modo algum seguirão*: Neste versículo, o texto original usa junto com o verbo grego duas palavras que significam “não”, o que era feito para negar algo de modo enfático. A ideia era mostrar que seria impossível que as palavras de Jesus não se cumprissem. Aqui, a palavra estranho se refere a alguém que as ovelhas não conhecem.
====

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus fez essa comparação, mas eles não entenderam o que ele lhes disse.

[TIP]
====
- *comparação*: João é o único escritor dos Evangelhos que usa a palavra grega paroimía. (Jo 10:6; 16:25, 29) O significado dessa palavra é semelhante ao da palavra grega parabolé (“parábola” ou “ilustração”), que é muito usada nos outros Evangelhos, mas não aparece nenhuma vez no Evangelho de João. (Veja a nota de estudo em Mt 13:3.) A palavra paroimía também pode passar a ideia de uma comparação ou analogia. Pedro usou essa mesma palavra para se referir ao “provérbio” sobre o cão que volta ao próprio vômito e a porca que volta a rolar na lama. (2Pe 2:22) Na Septuaginta, paroimía é usada como título do livro de Provérbios.
====

[[v43-10-7]]

^<<v43-10-7,7>>^ Por isso, Jesus disse de novo: “Digo-lhes com toda a certeza: Eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos os que vieram em meu lugar são ladrões e saqueadores; mas as ovelhas não os escutaram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta. Quem entrar por mim será salvo; entrará e sairá, e achará pastagem.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão só vem para furtar, matar e destruir. Eu vim para que tivessem vida, e a tivessem na mais plena medida.

[[v43-10-11]]

^<<v43-10-11,11>>^ Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas.

[TIP]
====
- *bom*: Ou: “excelente”. A palavra grega que aparece aqui é kalós. Ela pode se referir a algo que é bom ou belo por natureza, algo de excelente qualidade. Por exemplo, ela é usada para falar de um “bom fruto”, de um “solo bom” e de “pérolas de boa qualidade”. (Mt 3:10; 13:8, 45) Neste versículo, a palavra foi usada para indicar que Jesus é um pastor excelente, extraordinário.
- *vida*: Ou: “alma”. O significado da palavra grega psykhé, traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, varia de acordo com o contexto. Aqui, ela se refere à vida de Jesus. Por ser o bom pastor, Jesus deu voluntariamente sua vida em favor de suas ovelhas. — Veja o Glossário, “Alma”.
====

[[v43-10-12]]

^<<v43-10-12,12>>^ O empregado, que não é pastor e a quem não pertencem as ovelhas, quando vê o lobo chegando, abandona as ovelhas e foge, e o lobo as ataca e espalha;

[TIP]
====
- *empregado*: As ovelhas são animais vulneráveis, e um rebanho de ovelhas era algo valioso. Assim, muitas vezes quem tomava conta delas era o próprio dono, um de seus filhos ou outro parente. (Gên 29:9; 30:31; 1Sa 16:11) O dono também podia contratar alguém para cuidar das ovelhas. Mas um trabalhador contratado muitas vezes trabalhava pensando apenas em seu salário e não tinha a lealdade ao dono das ovelhas nem a preocupação com elas que um filho ou um parente teriam. (Compare com Jó 7:1, 2.) Nas Escrituras, o trabalho de um pastor é usado para representar o trabalho de cuidar, proteger e alimentar os servos de Deus, que são semelhantes a ovelhas. (Gên 48:15) Os que servem como pastores na congregação cristã não podem ter a atitude de um “empregado”. (Jo 10:13) Em vez disso, eles precisam se esforçar para imitar os exemplos de Jeová, que pastoreia seu povo com carinho (Sal 23:1-6; 80:1; Je 31:10; Ez 34:11-16), e de Jesus, “o bom pastor” que, por amor, se sacrificou por suas ovelhas. — Jo 10:11, 14; At 20:28, 29; 1Pe 5:2-4.
====

[[v43-10-13]]

^<<v43-10-13,13>>^ ele foge porque é um empregado e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor. Conheço as minhas ovelhas, e as minhas ovelhas me conhecem,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece e eu conheço o Pai; e eu dou a minha vida pelas ovelhas.

[TIP]
====
- *vida*: Ou: “alma”. — Veja a nota de estudo em Jo 10:11.
====

[[v43-10-16]]

^<<v43-10-16,16>>^ “E tenho outras ovelhas, que não são desse aprisco; a essas também tenho de trazer, e elas escutarão a minha voz e se tornarão um só rebanho, com um só pastor.

[TIP]
====
- *trazer*: Ou: “conduzir”. O verbo grego usado aqui, ágo, pode significar “trazer” ou “conduzir”, dependendo do contexto. Um manuscrito grego datado de cerca de 200 d.C. usa aqui uma palavra grega relacionada (synágo) que às vezes é traduzida como “reunir”. Jesus é o Bom Pastor e, por isso, reúne, guia, protege e alimenta as ovelhas que são desse aprisco (também chamadas de “pequeno rebanho” em Lu 12:32) e as outras ovelhas. Elas se tornam um só rebanho aos cuidados de um só pastor. Essa comparação destaca a união que existiria entre os seguidores de Jesus.
- *escutarão*: Aqui, a palavra grega traduzida como “escutarão” tem o sentido de “dar atenção, entender e agir de acordo”.
====

[[v43-10-17]]

^<<v43-10-17,17>>^ É por isso que o Pai me ama, porque entrego a minha vida, para que eu possa recebê-la de novo.

[TIP]
====
- *vida*: Ou: “alma”. O significado da palavra grega psykhé, traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, varia de acordo com o contexto. Aqui, ela se refere à vida de Jesus, que ele entregou voluntariamente como sacrifício. — Veja o Glossário, “Alma”.
====

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém a tira de mim, mas eu a entrego de minha própria iniciativa. Tenho o direito^&#42;1^ de entregá-la e tenho o direito^&#42;2^ de recebê-la de novo. Recebi esse mandamento do meu Pai.”

[NOTE]
====
. Lit.: “autoridade”.
. Lit.: “autoridade”.
====

[[v43-10-19]]

^<<v43-10-19,19>>^ Surgiu novamente uma divisão entre os judeus por causa dessas palavras.

[[v43-10-20]]

^<<v43-10-20,20>>^ Muitos deles diziam: “Ele tem demônio e está louco. Por que vocês o escutam?”

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros diziam: “Essas não são declarações de um homem endemoninhado. Será que um demônio pode abrir os olhos de cegos?”

[[v43-10-22]]

^<<v43-10-22,22>>^ Ocorreu então a Festividade da Dedicação em Jerusalém. Era inverno,

[TIP]
====
- *a Festividade da Dedicação*: O nome hebraico desta festividade é Hanuká (hhanukkáh), que significa “inauguração; dedicação”. Ela durava oito dias e começava no dia 25 do mês de quisleu, perto do solstício de inverno. (Veja a nota de estudo em inverno neste versículo e o Apêndice B15.) Essa festividade comemorava a rededicação do templo de Jerusalém, que aconteceu em 165 a.C. O rei sírio Antíoco IV (Epifânio) tinha profanado o templo para demonstrar seu desprezo por Jeová, o Deus dos judeus. Por exemplo, ele construiu um altar em cima do grande altar de Jeová onde as ofertas queimadas eram feitas diariamente. Em 25 de quisleu de 168 a.C., para profanar completamente o templo de Jeová, Antíoco sacrificou porcos no altar e mandou aspergir em todo o templo o caldo feito com a carne deles. Ele queimou os portões do templo, derrubou as salas dos sacerdotes e levou embora o altar de ouro, a mesa dos pães da apresentação e o candelabro de ouro. Depois, ele dedicou o templo de Jeová ao deus pagão Zeus, do Olimpo. Dois anos mais tarde, Judas Macabeu reconquistou a cidade e o templo. O templo foi purificado e, em 25 de quisleu de 165 a.C., foi rededicado. Isso aconteceu exatamente três anos depois de Antíoco ter feito seu sacrifício repugnante a Zeus no altar do templo. Daí, as ofertas queimadas voltaram a ser feitas a Jeová diariamente. Nas Escrituras inspiradas, não há nenhuma declaração direta que indique que Jeová tenha dado a vitória a Judas Macabeu e que o tenha orientado a restaurar o templo. Mas, antes disso, Jeová tinha usado homens de outras nações para realizar a sua vontade em relação à adoração verdadeira, como por exemplo, Ciro, da Pérsia. (Is 45:1) Então é razoável concluir que Jeová pode ter usado um homem do seu povo dedicado para cumprir a sua vontade. As Escrituras mostram que o templo tinha que estar de pé e funcionando para que se cumprissem as profecias sobre o Messias, sobre seu ministério e sobre sua morte sacrificial. Além disso, os sacrifícios especificados na Lei deveriam continuar sendo oferecidos até que o Messias fizesse o maior dos sacrifícios, dar sua vida em favor da humanidade. (Da 9:27; Jo 2:17; He 9:11-14) Os seguidores de Cristo não receberam a ordem de celebrar a Festividade da Dedicação. (Col 2:16, 17) Mas não há registro de que Jesus ou seus discípulos tenham condenado a celebração dessa festividade.
- *inverno*: Este foi o inverno de 32 d.C., o último do ministério de Jesus. A Festividade da Dedicação acontecia no nono mês do calendário judaico, o mês de quisleu (novembro/dezembro). Naquele ano, o dia 25 de quisleu, que era o primeiro dia da festividade, caiu no meio do mês de dezembro. (Veja o Apêndice B15.) Os judeus sabiam que essa festividade acontecia no inverno. Mas João pode ter mencionado esse detalhe para mostrar que o clima influenciou a escolha de Jesus de ensinar no “Pórtico de Salomão” (Jo 10:23), um local do templo protegido do vento leste que soprava no inverno. — Veja o Apêndice B11.
====

[[v43-10-23]]

^<<v43-10-23,23>>^ e Jesus estava andando no templo, no Pórtico^&#42;1^ de Salomão.

[NOTE]
====
. Ou: “na Colunata”.
====

[[v43-10-24]]

^<<v43-10-24,24>>^ Então os judeus o rodearam e lhe disseram: “Por quanto tempo você nos deixará na dúvida? Se você é o Cristo, diga-nos claramente.”

[TIP]
====
- *você nos deixará*: Ou: “você deixará as nossas almas”. O significado da palavra grega psykhé, traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, varia de acordo com o contexto. Em alguns contextos, como acontece aqui, ela é usada como se fosse um pronome pessoal. Outros textos das Escrituras Gregas Cristãs em que a palavra “alma” é usada assim são Mt 12:18 (onde “aprovo” equivale a “minha alma aprova”), Mt 26:38 (onde “estou” equivale a “minha alma está”) e He 10:38 (onde “não me agradarei” equivale a “minha alma não se agradará”). — Veja o Glossário, “Alma”.
====

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus lhes respondeu: “Eu lhes disse, e mesmo assim vocês não acreditam. As obras que eu faço em nome do meu Pai dão testemunho de mim.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vocês não acreditam porque não são minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ Minhas ovelhas escutam a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou vida eterna, e elas jamais serão destruídas, e ninguém as arrancará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ O que o meu Pai me deu é maior do que todas as outras coisas, e ninguém pode arrancá-las da mão do Pai.

[TIP]
====
- *O que o meu Pai me deu é maior do que todas as outras coisas*: Existem pequenas variações na maneira como esta frase aparece nos manuscritos gregos e nas traduções antigas para outros idiomas. A frase que aparece em alguns manuscritos poderia ser traduzida como: “Meu Pai, que as deu a mim, é maior do que todos os outros.” Mas muitos estudiosos consideram que a opção usada aqui no texto principal é provavelmente a original.
====

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.”

[TIP]
====
- *somos um*: Ou: “estamos em união”. Este comentário de Jesus mostra que ele e seu Pai estão unidos em proteger as pessoas semelhantes a ovelhas e em guiá-las para a vida eterna. O Pai e o Filho fazem juntos esse trabalho de pastoreio. Os dois têm a mesma preocupação com as ovelhas e não permitem que ninguém as arranque da mão deles. (Jo 10:27-29; compare com Ez 34:23, 24.) O Evangelho de João menciona muitas vezes o companheirismo e a união de pensamento que existem entre o Pai e o Filho. A palavra grega traduzida aqui como “um” está, não no gênero masculino (indicando “uma pessoa”), mas no gênero neutro (indicando “uma coisa”). Isso apoia a ideia de que Jesus e seu Pai são “um”, não porque sejam a mesma pessoa, mas porque cooperam um com o outro. (Jo 5:19; 14:9, 23) Uma comparação entre as palavras de Jesus aqui no capítulo 10 com a oração dele registrada no capítulo 17 confirma que Jesus estava dizendo que ele e seu Pai estão unidos nos seus objetivos, não que eles são iguais em divindade. (Jo 10:25-29; 17:2, 9-11) Isso fica claro no pedido que Jesus fez a seu Pai sobre seus seguidores: “Que [eles] sejam um, assim como nós somos um.” (Jo 17:11) Dessa forma, pode-se concluir que os capítulos 10 e 17 de João falam do mesmo tipo de união. — Veja as notas de estudo em Jo 17:11, 21; 1Co 3:8.
====

[[v43-10-31]]

^<<v43-10-31,31>>^ Mais uma vez, os judeus apanharam pedras para apedrejá-lo.

[[v43-10-32]]

^<<v43-10-32,32>>^ Então Jesus lhes disse: “Eu lhes mostrei muitas boas obras da parte do Pai. Por qual dessas obras vocês vão me apedrejar?”

[[v43-10-33]]

^<<v43-10-33,33>>^ Os judeus lhe responderam: “Nós não vamos apedrejá-lo por uma boa obra, mas por blasfêmia; pois você, embora seja um homem, se faz um deus.”

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus lhes respondeu: “Não está escrito na sua Lei: ‘Eu disse: “Vocês são deuses”’?

[TIP]
====
- *na sua Lei*: Aqui, a palavra “Lei” se refere às Escrituras Hebraicas como um todo, e não apenas à Lei mosaica. A citação que aparece neste versículo é do Sal 82:6. A palavra “Lei” é usada com esse mesmo sentido em Jo 12:34 e 15:25.
- *deuses*: Ou: “seres divinos”. Jesus estava citando o Sal 82:6, onde a palavra hebraica ʼelohím (deuses) é usada para se referir a humanos que serviam como juízes em Israel. Eles podiam ser chamados de “deuses” no sentido de que eram representantes ou porta-vozes de Deus. Da mesma forma, Jeová disse que Moisés ‘serviria como Deus’ para Arão e para Faraó. — Veja as notas de rodapé em Êx 4:16; 7:1.
====

[[v43-10-35]]

^<<v43-10-35,35>>^ Se aqueles contra^&#42;1^ quem se dirigiu a palavra de Deus foram chamados de ‘deuses’ — e as Escrituras não podem ser anuladas —,

[NOTE]
====
. Ou: “a”.
====

[[v43-10-36]]

^<<v43-10-36,36>>^ vocês dizem a mim,^&#42;1^ a quem o Pai santificou e enviou ao mundo: ‘Você blasfema’, porque eu disse: ‘Sou Filho de Deus’?

[NOTE]
====
. Ou: “vocês dizem daquele”.
====

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras do meu Pai, não acreditem em mim.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se eu as faço, mesmo que não acreditem em mim, acreditem nas obras, para que saibam e acreditem que o Pai está em união comigo e eu em união com o Pai.”

[TIP]
====
- *o Pai está em união comigo e eu em união com o Pai*: Lit.: “o Pai em mim e eu no Pai”. Neste contexto, a preposição grega en indica grande proximidade. Esse uso da preposição en é comum nos escritos do apóstolo João e do apóstolo Paulo. (Gál 1:22; 3:28; Ef 2:13, 15; 6:1) Em 1Jo 3:24 e 4:13, 15, ela foi usada para descrever a relação que existe entre Deus e os cristãos. Outra prova de que aqui a preposição en tem o sentido de “em união com” é o modo como ela foi usada em Jo 17:20-23, onde ela aparece cinco vezes.
====

[[v43-10-39]]

^<<v43-10-39,39>>^ Então mais uma vez tentaram prendê-lo, mas ele escapou.

[[v43-10-40]]

^<<v43-10-40,40>>^ E ele se retirou novamente para o outro lado do Jordão, para o lugar onde João batizava no princípio, e ficou ali.

[[v43-10-41]]

^<<v43-10-41,41>>^ Muitos foram ao encontro dele, e diziam: “João não realizou nenhum sinal, mas todas as coisas que João disse a respeito deste homem eram verdadeiras.”

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali depositaram fé nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]