include::./index.adoc[]

[[v43-20-0]]
=== As Boas Novas Segundo João, 20
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* L. O Cristo aparece depois de ser ressuscitado (20:1–21:25)
* Discípulos encontram túmulo de Jesus vazio (20:1-10)
* Dois anjos e Jesus falam com Maria Madalena (20:11-18)
* Discípulos reunidos com portas trancadas; Jesus aparece a eles (20:19-23)
* Tomé duvida, mas depois se convence (20:24-29)
* João explica o objetivo ‘deste rolo’ (20:30, 31)
* Jesus aparece aos discípulos na Galileia (21:1-14)
* Pedro confirma seu amor por Jesus (21:15-19)
* Jesus prediz o futuro do discípulo amado (21:20-23)
* Observações finais sobre o escritor (21:24, 25)
****

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana, Maria Madalena chegou cedo ao túmulo, enquanto ainda estava escuro, e viu que a pedra já havia sido retirada do túmulo.

[TIP]
====
- *No primeiro dia da semana*: Veja a nota de estudo em Mt 28:1.
- *túmulo*: Ou: “túmulo memorial”. — Veja o Glossário, “Túmulo memorial”.
====

[[v43-20-2]]

^<<v43-20-2,2>>^ Assim, ela foi correndo ao encontro de Simão Pedro e do outro discípulo, a quem Jesus amava, e lhes disse: “Retiraram o Senhor do túmulo, e não sabemos onde o colocaram.”

[TIP]
====
- *do outro discípulo, a quem Jesus amava*: Ou: “do outro discípulo, por quem Jesus tinha afeição”. Ou seja, aquele a quem Jesus amava especialmente. Esta é a terceira das cinco vezes que este Evangelho menciona um discípulo “a quem Jesus amava”. (Jo 13:23; 19:26; 20:2; 21:7, 20) Acredita-se que esse discípulo seja o apóstolo João. (Veja as notas de estudo em Jo 13:23; 18:15.) Em quatro das cinco vezes, a palavra grega traduzida como “amava” é agapáo. Este versículo usa um sinônimo, filéo, que passa a ideia de carinho e afeto e aparece em textos como Mt 10:37; Jo 11:3, 36; 16:27; 21:15-17; 1Co 16:22; Tit 3:15 e Ap 3:19. — Veja as notas de estudo em Jo 5:20; 16:27; 21:15.
====

[[v43-20-3]]

^<<v43-20-3,3>>^ Então, Pedro e o outro discípulo saíram em direção ao túmulo.

[[v43-20-4]]

^<<v43-20-4,4>>^ Os dois começaram a correr juntos, mas o outro discípulo correu mais rápido que Pedro e chegou ao túmulo primeiro.

[[v43-20-5]]

^<<v43-20-5,5>>^ Inclinando-se para a frente, ele viu os panos de linho deixados ali, mas não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Depois Simão Pedro, que o seguia, chegou também, entrou no túmulo e viu os panos de linho deixados ali.

[[v43-20-7]]

^<<v43-20-7,7>>^ O pano que tinha sido posto na cabeça dele não estava mais ali junto com as outras faixas, mas estava enrolado num lugar à parte.

[[v43-20-8]]

^<<v43-20-8,8>>^ Então o outro discípulo, que tinha chegado primeiro ao túmulo, também entrou, viu e acreditou.

[[v43-20-9]]

^<<v43-20-9,9>>^ Porque eles ainda não entendiam a passagem das Escrituras que dizia que ele tinha de ser levantado dentre os mortos.

[TIP]
====
- *a passagem das Escrituras*: A passagem mencionada aqui é provavelmente o Sal 16:10 ou Is 53:10. Nem mesmo os discípulos de Jesus entendiam algumas das profecias sobre o Messias, especialmente as que tinham a ver com ele ser rejeitado, sofrer, morrer e ser ressuscitado. — Is 53:3, 5, 12; Mt 16:21-23; 17:22, 23; Lu 24:21; Jo 12:34.
====

[[v43-20-10]]

^<<v43-20-10,10>>^ Assim, os discípulos voltaram para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria, porém, ficou chorando do lado de fora, perto do túmulo. Enquanto chorava, ela se inclinou para a frente a fim de olhar para dentro do túmulo

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos de branco sentados no lugar onde o corpo de Jesus tinha sido colocado, um à cabeceira e outro aos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ Eles perguntaram a ela: “Mulher, por que está chorando?” Ela lhes respondeu: “Levaram embora o meu Senhor, e não sei onde o colocaram.”

[[v43-20-14]]

^<<v43-20-14,14>>^ Depois de dizer isso, ela se virou e viu Jesus em pé ali, mas não percebeu que era Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Jesus lhe perguntou: “Mulher, por que está chorando? Quem você está procurando?” Pensando que fosse o jardineiro, ela lhe disse: “Se o senhor o tirou daqui, diga-me onde o colocou, e eu o levarei embora.”

[[v43-20-16]]

^<<v43-20-16,16>>^ Jesus lhe disse: “Maria!” Voltando-se para ele, ela disse em hebraico: “Rabôni!” (que significa: “Instrutor!”).

[TIP]
====
- *hebraico*: Veja a nota de estudo em Jo 5:2.
- *Rabôni!*: Palavra semítica que significa “meu instrutor”. É possível que a palavra “Rabôni” originalmente fosse considerada mais respeitosa ou carinhosa do que sua forma mais simples, “Rabi”. Mas, aqui e em Jo 1:38, João disse que essas duas palavras significavam simplesmente instrutor. Pode ser que, quando João escreveu seu Evangelho, o significado especial da forma “Rabôni” já tivesse se perdido.
====

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus lhe disse: “Pare de me segurar, porque ainda não subi para o Pai. Mas vá aos meus irmãos e diga-lhes: ‘Eu vou subir para o meu Pai e Pai de vocês, para o meu Deus e Deus de vocês.’”

[TIP]
====
- *Pare de me segurar*: O verbo grego que aparece aqui, háptomai, pode ter o sentido de “tocar” ou de “segurar; agarrar”. Algumas Bíblias traduzem as palavras de Jesus como: “Não me toque.” Mas Jesus não estava proibindo Maria de tocar nele, senão ele teria feito o mesmo com as mulheres que “abraçaram os pés dele” quando viram que tinha sido ressuscitado. (Mt 28:9) Tudo indica que Maria Madalena achava que Jesus estava prestes a subir ao céu. Ela queria tanto continuar na companhia do Senhor Jesus que tentou impedir que ele partisse. Jesus pediu a Maria que parasse de segurá-lo e que, em vez disso, fosse contar aos discípulos que ele tinha sido ressuscitado. Assim, ele mostrou a Maria que ele ainda não estava indo para o céu.
- *o meu Deus e Deus de vocês*: Esta conversa entre Jesus e Maria Madalena, no dia 16 de nisã de 33 d.C., mostra que Jesus continuava considerando o Pai como o seu Deus, assim como Maria Madalena considerava o Pai como o Deus dela. Dois dias antes, quando estava na estaca de tortura, Jesus se dirigiu a seu Pai com as palavras: “Deus meu, Deus meu.” Ao fazer isso, ele cumpriu o Sal 22:1 e reconheceu que o Pai era o seu Deus. (Mt 27:46; Mr 15:34; Lu 23:46) Em Ap 3:2, 12, Jesus também chama o Pai de “meu Deus”. Esses relatos mostram que, mesmo depois de ressuscitado e glorificado, Jesus continua adorando ao Pai como seu Deus, assim como os discípulos dele fazem.
====

[[v43-20-18]]

^<<v43-20-18,18>>^ Maria Madalena foi e levou a notícia aos discípulos: “Eu vi o Senhor!” E contou a eles o que ele tinha lhe dito.

[[v43-20-19]]

^<<v43-20-19,19>>^ Já era tarde naquele dia, o primeiro dia da semana, e as portas do lugar onde os discípulos se encontravam estavam trancadas, por medo dos judeus. Jesus apareceu então no meio deles e lhes disse: “Que a paz esteja com vocês.”

[TIP]
====
- *dos judeus*: Aqui, a palavra “judeus” pelo visto se refere às autoridades judaicas, os líderes religiosos dos judeus. — Veja a nota de estudo em Jo 7:1.
====

[[v43-20-20]]

^<<v43-20-20,20>>^ Depois de dizer isso, ele lhes mostrou suas mãos e o seu lado. Então os discípulos se alegraram ao ver o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Jesus lhes disse novamente: “Que a paz esteja com vocês. Assim como o Pai me enviou, eu também os envio.”

[[v43-20-22]]

^<<v43-20-22,22>>^ Depois de dizer isso, soprou sobre eles e lhes disse: “Recebam espírito santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se vocês perdoarem os pecados de alguém, eles estão perdoados; se não perdoarem os pecados de alguém, eles não estão perdoados.”

[[v43-20-24]]

^<<v43-20-24,24>>^ Mas Tomé, um dos Doze, que era chamado Gêmeo, não estava com eles quando Jesus apareceu.

[TIP]
====
- *Gêmeo*: Veja a nota de estudo em Jo 11:16.
====

[[v43-20-25]]

^<<v43-20-25,25>>^ Então os outros discípulos lhe disseram: “Nós vimos o Senhor!” Mas ele lhes disse: “Se eu não vir nas mãos dele a marca dos pregos, não colocar o dedo na marca dos pregos e não colocar a mão no lado dele, de modo algum acreditarei.”

[[v43-20-26]]

^<<v43-20-26,26>>^ Oito dias depois, seus discípulos estavam novamente reunidos, e Tomé estava com eles. Embora as portas estivessem trancadas, Jesus apareceu no meio deles e disse: “Que a paz esteja com vocês.”

[[v43-20-27]]

^<<v43-20-27,27>>^ Depois, disse a Tomé: “Coloque o dedo aqui e veja as minhas mãos; estenda a mão e coloque-a no meu lado. Pare de duvidar^&#42;1^ e acredite.”

[NOTE]
====
. Lit.: “ser incrédulo”.
====

[[v43-20-28]]

^<<v43-20-28,28>>^ Em resposta Tomé lhe disse: “Meu Senhor e meu Deus!”

[TIP]
====
- *Meu Senhor e meu Deus!*: Lit.: “O Senhor de mim e o Deus [ho theós] de mim!” Alguns estudiosos acreditam que, embora estas palavras de espanto de Tomé tenham sido ditas a Jesus, elas se dirigiam a Deus, o Pai. Outros dizem que o texto grego não abre essa possibilidade e que essas palavras se dirigiam ao próprio Jesus. Mesmo que isso seja verdade, o sentido da expressão “meu Senhor e meu Deus” precisa estar de acordo com o restante das Escrituras inspiradas. O relato mostra que, antes disso, Jesus tinha enviado a seus discípulos a mensagem: “Eu vou subir para o meu Pai e Pai de vocês, para o meu Deus e Deus de vocês.” Assim, não existe motivo para acreditar que Tomé achasse que Jesus era o Deus Todo-Poderoso. (Veja a nota de estudo em Jo 20:17.) Além disso, Tomé tinha ouvido Jesus orar ao “Pai” e chamá-lo de “o único Deus verdadeiro”. (Jo 17:1-3) Levando isso em conta, Tomé pode ter chamado Jesus de “meu Deus” por um dos seguintes motivos: Ele acreditava que Jesus era “um deus”, mas não o Deus Todo-Poderoso. (Veja a nota de estudo em Jo 1:1.) Ou Tomé pode ter imitado o modo como alguns servos fiéis do passado tinham se dirigido a anjos que estavam representando a Deus, conforme registrado nas Escrituras Hebraicas. Tomé com certeza conhecia relatos em que o próprio escritor do livro bíblico, ou outra pessoa, se dirigia a um anjo enviado por Deus como se o anjo fosse o próprio Jeová Deus. (Compare com Gên 16:7-11, 13; 18:1-5, 22-33; 32:24-30; Jz 6:11-15; 13:20-22.) Dessa forma, Tomé pode ter chamado Jesus de “meu Deus” porque reconhecia que Jesus era o representante ou porta-voz do verdadeiro Deus.
- *No texto grego, o artigo definido aparece antes das palavras “senhor” e “deus”, e alguns dizem que isso indica que essas palavras se referem ao Deus Todo-Poderoso. Mas, neste contexto, o artigo definido pode ter sido usado apenas para deixar essas palavras no vocativo, uma forma usada para chamar uma pessoa ou dirigir a palavra a ela. Alguns exemplos de textos em que uma pessoa se dirige a alguém dessa forma são Lu 12*:32 (onde no texto grego o artigo definido aparece antes de “pequeno rebanho”) e Col 3:18–4:1 (onde no texto grego o artigo definido aparece antes de “esposa”, “marido”, “filhos”, “pais”, “escravos” e “senhores”). De modo parecido, no texto grego de 1Pe 3:7, o artigo definido aparece antes da palavra “marido” (lit.: “os maridos”). Assim, o uso do artigo definido talvez não seja suficiente para determinar o que Tomé queria dizer com essas palavras.
====

[[v43-20-29]]

^<<v43-20-29,29>>^ Jesus lhe disse: “Você acreditou porque me viu? Felizes os que não viram, mas mesmo assim acreditam.”

[[v43-20-30]]

^<<v43-20-30,30>>^ Certamente, Jesus realizou muitos outros sinais diante dos discípulos, os quais não estão escritos neste rolo.

[[v43-20-31]]

^<<v43-20-31,31>>^ Mas estes foram escritos para que vocês creiam que Jesus é o Cristo, o Filho de Deus, e para que, por crerem, tenham vida por meio do nome dele.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]