include::./index.adoc[]

[[v43-16-0]]
=== As Boas Novas Segundo João, 16
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* J. Última Páscoa de Jesus e últimos conselhos para seus discípulos (13:1–17:26)
* Jesus lava os pés dos discípulos (13:1-20)
* Jesus identifica seu traidor: Judas Iscariotes (13:21-30)
* Jesus dá um novo mandamento (13:31-35)
* Jesus prediz que Pedro vai negá-lo três vezes (13:36-38)
* Jesus é o único caminho para se chegar ao Pai (14:1-14)
* Jesus promete que o espírito santo virá como ajudador (14:15-31)
* Ilustração da verdadeira videira (15:1-10)
* Mandamento para amar como Cristo amou (15:11-17)
* Mundo odeia Jesus e seus discípulos (15:18-27)
* Alguns discípulos de Jesus serão mortos (16:1-4a)
* Jesus enviará o espírito santo (16:4b-16)
* Tristeza dos discípulos será transformada em alegria (16:17-24)
* Jesus vence o mundo (16:25-33)
* Jesus ora em favor de todos os seus discípulos, presentes e futuros (17:1-26)
****

[[v43-16-1]]

^<<v43-16-1,1>>^ “Eu lhes disse essas coisas para que vocês não tropecem.

[[v43-16-2]]

^<<v43-16-2,2>>^ Os homens os expulsarão da sinagoga. De fato, vem a hora em que quem matar vocês pensará que está prestando um serviço sagrado a Deus.

[TIP]
====
- *os expulsarão da sinagoga*: Ou: “os excomungarão; os banirão da sinagoga”. A palavra grega aposynágogos (lit.: “fora da sinagoga”) aparece apenas três vezes nas Escrituras: em Jo 9:22, em Jo 12:42 e aqui neste versículo. Uma pessoa que fosse expulsa da sinagoga seria desprezada e excluída do convívio social com outros judeus, e isso também poderia trazer graves problemas financeiros para a família. O principal objetivo das sinagogas era instruir. Mas, pelo visto, elas também serviam como tribunais locais que tinham a autoridade de aplicar punições, como açoitamento e excomunhão (expulsar alguém de uma comunidade religiosa). (Veja a nota de estudo em Mt 10:17.) As palavras de Jesus neste versículo eram um alerta sobre o que poderia acontecer com quem decidisse segui-lo. Jesus já tinha falado que o mundo odiaria seus seguidores, mas essa foi a primeira vez que ele disse que alguns deles chegariam a ser mortos.
- *um serviço sagrado*: O substantivo grego usado aqui, latreía, se refere a um ato de adoração. Nas Escrituras Gregas Cristãs, esse substantivo é sempre usado com referência a serviço prestado a Deus. — Ro 9:4; 12:1; He 9:1, 6; para uma explicação sobre o verbo grego relacionado, latreúo, veja a nota de estudo em Lu 1:74.
====

[[v43-16-3]]

^<<v43-16-3,3>>^ Mas eles farão isso porque não conhecem nem ao Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Contudo, eu lhes disse essas coisas para que, quando chegar a hora de acontecerem, vocês se lembrem de que lhes falei delas.
“Eu não lhes disse essas coisas no princípio porque eu estava com vocês.

[[v43-16-5]]

^<<v43-16-5,5>>^ Mas agora vou para Aquele que me enviou; mesmo assim, nenhum de vocês me pergunta: ‘Para onde o senhor vai?’

[[v43-16-6]]

^<<v43-16-6,6>>^ Pelo contrário, o coração de vocês está cheio de tristeza porque eu lhes disse essas coisas.

[[v43-16-7]]

^<<v43-16-7,7>>^ Contudo, eu lhes digo a verdade: É em seu benefício que vou embora. Pois, se eu não for embora, o ajudador não virá a vocês; mas, se eu for, o enviarei a vocês.

[TIP]
====
- *ajudador*: Veja a nota de estudo em Jo 14:16.
====

[[v43-16-8]]

^<<v43-16-8,8>>^ E, quando ele vier, dará ao mundo provas convincentes do pecado, da justiça e do julgamento:

[TIP]
====
- *ele*: Aqui, a palavra “ele” se refere ao “ajudador”, mencionado no versículo anterior. (Veja a nota de estudo em Jo 16:13.) Ao chamar o espírito santo de “ajudador”, Jesus usou uma figura de linguagem chamada personificação, que envolve falar de algo sem vida ou de um objeto como se fossem uma pessoa. Apesar de o espírito santo ser uma força, e não uma pessoa, Jesus falou que o ajudador iria ‘ensinar’, ‘dar testemunho’, ‘dar provas’, ‘guiar’, ‘falar’, ‘ouvir’ e ‘receber’. (Jo 14:26; 15:26; 16:7-15) O espírito daria ao mundo provas convincentes do pecado porque tornaria evidente que o mundo não tinha fé no Filho de Deus. O espírito também daria provas convincentes da justiça porque o fato de Jesus ir para o céu provaria que ele era visto por Deus como justo. Além disso, o espírito mostraria por que o julgamento recebido por Satanás, “o governante deste mundo”, é merecido. (Jo 16:9-11) A palavra grega traduzida aqui como “dará . . . provas convincentes” é elégkho, que também é traduzida como “repreender”. — 1Ti 5:20; Tit 1:9.
====

[[v43-16-9]]

^<<v43-16-9,9>>^ primeiro, do pecado, porque eles não exercem fé em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ depois, da justiça, porque vou para o Pai e vocês não me verão mais;

[[v43-16-11]]

^<<v43-16-11,11>>^ então, do julgamento, porque o governante deste mundo foi julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ “Ainda tenho muitas coisas para lhes dizer, mas agora vocês não são capazes de suportá-las.

[[v43-16-13]]

^<<v43-16-13,13>>^ No entanto, quando ele vier, o espírito da verdade, ele os guiará a toda a verdade, pois não falará de sua própria iniciativa, mas falará o que ouvir e declarará a vocês as coisas que virão.

[TIP]
====
- *ele*: Nos versículos 13 e 14, a palavra “ele” se refere ao “ajudador” mencionado em Jo 16:7. Jesus usou a expressão “o ajudador” para se referir ao “espírito santo”, que é uma força, não uma pessoa. Em grego, a palavra para “ajudador” é do gênero masculino, mas a palavra para “espírito santo” é do gênero neutro. — Veja a nota de estudo em Jo 14:16.
====

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele me glorificará, porque receberá do que é meu e o declarará a vocês.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo que o Pai tem é meu. É por isso que eu disse que ele receberá do que é meu e o declarará a vocês.

[[v43-16-16]]

^<<v43-16-16,16>>^ Em breve vocês não me verão mais; e também em breve vocês me verão.”

[[v43-16-17]]

^<<v43-16-17,17>>^ Em vista disso, alguns dos seus discípulos disseram uns aos outros: “O que ele quer dizer com: ‘Em breve vocês não me verão; e também em breve vocês me verão’ e ‘porque vou para o Pai’?”

[[v43-16-18]]

^<<v43-16-18,18>>^ Eles diziam: “O que ele quer dizer com: ‘Em breve’? Não sabemos do que ele está falando.”

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus sabia que eles queriam lhe fazer perguntas, de modo que lhes disse: “Vocês estão perguntando uns aos outros o que eu quis dizer quando falei: ‘Em breve vocês não me verão; e também em breve vocês me verão’?

[[v43-16-20]]

^<<v43-16-20,20>>^ Digo-lhes com toda a certeza: Vocês chorarão e lamentarão, mas o mundo se alegrará; vocês ficarão tristes, mas a sua tristeza será transformada em alegria.

[TIP]
====
- *o mundo*: A palavra grega usada aqui é kósmos. Neste contexto, ela se refere à sociedade humana injusta afastada de Deus, ou seja, a todas as pessoas que não servem a Deus. — Compare com a nota de estudo em Jo 15:19.
====

[[v43-16-21]]

^<<v43-16-21,21>>^ Quando uma mulher está dando à luz, ela sofre porque chegou a sua hora; mas, quando nasce o seu bebê, ela não se lembra mais da aflição, por causa da alegria de um ser humano ter vindo ao mundo.

[TIP]
====
- *vindo ao mundo*: Jesus usou o nascimento de um bebê para ilustrar como lágrimas e sofrimento poderiam ser ‘transformados em alegria’. (Jo 16:20) Ao dar à luz, a mulher passa por muitas dores. Mas, quando o filho nasce, a alegria que ela sente é tão grande que a faz esquecer a dor que sentiu. Neste contexto, a palavra “mundo” (em grego, kósmos) se refere à sociedade humana organizada, onde o bebê passa a viver. Na Bíblia, a palavra “mundo” às vezes tem esse sentido. — 1Co 14:10; 1Ti 6:7; veja a nota de estudo em Lu 9:25.
====

[[v43-16-22]]

^<<v43-16-22,22>>^ Do mesmo modo, agora vocês estão tristes; mas eu os verei novamente, e o seu coração se alegrará, e ninguém tirará a sua alegria.

[[v43-16-23]]

^<<v43-16-23,23>>^ Naquele dia vocês não me farão absolutamente nenhuma pergunta. Digo-lhes com toda a certeza: Se pedirem ao Pai qualquer coisa em meu nome, ele a dará a vocês.

[TIP]
====
- *qualquer coisa*: Além dos assuntos que Jesus mencionou na oração-modelo (Mt 6:9-13), as Escrituras falam sobre muitas outras coisas que afetam a vida dos servos de Deus e que podem ser incluídas em suas orações. Isso mostra que as orações pessoais podem incluir praticamente qualquer assunto. — Fil 4:6; 1Pe 5:7; 1Jo 5:14.
====

[[v43-16-24]]

^<<v43-16-24,24>>^ Até agora vocês não pediram nem uma única coisa em meu nome. Peçam e receberão, para que a sua alegria seja completa.

[[v43-16-25]]

^<<v43-16-25,25>>^ “Eu lhes disse essas coisas usando comparações. Vem a hora em que não lhes falarei mais usando comparações, mas eu lhes falarei claramente a respeito do Pai.

[TIP]
====
- *comparações*: Ou: “figuras de linguagem; linguagem figurada”. — Veja a nota de estudo em Jo 10:6.
====

[[v43-16-26]]

^<<v43-16-26,26>>^ Naquele dia vocês pedirão ao Pai em meu nome. Não quero dizer com isso que pedirei por vocês.

[[v43-16-27]]

^<<v43-16-27,27>>^ Pois o próprio Pai ama vocês, porque vocês me amam e acreditam que vim como representante de Deus.

[TIP]
====
- *ama vocês*: Ou: “tem afeição por vocês”. O verbo grego filéo pode ser traduzido como “ter afeição”, “amar”, “gostar” e “beijar”. (Jo 12:25; Mt 23:6; Mr 14:44) Esse verbo muitas vezes descreve um forte apego, do tipo que verdadeiros amigos têm um pelo outro. Quando Jesus estava a caminho do túmulo de Lázaro e “começou a chorar”, as pessoas disseram: “Vejam como ele o amava [uma forma do verbo filéo]!” (Jo 11:35, 36) Esse verbo também é usado para descrever o relacionamento achegado que costuma existir entre pais e filhos. (Mt 10:37) Além disso, como mostra este versículo, filéo é usado para falar do forte apego que Jeová tem por cada um dos seguidores de seu Filho e também para falar dos sentimentos que esses seguidores têm pelo Filho de Deus. Em Jo 5:20, esse mesmo verbo é usado para descrever o forte apego que o Pai tem pelo Filho.
====

[[v43-16-28]]

^<<v43-16-28,28>>^ Vim como representante do Pai e entrei no mundo. Agora, deixo o mundo e vou para o Pai.”

[[v43-16-29]]

^<<v43-16-29,29>>^ Seus discípulos disseram: “Agora, sim, o senhor está falando claramente e não está fazendo comparações.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora sabemos que o senhor sabe todas as coisas e não precisa que lhe façam perguntas. Por isso acreditamos que o senhor veio de Deus.”

[[v43-16-31]]

^<<v43-16-31,31>>^ Jesus lhes respondeu: “Agora vocês acreditam?

[[v43-16-32]]

^<<v43-16-32,32>>^ Escutem: Vem a hora — realmente já veio — em que vocês serão espalhados, cada um para a sua própria casa, e me deixarão sozinho. Mas eu não estou sozinho, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Eu lhes disse essas coisas para que, por meio de mim, vocês tenham paz. No mundo vocês terão tribulação, mas coragem! Eu venci o mundo.”

[TIP]
====
- *por meio de mim*: Ou: “em união comigo”. A preposição grega en (traduzida aqui como “por meio de”) pode se referir a um meio para atingir um objetivo (“por meio de”) ou a uma relação de grande proximidade e união (“em união com”). — Veja a nota de estudo em Jo 10:38.
- *Eu venci o mundo*: Neste contexto, a palavra grega kósmos (“mundo”) se refere à sociedade humana injusta afastada de Deus, ou seja, a todas as pessoas que não servem a Deus. Ela foi usada com um sentido parecido em Jo 12:31; 15:19; 2Pe 2:5; 3:6; 1Jo 2:15-17 e 5:19. As Escrituras deixam claro qual é a vontade de Deus. Mas, em geral, as pessoas desse “mundo” pensam e agem de uma maneira que vai contra a vontade dele. (1Jo 2:16) Na sua última noite antes de morrer, Jesus pôde dizer: “Eu venci o mundo.” Ele venceu o mundo porque não se tornou como o mundo; ele não permitiu que os pensamentos e as ações das pessoas do mundo tivessem qualquer influência sobre ele. A fé, a lealdade e a integridade de Jesus provaram que “o governante do mundo”, Satanás, não tinha “nenhum poder” sobre ele. (Veja a nota de estudo em Jo 14:30.) Na oração de Jesus registrada em Jo 17, ele disse que nem ele nem seus discípulos faziam parte do mundo. (Jo 17:15, 16) E, quando estava sendo julgado pelo governante romano Pilatos, Jesus lhe disse: “Meu Reino não faz parte deste mundo.” (Jo 18:36) Mais de 60 anos depois do julgamento de Jesus, o apóstolo João foi inspirado a escrever: “Esta é a vitória que venceu o mundo: a nossa fé.” — 1Jo 5:4, 5.
====

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]