include::./index.adoc[]

[[v43-13-0]]
=== As Boas Novas Segundo João, 13
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* J. Última Páscoa de Jesus e últimos conselhos para seus discípulos (13:1–17:26)
* Jesus lava os pés dos discípulos (13:1-20)
* Jesus identifica seu traidor: Judas Iscariotes (13:21-30)
* Jesus dá um novo mandamento (13:31-35)
* Jesus prediz que Pedro vai negá-lo três vezes (13:36-38)
* Jesus é o único caminho para se chegar ao Pai (14:1-14)
* Jesus promete que o espírito santo virá como ajudador (14:15-31)
* Ilustração da verdadeira videira (15:1-10)
* Mandamento para amar como Cristo amou (15:11-17)
* Mundo odeia Jesus e seus discípulos (15:18-27)
* Alguns discípulos de Jesus serão mortos (16:1-4a)
* Jesus enviará o espírito santo (16:4b-16)
* Tristeza dos discípulos será transformada em alegria (16:17-24)
* Jesus vence o mundo (16:25-33)
* Jesus ora em favor de todos os seus discípulos, presentes e futuros (17:1-26)
****

[[v43-13-1]]

^<<v43-13-1,1>>^ Jesus sabia, antes da Festividade da Páscoa, que havia chegado a hora de deixar este mundo e ir para o Pai. Assim, tendo amado os seus que estavam no mundo, ele os amou até o fim.

[TIP]
====
- *da Festividade da Páscoa*: Ou seja, a Páscoa de 33 d.C. — Veja a nota de estudo em Jo 2:13.
- *tendo amado*: A partir deste capítulo, o amor se torna um dos temas principais do Evangelho de João. Nos primeiros 12 capítulos de João, o verbo grego agapáo (amar) e o substantivo grego agápe (amor) aparecem um total de oito vezes. Mas, nos capítulos 13 a 21, eles aparecem um total de 36 vezes. Na verdade, em nenhuma outra parte da Bíblia o amor que Jesus tem por seu Pai e por seus discípulos recebe mais destaque. Por exemplo, apesar de todos os Evangelhos falarem sobre o amor que Jesus tem por Jeová, apenas Jo 14:31 menciona que Jesus disse especificamente: “Eu amo o Pai.” João relatou também que, quando Jesus deu seus últimos conselhos a seus discípulos antes de morrer, ele não apenas disse que Jeová o amava, mas também explicou por quê. — Jo 15:9, 10.
- *os amou até o fim*: A expressão grega que aparece aqui provavelmente se refere ao fim da vida de Jesus como humano. Mas outros entendem que neste contexto ela signifique “os amou completamente; os amou continuamente”.
====

[[v43-13-2]]

^<<v43-13-2,2>>^ Eles estavam tomando a refeição,^&#42;1^ e o Diabo já tinha posto no coração de Judas Iscariotes, filho de Simão, que o traísse.

[NOTE]
====
. Ou, possivelmente: “A refeição estava sendo preparada”.
====

[TIP]
====
- *a refeição*: Ou: “a ceia”, referindo-se à Páscoa.
====

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus sabia que o Pai tinha entregado todas as coisas nas suas mãos e que tinha vindo de Deus e estava indo para Deus;

[[v43-13-4]]

^<<v43-13-4,4>>^ assim, ele se levantou da mesa e tirou a sua capa.^&#42;1^ Pegou então uma toalha e a amarrou na cintura.

[NOTE]
====
. Ou: “as suas roupas exteriores”.
====

[TIP]
====
- *a amarrou na cintura*: Ou: “cingiu-se”. Lavar e secar os pés de alguém era um serviço humilde, geralmente feito por um escravo. (Jo 13:12-17) Ao fazer isso, Jesus ensinou de forma marcante aos seus discípulos qual é a atitude que Jeová espera de seus servos. Pedro, que estava presente nessa ocasião, pode ter se lembrado desse dia quando mais tarde aconselhou seus irmãos: “Todos vocês, porém, revistam-se [ou: “cinjam-se”] de humildade.” — 1Pe 5:5, nota de rodapé.
====

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois, colocou água numa bacia e começou a lavar os pés dos discípulos e a enxugá-los com a toalha que tinha na cintura.

[TIP]
====
- *lavar os pés dos discípulos*: No Israel antigo, as sandálias eram o tipo de calçado mais comum. Elas eram basicamente uma sola presa ao pé e ao tornozelo por tiras de couro, e por isso os viajantes acabavam sujando seus pés com a lama ou a poeira das ruas e dos campos. Por causa disso, as pessoas tinham o costume de tirar as sandálias ao entrar numa casa, e um anfitrião hospitaleiro providenciaria que os pés dos visitantes fossem lavados. A Bíblia menciona várias vezes esse costume. (Gên 18:4, 5; 24:32; 1Sa 25:41; Lu 7:37, 38, 44) Quando Jesus lavou os pés dos discípulos, ele aproveitou esse costume para mostrar na prática o que significa ser humilde e servir outros.
- *que tinha na cintura*: Ou: “com a qual estava cingido”. — Veja a nota de estudo em Jo 13:4.
====

[[v43-13-6]]

^<<v43-13-6,6>>^ Então chegou a Simão Pedro. Este lhe disse: “Senhor, vai lavar os meus pés?”

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus lhe respondeu: “O que estou fazendo, você não entende agora, mas entenderá depois dessas coisas.”

[[v43-13-8]]

^<<v43-13-8,8>>^ Pedro lhe disse: “O senhor nunca lavará os meus pés.” Jesus disse então: “Se eu não lavar você, você não tem parte comigo.”

[[v43-13-9]]

^<<v43-13-9,9>>^ Simão Pedro lhe respondeu: “Senhor, então lave não só os meus pés, mas também as minhas mãos e a minha cabeça.”

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus lhe disse: “Quem se banhou está completamente limpo e não precisa lavar nada, só os pés. E vocês estão limpos, mas nem todos.”

[TIP]
====
- *vocês estão limpos*: Em sentido literal, os apóstolos estavam completamente limpos depois que seus pés foram lavados pelo seu Senhor. Mas, em sentido espiritual, um deles não estava limpo. Assim como os fariseus, que figurativamente limpavam o copo e o prato por fora, mas deixavam a parte de dentro suja, Judas Iscariotes estava limpo por fora, mas estava sujo em sentido espiritual. — Mt 23:25, 26.
====

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem o estava traindo. É por isso que disse: “Nem todos vocês estão limpos.”

[TIP]
====
- *ele sabia*: Jesus conseguia saber o que as pessoas estavam pensando e percebia suas intenções. Assim, fica claro que, quando Judas foi escolhido para ser um apóstolo, ele ainda não tinha desenvolvido as características ruins que o levaram a trair Jesus. (Mt 9:4; Mr 2:8; Jo 2:24, 25) Mas, quando Judas mais tarde começou a mudar, Jesus viu que isso estava acontecendo e soube que Judas iria traí-lo. Mesmo sabendo o que Judas faria, Jesus lavou os pés de seu traidor. — Veja as notas de estudo em Jo 6:64, 70.
====

[[v43-13-12]]

^<<v43-13-12,12>>^ Então, depois de lavar os pés deles e pôr a sua capa,^&#42;1^ ele se recostou novamente à mesa e lhes disse: “Vocês entendem o que eu lhes fiz?

[NOTE]
====
. Ou: “as suas roupas exteriores”.
====

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês me chamam de ‘Instrutor’ e ‘Senhor’, e estão certos, pois eu sou mesmo.

[[v43-13-14]]

^<<v43-13-14,14>>^ Portanto, se eu, o Senhor e Instrutor, lavei os seus pés, vocês também devem lavar os pés uns dos outros.

[TIP]
====
- *devem*: Ou: “têm a obrigação de”. O verbo grego traduzido aqui como “devem” é muitas vezes usado em contextos financeiros, com o sentido básico de “estar em dívida com alguém; dever algo a alguém”. (Mt 18:28, 30, 34; Lu 16:5, 7) Aqui e em outros contextos, ele é usado com o sentido mais amplo de ter a obrigação de fazer alguma coisa. — 1Jo 3:16; 4:11; 3Jo 8.
- *lavar os pés uns dos outros*: O contexto mostra que Jesus estava ensinando que seus seguidores devem se preocupar com o que seus irmãos precisam, não só em sentido físico, mas também em sentido espiritual. Logo antes, Jesus tinha lavado os pés de seus discípulos, apesar de ser o Senhor deles, mostrando o que significava ser humilde e servir outros. Mas, mesmo depois de fazer isso, ele disse: “Vocês estão limpos, mas nem todos.” (Jo 13:10) Isso indica que Jesus não estava falando apenas de uma limpeza em sentido físico. O texto de Ef 5:25, 26 fala de uma limpeza em sentido espiritual quando diz que Jesus purifica a congregação “com o banho de água por meio da palavra” da verdade. Os discípulos de Jesus poderiam imitar o exemplo dele por ajudar uns aos outros a se manter limpos espiritualmente, afastados de tentações e de laços com esse mundo que poderiam contaminá-los. — Gál 6:1; He 10:22; 12:13.
====

[[v43-13-15]]

^<<v43-13-15,15>>^ Pois estabeleci o modelo para vocês, a fim de que, assim como eu lhes fiz, vocês também façam.

[[v43-13-16]]

^<<v43-13-16,16>>^ Digo-lhes com toda a certeza: O escravo não é maior do que o seu senhor, nem o enviado é maior do que aquele que o enviou.

[TIP]
====
- *o enviado*: Ou: “o mensageiro (emissário); o apóstolo”. A palavra grega apóstolos vem do verbo apostéllo, que significa “enviar”. Ela foi traduzida como “apóstolo(s)” em quase todas as 80 vezes que aparece nas Escrituras Gregas Cristãs. (Em Fil 2:25, essa palavra grega aparece na expressão traduzida como “aquele que vocês enviaram”.) No Evangelho de João, a palavra apóstolos aparece apenas aqui. — Mt 10:5; Lu 11:49; 14:32; veja as notas de estudo em Mt 10:2; Mr 3:14 e o Glossário, “Apóstolo”.
====

[[v43-13-17]]

^<<v43-13-17,17>>^ Se vocês sabem essas coisas, felizes serão se as praticarem.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não estou falando a respeito de todos vocês; conheço os que eu escolhi. Mas é para que se cumpra esta passagem das Escrituras: ‘Aquele que comia do meu pão se voltou contra mim.’

[TIP]
====
- *comia do meu pão*: Comer pão com alguém era um sinal de amizade e indicava que havia paz entre o convidado e seu anfitrião. (Gên 31:54; compare com Êx 2:20 e 18:12, onde a expressão hebraica para “comer pão” foi traduzida como “coma” e “comer uma refeição”.) Alguém que, depois de comer pão com seu anfitrião, fizesse algum mal a ele era considerado o pior dos traidores. — Sal 41:9.
- *se voltou contra mim*: Lit.: “levantou seu calcanhar contra mim”. Jesus estava citando as palavras proféticas do Sal 41:9, que diz “se voltou contra mim” (lit.: “levantou seu calcanhar contra mim”). Davi, que foi o escritor desse salmo, estava falando em sentido figurado sobre alguém em quem ele confiava, mas que o traiu. Esse traidor talvez fosse Aitofel, que serviu como “conselheiro de Davi”. (2Sa 15:12) Jesus aplicou essas palavras a Judas Iscariotes. Assim, aqui a expressão “levantar o calcanhar” se refere a realizar um ato de traição com a intenção de prejudicar.
====

[[v43-13-19]]

^<<v43-13-19,19>>^ Digo-lhes isso agora, antes que ocorra, para que, quando ocorrer, acreditem em quem eu sou.

[[v43-13-20]]

^<<v43-13-20,20>>^ Digo-lhes com toda a certeza: Quem recebe a qualquer um que eu envio recebe também a mim, e quem me recebe, recebe também Aquele que me enviou.”

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer isso, Jesus ficou profundamente angustiado, e declarou:^&#42;1^ “Digo-lhes com toda a certeza: Um de vocês me trairá.”

[NOTE]
====
. Ou: “e deu testemunho, dizendo”.
====

[[v43-13-22]]

^<<v43-13-22,22>>^ Os discípulos começaram a olhar uns para os outros, sem saber sobre qual deles ele estava falando.

[[v43-13-23]]

^<<v43-13-23,23>>^ Um dos seus discípulos, aquele a quem Jesus amava, estava recostado junto de Jesus.

[TIP]
====
- *aquele a quem Jesus amava*: Ou seja, aquele a quem Jesus amava especialmente. Esta é a primeira das cinco vezes que este Evangelho menciona um discípulo “a quem Jesus amava”. (Jo 13:23; 19:26; 20:2; 21:7, 20) Acredita-se que esse discípulo seja o apóstolo João, filho de Zebedeu e irmão de Tiago. (Mt 4:21; Mr 1:19; Lu 5:10) Um motivo para essa conclusão é que o apóstolo João não é mencionado por nome nenhuma vez neste Evangelho. A única referência mais específica a ele está em Jo 21:2, que fala dos “filhos de Zebedeu”. Outro motivo é que Jo 21:20-24 mostra que “o discípulo que Jesus amava” foi o escritor deste Evangelho. Além disso, nesse mesmo relato Jesus disse o seguinte sobre esse discípulo: “Se eu quiser que ele permaneça até eu vir, o que importa isso a você [Pedro]?” Essas palavras dão a entender que o discípulo que Jesus amava viveria bem mais do que Pedro e os outros apóstolos, o que se encaixa com o que aconteceu com o apóstolo João. — Veja as notas de estudo em Jo Título e Jo 1:6; 21:20.
- *junto de*: Lit.: “ao seio de”. Esta expressão vem do modo como as pessoas costumavam se posicionar à mesa para tomar uma refeição nos dias de Jesus. Os convidados se deitavam sobre o seu lado esquerdo e apoiavam seu cotovelo esquerdo sobre uma almofada. Assim, um convidado podia se inclinar sobre o peito de um amigo que estivesse atrás dele para ter uma conversa particular. (Jo 13:25) Convidar alguém para tomar uma refeição “junto de” si (“ao seio”) era uma demonstração de grande consideração ou amizade achegada. Pelo visto, algumas expressões usadas em Lucas e João vieram desse costume. — Veja as notas de estudo em Lu 16:22, 23; Jo 1:18.
====

[[v43-13-24]]

^<<v43-13-24,24>>^ Portanto, Simão Pedro acenou com a cabeça para esse discípulo e lhe disse: “Diga-nos a respeito de quem ele está falando.”

[[v43-13-25]]

^<<v43-13-25,25>>^ De modo que ele se encostou no peito de Jesus e lhe perguntou: “Senhor, quem é?”

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu: “É aquele a quem eu der o pedaço de pão que vou molhar na tigela.” Então, depois de molhar o pão, ele o deu a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ Depois que Judas pegou o pedaço de pão, Satanás entrou nele. Então Jesus lhe disse: “Faça mais depressa o que você está fazendo.”

[[v43-13-28]]

^<<v43-13-28,28>>^ Mas nenhum dos que se recostavam à mesa entendeu por que ele lhe disse isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ De fato, visto que Judas cuidava da caixa de dinheiro, alguns pensavam que Jesus estava lhe dizendo: “Compre o que precisamos para a festividade”, ou que devia dar algo aos pobres.

[TIP]
====
- *para a festividade*: Pelo visto, esta festividade era a Festividade dos Pães sem Fermento, que começava logo depois da Páscoa.
====

[[v43-13-30]]

^<<v43-13-30,30>>^ Assim, depois de receber o pedaço de pão, ele saiu imediatamente. Era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Portanto, depois que ele saiu, Jesus disse: “Agora o Filho do Homem é glorificado, e Deus é glorificado por meio dele.

[[v43-13-32]]

^<<v43-13-32,32>>^ O próprio Deus o glorificará, e o glorificará imediatamente.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, estou com vocês mais um pouco. Vocês me procurarão e, assim como eu disse aos judeus, agora digo também a vocês: ‘Para onde eu vou, vocês não podem ir.’

[TIP]
====
- *Filhinhos*: Esta palavra demonstra carinho. João é o único escritor dos Evangelhos que menciona que Jesus chamou seus discípulos assim. A palavra grega traduzida aqui como “filhinhos” é tekníon, que é o diminutivo de téknon (“filho”). Nas Escrituras Gregas Cristãs, o diminutivo muitas vezes é usado para indicar carinho ou intimidade. (Veja o Glossário, “Diminutivo”.) Assim, a palavra grega tekníon também poderia ser traduzida como “filhos queridos” ou “filhos amados”. Nas nove vezes que a palavra aparece nas Escrituras Gregas Cristãs, ela é usada em sentido figurado e se refere a discípulos. — Gál 4:19; 1Jo 2:1, 12, 28; 3:7, 18; 4:4; 5:21.
====

[[v43-13-34]]

^<<v43-13-34,34>>^ Eu lhes dou um novo mandamento: Amem uns aos outros; assim como eu amei vocês, amem também uns aos outros.

[TIP]
====
- *novo mandamento*: A Lei mosaica exigia que as pessoas amassem ao próximo como a si mesmas. (Le 19:18) Mas ela não exigia que alguém amasse a ponto de dar sua vida pelo seu próximo. O mandamento que Jesus deu era completamente “novo”, já que ele disse a seus discípulos: Amem uns aos outros assim como eu amei vocês. Jesus amou aos outros mais do que a si mesmo, mostrando de forma perfeita o tipo de amor que seus seguidores precisariam ter, um amor que levaria uma pessoa a morrer por seu próximo. Tanto a vida como a morte de Jesus deixaram claro o tipo de amor que esse novo mandamento exigia. — Jo 15:13.
====

[[v43-13-35]]

^<<v43-13-35,35>>^ Por meio disto todos saberão que vocês são meus discípulos: se tiverem amor entre si.”

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro lhe disse: “Senhor, para onde vai?” Jesus respondeu: “Para onde eu vou, você não pode me seguir agora, mas me seguirá depois.”

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro lhe disse: “Senhor, por que não posso segui-lo agora? Eu darei a minha vida pelo senhor.”

[TIP]
====
- *vida*: Ou: “alma”. O significado da palavra grega psykhé, que foi traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, varia de acordo com o contexto. Aqui, ela se refere à vida de Pedro, que ele disse que estava disposto a dar por Jesus. — Veja o Glossário, “Alma”.
====

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus respondeu: “Você dará a sua vida por mim? Digo-lhe com toda a certeza: O galo de modo algum cantará até que você tenha me negado três vezes.”

[TIP]
====
- *vida*: Ou: “alma”. O significado da palavra grega psykhé, que foi traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, varia de acordo com o contexto. Aqui, ela se refere à vida de Pedro. — Veja a nota de estudo em Jo 13:37 e o Glossário, “Alma”.
- *O galo*: Os quatro Evangelhos mencionam esta declaração de Jesus, mas o relato de Marcos é o único que acrescenta o detalhe de que o galo cantaria duas vezes. (Mt 26:34, 74, 75; Mr 14:30, 72; Lu 22:34, 60, 61; Jo 18:27) A Mishná indica que nos dias de Jesus as pessoas criavam galos em Jerusalém, o que apoia o relato da Bíblia. É provável que o galo tenha cantado ainda de madrugada.
====

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]