include::./index.adoc[]

[[v43-7-0]]
=== As Boas Novas Segundo João, 7
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* G. Da época da Páscoa de 32 d.C. em diante (6:1–7:1)
* Jesus alimenta cerca de 5.000 homens no mar da Galileia (6:1-13)
* Jesus se retira quando o povo tenta fazer dele um rei (6:14, 15)
* Jesus anda sobre a água (6:16-21)
* Jesus diz para as pessoas trabalharem pelo alimento que permanece para a vida eterna (6:22-27)
* Jesus é “o pão da vida” (6:28-59)
* Muitos discípulos tropeçam por causa das palavras de Jesus, mas Pedro reconhece que Jesus é “o Santo de Deus” (6:60–7:1)
* H. Da época da Festividade das Tendas de 32 d.C. em diante (7:2–9:41)
* Irmãos de Jesus sobem para a festividade; Jesus vai depois e chega na cidade em segredo (7:2-13)
* Jesus ensina no templo durante a festividade (7:14-24)
* Pessoas têm opiniões diferentes sobre o Cristo (7:25-52)
* O Pai dá testemunho sobre Jesus, “a luz do mundo” (8:12-30)
* Verdadeiros discípulos de Jesus conhecerão a verdade (8:31, 32)
* Filhos de Abraão fazem as obras de Abraão (8:33-41)
* Filhos do Diabo fazem o que o Diabo deseja (8:42-47)
* Jesus e Abraão (8:48-59)
* Jesus cura um homem que nasceu cego (9:1-12)
* Fariseus interrogam o homem que foi curado (9:13-34)
* Cegueira dos fariseus (9:35-41)
****

[[v43-7-1]]

^<<v43-7-1,1>>^ Depois disso, Jesus continuou a viajar^&#42;1^ pela Galileia, porque não queria andar pela Judeia, visto que os judeus procuravam matá-lo.

[NOTE]
====
. Ou: “andar”.
====

[TIP]
====
- *os judeus*: No Evangelho de João, a palavra “judeus” pode ter significados diferentes, dependendo do contexto. Ela pode se referir aos judeus em geral, aos habitantes da região da Judeia ou aos que moravam em Jerusalém ou perto dali. Ela também pode ter um sentido mais específico e se referir aos judeus que se apegavam às tradições humanas acrescentadas à Lei mosaica. Essas tradições muitas vezes iam contra o espírito da Lei. (Mt 15:3-6) Quem tomava a frente entre esse último grupo de “judeus” eram as autoridades judaicas, os líderes religiosos dos judeus, que odiavam Jesus. O contexto indica que, aqui e em alguns outros versículos do capítulo 7, a palavra “judeus” se refere a essas autoridades judaicas. — Jo 7:13, 15, 35a; veja o Glossário, “Judeu”.
====

[[v43-7-2]]

^<<v43-7-2,2>>^ No entanto, estava próxima a festividade judaica das Tendas,

[TIP]
====
- *a festividade judaica das Tendas*: Ou: “a festividade judaica das Barracas”. Esta é a única vez que a festividade das Tendas é mencionada nas Escrituras Gregas Cristãs. Este versículo se refere à festividade que aconteceu no ano 32 d.C. — Veja o Glossário, “Festividade das Barracas” e o Apêndice B15.
====

[[v43-7-3]]

^<<v43-7-3,3>>^ e seus irmãos lhe disseram: “Saia daqui e vá à Judeia para que os seus discípulos também possam ver as obras que você está fazendo.

[[v43-7-4]]

^<<v43-7-4,4>>^ Pois ninguém faz as coisas em segredo quando procura ser conhecido publicamente. Se você está fazendo essas coisas, mostre-se ao mundo.”

[[v43-7-5]]

^<<v43-7-5,5>>^ Na verdade, seus irmãos não exerciam fé nele.

[[v43-7-6]]

^<<v43-7-6,6>>^ Portanto, Jesus lhes disse: “A minha hora ainda não chegou, mas para vocês qualquer hora é boa.

[[v43-7-7]]

^<<v43-7-7,7>>^ O mundo não tem razão para odiar vocês, mas odeia a mim, porque dou testemunho dele, de que as suas obras são más.

[[v43-7-8]]

^<<v43-7-8,8>>^ Subam para a festividade; eu ainda não vou a essa festividade, porque o meu tempo ainda não se cumpriu.”

[[v43-7-9]]

^<<v43-7-9,9>>^ Assim, depois de lhes dizer essas coisas, ele permaneceu na Galileia.

[[v43-7-10]]

^<<v43-7-10,10>>^ Mas, depois que os seus irmãos subiram para a festividade, ele também subiu, não abertamente, mas em segredo.

[[v43-7-11]]

^<<v43-7-11,11>>^ Por isso, os judeus começaram a procurá-lo na festividade e a dizer: “Onde está aquele homem?”

[TIP]
====
- *os judeus*: Aqui, a expressão “os judeus” talvez se refira ao povo em geral, que estava reunido em Jerusalém para a Festividade das Tendas. Mas também é possível que ela tenha sido usada para se referir aos líderes religiosos judaicos. — Veja a nota de estudo em Jo 7:1.
====

[[v43-7-12]]

^<<v43-7-12,12>>^ E entre as multidões muitos cochichavam por causa dele. Alguns diziam: “Ele é um homem bom.” Outros diziam: “Não é. Ele está enganando a multidão.”

[[v43-7-13]]

^<<v43-7-13,13>>^ Naturalmente, ninguém falava dele em público, por medo dos judeus.

[TIP]
====
- *dos judeus*: Aqui, a palavra “judeus” pelo visto se refere às autoridades judaicas, os líderes religiosos dos judeus. — Veja a nota de estudo em Jo 7:1.
====

[[v43-7-14]]

^<<v43-7-14,14>>^ Quando a festividade já estava na metade, Jesus subiu ao templo e começou a ensinar.

[[v43-7-15]]

^<<v43-7-15,15>>^ Os judeus ficaram admirados, e diziam: “Como é que este homem tem tanto conhecimento das Escrituras, se não estudou nas escolas?”

[TIP]
====
- *Os judeus*: É provável que a expressão “os judeus” tenha sido usada aqui para se referir às autoridades judaicas, os líderes religiosos dos judeus. Isso faz sentido, já que no versículo 19 Jesus perguntou a esses judeus: “Por que procuram me matar?” — Veja a nota de estudo em Jo 7:1.
- *das Escrituras*: Lit.: “escritos; letras” (letras do alfabeto). A expressão “conhecer (ter conhecimento de) letras” é uma expressão idiomática que significa “ter conhecimento dos escritos (livros, literatura)”. Neste contexto, essa expressão pelo visto se refere ao conhecimento das Escrituras inspiradas.
- *se não estudou nas escolas*: Ou: “se não foi ensinado”. Lit.: “não tendo aprendido”. Isso não quer dizer que Jesus não tinha nenhuma instrução. Mas ele não tinha cursado uma escola rabínica de ensino superior.
====

[[v43-7-16]]

^<<v43-7-16,16>>^ Então Jesus lhes respondeu: “O que eu ensino não é meu, mas pertence àquele que me enviou.

[[v43-7-17]]

^<<v43-7-17,17>>^ Se alguém desejar fazer a Sua vontade, saberá se os ensinamentos são de Deus ou se o que falo se origina de mim.

[TIP]
====
- *se origina de mim*: Ou: “é por conta própria”. Lit.: “de mim mesmo”. Como Jesus é o Principal Representante de Deus, ele sempre ouve a voz de Jeová e fala aquilo que Jeová o orienta a falar.
====

[[v43-7-18]]

^<<v43-7-18,18>>^ Quem fala as suas próprias ideias procura a sua própria glória; mas quem procura a glória daquele que o enviou é verdadeiro,^&#42;1^ e não há injustiça nele.

[NOTE]
====
. Ou: “fala a verdade”.
====

[[v43-7-19]]

^<<v43-7-19,19>>^ Moisés lhes deu a Lei, não deu? Mas nenhum de vocês obedece à Lei. Por que procuram me matar?”

[[v43-7-20]]

^<<v43-7-20,20>>^ A multidão respondeu: “Você tem demônio.^&#42;1^ Quem está procurando matá-lo?”

[NOTE]
====
. Ou: “Você está possesso de demônio; Você está endemoninhado”.
====

[[v43-7-21]]

^<<v43-7-21,21>>^ Em resposta, Jesus lhes disse: “Realizei uma só obra, e todos vocês estão surpresos.

[[v43-7-22]]

^<<v43-7-22,22>>^ Então, considerem o seguinte:^&#42;1^ Moisés deu a vocês a circuncisão (não que ela tenha vindo de Moisés, mas sim dos antepassados), e vocês circuncidam um homem num sábado.

[NOTE]
====
. Ou: “Por isso”.
====

[[v43-7-23]]

^<<v43-7-23,23>>^ Se um homem recebe a circuncisão num sábado para que a Lei de Moisés não seja violada, por que vocês estão tão irados comigo por eu ter curado completamente um homem num sábado?

[TIP]
====
- *a circuncisão num sábado*: A Lei mosaica exigia que todos os homens fossem circuncidados no oitavo dia de vida. (Le 12:2, 3) Isso era considerado tão importante que a circuncisão era feita mesmo que o oitavo dia caísse em um sábado.— Veja o Glossário, “Circuncisão”.
====

[[v43-7-24]]

^<<v43-7-24,24>>^ Parem de julgar pelas aparências, mas façam um julgamento justo.”

[[v43-7-25]]

^<<v43-7-25,25>>^ Então alguns dos habitantes de Jerusalém começaram a dizer: “Não é este o homem que procuram matar?

[[v43-7-26]]

^<<v43-7-26,26>>^ No entanto, ele está aqui falando em público, e não lhe dizem nada. Será que os nossos líderes realmente acham que ele é o Cristo?

[TIP]
====
- *os nossos líderes*: Esta expressão se refere às autoridades judaicas. Nos dias de Jesus, Israel estava sob o controle do Império Romano. Mas alguns judeus receberam certa autoridade para cuidar dos assuntos de seu povo. Entre esses judeus, o grupo de maior autoridade era o Sinédrio, que era composto de 71 anciãos (incluindo o sumo sacerdote). — Veja o Glossário, “Sinédrio”.
====

[[v43-7-27]]

^<<v43-7-27,27>>^ Mas nós sabemos de onde é esse homem; ao passo que, quando o Cristo vier, ninguém saberá de onde ele é.”

[[v43-7-28]]

^<<v43-7-28,28>>^ Então, enquanto ensinava no templo, Jesus disse bem alto: “Vocês me conhecem e sabem de onde eu sou. E eu não vim de minha própria iniciativa, mas Aquele que me enviou é real, e vocês não o conhecem.

[[v43-7-29]]

^<<v43-7-29,29>>^ Eu o conheço, porque sou representante dele, e ele me enviou.”

[TIP]
====
- *sou representante dele*: Ou: “venho dele”. Lit.: “ao lado dele eu estou”. Além de indicar que Jesus veio de Deus, a preposição grega usada aqui (pará, lit.: “ao lado de”) destaca a proximidade que existe entre eles. Por isso, Jesus pode ser considerado um “representante” de Deus.
====

[[v43-7-30]]

^<<v43-7-30,30>>^ Por isso procuraram prendê-lo, mas ninguém conseguiu segurá-lo, pois a sua hora ainda não havia chegado.

[[v43-7-31]]

^<<v43-7-31,31>>^ Contudo, muitos da multidão depositaram fé nele, e diziam: “Quando o Cristo vier, será que realizará mais sinais do que esse homem realizou?”

[[v43-7-32]]

^<<v43-7-32,32>>^ Os fariseus ouviram a multidão cochichando essas coisas a respeito dele, e os principais sacerdotes e os fariseus enviaram guardas para prendê-lo.^&#42;1^

[NOTE]
====
. Ou: “pegá-lo”.
====

[TIP]
====
- *guardas*: Ou seja, guardas da polícia do templo em Jerusalém. É provável que esses guardas fossem funcionários do Sinédrio e estivessem sob a autoridade dos principais sacerdotes.
====

[[v43-7-33]]

^<<v43-7-33,33>>^ Então Jesus disse: “Ficarei com vocês mais um pouco, antes de ir para Aquele que me enviou.

[[v43-7-34]]

^<<v43-7-34,34>>^ Vocês me procurarão, mas não me acharão, e, para onde eu vou,^&#42;1^ vocês não podem ir.”

[NOTE]
====
. Ou: “e onde eu estou”.
====

[[v43-7-35]]

^<<v43-7-35,35>>^ Portanto, os judeus disseram entre si: “Para onde esse homem pretende ir, de modo que não poderemos achá-lo? Será que ele pretende ir aos judeus dispersos entre os gregos e ensinar os gregos?

[TIP]
====
- *os judeus*: No contexto deste versículo, os fariseus e os principais sacerdotes são mencionados. (Jo 7:32, 45) Assim, a expressão “os judeus” que aparece aqui pelo visto se refere às autoridades judaicas, os líderes religiosos dos judeus. — Veja a nota de estudo em Jo 7:1.
- *judeus dispersos*: Lit.: “dispersão”. Neste contexto, a palavra grega diasporá se refere aos judeus que moravam fora de Israel. Os judeus foram dispersos, ou seja, espalhados, quando sua terra foi conquistada por outras nações e eles foram levados para o exílio. Isso aconteceu primeiro com a conquista pelos assírios, no século 8 a.C., e depois pelos babilônios, no século 7 a.C. (2Rs 17:22, 23; 24:12-17; Je 52:28-30) Apenas um restante dos exilados voltou para Israel; os outros continuaram espalhados. (Is 10:21, 22) Ao que parece, no século 5 a.C. havia comunidades de judeus nas 127 províncias do Império Persa. (Est 1:1; 3:8) A expressão usada aqui em Jo 7:35 se refere aos judeus que estavam dispersos entre os gregos. No século 1 d.C., judeus faziam parte de comunidades que falavam grego em lugares como a Síria, a Ásia Menor, o Egito e a parte europeia do Império Romano, incluindo a Grécia e Roma. Os esforços dos judeus para converter outros, com o tempo, fizeram com que um grande número de pessoas aprendesse algo sobre Jeová e sobre a Lei que ele tinha dado ao seu povo. (Mt 23:15) Muitos judeus e prosélitos estavam em Jerusalém para a Festividade de Pentecostes no ano 33 d.C. e ouviram as boas novas sobre Jesus Cristo. Assim, o fato de os judeus estarem espalhados por todo o Império Romano contribuiu para que o cristianismo se espalhasse rapidamente.
====

[[v43-7-36]]

^<<v43-7-36,36>>^ O que ele quer dizer com as palavras: ‘Vocês me procurarão, mas não me acharão, e, para onde eu vou, vocês não podem ir’?”

[[v43-7-37]]

^<<v43-7-37,37>>^ No último dia, o grande dia da festividade, Jesus se levantou e disse bem alto: “Se alguém tiver sede, venha a mim e beba.

[TIP]
====
- *No último dia*: Este dia, que também era chamado de “o grande dia da festividade”, era o sétimo dia da Festividade das Tendas, ou Barracas, ou seja, o dia 21 do mês judaico de tisri. — De 16:13; veja a nota de estudo em Jo 7:2; o Glossário, “Festividade das Barracas” e o Apêndice B15.
====

[[v43-7-38]]

^<<v43-7-38,38>>^ Quem depositar fé em mim, assim como disse uma passagem das Escrituras, ‘do seu íntimo fluirão correntes de água viva’.”

[TIP]
====
- *assim como disse uma passagem das Escrituras*: Tudo indica que Jesus não estava citando um versículo específico das Escrituras. Mas ele talvez estivesse fazendo referência a textos como Is 44:3; 58:11 e Za 14:8. Mais de dois anos antes, quando Jesus falou com uma mulher samaritana sobre a água viva, ele se concentrou nos benefícios que essa água podia trazer. (Jo 4:10, 14) Mas, neste versículo, Jesus indicou que a “água viva” iria fluir dos que depositassem fé nele, ao passo que compartilhassem essa água com outros. (Jo 7:37-39) As Escrituras Gregas Cristãs estão cheias de relatos que mostram que, depois que os seguidores de Jesus começaram a receber espírito santo no Pentecostes de 33 d.C., eles se sentiram motivados a compartilhar a água que dá vida com todos os que os escutassem. — At 5:28; Col 1:23.
- *fluirão correntes de água viva*: Jesus talvez estivesse fazendo referência a um costume que os judeus seguiam durante a Festividade das Tendas, ou Barracas. Esse costume envolvia retirar água do reservatório de Siloé, usando um jarro de ouro, e depois derramar essa água, além de vinho, sobre o altar na hora do sacrifício da manhã. (Veja a nota de estudo em Jo 7:2; o Glossário, “Festividade das Barracas” e o Apêndice B15.) Esse aspecto da festividade não é mencionado nas Escrituras Hebraicas e foi adotado apenas mais tarde. A maioria dos estudiosos acredita que isso era feito apenas nos sete dias da festividade, mas não no oitavo dia, quando era realizada uma assembleia. No primeiro dia da festividade, que era considerado um sábado, o sacerdote usava a água que tinha sido retirada do reservatório de Siloé no dia anterior. Nos outros dias, o sacerdote ia até o reservatório de Siloé e retirava a água usando um jarro de ouro. Ele calculava o tempo para retornar na hora em que os sacerdotes iam colocar o sacrifício no altar. Quando ele passava pelo Portão das Águas e entrava no Pátio dos Sacerdotes, sua entrada era anunciada pelos sacerdotes com três toques de trombeta. Então, a água era derramada em um recipiente que levava para a base do altar. Ao mesmo tempo, vinho era derramado em outro recipiente. Depois disso, os Salmos de Halel (Sal 113-118) eram cantados com acompanhamento musical. Enquanto isso, os que tinham ido ao templo para adorar balançavam folhas de palmeira em direção ao altar. Durante essa alegre cerimônia, os participantes talvez se lembrassem das palavras proféticas de Isaías, que disse: “Com alegria vocês tirarão água das fontes de salvação.” — Is 12:3.
====

[[v43-7-39]]

^<<v43-7-39,39>>^ No entanto, ao dizer isso, ele falava sobre o espírito, que os que depositaram fé nele iam receber; pois até então não havia espírito, porque Jesus ainda não havia sido glorificado.

[TIP]
====
- *pois até então não havia espírito*: Neste versículo, a palavra grega para “espírito” (pneúma) aparece duas vezes e se refere ao espírito santo, ou força ativa, de Deus. Já fazia muito tempo que Deus usava seu espírito santo (Gên 1:2, nota de rodapé; 2Sa 23:2; At 28:25) e ele já tinha dado seu espírito a seus servos leais, como Otniel, Jefté e Sansão (Jz 3:9, 10; 11:29; 15:14). Tanto Jesus como seus ouvintes sabiam disso. Assim, quando João diz aqui que “não havia espírito”, ele estava se referindo a uma nova maneira de o espírito santo atuar sobre humanos imperfeitos. Quando voltou ao céu, Jesus foi glorificado e recebeu de seu Pai o espírito santo. Daí, durante o Pentecostes de 33 d.C., ele derramou esse espírito sobre seus seguidores. (At 2:4, 33) Essa foi a primeira vez que humanos imperfeitos receberam a esperança de viver no céu como seres espirituais. Depois que foram ungidos, os cristãos conseguiram entender o significado de muitas coisas que eles não tinham entendido antes.
====

[[v43-7-40]]

^<<v43-7-40,40>>^ Alguns da multidão que ouviram essas palavras começaram a dizer: “Este é realmente o Profeta.”

[[v43-7-41]]

^<<v43-7-41,41>>^ Outros diziam: “Este é o Cristo.” Mas alguns diziam: “Será que o Cristo vem da Galileia?

[[v43-7-42]]

^<<v43-7-42,42>>^ Não dizem as Escrituras que o Cristo virá da descendência de Davi e de Belém, a aldeia de onde Davi era?”

[[v43-7-43]]

^<<v43-7-43,43>>^ Assim, surgiu uma divisão entre a multidão por causa dele.

[[v43-7-44]]

^<<v43-7-44,44>>^ Alguns deles, porém, queriam prendê-lo,^&#42;1^ mas ninguém conseguiu segurá-lo.

[NOTE]
====
. Ou: “pegá-lo”.
====

[[v43-7-45]]

^<<v43-7-45,45>>^ Os guardas voltaram então aos principais sacerdotes e aos fariseus, e estes lhes perguntaram: “Por que vocês não o trouxeram para cá?”

[[v43-7-46]]

^<<v43-7-46,46>>^ Os guardas responderam: “Nunca homem algum falou assim!”

[[v43-7-47]]

^<<v43-7-47,47>>^ Então os fariseus disseram: “Será que vocês também foram enganados?

[[v43-7-48]]

^<<v43-7-48,48>>^ Por acaso algum dos nossos líderes ou dos fariseus depositou fé nele?

[[v43-7-49]]

^<<v43-7-49,49>>^ Mas essa multidão, que não conhece a Lei, são pessoas amaldiçoadas.”

[TIP]
====
- *pessoas amaldiçoadas*: Os fariseus e os líderes judaicos, que se consideravam justos e eram orgulhosos, encaravam como inferiores as pessoas comuns que estavam escutando Jesus. Eles chamaram essas pessoas de “amaldiçoadas”. A palavra grega que aparece aqui, epáratos, expressava desprezo e dava a entender que a pessoa tinha sido amaldiçoada por Deus. Os líderes religiosos judaicos também mostravam seu desprezo pelas pessoas comuns usando a expressão “povo da terra” (em hebraico, ʽam haʼárets). Antes, essa expressão era uma forma respeitosa de se referir aos habitantes de um lugar específico e incluía tanto os pobres e humildes como os ricos. (Gên 23:7; 2Rs 23:35; Ez 22:29) Mas, nos dias de Jesus, a expressão era usada para se referir às pessoas que eram consideradas ignorantes com respeito à Lei ou que não cumpriam as tradições rabínicas nos mínimos detalhes. Alguns comentários rabínicos escritos mais tarde confirmam que os líderes religiosos judaicos tinham essa atitude. Muitos desses líderes sentiam desprezo por essas pessoas e se recusavam a comer, fazer negócios ou se associar com elas.
====

[[v43-7-50]]

^<<v43-7-50,50>>^ Nicodemos, que tinha ido a ele antes e era um deles, lhes disse:

[[v43-7-51]]

^<<v43-7-51,51>>^ “Será que a nossa Lei julga um homem sem que primeiro o ouça e saiba o que ele está fazendo?”

[[v43-7-52]]

^<<v43-7-52,52>>^ Em resposta, disseram-lhe: “Será que você também é da Galileia? Pesquise e veja que nenhum profeta surgirá na Galileia.”

[TIP]
====
- *Será que você também é da Galileia?*: Esta pergunta pelo visto reflete o desprezo que os habitantes da Judeia tinham pelos habitantes da Galileia. Nicodemos tinha defendido Jesus (Jo 7:51), e os fariseus estavam como que perguntando: “Você vai defender esse homem e ficar do lado dele? Vai se rebaixar ao nível de um galileu ignorante?” Como o Sinédrio e o templo ficavam em Jerusalém, na Judeia, é muito provável que houvesse uma grande concentração de instrutores da Lei ali. Provavelmente por isso, existia um provérbio judaico que dizia: “Se quiser riquezas, vá para o norte [para a Galileia], se quiser sabedoria, vá para o sul [para a Judeia].” Mas as evidências mostram que os galileus conheciam a Lei de Deus. As aldeias e cidades da Galileia tinham instrutores da Lei e também sinagogas, que serviam como centros de educação. (Lu 5:17) A resposta arrogante que os fariseus deram a Nicodemos indica que eles não fizeram nenhum esforço para saber onde Jesus tinha realmente nascido, ou seja, Belém. (Miq 5:2; Jo 7:42) Eles também não levaram em conta que a profecia de Isaías comparava a pregação que o Messias faria com “uma grande luz” que brilharia na Galileia. — Is 9:1, 2; Mt 4:13-17.
- *nenhum profeta surgirá na Galileia*: Os fariseus que fizeram essa afirmação não levaram em conta as palavras em Is 9:1, 2, que prediziam que uma grande luz brilharia na Galileia. Alguns estudiosos acreditam que os fariseus, que desprezavam os galileus, não estavam dizendo apenas que nenhum profeta viria da Galileia, mas também que nenhum dos profetas do passado tinha vindo de lá. Se esse for o sentido, os fariseus desconsideraram o fato de que o profeta Jonas era de uma cidade da Galileia chamada Gate-Héfer, que ficava apenas 4 quilômetros ao nordeste de Nazaré, onde Jesus foi criado. — 2Rs 14:25.
- *7*:53
- *O trecho de Jo 7*:53 a 8:11 não aparece nos manuscritos mais antigos e confiáveis. Esses 12 versículos obviamente não faziam parte do texto original do Evangelho de João. (Veja o Apêndice A3.) Eles não aparecem nos dois papiros mais antigos disponíveis do Evangelho de João, escritos no século 2 d.C., o Papiro Bodmer 2 (P66) e o Papiro Bodmer 14, 15 (P75). Eles também não foram incluídos no Códice Sinaítico e no Códice Vaticano, do século 4 d.C. Esses versículos aparecem pela primeira vez em um manuscrito grego do século 5 d.C. (Códice Bezae), mas não são encontrados em nenhum outro manuscrito grego até o século 9 d.C. Eles também não foram incluídos na maioria das primeiras traduções para outros idiomas. Além disso, os manuscritos que têm esses versículos não os incluem sempre no mesmo lugar. Por exemplo, um grupo de manuscritos gregos inclui esses versículos no fim do Evangelho de João; outro grupo de manuscritos inclui os versículos depois de Lu 21:38. O fato de que essas palavras aparecem em diferentes lugares nos manuscritos apoia a conclusão de que elas não faziam parte do texto original. A esmagadora maioria dos estudiosos concorda que essas palavras não faziam parte do Evangelho de João.
- *Alguns manuscritos gregos e algumas traduções para outros idiomas que incluem esses versículos dizem (com algumas variações) o seguinte*:
- 53 Foram assim cada um para o seu lar.
- *8 Mas Jesus foi para o monte das Oliveiras. 2 Ao amanhecer, porém, ele se apresentou novamente no templo e todo o povo começou a vir a ele, e ele se sentou e começou a ensiná-los. 3 Os escribas e os fariseus trouxeram então uma mulher que tinha sido pega cometendo adultério. Depois de a colocarem no meio deles, 4 disseram-lhe*: “Instrutor, esta mulher foi pega cometendo adultério. 5 Na Lei, Moisés mandou apedrejar esse tipo de mulher. E você, o que você diz?” 6 Naturalmente, diziam isso para o porem à prova, a fim de terem um motivo para acusá-lo. Mas Jesus abaixou-se e começou a escrever no chão com o seu dedo. 7 Quando persistiram em perguntar-lhe, ele se levantou e lhes disse: “Quem de vocês não tiver pecado seja o primeiro a atirar uma pedra nela.” 8 E, abaixando-se novamente, continuou escrevendo no chão. 9 Mas os que ouviram isso foram saindo um por um, começando com os anciãos, e ele foi deixado só, com a mulher que estava no meio deles. 10 Jesus se levantou e disse a ela: “Mulher, onde eles estão? Ninguém a condenou?” 11 Ela disse: “Ninguém, senhor.” Jesus disse: “Eu também não a condeno. Vá; de agora em diante não pratique mais pecado.”
====

'''

xref:043-joao/043-joao-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-joao/043-joao-008.adoc#v43-8-0[Próximo Capítulo &#62;]