include::./index.adoc[]

[[v47-11-0]]
=== A Segunda aos Coríntios, 11
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* D. ARGUMENTOS PARA COMBATER A INFLUÊNCIA DE FALSOS APÓSTOLOS (10:1–12:21)
* 1. Paulo defende seu ministério (10:1-18)
* Armas que não são carnais, mas são poderosas em Deus (10:1-6)
* Paulo se defende das acusações de ser fraco (10:7-12)
* Paulo se orgulha apenas do que realizava dentro dos limites de seu território (10:13-18)
* 2. Paulo e os superapóstolos (11:1-15)
* Paulo tem ciúme semelhante ao de Deus; ele quer apresentar os coríntios como “virgem casta” ao Cristo (11:1-5)
* Paulo está decidido a não se tornar um fardo para ninguém (11:6-15)
* 3. Dificuldades de Paulo como apóstolo (11:16-33)
* 4. Visões de Paulo e seu “espinho na carne” (12:1-21)
* Visão do terceiro céu e do paraíso (12:1-7a)
* Paulo fala de seu “espinho na carne” e da bondade imerecida de Deus (12:7b-10)
* Paulo não é inferior aos superapóstolos (12:11-13)
* Preocupação de Paulo com os coríntios (12:14-21)
****

[[v47-11-1]]

^<<v47-11-1,1>>^ Eu gostaria que vocês me suportassem numa pequena insensatez. Mas, de fato, vocês estão me suportando!

[TIP]
====
- *numa pequena insensatez*: Paulo sabia que o fato de ele se gabar poderia levar alguns a acharem que ele era insensato. (2Co 11:16) Mas ele se sentiu obrigado a fazer isso na parte final de 2 Coríntios para provar que era um apóstolo. (Em 2Co 11 e 12, Paulo usa oito vezes as palavras gregas áfron [“insensato”] e afrosýne [“insensatez”]: 2Co 11:1, 16, 17, 19, 21; 12:6, 11.) Os ataques dos “superapóstolos” estavam afetando a confiança dos irmãos em Paulo e nos ensinos dele, e isso estava prejudicando a congregação. Por isso, ele precisou falar de suas qualificações, deixando claro que sua autoridade vinha de Deus. (2Co 10:10; 11:5, 16; veja a nota de estudo em 2Co 11:5.) Nessas circunstâncias, isso não era algo insensato.
====

[[v47-11-2]]

^<<v47-11-2,2>>^ Pois tenho ciúme de vocês, um ciúme semelhante ao de Deus, porque eu pessoalmente os prometi em casamento a um só marido, ao Cristo, a fim de apresentá-los como virgem casta a ele.

[TIP]
====
- *tenho ciúme de vocês, um ciúme semelhante ao de Deus*: As palavras gregas traduzidas aqui como “tenho ciúme” e “ciúme” se referem a um sentimento forte que pode ser positivo ou negativo. Neste versículo, elas têm um sentido positivo e passam a ideia de ter profundo interesse e forte preocupação com alguém como demonstração de amor sincero. Era esse o tipo de sentimento que Paulo tinha pelos seus irmãos ungidos. Ele os comparou a uma virgem casta prometida em casamento a um só marido, Jesus Cristo. O ciúme que Paulo sentia o fazia querer proteger todos na congregação contra qualquer coisa que pudesse lhes causar dano espiritual, para que eles permanecessem puros para Cristo. Assim, ao dizer que tinha um “ciúme semelhante ao de Deus [lit.: “zelo de Deus”]”, Paulo indica que o amor e a afeição de Jeová incluem não apenas um profundo interesse por aqueles a quem ele ama, mas também um forte desejo de protegê-los contra qualquer dano. — Para uma explicação sobre o sentido negativo do verbo grego zelóo, veja a nota de estudo em 1Co 13:4.
- *casta*: Ou: “pura”. A noiva de Cristo é composta por 144.000 cristãos ungidos. Cada um deles se mantém figurativamente virgem por permanecer separado do mundo e se manter puro em sentido moral e doutrinal. — Ap 14:1, 4; compare com 1Co 5:9-13; 6:15-20; Tg 4:4; 2Jo 8-11; Ap 19:7, 8.
====

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas tenho medo de que, assim como a serpente seduziu Eva pela sua astúcia, a mente de vocês seja de algum modo corrompida, afastando-se da sinceridade e da castidade^&#42;1^ que devemos ao Cristo.

[NOTE]
====
. Ou: “pureza”.
====

[[v47-11-4]]

^<<v47-11-4,4>>^ Pois, de fato, se alguém chega e prega um Jesus diferente do que nós pregamos, ou se vocês recebem um espírito diferente do que receberam, ou boas novas diferentes das que aceitaram, vocês facilmente o suportam.

[[v47-11-5]]

^<<v47-11-5,5>>^ Pois eu não me considero inferior aos seus superapóstolos em coisa alguma.

[TIP]
====
- *superapóstolos*: Aqui, Paulo usa uma expressão que também poderia ser traduzida como “supremos apóstolos”. Com um toque de sarcasmo, Paulo usa essa expressão para se referir a alguns homens arrogantes de Corinto que, pelo visto, se consideravam superiores aos apóstolos que o próprio Jesus tinha escolhido. Em 2Co 11:13-15, Paulo chama esses mesmos homens de “falsos apóstolos”, porque eles eram na verdade servos de Satanás. Eles ensinavam sua própria versão das boas novas sobre Cristo. (2Co 11:3, 4) Além disso, eles caluniavam e menosprezavam Paulo, e questionavam a autoridade que ele tinha recebido de Deus como apóstolo.
====

[[v47-11-6]]

^<<v47-11-6,6>>^ Mas, mesmo que eu seja imperito no falar, certamente não o sou no conhecimento; de fato, deixamos isso claro a vocês de todos os modos e em todas as coisas.

[[v47-11-7]]

^<<v47-11-7,7>>^ Ou será que cometi um pecado por me humilhar para que vocês fossem enaltecidos, ao declarar-lhes de boa vontade as boas novas de Deus sem custo?

[[v47-11-8]]

^<<v47-11-8,8>>^ A outras congregações despojei, aceitando provisões delas a fim de servir a vocês.

[TIP]
====
- *despojei*: Lit.: “roubei”. O verbo grego que aparece aqui, syláo, é muitas vezes usado para se referir a tomar despojo de guerra. Apesar de Paulo ter usado esse verbo, isso não significa que ele tinha feito algo de errado ao aceitar provisões de outros. Na verdade, ele usa esse verbo em sentido figurado para dar força a seu argumento. Paulo está dando uma resposta aos “superapóstolos” de Corinto (2Co 11:5), que o acusavam, sem nenhuma base, de tirar vantagem da congregação daquela cidade. Quando Paulo ‘passou necessidade’ em Corinto, parece que os cristãos de lá não o ajudaram, apesar de alguns deles, pelo visto, serem ricos. Quem supriu suas necessidades foram os irmãos da Macedônia, que eram mais pobres. (2Co 11:9) Além disso, enquanto esteve em Corinto, Paulo trabalhou como um humilde fabricante de tendas para se sustentar em seu ministério. Talvez ele estivesse se referindo a isso quando disse no versículo anterior que não ‘cometeu um pecado’ por se humilhar. (2Co 11:7) Assim, pelo visto Paulo está falando com um toque de ironia quando diz que ‘despojou’, ou ‘roubou’, as outras congregações por ter aceitado ajuda financeira delas enquanto realizava atividades em favor dos coríntios.
- *provisões*: Ou: “apoio”. A palavra grega opsónion significa literalmente “pagamento; salário”. Em Lu 3:14 (veja a nota de estudo), essa palavra foi usada para se referir ao salário ou à ajuda para despesas que os soldados recebiam. Aqui, ela foi usada para se referir à pequena ajuda material que Paulo tinha recebido de algumas congregações para cuidar das necessidades dele enquanto estava em Corinto. — Para ver outros exemplos do uso dessa palavra grega, veja as notas de estudo em Ro 6:23; 1Co 9:7.
====

[[v47-11-9]]

^<<v47-11-9,9>>^ Contudo, quando estive presente entre vocês e passei necessidade, não me tornei um fardo para ninguém, pois os irmãos vindos da Macedônia supriram abundantemente as minhas necessidades. Sim, tomei cuidado para não me tornar um fardo para vocês em nenhum sentido, e continuarei fazendo isso.

[[v47-11-10]]

^<<v47-11-10,10>>^ Tão certo como a verdade de Cristo está em mim, não deixarei de falar com orgulho sobre isso nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por quê? Porque não amo vocês? Deus sabe que os amo.

[[v47-11-12]]

^<<v47-11-12,12>>^ Mas o que estou fazendo continuarei fazendo, a fim de eliminar o pretexto daqueles que estão procurando um motivo para ser considerados iguais a nós nas coisas das quais se gabam.

[TIP]
====
- *a fim de eliminar o pretexto*: Paulo se recusava a aceitar qualquer ajuda financeira da congregação de Corinto. (2Co 11:9) Os “superapóstolos”, por outro lado, pelo visto aceitavam essa ajuda com o pretexto de que os verdadeiros apóstolos não deviam trabalhar para se sustentar, assim como Paulo trabalhava. (2Co 11:4, 5, 20) Aqueles homens estavam procurando “um motivo [ou: “pretexto”] para ser considerados iguais” a Paulo. Quando Paulo fala que eles se gabavam de certas coisas, ele talvez esteja se referindo ao fato de eles afirmarem que estavam qualificados para servir como apóstolos. (2Co 11:7) Mais à frente neste capítulo e no capítulo 12, Paulo fala de suas próprias qualificações, mostrando que a afirmação deles não tinha base nenhuma. Além disso, Paulo diz sem rodeios que aqueles “superapóstolos” eram “falsos apóstolos, . . . disfarçados de apóstolos de Cristo”. — 2Co 11:13.
====

[[v47-11-13]]

^<<v47-11-13,13>>^ Pois esses homens são falsos apóstolos, trabalhadores enganosos, disfarçados de apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E isso não é de admirar, pois o próprio Satanás se disfarça de anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não surpreende que os servos^&#42;1^ dele também se disfarcem de servos^&#42;2^ da justiça. Mas o fim deles será segundo as suas obras.

[NOTE]
====
. Ou: “ministros”.
. Ou: “ministros”.
====

[[v47-11-16]]

^<<v47-11-16,16>>^ Digo novamente: Que ninguém pense que sou insensato. Mas, se vocês pensam isso, então aceitem-me como um insensato, para que eu também me gabe um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ Estou falando agora, não seguindo o exemplo do Senhor, mas como alguém insensato, com a autoconfiança de quem se gaba.

[[v47-11-18]]

^<<v47-11-18,18>>^ Já que muitos se gabam segundo a carne, eu também me gabarei.

[TIP]
====
- *segundo a carne*: Ou seja, por motivos humanos, se gabando de suas circunstâncias pessoais.
====

[[v47-11-19]]

^<<v47-11-19,19>>^ Vocês, que são tão “sensatos”, suportam de boa vontade os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ De fato, suportam a quem quer que os escravize, a quem quer que devore os seus bens, a quem quer que tome o que vocês têm, a quem quer que se enalteça sobre vocês, a quem quer que lhes bata no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ É uma desonra para nós dizer isso, pois pode parecer que fomos fracos.
Mas, se outros agem com ousadia — estou falando como insensato —, eu também ajo com ousadia.

[[v47-11-22]]

^<<v47-11-22,22>>^ Eles são hebreus? Eu também sou. São israelitas? Eu também sou. São descendência^&#42;1^ de Abraão? Eu também sou.

[NOTE]
====
. Lit.: “semente”.
====

[TIP]
====
- *hebreus . . . israelitas . . . descendência de Abraão*: Aqui, Paulo fala de suas próprias origens, talvez porque alguns de seus críticos em Corinto se gabassem de serem de origem judaica. Primeiro, Paulo diz que é hebreu, possivelmente para mostrar que sua família tinha ligação com os patriarcas, como Abraão e Moisés. (Gên 14:13; Êx 2:11; Fil 3:4, 5) Paulo também pode ter dito que era hebreu para chamar atenção ao fato de que sabia falar hebraico. (At 21:40–22:2; 26:14, 15) Depois, Paulo diz que é israelita, uma palavra que às vezes é usada para se referir aos judeus. (At 13:16; Ro 9:3, 4) Por último, Paulo diz especificamente que é descendente de Abraão, destacando que estava entre os que originalmente herdariam as promessas que Deus fez a Abraão. (Gên 22:17, 18) Apesar de mencionar esses pontos, Paulo não dava valor indevido a fatores humanos. — Fil 3:7, 8.
====

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? Respondo como louco: eu o sou ainda mais destacadamente — eu trabalhei mais, fui preso mais vezes, sofri incontáveis golpes e muitas vezes corri perigo de morte;

[[v47-11-24]]

^<<v47-11-24,24>>^ cinco vezes recebi dos judeus 40 golpes menos um,

[TIP]
====
- *dos judeus 40 golpes menos um*: A Lei mosaica autorizava que determinados crimes fossem punidos com golpes. Mas ninguém podia ser punido com mais de 40 golpes, para que não fosse “humilhado”. (De 25:1-3) Para evitar que esse número fosse ultrapassado por engano, a tradição judaica limitava o número de golpes a 39. O fato de Paulo ter recebido a punição máxima mostra que, aos olhos dos judeus, as coisas que ele tinha feito eram muito graves. Pelo visto, Paulo recebeu essa punição em sinagogas ou em tribunais locais associados a elas. (Veja a nota de estudo em Mt 10:17.) Em outras ocasiões, Paulo foi espancado por autoridades de outras nações, que não precisavam seguir os limites impostos pela Lei mosaica. — Veja a nota de estudo em 2Co 11:25.
====

[[v47-11-25]]

^<<v47-11-25,25>>^ três vezes fui espancado com varas, uma vez fui apedrejado, três vezes sofri naufrágio, uma noite e um dia passei em alto-mar;

[TIP]
====
- *três vezes fui espancado com varas*: Este método de punição era comum especialmente entre as autoridades romanas. O livro de Atos menciona apenas uma das “três vezes” que Paulo foi espancado com varas. Esse espancamento aconteceu em Filipos, antes de Paulo escrever sua segunda carta aos coríntios. (At 16:22, 23) Paulo também foi espancado pelos judeus em Jerusalém, mas o relato não diz nada sobre eles terem usado varas. (At 21:30-32) De qualquer forma, visto que Corinto era uma colônia romana, os irmãos ali com certeza sabiam o quanto esse tipo de punição era brutal. Além disso, os romanos tiravam a roupa da vítima antes de espancá-la, tornando o processo todo ainda mais humilhante. (Compare com 1Te 2:2.) Por lei, os cidadãos romanos não podiam sofrer esse tipo de espancamento. Foi por isso que Paulo, que era cidadão romano, informou aos magistrados em Filipos que eles tinham violado seus direitos. — Veja as notas de estudo em At 16:35, 37.
- *apedrejado*: É muito provável que aqui Paulo esteja se referindo ao que aconteceu em Listra, conforme registrado em At 14:19, 20. O apedrejamento era um método de execução mencionado na Lei mosaica. (Le 20:2) É provável que Paulo tenha sido apedrejado por uma turba formada por judeus fanáticos e, talvez, alguns não judeus. Não há dúvida que o objetivo deles era matar Paulo. Na verdade, eles acharam que tinham conseguido isso. É possível que algumas das marcas físicas deixadas pelos ataques brutais mencionados nestes versículos tenham acompanhado Paulo por toda a sua vida.
- *três vezes sofri naufrágio*: A Bíblia descreve em detalhes apenas um naufrágio de Paulo, mas ele aconteceu depois de Paulo ter escrito esta carta. (At 27:27-44) Não é possível saber exatamente em que ocasiões Paulo sofreu esse tipo de desastre, já que ele viajava com frequência pelo mar. (At 13:4, 13; 14:25, 26; 16:11; 17:14, 15; 18:18-22) Paulo também diz: Uma noite e um dia passei em alto-mar (lit.: “no profundo”). É bem provável que isso se refira ao que aconteceu depois de um naufrágio. Ele talvez tenha passado uma noite e um dia inteiros agarrado a um pedaço do barco, sendo jogado de um lado para o outro pelo mar revolto, até ser finalmente resgatado ou lançado na praia. Mesmo assim, Paulo nunca deixou que essas experiências terríveis o impedissem de continuar viajando pelo mar para realizar seu ministério.
====

[[v47-11-26]]

^<<v47-11-26,26>>^ em muitas viagens, em perigos de rios, em perigos de ladrões, em perigos por parte do meu próprio povo, em perigos por parte das nações, em perigos na cidade, em perigos no deserto, em perigos no mar, em perigos entre falsos irmãos,

[TIP]
====
- *em perigos de rios, em perigos de ladrões*: A palavra grega traduzida neste versículo como “rios” foi traduzida como “inundações” em Mt 7:25, 27. Em regiões montanhosas como a Pisídia — por onde Paulo viajou em sua primeira viagem missionária — as chuvas muitas vezes faziam os rios transbordarem, inundando vales e criando correntes de água mortais. A Pisídia também era conhecida por ter bandos de ladrões. Paulo estava disposto a enfrentar esses e outros perigos, não porque fosse imprudente, mas porque confiava que Deus estava guiando seu ministério. (At 13:2-4; 16:6-10; 21:19) O seu desejo de compartilhar as boas novas era maior do que qualquer preocupação que tivesse com seu conforto e segurança. — Compare com Ro 1:14-16; 1Te 2:8.
- *deserto*: Veja o Glossário.
====

[[v47-11-27]]

^<<v47-11-27,27>>^ em grande esforço e trabalho árduo, em muitas noites sem dormir, em fome e sede, frequentemente sem ter o que comer, em frio e sem ter o que vestir.

[TIP]
====
- *sem ter o que vestir*: A palavra grega que aparece aqui é gymnótes (lit.: “nudez”). Ela pode passar a ideia de “não ter roupa suficiente”. (Compare com Tg 2:15; nota de rodapé.) Quando Paulo diz que ficou com “frio e sem ter o que vestir”, ele está se referindo a dificuldades que teve que enfrentar ao realizar seu ministério ou ao lidar com perseguição. Ele pode ter passado por essas coisas ao viajar por regiões frias enfrentando condições climáticas desafiadoras, atravessar rios congelantes, ser assaltado ou ficar preso nas celas frias de uma prisão. — Veja a nota de estudo em 1Co 4:11.
====

[[v47-11-28]]

^<<v47-11-28,28>>^ Além dessas coisas exteriores, há o que diariamente pesa sobre mim:^&#42;1^ a ansiedade por todas as congregações.

[NOTE]
====
. Ou: “há a pressão diária que enfrento”.
====

[TIP]
====
- *a ansiedade*: A palavra grega mérimna, traduzida aqui como “ansiedade”, também pode ser traduzida como “cuidado; preocupação”. A ansiedade que Paulo sentia pelas congregações era imensa. Isso fica claro no fato de ele ter acrescentado essa ansiedade à lista de perigos e dificuldades que ele menciona nos versículos anteriores. (2Co 11:23-27) Paulo mantinha contato com diversos irmãos que o atualizavam sobre o bem-estar espiritual dos cristãos em várias congregações. (2Co 7:6, 7; Col 4:7, 8; 2Ti 4:9-13) Ele se preocupava muito com todos os irmãos e queria que eles continuassem fiéis a Deus até o fim. — Veja a nota de estudo em 1Co 12:25, onde o verbo relacionado merimnáo foi usado com um sentido parecido.
====

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem está fraco, sem que eu também me sinta fraco? Quem tropeça, sem que eu fique enfurecido?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se é preciso que me gabe, eu me gabarei das coisas que mostram a minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, Aquele que deve ser louvado para sempre, sabe que não estou mentindo.

[TIP]
====
- *Aquele que deve ser louvado para sempre*: A construção gramatical desta frase indica que a palavra “Aquele” se refere a Jeová, “o Deus e Pai”, e não ao “Senhor Jesus”. Expressões de louvor parecidas com esta podem ser encontradas em Lu 1:68 (veja a nota de estudo); Ro 1:25; 9:5; 2Co 1:3; Ef 1:3 e 1Pe 1:3.
====

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o governador sob o rei Aretas pôs guardas na cidade dos damascenos para me prender,

[TIP]
====
- *o governador*: Ou: “o etnarca”. Lit.: “o governante de uma nação”. Esta é a única vez que a palavra grega ethnárkhes, traduzida aqui como “governador”, aparece nas Escrituras Gregas Cristãs. Ela se refere a uma posição inferior à de um rei, mas superior à de um tetrarca (governador distrital). (Veja a nota de estudo em Mt 14:1.) O significado da palavra variou ao longo dos séculos. O governador mencionado neste versículo servia como representante do rei Aretas em Damasco, mas não se sabe exatamente quais eram suas atribuições nem qual era sua nacionalidade.
- *o rei Aretas*: O rei árabe Aretas IV governou de 9 a.C. a 40 d.C. A capital de seu reino era a cidade nabateia de Petra, ao sul do Mar Morto, mas Aretas também controlava Damasco. Neste versículo, Paulo está falando de acontecimentos que ocorreram pouco depois de sua conversão. O relato de Lucas em Atos diz que “os judeus tramaram matá-lo”. (At 9:17-25) Mas aqui Paulo atribui esse ataque ao governador local (ou: “etnarca”) de Damasco, que estava debaixo da autoridade do rei Aretas. Não há nenhuma contradição entre esses dois relatos; na verdade, eles se complementam. Certa obra de referência diz: “Os judeus forneceram o motivo; o etnarca, a força militar.”
====

[[v47-11-33]]

^<<v47-11-33,33>>^ mas me fizeram descer num cesto por uma janela na muralha da cidade, e eu escapei das mãos dele.

[TIP]
====
- *cesto*: Ou: “cesto de vime”. Aqui, ao contar aos coríntios sobre sua fuga, Paulo usa a palavra grega sargáne, que se refere a um cesto feito com cordas ou ramos entrelaçados. Pode ser que esse tipo de cesto fosse usado para carregar grandes quantidades de feno, palha ou lã. — Veja a nota de estudo em At 9:25.
- *uma janela*: Este mesmo acontecimento também foi registrado em At 9:25, onde o texto grego diz literalmente “através da muralha”. Mas o fato de o relato aqui falar especificamente de “uma janela” dá base para se traduzir as palavras de At 9:25 como “por uma abertura na muralha”. Alguns sugerem que Paulo foi baixado pela janela da casa de um discípulo que estava localizada na muralha.
====

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]