include::./index.adoc[]

[[v47-6-0]]
=== A Segunda aos Coríntios, 6
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* B. PAULO CONFIRMA SEU AMOR PELOS CRISTÃOS EM CORINTO E FALA DO MINISTÉRIO DELE (1:12–7:16)
* 1. Mudança nos planos de viagem de Paulo (1:12-24)
* Paulo fala de sua conduta em relação aos coríntios (1:12-14)
* Paulo se defende da acusação de não ser confiável (1:15-24)
* 2. O interesse de Paulo no bem-estar dos cristãos em Corinto (2:1-13)
* Paulo deseja dar alegria aos coríntios (2:1-4)
* Um pecador é perdoado e aceito de volta na congregação (2:5-11)
* Paulo não teve alívio porque não encontrou Tito em Trôade (2:12, 13)
* 3. O ministério glorioso de Paulo e de seus companheiros (2:14–4:6)
* O ministério é comparado a um desfile triunfal (2:14-17)
* Cartas de recomendação (3:1-3)
* Deus qualifica cristãos para serem servos do novo pacto (3:4-6)
* A glória do ministério do novo pacto é superior (3:7-18)
* O ministério que faz a luz brilhar por meio do conhecimento glorioso de Deus (4:1-6)
* 4. Mesmo sendo vasos de barro, Paulo e seus companheiros suportam muitas provações (4:7-18)
* Com o poder além do normal é possível suportar dificuldades (4:7-15)
* O sofrimento é momentâneo, mas produz uma glória eterna (4:16-18)
* 5. O desejo de Paulo de receber sua recompensa celestial (5:1-10)
* Corpo espiritual será superior (5:1-5)
* Enquanto estão na Terra, os cristãos ungidos andam pela fé, não pela vista (5:6-10)
* 6. O ministério da reconciliação (5:11–6:2)
* O amor que Cristo mostrou impele os cristãos (5:11-15)
* Os cristãos ungidos estão em união com Cristo e são uma nova criação (5:16-19)
* Embaixadores substituindo a Cristo suplicam: “Sejam reconciliados com Deus” (5:20, 21)
* Não se deve perder de vista o objetivo da bondade imerecida de Deus (6:1, 2)
* 7. Paulo fala de seu ministério (6:3-13)
* Como os cristãos se recomendam como ministros de Deus (6:3-10)
* Paulo fala do carinho que tem pelos irmãos em Corinto (6:11-13)
* 8. Alertas sobre impureza espiritual e idolatria (6:14–7:1)
* “Não se ponham em jugo desigual com descrentes” (6:14-18)
* “Purifiquemo-nos de toda imundície da carne e do espírito” (7:1)
* 9. Paulo se alegra por causa dos coríntios (7:2-16)
* Paulo tem orgulho dos irmãos em Corinto (7:2-4)
* Paulo foi consolado com a presença de Tito e com seu bom relato (7:5-7)
* Tristeza segundo a vontade de Deus e arrependimento levam à salvação (7:8-13a)
* Paulo se alegra ao saber do bom relacionamento entre Tito e os coríntios (7:13b-16)
****

[[v47-6-1]]

^<<v47-6-1,1>>^ Cooperando com ele, também exortamos vocês a não aceitar a bondade imerecida de Deus e perder de vista o objetivo dela.

[TIP]
====
- *Cooperando com ele*: Ou seja, com Deus, como mostra o contexto. Dois versículos antes, Paulo disse o seguinte sobre seu ministério: “[É] como se Deus fizesse um apelo por nosso intermédio.” (2Co 5:20) Essas palavras deixavam claro que quem estava ‘fazendo um apelo’ (em grego, parakaléo) por meio dos ministros cristãos era Deus. Aqui em 2Co 6:1, esse mesmo verbo (parakaléo) aparece na expressão “exortamos vocês a não aceitar [ou: “fazemos um apelo a vocês: não aceitem”]”. Esses versículos reforçam a ideia de que Deus trabalha junto com os ministros cristãos verdadeiros, como era o caso de Paulo e seus companheiros. — Veja a nota de estudo em 1Co 3:9.
- *bondade imerecida*: Veja o Glossário.
- *e perder de vista o objetivo dela*: Em grego, esta expressão inclui uma palavra que significa literalmente “vazio”. Essa palavra também pode ser traduzida como “em vão; sem resultado”. O contexto indica que Deus mostrou bondade imerecida aos cristãos ungidos e deu a eles o privilégio de realizar “o ministério da reconciliação”, servindo como “embaixadores, substituindo a Cristo”. (2Co 5:18-20) Se eles deixassem de realizar seu ministério e de se esforçar para ter a aprovação de Deus durante o “tempo aceitável”, ou “dia de salvação”, eles estariam perdendo de vista o objetivo da bondade imerecida de Deus. — 2Co 6:2.
====

[[v47-6-2]]

^<<v47-6-2,2>>^ Pois ele diz: “Num tempo aceitável ouvi você e num dia de salvação o ajudei.” Vejam, agora é o tempo especialmente aceitável. Vejam, agora é o dia de salvação!

[TIP]
====
- *Pois ele diz*: “Num tempo aceitável ouvi você”: Aqui, Paulo está citando palavras da profecia de Is 49:8. Elas pelo visto foram ditas a Isaías como se ele representasse a nação de Israel, o “servo”. (Is 49:3) A profecia de Isaías era uma profecia de restauração e teve o seu primeiro cumprimento quando a nação de Israel foi libertada de Babilônia. Mas Isaías também profetizou que esse “servo” de Jeová seria dado como um “pacto para o povo” (Is 49:8) e uma ‘luz para as nações, para que a salvação de Deus chegasse até os confins da terra’ (Is 49:6). Isso mostra que essa também era uma profecia sobre o Messias e se aplicava a Jesus Cristo como o “servo” de Deus. (Compare Is 42:1-4, 6, 7 com Mt 12:18-21.) Na profecia, a expressão “tempo de mostrar favor” se refere ao tempo em que Jeová iria responder a seu servo e ajudá-lo. De acordo com isso, durante o tempo em que Jesus esteve na Terra, ele “fez pedidos e súplicas . . . Àquele que era capaz de salvá-lo da morte, e ele foi ouvido por causa do seu temor de Deus”. (He 5:7-9; compare com Lu 22:41-44; 23:46; Jo 12:27, 28; 17:1-5.) Dessa forma, para o Filho de Deus, o “servo” prometido, esse tempo se tornou um “dia de salvação” e um “tempo aceitável [ou: “tempo de mostrar favor”]”. — Compare com a nota de estudo em Lu 4:19.
- *Vejam, agora é o tempo especialmente aceitável. Vejam, agora é o dia de salvação!*: A profecia que Paulo está citando aqui (Is 49:8) era uma profecia de restauração, mas também se aplicava ao Messias. Apesar de o segundo cumprimento da profecia inicialmente ter envolvido apenas Jesus Cristo, Paulo cita essa profecia aqui para indicar que ela também se aplicava aos cristãos. Paulo os incentivou “a não aceitar a bondade imerecida de Deus e perder de vista o objetivo dela”. (2Co 6:1) Os cristãos ungidos tinham se tornado o “Israel de Deus” a partir do Pentecostes de 33 d.C. (Gál 6:16) Mas, para que o “tempo aceitável [ou: “tempo de mostrar favor”]” se tornasse para eles “o dia de salvação”, eles precisavam provar que eram dignos da bondade imerecida de Deus.
====

[[v47-6-3]]

^<<v47-6-3,3>>^ De modo algum damos motivo para tropeço, para que o nosso ministério não seja criticado;

[[v47-6-4]]

^<<v47-6-4,4>>^ mas nós nos recomendamos de todos os modos como ministros de Deus, por perseverar em muitas provações, em tribulações, em tempos de privações, em dificuldades,

[TIP]
====
- *nós nos recomendamos . . . como ministros de Deus*: Nas suas cartas aos cristãos em Corinto, Paulo já tinha chamado a si mesmo e a seus companheiros de “ministros”, ou “servos”. (Veja as notas de estudo em 1Co 3:5; 2Co 3:6.) Aqui, a expressão grega traduzida como “nós nos recomendamos” passa a ideia de “nós provamos (mostramos) que somos”. Alguns homens que estavam se associando com a congregação em Corinto não estavam se mostrando dignos da bondade imerecida de Deus. (2Co 6:1, 3) Paulo e seus companheiros, por outro lado, se recomendavam “de todos os modos” como ministros de Deus.
====

[[v47-6-5]]

^<<v47-6-5,5>>^ em espancamentos, em prisões, em tumultos, em trabalho árduo, em noites sem dormir, em ocasiões sem comer;

[[v47-6-6]]

^<<v47-6-6,6>>^ pela pureza, pelo conhecimento, pela paciência, pela bondade, pelo espírito santo, pelo amor sem hipocrisia,

[[v47-6-7]]

^<<v47-6-7,7>>^ por palavras verdadeiras, pelo poder de Deus; por meio das armas da justiça na mão direita e na esquerda,

[TIP]
====
- *na mão direita e na esquerda*: Parece provável que Paulo esteja aqui se referindo ao modo como os soldados usavam suas armas. Eles normalmente carregavam a espada, sua arma de ataque, na mão direita e o escudo, para sua defesa, na mão esquerda. Paulo usava as armas da justiça, incluindo a palavra de Deus, para lutar em favor da verdade e defender a adoração pura dos ataques feitos contra ela. (2Co 10:4, 5; Ef 6:16, 17; He 4:12) Os inimigos de Paulo recorriam a abuso de poder, engano, calúnia e astúcia para atingir seus objetivos. (2Co 1:24; 10:9; 11:3, 13-15; 12:16, 17) Mas Paulo era diferente; ele se esforçava para usar apenas recursos que fossem justos aos olhos de Deus. (Veja o Glossário, “Justiça”.) Ele queria que todos os ministros cristãos estivessem completamente equipados para realizar o seu importante trabalho.
====

[[v47-6-8]]

^<<v47-6-8,8>>^ por meio de glória e de desonra, por meio de difamação e de boa fama. Somos considerados como enganadores, embora sejamos verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos, embora reconhecidos; como prestes a morrer, mas, vejam, estamos vivos; como castigados,^&#42;1^ embora não entregues à morte;

[NOTE]
====
. Ou: “disciplinados”.
====

[TIP]
====
- *prestes a morrer*: Ou: “considerados merecedores da morte”. Durante seu ministério, Paulo e seus companheiros passaram por muitas situações em que viram a morte de perto. (At 14:19; 1Co 15:30, 31; 2Co 1:8; 4:11; 11:23-27) Mesmo assim, eles podiam dizer: mas, vejam, estamos vivos. Apesar de todas as provações e da perseguição que enfrentaram, eles foram preservados vivos.
====

[[v47-6-10]]

^<<v47-6-10,10>>^ como tristes, mas sempre alegres; como pobres, mas enriquecendo a muitos; como não tendo nada, e ainda assim possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Nós abrimos a nossa boca para falar com vocês, coríntios, e abrimos amplamente o nosso coração.

[TIP]
====
- *Nós abrimos a nossa boca para falar com vocês*: Ou: “Nós falamos abertamente com vocês”. Lit.: “A nossa boca se abriu para vocês”. Em grego, esta é uma expressão idiomática que significa “falar francamente”.
====

[[v47-6-12]]

^<<v47-6-12,12>>^ Não estamos limitando nossos sentimentos por vocês, mas vocês estão limitando seus ternos sentimentos por nós.

[TIP]
====
- *Não estamos limitando nossos sentimentos por vocês*: Ou: “Vocês não ocupam um lugar apertado dentro de nós”. A palavra grega stenokhoréomai, que aparece duas vezes neste versículo, significa literalmente “colocar num lugar estreito”. Um léxico explica o significado das palavras de Paulo aos coríntios da seguinte forma: “Eles não estão confinados em uma pequena área das afeições de Paulo.” Em outras palavras, Paulo estava dizendo que o amor que ele sentia pelos cristãos em Corinto não tinha limites.
- *ternos sentimentos*: A palavra grega que aparece aqui, splágkhnon, se refere literalmente às entranhas de uma pessoa. Em At 1:18, ela foi traduzida como “vísceras”, mas também poderia ter sido traduzida como “intestinos”. Aqui em 2Co 6:12, ela se refere a sentimentos bem profundos, ou emoções intensas. Ela é uma das palavras mais fortes do idioma grego para o sentimento de compaixão.
====

[[v47-6-13]]

^<<v47-6-13,13>>^ Assim, como retribuição — falo como a meus filhos —, abram também amplamente o seu coração.

[TIP]
====
- *abram também amplamente o seu coração*: Ou: “alarguem-se também”. O verbo grego traduzido aqui como “abram . . . amplamente seu coração” significa literalmente “ampliar; dilatar”. (Mt 23:5) Neste versículo, Paulo usa esse verbo em sentido figurado para incentivar os coríntios a aumentar seu amor. Uma obra de referência comenta que, aqui, esse verbo se refere a mostrar “afeto generoso, que se expande”.
====

[[v47-6-14]]

^<<v47-6-14,14>>^ Não se ponham em jugo desigual com descrentes. Pois que afinidade a justiça tem com o que é contra a lei? Ou o que a luz tem em comum com a escuridão?

[TIP]
====
- *Não se ponham em jugo desigual*: Paulo usa aqui uma ilustração que vem da agricultura. O agricultor sabe que não deve pôr em um mesmo jugo dois animais de força ou tamanho muito diferentes. Se ele fizer isso, o animal mais fraco vai sofrer para acompanhar o mais forte, e o mais forte terá que levar a maior parte da carga. É provável que Paulo estivesse pensando em De 22:10, onde a Lei mosaica proibia os israelitas de ararem com um touro e um jumento no mesmo jugo. Ele usou esse princípio para ilustrar como seria ruim para a espiritualidade dos cristãos se eles se unissem a pessoas que não faziam parte da congregação cristã. Por exemplo, se um cristão casasse com alguém que não é cristão, os dois estariam em um jugo desigual. Nos assuntos espirituais, eles não estariam unidos em pensamentos e ações.
- *jugo desigual*: Esta é a única vez que o verbo grego heterozygéo aparece nas Escrituras Gregas Cristãs. Ele significa literalmente “estar em jugo diferente”. Um verbo relacionado, synzeúgnymi, foi usado em Mt 19:6 e Mr 10:9 na expressão “o que Deus pôs sob o mesmo jugo [ou: “juntou”]”. Os dois verbos estão relacionados com a palavra grega para “jugo”, zygós.
====

[[v47-6-15]]

^<<v47-6-15,15>>^ Além disso, que harmonia há entre Cristo e Belial? Ou o que o crente tem em comum com o descrente?

[TIP]
====
- *harmonia*: Ou: “acordo”. A palavra grega que aparece aqui, symfónesis, significa literalmente “som junto”. Quando usada em sentido literal, ela pode se referir à harmonia produzida por instrumentos musicais. Um léxico define symfónesis como “um estado em que se compartilham interesses”. A resposta óbvia para a primeira pergunta retórica de Paulo neste versículo é: “É claro que não existe absolutamente nenhuma harmonia, ou acordo, entre Cristo e Satanás.”
- *Belial*: Esta é a única vez que o nome Belial (usado para se referir a Satanás) aparece nas Escrituras Gregas Cristãs. Nos manuscritos gregos, esse nome é escrito Belíar, e algumas traduções seguem essa forma do nome. Mas esse nome corresponde à palavra hebraica beliyáʽal, que significa “imprestável; sem valor”. Essa palavra hebraica é usada para classificar ideias, palavras e conselhos (De 15:9, onde ela foi traduzida como “mau”; Sal 101:3; Na 1:11) e também para se referir a algo “terrível” (Sal 41:8). Mas, na maioria das vezes, ela é usada para se referir a pessoas sem valor, ou homens do pior tipo, como, por exemplo, os que induziam o povo de Jeová a adorar outros deuses. (De 13:13) Essa palavra também foi usada em vários versículos para se referir a homens maus. (Jz 19:22-27; 20:13; 1Sa 25:17, 25; 2Sa 20:1; 22:5; 1Rs 21:10, 13) No século 1 d.C., Belial era usado como um nome descritivo para Satanás. Aqui em 2Co 6:15, a Peshitta siríaca diz “Satanás”. Paulo normalmente chamava o adversário de Deus de Satanás (Ro 16:20; 2Co 2:11), mas também se referia a ele como “Diabo” (Ef 6:11; 1Ti 3:6), “Maligno” (2Te 3:3) e “deus deste mundo” (2Co 4:4).
- *o que o crente tem em comum com o descrente?*: Ou: “que parte tem o crente com o descrente?” Esta pergunta inclui a palavra grega merís, que significa “parte; porção”. A palavra merís também aparece em At 8:21, onde tem um sentido parecido e foi traduzida como “participação”.
- *o crente . . . o descrente*: Ou: “uma pessoa fiel . . . uma pessoa infiel”. A palavra grega traduzida aqui como “o crente” é pistós. Ela pode se referir a uma pessoa que confia, ou tem fé, em alguém ou alguma coisa. Mas essa mesma palavra grega também pode ser usada para se referir a uma pessoa que é vista por outros como alguém fiel, ou confiável. Em alguns casos, como acontece aqui, os dois sentidos são possíveis.
====

[[v47-6-16]]

^<<v47-6-16,16>>^ E que acordo há entre o templo de Deus e os ídolos? Pois nós somos templo de um Deus vivente, como Deus disse: “Residirei entre eles e andarei entre eles, e eu serei o seu Deus, e eles serão o meu povo.”

[TIP]
====
- *como Deus disse*: Neste contexto, Paulo cita ou faz referência a vários versículos das Escrituras Hebraicas para mostrar que o ponto de vista de Deus sobre a pureza espiritual sempre foi o mesmo. Aqui no versículo 16, Paulo está fazendo referência a Le 26:11, 12 e Ez 37:27.
====

[[v47-6-17]]

^<<v47-6-17,17>>^ “‘Portanto, saiam do meio deles e separem-se’, diz Jeová, ‘e parem de tocar em coisa impura’”; “‘e eu os acolherei’”.

[TIP]
====
- *Portanto, saiam do meio deles*: Nesta passagem (2Co 6:14–7:1), Paulo mostra aos cristãos em Corinto a importância de não entrarem em jugo desigual com descrentes e de se manterem puros. Aqui no versículo 17, ele está citando Is 52:11, onde Isaías foi inspirado a dar uma ordem profética aos judeus que seriam mais tarde libertados de Babilônia. Quando foram libertados em 537 a.C., os judeus que voltaram para Jerusalém levaram com eles os utensílios sagrados que o rei Nabucodonosor tinha tirado do templo. Para realizar essa tarefa, eles precisaram se purificar tanto por fora (dando os passos necessários para estar limpos em sentido cerimonial) como por dentro (livrando-se de qualquer vestígio de adoração falsa e mantendo o coração puro). De forma parecida, os cristãos em Corinto tinham que se manter longe dos templos impuros da religião falsa e de qualquer forma de idolatria. Eles precisavam ‘se purificar de toda imundície da carne e do espírito’. — 2Co 7:1.
- *diz Jeová*: Neste versículo, Paulo cita diferentes partes de Is 52:11, onde o contexto deixa claro que Jeová Deus é a Fonte da mensagem. (Is 52:4, 5) Ao fazer isso, Paulo inclui uma expressão grega que foi usada centenas de vezes na Septuaginta para traduzir expressões hebraicas que significam “diz Jeová” e “assim diz Jeová”. Alguns exemplos estão em Is 1:11; 48:17; 49:18 (citado em Ro 14:11); 52:4, 5. — Veja o Apêndice C3 (introdução e 2Co 6:17).
- *e eu os acolherei*: Ou: “e eu os receberei”. Aqui, Paulo pelo visto está citando as palavras de Ez 20:41, conforme elas aparecem na Septuaginta.
====

[[v47-6-18]]

^<<v47-6-18,18>>^ “‘E eu me tornarei pai para vocês, e vocês se tornarão filhos e filhas para mim’, diz Jeová, o Todo-Poderoso.”

[TIP]
====
- *diz Jeová, o Todo-Poderoso*: Neste versículo, Paulo pelo visto está citando palavras de 2Sa 7:14 e Is 43:6. As palavras traduzidas aqui como “diz Jeová, o Todo-Poderoso” parecem ser uma citação do texto de 2Sa 7:8, conforme ele aparece na Septuaginta. Nesse versículo de 2 Samuel, o texto hebraico original diz: “Assim diz Jeová dos exércitos.” Aqui e no contexto, Paulo cita diversas passagens das Escrituras Hebraicas para mostrar aos cristãos a importância de se manterem longe da adoração falsa e dos ídolos, que são objetos sem vida e não têm nenhum poder. Dessa forma, os cristãos estariam em condições de ser considerados “filhos e filhas” de “Jeová, o Todo-Poderoso”. — Veja os Apêndices C1 e C2.
- *o Todo-Poderoso*: O título grego que aparece aqui é Pantokrátor. Ele também poderia ter sido traduzido como “o Governante de Todos; Aquele Que Tem Todo o Poder”. Aqui e no contexto, Paulo cita diversas passagens das Escrituras Hebraicas para mostrar aos cristãos a importância de se manterem longe da adoração falsa e dos ídolos, que são objetos sem vida e não têm nenhum poder. (2Co 6:16) Se fizessem isso, os cristãos de Corinto estariam em condições de ser considerados filhos do “Todo-Poderoso”. Esta é a primeira das dez vezes que Pantokrátor aparece nas Escrituras Gregas Cristãs; as outras nove estão em Apocalipse. — Ap 1:8; 4:8; 11:17; 15:3; 16:7, 14; 19:6, 15; 21:22.
====

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]