include::./index.adoc[]

[[v47-9-0]]
=== A Segunda aos Coríntios, 9
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. COLETA PARA AJUDAR IRMÃOS POBRES NA JUDEIA (8:1–9:15)
* A generosidade dos cristãos da Macedônia é um exemplo para os coríntios (8:1-7)
* Paulo incentiva “uma compensação” de recursos (8:8-15)
* Tito é enviado a Corinto para ajudar na coleta (8:16-24)
* A prontidão é importante (9:1-5)
* Paulo incentiva a generosidade: “Deus ama quem dá com alegria” (9:6-14)
* A “indescritível dádiva” de Deus (9:15)
****

[[v47-9-1]]

^<<v47-9-1,1>>^ A respeito do serviço^&#42;1^ em favor dos santos, não é de todo necessário que eu lhes escreva,

[NOTE]
====
. Ou: “ministério”.
====

[[v47-9-2]]

^<<v47-9-2,2>>^ pois conheço a sua prontidão e dela falo com orgulho aos macedônios, dizendo que a Acaia já está pronta há um ano, e o zelo de vocês estimulou a maioria deles.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas estou enviando os irmãos, para que o orgulho que temos de vocês nesse respeito não se mostre infundado, e para que vocês estejam realmente prontos, assim como eu disse que estariam.

[TIP]
====
- *estou enviando os irmãos*: Veja a nota de estudo em 1Co 16:3.
====

[[v47-9-4]]

^<<v47-9-4,4>>^ Senão, se os macedônios fossem comigo e não os achassem prontos, nós — para não mencionar vocês — ficaríamos envergonhados por ter tido confiança em vocês.

[[v47-9-5]]

^<<v47-9-5,5>>^ Por isso achei necessário incentivar os irmãos a ir visitá-los antes e a aprontar com antecedência a sua prometida dádiva generosa, para que estivesse pronta como algo dado com generosidade, e não à força.

[TIP]
====
- *não à força*: A palavra grega traduzida aqui como “à força” é geralmente traduzida como “ganância”. (Lu 12:15; Ro 1:29; Ef 4:19; 5:3; Col 3:5) Assim, as palavras de Paulo dão a entender que ele e seus companheiros não estavam realizando aquela coleta com a motivação errada, por ganância. Ele não pressionou os cristãos em Corinto a contribuírem para o serviço de ajuda, fazendo com que eles se sentissem explorados ou obrigados a dar algo. Qualquer donativo que fizessem deveria ser voluntário, motivado pela generosidade deles e feito com alegria. — 2Co 9:7.
====

[[v47-9-6]]

^<<v47-9-6,6>>^ Mas, quanto a isso, quem semear parcimoniosamente colherá também parcimoniosamente, e quem semear generosamente colherá também generosamente.

[TIP]
====
- *quem semear generosamente colherá também generosamente*: Neste contexto, a expressão “semear generosamente” passa a ideia de semear uma abundância de bênçãos ou benefícios materiais. Aqui, Paulo está incentivando os cristãos em Corinto a contribuírem generosamente para o serviço de ajuda aos irmãos de Jerusalém. (Ro 15:26; 2Co 8:4; 9:1, 7) Esses irmãos pelo visto tinham enfrentado grandes dificuldades, talvez chegando a perder muitos de seus bens por causa da perseguição que sofreram às mãos dos judeus. (1Te 2:14) As palavras de Paulo indicam que, por semear generosamente, os cristãos em Corinto ‘colheriam também generosamente’. Eles seriam abençoados com o favor e a bondade imerecida de Deus, além de ter a garantia de que Deus cuidaria das necessidades materiais deles. (2Co 9:8, 10) Todos os envolvidos se sentiriam motivados a louvar e agradecer a Deus, alguns pelo privilégio de dar ajuda e outros por receber a ajuda de que precisavam. — 2Co 9:11-14.
====

[[v47-9-7]]

^<<v47-9-7,7>>^ Faça cada um conforme resolveu no coração, não a contragosto nem por obrigação, pois Deus ama quem dá com alegria.

[TIP]
====
- *resolveu no coração*: Estas palavras mostram que Paulo confiava que os coríntios desejavam contribuir para o serviço de ajuda aos irmãos necessitados da Judeia. (2Co 8:4, 6, 10; 9:1, 2) Mas eles precisavam transformar seu zelo e seu desejo de ajudar em ação. (2Co 9:3-5) A intenção de Paulo não era pressionar os coríntios a contribuir. Afinal, uma pessoa que é forçada a dar algo dificilmente faz isso “com alegria”. Na verdade, Paulo acreditava que eles já tinham tomado a decisão de dar. A palavra grega traduzida aqui como “resolveu” significa “decidir previamente; escolher com antecedência”. Assim, Paulo mostra que os cristãos verdadeiros primeiro consideram as necessidades de seus irmãos e analisam como podem contribuir para suprir essas necessidades; daí eles agem.
- *não a contragosto*: Ou: “não com relutância”. A expressão grega traduzida aqui como “a contragosto” significa literalmente “com tristeza (pesar)”.
- *por obrigação*: A expressão grega que aparece aqui significa literalmente “por necessidade” ou “sob pressão”. Quando uma pessoa é forçada a dar algo ou se sente pressionada a fazer isso, ela não sente a verdadeira felicidade que vem do ato de dar. Assim, Paulo indica que na congregação cristã daquela época as contribuições deviam ser feitas de modo completamente voluntário. — Compare com De 15:10.
- *Deus ama quem dá com alegria*: Deus fica muito feliz quando um cristão pratica o dar com a motivação correta, seja para apoiar a adoração verdadeira seja para ajudar seus irmãos. A pessoa ‘que dá com alegria’ sente verdadeira felicidade pelo simples fato de poder dar algo a alguém. Ao longo da história, os servos de Deus têm sentido a alegria que vem de dar de si mesmos e de seus recursos para apoiar a adoração de Jeová. Por exemplo, os israelitas dos dias de Moisés apoiaram com alegria a construção do tabernáculo. Todos os que tinham “coração disposto” deram ouro, prata, madeira, linho e outras coisas de forma voluntária como uma “contribuição a Jeová”. (Êx 35:4-35; 36:4-7) Séculos mais tarde, o rei Davi, os príncipes, os chefes e outros membros da nação de Israel contribuíram generosamente para o templo de Jeová, que foi construído por Salomão, filho de Davi. — 1Cr 29:3-9.
====

[[v47-9-8]]

^<<v47-9-8,8>>^ Além do mais, Deus é capaz de tornar abundante para vocês toda a Sua bondade imerecida, para que sempre sejam plenamente autossuficientes em tudo, e também tenham bastante para toda boa obra.

[[v47-9-9]]

^<<v47-9-9,9>>^ (Assim como está escrito: “Ele distribui amplamente; dá aos pobres. Sua justiça permanece para sempre.”

[TIP]
====
- *Ele distribui amplamente*: Ao falar sobre dar ajuda a cristãos em necessidade, Paulo cita neste versículo o Sal 112:9 conforme ele aparece na Septuaginta (111:9, LXX). Tanto a palavra grega usada aqui e na Septuaginta como a palavra hebraica que aparece no texto original desse salmo significam literalmente “espalhar”. Aqui neste contexto, essa palavra passa a ideia de dar ou distribuir de forma abundante ou generosa. Assim, ela também poderia ser traduzida como “ele distribui generosamente”. A pessoa que é generosa de verdade não fica com medo de cair na pobreza por causa de sua generosidade, mesmo que em algumas situações dê aos outros mais do que sua condição financeira realmente permita. — 2Co 9:8, 10.
- *Sua justiça*: Aqui, Paulo continua citando as Escrituras Hebraicas. (Veja a nota de estudo em Ele distribui amplamente neste versículo.) Quem realiza atos de bondade que beneficiam outros, como ajudar generosamente os pobres, mostra que tem a qualidade da “justiça”. A pessoa que abre mão de suas preferências pessoais para viver de acordo com a vontade de Deus e com os padrões dele tem a perspectiva de fazer isso para sempre. — Compare com Mt 6:1, 2, 33.
====

[[v47-9-10]]

^<<v47-9-10,10>>^ Aquele que fornece abundantemente semente ao semeador e pão como alimento também fornecerá e multiplicará a semente para vocês semearem e aumentará a colheita da justiça de vocês.)

[[v47-9-11]]

^<<v47-9-11,11>>^ Em tudo vocês estão sendo enriquecidos para praticar todo tipo de generosidade, a qual, por nosso intermédio, produz agradecimentos a Deus;

[[v47-9-12]]

^<<v47-9-12,12>>^ porque esse serviço que estão prestando não somente suprirá adequadamente as necessidades dos santos, mas também se tornará uma abundante fonte de agradecimentos a Deus.

[TIP]
====
- *esse serviço que estão prestando*: Ou: “o ministério desse serviço público”. A palavra grega traduzida aqui como “serviço” é leitourgía. Ela também pode ser traduzida como “serviço público”. Neste versículo, Paulo usa leitourgía para se referir ao ministério, ou serviço de ajuda, que estava sendo realizado em benefício dos cristãos judeus de Jerusalém e da Judeia. A palavra leitourgía e as palavras relacionadas leitourgéo (“prestar serviço público”) e leitourgós (“servidor público”) eram usadas pelos gregos e romanos para se referir a serviços prestados ao governo ou a autoridades civis em benefício do povo. Nas Escrituras Gregas Cristãs, essas palavras gregas são usadas muitas vezes para se referir ao serviço que era prestado no templo e ao ministério cristão. — Para ver exemplos desse uso, veja as notas de estudo em Lu 1:23; At 13:2; Ro 13:6; 15:16.
====

[[v47-9-13]]

^<<v47-9-13,13>>^ Eles glorificam a Deus, pois esse serviço de ajuda prova que vocês são submissos às boas novas a respeito do Cristo, conforme declararam publicamente, e que são generosos na sua contribuição para eles e para todos.

[TIP]
====
- *serviço de ajuda*: Ou: “ministério”. A palavra grega que aparece aqui é muitas vezes traduzida como “ministério”. Isso mostra que prestar ajuda a irmãos necessitados é uma parte muito importante do ministério cristão e é um “serviço sagrado”. — Ro 12:1, 7; veja as notas de estudo em At 11:29; Ro 15:31; 2Co 8:4.
- *contribuição*: A palavra grega koinonía tem o sentido básico de “partilhar”, mas o seu significado varia de acordo com o contexto. (Veja as notas de estudo em At 2:42; 1Co 1:9.) Aqui, ela passa a ideia de que aquele que dá é motivado por um sentimento de companheirismo. A mesma palavra foi usada com um sentido parecido em He 13:16, que diz: “Não se esqueçam de fazer o bem e de partilhar com outros o que vocês têm, pois Deus se agrada desses sacrifícios.”
====

[[v47-9-14]]

^<<v47-9-14,14>>^ E, com súplicas a favor de vocês, eles expressam que os amam, por causa da extraordinária bondade imerecida de Deus para com vocês.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças sejam dadas a Deus por Sua indescritível dádiva.^&#42;1^

[NOTE]
====
. Ou: “dádiva gratuita”.
====

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]