include::./index.adoc[]

[[v47-12-0]]
=== A Segunda aos Coríntios, 12
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* D. ARGUMENTOS PARA COMBATER A INFLUÊNCIA DE FALSOS APÓSTOLOS (10:1–12:21)
* 1. Paulo defende seu ministério (10:1-18)
* Armas que não são carnais, mas são poderosas em Deus (10:1-6)
* Paulo se defende das acusações de ser fraco (10:7-12)
* Paulo se orgulha apenas do que realizava dentro dos limites de seu território (10:13-18)
* 2. Paulo e os superapóstolos (11:1-15)
* Paulo tem ciúme semelhante ao de Deus; ele quer apresentar os coríntios como “virgem casta” ao Cristo (11:1-5)
* Paulo está decidido a não se tornar um fardo para ninguém (11:6-15)
* 3. Dificuldades de Paulo como apóstolo (11:16-33)
* 4. Visões de Paulo e seu “espinho na carne” (12:1-21)
* Visão do terceiro céu e do paraíso (12:1-7a)
* Paulo fala de seu “espinho na carne” e da bondade imerecida de Deus (12:7b-10)
* Paulo não é inferior aos superapóstolos (12:11-13)
* Preocupação de Paulo com os coríntios (12:14-21)
****

[[v47-12-1]]

^<<v47-12-1,1>>^ Tenho de me gabar. Não há nada a ganhar com isso, mas passarei às visões sobrenaturais e revelações da parte do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em união com Cristo que, há 14 anos — quer no corpo, quer fora do corpo, não sei; Deus sabe —, foi arrebatado ao terceiro céu.

[TIP]
====
- *um homem*: Paulo não diz o nome do homem que teve essa visão sobrenatural, mas o contexto indica fortemente que ele está falando de si mesmo. Paulo vinha fazendo uma defesa de suas qualificações como apóstolo, que estavam sendo atacadas pelos “superapóstolos” e outros opositores. (2Co 11:5, 23) Daí, em 2Co 12:1, Paulo cita como prova de suas qualificações as “visões sobrenaturais e revelações da parte do Senhor” que ele recebia. Além disso, a Bíblia não fala de outra pessoa ter sido arrebatada ao terceiro céu. Assim, parece lógico concluir que o homem mencionado aqui seja o próprio Paulo.
- *ao terceiro céu*: Nas Escrituras, a palavra “céu” pode ter diferentes sentidos. Ela pode se referir ao céu físico (visível) ou ao céu espiritual (invisível), o lugar onde Jeová e os anjos moram. (Gên 11:4; Is 63:15) Mas ela pode também se referir a um governo, tanto humano como de Deus. (Is 14:12; Da 4:25, 26) Pelo visto, aqui Paulo está se referindo a algo que foi revelado a ele sobre o futuro por meio de uma visão. (2Co 12:1) Às vezes, as Escrituras usam o número três ou repetem três vezes algo para dar força ou peso ao que está sendo dito. (Is 6:3; Ez 21:27; Ap 4:8) Assim, parece que o “terceiro céu” que Paulo viu é um governo superior: o Reino messiânico de Deus, formado por Jesus Cristo e os 144.000 escolhidos para reinar com ele nos céus. — Is 65:17; 66:22; 2Pe 3:13; Ap 14:1-5.
====

[[v47-12-3]]

^<<v47-12-3,3>>^ Sim, conheço esse homem que — quer no corpo, quer separado do corpo, não sei; Deus sabe —

[[v47-12-4]]

^<<v47-12-4,4>>^ foi arrebatado para o paraíso e ouviu palavras que não podem ser ditas e que não se permite ao homem falar.

[TIP]
====
- *paraíso*: A palavra grega usada aqui, parádeisos, aparece três vezes nas Escrituras Gregas Cristãs. (Lu 23:43, veja a nota de estudo; 2Co 12:4; Ap 2:7) Existem palavras semelhantes em hebraico (pardés, em Ne 2:8; Ec 2:5; Cân 4:13) e em persa (pairidaeza). O sentido básico das palavras para “paraíso” nesses três idiomas é o de um lindo jardim semelhante a um parque. Aqui, parádeisos pode significar várias coisas. (Veja a nota de estudo em 2Co 12:2.) Paulo pode estar se referindo (1) ao Paraíso literal que vai existir na Terra, (2) à condição espiritual que vai existir entre o povo de Deus naquela época e (3) às condições maravilhosas no céu. No novo mundo, esses três “paraísos” vão existir ao mesmo tempo. Nos dias de Paulo, não era permitido falar dessas coisas porque ainda não tinha chegado o tempo de Deus para revelar detalhes sobre como o propósito dele se realizaria.
====

[[v47-12-5]]

^<<v47-12-5,5>>^ Eu me gabarei desse homem, mas não me gabarei de mim mesmo, a não ser das minhas fraquezas.

[TIP]
====
- *desse homem*: Ou, possivelmente: “dessa coisa”. Ou seja, desse acontecimento. — Veja a nota de estudo em 2Co 12:2.
====

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, mesmo que eu quisesse me gabar, eu não seria insensato, porque diria a verdade. Mas evito fazer isso para que ninguém me dê crédito por algo além do que vê em mim ou do que ouve de mim,

[[v47-12-7]]

^<<v47-12-7,7>>^ só porque recebo essas revelações extraordinárias.
Para impedir que eu ficasse enaltecido demais, foi-me dado um espinho na carne, um anjo de Satanás, para me esbofetear continuamente, a fim de que eu não me enaltecesse demais.

[TIP]
====
- *extraordinárias*: Aqui, Paulo usa a palavra grega hyperbolé para descrever as revelações que recebeu, passando a ideia de que elas eram “extraordinárias”, ou fora do comum. (Veja a nota de estudo em 2Co 12:2.) Essa palavra grega aparece oito vezes nas Escrituras Gregas Cristãs, sempre nas cartas de Paulo. Ela foi traduzida de diferentes maneiras, de acordo com o contexto. Por exemplo, em 2Co 4:7, essa palavra aparece na expressão “poder além do normal”. E, em 2Co 1:8, onde Paulo fala da tribulação que ele e seus companheiros passaram, ele usa hyperbolé na expressão “extrema pressão”.
- *um espinho na carne*: Aqui, Paulo usa essa metáfora para representar uma aflição constante. Um espinho que não é retirado causa dor persistente. (A palavra grega traduzida aqui como “espinho” podia se referir a qualquer coisa que fosse pontuda, como, por exemplo, uma estaca pontiaguda, uma farpa ou um espinho.) Não é possível ter certeza se Paulo está se referindo a uma dor física ou emocional. Algumas declarações nas cartas de Paulo podem dar a entender que ele sofria de problemas de visão. Com um problema desse tipo, seria mais difícil para Paulo fazer suas viagens, escrever cartas e realizar seu ministério. (Gál 4:15; 6:11; veja também At 23:1-5.) Mas, já que no contexto deste versículo Paulo estava falando da oposição constante de falsos instrutores, também é possível que o espinho se referisse ao estresse e à ansiedade que ele sofria por causa dos ataques desses opositores arrogantes. (Veja a nota de estudo em 2Co 11:5.) De qualquer forma, Paulo chama a fonte dessa dor de um anjo de Satanás, dando a entender que Satanás tenta usar toda aflição, seja física seja emocional, para desanimar os servos de Deus. Paulo procurou ter um ponto de vista positivo de sua provação, dizendo que esse “espinho” impedia que ele ficasse enaltecido demais. Em outras palavras, ter de lidar com esse “espinho” o ajudava a continuar humilde e, assim, agradar a Deus. — Mt 23:12.
- *esbofetear*: Ou: “espancar”. O verbo grego que Paulo usa aqui pode ter o sentido literal de bater com a mão aberta, com as juntas dos dedos ou com os punhos fechados. Ele foi usado nesse último sentido em Mt 26:67, que diz que os soldados romanos “esmurraram” Jesus. Em 1Co 4:11, ele foi usado com um sentido mais amplo, passando a ideia de maltratar.
====

[[v47-12-8]]

^<<v47-12-8,8>>^ Três vezes supliquei ao Senhor, pedindo que isso se afastasse de mim.

[TIP]
====
- *ao Senhor*: Aqui, Paulo usa a expressão grega ton Kýrion (“o Senhor”), que algumas vezes é usada para se referir a Jeová e outras vezes para se referir a Jesus. Neste versículo, parece lógico que Paulo esteja dizendo que fez três súplicas ao Senhor Jeová, o “Ouvinte de oração”. (Sal 65:2) Afinal, é a Jeová que todas as orações devem ser dirigidas. (Sal 145:18; Fil 4:6) Além disso, na resposta a Paulo, o Senhor mencionou sua “bondade imerecida” e seu “poder”, coisas que Jeová dá generosamente aos seus servos. (2Co 12:9; Is 40:26; Lu 24:49) Alguns chamam atenção ao fato de que, no versículo 9, Paulo também fala sobre “o poder do Cristo”. Mas isso não significa que Paulo fez esses três pedidos a Cristo. Sem dúvida, Jesus é poderoso, mas seu poder vem da Fonte de todo o poder divino, Jeová. — Lu 5:17.
====

[[v47-12-9]]

^<<v47-12-9,9>>^ Mas ele me disse: “A minha bondade imerecida é suficiente para você, pois o meu poder está sendo aperfeiçoado na fraqueza.” Com muita alegria, então, eu me gabarei das minhas fraquezas, para que o poder do Cristo permaneça sobre mim como uma tenda.

[[v47-12-10]]

^<<v47-12-10,10>>^ Assim, tenho prazer em fraquezas, em insultos, em privações, em perseguições e dificuldades, por Cristo. Pois, quando estou fraco, então é que sou poderoso.

[[v47-12-11]]

^<<v47-12-11,11>>^ Tornei-me insensato. Vocês me obrigaram a isso, porque deveriam ter me recomendado. Pois não me mostrei em coisa alguma inferior aos seus superapóstolos, embora eu não seja nada.

[TIP]
====
- *insensato*: Veja a nota de estudo em 2Co 11:1.
====

[[v47-12-12]]

^<<v47-12-12,12>>^ De fato, os sinais que identificam um apóstolo foram produzidos entre vocês com grande perseverança, e por sinais, milagres e obras poderosas.

[TIP]
====
- *milagres*: Ou: “presságios”. — Veja a nota de estudo em At 2:19.
====

[[v47-12-13]]

^<<v47-12-13,13>>^ Pois em que é que vocês foram menos favorecidos do que as outras congregações, a não ser no fato de que eu mesmo não me tornei um fardo para vocês? Perdoem-me bondosamente essa injustiça.

[[v47-12-14]]

^<<v47-12-14,14>>^ Vejam, esta é a terceira vez que estou pronto para ir visitá-los, e não me tornarei um fardo. Pois estou buscando não os seus bens, mas a vocês; porque não se espera que os filhos acumulem para os pais, mas sim os pais para os filhos.

[TIP]
====
- *a terceira vez*: Aqui, Paulo fala que essa era a terceira vez que ele estava pronto para visitar Corinto, e não que essa seria a terceira visita dele. Ele estava “pronto” no sentido de que desejava visitar os irmãos de Corinto. Mas ele precisava das circunstâncias adequadas. Da primeira vez, ele conseguiu ir para Corinto e deu início à congregação ali, permanecendo na cidade por um ano e meio. (At 18:9-11) Da segunda vez, Paulo planejou visitar Corinto, mas seus planos não deram certo. (2Co 1:15, 16, 23) As evidências indicam que o intervalo entre a escrita das duas cartas inspiradas aos coríntios foi bem curto, menor do que seria necessário para Paulo ter feito uma visita a eles. Além disso, o livro de Atos fala de apenas uma visita. (At 18:1) Aqui e em 2Co 13:1, 2, Paulo menciona a terceira vez que planejou ir a Corinto. Essa visita realmente aconteceu, por volta de 56 d.C. Foi dali que ele escreveu o livro de Romanos. — At 20:2, 3; Ro 16:1, 23; 1Co 1:14.
====

[[v47-12-15]]

^<<v47-12-15,15>>^ Quanto a mim, de muito boa vontade gastarei e serei completamente gasto a favor de vocês. Se os amo tanto, deveria eu ser amado menos?

[TIP]
====
- *gasto a favor de vocês*: Aqui, o texto grego diz literalmente “gasto a favor das suas almas”. Neste contexto, a palavra grega psykhé, que foi traduzida como “alma” nas edições anteriores da Tradução do Novo Mundo, se refere a pessoas. — Veja o Glossário, “Alma”.
====

[[v47-12-16]]

^<<v47-12-16,16>>^ Mas, seja como for, não os sobrecarreguei. No entanto, vocês dizem que fui “ardiloso” e que os apanhei “com astúcia”.

[[v47-12-17]]

^<<v47-12-17,17>>^ Será que me aproveitei de vocês por meio de algum daqueles que lhes enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Insisti com Tito para que visitasse vocês e enviei o irmão com ele. Será que Tito se aproveitou de vocês? Por acaso não andamos no mesmo espírito, nas mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Vocês pensaram durante todo esse tempo que estávamos fazendo a nossa defesa perante vocês? É perante Deus que estamos falando, em união com Cristo. Mas, amados, tudo o que fazemos é para edificar vocês.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois receio que, quando eu chegar aí, talvez não os encontre como eu queria, e eu não seja como vocês queriam, mas, em vez disso, que eu encontre brigas, ciúme, acessos de ira, discórdias, calúnias, cochichos, demonstrações de orgulho e desordens.

[TIP]
====
- *cochichos*: Ou: “fofocas”. A palavra grega que aparece aqui passa a ideia de uma informação negativa ou um boato que alguém espalha secretamente. Esta é a única vez que essa palavra grega foi usada nas Escrituras Gregas Cristãs, mas uma palavra relacionada aparece numa lista de atitudes ruins em Ro 1:29, onde foi traduzida como “cochichadores” (veja a nota de estudo). Além disso, o verbo grego para “cochichar” foi usado em sentido negativo na Septuaginta em 2Sa 12:19 e Sal 41:7 (40:8, LXX).
====

[[v47-12-21]]

^<<v47-12-21,21>>^ Talvez, quando eu for novamente, meu Deus me humilhe diante de vocês, e eu tenha de chorar por muitos que anteriormente pecaram e não se arrependeram da impureza, da imoralidade sexual e da conduta insolente que praticaram.

[TIP]
====
- *impureza*: A palavra grega que aparece aqui é akatharsía. Dos três termos gregos alistados neste versículo (traduzidos como “impureza”, “imoralidade sexual” e “conduta insolente”), akatharsía é o que tem sentido mais amplo. Essa palavra se refere literalmente a algo impuro, ou imundo. (Mt 23:27) Em sentido figurado, ela se refere a qualquer tipo de impureza — em assuntos sexuais, em assuntos espirituais, em palavra ou em ação. (Compare com 1Co 7:14; 2Co 6:17; 1Te 2:3.) “Impureza” pode se referir a diferentes tipos de comportamentos errados e pode ter diferentes níveis de gravidade. (Ef 4:19) A palavra grega dá destaque ao fato de que a conduta errada ou a condição da pessoa é repugnante em sentido moral. — Veja o Glossário, “Impuro”, e a nota de estudo em Gál 5:19.
- *imoralidade sexual*: A palavra grega porneía é um termo genérico usado para se referir a todas as formas de relações sexuais que a Bíblia condena, incluindo adultério, sexo entre pessoas que não são casadas e entre pessoas do mesmo sexo, além de outros tipos de pecados sexuais. — Veja o Glossário e a nota de estudo em Gál 5:19.
- *conduta insolente*: Ou: “conduta desavergonhada”. A palavra grega que aparece aqui, asélgeia, indica um tipo de conduta que viola gravemente as leis de Deus e que reflete uma atitude descarada ou atrevida de desrespeito. — Veja o Glossário e a nota de estudo em Gál 5:19.
====

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]