include::./index.adoc[]

[[v47-5-0]]
=== A Segunda aos Coríntios, 5
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* B. PAULO CONFIRMA SEU AMOR PELOS CRISTÃOS EM CORINTO E FALA DO MINISTÉRIO DELE (1:12–7:16)
* 1. Mudança nos planos de viagem de Paulo (1:12-24)
* Paulo fala de sua conduta em relação aos coríntios (1:12-14)
* Paulo se defende da acusação de não ser confiável (1:15-24)
* 2. O interesse de Paulo no bem-estar dos cristãos em Corinto (2:1-13)
* Paulo deseja dar alegria aos coríntios (2:1-4)
* Um pecador é perdoado e aceito de volta na congregação (2:5-11)
* Paulo não teve alívio porque não encontrou Tito em Trôade (2:12, 13)
* 3. O ministério glorioso de Paulo e de seus companheiros (2:14–4:6)
* O ministério é comparado a um desfile triunfal (2:14-17)
* Cartas de recomendação (3:1-3)
* Deus qualifica cristãos para serem servos do novo pacto (3:4-6)
* A glória do ministério do novo pacto é superior (3:7-18)
* O ministério que faz a luz brilhar por meio do conhecimento glorioso de Deus (4:1-6)
* 4. Mesmo sendo vasos de barro, Paulo e seus companheiros suportam muitas provações (4:7-18)
* Com o poder além do normal é possível suportar dificuldades (4:7-15)
* O sofrimento é momentâneo, mas produz uma glória eterna (4:16-18)
* 5. O desejo de Paulo de receber sua recompensa celestial (5:1-10)
* Corpo espiritual será superior (5:1-5)
* Enquanto estão na Terra, os cristãos ungidos andam pela fé, não pela vista (5:6-10)
* 6. O ministério da reconciliação (5:11–6:2)
* O amor que Cristo mostrou impele os cristãos (5:11-15)
* Os cristãos ungidos estão em união com Cristo e são uma nova criação (5:16-19)
* Embaixadores substituindo a Cristo suplicam: “Sejam reconciliados com Deus” (5:20, 21)
* Não se deve perder de vista o objetivo da bondade imerecida de Deus (6:1, 2)
* 7. Paulo fala de seu ministério (6:3-13)
* Como os cristãos se recomendam como ministros de Deus (6:3-10)
* Paulo fala do carinho que tem pelos irmãos em Corinto (6:11-13)
* 8. Alertas sobre impureza espiritual e idolatria (6:14–7:1)
* “Não se ponham em jugo desigual com descrentes” (6:14-18)
* “Purifiquemo-nos de toda imundície da carne e do espírito” (7:1)
* 9. Paulo se alegra por causa dos coríntios (7:2-16)
* Paulo tem orgulho dos irmãos em Corinto (7:2-4)
* Paulo foi consolado com a presença de Tito e com seu bom relato (7:5-7)
* Tristeza segundo a vontade de Deus e arrependimento levam à salvação (7:8-13a)
* Paulo se alegra ao saber do bom relacionamento entre Tito e os coríntios (7:13b-16)
****

[[v47-5-1]]

^<<v47-5-1,1>>^ Pois nós sabemos que, se a nossa casa terrena, esta tenda, for destruída, teremos um edifício da parte de Deus, uma casa eterna nos céus, não feita por mãos humanas.

[TIP]
====
- *a nossa casa terrena, esta tenda*: Aqui, Paulo usa uma tenda como metáfora para representar o corpo humano dos cristãos ungidos. Uma tenda literal é uma estrutura temporária, desmontável e relativamente frágil. De forma parecida, o corpo que os cristãos ungidos têm enquanto estão na Terra é temporário, mortal e perecível. Mas eles aguardam receber “um edifício da parte de Deus”, ou seja, um corpo espiritual eterno e imperecível. — 1Co 15:50-53; compare com 2Pe 1:13, 14; veja a nota de estudo em 2Co 5:4.
- *destruída*: Ou: “dissolvida”. A palavra grega que aparece aqui é katalýo. Nesta ilustração de Paulo, que fala do corpo humano dos ungidos como se fosse uma tenda, essa palavra também poderia ser traduzida como “desarmada; desmontada”.
====

[[v47-5-2]]

^<<v47-5-2,2>>^ Pois de fato gememos nesta casa, desejando ansiosamente nos revestir daquela que é para nós, do céu,

[TIP]
====
- *casa*: Ou: “morada”. A palavra grega usada aqui é oiketérion. Ela aparece apenas neste versículo e em Ju 6, onde foi traduzida como “morada”.
- *daquela que é para nós, do céu*: Ou: “da nossa morada, que é do céu; da nossa morada celestial”. — Veja a nota de estudo em 2Co 5:1.
====

[[v47-5-3]]

^<<v47-5-3,3>>^ de modo que, quando nos revestirmos dela, não seremos achados nus.

[TIP]
====
- *não seremos achados nus*: Paulo sabia que ele e os outros cristãos ungidos que morressem antes da presença de Cristo ficariam, por um tempo, dormindo na Sepultura. Enquanto estivessem ali, eles estariam como que “nus”, ou despidos, no sentido de que não estariam vivos nem com um corpo humano nem com um corpo espiritual. No entanto, aqueles que morressem fiéis não permaneceriam “nus”, ou seja, mortos. Pelo contrário, eles seriam ressuscitados e iriam ‘se revestir’ de um corpo espiritual para “morar com o Senhor”. — 2Co 5:1-8; veja a nota de estudo em 2Co 5:4.
====

[[v47-5-4]]

^<<v47-5-4,4>>^ Na verdade, nós, que estamos nesta tenda, gememos oprimidos, pois não queremos nos despir dela, mas queremos nos revestir da outra, para que aquilo que é mortal seja consumido^&#42;1^ pela vida.

[NOTE]
====
. Ou: “engolido”.
====

[TIP]
====
- *queremos nos revestir da outra*: Paulo e os outros cristãos ungidos ‘desejavam ansiosamente’ ser ressuscitados para viver como criaturas espirituais no céu (2Co 5:2), um desejo que tinha sido dado a eles por Deus. Mas isso não queria dizer que eles desejavam morrer. Paulo deixou isso claro quando, depois de se referir ao corpo humano dos ungidos como uma tenda, disse: não queremos nos despir dela. (Veja a nota de estudo em 2Co 5:1.) Eles não encaravam a morte como um modo de evitar doenças e outras dificuldades da vida humana ou de fugir das responsabilidades e dos problemas que seu ministério trazia. (Veja a nota de estudo em 2Co 5:3.) Quando Paulo disse “queremos nos revestir da outra”, ele estava apenas expressando o desejo que todos os cristãos ungidos têm de viver no céu. Eles aguardam ansiosamente estar com Jeová e servi-lo para sempre junto com Jesus Cristo. — 1Co 15:42-44, 53, 54; Fil 1:20-24; 2Pe 1:4; 1Jo 3:2, 3; Ap 20:6.
====

[[v47-5-5]]

^<<v47-5-5,5>>^ Quem nos preparou para isso foi Deus, que nos deu o espírito como garantia daquilo que virá.

[TIP]
====
- *garantia daquilo que virá*: Ou: “entrada (sinal); penhor daquilo que virá”. — Veja a nota de estudo em 2Co 1:22.
====

[[v47-5-6]]

^<<v47-5-6,6>>^ Assim, estamos sempre confiantes e sabemos que, enquanto moramos^&#42;1^ no corpo, estamos longe do Senhor,

[NOTE]
====
. Lit.: “enquanto temos o nosso lar”.
====

[[v47-5-7]]

^<<v47-5-7,7>>^ pois estamos andando pela fé, não pela vista.

[TIP]
====
- *andando pela fé, não pela vista*: Na Bíblia, a expressão “andar” é muitas vezes usada em sentido figurado para passar a ideia de “viver; agir; levar um certo tipo de vida”. Assim, ‘andar pela fé’ significa levar uma vida guiada pela fé, confiando em Deus e naquilo que ele revelou em sua Palavra. Paulo contrasta ‘andar pela fé’ com ‘andar pela vista’, ou seja, levar uma vida guiada pelo que os olhos veem e pela aparência externa das coisas. Quando Paulo falou estas palavras, ele estava pensando especificamente nos cristãos ungidos. Apesar de não conseguirem enxergar literalmente a sua recompensa celestial, eles tinham uma base sólida para sua fé. Não apenas os ungidos, mas todos os cristãos, precisam deixar a fé guiar suas vidas.
====

[[v47-5-8]]

^<<v47-5-8,8>>^ Mas estamos cheios de confiança e preferimos estar longe do corpo e morar com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ Assim, quer moremos com ele, quer estejamos longe dele, temos por alvo agradar a ele.

[[v47-5-10]]

^<<v47-5-10,10>>^ Pois todos nós compareceremos^&#42;1^ perante o tribunal do Cristo, para que cada um receba a sua retribuição de acordo com as coisas que fez enquanto no corpo, sejam boas sejam más.

[NOTE]
====
. Ou: “seremos manifestados”.
====

[TIP]
====
- *o tribunal do Cristo*: Em Ro 14:10, Paulo se refere a este mesmo tribunal como “o tribunal de Deus”. Aqui, ele é chamado de “o tribunal do Cristo” porque Jeová usa seu Filho para julgar em seu nome. (Jo 5:22, 27) A palavra grega traduzida aqui como “tribunal” é béma. Ela se refere a um tipo de tribunal que existia em algumas cidades na época dos primeiros cristãos. O béma geralmente era uma plataforma elevada, ao ar livre, acessível por meio de degraus. Ali, as autoridades se sentavam para falar às multidões e anunciar suas decisões. (Mt 27:19; Jo 19:13; At 12:21; 18:12; 25:6, 10) O fato de Paulo ter usado essa palavra aqui pode ter lembrado os coríntios do impressionante tribunal que existia em sua cidade. — Veja o Glossário, “Tribunal”, e a mídia “Tribunal de Corinto”.
- *más*: Ou: “repugnantes”. A palavra grega traduzida aqui como “más” é faúlos. Em alguns contextos, ela passa a ideia de “baixo em sentido moral”. Paulo mostra que os humanos têm diante deles uma escolha: praticar coisas boas ou coisas más, ou seja, viver de acordo com os padrões de Deus ou ignorar esses padrões.
====

[[v47-5-11]]

^<<v47-5-11,11>>^ Portanto, visto que conhecemos o temor do Senhor, continuamos persuadindo a homens, mas somos plenamente conhecidos por Deus. E espero que também sejamos plenamente conhecidos pela consciência de vocês.

[TIP]
====
- *o temor do Senhor*: Neste contexto, o título “Senhor” pelo visto se refere a Jesus Cristo. No versículo anterior, Paulo disse “todos nós compareceremos perante o tribunal do Cristo”. (Veja a nota de estudo em 2Co 5:10.) Esse papel de Jesus como juiz foi profetizado por Isaías. (Is 11:3, 4) “O temor do Senhor” vem de um profundo amor e respeito por Jeová, que foi quem designou Jesus como Juiz. — Jo 5:22, 27.
- *somos plenamente conhecidos por . . . sejamos plenamente conhecidos pela*: Lit.: “temos sido manifestados a . . . tenhamos sido manifestados na”. Paulo tinha certeza de que Deus sabia o tipo de pessoas que ele e seus companheiros eram. E ele esperava que os coríntios também tivessem percebido que a motivação e a conduta dele e de seus companheiros eram boas.
====

[[v47-5-12]]

^<<v47-5-12,12>>^ Não estamos nos recomendando novamente a vocês, mas estamos lhes dando um incentivo para que falem de nós com orgulho, a fim de que possam responder aos que se orgulham da aparência, e não do que há no coração.

[TIP]
====
- *aos que se orgulham da aparência*: Ou: “aos que se gabam da aparência”. O verbo grego kaukháomai (“orgulhar-se; gabar-se”) muitas vezes passa a ideia de ter orgulho egoísta. Paulo usou esse verbo várias vezes em suas cartas aos coríntios. A Bíblia mostra que nenhum humano tem motivos para se orgulhar de si mesmo ou de suas realizações. (Je 9:23, 24) O apóstolo Paulo deu fortes conselhos aos coríntios sobre esse assunto, deixando claro que os humanos não têm motivos válidos para se gabar, exceto sobre Jeová e o que ele faz por eles. — 1Co 1:28, 29, 31; 4:6, 7; 2Co 10:17.
====

[[v47-5-13]]

^<<v47-5-13,13>>^ Pois, se perdemos o juízo,  foi para Deus; se temos juízo são, é para vocês.

[TIP]
====
- *Pois, se perdemos o juízo, foi para Deus*: Paulo usa aqui um verbo grego que significa literalmente “sair fora de si; estar fora de si”. É possível que, ao dizer estas palavras, Paulo estivesse pensando no que pretendia dizer mais tarde em sua carta para se defender dos que tinham questionado suas qualificações como apóstolo. (2Co 11:16-18, 23) Paulo precisou falar de suas realizações para provar que estava qualificado. Mas ele não se sentia à vontade ao se gabar. Ele explica que “foi para Deus” que ele se gabou, e não por orgulho. O seu objetivo era defender a verdade e proteger a congregação de influências perigosas. Na verdade, Paulo tinha juízo são, ou seja, tinha um ponto de vista equilibrado sobre si mesmo. (Compare com At 26:24, 25; Ro 12:3.) Visto que esse ponto de vista equilibrado ajudava aqueles a quem Paulo ensinava, ele podia dizer aos coríntios: se temos juízo são, é para vocês.
====

[[v47-5-14]]

^<<v47-5-14,14>>^ Pois o amor do Cristo nos impele, porque nós concluímos o seguinte: um só homem morreu por todos — de fato, todos tinham morrido.

[TIP]
====
- *o amor do Cristo*: Em grego, estas palavras podem ser entendidas de duas formas: “o amor que Cristo mostra por nós” ou “o amor que nós mostramos por Cristo”. Alguns têm sugerido que os dois significados são possíveis. Mas o contexto destaca o amor que Cristo mostra por nós. — 2Co 5:15.
- *nos impele*: O verbo grego que aparece aqui significa literalmente “manter unido” e pode passar a ideia de “exercer contínuo controle sobre algo ou alguém; incentivar fortemente; impulsionar fortemente”. O amor que Cristo mostrou ao entregar a vida por seus seguidores foi imenso. Quanto mais um cristão compreende o tamanho desse amor, mais motivado ele se sente. Era nesse sentido que o amor de Cristo impelia, ou controlava, Paulo. Esse amor o motivou a deixar de lado os seus objetivos pessoais e a usar sua vida para servir a Deus e ao próximo, dentro e fora da congregação. — Compare com a nota de estudo em 1Co 9:16.
====

[[v47-5-15]]

^<<v47-5-15,15>>^ E ele morreu por todos para que os que vivem não vivessem mais para si mesmos, mas para aquele que morreu por eles e foi levantado.

[[v47-5-16]]

^<<v47-5-16,16>>^ Assim, de agora em diante não conhecemos mais a ninguém de um ponto de vista carnal. Mesmo que antes tenhamos conhecido a Cristo segundo a carne, certamente não o conhecemos mais assim.

[TIP]
====
- *de um ponto de vista carnal*: Ou: “de um ponto de vista humano”. Lit.: “segundo a carne”. Aqui, a palavra grega para “carne” (sarx) tem um sentido amplo e se refere às limitações dos humanos, incluindo sua maneira limitada de pensar e os resultados limitados que conseguem alcançar. (Veja as notas de estudo em Ro 3:20; 8:4.) Paulo estava mostrando que, para os cristãos, coisas como posição, riqueza, raça e nacionalidade não são importantes. Já que Cristo morreu por todos, essas diferenças não significam absolutamente nada. O que realmente importa para os cristãos é o relacionamento espiritual que eles têm uns com os outros. — Mt 12:47-50.
- *certamente não o conhecemos mais assim*: Alguns cristãos tinham tido, no passado, um ponto de vista carnal, ou humano, sobre Cristo, acreditando que ele iria restabelecer o reino terrestre de Israel. (Jo 6:15, 26) Mas eles abandonaram esse ponto de vista quando entenderam que ele tinha dado seu corpo carnal como resgate e agora era um espírito que dá vida. — 1Co 15:45; 2Co 5:15.
====

[[v47-5-17]]

^<<v47-5-17,17>>^ Portanto, se alguém está em união com Cristo, é uma nova criação. As coisas antigas passaram. Vejam! Coisas novas vieram à existência.

[TIP]
====
- *em união com Cristo*: Lit.: “em Cristo”. Cada cristão ungido está individualmente unido com Jesus Cristo. (Jo 17:21; 1Co 12:27) Para que esse relacionamento especial possa existir, Jeová precisa atrair o cristão a seu Filho e usar o espírito santo para gerá-lo como um filho em sentido espiritual. — Jo 3:3-8; 6:44.
- *é uma nova criação*: Cada cristão ungido é, individualmente, uma nova criação, ou seja, um filho de Deus gerado por espírito que tem a esperança de reinar com Cristo no céu. (Gál 4:6, 7) É verdade que, depois do sexto dia criativo, Deus não criou novas coisas físicas (Gên 2:2, 3), mas ele criou novas coisas espirituais.
- *Coisas novas vieram à existência*: Jesus foi o primeiro a se tornar uma “nova criação” de Deus. Isso aconteceu no batismo dele, quando ele foi ungido e se tornou um filho de Deus gerado por espírito, com a esperança de viver no céu. Além disso, Jesus e aqueles que vão reinar com ele (os cristãos ungidos) formam juntos a congregação cristã, que também é uma nova criação espiritual. — 1Pe 2:9.
====

[[v47-5-18]]

^<<v47-5-18,18>>^ Mas tudo isso vem de Deus, que nos reconciliou consigo mesmo por meio de Cristo e nos deu o ministério da reconciliação

[TIP]
====
- *Deus, que nos reconciliou consigo mesmo*: Todos os humanos precisam ser reconciliados com Deus porque o primeiro homem, Adão, desobedeceu a ele e passou o pecado e a imperfeição para toda a humanidade. (Ro 5:12) Isso afastou os humanos de Deus; eles se tornaram inimigos de Deus, já que os padrões de justiça dele não permitem que ele tolere o pecado. (Ro 8:7, 8) As palavras gregas para “reconciliar” e “reconciliação” têm o sentido básico de “mudar; trocar” e, neste contexto, se referem a transformar uma relação de inimizade com Deus em uma relação de amizade e harmonia com ele. Aqui, a expressão “nos reconciliou” se refere a Paulo, a seus companheiros e a todos os outros cristãos ungidos. Eles foram reconciliados com Deus por meio de Cristo, ou seja, com base no sacrifício de resgate de Cristo. Em seguida, Paulo mostra que Deus deu a eles “o ministério da reconciliação”. — Veja a nota de estudo em Ro 5:10.
- *o ministério da reconciliação*: Ou seja, o ministério de ajudar as pessoas a serem 
- *‘reconciliadas com Deus por meio da morte do seu Filho’. (Ro 5*:10) Esse ministério é urgente e envolve ajudar os que estão afastados de Deus a entrarem em uma relação pacífica com ele e se tornarem seus amigos. — 2Co 5:18-20; para uma explicação sobre a palavra “ministério” (em grego, diakonía), veja as notas de estudo em At 11:29; Ro 11:13.
====

[[v47-5-19]]

^<<v47-5-19,19>>^ — isto é, que Deus, por meio de Cristo, estava reconciliando um mundo consigo mesmo, sem levar em conta contra eles os seus pecados; e ele nos confiou a mensagem da reconciliação.

[TIP]
====
- *Deus, por meio de Cristo, estava reconciliando*: Algumas Bíblias traduzem estas palavras como “Deus estava em Cristo, reconciliando”. Mas a preposição grega en, que significa literalmente “em”, é muito abrangente e, para entender seu sentido, é preciso levar em conta o contexto em que ela aparece. O versículo anterior (2Co 5:18) diz claramente: “Deus . . . nos reconciliou consigo mesmo por meio de [em grego, diá] Cristo.” Isso ajuda a entender que o sentido da preposição en aqui é “por meio de”.
- *reconciliando um mundo consigo mesmo*: A humanidade precisa ser reconciliada com Deus porque o primeiro homem, Adão, desobedeceu a ele e passou o pecado e a imperfeição para todos os seus descendentes. (Veja a nota de estudo em 2Co 5:18.) Deus torna possível que os humanos se reconciliem com ele por meio de Cristo, ou seja, por meio do sacrifício de resgate de Jesus. (Ro 5:10; 2Co 5:21; Col 1:21, 22) Jeová designou os que estão em união com Cristo (os cristãos ungidos) para servir como “embaixadores” num mundo hostil e realizar “o ministério da reconciliação”. — 2Co 5:18, 20.
- *a mensagem da reconciliação*: Ou: “a palavra da reconciliação”. A Bíblia usa várias expressões para se referir à palavra, ou mensagem, de Deus para a humanidade. Elas ajudam a entender a abrangência e o significado da mensagem e destacam alguns aspectos específicos de seu conteúdo. Aqui, essa mensagem é chamada de “a mensagem da reconciliação”. Em outros versículos, ela também é chamada de “a palavra [ou: “mensagem”] do Reino” (Mt 13:19), “essa mensagem de salvação” (At 13:26), “a palavra da verdade” (Ef 1:13) e “a palavra da justiça” (He 5:13). Quando Paulo diz aqui “Deus . . . nos confiou a mensagem”, ele mostra que considerava uma honra poder levar, junto com os outros cristãos ungidos, a mensagem da reconciliação.
====

[[v47-5-20]]

^<<v47-5-20,20>>^ Somos, portanto, embaixadores, substituindo a Cristo, como se Deus fizesse um apelo por nosso intermédio. Suplicamos, como substitutos de Cristo: “Sejam reconciliados com Deus.”

[TIP]
====
- *Somos . . . embaixadores*: Aqui, Paulo se refere a si mesmo e a seus companheiros cristãos como “embaixadores, substituindo a Cristo”. Nos tempos bíblicos, embaixadores e outros mensageiros eram enviados pelos mais variados motivos. Por exemplo, em períodos de tensão entre governos, os embaixadores eram enviados para tentar evitar a guerra ou, quando a guerra já tinha começado, para negociar termos de paz. (Is 30:1-4; 33:7) Nos dias de Paulo, também era comum que povos, cidades ou províncias do Império Romano enviassem embaixadores a Roma para defender seus interesses em determinado assunto, para pedir ajuda ou para estreitar os laços com o governo romano. O verbo grego para “ser (atuar como) um embaixador” é presbeúo. Ele aparece duas vezes nas Escrituras Gregas Cristãs: aqui e em Ef 6:19, 20, onde Paulo fala de si mesmo como um embaixador das boas novas. Em Lu 14:32 e 19:14, o substantivo relacionado presbeía foi traduzido como “grupo de embaixadores”. Tanto o verbo presbeúo como o substantivo presbeía estão relacionados com a palavra presbýteros, que significa “homem mais velho; ancião”. — Mt 16:21; At 11:30.
- *substituindo a Cristo*: Ou: “em lugar de Cristo; em nome de Cristo”. Depois que Jesus foi ressuscitado e subiu ao céu, seus fiéis seguidores foram designados para atuar em seu lugar, como “embaixadores, substituindo a Cristo”. Eles foram enviados a todos os que estavam afastados do Soberano Supremo Jeová; primeiro aos judeus e, mais tarde, às pessoas das nações. Os cristãos ungidos servem como embaixadores num mundo que não está em paz com Deus. (Jo 14:30; 15:18, 19; Tg 4:4) Na carta de Paulo aos efésios, que foi escrita durante sua primeira prisão em Roma (cerca de 59-61 d.C.), ele falou de si mesmo como um “embaixador preso em correntes”. — Ef 6:20.
====

[[v47-5-21]]

^<<v47-5-21,21>>^ Àquele que não conheceu pecado, ele tornou pecado por nós, para que, por meio dele, nós nos tornássemos justiça de Deus.

[TIP]
====
- *Àquele que não conheceu pecado*: Ou seja, Jesus, que nunca pecou. Mas Jeová o tornou pecado por nós, ou seja, para o nosso benefício. Jeová providenciou que Jesus morresse como oferta pelo pecado, pagando assim o preço pelos pecados da humanidade. (Compare com Le 16:21; Is 53:12; Gál 3:13; He 9:28.) A expressão “tornou pecado por nós” também poderia ser traduzida como “tornou oferta pelo pecado por nós”. O apóstolo João disse o seguinte a respeito de Jesus: “Ele é um sacrifício propiciatório [ou: “sacrifício de expiação; meio de pacificação”] pelos nossos pecados; contudo, não apenas pelos nossos, mas também pelos do mundo inteiro.” (1Jo 2:2) O meio que os israelitas tinham para se aproximar de Deus, os sacrifícios de animais, era muito inferior ao meio que os cristãos têm para se aproximar dele, o sacrifício de Jesus Cristo. — Jo 14:6; 1Pe 3:18.
- *para que, por meio dele, nós nos tornássemos justiça de Deus*: Em outras palavras, Paulo estava dizendo que, por meio de Jesus, é possível ser considerado justo, ou aprovado, por Deus. Paulo talvez estivesse pensando na profecia de Is 53:11, que dizia que o servo de Jeová, o Messias, ‘traria uma posição justa a muitos’.
====

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]