include::./index.adoc[]

[[v47-2-0]]
=== A Segunda aos Coríntios, 2
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* B. PAULO CONFIRMA SEU AMOR PELOS CRISTÃOS EM CORINTO E FALA DO MINISTÉRIO DELE (1:12–7:16)
* 1. Mudança nos planos de viagem de Paulo (1:12-24)
* Paulo fala de sua conduta em relação aos coríntios (1:12-14)
* Paulo se defende da acusação de não ser confiável (1:15-24)
* 2. O interesse de Paulo no bem-estar dos cristãos em Corinto (2:1-13)
* Paulo deseja dar alegria aos coríntios (2:1-4)
* Um pecador é perdoado e aceito de volta na congregação (2:5-11)
* Paulo não teve alívio porque não encontrou Tito em Trôade (2:12, 13)
* 3. O ministério glorioso de Paulo e de seus companheiros (2:14–4:6)
* O ministério é comparado a um desfile triunfal (2:14-17)
* Cartas de recomendação (3:1-3)
* Deus qualifica cristãos para serem servos do novo pacto (3:4-6)
* A glória do ministério do novo pacto é superior (3:7-18)
* O ministério que faz a luz brilhar por meio do conhecimento glorioso de Deus (4:1-6)
* 4. Mesmo sendo vasos de barro, Paulo e seus companheiros suportam muitas provações (4:7-18)
* Com o poder além do normal é possível suportar dificuldades (4:7-15)
* O sofrimento é momentâneo, mas produz uma glória eterna (4:16-18)
* 5. O desejo de Paulo de receber sua recompensa celestial (5:1-10)
* Corpo espiritual será superior (5:1-5)
* Enquanto estão na Terra, os cristãos ungidos andam pela fé, não pela vista (5:6-10)
* 6. O ministério da reconciliação (5:11–6:2)
* O amor que Cristo mostrou impele os cristãos (5:11-15)
* Os cristãos ungidos estão em união com Cristo e são uma nova criação (5:16-19)
* Embaixadores substituindo a Cristo suplicam: “Sejam reconciliados com Deus” (5:20, 21)
* Não se deve perder de vista o objetivo da bondade imerecida de Deus (6:1, 2)
* 7. Paulo fala de seu ministério (6:3-13)
* Como os cristãos se recomendam como ministros de Deus (6:3-10)
* Paulo fala do carinho que tem pelos irmãos em Corinto (6:11-13)
* 8. Alertas sobre impureza espiritual e idolatria (6:14–7:1)
* “Não se ponham em jugo desigual com descrentes” (6:14-18)
* “Purifiquemo-nos de toda imundície da carne e do espírito” (7:1)
* 9. Paulo se alegra por causa dos coríntios (7:2-16)
* Paulo tem orgulho dos irmãos em Corinto (7:2-4)
* Paulo foi consolado com a presença de Tito e com seu bom relato (7:5-7)
* Tristeza segundo a vontade de Deus e arrependimento levam à salvação (7:8-13a)
* Paulo se alegra ao saber do bom relacionamento entre Tito e os coríntios (7:13b-16)
****

[[v47-2-1]]

^<<v47-2-1,1>>^ Pois eu decidi que a minha próxima visita a vocês não será triste.

[[v47-2-2]]

^<<v47-2-2,2>>^ Porque, se eu os entristecer, quem haverá para me alegrar, a não ser aqueles que eu tiver entristecido?

[[v47-2-3]]

^<<v47-2-3,3>>^ Escrevi o que escrevi para que, quando eu for aí, não fique triste por causa daqueles que deveriam me alegrar; porque tenho confiança de que o que me traz alegria traz a mesma alegria a todos vocês.

[[v47-2-4]]

^<<v47-2-4,4>>^ Pois eu lhes escrevi com muita aflição e angústia de coração, com muitas lágrimas, não para entristecê-los, mas para que soubessem do profundo amor que tenho por vocês.

[[v47-2-5]]

^<<v47-2-5,5>>^ Ora, se alguém causou tristeza, ele entristeceu não a mim, mas a todos vocês, até certo ponto — para não ser severo demais no que digo.

[[v47-2-6]]

^<<v47-2-6,6>>^ Essa censura da parte da maioria é suficiente para esse homem;

[TIP]
====
- *censura*: Ou: “castigo; punição”. Em sua primeira carta inspirada aos coríntios, Paulo os instruiu a expulsar da congregação um homem que estava praticando imoralidade sexual e que não tinha se arrependido. (1Co 5:1, 7, 11-13) Aquela disciplina teve bons resultados. Ela protegeu a congregação da má influência do pecador e o levou a se arrepender sinceramente. Visto que aquele homem tinha mostrado por suas ações que estava arrependido, Paulo diz aqui que a “censura da parte da maioria [era] suficiente” e que a congregação deveria acolher aquele homem de volta. Isso estava de acordo com a maneira de Jeová agir. Jeová disciplina seu povo “no devido grau”. — Je 30:11.
====

[[v47-2-7]]

^<<v47-2-7,7>>^ agora, ao contrário, vocês devem perdoá-lo bondosamente e consolá-lo, para que ele não seja vencido pela excessiva tristeza.

[TIP]
====
- *seja vencido*: Ou: “seja consumido”. A palavra grega que aparece aqui pode se referir literalmente a engolir ou devorar algo. (He 11:29; 1Pe 5:8) De acordo com um léxico, a expressão “ser vencido pela excessiva tristeza” significa “estar tão triste a ponto de perder a esperança . . . ficar tão desanimado a ponto de desistir”.
====

[[v47-2-8]]

^<<v47-2-8,8>>^ Eu os exorto, portanto, a reafirmar o seu amor por ele.

[TIP]
====
- *reafirmar o seu amor por ele*: A palavra grega traduzida aqui como “reafirmar” é um termo jurídico que significa “validar”. (Ela foi traduzida como “validado” em Gál 3:15.) Os cristãos em Corinto deviam mostrar por suas atitudes e ações que seu amor pelo homem arrependido era verdadeiro. Eles precisavam deixar claro que estavam felizes em recebê-lo de volta na congregação. Por voltarem a tratá-lo como seu amigo e irmão, eles iriam “reafirmar”, ou validar, o seu amor por ele. Eles não deveriam imaginar que aquele homem já sabia que era amado. O amor que sentiam por ele precisava ser demonstrado.
====

[[v47-2-9]]

^<<v47-2-9,9>>^ Pois é também por isso que lhes escrevi: para ver se vocês dariam provas de que são obedientes em todas as coisas.

[[v47-2-10]]

^<<v47-2-10,10>>^ Se vocês perdoarem alguém por alguma coisa, eu também perdoo. De fato, o que perdoei (se eu tiver perdoado alguma coisa), foi para o bem de vocês, à vista de Cristo,

[[v47-2-11]]

^<<v47-2-11,11>>^ para que não sejamos vencidos por Satanás, pois não desconhecemos as suas tramas.

[TIP]
====
- *não sejamos vencidos por Satanás*: Ou: “não sejamos enganados por Satanás; Satanás não se aproveite de nós”. Na época em que Paulo escreveu 1 Coríntios, Satanás tinha conseguido influenciar a atitude da congregação em Corinto. Eles tinham se tornado permissivos demais, deixando que um homem que estava praticando imoralidade sexual permanecesse na congregação, sem levar em conta o quanto isso estava manchando o nome de Deus. Paulo repreendeu os coríntios por causa disso. (1Co 5:1-5) Mas agora aquele homem estava sinceramente arrependido. Assim, se a congregação fosse para o outro extremo e se recusasse a perdoá-lo, eles estariam sendo vencidos por Satanás de outro modo: estariam se tornando duros e sem compaixão, como o próprio Satanás. Isso deixaria o homem arrependido muito desanimado.
- *não desconhecemos as suas tramas*: Paulo poderia ter dito simplesmente “conhecemos as suas tramas”. Mas ele usa aqui uma figura de linguagem chamada lítotes, que envolve dizer que o oposto de algo não é verdade. A lítotes consegue ao mesmo tempo suavizar uma afirmação e dar ênfase a ela. (Outro exemplo do uso de lítotes aparece em At 21:39. Ali, falando sobre Tarso, o texto grego diz literalmente “uma cidade não insignificante”, com o sentido de “uma cidade importante”.) Por isso, algumas Bíblias traduzem as palavras de Paulo aqui como “sabemos bem de suas maquinações” ou “conhecemos bem os planos dele”, o que dá uma ênfase parecida.
- *tramas*: Ou: “intenções; maquinações”. A palavra grega que aparece aqui, nóema, vem da palavra nous, que significa “mente”. Aqui, ela se refere às maquinações de Satanás, ou seja, os planos dele. Satanás usa toda a sua inteligência para tentar fazer os cristãos pararem de servir a Deus. Mas os Evangelhos e outros relatos das Escrituras, como o livro de Jó, revelam as estratégias dele. (Jó 1:7-12; Mt 4:3-10; Lu 22:31; Jo 8:44) Mais à frente nesta carta, Paulo diz que “a serpente seduziu Eva pela sua astúcia” e que “o próprio Satanás se disfarça de anjo de luz”. (2Co 11:3, 14) Assim, Paulo tinha bons motivos para dizer: não desconhecemos as suas tramas. Alguns têm sugerido que, neste versículo, Paulo esteja fazendo um jogo de palavras que poderia ser traduzido como “a nossa mente não desconhece a mente dele”, ou seja, a maneira maldosa de ele pensar.
====

[[v47-2-12]]

^<<v47-2-12,12>>^ Quando cheguei a Trôade para declarar as boas novas a respeito do Cristo, e foi aberta para mim uma porta na obra do Senhor,^&#42;1^

[NOTE]
====
. Lit.: “uma porta no Senhor”.
====

[[v47-2-13]]

^<<v47-2-13,13>>^ meu espírito não teve alívio porque não achei Tito, meu irmão. Então me despedi dos irmãos dali e parti para a Macedônia.

[TIP]
====
- *meu espírito não teve alívio porque não achei Tito*: Durante o período em que esteve em Éfeso, Paulo escreveu 1 Coríntios. Nessa carta, ele deu fortes conselhos aos cristãos em Corinto. Depois, Paulo enviou Tito para lá para ajudar na coleta que seria enviada aos cristãos em necessidade na Judeia. (2Co 8:1-6) O plano de Paulo era encontrar com Tito mais tarde, em Trôade, mas, quando chegou lá e não achou Tito, seu “espírito não teve alívio”. Paulo talvez tenha ficado decepcionado ao não encontrar Tito porque estava ansioso para saber como os coríntios tinham reagido aos seus fortes conselhos. Ele abriu seu coração com os cristãos coríntios, mostrando o quanto se importava com eles. De Trôade, Paulo ‘partiu para a Macedônia’. Ali, ele encontrou Tito, que trazia boas notícias. Para o grande alívio e alegria de Paulo, a congregação tinha reagido bem aos conselhos dele. — 2Co 7:5-7; veja a nota de estudo em 2Co 7:5.
====

[[v47-2-14]]

^<<v47-2-14,14>>^ Mas graças sejam dadas a Deus, que sempre nos conduz num desfile triunfal em companhia do Cristo e, por nosso intermédio, espalha o aroma do conhecimento dele por toda a parte!

[TIP]
====
- *nos conduz num desfile triunfal*: A palavra grega thriambeúo, que significa “conduzir num desfile triunfal”, aparece apenas duas vezes nas Escrituras. Nas duas vezes, ela foi usada em uma ilustração, mas a aplicação em cada caso é diferente. (2Co 2:14; Col 2:15) Os desfiles triunfais romanos eram eventos oficiais realizados para agradecer aos deuses por uma vitória militar e dar glória ao general responsável por ela. Desfiles triunfais foram retratados em esculturas, pinturas e moedas, e também em obras literárias e peças teatrais. No Arco de Tito, em Roma, é possível ver uma representação do desfile triunfal que aconteceu em junho de 71 d.C. Algumas das imagens esculpidas no arco mostram soldados romanos carregando objetos sagrados retirados do templo de Jerusalém, que tinha sido destruído.
- *espalha o aroma*: Ou: “faz sentir o aroma”. Esta parte da metáfora de Paulo sobre o desfile triunfal provavelmente vem do costume de queimar incenso ao longo do caminho por onde o desfile passava. Paulo compara espalhar o conhecimento sobre Deus com espalhar um aroma.
====

[[v47-2-15]]

^<<v47-2-15,15>>^ Pois para Deus somos aroma agradável de Cristo, entre os que estão a caminho da salvação^&#42;1^ e entre os que estão a caminho da destruição^&#42;2^

[NOTE]
====
. Ou: “estão sendo salvos”.
. Ou: “estão perecendo”.
====

[TIP]
====
- *aroma agradável de Cristo*: A palavra grega traduzida aqui como “aroma agradável” é euodía. Ela foi usada em Ef 5:2 e Fil 4:18, onde, combinada com a palavra grega osmé (“odor; cheiro”), foi traduzida como “aroma agradável” e “aroma suave”. Na Septuaginta, essas duas palavras gregas muitas vezes foram usadas para traduzir a expressão hebraica para “um aroma agradável”, que se refere ao aroma dos sacrifícios oferecidos a Jeová. (Gên 8:21; Êx 29:18) Neste versículo e no anterior, Paulo está falando sobre um desfile triunfal e compara o incenso que era queimado nesses desfiles ao aroma agradável de Cristo. Esse “aroma” provoca diferentes sensações nas pessoas, dependendo de se elas aceitam ou rejeitam a mensagem cristã.
====

[[v47-2-16]]

^<<v47-2-16,16>>^ — para estes últimos, cheiro de morte que leva à morte; para os primeiros, aroma de vida que leva à vida. E quem está qualificado para isso?

[TIP]
====
- *cheiro*: Ou: “aroma”. A palavra grega osmé aparece duas vezes neste versículo, uma delas na expressão “cheiro de morte” e a outra na expressão “aroma de vida”. Essa palavra grega pode se referir tanto a um cheiro agradável (Jo 12:3; 2Co 2:14, 16; Ef 5:2; Fil 4:18) como a um cheiro desagradável. Na Septuaginta, ela foi usada em Is 34:3 para se referir ao ‘mau cheiro de cadáveres’. Aqui, em 2Co 2:16, as duas ocorrências de osmé se referem ao mesmo “cheiro”: a mensagem proclamada pelos discípulos de Jesus. Durante um desfile triunfal literal, os prisioneiros de guerra eram exibidos para a multidão. No final do desfile, eles eram executados. Por isso, para aqueles prisioneiros, o cheiro do incenso que era queimado durante o desfile era um “cheiro de morte”. Na ilustração de Paulo, o que tornava o cheiro agradável ou desagradável era a reação das pessoas à mensagem. Para as que a aceitavam, ela era um “aroma de vida”; para as que a rejeitavam, ela era um “cheiro de morte”.
- *para isso*: Ou seja, para o ministério que Paulo tinha mencionado nos versículos anteriores. Em outras palavras, Paulo está perguntando: ‘Quem está qualificado para agir como um ministro verdadeiro de Deus e espalhar o aroma do conhecimento sobre Deus em toda parte?’
====

[[v47-2-17]]

^<<v47-2-17,17>>^ Nós estamos, pois não somos vendedores ambulantes da palavra de Deus, como muitos são, mas falamos com toda a sinceridade como enviados por Deus, sim, à vista de Deus e na companhia de Cristo.

[TIP]
====
- *Nós estamos*: Aqui, Paulo está respondendo à pergunta que ele mesmo tinha feito no final do versículo 16. Quando Paulo diz que ele e seus companheiros estão qualificados, ele não está sendo arrogante. Pelo contrário, ele deixa claro que eles falavam como enviados por Deus, mostrando que eles sabiam que só estavam qualificados por causa da ajuda de Deus. Além disso, eles realizavam seu ministério com toda a sinceridade, ou seja, eles tinham a motivação correta. — 2Co 3:4-6.
- *pois não somos vendedores ambulantes da palavra de Deus*: Ou: “pois não comercializamos [ou: “não lucramos com”] a mensagem de Deus”. Ao contrário dos falsos instrutores, Paulo, os apóstolos e seus companheiros pregavam a mensagem de Deus sem alterá-la e com a motivação correta. No início, o verbo grego traduzido aqui como “ser vendedor ambulante” (kapeleúo) era usado para se referir a comerciantes ou a donos de tavernas, mas com o tempo passou a incluir a ideia de ser desonesto ou agir por ganância. Uma palavra grega relacionada com kapeleúo aparece na Septuaginta em Is 1:22, onde o versículo diz “seus comerciantes de vinho [“taverneiros”] misturam o vinho com água”. No mundo greco-romano, antes de beberem vinho, as pessoas geralmente o diluíam com água. Para lucrar mais, alguns comerciantes aumentavam a quantidade de água que colocavam no vinho. Por isso, alguns estudiosos acreditam que aqui Paulo esteja fazendo referência a esses comerciantes desonestos. A mesma metáfora foi usada na literatura grega para se referir a filósofos viajantes que cobravam para ensinar os outros. Quando Paulo fala aqui de muitos que eram “vendedores ambulantes” da palavra de Deus, ele pelo visto estava pensando nos falsos instrutores que misturavam filosofias humanas, tradições e ensinos religiosos falsos com a Palavra de Jeová. Esses falsos instrutores estavam como que diluindo a palavra de Deus, alterando sua fragrância e sabor, e diminuindo o poder que ela tem de alegrar as pessoas. — Sal 104:15; veja a nota de estudo em 2Co 4:2.
====

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]