include::./index.adoc[]

[[v47-8-0]]
=== A Segunda aos Coríntios, 8
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. COLETA PARA AJUDAR IRMÃOS POBRES NA JUDEIA (8:1–9:15)
* A generosidade dos cristãos da Macedônia é um exemplo para os coríntios (8:1-7)
* Paulo incentiva “uma compensação” de recursos (8:8-15)
* Tito é enviado a Corinto para ajudar na coleta (8:16-24)
* A prontidão é importante (9:1-5)
* Paulo incentiva a generosidade: “Deus ama quem dá com alegria” (9:6-14)
* A “indescritível dádiva” de Deus (9:15)
****

[[v47-8-1]]

^<<v47-8-1,1>>^ Agora, irmãos, queremos que vocês saibam da bondade imerecida de Deus que foi concedida às congregações da Macedônia.

[[v47-8-2]]

^<<v47-8-2,2>>^ Mesmo sob aflição durante uma grande prova, a imensa alegria e a extrema pobreza deles fizeram transbordar as riquezas de sua generosidade.

[TIP]
====
- *fizeram transbordar as riquezas de sua generosidade*: Ou: “tornaram abundantes as riquezas de sua generosidade”. Para motivar os coríntios a terminarem de reunir a contribuição que estavam preparando para os cristãos necessitados da Judeia, Paulo cita o excelente exemplo de generosidade das “congregações da Macedônia”, o que incluía as congregações de Filipos e Tessalônica. (2Co 8:1-4; 9:1-7; Ro 15:26; Fil 4:14-16) A generosidade deles era muito impressionante porque, mesmo passando por “extrema pobreza” e aflição durante uma grande prova, os macedônios deram ajuda com alegria. Não se sabe o que a “grande prova” mencionada aqui envolvia. É possível que os cristãos da Macedônia estivessem sendo acusados de promover costumes que eram ilegais para os cidadãos romanos. O próprio Paulo sofreu esse tipo de acusação em Filipos. (At 16:20, 21) Outra possibilidade é que a prova estivesse relacionada com a pobreza deles. Os irmãos da Judeia estavam enfrentando provas, ou dificuldades, parecidas com essas, e talvez tenha sido por isso que os macedônios tiveram tanta empatia por eles. (At 17:5-9; 1Te 2:14) Os cristãos da Macedônia queriam muito ajudar e ficaram felizes em dar “até mesmo além de seus recursos”. — 2Co 8:3.
====

[[v47-8-3]]

^<<v47-8-3,3>>^ Pois o que eles fizeram foi segundo seus recursos, sim, sou testemunha de que foi até mesmo além de seus recursos;

[[v47-8-4]]

^<<v47-8-4,4>>^ eles nos suplicavam insistentemente, de sua própria iniciativa, pelo privilégio de dar bondosamente, para participar no serviço de ajuda aos santos.

[TIP]
====
- *participar no serviço de ajuda*: Ou: “participar no ministério de ajuda”. O substantivo grego traduzido aqui como “serviço de ajuda” é diakonía. Na Bíblia, esse substantivo é muitas vezes usado para falar de tarefas humildes feitas por amor a outras pessoas. É interessante notar que esse substantivo grego é usado para se referir aos dois tipos de ministério cristão: a pregação e a ajuda aos necessitados. (Veja a nota de estudo em At 11:29.) Neste versículo, Paulo está se referindo especificamente a dar ajuda aos cristãos que estão passando por dificuldades. (2Co 9:13; veja a nota de estudo em Ro 15:31.) As congregações da Macedônia consideravam um privilégio poder participar desse serviço de ajuda. Tanto a pregação como a ajuda aos necessitados são “serviço sagrado”. — Ro 12:1, 6-8.
====

[[v47-8-5]]

^<<v47-8-5,5>>^ E fizeram mais do que esperávamos, visto que se entregaram primeiramente ao Senhor e a nós, pela vontade de Deus.

[[v47-8-6]]

^<<v47-8-6,6>>^ Assim, incentivamos Tito a terminar a coleta da bondosa dádiva de vocês, visto que ele havia iniciado esse trabalho no seu meio.

[[v47-8-7]]

^<<v47-8-7,7>>^ Portanto, assim como vocês são ricos em tudo — em fé, em palavra, em conhecimento, em toda a diligência e em nosso amor por vocês —, sejam ricos também no que se refere a essa bondosa dádiva.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não digo isso como uma ordem, mas para informá-los da diligência de outros e para pôr à prova a sinceridade do amor de vocês.

[[v47-8-9]]

^<<v47-8-9,9>>^ Pois vocês conhecem a bondade imerecida do nosso Senhor Jesus Cristo: embora fosse rico, tornou-se pobre por causa de vocês, para que vocês se tornassem ricos por meio da pobreza dele.

[TIP]
====
- *embora fosse rico, tornou-se pobre por causa de vocês*: Para incentivar os coríntios a ajudar os que passavam necessidade, Paulo menciona o exemplo que Jesus deu de ser generoso e abnegado. Antes de vir à Terra como humano, Jesus era rico num sentido muito especial: ele era mais favorecido e abençoado por seu Pai do que qualquer outra pessoa. (Jo 1:14; Ef 3:8) Mas ele voluntariamente abriu mão de sua posição favorecida. (Jo 1:18; Fil 2:5-8) Ele deixou seu lar, o céu, para viver entre humanos imperfeitos que lidavam diariamente com pobreza, doença e morte. Além disso, Jesus nasceu na família de um carpinteiro pobre. (Veja a nota de estudo em Lu 2:24.) Como adulto, Jesus levou uma vida simples. (Mt 8:20) Mesmo assim, ele foi capaz de resgatar a humanidade. Por causa da generosidade de Jesus, os cristãos em Corinto se tornaram ricos em sentido espiritual e receberam muitas bênçãos, incluindo a esperança de reinar com Cristo nos céus. Paulo incentiva os coríntios a imitar a atitude generosa de Jesus.
====

[[v47-8-10]]

^<<v47-8-10,10>>^ E a esse respeito dou a minha opinião: cuidar disso é para o seu próprio bem, visto que já faz um ano que vocês não somente iniciaram essa obra, mas também mostraram o desejo de fazê-la.

[[v47-8-11]]

^<<v47-8-11,11>>^ Agora, então, terminem o que começaram, de modo que a sua prontidão para agir seja completada segundo os recursos que têm à disposição.

[[v47-8-12]]

^<<v47-8-12,12>>^ Pois, se já existe a prontidão, a dádiva é especialmente aceitável segundo o que a pessoa tem, não segundo o que a pessoa não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Porque não quero aliviar outros e sobrecarregar vocês;

[[v47-8-14]]

^<<v47-8-14,14>>^ mas, por meio de uma compensação, que o excedente que agora vocês têm supra a necessidade deles, a fim de que o excedente deles também supra a carência de vocês, e desse modo haja uma compensação.

[TIP]
====
- *uma compensação*: Ou: “uma reciprocidade”. Neste contexto, Paulo dá instruções sobre a coleta para ‘os santos’ que estavam passando necessidade em Jerusalém e outras partes da Judeia. (2Co 8:4; 9:1) Os cristãos em Corinto tinham melhores condições financeiras. Por isso, Paulo sugere que eles poderiam usar os recursos extras que tinham para suprir a necessidade material dos irmãos da Judeia. Essa generosidade resultaria em “uma compensação”, ou seja, traria um equilíbrio de recursos entre os irmãos. Ninguém estava sendo pressionado a dar mais do que podia. — 2Co 8:12, 13; 9:7; veja a nota de estudo em 2Co 8:15.
====

[[v47-8-15]]

^<<v47-8-15,15>>^ Assim como está escrito: “Quem tinha muito não teve demais, e quem tinha pouco não teve de menos.”

[TIP]
====
- *Assim como está escrito*: Aqui, Paulo cita Êx 16:18 para mostrar que o princípio da “compensação” tinha base nas Escrituras. O texto de Êxodo fala da provisão amorosa do maná, que Jeová forneceu aos israelitas durante o tempo que estiveram no deserto. (2Co 8:14; veja o Glossário, “Maná”.) O chefe da família recolhia ou supervisionava a coleta do maná para toda a sua família. Como o maná derretia quando o sol ficava quente, os israelitas provavelmente recolhiam rapidamente a quantidade aproximada de maná de que precisavam, de acordo com o tamanho da família, e deixavam para medir depois. Mas, não importava se eles recolhiam muito ou pouco, na hora de medir a quantidade acabava sendo sempre um gomor (2,2 litros) por pessoa. (Êx 16:16-18) Paulo faz referência a esse exemplo para apoiar o que tinha dito no versículo anterior, onde incentivou os cristãos em Corinto a suprir a necessidade de seus irmãos na Judeia usando os recursos extras que tinham. — Veja a nota de estudo em 2Co 8:14.
====

[[v47-8-16]]

^<<v47-8-16,16>>^ Graças sejam dadas a Deus por ter colocado no coração de Tito a mesma preocupação sincera que temos por vocês,

[[v47-8-17]]

^<<v47-8-17,17>>^ porque ele não só correspondeu ao nosso incentivo, mas, como tem muito boa vontade, está indo visitá-los por iniciativa própria.

[[v47-8-18]]

^<<v47-8-18,18>>^ Nós, porém, estamos enviando junto com ele o irmão que tem sido elogiado em todas as congregações por causa do que está fazendo pelas boas novas.

[TIP]
====
- *o irmão*: Paulo não diz o nome do irmão de quem está falando aqui. No versículo seguinte, Paulo se refere a ele usando uma palavra grega que foi traduzida como “companheiro de viagem”. (2Co 8:19) Essa palavra grega aparece nas Escrituras Gregas Cristãs apenas mais uma vez, em At 19:29, onde foi usada no plural. Um dos companheiros de viagem mencionados em At 19:29 é Aristarco. Já que Aristarco se tornou um grande amigo de Paulo, alguns estudiosos acreditam que ele seja “o irmão” mencionado aqui, mas é possível que tenha sido algum outro cristão, como por exemplo Tíquico. — At 20:2-4; 27:2; Col 4:7, 10.
====

[[v47-8-19]]

^<<v47-8-19,19>>^ Não só isso, mas ele também foi designado pelas congregações para ser nosso companheiro de viagem ao cuidarmos dessa^&#42;1^ bondosa dádiva para a glória do Senhor e como prova da nossa prontidão em ajudar.

[NOTE]
====
. Ou: “administrarmos essa”.
====

[[v47-8-20]]

^<<v47-8-20,20>>^ Estamos assim evitando que alguém nos critique com relação a essa contribuição generosa da qual estamos cuidando.^&#42;1^

[NOTE]
====
. Ou: “que estamos administrando”.
====

[[v47-8-21]]

^<<v47-8-21,21>>^ Pois ‘cuidamos de tudo honestamente, não somente à vista de Jeová, mas também à vista dos homens’.

[TIP]
====
- *‘cuidamos de tudo honestamente’*: Paulo se esforçava para que nenhum aspecto de sua vida ou de sua conduta desse motivos para outros criticarem seu ministério. (2Co 6:3) Ele sabia que alguns na congregação de Corinto tinham feito críticas e calúnias sobre ele para desmerecer sua autoridade como apóstolo. Paulo também sabia que esse tipo de conversa negativa seria ainda mais perigoso se o assunto envolvesse dinheiro. Por isso, ele disse para a congregação que estava mandando Tito e dois outros irmãos de confiança para cuidar das contribuições. (2Co 8:20, 22) Paulo queria agir honestamente não somente à vista de Jeová, mas também à vista dos homens. Aqui, ele faz referência ao texto de Pr 3:4, conforme aparece na Septuaginta. Com isso Paulo mostra que o princípio de providenciar que os donativos fossem administrados de forma honesta tinha base nas Escrituras. Nas cópias disponíveis hoje da Septuaginta, esse texto de Provérbios diz: “Procurem coisas honestas à vista do Senhor e dos homens [ou: das pessoas].” — Para uma explicação sobre os motivos de o nome de Deus ter sido usado aqui, veja o Apêndice C3 (introdução e 2Co 8:21).
====

[[v47-8-22]]

^<<v47-8-22,22>>^ Além disso, estamos enviando com eles o nosso irmão, cuja diligência comprovamos muitas vezes e em muitos assuntos; mas ele agora se mostra ainda mais diligente por causa da grande confiança que tem em vocês.

[TIP]
====
- *o nosso irmão*: Para garantir que não houvesse dúvidas sobre o uso do dinheiro contribuído, dois irmãos de confiança e devidamente designados foram escolhidos para ajudar Tito a completar a coleta. (2Co 8:20, 21; 9:5) Paulo não cita esses irmãos por nome. (Veja a nota de estudo em 2Co 8:18.) Assim, não se sabe quem era o irmão mencionado aqui, mas alguns sugerem que é possível que fosse Trófimo ou Tíquico. — At 20:4.
====

[[v47-8-23]]

^<<v47-8-23,23>>^ No entanto, se houver qualquer dúvida quanto a Tito, ele é meu companheiro^&#42;1^ e colaborador a favor dos interesses de vocês; ou, se houver dúvidas quanto aos nossos irmãos, eles são enviados das congregações e uma glória para Cristo.

[NOTE]
====
. Lit.: “parceiro”.
====

[TIP]
====
- *enviados das congregações*: Ou: “apóstolos das congregações”. A palavra grega apóstolos aparece aqui no plural e foi traduzida como “enviados”. Embora essa palavra grega possa ser traduzida como “apóstolo”, aqui Paulo a usa no seu sentido básico de “enviado” ou “emissário”. (Veja a nota de estudo em Jo 13:16.) Os irmãos mencionados por Paulo tinham sido enviados como representantes de suas congregações. Paulo usou a palavra grega apóstolos de forma parecida quando falou de Epafrodito como “aquele que vocês enviaram”. (Fil 2:25) Esses homens fiéis não eram apóstolos no sentido de terem sido designados para servir como um dos Doze, como foi o caso de Matias; nem eram apóstolos no sentido de terem sido escolhidos por Cristo para servir como apóstolos para as nações, como foi o caso de Paulo.— Veja a nota de estudo em At 1:26; veja também At 9:15; Ro 11:13.
====

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, deem a eles provas do seu amor e mostrem às congregações o motivo de falarmos com orgulho a respeito de vocês.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]