include::./index.adoc[]

[[v47-13-0]]
=== A Segunda aos Coríntios, 13
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* E. PALAVRAS FINAIS DE PAULO AOS CORÍNTIOS (13:1-14)
* Paulo diz aos coríntios que eles devem examinar a si mesmos (13:1-10)
* Exortações e saudações finais (13:11-14)
****

[[v47-13-1]]

^<<v47-13-1,1>>^ Esta é a terceira vez que estou para ir visitá-los. “Toda questão deve ficar estabelecida com base no depoimento de duas ou três testemunhas.”

[TIP]
====
- *a terceira vez*: Veja a nota de estudo em 2Co 12:14.
- *com base no depoimento de duas ou três testemunhas*: Lit.: “na boca de duas ou três testemunhas”. A palavra “boca” era usada como uma figura de linguagem (chamada metonímia) para se referir ao depoimento de uma testemunha. Debaixo da Lei mosaica, os juízes só poderiam condenar alguém “com base no depoimento” de duas, ou mesmo três, testemunhas. (De 17:6; 19:15) Jesus também citou esse padrão em outros contextos. (Mt 18:16; Jo 8:17, 18) O fato de Paulo ter citado De 19:15 ao falar de suas visitas a Corinto indica que esse princípio continuou a ser seguido na congregação cristã. — 1Ti 5:19.
====

[[v47-13-2]]

^<<v47-13-2,2>>^ Embora eu esteja ausente agora, é como se eu estivesse presente pela segunda vez, e eu previno os que pecaram no passado, e a todos os outros, que não os pouparei se eu for aí outra vez,^&#42;1^

[NOTE]
====
. Ou: “eu voltar”.
====

[[v47-13-3]]

^<<v47-13-3,3>>^ visto que vocês estão querendo provas de que Cristo, que não é fraco ao lidar com vocês, mas é poderoso entre vocês, fala realmente por meio de mim.

[[v47-13-4]]

^<<v47-13-4,4>>^ Pois, de fato, ele foi morto na estaca em razão de sua fraqueza, mas está vivo por causa do poder de Deus. É verdade que nós também somos fracos com ele, mas viveremos junto com ele por causa do poder de Deus em vocês.

[TIP]
====
- *foi morto na estaca*: Ou: “foi preso numa estaca (num poste)”. — Veja a nota de estudo em Mt 20:19 e o Glossário, “Madeiro; Estaca”; “Estaca de tortura”.
====

[[v47-13-5]]

^<<v47-13-5,5>>^ Persistam em examinar se estão na fé; persistam em pôr à prova o que vocês mesmos são. Ou não reconhecem que Jesus Cristo está em união com vocês? A menos que estejam reprovados.

[TIP]
====
- *Persistam em examinar*: Alguns em Corinto tinham desafiado Paulo, querendo provas de que ele era realmente um representante de Cristo. (2Co 13:3) Paulo diz que, na verdade, eles precisavam ‘persistir em examinar’ a si mesmos. Um léxico diz que a palavra grega traduzida aqui como “examinar” significa “tentar descobrir a natureza ou o caráter de algo”. Eles podiam descobrir como estava a sua situação espiritual comparando a conduta, as atitudes e as decisões diárias deles com as verdades sagradas que eles tinham aprendido. Fazer esse tipo de exame seria uma forma de eles persistirem em pôr à prova a si mesmos, para se certificar de que eram cristãos verdadeiros. A palavra grega traduzida aqui como “pôr à prova” pode se referir a fazer um teste de autenticidade, como quando se testa a pureza de um metal.
- *na fé*: Neste contexto, a expressão “a fé” se refere a todo o conjunto de crenças e ensinos cristãos. (At 6:7; Gál 6:10; Ef 4:5; Ju 3) Ela tem o mesmo significado da expressão “a verdade” que foi usada em Gál 5:7, 2Pe 2:2 e 2Jo 1. Aqui, Paulo está enfatizando que não basta conhecer as verdades e os princípios que Jesus ensinou; o cristão precisa ‘estar na fé’, ou seja, viver de acordo com essas verdades. — 2Co 12:20, 21.
====

[[v47-13-6]]

^<<v47-13-6,6>>^ Eu realmente espero que vocês reconheçam que nós não estamos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Oramos a Deus que vocês não façam nada de errado, não para que nós pareçamos aprovados, mas para que vocês façam o que é bom, mesmo que nós pareçamos reprovados.

[[v47-13-8]]

^<<v47-13-8,8>>^ Pois não podemos fazer nada contra a verdade, mas somente a favor da verdade.

[[v47-13-9]]

^<<v47-13-9,9>>^ Nós certamente nos alegramos sempre que estamos fracos e vocês poderosos. E o que pedimos em oração é que vocês sejam reajustados.

[TIP]
====
- *sejam reajustados*: Ou: “sejam colocados no alinhamento correto”. A palavra grega que aparece aqui é katártisis. Esta é a única vez que ela foi usada nas Escrituras Gregas Cristãs. Tanto katártisis como outros termos relacionados passam a ideia de restaurar algo a uma condição correta. Por exemplo, em Mt 4:21, o verbo katartízo foi usado para falar de “consertar” redes. Esse verbo também foi usado em Gál 6:1 para se referir à necessidade de reajustar em sentido espiritual um irmão que deu um passo em falso. O substantivo katartismós, traduzido como “reajustamento” em Ef 4:12, era usado às vezes em textos médicos para se referir a colocar um osso, um membro ou uma articulação no lugar.
====

[[v47-13-10]]

^<<v47-13-10,10>>^ É por isso que escrevo estas coisas enquanto estou ausente, para que, quando estiver presente, não tenha de ser severo ao usar a autoridade que o Senhor me deu, que é para edificar, e não para derrubar.

[[v47-13-11]]

^<<v47-13-11,11>>^ Finalmente, irmãos, continuem a se alegrar, a ser reajustados, a ser consolados, a pensar do mesmo modo, a viver pacificamente; e o Deus de amor e de paz estará com vocês.

[TIP]
====
- *continuem . . . a ser reajustados*: Veja a nota de estudo em 2Co 13:9.
====

[[v47-13-12]]

^<<v47-13-12,12>>^ Cumprimentem uns aos outros com beijo santo.

[TIP]
====
- *com beijo santo*: Veja a nota de estudo em Ro 16:16.
====

[[v47-13-13]]

^<<v47-13-13,13>>^ Todos os santos lhes mandam saudações.

[[v47-13-14]]

^<<v47-13-14,14>>^ A bondade imerecida do Senhor Jesus Cristo, o amor de Deus e a participação no espírito santo estejam com todos vocês.

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]