include::./index.adoc[]

[[v46-3-0]]
=== A Primeira aos Coríntios, 3
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* B. A IMPORTÂNCIA DA UNIÃO NA CONGREGAÇÃO CRISTÃ (1:10–4:21)
* 1. Coisas que contribuem para a união ou a desunião (1:10–2:16)
* Seguir humanos causa divisões (1:10-17)
* Reconhecer a Cristo, que é o poder e a sabedoria de Deus (1:18-25)
* Orgulhar-se somente em Jeová, não em humanos (1:26-31)
* Pregar como Paulo, sem usar linguagem ou sabedoria extravagantes (2:1-5)
* Reconhecer a superioridade da sabedoria de Deus (2:6-10)
* Receber o espírito que vem de Deus; ser um homem espiritual (2:11-16)
* 2. Cooperar com Deus para que a congregação cresça e seja unida (3:1-23)
* Pensamento carnal gera ciúme e brigas (3:1-4)
* Humanos são ministros, mas é Deus quem faz crescer (3:5-9)
* Construir com materiais resistentes ao fogo (3:10-15)
* “Vocês . . . são templo de Deus” (3:16, 17)
* A sabedoria do mundo é tolice perante Deus (3:18-23)
* 3. Conselhos adicionais que contribuem para a união (4:1-21)
* O que importa é o julgamento de Jeová (4:1-5)
* Cristãos que são humildes não se acham melhores do que os seus irmãos (4:6-13)
* Paulo aconselha seus filhos espirituais a não serem orgulhosos (4:14-21)
****

[[v46-3-1]]

^<<v46-3-1,1>>^ Assim, irmãos, não lhes pude falar como a homens espirituais, mas como a homens carnais, como a criancinhas em Cristo.

[[v46-3-2]]

^<<v46-3-2,2>>^ Eu os alimentei com leite, não com alimento sólido, pois vocês ainda não eram fortes o suficiente. De fato, nem mesmo agora são fortes o suficiente,

[TIP]
====
- *com leite, não com alimento sólido*: Assim como o leite ajuda a criança a crescer e se desenvolver, os ensinos básicos da Bíblia ajudam os que se tornam cristãos a crescer e se desenvolver em sentido espiritual. (He 5:12–6:2) Essas verdades básicas são essenciais para a salvação. (1Pe 2:2) Mas Paulo queria que os cristãos em Corinto continuassem crescendo em sentido espiritual ou, como ele disse aos cristãos judeus em Jerusalém, que eles ‘avançassem à madureza’. (He 6:1) Assim, Paulo mostra aqui que é importante ingerir alimento sólido, ou seja, verdades espirituais profundas.
====

[[v46-3-3]]

^<<v46-3-3,3>>^ pois ainda são carnais. Visto que há entre vocês ciúme e brigas, não é verdade que são carnais e estão andando como homens?

[[v46-3-4]]

^<<v46-3-4,4>>^ Pois, quando um diz: “Eu pertenço a Paulo”, mas outro diz: “Eu a Apolo”, será que vocês não estão agindo como simples homens?

[TIP]
====
- *Apolo*: Veja a nota de estudo em 1Co 1:12.
====

[[v46-3-5]]

^<<v46-3-5,5>>^ O que, então, é Apolo? Sim, o que é Paulo? Ministros por meio de quem vocês se tornaram crentes, assim como o Senhor concedeu a cada um.

[TIP]
====
- *Ministros*: Ou: “Servos”. A Bíblia muitas vezes usa a palavra grega diákonos para se referir a uma pessoa que presta serviço a outros de modo humilde e perseverante. (Veja a nota de estudo em Mt 20:26.) Em Ro 15:8, essa palavra é usada para se referir a Jesus. (Veja a nota de estudo.) Aqui em 1Co 3:5, Paulo fala de si mesmo e de Apolo como ministros, ou servos, que tinham ajudado os coríntios a se tornarem cristãos. O ministério de Paulo e Apolo (assim como o ministério de qualquer cristão batizado) envolvia ajudar outras pessoas a satisfazerem suas necessidades espirituais. — Lu 4:16-21.
====

[[v46-3-6]]

^<<v46-3-6,6>>^ Eu plantei, Apolo regou, mas Deus fazia crescer,

[TIP]
====
- *Eu plantei, Apolo regou*: Aqui, Paulo compara o ministério cristão ao trabalho de um lavrador. Quando Paulo levou as boas novas para as pessoas de Corinto, era como se ele estivesse plantando uma semente (a mensagem do Reino) em uma lavoura. O trabalho que Apolo fez depois, continuando a ensinar aquelas pessoas, poderia ser comparado a regar e nutrir a semente. (At 18:24; 19:1) Mas foi Deus, por meio do seu espírito, quem fez aqueles novos discípulos crescerem em sentido espiritual. O ponto da ilustração de Paulo era que o crescimento espiritual não depende dos esforços individuais de nenhum humano. Todos são ministros, trabalhando juntos como “colaboradores de Deus”. (1Co 3:9) Deus, por sua vez, abençoa os esforços altruístas de seus servos e é o verdadeiro responsável pelo crescimento.
====

[[v46-3-7]]

^<<v46-3-7,7>>^ de modo que nem o que planta nem o que rega são alguma coisa, mas sim Deus, que faz crescer.

[[v46-3-8]]

^<<v46-3-8,8>>^ Quem planta e quem rega são um só, mas cada um receberá a sua própria recompensa, segundo o seu próprio trabalho.

[TIP]
====
- *são um só*: Ou: “têm um só propósito”. Aqui, Paulo usa estas palavras para descrever a união que existe entre os cristãos quando eles trabalham juntos uns com os outros e com Deus. (1Co 3:9) A palavra grega traduzida aqui como “um só” não está no gênero masculino (indicando “uma pessoa”), mas no gênero neutro (indicando “uma coisa”). Assim, Paulo fala que quem planta e quem rega são “um só” no sentido de que eles agem de modo unido, cooperando um com o outro. — Veja as notas de estudo em Jo 10:30; 17:11, 21, onde a palavra grega traduzida aqui como “um só” foi usada de forma parecida.
====

[[v46-3-9]]

^<<v46-3-9,9>>^ Pois somos colaboradores de Deus. Vocês são lavoura de Deus, edifício de Deus.

[TIP]
====
- *colaboradores de Deus*: A palavra grega para “colaborador”, synergós, ocorre mais de dez vezes nas Escrituras Gregas Cristãs, a maioria delas nas cartas de Paulo. Ela foi usada para se referir aos que trabalhavam juntos divulgando as boas novas. (Ro 16:9, 21; 2Co 1:24; 8:23; Fil 2:25; 4:3; Col 4:11; Flm 1, 24) Aqui, Paulo chama atenção ao enorme privilégio que os cristãos têm de serem “colaboradores de Deus”. (Veja a nota de estudo em 1Co 3:6.) Em 2Co 6:1, Paulo expressa uma ideia parecida quando fala sobre ‘cooperar com ele’, ou seja, com Deus. — 2Co 5:20; veja a nota de estudo em Ro 16:3.
- *Vocês são lavoura de Deus*: O verdadeiro dono da lavoura figurativa onde os cristãos estavam crescendo era Deus, e não Paulo. Sem as bênçãos e o espírito de Deus, o trabalho de Paulo e de Apolo não teria tido nenhum resultado. (Veja a nota de estudo em 1Co 3:6.) Esta é a única vez que a palavra grega geórgion, traduzida aqui como “lavoura”, aparece nas Escrituras Gregas Cristãs. Apesar de a economia de Corinto se basear principalmente no comércio, as terras da região eram famosas por serem muito férteis. Além dessa comparação ligada à agricultura, neste versículo Paulo também faz uma comparação relacionada à construção. (Veja a nota de estudo em edifício de Deus neste versículo.) Tanto a agricultura como a construção eram atividades comuns no mundo antigo. Por usar essas duas comparações, Paulo conseguiu tocar o coração de diferentes membros da congregação.
- *edifício de Deus*: Aqui, Paulo compara a congregação cristã a um edifício. No versículo seguinte, Paulo se compara a um construtor que estava trabalhando junto com Deus numa obra de construção espiritual. Essa obra envolvia produzir cristãos que tivessem qualidades que os ajudariam a permanecer firmes. (1Co 3:10-15) Em 1Co 3:16 (veja a nota de estudo), Paulo chama a congregação de “templo de Deus”. E, em Ef 2:21, 22, ele diz que a congregação é “um templo santo” em que Deus habita “por espírito”. Deus faz isso usando seu espírito santo (sua força ativa invisível) para motivar e dar apoio aos cristãos da congregação e para ajudá-los a desenvolver o fruto do espírito. (Gál 5:22, 23) O apóstolo Pedro faz uma comparação parecida em 1Pe 2:5, onde ele chama os discípulos de “pedras viventes”. Em Ef 2:20, Paulo compara os apóstolos e profetas ao alicerce, e Jesus à “pedra angular de alicerce”.
====

[[v46-3-10]]

^<<v46-3-10,10>>^ Segundo a bondade imerecida de Deus que me foi concedida, eu lancei um alicerce como construtor perito, mas outro constrói sobre ele. Que cada um, porém, preste atenção a como constrói sobre ele.

[TIP]
====
- *construtor perito*: Ou: “sábio diretor de obras”. A palavra grega arkhitékton poderia ser traduzida literalmente como “artesão principal”. Essa palavra geralmente era usada para se referir ao encarregado de uma construção, que trabalhava no canteiro de obras. Ele contratava os trabalhadores e supervisionava o serviço deles. Neste versículo, Paulo se compara a um construtor que estava trabalhando junto com Deus numa obra de construção espiritual. Essa obra envolvia produzir cristãos que tivessem qualidades que os ajudariam a permanecer firmes. (1Co 3:9-16) Esta é a única vez que a palavra arkhitékton aparece nas Escrituras Gregas Cristãs. A palavra grega relacionada tékton foi usada para se referir a Jesus e a seu pai adotivo, José, e foi traduzida como “carpinteiro”. — Veja as notas de estudo em Mt 13:55; Mr 6:3.
====

[[v46-3-11]]

^<<v46-3-11,11>>^ Pois ninguém pode lançar outro alicerce, a não ser o que já foi lançado, que é Jesus Cristo.

[[v46-3-12]]

^<<v46-3-12,12>>^ Ora, se alguém construir sobre o alicerce com ouro, prata, pedras preciosas, ou com madeira, feno, palha,

[TIP]
====
- *com ouro, prata, pedras preciosas, ou com madeira, feno, palha*: Nesta passagem, Paulo incentiva os cristãos em Corinto que estavam dando continuidade ao seu trabalho a serem bons instrutores, ajudando os novos discípulos a desenvolverem qualidades cristãs. (1Co 3:6) Para ilustrar isso, Paulo faz um contraste entre construir com materiais de boa qualidade, resistentes ao fogo e duráveis, e construir com materiais inferiores, inflamáveis e que não duravam muito. Mesmo sendo uma cidade rica, Corinto sem dúvida tinha construções dos dois tipos. Havia templos impressionantes, feitos com blocos de pedra enormes e caros. Alguns deles talvez fossem decorados com ouro e prata. É bem provável que perto desses templos houvesse moradias pobres e barracas de feira feitas com estruturas simples de madeira e telhado de palha. Na ilustração de Paulo, o ouro, a prata e as pedras preciosas representam qualidades cristãs como forte fé, sabedoria divina, discernimento, lealdade, e apreço e amor por Jeová e por suas leis. Qualidades como essas são indispensáveis para que os cristãos tenham uma forte amizade com Jeová Deus e, assim, consigam resistir a testes de fé.
====

[[v46-3-13]]

^<<v46-3-13,13>>^ a qualidade da obra de cada um ficará evidente,^&#42;1^ pois o dia a porá à mostra; porque será revelada por meio de fogo, e o próprio fogo mostrará que tipo de obra cada um realizou.

[NOTE]
====
. Ou: “será claramente vista”. Lit.: “será tornada manifesta”.
====

[[v46-3-14]]

^<<v46-3-14,14>>^ Se a obra que alguém construiu sobre o alicerce permanecer, ele receberá uma recompensa;

[[v46-3-15]]

^<<v46-3-15,15>>^ caso se queime a obra de alguém, ele sofrerá perda, mas ele mesmo será salvo; contudo, nesse caso, será como que através do fogo.

[TIP]
====
- *será como que através do fogo*: Os ministros cristãos precisam ajudar seus estudantes a desenvolver qualidades cristãs que resistam a testes de fé. Ao fazer isso, eles estão como que construindo com materiais resistentes ao fogo. (1Co 3:10-14) Se um instrutor cristão não seguir as instruções da Bíblia sobre como fazer o seu trabalho, pode ser que sua “obra” não resista quando passar por um teste de fogo. (Mt 28:19, 20; Ro 2:21, 22; 1Ti 4:16; 2Ti 2:15; 4:2) Além disso, o próprio instrutor pode acabar sofrendo, como se fosse um homem que perdeu tudo em um incêndio e que por pouco se salvou. Assim como Paulo usa aqui a palavra “fogo” em sentido figurado, outros escritores gregos usaram a expressão “através do fogo” como uma metáfora para dizer que alguém tinha escapado por pouco de um problema ou de uma situação difícil.
====

[[v46-3-16]]

^<<v46-3-16,16>>^ Vocês não sabem que são templo de Deus e que o espírito de Deus mora em vocês?

[TIP]
====
- *Vocês . . . são templo de Deus*: Esta é uma das várias vezes que a Bíblia compara pessoas a um templo. Em Jo 2:19, o próprio Jesus se comparou a um templo. Além disso, as Escrituras diziam que Jesus se tornaria “a principal pedra angular” de um templo espiritual. (Sal 118:22; Is 28:16, 17; At 4:10, 11) O verbo grego traduzido aqui como “são” está na segunda pessoa do plural. Isso indica que todos os cristãos ungidos formam, como grupo, o “templo de Deus” em que o espírito dele mora. Esses cristãos, que servem como sacerdotes, são “edifício de Deus”. (1Co 3:9; veja a nota de estudo.) Por isso, o versículo 17 destaca que esse templo espiritual é santo e alerta sobre as consequências de tentar profaná-lo. Em Ef 2:20-22 e 1Pe 2:6, 7, Paulo e Pedro fazem comparações parecidas ao falar de Jesus e de seus seguidores.
====

[[v46-3-17]]

^<<v46-3-17,17>>^ Se alguém destruir o templo de Deus, Deus o destruirá; pois o templo de Deus é santo, e vocês são esse templo.

[[v46-3-18]]

^<<v46-3-18,18>>^ Que ninguém engane a si mesmo: se alguém entre vocês pensa que é sábio neste sistema de coisas, torne-se tolo, para que se torne sábio.

[TIP]
====
- *neste sistema de coisas*: Veja a nota de estudo em 1Co 1:20.
====

[[v46-3-19]]

^<<v46-3-19,19>>^ Porque a sabedoria deste mundo é tolice perante Deus, pois está escrito: “Ele apanha os sábios na sua própria astúcia.”

[TIP]
====
- *pois está escrito*: O que Paulo diz em seguida é uma citação das palavras de Elifaz, o temanita. Quando Elifaz falou com Jó, ele disse que Deus “apanha os sábios na sua própria astúcia” e aplicou essas palavras de forma errada a Jó. (Jó 4:1; 5:13) O fato de Paulo ter feito essa citação não significa que ele apoiava tudo o que Elifaz disse, já que muitas coisas eram mentira ou tinham sido mal aplicadas. (Jó 42:7) Mas a observação de Elifaz registrada em Jó 5:13 reflete uma verdade que está de acordo com outros versículos das Escrituras. (Sal 10:2; compare Jó 5:17 com Sal 94:12.) Paulo foi inspirado a citar essas palavras para mostrar que não há como comparar a sabedoria do homem com a sabedoria de Deus.
====

[[v46-3-20]]

^<<v46-3-20,20>>^ E também: “Jeová sabe que os raciocínios dos sábios são fúteis.”

[TIP]
====
- *Jeová*: Esta é uma citação do Sal 94:11. No texto hebraico original desse salmo, aparecem as quatro letras hebraicas que formam o nome de Deus (que equivalem a YHWH). — Veja os Apêndices C1 e C2.
====

[[v46-3-21]]

^<<v46-3-21,21>>^ Assim, que ninguém ponha seu orgulho nos homens; porque a vocês pertence tudo:

[[v46-3-22]]

^<<v46-3-22,22>>^ quer Paulo, quer Apolo, quer Cefas, quer o mundo, quer a vida, quer a morte, quer as coisas presentes, quer as coisas por vir, tudo pertence a vocês;

[TIP]
====
- *Cefas*: Veja a nota de estudo em 1Co 1:12.
====

[[v46-3-23]]

^<<v46-3-23,23>>^ vocês, por sua vez, pertencem a Cristo; Cristo, por sua vez, pertence a Deus.

'''

xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[&#60; Capítulo Anterior] | <<v46-3-0,Topo>> | xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[Próximo Capítulo &#62;]