include::./index.adoc[]

[[v46-7-0]]
=== A Primeira aos Coríntios, 7
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* D. CONSELHOS SOBRE SE CASAR OU FICAR SOLTEIRO (7:1-40)
* 1. Conselhos para os casados e os não casados (7:1-24)
* Marido e esposa devem dar um ao outro o que é devido, mostrando consideração (7:1-7)
* “É melhor se casar do que ficar ardendo de paixão” (7:8, 9)
* O marido ou a esposa ser descrente não é motivo para separação; talvez, com o tempo, o cristão possa ajudar seu cônjuge a ganhar a salvação (7:10-16)
* Cada um permaneça no estado em que foi chamado (7:17-24)
* 2. Os não casados e as viúvas (7:25-40)
* Melhor a pessoa continuar como está; “o tempo que resta é reduzido” (7:25-31)
* Quem permanece solteiro tem mais liberdade para dar plena devoção a Deus (7:32-35)
* Não é errado se casar, mas isso deve ser feito “somente no Senhor” (7:36-40)
****

[[v46-7-1]]

^<<v46-7-1,1>>^ Agora, quanto às coisas sobre as quais vocês escreveram, é melhor que o homem não toque em mulher;

[TIP]
====
- *Agora, quanto às coisas sobre as quais vocês escreveram*: Tanto estas palavras como as de 1Co 8:1 mostram que os irmãos em Corinto tinham escrito a Paulo, fazendo perguntas sobre casamento e sobre se era correto comer alimentos oferecidos a ídolos. — Veja as notas de estudo em 1Co 1:2; 8:1.
- *não toque em mulher*: Ou seja, não tenha nenhum contato sexual com uma mulher. Entender estas palavras dessa maneira está de acordo com outros versículos da Bíblia em que “tocar” significa ter contato sexual ou relações sexuais com alguém. (Gên 20:6, 7; Pr 6:29) Paulo não está falando de relações sexuais dentro do casamento, visto que ele incentiva marido e esposa a darem um ao outro o que é devido. (1Co 7:3-5; veja a nota de estudo em 1Co 7:3.) Como mostra o contexto, quando Paulo disse que “é melhor que o homem não toque em mulher”, ele estava incentivando cristãos não casados a continuarem solteiros. — 1Co 7:6-9; compare com Mt 19:10-12.
====

[[v46-7-2]]

^<<v46-7-2,2>>^ mas, visto que há tanta imoralidade sexual, que cada homem tenha a sua própria esposa, e que cada mulher tenha o seu próprio marido.

[TIP]
====
- *há tanta imoralidade sexual*: Aqui, o texto grego usa uma única palavra, a forma plural de porneía. Algumas Bíblias traduzem essa parte do versículo como “a imoralidade sexual é tão comum [ou: “está em todo o lugar”]”. Isso descreve bem a situação que existia em Corinto. — Veja a nota de estudo em 1Co 5:9.
====

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido dê à esposa o que lhe é devido, e faça a esposa o mesmo para com o marido.

[TIP]
====
- *o que lhe é devido*: Lit.: “a dívida; a obrigação”. Isto se refere às relações sexuais que fazem parte do casamento, que é um presente de Deus. O marido e a esposa não devem negar essa expressão de amor um ao outro, a não ser por consentimento mútuo. (1Co 7:5) Jesus mencionou outra exceção: se o marido ou a esposa for infiel, a pessoa inocente tem a opção de não manter relações sexuais e pedir o divórcio. — Mt 5:32; 19:9.
====

[[v46-7-4]]

^<<v46-7-4,4>>^ A esposa não tem autoridade sobre o seu próprio corpo, mas sim o marido; do mesmo modo, o marido não tem autoridade sobre o seu próprio corpo, mas sim a esposa.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não privem um ao outro do que é devido, a não ser por consentimento mútuo, por um tempo determinado, para que dediquem tempo à oração e depois se unam novamente, a fim de que Satanás não os tente pela sua falta de autodomínio.

[[v46-7-6]]

^<<v46-7-6,6>>^ No entanto, digo isso como concessão, não como ordem.

[TIP]
====
- *como concessão*: Ou: “como permissão”. Pelo visto, estas palavras se referem ao conselho que Paulo deu em 1Co 7:2.
====

[[v46-7-7]]

^<<v46-7-7,7>>^ Mas eu queria que todos os homens fossem como eu. Entretanto, cada um tem o seu próprio dom da parte de Deus, um desse modo, outro daquele modo.

[TIP]
====
- *como eu*: O apóstolo Paulo não era casado quando fez suas viagens missionárias, e a Bíblia não diz especificamente se ele já tinha sido casado. Mas, com base em algumas coisas que Paulo disse, existe a possibilidade de que ele fosse viúvo. — 1Co 7:8; 9:5.
====

[[v46-7-8]]

^<<v46-7-8,8>>^ Agora, digo aos que não são casados e às viúvas que é melhor para eles que permaneçam assim como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se não tiverem autodomínio, que se casem, pois é melhor se casar do que ficar ardendo de paixão.

[[v46-7-10]]

^<<v46-7-10,10>>^ Aos casados ordeno, não eu, mas o Senhor, que a esposa não se separe do marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Mas, se ela se separar, que permaneça sem se casar, ou então que se reconcilie com o marido; e o marido não deve deixar a esposa.

[TIP]
====
- *que se reconcilie*: Aqui, Paulo usa o verbo katallásso, que é uma palavra composta e tem o sentido básico de “trocar”. Nas Escrituras Gregas Cristãs, katallásso é usado com o sentido de “mudar de inimizade para amizade” ou de “restaurar a harmonia”. Paulo pode ter usado esse verbo ao falar de casamento para mostrar que um casal que está com problemas pode “trocar” o seu relacionamento ruim por um relacionamento harmonioso um com outro, assim como é possível trocar um relacionamento ruim com Deus por um relacionamento de paz com ele. — Veja a nota de estudo em Ro 5:10.
====

[[v46-7-12]]

^<<v46-7-12,12>>^ Mas aos outros digo eu, sim, eu, não o Senhor: Se algum irmão tem esposa descrente, e ela está disposta a ficar com ele, que ele não a deixe;

[TIP]
====
- *digo eu, sim, eu, não o Senhor*: Várias vezes neste capítulo, Paulo faz uma diferença entre suas próprias ideias e opiniões e as palavras de Cristo. (Veja também os versículos 25 e 40.) Parece que Paulo estava sendo humilde e chamando a atenção dos seus leitores ao fato de que, em alguns assuntos, não era possível citar um ensinamento específico de Jesus Cristo. Mas Paulo podia dar sua opinião como um apóstolo de Cristo que estava cheio de espírito santo. Jesus tinha prometido que esse espírito guiaria seus seguidores “a toda a verdade”. (Jo 16:13) Assim, os conselhos de Paulo foram inspirados por Deus e, como as outras partes das Escrituras, dão orientações úteis e confiáveis para todos os cristãos. — 2Ti 3:16.
- *esposa descrente*: Neste contexto, a palavra traduzida como “descrente” não se refere a uma esposa que não tinha nenhuma crença religiosa. Ela se refere a uma esposa que não tinha fé em Jesus e não era dedicada a Jeová, como, por exemplo, uma mulher que era judia ou que acreditava em deuses pagãos.
====

[[v46-7-13]]

^<<v46-7-13,13>>^ e se uma mulher tem marido descrente, e ele está disposto a ficar com ela, que ela não deixe o marido.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois o marido descrente está santificado em relação à esposa, e a esposa descrente está santificada em relação ao irmão; do contrário, os seus filhos seriam impuros, mas agora são santos.

[TIP]
====
- *descrente*: Neste contexto, Paulo usa a palavra “descrente” para se referir a pessoas que não exercem fé no sacrifício de resgate de Jesus Cristo. Elas não se separaram do mundo impuro e não foram libertadas da escravidão ao pecado. Pessoas descrentes podem até ser honestas e levar uma vida moralmente correta, mas elas não são santas, ou puras, aos olhos de Deus. — Jo 8:34-36; 2Co 6:17; Tg 4:4; veja a nota de estudo em está santificado em relação à neste versículo.
- *está santificado em relação à*: O verbo grego hagiázo, traduzido aqui como “está santificado”, e o adjetivo relacionado hágios, que significa “santo”, passam a ideia de ser separado para Deus. Assim, algo santificado é algo santo, puro, separado para o serviço de Deus. (Mr 6:20; 2Co 7:1; 1Pe 1:15, 16; veja o Glossário, “Santo; Santidade”.) Para ter essa condição pura aos olhos de Deus, a pessoa precisa exercer fé no sacrifício de resgate que Deus providenciou por meio de seu Filho. Aqui, Paulo indica que Deus encara a união entre o cristão e o descrente como pura e honrosa. — Veja a nota de estudo em descrente neste versículo.
- *santos*: Neste versículo, Paulo chama os filhos de “santos”, mas ele não diz que o casamento torna ‘santo’ o marido ou a esposa descrente, que talvez esteja até praticando coisas erradas ou impuras. Em vez disso, Paulo diz que o descrente está santificado apenas com “relação” ao cristão. A união deles é vista por Deus como pura e honrosa. Por causa do cristão, os filhos pequenos do casal são considerados santos e estão debaixo do cuidado e da proteção de Deus — uma condição melhor do que a dos filhos que não têm nem pai nem mãe cristãos.
====

[[v46-7-15]]

^<<v46-7-15,15>>^ No entanto, se o descrente decidir deixá-la, que a deixe; o irmão ou a irmã não estão sob obrigação nessas circunstâncias, mas Deus chamou vocês à paz.

[TIP]
====
- *deixá-la*: Ou: “separar-se”. Em 1Co 7:10, 11, a mesma palavra grega que aparece aqui (khorízo) foi traduzida como “separar-se”.
====

[[v46-7-16]]

^<<v46-7-16,16>>^ Pois, esposa, como sabe se não salvará o seu marido? Ou, marido, como sabe se não salvará a sua esposa?

[[v46-7-17]]

^<<v46-7-17,17>>^ Contudo, que cada um ande conforme a porção que Jeová lhe deu, conforme Deus o chamou. E assim dou esta ordem em todas as congregações.

[TIP]
====
- *que cada um ande conforme a porção que Jeová lhe deu*: Ou: “que cada um ande conforme a porção que Jeová deu a cada um”. Aqui, a palavra “porção” se refere às circunstâncias de vida de uma pessoa, tanto as criadas por Jeová como as que ele simplesmente permite. Paulo incentiva cada cristão a andar, ou seja, a levar a vida, sem se preocupar demais em mudar suas circunstâncias. A palavra grega traduzida como “cada um” aparece duas vezes no texto original deste versículo. Paulo talvez tenha usado essa palavra duas vezes para destacar que Deus se preocupa com cada cristão de modo individual. Embora a maioria dos manuscritos gregos use aqui a expressão “o Senhor” (ho Kýrios), há bons motivos para se usar o nome de Deus no texto principal. — Veja o Apêndice C3 (introdução e 1Co 7:17).
- *Deus*: Os manuscritos gregos mais antigos dizem “Deus” nesta parte do versículo, mas alguns outros manuscritos dizem “Senhor”. Algumas traduções das Escrituras Gregas Cristãs para o hebraico (chamadas de J7, 8, 10 no Apêndice C4) usam o nome de Deus aqui e dizem “Jeová”.
====

[[v46-7-18]]

^<<v46-7-18,18>>^ Alguém já era circuncidado quando foi chamado? Que não desfaça a circuncisão. Alguém era incircunciso quando foi chamado? Não seja circuncidado.

[TIP]
====
- *Que não desfaça a circuncisão*: Aqui, Paulo talvez esteja fazendo referência a um procedimento ao qual alguns atletas judeus escolhiam se submeter para participar dos jogos helenísticos. Nesses jogos, os atletas corriam nus. Para não serem ridicularizados, alguns atletas judeus tentavam ‘desfazer sua circuncisão’ por meio de uma cirurgia que dava a aparência de que eles não tinham removido o prepúcio. Pelo visto, diferentes opiniões sobre a circuncisão estavam dividindo a congregação em Corinto. Por isso, Paulo aconselhou os cristãos ali, tanto os circuncisos como os incircuncisos, a não tentarem mudar o estado em que tinham sido chamados. — 1Co 7:17-20; He 13:17.
====

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão não significa nada, e a incircuncisão não significa nada; o que importa é a obediência aos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Que cada um permaneça no estado em que foi chamado.

[[v46-7-21]]

^<<v46-7-21,21>>^ Você foi chamado quando escravo? Não se preocupe com isso; mas, se puder ficar livre, aproveite a oportunidade.

[[v46-7-22]]

^<<v46-7-22,22>>^ Pois todo aquele que era escravo quando foi chamado no Senhor é agora o liberto que pertence ao Senhor; igualmente, aquele que era livre quando foi chamado é agora escravo de Cristo.

[TIP]
====
- *o liberto que pertence ao Senhor . . . aquele que era livre*: A palavra grega apeleútheros, traduzida aqui como “liberto”, se refere a alguém que foi libertado da escravidão. Esta é a única vez que essa palavra grega aparece nas Escrituras. Mas as pessoas de Corinto conheciam essa palavra, já que muitos “libertos” tinham se mudado para lá na época em que os romanos reconstruíram a cidade. Na congregação de Corinto, havia cristãos libertos, mas também havia cristãos que nunca tinham sido escravos; eles eram “livres” (em grego, eleútheros) desde seu nascimento. Todos os cristãos foram “comprados por um preço”, ou seja, o sangue precioso de Jesus. Assim, tanto o “liberto” como o “livre” eram, na verdade, escravos de Deus e de Jesus Cristo, e precisavam obedecer às ordens deles. Na congregação cristã, não havia diferença entre o escravo, o liberto e o livre. — 1Co 7:23; Gál 3:28; He 2:14, 15; 1Pe 1:18, 19; 2:16; veja o Glossário, “Livre; Liberto”.
====

[[v46-7-23]]

^<<v46-7-23,23>>^ Vocês foram comprados por um preço; parem de se tornar escravos de homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, que cada um permaneça diante de Deus no estado em que foi chamado.

[[v46-7-25]]

^<<v46-7-25,25>>^ Agora, no que se refere aos que são virgens, não tenho ordem da parte do Senhor, mas dou a minha opinião como alguém que é fiel pela misericórdia do Senhor.

[TIP]
====
- *aos que são virgens*: Ou: “aos que nunca se casaram”. A palavra grega parthénos, que muitas vezes é traduzida como “virgem”, significa literalmente “alguém que nunca teve relações sexuais”. Ela pode ser usada em sentido literal ou figurado para se referir tanto a homens como a mulheres. (Mt 25:1-12; Lu 1:27; Ap 14:4; veja a nota de estudo em At 21:9.) Mas, nos versículos 32 a 35, Paulo amplia a aplicação de seus conselhos para incluir todos os que não estão casados, não apenas os virgens.
- *dou a minha opinião*: Aqui, Paulo deixa claro que está dando sua opinião pessoal sobre a escolha de se casar ou ficar solteiro. Ele não condena ou proíbe o casamento, mas, debaixo de inspiração, ele destaca as vantagens que os solteiros têm no serviço do Senhor. — Veja a nota de estudo em 1Co 7:12.
====

[[v46-7-26]]

^<<v46-7-26,26>>^ Portanto, penso que é melhor o homem continuar como está, em vista das dificuldades atuais.

[[v46-7-27]]

^<<v46-7-27,27>>^ Você está amarrado a uma esposa? Pare de tentar ficar livre. Você não está amarrado a uma esposa? Pare de procurar uma esposa.

[[v46-7-28]]

^<<v46-7-28,28>>^ Mas, mesmo que você se case, não comete pecado. E, se uma pessoa virgem se casa, não comete pecado. No entanto, os que fizerem isso terão dificuldades na vida. Mas eu estou tentando poupá-los disso.

[TIP]
====
- *uma pessoa virgem*: Veja a nota de estudo em 1Co 7:25.
- *dificuldades na vida*: Lit.: “tribulação na carne”. A palavra grega traduzida aqui como “dificuldades” muitas vezes é traduzida como “tribulação”, mas também poderia ser traduzida como “aflições; problemas”. Ela tem o sentido básico de “angústia ou sofrimento causados pela pressão das circunstâncias”. A palavra grega traduzida aqui como “vida” (lit.: “carne”) é muitas vezes usada para se referir a um humano. (Veja a nota de estudo em Ro 3:20.) Neste contexto, a expressão literal “tribulação na carne” se refere aos problemas e desafios que são comuns na vida de um casal, que se torna “uma só carne” aos olhos de Deus. (Mt 19:6) Algumas traduções da Bíblia traduzem essas palavras como “problemas na vida; os problemas do dia a dia”. As “dificuldades” ligadas ao casamento e à vida familiar podem ser causadas por doença, problemas econômicos e, no caso dos cristãos, perseguição. — Veja a nota de estudo em 2Co 1:4.
====

[[v46-7-29]]

^<<v46-7-29,29>>^ Além disso, digo o seguinte, irmãos: O tempo que resta é reduzido. De agora em diante, aqueles que têm esposa vivam como se não tivessem;

[[v46-7-30]]

^<<v46-7-30,30>>^ os que choram, como quem não chora; os que se alegram, como quem não se alegra; os que compram, como quem não possui;

[[v46-7-31]]

^<<v46-7-31,31>>^ e os que fazem uso do mundo, como quem não o usa plenamente. Porque a cena deste mundo está mudando.

[TIP]
====
- *fazem uso do mundo*: Nas Escrituras Gregas Cristãs, a palavra “mundo” (kósmos) é usada para se referir principalmente à humanidade. (Veja as notas de estudo em Jo 1:9, 10; 3:16.) Mas, aqui, essa palavra tem um sentido mais amplo e se refere à estrutura em que a humanidade está organizada, ou seja, ao sistema mundial dentro do qual a sociedade humana funciona e as pessoas vivem. Esse “mundo” inclui coisas ligadas ao sistema econômico como, por exemplo, moradia, comida e roupa. (Veja a nota de estudo em Lu 9:25.) Para que os cristãos e suas famílias tenham essas coisas necessárias, eles “fazem uso do mundo”. Mas eles tomam cuidado para não usar o mundo plenamente, ou seja, eles não deixam que essas coisas se tornem o foco principal de sua vida.
- *a cena deste mundo está mudando*: A palavra grega traduzida aqui como “cena” pode ser definida como “aparência ou forma de algo; estrutura atual das coisas”. Paulo talvez estivesse fazendo referência às peças teatrais de seus dias e comparando o mundo a um palco onde as cenas e os atores mudam com frequência. As palavras de Paulo talvez também incluam a ideia de que o mundo como ele é hoje (em sua forma e estrutura atuais) “está passando”. — 1Jo 2:17.
====

[[v46-7-32]]

^<<v46-7-32,32>>^ Realmente, quero que vocês estejam livres de preocupação. O homem que não é casado se preocupa com as coisas do Senhor, em como pode agradar ao Senhor.

[TIP]
====
- *se preocupa com*: O verbo grego traduzido aqui como “se preocupa com” é merimnáo. O significado desse verbo depende do contexto. Neste contexto, ele foi usado em sentido positivo e passa a ideia de estar ansioso para se envolver em atividades espirituais, com o objetivo de agradar ao Senhor. Nos versículos 33 e 34, esse mesmo verbo é usado para se referir à preocupação que o marido e a esposa têm em cuidar das necessidades emocionais, físicas e materiais um do outro. De acordo com 1Co 12:25, os cristãos em geral também devem se preocupar com as necessidades uns dos outros. Mas, em outros contextos, esse verbo grego foi usado em sentido negativo e se refere ao tipo de preocupação ou ansiedade que divide e distrai a mente da pessoa, tirando sua alegria. — Mt 6:25, 27, 28, 31, 34; Lu 12:11, 22, 25, 26; veja as notas de estudo em Mt 6:25; Lu 12:22.
- *as coisas do Senhor*: Ou seja, tudo o que é feito para dar apoio ao Filho de Deus e ao seu Pai, Jeová. As “coisas” mencionadas aqui envolvem basicamente a vida, a adoração e o ministério do cristão. — Mt 4:10; Ro 14:8; 2Co 2:17; 3:5, 6; 4:1; veja a nota de estudo em 1Co 7:33.
====

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o homem casado se preocupa com as coisas do mundo, em como pode agradar à esposa,

[TIP]
====
- *as coisas do mundo*: Aqui, a palavra grega kósmos (“mundo”) se refere a tudo o que está envolvido na vida humana, incluindo a estrutura em que a humanidade está organizada. As “coisas” mencionadas neste versículo incluem atividades do dia a dia que não estão relacionadas com assuntos espirituais, como as que são necessárias para conseguir comida, roupa e moradia. Neste contexto, Paulo não estava se referindo às coisas que fazem parte deste mundo mau e que devem ser evitadas pelos cristãos, como as que são mencionadas em 1Jo 2:15-17. — Veja a nota de estudo em 1Co 7:32.
====

[[v46-7-34]]

^<<v46-7-34,34>>^ e está dividido. Além disso, a mulher não casada e a virgem se preocupam com as coisas do Senhor, para serem santas tanto no corpo como no espírito. No entanto, a mulher casada se preocupa com as coisas do mundo, em como pode agradar ao marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Digo isso para o seu próprio bem, não para lhes impor restrições, mas para induzi-los a fazer o que é apropriado e a servir constantemente ao Senhor, sem distração.

[TIP]
====
- *para lhes impor restrições*: Lit.: “para lançar um laço sobre vocês”. Em sentido literal, a expressão grega que aparece aqui pode se referir a capturar ou restringir os movimentos de um animal laçando-o ou amarrando uma corda em seu pescoço. Ela também era usada para se referir a restringir uma pessoa que estava presa. Neste contexto, a expressão foi usada em sentido figurado e passa a ideia de estabelecer regras para alguém ou de controlar o comportamento e as ações de uma pessoa. Ao dar conselhos sobre se era melhor se casar ou continuar solteiro (1Co 7:25-34), Paulo não queria tirar a liberdade dos cristãos em Corinto. Em vez disso, ele queria ajudá-los a servir “ao Senhor, sem distração”.
====

[[v46-7-36]]

^<<v46-7-36,36>>^ Mas, se alguém, por ficar sem se casar, acha que está se comportando de modo impróprio, e se ele estiver além da flor da juventude, então isto é o que deve ocorrer: que ele faça o que quer; ele não peca. Que se casem.

[TIP]
====
- *por ficar sem se casar*: Ou: “com relação à sua virgindade”. A palavra grega que aparece aqui, parthénos, é muitas vezes traduzida como “virgem”. Algumas Bíblias usam nesta parte do versículo traduções como “com relação à sua virgem [ou: “noiva; filha”]”. Mas, neste contexto, fica claro que a palavra não se refere a outra pessoa virgem ou que não está casada, mas à virgindade do próprio cristão. Neste versículo, Paulo está continuando com o raciocínio dos versículos anteriores, em que ele estava incentivando os cristãos a ficarem solteiros.
- *além da flor da juventude*: Esta expressão é a tradução da palavra grega hypérakmos, que é formada por duas palavras: hypér, que significa “além”, e akmé, que significa “plena floração de uma flor” ou “ponto mais alto”. A palavra akmé era usada com frequência para se referir ao desabrochar das flores. Aqui, a “flor da juventude” pelo visto se refere à época da vida em que o jovem se desenvolve fisicamente e se torna capaz de ter filhos. Mas essas mudanças físicas muitas vezes são acompanhadas por fortes impulsos e emoções, que comprometem sua capacidade de tomar boas decisões. Quando Paulo falou as palavras deste versículo, ele não estava incentivando o casamento, já que no contexto ele considera as vantagens de permanecer solteiro. As palavras de Paulo aqui indicam que, no caso de um jovem que está maduro em sentido físico, mas que ainda está se desenvolvendo em sentido emocional e espiritual, o foco dele não deveria ser se casar rapidamente, mas sim ter mais autodomínio.
====

[[v46-7-37]]

^<<v46-7-37,37>>^ No entanto, se alguém estiver resolvido no coração e não sentir necessidade, mas tiver controle^&#42;1^ sobre a sua própria vontade e tiver tomado no seu próprio coração a decisão de não se casar, ele fará bem.

[NOTE]
====
. Lit.: “autoridade”.
====

[TIP]
====
- *não se casar*: Ou: “manter a sua própria virgindade”. Como mostra a nota de estudo em 1Co 7:36, neste contexto a palavra grega parthénos não se refere a outra pessoa virgem ou que não está casada, mas à virgindade do próprio cristão. Faz sentido entender que esse é o significado de parthénos aqui, já que Paulo estava considerando as vantagens que os cristãos teriam se decidissem permanecer sem se casar. — 1Co 7:32-35.
====

[[v46-7-38]]

^<<v46-7-38,38>>^ Assim também, aquele que se casa faz bem, mas aquele que não se casar fará melhor.

[TIP]
====
- *se casa*: Ou: “dá a sua virgindade em casamento”. — Veja as notas de estudo em 1Co 7:36, 37.
====

[[v46-7-39]]

^<<v46-7-39,39>>^ A esposa está amarrada ao marido durante todo o tempo em que ele estiver vivo. Mas, se o seu marido adormecer na morte, ela estará livre para se casar com quem quiser, somente no Senhor.

[TIP]
====
- *somente no Senhor*: Ou: “somente se ele estiver em união com o Senhor; somente com alguém que acredita no Senhor”. Ou seja, somente com alguém que também é cristão. Esta orientação inspirada se aplica a todos os seguidores de Cristo. O fato de que Paulo usou aqui a expressão “no Senhor” para se referir a alguém que é cristão fica claro pelo uso que ele faz dela em outros lugares. Em Ro 16:8-11, ele usa essa expressão para se referir a seus companheiros de fé e, em Col 4:7, ele a usa junto com palavras como “amado irmão”, “fiel ministro” e “coescravo”. Os cristãos judeus sabiam que, de acordo com a Lei de Deus a Israel, os israelitas não deviam ‘formar nenhuma aliança matrimonial’ com as pessoas das nações vizinhas, que não adoravam a Jeová. Os israelitas foram alertados por Jeová: “Eles desviarão os seus filhos de me seguir, e estes servirão a outros deuses.” (De 7:3, 4) Para os cristãos, a orientação de casar “somente no Senhor” significa casar somente com alguém que também adora a Jeová e segue a Cristo.
- *Senhor*: Neste contexto, o título “Senhor” pode se referir tanto a Jesus Cristo como a Jeová Deus.
====

[[v46-7-40]]

^<<v46-7-40,40>>^ Na minha opinião, porém, ela será mais feliz se permanecer como está; e estou certo de que tenho também o espírito de Deus.

[TIP]
====
- *Na minha opinião*: Veja a nota de estudo em 1Co 7:25.
====

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]