include::./index.adoc[]

[[v46-9-0]]
=== A Primeira aos Coríntios, 9
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* E. PENSAR NO BEM-ESTAR ESPIRITUAL DE OUTROS CRISTÃOS (8:1–11:1)
* 1. Sobre os alimentos oferecidos a ídolos (8:1-13)
* O amor é superior ao conhecimento (8:1-3)
* Não fazer outros tropeçar na questão de comer alimentos oferecidos a ídolos (8:4-13)
* 2. O exemplo de Paulo como apóstolo (9:1-27)
* Ministros cristãos têm direito de receber ajuda material (9:1-18)
* Tornar-se todas as coisas para pessoas de todo tipo (9:19-23)
* É necessário ter autodomínio na corrida pela vida (9:24-27)
* 3. Exemplos da história de Israel que servem de alerta (10:1-22)
* Os israelitas no deserto (10:1-5)
* Avisos contra ganância, idolatria, imoralidade e outras coisas más (10:6-11)
* Ninguém é tentado além do que pode suportar (10:12, 13)
* “Fujam da idolatria”; rejeitem a mesa de demônios (10:14-22)
* 4. Ter consideração pelos outros ao usar a liberdade cristã (10:23–11:1)
* “Tudo é permitido, mas nem tudo edifica” (10:23, 24)
* Levar em conta a consciência de outros (10:25-30)
* Fazer todas as coisas para a glória de Deus; imitar Paulo e Cristo (10:31–11:1)
****

[[v46-9-1]]

^<<v46-9-1,1>>^ Não sou livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Não são vocês a minha obra no Senhor?

[TIP]
====
- *apóstolo*: Veja a nota de estudo em Ro 1:1.
====

[[v46-9-2]]

^<<v46-9-2,2>>^ Mesmo que eu não seja apóstolo para os outros, com toda a certeza sou para vocês! Pois vocês são o selo que confirma o meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Minha defesa perante os que me questionam é a seguinte:

[[v46-9-4]]

^<<v46-9-4,4>>^ Será que não temos o direito de^&#42;1^ comer e beber?

[NOTE]
====
. Lit.: “não temos autoridade para”.
====

[[v46-9-5]]

^<<v46-9-5,5>>^ Será que não temos o direito de ser acompanhados por uma esposa crente, assim como os outros apóstolos, os irmãos do Senhor e Cefas?

[TIP]
====
- *uma esposa crente*: Ou: “uma irmã como esposa”. Ou seja, uma esposa cristã. Dentro da congregação, as mulheres são vistas como irmãs em sentido espiritual. — Ro 16:1; 1Co 7:15; Tg 2:15.
- *Cefas*: Este era um dos nomes do apóstolo Pedro. (Veja as notas de estudo em Mt 10:2; 1Co 1:12.) Aqui, Paulo diz que Cefas era casado. De acordo com os Evangelhos, a sogra de Cefas morava com ele na casa que ele dividia com seu irmão, André. (Mt 8:14; Mr 1:29-31; veja a nota de estudo em Lu 4:38.) Este versículo mostra que a esposa de Cefas às vezes o acompanhava em seu ministério. As esposas dos outros apóstolos e dos meios-irmãos de Jesus também acompanhavam seus maridos.
====

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que só eu e Barnabé não temos o direito de deixar de trabalhar para o nosso sustento?

[[v46-9-7]]

^<<v46-9-7,7>>^ Que soldado serve com os seus próprios recursos? Quem planta um vinhedo e não come do seu fruto? Ou quem pastoreia um rebanho e não toma do leite do rebanho?

[TIP]
====
- *com os seus próprios recursos*: Ou: “às suas próprias custas”. Lit.: “com os seus próprios salários”. A palavra grega traduzida aqui como “recursos” era usada para se referir às provisões materiais dadas aos que estavam prestando serviço militar. (Veja a nota de estudo em Lu 3:14.) Neste contexto, a palavra foi usada em sentido figurado e indica que, por trabalharem com zelo, os “soldados” cristãos merecem receber uma pequena ajuda material.
====

[[v46-9-8]]

^<<v46-9-8,8>>^ Será que estou dizendo essas coisas de um ponto de vista humano? Ou a Lei não diz também essas coisas?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois está escrito na Lei de Moisés: “Não amordace o touro quando ele debulha o grão.” Será que é com touros que Deus está preocupado?

[TIP]
====
- *Será que é com touros que Deus está preocupado?*: Paulo usa esta pergunta retórica para dar força a seu argumento. Ele tinha acabado de citar o mandamento da Lei mosaica que diz: “Não amordace o touro quando ele debulha o grão.” (De 25:4) Assim como o touro merece comer dos grãos que ele debulha, o cristão que trabalha compartilhando coisas espirituais com outros merece receber apoio material. Em 1Co 9:10, Paulo diz que o mandamento registrado em De 25:4 na verdade “foi escrito por nossa causa”. As palavras de Paulo não querem dizer que os cristãos podem ignorar o princípio bíblico de ter consideração pelos animais. Em vez disso, o argumento é que, se Deus espera que se tenha consideração por animais que estão trabalhando, isso vale ainda mais para humanos, especialmente para os que trabalham duro no serviço de Deus.
====

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou não é de fato por nossa causa que ele diz isso? Realmente, isso foi escrito por nossa causa, porque o homem que ara e o homem que debulha devem fazer essas coisas na esperança de receber uma parte.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós semeamos entre vocês coisas espirituais, seria demais colhermos de vocês apoio material?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros homens têm esse direito sobre vocês, será que nós não temos esse direito ainda muito mais? Contudo, não fizemos uso desse direito,^&#42;1^ mas estamos suportando tudo para não criar nenhum obstáculo às boas novas a respeito do Cristo.

[NOTE]
====
. Lit.: “dessa autoridade”.
====

[[v46-9-13]]

^<<v46-9-13,13>>^ Vocês não sabem que os homens que cumprem deveres sagrados comem das coisas do templo, e que aqueles que servem regularmente diante do altar recebem uma parte do que é oferecido no altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Do mesmo modo, o Senhor ordenou que aqueles que proclamam as boas novas vivam das boas novas.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas eu não tenho feito uso de nem uma única dessas coisas. De fato, não escrevi para que se fizesse isso no meu caso, pois seria melhor morrer do que . . . Ninguém vai tirar o meu motivo de orgulho!

[[v46-9-16]]

^<<v46-9-16,16>>^ Ora, se eu estou declarando as boas novas, isso não é motivo para me orgulhar, pois me é imposta a necessidade. Realmente, ai de mim se eu não declarar as boas novas!

[TIP]
====
- *a necessidade*: Ou: “a obrigação”. Paulo tinha recebido a designação de pregar e, por isso, sentia que realizar esse trabalho era sua obrigação. (At 9:15-17; Gál 1:15, 16) Neste mesmo versículo, Paulo diz: Ai de mim se eu não declarar as boas novas! Ele usa a palavra grega traduzida aqui como “ai” para expressar a aflição que ele sentiria se não cumprisse sua obrigação. A vida de Paulo dependia da lealdade dele nessa questão. (Compare com Ez 33:7-9, 18; At 20:26.) Paulo talvez estivesse pensando nas palavras de Jeremias e de Amós. (Je 20:9; Am 3:8) De qualquer forma, a Bíblia mostra que Paulo pregava por amor, e não simplesmente por obrigação. — 2Co 5:14, 20; Fil 1:16.
====

[[v46-9-17]]

^<<v46-9-17,17>>^ Se eu faço isso espontaneamente, tenho uma recompensa; mas, mesmo se o fizer contra a minha vontade, ainda assim estou incumbido de uma responsabilidade.^&#42;1^

[NOTE]
====
. Ou: “administração”.
====

[[v46-9-18]]

^<<v46-9-18,18>>^ Então, qual é a minha recompensa? É que, quando eu declarar as boas novas, eu ofereça as boas novas sem custo, para não abusar da minha autoridade^&#42;1^ no que se refere às boas novas.

[NOTE]
====
. Ou: “dos meus direitos”.
====

[[v46-9-19]]

^<<v46-9-19,19>>^ Pois, embora eu seja livre com relação a todos, eu me fiz escravo de todos, para ganhar o maior número possível de pessoas.

[[v46-9-20]]

^<<v46-9-20,20>>^ Para os judeus me tornei como judeu, para ganhar os judeus; para os debaixo de lei me tornei como debaixo de lei — embora eu mesmo não esteja debaixo de lei —, para ganhar os debaixo de lei.

[TIP]
====
- *Para os judeus me tornei como judeu*: O fato de Paulo ter sido criado como judeu e estar disposto a ‘fazer tudo pela causa das boas novas’ contribuía para que ele conseguisse ajudar judeus humildes a aceitarem Jesus como Messias. (1Co 9:23) Por exemplo, “por causa dos judeus”, Paulo circuncidou Timóteo. Paulo decidiu fazer isso — e Timóteo concordou — apesar de a circuncisão não ser necessária para os cristãos. — At 16:1-3.
====

[[v46-9-21]]

^<<v46-9-21,21>>^ Para os sem lei me tornei como sem lei — embora eu não esteja sem lei para com Deus, mas esteja debaixo de lei para com Cristo —, para ganhar os sem lei.

[TIP]
====
- *Para os sem lei me tornei como sem lei*: A expressão “os sem lei” se refere aos não judeus, que não estavam debaixo da Lei mosaica. Quando Paulo deu testemunho a um grupo de gregos em Atenas, ele levou em conta a maneira de pensar deles e lhes apresentou o Deus que eles ainda não conheciam. Nessa ocasião, Paulo até mesmo citou alguns poetas gregos. — At 17:22-34.
====

[[v46-9-22]]

^<<v46-9-22,22>>^ Para os fracos me tornei fraco, para ganhar os fracos. Eu me tornei todas as coisas para pessoas de todo tipo, para de todos os modos possíveis salvar alguns.

[TIP]
====
- *Para os fracos me tornei fraco*: Embora Paulo falasse de forma bem direta, ele levava em conta a consciência mais sensível de alguns cristãos judeus e não judeus. Dessa forma, ele ‘se tornou fraco’ para os fracos. — Ro 14:1, 13, 19; 15:1.
====

[[v46-9-23]]

^<<v46-9-23,23>>^ Mas faço tudo pela causa das boas novas, para compartilhá-las com outros.

[TIP]
====
- *faço tudo pela causa das boas novas*: Com estas palavras, Paulo resume o esforço que ele fazia para adaptar sua pregação e tocar o coração de pessoas de todo tipo. (1Co 9:19-23) Mas ele nunca pensou em ‘adulterar a palavra de Deus’ ou em usar de “astúcia”, ou seja, de engano, para tentar fazer discípulos. — 2Co 4:2.
====

[[v46-9-24]]

^<<v46-9-24,24>>^ Vocês não sabem que numa corrida todos os corredores correm, mas apenas um recebe o prêmio? Corram de tal modo que consigam ganhá-lo.

[TIP]
====
- *corrida*: A palavra grega que aparece aqui é stádion. Essa palavra pode se referir a um local onde eram realizadas corridas a pé e outros eventos, a uma medida de distância ou à própria corrida a pé, como é o caso neste versículo. O comprimento de um stádion grego podia variar de uma região para outra. Em Corinto, o stádion tinha cerca de 165 metros. Já um stádion romano equivalia a uns 185 metros. — Veja o Apêndice B14-A.
- *os corredores*: As competições atléticas eram uma parte importante da cultura grega. Por isso, Paulo usou muitas vezes essas competições em suas ilustrações. (1Co 9:24-27; Fil 3:14; 2Ti 2:5; 4:7, 8; He 12:1, 2) Os cristãos coríntios conheciam bem as provas de atletismo que faziam parte dos Jogos Ístmicos, realizados perto de Corinto. Esses jogos eram realizados de dois em dois anos. Tudo indica que Paulo estava em Corinto durante os jogos do ano 51 d.C. Os Jogos Ístmicos só perdiam em importância para os Jogos Olímpicos, realizados na cidade de Olímpia, na Grécia. Nos jogos gregos, havia corridas de diferentes distâncias. Em suas ilustrações, Paulo fez referência a corredores e lutadores de boxe para ensinar o valor do autodomínio, da eficiência e da perseverança. — 1Co 9:26.
- *apenas um recebe o prêmio*: Nas competições atléticas da Grécia antiga, o prêmio para o vencedor era uma coroa, geralmente feita de folhas. Receber essa coroa era uma grande honra. Tudo indica que a coroa ficava exposta no estádio para que os competidores pudessem ver o prêmio. Paulo incentivou os cristãos ungidos a se esforçarem para ganhar algo muito melhor do que uma coroa que perece, ou seja, que com o tempo se decompõe. Eles deviam buscar a coroa imperecível da vida imortal. Para vencer, o cristão precisa manter seus olhos fixos no prêmio. — 1Co 9:25; 15:53; 1Pe 1:3, 4; 5:4.
====

[[v46-9-25]]

^<<v46-9-25,25>>^ Todos os que participam numa competição exercem autodomínio em todas as coisas. Claro, eles fazem isso para receber uma coroa perecível, mas nós, uma que não perece.

[TIP]
====
- *Todos os que participam numa competição exercem*: Ou: “Todo atleta exerce”. O verbo grego traduzido aqui como “participam numa competição” está relacionado com um substantivo grego que muitas vezes era usado para se referir a competições de atletismo. Em He 12:1, esse substantivo foi usado para descrever a “corrida” cristã para ganhar a vida. E em outros versículos ele foi usado com o sentido mais geral de “luta”. (Fil 1:30; Col 2:1; 1Ti 6:12; 2Ti 4:7) O verbo grego usado aqui também foi traduzido como ‘esforçar-se vigorosamente’ (Lu 13:24), ‘esforçar-se’ (Col 1:29; 1Ti 4:10), ‘[orar] com fervor’ (Col 4:12) e ‘travar [a luta]’ (1Ti 6:12). — Veja a nota de estudo em Lu 13:24.
- *exercem autodomínio*: Para se preparar para uma competição, os atletas precisavam ter autocontrole. Muitos deles mudavam a sua dieta, e alguns deixavam de consumir vinho. O historiador Pausânias escreveu que o período de treinamento para os Jogos Olímpicos era de dez meses, e acredita-se que o período de treinamento para outros jogos importantes fosse semelhante.
====

[[v46-9-26]]

^<<v46-9-26,26>>^ Portanto, não corro sem rumo; direciono os meus golpes de modo a não golpear o ar;

[TIP]
====
- *direciono os meus golpes*: Aqui, Paulo se compara a um boxeador numa luta. Um boxeador bem treinado tenta fazer cada soco valer. Ele não desperdiça energia golpeando o ar. De modo parecido, os cristãos precisam direcionar bem seus esforços, tendo sempre em mente o prêmio da vida eterna. (Mt 7:24, 25; Tg 1:22) Eles lutam para superar qualquer desafio ou obstáculo que surja em seu caminho, incluindo suas próprias imperfeições. — 1Co 9:27; 1Ti 6:12.
====

[[v46-9-27]]

^<<v46-9-27,27>>^ surro o meu corpo e o conduzo como escravo, para que, depois de ter pregado a outros, eu mesmo não venha a ser de algum modo reprovado.^&#42;1^

[NOTE]
====
. Ou: “desqualificado”.
====

[TIP]
====
- *surro*: Ou: “puno; disciplino severamente”. A palavra grega traduzida aqui como “surro” significa literalmente “atingir debaixo [do olho]”. Os cristãos precisam disciplinar a si mesmos. Existem situações em que mostrar o autodomínio necessário pode ser tão doloroso quanto um soco no olho. Mas ter esse grau de autodisciplina ajuda o cristão a não ‘ser reprovado’ por Deus. — Compare com a nota de estudo em Lu 18:5.
====

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]