include::./index.adoc[]

[[v46-6-0]]
=== A Primeira aos Coríntios, 6
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. A PUREZA MORAL DA CONGREGAÇÃO DEVE SER PRESERVADA (5:1–6:20)
* 1. Como lidar com um caso de imoralidade sexual (5:1-13)
* A congregação não deve tolerar imoralidade sexual (5:1-5)
* “Um pouco de fermento leveda a massa toda” (5:6-8)
* Parar de ter convivência com os maus (5:9-13)
* 2. Melhor ser prejudicado do que levar um irmão a juízo perante descrentes (6:1-8)
* 3. Avisos contra impureza espiritual e moral (6:9-20)
* Os que não herdarão o Reino (6:9-11)
* “Os seus corpos são membros de Cristo”, então “fujam da imoralidade sexual!” (6:12-20)
****

[[v46-6-1]]

^<<v46-6-1,1>>^ Quando algum de vocês tem uma questão contra outro, como se atreve a ir a juízo perante os injustos, e não perante os santos?

[TIP]
====
- *ir a juízo perante os injustos*: Os juízes dos tribunais humanos não eram guiados pela lei de Deus, e a consciência deles não tinha sido treinada pelo estudo da Palavra de Deus. Paulo se referiu a eles como “injustos”, talvez porque muitos juízes daquela época fossem corruptos. Se um cristão recorresse a esses juízes para resolver um assunto com um irmão, seria como se ele estivesse dizendo que os anciãos da congregação não eram sábios o suficiente para julgar as “questões desta vida”. (1Co 6:3-5) Mas, na verdade, os cristãos ungidos iriam governar com o Senhor Jesus Cristo no céu e julgar não só humanos, mas até mesmo anjos. (Veja a nota de estudo em 1Co 6:3.) Paulo diz que seria muito melhor que um cristão aceitasse “sofrer a injustiça”, ou seja, ter algum prejuízo pessoal, do que causar divisão na congregação e tornar públicos esses desentendimentos. — 1Co 6:7, 8.
====

[[v46-6-2]]

^<<v46-6-2,2>>^ Ou vocês não sabem que os santos julgarão o mundo? E, se o mundo será julgado por vocês, será que vocês não são capazes de julgar questões de tão pouca importância?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabem que nós julgaremos anjos? Então por que não questões desta vida?

[TIP]
====
- *julgaremos anjos*: Aqui, Paulo foi inspirado a escrever sobre algo que aconteceria muito depois dos dias dele, no tempo em que os cristãos ungidos já tivessem sido ressuscitados para reinar com Cristo. (1Co 4:8; Ap 20:6) Os cristãos ungidos ajudarão Jesus a executar os julgamentos justos de Jeová sobre as pessoas más. (1Co 6:2; Ap 17:14) Pode ser que eles também ajudem a executar os julgamentos de Jeová sobre os anjos maus, que se rebelaram contra ele. — Ju 6.
====

[[v46-6-4]]

^<<v46-6-4,4>>^ Se vocês, então, têm questões desta vida para serem julgadas, por que vocês escolhem como juízes a homens que são vistos com desaprovação pela congregação?

[[v46-6-5]]

^<<v46-6-5,5>>^ Digo isso para induzi-los à vergonha. Será que não há nenhum homem sábio entre vocês que possa julgar entre seus irmãos?

[[v46-6-6]]

^<<v46-6-6,6>>^ Em vez disso, irmão vai a juízo contra irmão, e isso perante descrentes!

[[v46-6-7]]

^<<v46-6-7,7>>^ Realmente, já é uma derrota para vocês quando movem ações judiciais uns contra os outros. Não seria melhor sofrer a injustiça? Não seria melhor ficar com o prejuízo?^&#42;1^

[NOTE]
====
. Ou: “ser defraudado”.
====

[[v46-6-8]]

^<<v46-6-8,8>>^ Pelo contrário, vocês fazem injustiça e causam prejuízo,^&#42;1^ e isso a seus irmãos!

[NOTE]
====
. Ou: “e defraudam”.
====

[[v46-6-9]]

^<<v46-6-9,9>>^ Ou será que vocês não sabem que os injustos não herdarão o Reino de Deus? Não se enganem.^&#42;1^ Os que praticam imoralidade sexual, os idólatras, os adúlteros, os homens que se submetem a atos homossexuais, os homens que praticam o homossexualismo,

[NOTE]
====
. Ou: “Não se deixem enganar.”
====

[TIP]
====
- *Os que praticam imoralidade sexual*: Veja a nota de estudo em 1Co 5:9.
- *os adúlteros*: Ou seja, os que cometem adultério; os que traem o marido ou a esposa. De acordo com a Bíblia, adultério se refere a qualquer ato intencional de “imoralidade sexual” (em grego, porneía) que uma pessoa casada comete com alguém que não é sua esposa ou seu marido. — Veja o Glossário, “Adultério”; e as notas de estudo em Mt 5:27, 32; Mr 10:11.
- *os homens que se submetem a atos homossexuais, os homens que praticam o homossexualismo*: Aqui, o texto grego usa duas palavras diferentes. A primeira é malakós, que tem o sentido básico de “macio”. (Compare com a nota de rodapé em Mt 11:8.) Mas, neste contexto, pelo visto ela se refere a homens que assumem o papel passivo, semelhante ao de uma mulher, no relacionamento homossexual. Por isso, malakós foi traduzida aqui como os homens que se submetem a atos homossexuais. A segunda palavra, arsenokoítes, também aparece em 1Ti 1:10 e significa literalmente “homens que se deitam com homens”. Tudo indica que ela se refere a homens que assumem o papel ativo no relacionamento homossexual. Assim, arsenokoítes foi traduzida aqui como os homens que praticam o homossexualismo. Outra opção de tradução seria “os homens que têm relações sexuais com homens”. Por mencionar de modo específico tanto o papel passivo como o ativo, Paulo deixa claro que Deus desaprova todos os atos homossexuais.
====

[[v46-6-10]]

^<<v46-6-10,10>>^ os ladrões, os gananciosos, os beberrões, os injuriadores e os extorsores não herdarão o Reino de Deus.

[TIP]
====
- *os injuriadores*: Ou: “os que agridem com palavras”. — Veja a nota de estudo em 1Co 5:11.
- *os extorsores*: Ou: “os trapaceiros; os assaltantes”. Extorsão é o ato de tirar algo de uma pessoa ou de obrigá-la a fazer algo, por meio de ameaças, uso de força ou abuso de autoridade. O sentido básico da palavra grega para “extorsor” (hárpax) é “alguém que tira algo de outro à força”. (Kingdom Interlinear) Em Mt 7:15, essa palavra foi traduzida como “vorazes”. No versículo seguinte (1Co 6:11), Paulo diz que alguns cristãos de Corinto tinham feito coisas desse tipo, mas que eles tinham sido lavados e agora estavam puros. — Compare com a nota de estudo em Lu 18:11.
====

[[v46-6-11]]

^<<v46-6-11,11>>^ E, no entanto, isso é o que alguns de vocês foram. Mas vocês foram lavados; vocês foram santificados; vocês foram declarados justos no nome do Senhor Jesus Cristo e com o espírito do nosso Deus.

[TIP]
====
- *vocês foram santificados*: Ou: “vocês foram tornados santos; vocês foram colocados à parte”. Ou seja, colocados à parte para prestar serviço sagrado a Deus. Os cristãos em Corinto que abandonaram os pecados mencionados nos versículos anteriores e exerceram fé em Jesus foram santificados pelo “sangue do Cristo”. (He 9:13, 14; 1Co 1:2; 6:9, 10) Assim, eles podiam prestar serviço sagrado a Deus com uma consciência limpa.
====

[[v46-6-12]]

^<<v46-6-12,12>>^ Tudo me é permitido, mas nem tudo é vantajoso. Tudo me é permitido, mas não me deixarei ser controlado^&#42;1^ por nada.

[NOTE]
====
. Ou: “colocado debaixo de autoridade”.
====

[TIP]
====
- *permitido*: Ou: “lícito”. É lógico que Paulo não queria dizer que era permitido fazer coisas que Deus condena. (At 15:28, 29) Em vez disso, ele estava simplesmente reconhecendo que os cristãos não tinham a obrigação de seguir as muitas ordens da Lei mosaica e, por isso, eles muitas vezes teriam que tomar decisões sem ter uma lei específica das Escrituras para guiá-los. Nesses casos, eles teriam que levar em conta não só a consciência deles, mas também a de outros. Paulo deu como exemplo a questão dos alimentos. (1Co 6:13) Alguns cristãos, que tinham a consciência mais sensível, não achavam correto comer determinados alimentos. (1Co 10:23, 25-33) Por isso, mesmo sabendo que esses alimentos eram permitidos para os cristãos, Paulo disse que preferia abrir mão de seu direito de comê-los do que fazer outros tropeçar ou ferir a consciência deles. — 1Co 8:12, 13.
====

[[v46-6-13]]

^<<v46-6-13,13>>^ O alimento é para o estômago, e o estômago para o alimento; mas Deus reduzirá ambos a nada. O corpo não é para imoralidade sexual, mas para o Senhor; e o Senhor é para o corpo.

[TIP]
====
- *imoralidade sexual*: A palavra grega que aparece aqui, porneía, é um termo genérico usado para se referir a todos os tipos de atividade sexual que a Bíblia condena. Nesta carta inspirada de Paulo aos coríntios, ele usa essa e outras palavras relacionadas várias vezes. — Veja as notas de estudo em 1Co 5:1, 9; 7:2.
====

[[v46-6-14]]

^<<v46-6-14,14>>^ Mas Deus levantou o Senhor e também levantará a nós da morte, por meio do seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Vocês não sabem que os seus corpos são membros de Cristo? Deveria eu, então, tirar os membros do Cristo e uni-los a uma prostituta? De modo algum!

[TIP]
====
- *prostituta*: Veja o Glossário.
====

[[v46-6-16]]

^<<v46-6-16,16>>^ Vocês não sabem que aquele que se une a uma prostituta é um só corpo com ela? Pois “os dois”, diz ele, “serão uma só carne”.

[TIP]
====
- *diz ele*: Ou seja, Deus. Paulo está citando as palavras de Deus no relato da criação em Gên 2:24. A palavra grega que aparece aqui também poderia ser traduzida como “diz ela”, fazendo referência à Escritura.
- *uma só carne*: Veja a nota de estudo em Mt 19:5.
====

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas quem está unido ao Senhor é um só em espírito com ele.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fujam da imoralidade sexual! Qualquer outro pecado que o homem possa cometer é fora de seu corpo, mas quem pratica a imoralidade sexual peca contra o seu próprio corpo.

[TIP]
====
- *Fujam da imoralidade sexual!*: O verbo grego feúgo significa “fugir; correr de”. Aqui, Paulo usa esse verbo em sentido figurado para mostrar como os cristãos em Corinto deviam agir em relação à imoralidade sexual. Alguns sugerem que ele estava fazendo referência ao que aconteceu com José, que fugiu sem hesitar da esposa de Potifar. O mesmo verbo usado por Paulo neste versículo foi usado na Septuaginta no relato sobre a fuga de José. (Gên 39:12-18) No texto grego original de 1Co 6:18, esse verbo está no presente (lit.: “estejam fugindo”), passando a ideia de uma ação contínua e repetida. — Kingdom Interlinear.
- *Qualquer outro pecado que o homem possa cometer é fora de seu corpo*: Nos versículos anteriores, Paulo deixa claro que os cristãos devem estar em união com Cristo Jesus, seu Senhor e cabeça. (1Co 6:13-15) A pessoa que se envolve em imoralidade sexual comete um pecado que a torna “uma só carne” com outra pessoa. (1Co 6:16) Em certo sentido, o cristão que comete imoralidade sexual rompe sua união com Cristo e faz com que seu corpo se torne “um” com a pessoa com quem pecou. Pelo visto, todos os outros pecados são considerados aqui como ‘fora do corpo’ porque nenhum outro pecado é capaz de separar a pessoa de Cristo e tornar o corpo dela “um” com o de outra pessoa. Um cristão que pratica imoralidade sexual peca contra o seu próprio corpo, usando seus órgãos reprodutivos para um objetivo imoral.
====

[[v46-6-19]]

^<<v46-6-19,19>>^ Vocês não sabem que o seu corpo é o templo do espírito santo, que está em vocês e que lhes foi dado por Deus? Além disso, vocês não pertencem a si mesmos,

[TIP]
====
- *o seu corpo é o templo*: Os cristãos ungidos, como grupo, têm um lugar especial no propósito de Jeová. O pronome grego traduzido aqui como “seu” está no plural e, por isso, não se refere ao corpo de uma só pessoa da congregação. (1Co 10:17) A Bíblia com frequência usa a palavra “templo” em sentido figurado, às vezes se referindo a pessoas. Em Jo 2:19, o próprio Jesus se comparou a um templo. Além disso, as Escrituras diziam que o Messias se tornaria “a principal pedra angular” de um templo espiritual. (Sal 118:22; Is 28:16, 17; At 4:10, 11) Paulo e Pedro fizeram comparações parecidas ao falar de Jesus e de seus seguidores em 1Co 3:16, 17; Ef 2:20-22 e 1Pe 2:6, 7.
====

[[v46-6-20]]

^<<v46-6-20,20>>^ pois foram comprados por um preço. Portanto, glorifiquem a Deus no corpo de vocês.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]