include::./index.adoc[]

[[v46-13-0]]
=== A Primeira aos Coríntios, 13
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* F. INSTRUÇÕES PARA QUE A CONGREGAÇÃO ADORE A DEUS DE MODO ORDEIRO (11:2–14:40)
* Respeito pelo princípio da chefia; cobrir a cabeça (11:2-16)
* Mostrar respeito pela Ceia do Senhor (11:17-34)
* Dons do espírito (12:1-11)
* Um corpo, muitos membros (12:12-31a)
* Amor: um caminho superior (12:31b–13:13)
* Dons de profecia e de falar em línguas (14:1-25)
* Manter a ordem nas reuniões cristãs (14:26-40)
****

[[v46-13-1]]

^<<v46-13-1,1>>^ Se eu falar em línguas de homens e de anjos, mas não tiver amor, sou um gongo que ressoa ou um címbalo que retine.

[TIP]
====
- *um gongo que ressoa ou um címbalo que retine*: Tanto um gongo ressoando como um címbalo retinindo emitem um som alto e estridente. Com essa comparação, Paulo mostra que um dom do espírito (como falar em línguas) até podia chamar bastante atenção, mas, se o cristão que tivesse esse dom não tivesse amor pelos outros, ele seria como um objeto de latão que faz um barulho alto e desagradável. Esse tipo de som afastaria as pessoas, em vez de atraí-las.
====

[[v46-13-2]]

^<<v46-13-2,2>>^ E se eu tiver o dom de profecia e entender todos os segredos sagrados e todo o conhecimento, e se eu tiver toda a fé, a ponto de mover montanhas, mas não tiver amor, nada sou.^&#42;1^

[NOTE]
====
. Ou: “não sirvo para nada”.
====

[TIP]
====
- *mover montanhas*: Ou: “transplantar montanhas”. Aqui, Paulo pelo visto está usando uma figura de linguagem antiga que passa a ideia de “tornar possível o que parece impossível”. — Compare com Mr 11:23, onde uma expressão parecida foi usada para falar da fé.
====

[[v46-13-3]]

^<<v46-13-3,3>>^ E se eu der todos os meus bens para alimentar outros, e se eu entregar o meu corpo para me gabar, mas não tiver amor, de nada me adianta.

[TIP]
====
- *para me gabar*: Neste contexto, o verbo grego kaukháomai (“gabar-se”) passa a ideia de ter orgulho egoísta. Aqui, Paulo fala qual seria o resultado se a motivação dele fosse esse tipo de orgulho em vez de o amor. Ele diz que, mesmo que ele desse tudo o que ele tinha para alimentar outros ou até morresse como mártir para dar testemunho da verdade, isso não adiantaria nada. (Pr 25:27b) Alguns manuscritos usam um verbo grego que significa “queimar” (em vez do verbo “gabar-se”), e existem Bíblias que seguem esses manuscritos. Mas os manuscritos mais confiáveis usam uma palavra que significa “gabar-se”.
====

[[v46-13-4]]

^<<v46-13-4,4>>^ O amor é paciente e bondoso. O amor não é ciumento. Não se gaba, não é orgulhoso,

[TIP]
====
- *amor*: Nesta famosa descrição que Paulo faz do amor, ele usa a mesma palavra grega (agápe) que aparece em 1Jo 4:8-10, onde João fala sobre “o amor de Deus”. João até mesmo diz, no versículo 8, que “Deus é amor”, o que significa que Jeová é o amor em pessoa. (Veja a nota de estudo em Jo 3:16.) O melhor modo de descrever o amor cristão é falar o que ele faz e o que ele não faz. O amor cristão é guiado por princípios e não é egoísta. O amor guiado por princípios pode envolver ou não carinho e afeto. Às vezes, alguém mostra esse amor simplesmente porque é a coisa certa a fazer. Por exemplo, um cristão mostra amor quando decide ‘não levar em conta o dano’, mesmo se ele está muito magoado. (1Co 13:5) Assim, o amor que Paulo descreve pode se referir tanto a um sentimento carinhoso que vem do coração como a um esforço consciente de aplicar os padrões justos de Deus. — Veja as notas de estudo em Mt 5:44; 22:37.
- *O amor é paciente*: Ou: “O amor é longânime”. O verbo grego traduzido aqui como “é paciente” poderia ser traduzido literalmente como “tem longura de espírito”. (Kingdom Interlinear) Tanto esse verbo como o substantivo relacionado passam a ideia de perseverar com tranquilidade e de demorar para ficar irado. A paciência é um aspecto do fruto do espírito santo de Deus (Gál 5:22) e um sinal que identifica os ministros de Deus. (2Co 6:4-6; Col 3:12; 1Te 5:14; veja o Apêndice A2.) Jeová e Jesus mostram constantemente essa qualidade ao lidar com os humanos. (Ro 2:4; 9:22; 1Ti 1:16; 1Pe 3:20; 2Pe 3:9, 15; veja a nota de estudo em Gál 5:22.) Por serem imitadores de Jesus e de Jeová, os cristãos precisam ter paciência com outros. — 1Co 11:1; Ef 5:1.
- *O amor é . . . bondoso*: O verbo grego khresteúomai, traduzido como “é . . . bondoso”, está relacionado com o substantivo khrestótes (“bondade”), que é um aspecto do “fruto do espírito”. (Gál 5:22) Mostrar bondade envolve se interessar pelo bem-estar de outros e ajudá-los no que eles precisam. A bondade também influencia o modo em que o cristão dá essa ajuda; ele age de modo gentil e amigável, mostrando consideração pela pessoa. — Col 3:12; Tit 3:4.
- *O amor não é ciumento*: O verbo grego zelóo passa a ideia de um sentimento forte que pode ser positivo ou negativo. Neste versículo, ele foi traduzido com a expressão “ser ciumento” porque se refere a um sentimento negativo que uma pessoa tem em relação a alguém que ela encara como rival ou a alguém que parece ter uma vantagem sobre ela. O substantivo relacionado zélos, muitas vezes traduzido como “ciúme”, está citado entre “as obras da carne” em Gál 5:19-21. Esse tipo de ciúme é egoísta e gera ódio, não amor. O cristão que tem o amor descrito por Paulo não sente ciúme indevido; ele confia e acredita nos outros, e sempre age pensando no bem deles. — 1Co 13:4-7; para uma explicação sobre o sentido positivo desse verbo grego, veja a nota de estudo em 2Co 11:2.
====

[[v46-13-5]]

^<<v46-13-5,5>>^ não se comporta indecentemente, não procura os seus próprios interesses, não se irrita com facilidade. Não leva em conta o dano.

[TIP]
====
- *não se comporta indecentemente*: Ou: “não é grosseiro; não age de modo inapropriado”. A palavra grega traduzida aqui como “se comporta indecentemente” pode incluir a ideia de agir de uma forma moralmente vergonhosa, de uma forma grosseira (sem boas maneiras) ou de uma forma que desonra outros.
- *Não leva em conta o dano*: O verbo grego logízomai, traduzido aqui como “leva em conta”, poderia também ser traduzido como “contabiliza”. Nos tempos antigos, ele era muito usado para se referir a cálculos numéricos, como, por exemplo, cálculos feitos na área da contabilidade. Ele também era usado com o sentido de “pensar em” ou “meditar em”. (Veja Fil 4:8, onde logízomai foi traduzido como “continuem a considerar”.) Quem ama não fica contabilizando “o dano [ou: “os erros”]”, como se estivesse fazendo um registro das palavras e ações que o magoaram para não esquecer delas. Ele não fica pensando sobre isso. Esse mesmo verbo grego também aparece em 2Co 5:19, onde fala que Jeová lida com seu povo “sem levar em conta contra eles os seus pecados”.
====

[[v46-13-6]]

^<<v46-13-6,6>>^ Não se alegra com a injustiça, mas se alegra com a verdade.

[[v46-13-7]]

^<<v46-13-7,7>>^ Suporta todas as coisas, acredita em todas as coisas, espera todas as coisas, persevera em todas as coisas.

[TIP]
====
- *Suporta todas as coisas*: Esta expressão pode ser traduzida literalmente como “todas as coisas está cobrindo”. (Kingdom Interlinear) De acordo com alguns estudiosos, o verbo que aparece aqui está relacionado com o substantivo grego para “teto”. Quem ama consegue como que cobrir as imperfeições e falhas de outros, se esforçando para não expor esses erros quando nenhum pecado grave está envolvido. O verbo grego também passa a ideia de “aguentar”.
====

[[v46-13-8]]

^<<v46-13-8,8>>^ O amor nunca acaba. Mas, quer haja dom de profecia, será eliminado; quer haja dom de línguas, cessará; quer haja dom de conhecimento, será eliminado.

[TIP]
====
- *O amor nunca acaba*: Ou: “O amor nunca falha”. O amor nunca vai acabar ou deixar de existir, porque “Deus é amor” e é o “Rei da eternidade”. (1Jo 4:16; 1Ti 1:17) Os humanos obedientes vão mostrar esse amor por toda a eternidade. Além disso, o amor nunca deixa a desejar. Ele está à altura de qualquer situação ou desafio. O amor sempre produz bons resultados. — 1Co 13:13.
- *dom de línguas*: Ou seja, o dom milagroso de falar em outras línguas. — Veja as notas de estudo em At 2:4; 1Co 12:10.
- *dom de conhecimento*: Ou seja, o dom de um conhecimento especial que o espírito santo dava a alguns dos primeiros cristãos. Não se sabe exatamente que tipo de conhecimento era esse, mas ele talvez incluísse o conhecimento de textos bíblicos. Naquela época, não era tão fácil conseguir cópias da Palavra de Deus. Assim, quando um rolo não estava disponível na congregação, pode ser que o cristão que tinha o dom de conhecimento e que já tinha lido aquele rolo fosse capaz de lembrar de um texto dele e de entender como aplicá-lo. Esse conhecimento especial, assim como os outros dons do espírito, era uma provisão temporária que ajudou a fortalecer a congregação cristã no seu início. — Veja a nota de estudo em 1Co 12:8.
- *será eliminado*: Lit.: “será tornado sem efeito”. Por meio do espírito santo, os apóstolos receberam de Deus habilidades milagrosas. E eles podiam passar esses poderes especiais a outras pessoas. Essas habilidades incluíam o dom de profecia, a capacidade milagrosa de falar diferentes línguas e o dom de conhecimento especial. Mas esses poderes milagrosos acabariam quando a congregação cristã saísse de sua fase inicial e atingisse a madureza. (1Co 13:9-11) Nesse ponto, os dons já teriam cumprido seu objetivo, que era mostrar que a congregação cristã tinha a aprovação e o apoio de Deus.
====

[[v46-13-9]]

^<<v46-13-9,9>>^ Pois temos conhecimento parcial e profetizamos parcialmente,

[TIP]
====
- *temos conhecimento parcial e profetizamos parcialmente*: De acordo com Paulo, esses dons milagrosos de conhecimento e de profecia eram incompletos. Parece que os cristãos que tinham o dom de profecia não conheciam todos os detalhes daquilo que prediziam e só podiam prever acontecimentos futuros de forma parcial. Um entendimento mais completo de profecias só estaria disponível no futuro, como Paulo indicou ao dizer: “Quando vier o que é completo.” (1Co 13:10; veja a nota de estudo.) Mas os primeiros cristãos tinham conhecimento suficiente naquela época para satisfazer suas necessidades espirituais. — Col 1:9, 10.
====

[[v46-13-10]]

^<<v46-13-10,10>>^ mas, quando vier o que é completo, será eliminado o que é parcial.

[TIP]
====
- *quando vier o que é completo*: Em muitos contextos, a palavra grega téleios (traduzida aqui como “o que é completo”) passa a ideia de algo plenamente desenvolvido, perfeito ou completo. Embora alguns cristãos do século 1 d.C. tivessem os dons milagrosos de “profecia” e de “conhecimento”, eles tinham um entendimento apenas parcial dos propósitos de Deus. (1Co 13:9) Neste versículo, a expressão “o que é completo” se refere a um entendimento pleno dos propósitos de Deus que estão registrados na Bíblia. Os cristãos vão ter entendimento completo quando as profecias bíblicas forem totalmente cumpridas e a vontade de Deus se realizar de forma plena.
====

[[v46-13-11]]

^<<v46-13-11,11>>^ Quando eu era criança, falava como criança, pensava como criança, raciocinava como criança; mas, agora que me tornei homem, eliminei as características de criança.

[TIP]
====
- *criança . . . homem*: Paulo usa o desenvolvimento de uma criança para ilustrar o progresso da congregação cristã. As crianças precisam de muita ajuda; já os adultos, não. De forma parecida, nos dias de Paulo, a congregação cristã ainda estava em seu começo e precisava da ajuda dos dons milagrosos, como os dons de profecia, de línguas e de conhecimento. Nessa época, esses dons eram necessários para não deixar dúvidas de que, a partir dali, o povo de Deus era a congregação cristã, e não mais a nação judaica. (He 2:3, 4) Mas Paulo deixa claro que, com o tempo, a congregação amadureceria, como que se tornando adulta, e não precisaria mais dos dons milagrosos.
====

[[v46-13-12]]

^<<v46-13-12,12>>^ Pois atualmente vemos contornos indefinidos por meio de um espelho de metal, mas então será face a face. Atualmente eu conheço em parte,^&#42;1^ mas então conhecerei de modo exato,^&#42;2^ assim como eu sou conhecido de modo exato.

[NOTE]
====
. Ou: “o conhecimento que eu tenho é incompleto (parcial)”.
. Ou: “pleno”.
====

[TIP]
====
- *contornos indefinidos*: Ou: “de forma indistinta”. A palavra grega que aparece aqui é muitas vezes usada para se referir a um enigma, mas ela também pode indicar algo indistinto, obscuro ou que não dá para ver em detalhes.
- *um espelho de metal*: Em geral, os espelhos dos tempos bíblicos eram feitos de metal polido — normalmente de bronze, mas às vezes de estanho, cobre, prata ou ouro. Por mais que os espelhos antigos fossem úteis, a imagem que eles refletiam não era clara. Por isso, ver o reflexo num espelho não se comparava com olhar diretamente para o objeto. Paulo usou essa ilustração para mostrar que os primeiros cristãos tinham um entendimento limitado de alguns assuntos espirituais, em especial de profecias que ainda estavam para se cumprir. Ainda não era o tempo de Deus para revelar certas coisas. Por isso, aqueles cristãos viam contornos indefinidos do propósito de Deus, como se eles estivessem vendo um reflexo embaçado. Paulo faz um contraste entre essa visão limitada e uma visão clara, face a face. Os cristãos vão ter um entendimento completo do propósito de Deus quando as profecias bíblicas se cumprirem plenamente.
- *assim como eu sou conhecido de modo exato*: Ou seja, conhecido de modo exato por Deus. Paulo sabia que Deus o conhecia muito mais do que ele conhecia a Deus. Mas, sobre conhecer a Jeová, Paulo disse: “Conhecerei de modo exato.” Com essas palavras, Paulo mostrou que sabia que, depois que recebesse sua recompensa celestial, ele alcançaria o grau mais íntimo de relacionamento com Jeová.
====

[[v46-13-13]]

^<<v46-13-13,13>>^ Agora, porém, permanecem estas três coisas: a fé, a esperança, o amor; mas a maior delas é o amor.

[TIP]
====
- *a maior delas é o amor*: Deus é de eternidade a eternidade, e sua qualidade principal é o amor. (Sal 90:2; 1Jo 4:8) Por isso, o amor permanecerá para sempre. E o amor dos servos de Deus, que devem imitá-lo, vai continuar aumentando por toda a eternidade. (Ef 5:1) Nesse sentido, o amor é superior à fé e à esperança. Quando as promessas e as profecias de Deus já tiverem se cumprido, seus servos não precisarão mais exercer fé nem ter esperança nelas. Assim, o amor é a maior das três qualidades que Paulo citou.
====

'''

xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[&#60; Capítulo Anterior] | <<v46-13-0,Topo>> | xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[Próximo Capítulo &#62;]