include::./index.adoc[]

[[v46-5-0]]
=== A Primeira aos Coríntios, 5
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. A PUREZA MORAL DA CONGREGAÇÃO DEVE SER PRESERVADA (5:1–6:20)
* 1. Como lidar com um caso de imoralidade sexual (5:1-13)
* A congregação não deve tolerar imoralidade sexual (5:1-5)
* “Um pouco de fermento leveda a massa toda” (5:6-8)
* Parar de ter convivência com os maus (5:9-13)
* 2. Melhor ser prejudicado do que levar um irmão a juízo perante descrentes (6:1-8)
* 3. Avisos contra impureza espiritual e moral (6:9-20)
* Os que não herdarão o Reino (6:9-11)
* “Os seus corpos são membros de Cristo”, então “fujam da imoralidade sexual!” (6:12-20)
****

[[v46-5-1]]

^<<v46-5-1,1>>^ O fato é que se relata entre vocês imoralidade sexual, imoralidade que não se encontra nem entre as nações: um homem está vivendo com^&#42;1^ a esposa de seu pai.

[NOTE]
====
. Lit.: “possuindo”.
====

[TIP]
====
- *imoralidade sexual . . . imoralidade*: A palavra grega porneía aparece duas vezes neste versículo. Essa palavra é um termo genérico usado para se referir a todos os tipos de atividade sexual que a Bíblia condena. Isso inclui adultério, prostituição, sexo entre pessoas não casadas, entre pessoas do mesmo sexo e entre humanos e animais. — Veja o Glossário.
====

[[v46-5-2]]

^<<v46-5-2,2>>^ E vocês se orgulham disso? Não deviam, na verdade, estar de luto, para que o homem que cometeu esse ato fosse tirado do seu meio?

[[v46-5-3]]

^<<v46-5-3,3>>^ Embora eu esteja ausente em corpo, estou presente em espírito, e já julguei o homem que fez isso, como se eu estivesse aí com vocês.

[[v46-5-4]]

^<<v46-5-4,4>>^ Quando estiverem reunidos em nome do nosso Senhor Jesus, sabendo que estou com vocês em espírito com o poder do nosso Senhor Jesus,

[[v46-5-5]]

^<<v46-5-5,5>>^ entreguem esse homem a Satanás, para a destruição da carne, a fim de que o espírito seja salvo no dia do Senhor.

[TIP]
====
- *entreguem esse homem a Satanás*: Esta era uma ordem para expulsar, ou desassociar, aquele homem da congregação. (1Co 5:13; 1Ti 1:20) Quando isso acontecesse, ele passaria a fazer parte do mundo, que tem Satanás como seu deus e governante. (1Jo 5:19) Paulo disse que a desassociação resultaria na destruição da carne no sentido de que a má influência que poderia corromper a congregação seria eliminada. Isso faria com que o espírito (a atitude dominante) da congregação continuasse positivo. — 2Ti 4:22.
====

[[v46-5-6]]

^<<v46-5-6,6>>^ O seu motivo de orgulho não é bom. Não sabem que um pouco de fermento leveda a massa toda?

[TIP]
====
- *fermento*: Nos tempos bíblicos, o fermento geralmente era uma porção de massa fermentada que era guardada para servir de fermento para outra massa. (Êx 12:20) A Bíblia muitas vezes usa o fermento para representar o pecado e a maldade. — Veja a nota de estudo em Mt 16:6.
- *leveda a*: Ou: “se espalha pela; tem efeito sobre a”. O verbo grego usado aqui, zymóo (“fermentar”), está relacionado com o substantivo zýme (“fermento”), que também foi usado neste versículo. Em Gál 5:9, Paulo também usou essa metáfora, que pelo visto era um ditado popular.
====

[[v46-5-7]]

^<<v46-5-7,7>>^ Eliminem o velho fermento, para que sejam massa nova, sem fermento, como de fato são. Pois, realmente, Cristo, o nosso cordeiro pascoal, já foi sacrificado.

[TIP]
====
- *Eliminem o velho fermento*: Aqui, Paulo faz uma referência indireta ao significado da Festividade dos Pães sem Fermento, que acontecia logo depois da celebração da Páscoa judaica. Durante a Páscoa, os israelitas retiravam todo o fermento de suas casas. Da mesma forma, os anciãos cristãos precisam agir e retirar “o velho fermento” da congregação. (1Co 5:8) Assim como apenas um pouco de fermento leveda rapidamente a massa toda, uma única pessoa que não se arrepende pode corromper toda a congregação, que se tornaria impura aos olhos de Jeová.
- *sem fermento . . . são*: Lit.: “vocês são sem fermento”. (Veja o Glossário, “Festividade dos Pães sem Fermento”.) O fermento muitas vezes representava o pecado e a maldade. Por isso, Paulo compara levar uma vida pura com celebrar a Festividade dos Pães sem Fermento. — 1Co 5:8; veja a nota de estudo em Eliminem o velho fermento neste versículo.
- *Cristo, o nosso cordeiro pascoal, já foi sacrificado*: Em Israel, o dia 14 de nisã era um dia alegre porque se celebrava a Páscoa judaica. Todos os anos, nesse dia, as famílias abatiam um cordeiro sem defeito e o preparavam para a refeição da Páscoa. Embora os cristãos não celebrassem a Páscoa, eles reconheciam que, em 14 de nisã de 1513 a.C., o sangue do cordeiro teve um papel importante na salvação dos primogênitos dos israelitas. Naquele dia, o anjo da morte matou todos os primogênitos dos egípcios, mas poupou os primogênitos dos israelitas obedientes. (Êx 12:1-14) Aqui, Paulo mostra que o cordeiro pascoal representava Jesus, que morreu em 14 de nisã de 33 d.C. Assim como o sangue do cordeiro pascoal, o sangue derramado de Jesus torna possível a salvação de muitas pessoas. — Jo 3:16, 36.
====

[[v46-5-8]]

^<<v46-5-8,8>>^ Portanto, celebremos a festividade, não com o velho fermento, nem com o fermento da maldade e da impiedade, mas com pães sem fermento, de sinceridade e de verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Eu lhes escrevi na minha carta que parassem de ter convivência com os que praticam imoralidade sexual,

[TIP]
====
- *Eu lhes escrevi na minha carta*: Aqui, Paulo está falando de uma carta que ele tinha escrito antes para os coríntios, mas que não está disponível hoje. Pelo visto, Deus decidiu não preservar essa outra carta, talvez porque seu conteúdo fosse necessário apenas para as pessoas a quem Paulo escreveu. — Veja a nota de estudo em 1Co 1:2.
- *parassem de ter convivência com*: Ou: “parassem de se associar com”. — Veja a nota de estudo em 1Co 5:11.
- *os que praticam imoralidade sexual*: Estas palavras são a tradução do substantivo grego pórnos, que está relacionado com o substantivo porneía (“imoralidade sexual”, 1Co 5:1) e com o verbo porneúo (“praticar imoralidade sexual”, 1Co 6:18). (Veja o Glossário, “Imoralidade sexual”.) Desde os tempos antigos, a cidade de Corinto era famosa por ser um lugar onde as pessoas levavam uma vida muito imoral e adoravam a deusa Afrodite. A adoração dessa deusa incentivava a sensualidade e a imoralidade. (Compare com a nota de estudo em 1Co 7:2.) Em 1Co 6:11, Paulo dá a entender que alguns cristãos de Corinto antes levavam uma vida imoral, mas mudaram sua conduta e se tornaram boas companhias.
====

[[v46-5-10]]

^<<v46-5-10,10>>^ não querendo dizer toda a convivência com as pessoas deste mundo que praticam imoralidade sexual, ou com os gananciosos, com os extorsores ou com os idólatras. Nesse caso, vocês teriam realmente de sair do mundo.

[TIP]
====
- *as pessoas . . . que praticam imoralidade sexual*: Veja a nota de estudo em 1Co 5:9.
====

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas eu lhes escrevo agora que parem de ter convivência com qualquer um que se chame irmão, mas que pratique imoralidade sexual, ou que seja ganancioso, idólatra, injuriador, beberrão ou extorsor; nem sequer comam com tal homem.

[TIP]
====
- *parem de ter convivência com*: Ou: “parem de se associar com”. O verbo grego synanamígnymai, traduzido aqui como “ter convivência com”, significa “misturar com”. (Esse verbo grego também aparece em 2Te 3:14.) Assim, “ter convivência” com uma pessoa envolveria ter amizade achegada ou companheirismo com ela e ter as mesmas opiniões e os mesmos sentimentos que ela. Os cristãos em Corinto tinham que ‘parar de ter convivência com’ qualquer um que fosse pecador e que não se arrependesse, ou seja, tinham que se recusar a se misturar com esse tipo de pessoa. Paulo disse: “Removam do meio de vocês a pessoa má.” — 1Co 5:13.
- *que pratique imoralidade sexual*: Veja a nota de estudo em 1Co 5:9.
- *injuriador*: Ou: “uma pessoa que agride com palavras”. Um injuriador é alguém que tem o hábito de insultar outros com a intenção de magoá-los. Uma pessoa que se nega a parar de fazer isso não está qualificada para fazer parte da congregação. — 1Co 5:11-13; 6:9, 10.
- *nem sequer comam com tal homem*: Com estas palavras, Paulo esclarece o que ele quis dizer quando deu a orientação sobre ‘parar de ter convivência’ com alguém da congregação que cometesse um pecado e não se arrependesse. Na Bíblia, comer junto com alguém era muitas vezes um sinal de amizade, e isso geralmente levava as pessoas a passarem mais tempo juntas. Os cristãos judeus entendiam muito bem esse conceito, já que os judeus não tinham convivência com pessoas “das nações” nem comiam com elas. — Mt 18:17; At 10:28; 11:2, 3.
====

[[v46-5-12]]

^<<v46-5-12,12>>^ Pois o que eu tenho a ver com o julgamento dos de fora? Não são vocês que julgam os de dentro,

[[v46-5-13]]

^<<v46-5-13,13>>^ ao passo que Deus julga os de fora? “Removam do meio de vocês a pessoa má.”

[TIP]
====
- *Removam do meio de vocês a pessoa má*: No começo deste capítulo, Paulo deu instruções para remover da congregação, ou desassociar, um homem que estava levando uma vida imoral. (1Co 5:1, 2; veja as notas de estudo em 1Co 5:1, 5.) Aqui, Paulo está citando De 17:7, onde Jeová disse para a nação de Israel: “Você deve eliminar o mal do seu meio.” Assim, Paulo mostra que a instrução que ele estava dando se baseava nas leis de Deus. Pelo visto, Paulo estava citando esse versículo conforme ele está na Septuaginta, que diz “a pessoa má” em vez de “o mal”. Frases bem parecidas com essa aparecem em De 19:19; 22:21, 24 e 24:7.
====

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]