include::./index.adoc[]

[[v46-11-0]]
=== A Primeira aos Coríntios, 11
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* E. PENSAR NO BEM-ESTAR ESPIRITUAL DE OUTROS CRISTÃOS (8:1–11:1)
* 1. Sobre os alimentos oferecidos a ídolos (8:1-13)
* O amor é superior ao conhecimento (8:1-3)
* Não fazer outros tropeçar na questão de comer alimentos oferecidos a ídolos (8:4-13)
* 2. O exemplo de Paulo como apóstolo (9:1-27)
* Ministros cristãos têm direito de receber ajuda material (9:1-18)
* Tornar-se todas as coisas para pessoas de todo tipo (9:19-23)
* É necessário ter autodomínio na corrida pela vida (9:24-27)
* 3. Exemplos da história de Israel que servem de alerta (10:1-22)
* Os israelitas no deserto (10:1-5)
* Avisos contra ganância, idolatria, imoralidade e outras coisas más (10:6-11)
* Ninguém é tentado além do que pode suportar (10:12, 13)
* “Fujam da idolatria”; rejeitem a mesa de demônios (10:14-22)
* 4. Ter consideração pelos outros ao usar a liberdade cristã (10:23–11:1)
* “Tudo é permitido, mas nem tudo edifica” (10:23, 24)
* Levar em conta a consciência de outros (10:25-30)
* Fazer todas as coisas para a glória de Deus; imitar Paulo e Cristo (10:31–11:1)
* F. INSTRUÇÕES PARA QUE A CONGREGAÇÃO ADORE A DEUS DE MODO ORDEIRO (11:2–14:40)
* Respeito pelo princípio da chefia; cobrir a cabeça (11:2-16)
* Mostrar respeito pela Ceia do Senhor (11:17-34)
* Dons do espírito (12:1-11)
* Um corpo, muitos membros (12:12-31a)
* Amor: um caminho superior (12:31b–13:13)
* Dons de profecia e de falar em línguas (14:1-25)
* Manter a ordem nas reuniões cristãs (14:26-40)
****

[[v46-11-1]]

^<<v46-11-1,1>>^ Tornem-se meus imitadores, como eu sou de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Eu os elogio porque em todas as coisas vocês se lembram de mim e se apegam às tradições conforme as transmiti a vocês.

[TIP]
====
- *às tradições*: A palavra grega parádosis, traduzida aqui como “tradições”, se refere a algo que é passado adiante, como, por exemplo, informações, instruções ou práticas. Nas Escrituras Gregas Cristãs, parádosis é às vezes usada com um tom positivo e se refere a tradições que faziam parte da adoração verdadeira. (2Te 2:15; 3:6) Um exemplo disso são as instruções que Paulo recebeu sobre como a Ceia do Senhor devia ser realizada. Essas instruções podiam corretamente ser transmitidas às congregações como uma tradição cristã. (1Co 11:23) Mas a mesma palavra grega é muitas vezes usada para se referir a tradições que eram erradas ou que, por causa da maneira como eram entendidas ou aplicadas, se tornavam prejudiciais ou questionáveis. — Mt 15:2, 3; Mr 7:3, 5, 13; Col 2:8.
====

[[v46-11-3]]

^<<v46-11-3,3>>^ Mas quero que saibam que o cabeça de todo homem é o Cristo; o cabeça da mulher é o homem; e o cabeça do Cristo é Deus.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo homem que ora ou profetiza com algo sobre a cabeça envergonha a sua^&#42;1^ cabeça;

[NOTE]
====
. Ou: “o seu”.
====

[[v46-11-5]]

^<<v46-11-5,5>>^ mas toda mulher que ora ou profetiza com a cabeça descoberta envergonha a sua^&#42;1^ cabeça, pois é exatamente como se fosse uma mulher com a cabeça raspada.

[NOTE]
====
. Ou: “o seu”.
====

[TIP]
====
- *descoberta*: Ou: “sem véu”. Na sociedade judaica e em algumas partes do mundo greco-romano, muitos consideravam que as mulheres deviam cobrir seu cabelo (ou usar um véu) em público, como um sinal de modéstia. As palavras de Paulo neste capítulo mostram que as mulheres cristãs do século 1 d.C. também cobriam a cabeça. Parece que algumas mulheres, incluindo feiticeiras e sacerdotisas de vários cultos, retiravam o véu e deixavam o cabelo cair despenteado, dizendo estar sob a influência de um poder sobrenatural. Uma mulher que fizesse algo assim dentro da congregação cristã não estaria sendo submissa e estaria desrespeitando o princípio da chefia dado por Jeová. Pode ter sido por isso que Paulo aconselhou os cristãos em Corinto sobre esse assunto. — 1Co 11:3-10; veja as notas de estudo em 1Co 11:10, 15.
- *uma mulher com a cabeça raspada*: De acordo com as palavras de Paulo aqui, era vergonhoso para uma mulher ter sua cabeça raspada ou seu cabelo cortado curto. Isso talvez fosse considerado vergonhoso porque normalmente as únicas mulheres que tinham a cabeça raspada eram as escravas e, possivelmente, as que tinham sido pegas cometendo adultério. Além disso, as Escrituras Hebraicas falam sobre mulheres que tiveram seus “belos penteados” transformados em “calvície”, um sinal de luto. (Is 3:24) Apesar de não ser possível saber exatamente o que Paulo tinha em mente, ele diz que seria tão vergonhoso para uma mulher orar ou profetizar com a cabeça descoberta na congregação quanto seria vergonhoso para ela ter sua cabeça raspada. A mulher que agisse assim também não estaria mostrando respeito pelo princípio da chefia dado por Deus. — 1Co 11:3-10; veja a nota de estudo em 1Co 11:15.
====

[[v46-11-6]]

^<<v46-11-6,6>>^ Porque, se a mulher não se cobrir, deve cortar rente o cabelo; mas, se é vergonhoso para a mulher cortar rente o cabelo ou raspar a cabeça, ela deve se cobrir.

[[v46-11-7]]

^<<v46-11-7,7>>^ Pois o homem não deve cobrir a cabeça, visto ser imagem e glória de Deus, mas a mulher é a glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Porque o homem não veio da mulher, mas a mulher veio do homem.

[[v46-11-9]]

^<<v46-11-9,9>>^ E, além disso, o homem não foi criado para a mulher, mas a mulher para o homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ É por isso que a mulher deve ter um sinal de autoridade sobre a cabeça, e por causa dos anjos.

[TIP]
====
- *um sinal de autoridade*: Neste capítulo, Paulo dá orientações sobre o princípio da chefia. (1Co 11:3) Aqui, ele fala sobre a necessidade de a mulher cobrir a cabeça ao orar ou profetizar na congregação. Cobrir a cabeça é “um sinal de autoridade”, ou seja, é uma prova visível (até mesmo para os anjos) de que a mulher reconhece que Deus deu aos homens o papel de liderança na congregação. Ao cobrir a cabeça em certas situações, a mulher mostra que se submete de coração à “autoridade” dentro da congregação. — 1Co 11:4-6; veja as notas de estudo em 1Co 11:5, 15.
====

[[v46-11-11]]

^<<v46-11-11,11>>^ Entretanto, no Senhor, nem a mulher existe sem o homem, nem o homem sem a mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ Pois, assim como a mulher procede do homem, assim também o homem vem à existência por meio da mulher; mas todas as coisas procedem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julguem vocês mesmos: É apropriado para uma mulher orar a Deus com a cabeça descoberta?

[[v46-11-14]]

^<<v46-11-14,14>>^ Não lhes ensina a própria natureza que ter cabelo comprido é uma desonra para o homem,

[[v46-11-15]]

^<<v46-11-15,15>>^ mas, se a mulher tem cabelo comprido, isso é uma glória para ela? Pois o cabelo lhe foi dado em lugar de uma cobertura para a cabeça.

[TIP]
====
- *lhe foi dado em lugar de uma cobertura para a cabeça*: Esta é a única vez que a palavra grega peribólaion, traduzida aqui como “cobertura para a cabeça”, aparece nas Escrituras Gregas Cristãs. Ela significa “algo que alguém joga em volta de si”, como um lenço ou um manto usado para cobrir a cabeça e os ombros. Entre os judeus e os gregos, as pessoas associavam o comprimento do cabelo com o sexo da pessoa. As únicas mulheres que tinham cabeça raspada ou cabelo curto eram as escravas e, possivelmente, as que tinham sido pegas cometendo adultério. (Veja a nota de estudo em 1Co 11:5.) Os cabelos compridos das mulheres serviam como um lembrete natural de sua submissão ao homem. (1Co 11:3) Quando uma mulher cobria a cabeça como “um sinal de autoridade” ao orar ou profetizar na congregação, ela mostrava a todos, incluindo os anjos, que reconhecia o princípio da chefia. — 1Co 11:3-16; veja a nota de estudo em 1Co 11:10.
====

[[v46-11-16]]

^<<v46-11-16,16>>^ No entanto, se alguém quiser argumentar a favor de outro costume, não temos outro, nem o têm as congregações de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Mas, ao dar essas ordens, não os elogio, porque não é para o seu benefício que vocês se reúnem, mas para o seu prejuízo.

[[v46-11-18]]

^<<v46-11-18,18>>^ Pois, em primeiro lugar, ouço dizer que, quando vocês se reúnem como congregação, existem divisões entre vocês; e, até certo ponto, acredito nisso.

[TIP]
====
- *divisões*: Veja a nota de estudo em 1Co 1:10.
====

[[v46-11-19]]

^<<v46-11-19,19>>^ Pois certamente haverá seitas^&#42;1^ entre vocês, para que também fique claro quais de vocês são aprovados.

[NOTE]
====
. Ou: “facções”.
====

[TIP]
====
- *seitas entre vocês*: O versículo anterior mostra que Paulo tinha sido informado sobre a existência de “divisões” na congregação em Corinto. Aqui neste versículo, ele indica que essas divisões na verdade ajudariam a deixar claro quais dos cristãos daquela congregação eram aprovados por Deus. Aqueles que não se envolvessem nessas divisões e que, com humildade, fizessem tudo ao seu alcance para promover o amor e a união mostrariam que eram cristãos fiéis e verdadeiros que tinham a motivação correta. Assim, as seitas ou divisões acabariam servindo para identificar os que tinham a aprovação de Deus. — Para uma explicação sobre a palavra “seita”, veja a nota de estudo em At 24:5.
====

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando vocês se reúnem, não é realmente para tomar a Ceia do Senhor.

[TIP]
====
- *a Ceia do Senhor*: Esta é a única vez que a expressão “Ceia do Senhor” aparece nas Escrituras Gregas Cristãs. Ela se refere à celebração que foi criada pelo Senhor Jesus Cristo em 14 de nisã, na noite anterior à sua morte. Nessa celebração, pão não fermentado e vinho são usados para simbolizar o corpo e o sangue de Cristo. A primeira Ceia do Senhor e alguns acontecimentos relacionados a ela foram registrados por dois apóstolos que participaram daquela celebração, Mateus e João. (Mt 26:17-30; Jo 13:1-38) Marcos e Lucas não estavam presentes, mas registraram alguns detalhes adicionais. (Mr 14:17-26; Lu 22:7-39) Aqui, ao dar instruções para a congregação em Corinto, Paulo ajuda a entender ainda outros detalhes. (1Co 10:16-22; 11:20-34) De acordo com os relatos feitos por Lucas e Paulo, Jesus disse a seus discípulos: “Persistam em fazer isso em memória de mim.” (Lu 22:19; 1Co 11:24, 25) O objetivo da Ceia do Senhor é celebrar a morte de Jesus. Por isso, ela também pode ser chamada corretamente de Celebração. Essa é a única celebração que as Escrituras ordenam que os cristãos realizem.
====

[[v46-11-21]]

^<<v46-11-21,21>>^ Pois, na hora de tomá-la, vocês comem primeiro o seu próprio jantar, de modo que um está com fome, mas outro está embriagado.

[TIP]
====
- *um está com fome, mas outro está embriagado*: Aqui, Paulo repreende os cristãos em Corinto porque alguns deles não estavam participando na Ceia do Senhor de forma unida e digna. Eles levavam seu próprio jantar para comer antes ou durante a reunião. Entre esses, alguns consumiam vinho demais e ficavam bêbados. Outros, que não tinham jantado, ficavam com fome e se sentiam envergonhados ao se comparar com os que tinham levado muita comida. Enquanto alguns ficavam sonolentos, outros ficavam distraídos. Nos dois casos, eles não estavam em condições de participar na Ceia do Senhor e dar a ela o devido valor.
====

[[v46-11-22]]

^<<v46-11-22,22>>^ Será que vocês não têm casa para comer e beber? Ou desprezam a congregação de Deus e fazem aqueles que não têm nada se sentir envergonhados? O que posso dizer a vocês? Devo elogiá-los? Nisso não os elogio.

[[v46-11-23]]

^<<v46-11-23,23>>^ Pois eu recebi do Senhor o que também lhes transmiti: que o Senhor Jesus, na noite em que ia ser traído, pegou um pão,

[TIP]
====
- *eu recebi do Senhor*: Paulo não estava presente quando Jesus realizou a primeira Ceia do Senhor com seus 11 apóstolos em 14 de nisã do ano 33 d.C. Assim, ele pode ter ‘recebido do Senhor’ essas informações por meio de uma revelação inspirada ou pode ser que o próprio Jesus tenha falado com ele. Apesar de algumas poucas traduções usarem o nome de Deus neste versículo, aqui a palavra grega Kýrios (“Senhor”) pelo visto se refere ao Senhor Jesus Cristo.
====

[[v46-11-24]]

^<<v46-11-24,24>>^ e, depois de dar graças, partiu-o e disse: “Isto representa o meu corpo, em benefício de vocês. Persistam em fazer isso em memória de mim.”

[TIP]
====
- *representa*: Veja a nota de estudo em Mt 26:26.
====

[[v46-11-25]]

^<<v46-11-25,25>>^ Ele fez o mesmo também com respeito ao cálice, depois de terem tomado a refeição, dizendo: “Este cálice representa o novo pacto com base no meu sangue. Persistam em fazer isso, sempre que o beberem, em memória de mim.”

[TIP]
====
- *a refeição*: Ou: “a ceia”. Ou seja, a Páscoa.
====

[[v46-11-26]]

^<<v46-11-26,26>>^ Pois, sempre que vocês comerem esse pão e beberem esse cálice, estarão proclamando a morte do Senhor, até que ele venha.

[TIP]
====
- *sempre que*: Neste contexto, Paulo está falando sobre como realizar a Celebração, e não sobre a frequência com que ela deve ser realizada. A palavra grega que Paulo usa aqui (e também no versículo 25) é hosákis, que significa “todas as vezes que; sempre que”. Assim, ele estava dizendo aos cristãos ungidos: ‘Cada vez que vocês fizerem isso’, estarão proclamando a morte do Senhor. Os cristãos ungidos vão fazer isso até que ele venha, ou seja, até que Jesus venha para receber os ungidos no céu e para executar julgamento. Depois disso, a Ceia do Senhor não será mais realizada. — Veja a nota de estudo em Mt 24:30.
====

[[v46-11-27]]

^<<v46-11-27,27>>^ Portanto, quem comer o pão ou beber o cálice do Senhor indignamente será culpado com respeito ao corpo e ao sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Primeiro, que o homem examine e aprove a si mesmo, e só então coma do pão e beba do cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Pois quem come e bebe sem discernir o corpo, come e bebe julgamento contra si mesmo.

[TIP]
====
- *come e bebe julgamento contra si mesmo*: A Ceia do Senhor é uma refeição de participação em comum. Ela é semelhante aos sacrifícios de participação em comum do antigo Israel, em que o adorador oferecia um sacrifício e depois participava de uma refeição junto com outros e, de certa forma, com Jeová. (Veja o Glossário, “Sacrifício de participação em comum”.) De acordo com a Lei mosaica, se uma pessoa que estivesse impura participasse desse tipo de refeição sagrada, ela seria “eliminada do seu povo”. (Le 7:20, 21) Na Ceia do Senhor, os ungidos compartilham uma refeição, comendo do pão e bebendo do vinho (que representam o corpo e o sangue de Jesus). Unidos pela sua fé, eles como que tomam essa refeição com Jeová, que foi quem tornou essa celebração possível. A Ceia do Senhor é uma refeição sagrada. Por isso, Paulo avisa aos cristãos que eles devem examinar a si mesmos antes da Ceia do Senhor. (1Co 11:27-29) Se um ungido estivesse envolvido em comportamento impuro, antibíblico ou hipócrita e participasse dessa refeição sagrada, ele estaria comendo e bebendo “julgamento contra si mesmo” porque estaria tratando o resgate com desrespeito. — Compare com He 10:28-31.
====

[[v46-11-30]]

^<<v46-11-30,30>>^ É por isso que muitos entre vocês estão fracos e doentes, e um bom número está dormindo na morte.

[TIP]
====
- *está dormindo na morte*: Lit.: “está dormindo”. Aqui, estas palavras pelo visto se referem à morte espiritual.
====

[[v46-11-31]]

^<<v46-11-31,31>>^ Mas, se discerníssemos o que nós mesmos somos, não seríamos julgados.

[[v46-11-32]]

^<<v46-11-32,32>>^ No entanto, quando somos julgados, somos disciplinados por Jeová, para não sermos condenados com o mundo.

[TIP]
====
- *somos disciplinados por Jeová*: Aqui, Paulo incentiva os cristãos em Corinto a aceitar a disciplina, ou correção, que tinham recebido porque estavam tratando a Ceia do Senhor com desrespeito. (1Co 11:27, 29) Se eles mudassem sua atitude, eles não seriam condenados com o mundo, ou seja, com os humanos que não servem a Deus. As Escrituras mostram que, por amor, Jeová disciplina seu povo quando necessário. — De 11:2; Pr 3:11, 12; Je 7:28; He 12:5, 6.
- *disciplinados por Jeová*: As palavras de Paulo aqui fazem lembrar Pr 3:11, 12, que diz: “Meu filho, não rejeite a disciplina de Jeová . . . Pois Jeová repreende aqueles a quem ama.” No texto hebraico original de Pr 3:11, o substantivo hebraico para “disciplina” aparece junto com as quatro letras hebraicas que formam o nome de Deus (que equivalem a YHWH). Em He 12:5, 6, Paulo cita esses versículos de Provérbios e, por isso, o nome “Jeová” foi usado no texto principal de Hebreus na Tradução do Novo Mundo. (Veja o Apêndice C1.) A expressão que aparece aqui em 1Co 11:32 lembra as expressões que aparecem em Provérbios e Hebreus. Além disso, as palavras gregas para “disciplina” e “disciplinar” que foram usadas aqui e em He 12:5, 6 são as mesmas que aparecem em Pr 3:11, 12 na Septuaginta. Por isso, o nome de Deus foi usado aqui no texto principal de 1Co 11:32. — Veja o Apêndice C3 (introdução e 1Co 11:32).
====

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando se reunirem para essa ceia, esperem uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se alguém estiver com fome, que coma em casa, para que, quando vocês se reunirem, isso não resulte em julgamento. Mas, quanto aos outros assuntos, eu os porei em ordem quando chegar aí.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]