include::./index.adoc[]

[[v46-4-0]]
=== A Primeira aos Coríntios, 4
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* B. A IMPORTÂNCIA DA UNIÃO NA CONGREGAÇÃO CRISTÃ (1:10–4:21)
* 1. Coisas que contribuem para a união ou a desunião (1:10–2:16)
* Seguir humanos causa divisões (1:10-17)
* Reconhecer a Cristo, que é o poder e a sabedoria de Deus (1:18-25)
* Orgulhar-se somente em Jeová, não em humanos (1:26-31)
* Pregar como Paulo, sem usar linguagem ou sabedoria extravagantes (2:1-5)
* Reconhecer a superioridade da sabedoria de Deus (2:6-10)
* Receber o espírito que vem de Deus; ser um homem espiritual (2:11-16)
* 2. Cooperar com Deus para que a congregação cresça e seja unida (3:1-23)
* Pensamento carnal gera ciúme e brigas (3:1-4)
* Humanos são ministros, mas é Deus quem faz crescer (3:5-9)
* Construir com materiais resistentes ao fogo (3:10-15)
* “Vocês . . . são templo de Deus” (3:16, 17)
* A sabedoria do mundo é tolice perante Deus (3:18-23)
* 3. Conselhos adicionais que contribuem para a união (4:1-21)
* O que importa é o julgamento de Jeová (4:1-5)
* Cristãos que são humildes não se acham melhores do que os seus irmãos (4:6-13)
* Paulo aconselha seus filhos espirituais a não serem orgulhosos (4:14-21)
****

[[v46-4-1]]

^<<v46-4-1,1>>^ Os homens devem nos considerar como assistentes do Cristo e administradores dos segredos sagrados de Deus.

[TIP]
====
- *assistentes do*: Ou: “subordinados ao”. A palavra grega traduzida aqui como “assistentes” é hyperétes. Ela passa a ideia de alguém que serve como “ajudante”. (At 13:5) Os “assistentes do Cristo” obedecem às ordens dele de boa vontade.
- *administradores*: A palavra grega para “administrador”, oikonómos, também poderia ser traduzida como “administrador da casa; mordomo”. Ela se refere a um servo que tinha autoridade sobre a “casa” de seu senhor, o que incluía os negócios, as propriedades e os outros servos dele. A função de administrador era um cargo de confiança e, por isso, se esperava que os administradores fossem fiéis. (1Co 4:2) Paulo reconhecia que seu serviço como administrador envolvia cuidar bem dos “segredos sagrados de Deus” e que, para ser considerado fiel, ele precisava declarar esses segredos a outros, conforme seu Senhor, Jesus Cristo, tinha ordenado. — 1Co 9:16; veja a nota de estudo em Lu 12:42.
====

[[v46-4-2]]

^<<v46-4-2,2>>^ Ora, o que se espera dos administradores é que se mostrem fiéis.

[[v46-4-3]]

^<<v46-4-3,3>>^ Para mim, pouco importa ser examinado por vocês ou por um tribunal humano. Na verdade, nem eu examino a mim mesmo.

[TIP]
====
- *um tribunal humano*: Ou: “uma corte humana”. Lit.: “um dia humano”. A palavra grega para “dia” foi usada neste versículo com o sentido de “dia escolhido para um determinado objetivo”. Aqui, ela se refere especificamente ao dia escolhido por um juiz humano para realizar um julgamento ou para emitir uma sentença. O contexto mostra o que Paulo queria dizer. Em vez de se preocupar com julgamentos feitos por humanos (pelos coríntios ou por um tribunal humano), Paulo se preocupava principalmente com o futuro dia de julgamento de Deus, em que Jesus agirá como Juiz designado por Deus. — 1Co 4:4, 5.
====

[[v46-4-4]]

^<<v46-4-4,4>>^ Pois não estou ciente de nada contra mim mesmo. Mas isso não prova que eu seja justo; quem me examina é Jeová.

[TIP]
====
- *quem me examina é Jeová*: Para Paulo, o importante não era o julgamento que outros faziam sobre ele. Ele também não confiava na opinião que tinha de si mesmo. (1Co 4:1-3) O que realmente importava para Paulo era o que Jeová achava dele. Com base nas Escrituras Hebraicas, Paulo sabia que é Jeová quem examina seus servos. — Sal 26:2; Pr 21:2; Je 20:12; para uma explicação sobre os motivos de o nome de Deus ter sido usado aqui, veja o Apêndice C3 (introdução e 1Co 4:4).
====

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem nada antes do tempo devido, até que venha o Senhor. Ele trará da escuridão para a luz as coisas secretas e revelará as intenções dos corações, e então cada um receberá o seu louvor da parte de Deus.

[[v46-4-6]]

^<<v46-4-6,6>>^ Irmãos, eu apliquei essas coisas a mim mesmo e a Apolo para o bem de vocês, a fim de que, por meio do nosso exemplo, aprendam a regra: “Não vão além das coisas que estão escritas”, a fim de que não fiquem cheios de orgulho, tomando o partido de um contra o outro.

[TIP]
====
- *Não vão além das coisas que estão escritas*: Esta frase não é uma citação das Escrituras Hebraicas, mas, pelo visto, era uma frase bem conhecida ou um ditado. A regra citada aqui por Paulo indica que os servos de Deus não devem ensinar nem fazer nada que ultrapasse os limites fixados pelas leis e princípios registrados na Palavra inspirada de Deus. Por exemplo, as Escrituras ajudam os cristãos a ter um ponto de vista correto sobre si mesmos e sobre os outros. Seria errado ir além do que elas dizem, desconsiderando essas orientações. Os coríntios tinham caído nesse erro e se orgulhavam de sua ligação com certos homens, talvez Apolo ou até mesmo Paulo. Eles davam mais importância a uma pessoa do que a outra, causando desunião. Talvez com a intenção de dar aos coríntios um exemplo prático sobre não ir além das coisas escritas, Paulo citou as Escrituras Hebraicas várias vezes para apoiar seus argumentos nos capítulos anteriores desta carta. Ao fazer isso, ele usou a expressão “está escrito”. — 1Co 1:19, 31; 2:9; 3:19; veja também 1Co 9:9; 10:7; 14:21; 15:45.
====

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois quem torna você diferente dos outros? Realmente, o que você tem que não tenha recebido? Se você, de fato, recebeu tudo que tem, por que se gaba como se não o tivesse recebido?

[[v46-4-8]]

^<<v46-4-8,8>>^ Vocês já estão satisfeitos? Já estão ricos? Já começaram a reinar sem nós? Eu realmente queria que vocês já tivessem começado a reinar, para que nós também reinássemos com vocês.

[[v46-4-9]]

^<<v46-4-9,9>>^ Pois me parece que Deus pôs a nós, os apóstolos, em exibição por último, como homens condenados à morte, porque nos tornamos um espetáculo para o mundo, para anjos e para homens.

[TIP]
====
- *um espetáculo*: Lit.: “um teatro”. A palavra grega théatron podia se referir tanto ao local onde o espetáculo era realizado (At 19:29, 31) quanto ao espetáculo em si, como é o caso neste versículo. Paulo talvez estivesse fazendo referência ao evento que costumava encerrar as competições de gladiadores nas arenas dos anfiteatros romanos. Alguns gladiadores eram levados para a arena nus e desarmados, e então eram mortos de maneira brutal. Ao noroeste da praça principal de Corinto, existia um teatro com capacidade para umas 15.000 pessoas. Além disso, também havia um anfiteatro no canto nordeste da cidade, que provavelmente estava em funcionamento nos dias de Paulo. Por isso, os coríntios devem ter entendido muito bem o que Paulo quis dizer quando escreveu que os apóstolos eram “um espetáculo para o mundo”.
- *para o mundo, para anjos e para homens*: Aqui, a palavra grega traduzida como “mundo” (kósmos) se refere a todos os humanos. A continuação da frase, “para anjos e para homens”, não é uma explicação da palavra “mundo”, como se ela incluísse tanto criaturas espirituais invisíveis quanto seres humanos. Paulo estava apenas explicando que, além dos humanos, os anjos também estavam assistindo a esse espetáculo. O fato de Paulo usar a palavra kósmos para se referir a todos os humanos em 1Co 1:20, 21, 27, 28; 2:12 e 3:19, 22 apoia o entendimento de que neste versículo ela tem o mesmo significado.
====

[[v46-4-10]]

^<<v46-4-10,10>>^ Nós somos tolos por causa de Cristo, mas vocês são prudentes em união com Cristo; nós somos fracos, mas vocês são fortes; vocês são honrados, mas nós somos desonrados.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até agora, passamos fome e sede, não temos roupa suficiente, somos espancados,^&#42;1^ estamos desabrigados

[NOTE]
====
. Ou: “maltratados”.
====

[TIP]
====
- *não temos roupa suficiente*: O verbo grego que aparece aqui significa literalmente “estar nu”, mas neste contexto ele se refere a não ter roupa suficiente. (Veja a nota de estudo em Mt 25:36.) Pelo visto, aqui Paulo está fazendo um contraste entre a vida de sacrifícios que ele levava e a vida relativamente fácil de alguns cristãos em Corinto que se consideravam espiritualmente superiores aos outros. — 1Co 4:8-10; compare com 2Co 11:5.
====

[[v46-4-12]]

^<<v46-4-12,12>>^ e trabalhamos arduamente com as nossas próprias mãos. Quando insultados, abençoamos; quando perseguidos, suportamos com paciência;

[[v46-4-13]]

^<<v46-4-13,13>>^ quando caluniados, respondemos com brandura;^&#42;1^ nós nos tornamos como o lixo do mundo, a escória de todas as coisas, até agora.

[NOTE]
====
. Lit.: “suplicamos”.
====

[TIP]
====
- *lixo*: Ou: “refugo”. As palavras gregas traduzidas neste versículo como “lixo” (perikátharma) e escória (perípsema) são fortes e têm um significado parecido. Esta é a única vez que essas palavras aparecem nas Escrituras Gregas Cristãs. As duas passam a ideia de algo que é descartado — algo que é jogado fora depois de uma limpeza ou que é removido ou lavado de uma superfície. Pelo visto, era assim que algumas pessoas que criticavam Paulo viam a ele e ao seu trabalho missionário.
====

[[v46-4-14]]

^<<v46-4-14,14>>^ Estou escrevendo essas coisas, não para envergonhá-los, mas para instruí-los como meus filhos amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Pois, embora vocês tenham 10.000 tutores em Cristo, certamente não têm muitos pais; porque fui eu que me tornei seu pai em Cristo Jesus por meio das boas novas.

[TIP]
====
- *tutores*: Ou: “guardiões”. Nos tempos bíblicos, muitas famílias gregas e romanas que eram ricas contavam com o trabalho de um tutor, ou guardião. O tutor podia ser um escravo de confiança ou alguém contratado. Ele tinha a responsabilidade de acompanhar a criança no caminho de ida e volta da escola e de protegê-la de perigos físicos e de más influências. Em alguns casos, ele também ajudava a ensinar para a criança o que é certo e errado e até mesmo a disciplinava. (Gál 3:24, 25) Aqui, Paulo usa essa palavra em sentido figurado para se referir aos homens que tinham recebido a responsabilidade de cuidar em sentido espiritual dos cristãos em Corinto. — 1Co 3:6, 10.
- *me tornei seu pai*: Aqui, Paulo fala de si mesmo como um pai porque alguns dos cristãos em Corinto eram seus filhos em sentido espiritual. Ele tinha passado um ano e meio naquela cidade e, durante esse tempo, tinha ensinado pessoalmente as boas novas para muitos ali. (At 18:7-11) Além de dar início à congregação em Corinto, Paulo teve um papel importante em ajudar os cristãos daquela congregação a crescer em sentido espiritual. (1Co 3:5, 6, 10; compare com 3Jo 4.) Mas Paulo não estava dando a entender que eles deviam chamá-lo de “pai”, como um título religioso, porque isso iria contra o que Jesus Cristo tinha dito. — Mt 23:8, 9; veja a nota de estudo em Mt 23:9.
====

[[v46-4-16]]

^<<v46-4-16,16>>^ Assim, eu os exorto: tornem-se meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ É por isso que lhes envio Timóteo, porque ele é meu filho amado e fiel no Senhor. Ele lembrará vocês do meu modo de fazer as coisas em união com Cristo Jesus, assim como estou ensinando em toda a parte, em todas as congregações.

[TIP]
====
- *do meu modo de fazer as coisas*: Lit.: “dos meus caminhos”. Algumas Bíblias usam aqui expressões como “meus princípios de vida; minha maneira de viver”. Mas o contexto mostra que Paulo não estava falando apenas de sua conduta cristã. Paulo diz em seguida “assim como estou ensinando em toda a parte, em todas as congregações”. Isso indica que ele estava se referindo ao seu modo de ensinar e aos princípios que ele seguia ao realizar seu ministério cristão.
====

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns estão cheios de orgulho, como se eu não fosse visitar vocês.

[[v46-4-19]]

^<<v46-4-19,19>>^ Mas vou visitá-los em breve, se Jeová quiser, e tomarei conhecimento não das palavras desses orgulhosos, mas do poder deles.

[TIP]
====
- *se Jeová quiser*: Esta expressão mostra que é necessário levar em conta a vontade de Deus ao planejar ou fazer qualquer coisa. O apóstolo Paulo sempre tinha em mente esse princípio. (At 18:21; 1Co 16:7; He 6:3) O discípulo Tiago também incentivou seus leitores a dizer: “Se Jeová quiser, viveremos e faremos isso ou aquilo.” (Tg 4:15) Tiago não estava dizendo que os cristãos precisam sempre falar essas palavras em voz alta. Também não seria correto dizer isso apenas da boca para fora ou por superstição. Em vez disso, os cristãos devem tentar saber qual é a vontade de Deus e agir de acordo com ela.
====

[[v46-4-20]]

^<<v46-4-20,20>>^ Pois o Reino de Deus não é questão de palavras, mas de poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ O que vocês preferem? Que eu os visite com uma vara, ou com amor e brandura de espírito?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]