include::./index.adoc[]

[[v46-12-0]]
=== A Primeira aos Coríntios, 12
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* F. INSTRUÇÕES PARA QUE A CONGREGAÇÃO ADORE A DEUS DE MODO ORDEIRO (11:2–14:40)
* Respeito pelo princípio da chefia; cobrir a cabeça (11:2-16)
* Mostrar respeito pela Ceia do Senhor (11:17-34)
* Dons do espírito (12:1-11)
* Um corpo, muitos membros (12:12-31a)
* Amor: um caminho superior (12:31b–13:13)
* Dons de profecia e de falar em línguas (14:1-25)
* Manter a ordem nas reuniões cristãs (14:26-40)
****

[[v46-12-1]]

^<<v46-12-1,1>>^ Agora, quanto aos dons espirituais,^&#42;1^ irmãos, não quero que vocês fiquem na ignorância.

[NOTE]
====
. Lit.: “às (coisas) espirituais”.
====

[TIP]
====
- *irmãos*: Veja a nota de estudo em Ro 1:13.
====

[[v46-12-2]]

^<<v46-12-2,2>>^ Vocês sabem que, quando eram pessoas das nações, eram influenciados e desviados para aqueles ídolos sem voz, seguindo-os para onde quer que levassem vocês.

[TIP]
====
- *pessoas das nações*: Ou seja, descrentes.
====

[[v46-12-3]]

^<<v46-12-3,3>>^ Portanto, saibam que ninguém diz: “Jesus é maldito!” quando fala pelo espírito de Deus, e ninguém pode dizer: “Jesus é Senhor!” a não ser por espírito santo.

[[v46-12-4]]

^<<v46-12-4,4>>^ Há diferentes dons, mas há o mesmo espírito;

[TIP]
====
- *dons*: Aqui, Paulo está falando dos dons que Deus dava aos cristãos do século 1 d.C. (1Co 12:1) Cada um dos dons mencionados em 1Co 12:8-10 (veja as notas de estudo nesses versículos) envolvia uma habilidade milagrosa. Para dar esses dons aos cristãos, Deus usou seu espírito santo, ou força ativa. O espírito santo pode agir de maneiras diferentes em cada servo de Deus para atingir um objetivo específico. Assim, nem todos recebiam o mesmo dom, ou habilidade milagrosa. A palavra grega usada aqui, khárisma (lit.: “graça”), aparece 17 vezes nas Escrituras Gregas Cristãs. Essa palavra está relacionada com a palavra kháris, muitas vezes traduzida como “bondade imerecida”. — Veja a nota de estudo em Ro 6:23.
====

[[v46-12-5]]

^<<v46-12-5,5>>^ e há diferentes maneiras de servir,^&#42;1^ contudo há o mesmo Senhor;

[NOTE]
====
. Ou: “diferentes ministérios”.
====

[[v46-12-6]]

^<<v46-12-6,6>>^ e há diferentes atividades,^&#42;1^ contudo é o mesmo Deus que realiza tudo em todos.

[NOTE]
====
. Ou: “operações”.
====

[[v46-12-7]]

^<<v46-12-7,7>>^ Mas a manifestação do espírito é dada a cada um com um objetivo benéfico.

[[v46-12-8]]

^<<v46-12-8,8>>^ Pois a um é dada a palavra de sabedoria por meio do espírito; a outro, a palavra de conhecimento, segundo o mesmo espírito;

[TIP]
====
- *a palavra de sabedoria*: Ou: “uma mensagem de sabedoria”. Esta expressão se refere a uma sabedoria maior do que a que um cristão conseguiria naturalmente por estudar a Palavra de Deus e viver de acordo com seus princípios. Aqui, Paulo está se referindo a uma habilidade sobrenatural de aplicar bem o conhecimento. Esse tipo de sabedoria com certeza foi muito útil para ajudar a resolver os problemas que surgiram no início da congregação cristã. Paulo talvez tivesse esse dom, que ele pode ter usado, por exemplo, para escrever as cartas que se tornaram parte da Palavra inspirada de Deus. (2Pe 3:15, 16) Jesus tinha prometido que os cristãos receberiam sabedoria quando precisassem defender sua fé. — Lu 21:15; At 6:9, 10.
- *a palavra de conhecimento*: Aqui, Paulo não está se referindo ao conhecimento sobre Deus que todos os cristãos precisam ter para se tornarem discípulos. (Jo 17:3; Ro 10:14) Em vez disso, ele está falando de um conhecimento milagroso, que ia além do conhecimento que estava disponível para os cristãos em geral. Por exemplo, o apóstolo Pedro pode ter usado o dom da “palavra de conhecimento” ao lidar com o caso de Ananias. O espírito santo revelou a Pedro que Ananias tinha mentido para a congregação a respeito de um assunto financeiro, algo que teria sido impossível Pedro saber de outra forma. — At 5:1-5.
====

[[v46-12-9]]

^<<v46-12-9,9>>^ a outro, a fé, pelo mesmo espírito; a outro, dons de curar, por esse único espírito;

[TIP]
====
- *a fé*: É verdade que todos os cristãos precisam ter fé (Ro 10:10; He 11:6), mas aqui Paulo está falando de uma fé especial. Pelo visto, essa fé dava a alguns cristãos a capacidade milagrosa de vencer desafios gigantescos, comparáveis a montanhas, que de outra forma poderiam impedir que eles continuassem servindo lealmente a Deus. — 1Co 13:2.
- *dons de curar*: Esta expressão se refere à habilidade milagrosa de curar qualquer tipo de problema físico. As pessoas com doenças ou deficiências não precisavam fazer uma declaração emocionada de fé para serem curadas. (Jo 5:5-9, 13) Em vez disso, o mais importante era que a pessoa que estava fazendo a cura tivesse fé. (Mt 17:14-16, 18-20) Esse dom era uma prova clara de que a recém-formada congregação cristã tinha as bênçãos e o espírito de Deus. — At 5:15, 16; 9:33, 34; 28:8, 9.
====

[[v46-12-10]]

^<<v46-12-10,10>>^ a ainda outro, a realização de obras poderosas; a outro, o profetizar; a outro, o discernimento de expressões inspiradas; a outro, diversas línguas; e a outro, a interpretação de línguas.

[TIP]
====
- *a realização de obras poderosas*: Ou: “a realização de milagres”. Lit.: “operações de poderes”. Aqui, Paulo pelo visto está se referindo a uma variedade de obras sobrenaturais que talvez incluíssem ressuscitar pessoas, expulsar demônios e até deixar opositores cegos. Essas obras impressionantes motivaram muitos a se tornarem cristãos. — At 9:40, 42; 13:8-12; 19:11, 12, 20.
- *o profetizar*: Em certo sentido, todos os cristãos profetizavam quando falavam sobre o cumprimento das profecias registradas na Palavra de Deus. (At 2:17, 18; veja as notas de estudo em At 2:17; 21:9 e o Glossário, “Profecia”; “Profeta”.) Mas aqueles que tinham o dom milagroso que Paulo menciona aqui também conseguiam predizer acontecimentos futuros. Por exemplo, Ágabo foi inspirado a profetizar uma grande fome e a predizer que Paulo seria preso por causa da perseguição dos judeus. (At 11:27, 28; 21:10, 11) O dom de profetizar cumpriu um papel importante em fortalecer as congregações. — 1Co 14:3-5, 24, 25.
- *o discernimento de expressões inspiradas*: Estas palavras, que significam literalmente “discernimentos de espíritos”, se referem a um entendimento milagroso de expressões inspiradas. Esse dom provavelmente envolvia a capacidade de saber se uma expressão tinha sido inspirada por Deus ou se vinha de outra fonte. Essa habilidade com certeza foi importante para proteger a congregação contra falsos profetas. (2Co 11:3, 4; 1Jo 4:1) Ela também pode ter ajudado os apóstolos e anciãos em Jerusalém a determinar as partes da Lei que ainda precisavam ser consideradas como “coisas necessárias” para os cristãos. (At 15:19, 20, 28, 29) Os cristãos também precisaram desse dom para saber quais cartas e escritos deviam circular entre as congregações e para discernir quais se tornariam parte do cânon da Bíblia. Por exemplo, o apóstolo Pedro indicou que algumas das cartas de Paulo faziam parte das Escrituras inspiradas quando disse: “Os ignorantes e instáveis estão distorcendo [as cartas de Paulo], assim como fazem também com o restante das Escrituras.” (2Pe 3:16) O processo de seleção dos livros da Bíblia sem dúvida foi guiado pelo espírito de Deus, muito provavelmente usando irmãos que tinham o dom mencionado aqui. — 2Ti 3:16; veja o Glossário, “Cânon da Bíblia”; “Espírito”.
- *diversas línguas*: O dom de línguas possibilitava que o cristão pregasse as boas novas do Reino de Deus a pessoas que falavam línguas que ele não sabia. Por causa desse dom dado por Deus, os cristãos puderam compartilhar “as coisas magníficas de Deus” com muitos estrangeiros que tinham ido a Jerusalém para a Festividade de Pentecostes em 33 d.C. (At 2:1-12) Paulo depois lembrou aos coríntios que eles deviam usar esse dom de maneira ordeira, garantindo que o que eles falassem fosse interpretado e que aqueles que tinham o dom de línguas falassem um de cada vez. — 1Co 14:4, 5, 9, 27.
- *línguas*: Veja a nota de estudo em At 2:4.
- *a interpretação de línguas*: Com este dom milagroso, o cristão conseguia ser intérprete de uma língua que ele não sabia. Esse dom era muito útil quando outro cristão estava falando em línguas, já que os irmãos só seriam encorajados pela mensagem se entendessem o que estava sendo falado. Por isso, Paulo disse que quem falava em línguas devia permanecer em silêncio a não ser que alguém pudesse ser intérprete. Se a mensagem fosse interpretada, a congregação inteira seria encorajada. — 1Co 14:27, 28.
====

[[v46-12-11]]

^<<v46-12-11,11>>^ Mas todas essas coisas^&#42;1^ são realizadas pelo mesmo e único espírito, que distribui a cada um, individualmente, assim como quer.

[NOTE]
====
. Ou: “operações”.
====

[[v46-12-12]]

^<<v46-12-12,12>>^ Pois, assim como o corpo é um só, mas tem muitos membros, e todos os membros do corpo, embora muitos, são um só corpo, assim também é o Cristo.

[[v46-12-13]]

^<<v46-12-13,13>>^ Pois todos nós fomos batizados por um só espírito para formar um só corpo, quer judeus quer gregos, quer escravos quer livres, e a todos nós se deu de beber de um só espírito.

[[v46-12-14]]

^<<v46-12-14,14>>^ Pois, de fato, o corpo não é composto de um só membro, mas de muitos.

[[v46-12-15]]

^<<v46-12-15,15>>^ Se o pé dissesse: “Visto que não sou mão, não sou parte do corpo”, não é por isso que ele deixaria de ser parte do corpo.

[[v46-12-16]]

^<<v46-12-16,16>>^ E, se o ouvido dissesse: “Visto que não sou olho, não sou parte do corpo”, não é por isso que ele deixaria de ser parte do corpo.

[[v46-12-17]]

^<<v46-12-17,17>>^ Se o corpo inteiro fosse um olho, onde ficaria a audição? Se todo ele fosse um ouvido, onde ficaria o olfato?

[[v46-12-18]]

^<<v46-12-18,18>>^ Mas a verdade é que Deus dispôs cada um dos membros do corpo assim como lhe agradou.

[[v46-12-19]]

^<<v46-12-19,19>>^ Se todos fossem um só membro, onde estaria o corpo?

[[v46-12-20]]

^<<v46-12-20,20>>^ Mas o fato é que são muitos membros, porém um só corpo.

[[v46-12-21]]

^<<v46-12-21,21>>^ O olho não pode dizer à mão: “Não preciso de você”; nem a cabeça pode dizer aos pés: “Não preciso de vocês.”

[[v46-12-22]]

^<<v46-12-22,22>>^ Pelo contrário, os membros do corpo que parecem mais fracos são necessários,

[[v46-12-23]]

^<<v46-12-23,23>>^ e as partes do corpo que consideramos menos honrosas, nós cercamos de maior honra; assim as nossas partes menos atraentes são tratadas com mais decência,

[[v46-12-24]]

^<<v46-12-24,24>>^ ao passo que as nossas partes atraentes não precisam desse cuidado. Mas Deus formou^&#42;1^ o corpo desse modo, dando maior honra à parte que dela precisava,

[NOTE]
====
. Lit.: “misturou junto”.
====

[[v46-12-25]]

^<<v46-12-25,25>>^ para que não houvesse divisão no corpo, mas para que os membros tivessem o mesmo cuidado uns com os outros.

[TIP]
====
- *os membros tivessem o mesmo cuidado uns com os outros*: Lit.: “os membros estejam preocupados uns com os outros”. O verbo grego traduzido aqui como “ter cuidado” (merimnáo) também foi usado em 1Co 7:32, onde Paulo fala que um cristão solteiro “se preocupa com as coisas do Senhor”. (Veja a nota de estudo em 1Co 7:32.) O mesmo verbo aparece em 1Co 7:33, fazendo referência à preocupação amorosa que o marido tem pela esposa. Paulo também falou que ele tinha “ansiedade [em grego, mérimna, substantivo relacionado com merimnáo] por todas as congregações”. (2Co 11:28) Ele se preocupava muito com os cristãos e queria que todos continuassem sendo fiéis discípulos do Filho de Deus até o fim. Além disso, em Fil 2:20, Paulo usou merimnáo ao falar que Timóteo cuidaria genuinamente dos irmãos em Filipos. O fato de Paulo usar esse verbo aqui em 1Co 12:25 mostra que os membros da congregação cristã devem estar profundamente interessados no bem-estar espiritual, físico e material uns dos outros. — 1Co 12:26, 27; Fil 2:4.
====

[[v46-12-26]]

^<<v46-12-26,26>>^ Se um membro sofre, todos os outros membros sofrem com ele; se um membro é glorificado, todos os outros membros se alegram com ele.

[[v46-12-27]]

^<<v46-12-27,27>>^ Ora, vocês são o corpo de Cristo, e cada um de vocês, individualmente, é membro desse corpo.

[[v46-12-28]]

^<<v46-12-28,28>>^ E Deus estabeleceu os vários membros na congregação: primeiro, apóstolos; segundo, profetas; terceiro, instrutores; depois vêm obras poderosas; depois dons de curar; a prestação de ajuda; habilidades de liderança; diversas línguas.

[TIP]
====
- *obras poderosas*: Ou: “milagres”. — Veja a nota de estudo em 1Co 12:10.
- *habilidades de liderança*: A palavra grega usada aqui, kybérnesis, passa a ideia de “direção; condução; administração; governo”. Esse tipo de habilidade era necessário para cumprir a comissão que Jesus deu: “Façam discípulos de pessoas de todas as nações.” (Mt 28:19, 20) Para que isso acontecesse, alguns membros da congregação precisariam receber autoridade para dar início a novas congregações e para orientar as atividades de todas as congregações. (At 15:1, 2, 27-29; 16:4) Essa palavra grega está relacionada ao verbo kybernáo, que significa literalmente “pilotar (dirigir) um navio”. Um substantivo relacionado (kybernétes) aparece duas vezes nas Escrituras Gregas Cristãs e foi traduzido como “piloto” e “capitão de navio”. — At 27:11; Ap 18:17.
====

[[v46-12-29]]

^<<v46-12-29,29>>^ Será que todos são apóstolos? Será que todos são profetas? Será que todos são instrutores? Será que todos realizam obras poderosas?

[[v46-12-30]]

^<<v46-12-30,30>>^ Será que todos têm dons de curar? Será que todos falam em línguas? Será que todos são intérpretes?

[TIP]
====
- *intérpretes*: Ou: “tradutores”. — Veja a nota de estudo em 1Co 14:5.
====

[[v46-12-31]]

^<<v46-12-31,31>>^ Mas persistam em se empenhar pelos^&#42;1^ maiores dons. Contudo, ainda lhes mostrarei um caminho superior.

[NOTE]
====
. Ou: “persistam em buscar zelosamente os”.
====

'''

xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[&#60; Capítulo Anterior] | <<v46-12-0,Topo>> | xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[Próximo Capítulo &#62;]