include::./index.adoc[]

[[v45-15-0]]
=== A Carta aos Romanos, 15
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. COMO OS VERDADEIROS CRISTÃOS DEVEM VIVER (12:1–15:13)
* 1. Adorar a Deus de todo o coração e tratar bem os irmãos e as outras pessoas (12:1-21)
* Apresentem o seu corpo como sacrifício vivo, santo, com a sua faculdade de raciocínio (12:1, 2)
* Os cristãos têm dons diferentes, mas fazem parte de um só corpo (12:3-8)
* Amem e honrem os irmãos; sirvam a Jeová com zelo, perseverança e submissão (12:9-16)
* “Continue vencendo o mal com o bem” (12:17-21)
* 2. Os cristãos verdadeiros e o governo humano (13:1-7)
* Sujeição “às autoridades superiores”; elas atuam como servas de Deus (13:1-4)
* Deem às autoridades o que lhes é devido (13:5-7)
* 3. Cumprir a lei do amor e ficar despertos (13:8-14)
* Não devam nada a ninguém, a não ser amar uns aos outros; o amor cumpre a Lei (13:8-10)
* Andem decentemente como em pleno dia e imitem Jesus (13:11-14)
* 4. Empenhar-se pela união; o Reino de Deus significa justiça, paz e alegria (14:1–15:13)
* Não julguem uns aos outros (14:1-12)
* Não façam outros tropeçar (14:13-18)
* Empenhem-se pela paz e pelas coisas que edificam uns aos outros (14:19-23)
* Sigam o exemplo de Cristo, que não agradou a si mesmo (15:1-6)
* “Acolham uns aos outros”; as nações glorificarão a Deus (15:7-13)
* D. PAULO FALA DE SEU MINISTÉRIO E DE SEUS PLANOS FUTUROS (15:14-29)
* Paulo se ocupou na obra santa das boas novas de Deus (15:14-16)
* Paulo fala das atividades que realizou (15:17-21)
* Por não ter mais território virgem por perto, Paulo pretende ir para a Espanha, passando por Roma (15:22-24)
* Paulo está prestes a ir para Jerusalém com as contribuições da Macedônia e da Acaia (15:25-29)
* E. PEDIDO FINAL E SAUDAÇÕES (15:30–16:27)
* Paulo exorta os cristãos em Roma a orarem por ele (15:30-33)
* Paulo apresenta Febe, uma ministra da congregação em Cencreia (16:1, 2)
* Saudações de Paulo a irmãos específicos de Roma (16:3-16)
* Alerta contra divisões (16:17-19)
* Deus esmagará em breve a Satanás (16:20)
* Saudações dos colaboradores de Paulo (16:21-24)
* Glória a Deus, que é o único sábio, por meio de Jesus Cristo (16:25-27)
****

[[v45-15-1]]

^<<v45-15-1,1>>^ Mas nós, que somos fortes, devemos suportar as fraquezas dos que não são fortes, e não agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Que cada um de nós agrade ao seu próximo para o bem dele, para edificá-lo.

[[v45-15-3]]

^<<v45-15-3,3>>^ Pois nem mesmo o Cristo agradou a si mesmo, mas, assim como está escrito: “Os insultos daqueles que te insultam caem sobre mim.”

[[v45-15-4]]

^<<v45-15-4,4>>^ Pois todas as coisas escritas anteriormente foram escritas para a nossa instrução, a fim de que, por meio da nossa perseverança e por meio do consolo das Escrituras, tivéssemos esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ Que o Deus que dá perseverança e consolo lhes conceda terem entre si a mesma atitude que Cristo Jesus teve,

[[v45-15-6]]

^<<v45-15-6,6>>^ para que, unidos e com uma só voz, vocês glorifiquem ao Deus e Pai do nosso Senhor Jesus Cristo.

[TIP]
====
- *unidos e com uma só voz*: Lit.: “com uma [só] mente, com uma [só] boca”. Paulo orava para que seus irmãos se mantivessem unidos em pensamento e ação, assim como Jesus tinha orado para que houvesse união entre seus seguidores. (Jo 17:20-23; veja a nota de estudo em Jo 17:23.) Neste versículo, Paulo usa duas expressões que destacam a força que essa união deveria ter. A primeira delas, que foi traduzida aqui como “unidos”, foi usada várias vezes no livro de Atos para se referir à impressionante união que existia entre os cristãos do século 1 d.C. (At 1:14; 15:25, “de comum acordo”; 2:46, “unidos no mesmo propósito”; 4:24, “unidos”) A segunda expressão, traduzida aqui como “uma só voz”, mostra que Paulo queria que os cristãos judeus e não judeus da congregação de Roma unissem suas vozes para dar glória a Deus em perfeita harmonia.
====

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, acolham uns aos outros, assim como o Cristo também acolheu vocês, visando glória para Deus.

[TIP]
====
- *acolham*: Ou: “aceitem; recebam”. A palavra grega que aparece aqui passa a ideia de receber uma pessoa com bondade ou de modo hospitaleiro, como quando alguém recebe uma pessoa em sua casa ou a aceita em seu círculo de amigos. Essa mesma palavra grega também pode ser traduzida como “receber bondosamente” (Flm 17) ou “receber bem” (At 28:2).
====

[[v45-15-8]]

^<<v45-15-8,8>>^ Pois eu lhes digo que Cristo se tornou servo dos circuncisos para mostrar a veracidade de Deus e confirmar as promessas que Ele fez aos antepassados deles,

[TIP]
====
- *servo*: Ou: “ministro”. A Bíblia muitas vezes usa a palavra grega diákonos para se referir a uma pessoa que presta serviço a outros de modo humilde. (Veja a nota de estudo em Mt 20:26.) Aqui, essa palavra é usada para se referir a Cristo. Antes de vir para a Terra, Jesus já tinha servido a Jeová por incontáveis anos. Mas, depois que Jesus veio para a Terra e se batizou, ele passou a realizar um novo serviço, que envolvia cuidar das necessidades espirituais dos humanos pecadores. Como parte desse serviço, ele chegou até mesmo a dar sua vida como resgate. (Mt 20:28; Lu 4:16-21) Paulo diz que Jesus se tornou servo dos judeus circuncisos para mostrar a veracidade de Deus, porque, como parte de seu serviço, Jesus cumpriu promessas que Deus tinha feito aos antepassados deles. Entre elas, estava a promessa que Deus fez a Abraão de que todas as nações da Terra seriam abençoadas por meio do descendente dele. (Gên 22:17, 18) Essa promessa mostrava que o serviço de Jesus também beneficiaria pessoas das nações, que iriam ‘basear a sua esperança’ nele. — Ro 15:9-12.
====

[[v45-15-9]]

^<<v45-15-9,9>>^ e para que as nações glorificassem a Deus pela Sua misericórdia. Assim como está escrito: “É por isso que te reconhecerei abertamente entre as nações e ao teu nome cantarei louvores.”

[TIP]
====
- *Assim como está escrito*: Nesta passagem (Ro 15:9-12), Paulo cita as Escrituras Hebraicas quatro vezes, mostrando que já fazia muito tempo que Jeová tinha predito que pessoas das nações também o louvariam. Essas citações deixavam claro que não apenas os judeus, mas também os não judeus, se beneficiariam do serviço, ou ministério, de Cristo. Elas davam ainda mais motivo para que os irmãos da congregação de Roma, formada por cristãos tanto judeus como não judeus, seguissem o conselho de Paulo de ‘acolherem uns aos outros’. — Ro 15:7; veja a nota de estudo em Ro 1:17.
- *entre as nações*: Neste versículo, Paulo pelo visto está citando parte do Sal 18:49, que diz: “Te glorificarei entre as nações, ó Jeová.” (Em 2Sa 22:50, também existe uma frase bem parecida.) A tradução usada aqui no texto principal de Ro 15:9 tem o apoio de manuscritos muito antigos e confiáveis, mas alguns poucos manuscritos acrescentam as palavras “ó Senhor” depois da expressão “entre as nações”. Pelo visto, alguns copistas mais tarde aumentaram a citação para incluir a frase completa “entre as nações, ó Senhor”, refletindo a tradução da Septuaginta do Sal 18:49 (17:50, LXX) e de 2Sa 22:50.
====

[[v45-15-10]]

^<<v45-15-10,10>>^ E ele diz também: “Alegrem-se, nações, com o povo dele.”

[[v45-15-11]]

^<<v45-15-11,11>>^ E ainda: “Louvem a Jeová, todas as nações, e que todos os povos o louvem.”

[TIP]
====
- *Jeová*: Esta é uma citação do Sal 117:1. No texto hebraico original desse salmo, aparecem as quatro letras hebraicas que formam o nome de Deus (que equivalem a YHWH). — Veja os Apêndices A5 e C1.
====

[[v45-15-12]]

^<<v45-15-12,12>>^ E Isaías diz também: “Haverá a raiz de Jessé, aquele que surgirá para governar as nações; nele as nações basearão a sua esperança.”

[TIP]
====
- *a raiz de Jessé*: Aqui, Paulo está citando Is 11:10, conforme esse versículo foi traduzido na Septuaginta. Paulo usa essa citação, que fala sobre “as nações” basearem sua esperança na “raiz de Jessé”, para mostrar que pessoas das nações também fariam parte da congregação cristã. Jessé foi o pai de Davi. (Ru 4:17, 22; 1Sa 16:5-13) O texto de Is 11:10 predizia que o Messias seria chamado de “a raiz de Jessé”. (Compare com Ap 5:5, onde Jesus é chamado de “a raiz de Davi”; veja também Ap 22:16.) Na grande maioria das árvores e plantas, a raiz surge antes do tronco e dos ramos. Assim, poderia parecer mais lógico a profecia dizer que Jessé (ou seu filho Davi) era a raiz de onde Jesus viria, já que o Messias seria um descendente, e não um antepassado, de Jessé (ou de Davi). (Mt 1:1, 6, 16) Mas outras passagens da Bíblia ajudam a entender por que Jesus pode ser considerado a raiz de Jessé: (1) Visto que Jesus é imortal, é por meio dele que a linhagem de Jessé continua existindo. (Ro 6:9) (2) Jesus foi designado por Jeová como Juiz e Rei, o que o coloca em uma posição superior até mesmo à de seus antepassados. (Lu 1:32, 33; 19:12, 15; 1Co 15:25) (3) Davi chamou Jesus profeticamente de seu Senhor. (Sal 110:1; At 2:34-36) (4) Durante o Milênio, Jessé vai ser beneficiado pelo sacrifício de resgate de Jesus, e sua vida na Terra estará nas mãos de Jesus, que vai então exercer o papel de “Pai Eterno” de Jessé e de Davi. — Is 9:6.
====

[[v45-15-13]]

^<<v45-15-13,13>>^ Que o Deus que dá esperança encha vocês de toda alegria e paz por meio da sua confiança nele, para que transbordem^&#42;1^ de esperança pelo poder do espírito santo.

[NOTE]
====
. Ou: “tenham abundância”.
====

[[v45-15-14]]

^<<v45-15-14,14>>^ Pessoalmente, estou convencido quanto a vocês, meus irmãos, de que vocês mesmos também estão cheios de coisas boas, cheios de todo o conhecimento, e de que podem aconselhar^&#42;1^ uns aos outros.

[NOTE]
====
. Ou: “instruir”.
====

[[v45-15-15]]

^<<v45-15-15,15>>^ No entanto, eu lhes escrevi com bastante franqueza sobre alguns pontos, para que vocês se lembrem deles novamente. Faço isso por causa da bondade imerecida que me foi concedida por Deus

[[v45-15-16]]

^<<v45-15-16,16>>^ para que eu fosse servo de Cristo Jesus a favor das nações. Estou ocupado na obra santa das boas novas de Deus, a fim de que as nações sejam uma oferta aceitável, santificada com espírito santo.

[TIP]
====
- *servo*: Ou: “servidor público”. A palavra grega leitourgós vem das palavras gregas laós, “povo”, e érgon, “trabalho”. Ela era usada originalmente pelos gregos para se referir a alguém que prestava serviço para autoridades civis, geralmente às suas próprias custas, em benefício do povo. Esse tipo de serviço também existia entre os romanos. Na Bíblia, essa palavra foi usada na maioria das vezes para se referir a alguém que realizava um serviço considerado sagrado. A palavra relacionada leitourgía foi usada muitas vezes na Septuaginta para se referir aos “deveres” (Núm 7:5) dos sacerdotes e ao “serviço” (Núm 4:28; 1Cr 6:32 [6:17, LXX]) que eles prestavam no tabernáculo ou no templo em Jerusalém. Aqui, Paulo usa a palavra leitourgós para se referir a si mesmo, já que ele servia como “apóstolo para as nações”, ou seja, para os não judeus, proclamando as boas novas de Deus. (Ro 11:13) A pregação de Paulo trazia grandes benefícios para o povo, especialmente para as pessoas das nações.
- *ocupado na obra santa*: Esta é a única vez que o verbo hierourgéo aparece nas Escrituras Gregas Cristãs. Ele passa a ideia de estar ocupado em um serviço ou dever sagrado. A “obra santa” que Paulo estava realizando era proclamar as boas novas de Deus, os ensinos de Cristo, a pessoas de todas as nações. (Veja as notas de estudo em Ro 1:1,  9.) O fato de Paulo ter usado hierourgéo mostra que ele considerava essa obra como uma grande responsabilidade e como algo sagrado. Esse verbo está relacionado com o verbo hierateúo, que foi traduzido em Lu 1:8 como “servindo . . . como sacerdote”, e com a palavra hierón (“templo”), que aparece em Mt 4:5 e em muitos outros versículos. Talvez por isso Paulo tenha feito uma referência aos sacrifícios que eram feitos no templo, comparando as pessoas das nações que aceitavam as boas novas a uma oferta feita a Deus. Deus não apenas aceitava essa oferta, mas também a abençoava com seu espírito. — Ro 1:1, 16.
====

[[v45-15-17]]

^<<v45-15-17,17>>^ Portanto, tenho motivo para me orgulhar em Cristo Jesus no meu serviço a Deus.^&#42;1^

[NOTE]
====
. Ou: “quanto às coisas referentes a Deus”.
====

[[v45-15-18]]

^<<v45-15-18,18>>^ Pois não me atreverei a falar de coisa alguma a não ser daquilo que Cristo realizou por meu intermédio para que as nações fossem obedientes. Ele agiu por meio das minhas palavras e ações,

[[v45-15-19]]

^<<v45-15-19,19>>^ pelo poder de sinais e milagres e pelo poder do espírito de Deus; assim, desde Jerusalém e por todos os lados até o Ilírico, preguei cabalmente as boas novas a respeito do Cristo.

[TIP]
====
- *milagres*: Ou: “presságios”. — Veja a nota de estudo em At 2:19.
- *espírito de Deus*: Alguns manuscritos bem antigos dizem “espírito santo” ou apenas “espírito”, mas a tradução “espírito de Deus”, usada aqui no texto principal, tem o apoio de manuscritos muito antigos e confiáveis.
- *por todos os lados até o Ilírico*: Ou: “num circuito até o Ilírico”. Ilírico era o nome de uma província romana que ficava na parte noroeste da península Balcânica, na costa do mar Adriático. (Veja o Apêndice B13.) O nome Ilírico vem das tribos que moravam naquela região. As divisões e as fronteiras da província variaram bastante durante o domínio romano. Não é possível ter certeza se a palavra grega traduzida aqui como “até” significa que Paulo chegou a pregar no Ilírico ou se ele, na verdade, chegou apenas até a fronteira dessa província.
====

[[v45-15-20]]

^<<v45-15-20,20>>^ Desse modo, fiz o possível para não declarar as boas novas nos lugares onde o nome de Cristo já fosse conhecido, a fim de não construir sobre o alicerce de outra pessoa;

[[v45-15-21]]

^<<v45-15-21,21>>^ mas, assim como está escrito: “Aqueles que nunca tiveram notícia sobre ele verão, e os que não tinham ouvido entenderão.”

[[v45-15-22]]

^<<v45-15-22,22>>^ É por isso que fui muitas vezes impedido de ir visitar vocês.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas agora não tenho mais território virgem nestas regiões e por muitos^&#42;1^ anos estou ansioso de ir visitá-los.

[NOTE]
====
. Ou, possivelmente: “alguns”.
====

[TIP]
====
- *território virgem*: Paulo queria muito que a pregação das boas novas alcançasse mais pessoas. Por isso, ele desejava pregar em lugares onde as boas novas ainda não tinham chegado. (Compare com 2Co 10:15, 16.) No versículo seguinte, Paulo diz que pretendia levar seu trabalho missionário para o oeste, até a Espanha. Ele escreveu essas palavras no início de 56 d.C., perto do fim de sua terceira viagem missionária.
====

[[v45-15-24]]

^<<v45-15-24,24>>^ Por isso, quando eu viajar para a Espanha, espero vê-los e ser acompanhado por vocês parte do caminho, depois de primeiro ter desfrutado um pouco a companhia de vocês.

[TIP]
====
- *Espanha*: Paulo menciona a Espanha duas vezes em sua carta aos romanos: aqui e em Ro 15:28. Não se sabe ao certo se Paulo conseguiu realmente ir à Espanha. Mas Clemente de Roma, que escreveu por volta de 95 d.C., disse que Paulo viajou para “o extremo limite do O[este]”, o que talvez tenha incluído a Espanha. Se Paulo conseguiu visitar a Espanha, ele deve ter feito isso depois de ter sido solto de seu primeiro período de prisão em Roma (cerca de 61 d.C.) e antes de seu segundo período de prisão ali (cerca de 65 d.C.). Naquela época, a Espanha era governada pelos romanos e a maioria da população falava latim, e não grego. Paulo pelo visto considerava a Espanha como um “território virgem”. — Ro 15:23.
====

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas no momento estou de partida para Jerusalém a fim de servir os santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Pois os irmãos da Macedônia e os da Acaia partilharam de boa vontade suas coisas fazendo uma contribuição para os pobres entre os santos em Jerusalém.

[TIP]
====
- *Macedônia*: Veja o Glossário.
- *Acaia*: Veja a nota de estudo em At 18:12.
====

[[v45-15-27]]

^<<v45-15-27,27>>^ Sim, eles fizeram isso de boa vontade, e de fato eram devedores deles; pois, se as nações participaram das coisas espirituais deles, elas também têm o dever de servir a eles com suas coisas materiais.

[TIP]
====
- *eram devedores deles*: Ou: “tinham uma dívida com eles; tinham uma obrigação para com eles”. Nas Escrituras, a palavra grega para “devedor” e outras palavras relacionadas com dívidas podem se referir tanto a dívidas financeiras como a obrigações e deveres em geral. (Veja a nota de estudo em Ro 1:14.) Paulo destaca aqui que os cristãos não judeus estavam em dívida com os cristãos judeus de Jerusalém por causa dos benefícios espirituais que tinham recebido por meio deles. Assim, agora que esses cristãos judeus estavam passando necessidade, nada mais justo do que os cristãos não judeus ajudarem materialmente seus irmãos. — Ro 15:26.
====

[[v45-15-28]]

^<<v45-15-28,28>>^ Assim, depois que eu tiver terminado de fazer isso e tiver entregado a eles essa contribuição em segurança, partirei para a Espanha e visitarei vocês no caminho.

[TIP]
====
- *essa contribuição*: Lit.: “esse fruto”. Aqui, a palavra “fruto” foi usada com o sentido de “resultado; produto” e, pelo visto, se refere ao dinheiro que tinha sido coletado para os irmãos em Jerusalém.
====

[[v45-15-29]]

^<<v45-15-29,29>>^ Além disso, sei que, quando eu for visitá-los, chegarei com uma plena medida de bênçãos de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Eu os exorto, irmãos, por meio do nosso Senhor Jesus Cristo e por meio do amor do espírito, que vocês se esforcem comigo em orações a Deus por mim,

[[v45-15-31]]

^<<v45-15-31,31>>^ para que eu seja livrado dos descrentes na Judeia e para que meu serviço a favor de Jerusalém seja bem aceito pelos santos.

[TIP]
====
- *meu serviço*: Ou: “meu ministério”. Aqui, a palavra grega diakonía, muitas vezes traduzida como “ministério”, tem o sentido de “trabalho de prestar ajuda; serviço de ajuda”, assim como acontece em At 11:29; 12:25; 2Co 8:4 e 9:13. As congregações da Macedônia e da Acaia tinham participado em um “serviço de ajuda”, reunindo dinheiro para que Paulo levasse aos irmãos da Judeia que estavam passando necessidade. (2Co 8:1-4; 9:1, 2, 11-13) Uns poucos manuscritos bem antigos usam aqui a palavra grega doroforía, que se refere ao ato de trazer um presente, em vez de diakonía. Alguns estudiosos sugerem que essa mudança foi feita por um escriba na tentativa de deixar mais claro qual era o tipo de “serviço” de que Paulo estava falando. — Veja a nota de estudo em At 11:29.
====

[[v45-15-32]]

^<<v45-15-32,32>>^ Assim, pela vontade de Deus, eu os visitarei com alegria e serei reanimado junto com vocês.

[[v45-15-33]]

^<<v45-15-33,33>>^ Que o Deus que dá paz esteja com todos vocês. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]