include::./index.adoc[]

[[v45-14-0]]
=== A Carta aos Romanos, 14
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. COMO OS VERDADEIROS CRISTÃOS DEVEM VIVER (12:1–15:13)
* 1. Adorar a Deus de todo o coração e tratar bem os irmãos e as outras pessoas (12:1-21)
* Apresentem o seu corpo como sacrifício vivo, santo, com a sua faculdade de raciocínio (12:1, 2)
* Os cristãos têm dons diferentes, mas fazem parte de um só corpo (12:3-8)
* Amem e honrem os irmãos; sirvam a Jeová com zelo, perseverança e submissão (12:9-16)
* “Continue vencendo o mal com o bem” (12:17-21)
* 2. Os cristãos verdadeiros e o governo humano (13:1-7)
* Sujeição “às autoridades superiores”; elas atuam como servas de Deus (13:1-4)
* Deem às autoridades o que lhes é devido (13:5-7)
* 3. Cumprir a lei do amor e ficar despertos (13:8-14)
* Não devam nada a ninguém, a não ser amar uns aos outros; o amor cumpre a Lei (13:8-10)
* Andem decentemente como em pleno dia e imitem Jesus (13:11-14)
* 4. Empenhar-se pela união; o Reino de Deus significa justiça, paz e alegria (14:1–15:13)
* Não julguem uns aos outros (14:1-12)
* Não façam outros tropeçar (14:13-18)
* Empenhem-se pela paz e pelas coisas que edificam uns aos outros (14:19-23)
* Sigam o exemplo de Cristo, que não agradou a si mesmo (15:1-6)
* “Acolham uns aos outros”; as nações glorificarão a Deus (15:7-13)
****

[[v45-14-1]]

^<<v45-14-1,1>>^ Acolham o homem que tem fraquezas na fé, mas não façam julgamentos sobre opiniões divergentes.

[[v45-14-2]]

^<<v45-14-2,2>>^ Um homem tem fé para comer de tudo, mas o homem que é fraco só come verduras.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem come não menospreze aquele que não come, e quem não come não julgue aquele que come, pois Deus o acolheu.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem é você para julgar o servo de outro? É para o seu próprio senhor que ele fica de pé ou cai. De fato, ele ficará de pé, pois Jeová pode fazê-lo ficar de pé.

[TIP]
====
- *Quem é você para julgar o servo de outro?*: Nesta passagem (Ro 14:1-12), Paulo deixa claro que os cristãos não devem julgar uns aos outros em assuntos de consciência. Os cristãos da congregação em Roma tinham formações culturais diferentes e alguns deles estavam julgando seus irmãos por coisas que não iam contra nenhum princípio bíblico. O versículo anterior (Ro 14:3) explica que ‘Deus acolheu’ tanto “aquele que come” como “aquele que não come”. Assim, a pergunta que Paulo faz aqui no versículo 4 era um lembrete para os cristãos de que, quando eles julgavam um irmão, eles estavam julgando alguém que tinha o apoio de Jeová. Paulo usa aqui o exemplo de um servo e seu senhor. Apenas o senhor tem o direito de criar regras sobre o que o servo pode ou não fazer, de determinar as tarefas que ele precisa realizar e de decidir se vai continuar com ele ou se vai mandá-lo embora. Se outra pessoa tentasse tomar essas decisões, o senhor do servo teria todo o direito de dizer a ela: ‘Quem você pensa que é?’ De forma parecida, cada cristão precisa prestar contas a Deus, o seu Senhor, por suas decisões em assuntos de consciência. Já que todos os cristãos pertencem apenas a Deus, nenhum deles tem o direito de julgar seu irmão.
- *Jeová*: Muitos manuscritos gregos usam aqui a expressão “o Senhor” (ho Kýrios). Mas, como explicado no Apêndice C1, há bons motivos para acreditar que o nome de Deus aparecia no texto original deste versículo e que mais tarde foi substituído pelo título “Senhor”. O contexto mostra que Paulo está se referindo a Jeová Deus. Em Ro 14:1-12, Paulo está falando sobre a importância de não julgar outros em assuntos de consciência. Em Ro 14:10, ele diz que todos vão ‘comparecer perante o tribunal de Deus’. Depois, em Ro 14:11, para apoiar seu argumento, Paulo cita parte de Is 45:23, onde o contexto mostra que é Jeová Deus quem está falando (Is 45:18-22), e pelo visto inclui também parte de Is 49:18, onde aparece o nome de Deus. (Veja a nota de estudo em Ro 14:11.) Paulo conclui seu raciocínio em Ro 14:12, dizendo: “Assim, cada um de nós prestará contas de si mesmo a Deus.” Dessa forma, tanto o contexto deste versículo como a passagem das Escrituras Hebraicas citada por Paulo apoiam o uso do nome Jeová aqui no texto principal. — Veja o Apêndice C3 (introdução e Ro 14:4).
- *fazê-lo ficar de pé*: Ou seja, Jeová pode fazer com que ele tenha bons resultados e continue tendo sua aprovação. A mesma palavra grega que aparece aqui foi usada em Lu 21:36, onde ela também passa a ideia de receber aprovação.
====

[[v45-14-5]]

^<<v45-14-5,5>>^ Uma pessoa considera um dia mais importante que outro, ao passo que outra pessoa considera todos os dias iguais; que cada um esteja plenamente convencido na sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem guarda o dia, guarda-o para Jeová. E quem come, come para Jeová, pois agradece a Deus; e quem não come, deixa de comer para Jeová, e mesmo assim agradece a Deus.

[TIP]
====
- *Jeová*: Nos manuscritos gregos disponíveis, a palavra “Senhor” (Kýrios, sem o artigo definido no texto grego) aparece três vezes neste versículo. Mas, como explicado no Apêndice C1, há motivos para acreditar que o nome de Deus aparecia no texto original deste versículo e que mais tarde foi substituído pelo título “Senhor”. Por isso, o nome “Jeová” é usado aqui no texto principal. — Veja o Apêndice C3 (introdução e Ro 14:6).
====

[[v45-14-7]]

^<<v45-14-7,7>>^ De fato, nenhum de nós vive somente para si mesmo, e ninguém morre somente para si mesmo.

[[v45-14-8]]

^<<v45-14-8,8>>^ Pois, se vivemos, vivemos para Jeová; se morremos, morremos para Jeová. Portanto, quer vivamos, quer morramos, pertencemos a Jeová.

[TIP]
====
- *Jeová*: Nos manuscritos gregos disponíveis, a palavra “Senhor” (Kýrios, com o artigo definido no texto grego) aparece três vezes neste versículo. Mas, como explicado no Apêndice C1, há motivos para acreditar que o nome de Deus aparecia no texto original deste versículo e que mais tarde foi substituído pelo título “Senhor”. Por isso, o nome “Jeová” é usado aqui no texto principal. — Veja o Apêndice C3 (introdução e Ro 14:8).
====

[[v45-14-9]]

^<<v45-14-9,9>>^ Pois com este objetivo Cristo morreu e voltou a viver: para ser Senhor tanto dos mortos como dos vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Mas por que você julga o seu irmão? E você, por que menospreza o seu irmão? Pois todos nós compareceremos perante o tribunal de Deus.

[[v45-14-11]]

^<<v45-14-11,11>>^ Porque está escrito: “‘Tão certo como eu vivo’, diz Jeová, ‘diante de mim todo joelho se dobrará, e toda língua reconhecerá abertamente a Deus’.”

[TIP]
====
- *diz Jeová*: Aqui, Paulo está citando Is 45:23, onde o contexto deixa claro que é Jeová quem está falando. (Is 45:18-22) Mas as palavras “diz Jeová” não aparecem em Is 45:23. Estudiosos sugerem que Paulo pode ter incluído em sua citação o texto de Is 49:18, que diz: “‘Tão certo como eu vivo’, diz Jeová.” Outra possibilidade é que ele tenha incluído as palavras “diz Jeová” apenas para tornar claro quem estava falando. Se esse foi o caso, ele pode ter sido influenciado por um dos muitos versículos das Escrituras Hebraicas que usam essas mesmas palavras ou palavras parecidas. — Núm 14:28; Je 22:24; 46:18 (26:18, LXX); Ez 5:11; 14:16; 16:48; 17:16; 18:3; 20:31, 33; Sof 2:9.
====

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, cada um de nós prestará contas de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto, não julguemos mais uns aos outros, mas, em vez disso, estejam determinados a não pôr uma pedra de tropeço ou um obstáculo diante de um irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ (Sei e estou convencido no Senhor Jesus que nada é impuro em si mesmo; somente quando alguém considera algo como impuro, então para ele é impuro.)

[[v45-14-15]]

^<<v45-14-15,15>>^ Pois, se o seu irmão se ofende por causa de um alimento, você não está mais andando de acordo com o amor. Não arruíne,^&#42;1^ pelo seu alimento, aquele pelo qual Cristo morreu.

[NOTE]
====
. Ou: “Não destrua”.
====

[[v45-14-16]]

^<<v45-14-16,16>>^ Portanto, não deixem que se fale mal do bem que vocês fazem.

[[v45-14-17]]

^<<v45-14-17,17>>^ Pois o Reino de Deus não tem a ver com^&#42;1^ comida e bebida, mas com^&#42;2^ justiça, paz e alegria no espírito santo.

[NOTE]
====
. Lit.: “não é”.
. Lit.: “mas é”.
====

[[v45-14-18]]

^<<v45-14-18,18>>^ Pois quem trabalha dessa forma como escravo para Cristo agrada a Deus e tem a aprovação dos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Assim, empenhemo-nos pelas coisas que promovem a paz e pelas coisas que edificam uns aos outros.

[[v45-14-20]]

^<<v45-14-20,20>>^ Parem de demolir a obra de Deus só por causa do alimento. É verdade que todas as coisas são puras; mas é prejudicial^&#42;1^ para o homem comer se isso for causar tropeço.

[NOTE]
====
. Ou: “errado”.
====

[[v45-14-21]]

^<<v45-14-21,21>>^ É melhor não comer carne, nem beber vinho, nem fazer nada que leve o seu irmão a tropeçar.

[[v45-14-22]]

^<<v45-14-22,22>>^ A fé que você tem, guarde-a para si diante de Deus. Feliz é aquele que não condena a si mesmo por aquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas, se alguém tem dúvidas e come, já está condenado, porque não come com base na fé. E tudo o que não se baseia na fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]