include::./index.adoc[]

[[v45-12-0]]
=== A Carta aos Romanos, 12
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* C. COMO OS VERDADEIROS CRISTÃOS DEVEM VIVER (12:1–15:13)
* 1. Adorar a Deus de todo o coração e tratar bem os irmãos e as outras pessoas (12:1-21)
* Apresentem o seu corpo como sacrifício vivo, santo, com a sua faculdade de raciocínio (12:1, 2)
* Os cristãos têm dons diferentes, mas fazem parte de um só corpo (12:3-8)
* Amem e honrem os irmãos; sirvam a Jeová com zelo, perseverança e submissão (12:9-16)
* “Continue vencendo o mal com o bem” (12:17-21)
* 2. Os cristãos verdadeiros e o governo humano (13:1-7)
* Sujeição “às autoridades superiores”; elas atuam como servas de Deus (13:1-4)
* Deem às autoridades o que lhes é devido (13:5-7)
* 3. Cumprir a lei do amor e ficar despertos (13:8-14)
* Não devam nada a ninguém, a não ser amar uns aos outros; o amor cumpre a Lei (13:8-10)
* Andem decentemente como em pleno dia e imitem Jesus (13:11-14)
* 4. Empenhar-se pela união; o Reino de Deus significa justiça, paz e alegria (14:1–15:13)
* Não julguem uns aos outros (14:1-12)
* Não façam outros tropeçar (14:13-18)
* Empenhem-se pela paz e pelas coisas que edificam uns aos outros (14:19-23)
* Sigam o exemplo de Cristo, que não agradou a si mesmo (15:1-6)
* “Acolham uns aos outros”; as nações glorificarão a Deus (15:7-13)
****

[[v45-12-1]]

^<<v45-12-1,1>>^ Portanto, eu lhes suplico, irmãos, pelas compaixões de Deus, que apresentem o seu corpo como sacrifício vivo, santo e aceitável a Deus, prestando assim um serviço sagrado com a sua faculdade de raciocínio.

[TIP]
====
- *Portanto*: Tudo indica que aqui Paulo usa esta palavra para fazer uma ligação entre o que ele tinha dito antes em sua carta com o que ele estava para dizer. Em outras palavras, Paulo está dizendo: “Levando em conta o que eu acabei de explicar, eu suplico a vocês que façam o que eu vou lhes dizer agora.” Antes, Paulo tinha falado sobre a oportunidade que tanto judeus como não judeus receberam de serem declarados justos pela fé, não por obras, e de reinarem junto com Cristo. (Ro 1:16; 3:20-24; 11:13-36) Começando no capítulo 12, Paulo incentiva os cristãos a serem gratos e a mostrarem sua fé e gratidão por serem obedientes a Deus e colocarem os interesses de Deus e dos outros à frente dos seus.
- *irmãos*: Veja a nota de estudo em Ro 1:13.
- *apresentem o seu corpo*: Debaixo da Lei mosaica, os israelitas abatiam animais e ofereciam os animais mortos como sacrifício. Assim, cada sacrifício podia ser oferecido uma única vez. Por outro lado, o sacrifício que os cristãos fazem é um sacrifício vivo. Eles apresentam seu corpo, ou seja, todo o seu ser, de forma contínua. Esse “sacrifício” inclui a mente, o coração e a força da pessoa. Ele envolve total dedicação e influencia todos os aspectos da vida. Paulo acrescenta que esse sacrifício precisa ser santo e aceitável a Deus. Ele talvez estivesse fazendo referência ao fato de que, de acordo com a Lei, alguns sacrifícios eram considerados inaceitáveis, como os de animais mancos ou com outros defeitos graves. (Le 22:19, 20; De 15:21; Mal 1:8, 13) De forma parecida, para que o sacrifício dos cristãos seja aceitável a Deus, eles precisam levar uma vida limpa e pura aos olhos dele.
- *um serviço sagrado*: Ou: “uma adoração”. O substantivo grego que aparece aqui, latreía, se refere a um ato de adoração. Nas Escrituras Gregas Cristãs, esse substantivo às vezes é usado para se referir à adoração que os judeus prestavam de acordo com a Lei mosaica. (Ro 9:4; He 9:1, 6) Mas, aqui, Paulo usa latreía para se referir à adoração prestada pelos cristãos. O verbo grego relacionado, latreúo (“prestar serviço sagrado”), é usado tanto para se referir à adoração prestada pelos judeus (Lu 2:37; He 8:5; 9:9) como à adoração prestada pelos cristãos (Fil 3:3; 2Ti 1:3; He 9:14; Ap 7:15). Em Ro 1:9, Paulo mostra que a pregação das ‘boas novas a respeito do Filho’ de Deus era uma parte importante de seu serviço sagrado.
- *com a sua faculdade de raciocínio*: A palavra grega traduzida aqui como “faculdade de raciocínio” é logikós. Aqui, ela passa a ideia de um serviço prestado de maneira “lógica”, “racional” ou “inteligente”. Um léxico diz que essa palavra se refere a algo que foi “avaliado com atenção, cuidadosamente pensado”. Na vida, o cristão precisa muitas vezes avaliar com cuidado os princípios da Bíblia. Ao tomar suas decisões, ele precisa entender como os princípios bíblicos se relacionam uns com os outros e como eles se aplicam em cada situação. Dessa forma, ele usa a faculdade, ou capacidade, de raciocínio que Jeová lhe deu para tomar decisões equilibradas que vão agradar a Jeová e ter as bênçãos dele. Para os judeus que tinham se tornado cristãos, adorar a Deus desse modo era uma grande mudança, já que eles estavam acostumados a prestar adoração seguindo as muitas regras da tradição judaica.
====

[[v45-12-2]]

^<<v45-12-2,2>>^ E parem de se amoldar a este mundo, mas sejam transformados, renovando a sua mente, a fim de comprovar por si mesmos a boa, aceitável e perfeita vontade de Deus.

[TIP]
====
- *parem de se amoldar a*: A palavra grega traduzida aqui como “se amoldar a” passa a ideia de “dar forma a algo seguindo um modelo ou molde”. O tempo verbal que Paulo usa aqui ao falar com os cristãos ungidos da congregação em Roma indica que ele estava se referindo a interromper uma ação que já estava em andamento. As palavras dele dão a entender que alguns cristãos ali ainda estavam sendo influenciados pelo mundo daquela época. (Ro 1:7) Quando Paulo escreveu aos cristãos em Roma por volta de 56 d.C., esse mundo envolvia os valores, costumes, comportamentos e estilos típicos do mundo romano. — Veja a nota de estudo em mundo neste versículo.
- *mundo*: Ou: “sistema de coisas”. A palavra grega usada aqui, aión, tem o sentido básico de “época”. Ela pode se referir também a uma situação existente ou a características marcantes de certa época ou período. Aqui, ela foi usada nesse último sentido e se refere aos valores, costumes, comportamentos, opiniões, estilos e outras características de uma determinada época. — Veja o Glossário, “Sistema(s) de coisas”.
- *sejam transformados, renovando a sua mente*: O verbo grego traduzido aqui como “sejam transformados” é metamorfóo. (Esse verbo deu origem à palavra portuguesa “metamorfose” e a palavras equivalentes em muitos outros idiomas.) A palavra grega traduzida aqui como “mente” tem o sentido básico de “capacidade de pensar”, mas também pode se referir às opiniões ou à maneira de pensar de uma pessoa. A expressão ‘renovar a mente’ indica que a mudança feita pela pessoa envolveria mudar seus pensamentos, intenções, sentimentos e desejos. O fato de essa expressão ter sido usada junto com o verbo metamorfóo mostra o quanto essa mudança é profunda. Esse verbo foi usado em Mt 17:2 e Mr 9:2, que falam que Jesus “foi transfigurado”. (Veja a nota de estudo em Mt 17:2.) A transfiguração de Jesus não foi uma mudança superficial. Pelo contrário, foi uma mudança tão completa que ele, que ainda não tinha assumido seu papel de Rei do “Reino de Deus”, podia ser descrito como já tendo “vindo em poder”. (Mr 9:1, 2) O verbo metamorfóo também foi usado em 2Co 3:18, onde ele se refere à transformação em sentido espiritual que é feita pelos cristãos ungidos. Assim, quando Paulo incentivou os cristãos a renovarem sua mente, ele estava falando de um processo contínuo de transformação que leva a pessoa a mudar completamente sua maneira de pensar e a ver as coisas assim como Deus vê.
- *comprovar por si mesmos*: A palavra grega traduzida aqui como “comprovar” é dokimázo. Ela passa a ideia de “comprovar por meio de teste” e muitas vezes se refere a um teste que tem um resultado positivo, que leva à aprovação. Em 1Co 11:28, a palavra dokimázo foi traduzida como “aprove”. Em algumas Bíblias, essa palavra é traduzida como “verificar; discernir”. Paulo não estava aconselhando os cristãos a serem céticos, duvidando de tudo, mas também não queria que eles tivessem uma fé cega. Na verdade, ele estava incentivando os cristãos a testarem, no bom sentido, as ordens de Deus, com o objetivo de entender e aplicar essas ordens e de sentir os bons resultados delas em sua vida. Quando os cristãos fazem isso, eles provam a si mesmos que a “vontade de Deus” é boa e perfeita e que viver de acordo com ela é a melhor maneira de se viver.
====

[[v45-12-3]]

^<<v45-12-3,3>>^ Pois, por meio da bondade imerecida que me foi concedida, digo a cada um de vocês que não pense de si mesmo mais do que é necessário pensar, mas que cada um pense de um modo que revele bom senso, conforme a medida de fé que Deus lhe deu.^&#42;1^

[NOTE]
====
. Ou: “repartiu; distribuiu”.
====

[[v45-12-4]]

^<<v45-12-4,4>>^ Pois, assim como temos muitos membros em um só corpo, mas os membros não têm todos a mesma função,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim também nós, embora muitos, somos um só corpo em união com Cristo, mas, individualmente, somos membros que pertencem uns aos outros.

[[v45-12-6]]

^<<v45-12-6,6>>^ Temos dons que diferem segundo a bondade imerecida que nos foi concedida; sendo assim, se o dom é o de profecia, profetizemos conforme a nossa fé;

[[v45-12-7]]

^<<v45-12-7,7>>^ se é o de servir, sirvamos;^&#42;1^ aquele que tem o dom do ensino, que ensine;

[NOTE]
====
. Ou: “se é um ministério, ministremos”.
====

[[v45-12-8]]

^<<v45-12-8,8>>^ aquele que tem o dom de encorajar, que encoraje; aquele que distribui, faça-o generosamente; aquele que preside, faça-o com diligência;^&#42;1^ aquele que mostra misericórdia, faça-o com alegria.

[NOTE]
====
. Ou: “seriedade”.
====

[TIP]
====
- *encorajar*: Ou: “exortar”. O verbo grego que aparece aqui, parakaléo, significa literalmente “chamar para o seu lado”. Esse verbo é bem abrangente e pode passar a ideia de “encorajar” (At 11:23; 14:22; 15:32; 1Te 5:11; He 10:25), de “consolar” (2Co 1:4; 2:7; 7:6; 2Te 2:17) e, em alguns contextos, de “exortar”, ou dar fortes conselhos (At 2:40; Ro 15:30; 1Co 1:10; Fil 4:2; 1Te 5:14; 2Ti 4:2; Tit 1:9, nota de rodapé). O fato de parakaléo poder ser traduzido tanto como “exortar” quanto como “encorajar” e “consolar” indica que os cristãos não deveriam nunca exortar alguém de maneira dura ou desamorosa.
- *encoraje*: Ou: “exorte”. O substantivo grego paráklesis, traduzido aqui como “encoraje”, está relacionado com o verbo parakaléo, que significa literalmente “chamar para o seu lado”. Esse substantivo muitas vezes passa a ideia de “encorajamento” (At 13:15; Fil 2:1) ou “consolo” (Ro 15:4; 2Co 1:3, 4; 2Te 2:16). Assim como acontece com o verbo parakaléo (que também aparece neste versículo), o substantivo paráklesis pode passar a ideia de “exortação” e foi traduzido assim em alguns versículos. (1Te 2:3; 1Ti 4:13; He 12:5) O fato de essas duas palavras gregas poderem passar a ideia tanto de “exortação” como de “encorajamento” e “consolo” indica que os cristãos não deveriam nunca exortar alguém de maneira dura ou desamorosa.
- *distribui*: Ou: “contribui”. O verbo grego que aparece aqui também é traduzido como “transmitir” (Ro 1:11; 1Te 2:8), “partilhar” (Lu 3:11) e “repartir” (Ef 4:28).
- *aquele que preside*: Ou: “aquele que toma a liderança”. A palavra grega proístemi significa literalmente “posicionar-se diante de (em frente de)” e tem o sentido de “liderar; conduzir; dirigir; mostrar interesse em; cuidar de” outras pessoas.
====

[[v45-12-9]]

^<<v45-12-9,9>>^ Que o amor de vocês seja sem hipocrisia. Abominem o que é mau; agarrem-se ao que é bom.

[TIP]
====
- *Abominem*: Esta é a única vez que a palavra grega apostygéo aparece nas Escrituras Gregas Cristãs. Ela é a forma intensificada de um verbo grego que significa “odiar” e, por isso, tem o sentido de “odiar intensamente (fortemente)”. Ela passa a ideia de um forte sentimento de aversão ou repugnância.
- *agarrem-se*: O verbo grego usado aqui, kolláo, significa literalmente “colar”. Neste versículo, ele é usado em sentido figurado. O cristão que tem amor sem hipocrisia, ou seja, amor verdadeiro, cria uma ligação extremamente forte com o que é bom. Assim, aquilo que é bom se torna uma parte inseparável de sua personalidade. Essa mesma palavra grega foi usada para se referir à forte ligação que deve existir entre marido e esposa. — Veja a nota de estudo em Mt 19:5.
====

[[v45-12-10]]

^<<v45-12-10,10>>^ Com amor fraternal, tenham ternos sentimentos uns pelos outros. Tomem a iniciativa em honrar uns aos outros.

[TIP]
====
- *amor fraternal*: A palavra grega que aparece aqui, filadelfía, significa literalmente “amor por um irmão”. Paulo usa essa palavra três vezes: aqui, em 1Te 4:9 e em He 13:1. Pedro também usa essa palavra três vezes em suas cartas: uma vez em 1Pe 1:22 e duas vezes em 2Pe 1:7. O fato de Paulo e Pedro terem usado essa palavra para se referir ao relacionamento entre cristãos indica que esse relacionamento deve ser tão achegado, forte e amoroso quanto o que existe entre os membros de uma família.
- *ternos sentimentos*: A palavra grega que aparece aqui, filóstorgos, é formada por duas palavras ligadas a amor e afeto: a raiz, stérgo, que se refere ao amor que existe naturalmente dentro da família, e uma palavra relacionada com fílos, que se refere a um amigo achegado. (Jo 15:13-15) Juntas, essas duas palavras passam a ideia de um forte amor, como o amor entre os membros de uma família. Na verdade, tanto a palavra filóstorgos quanto a palavra filadelfía (que foi traduzida como “amor fraternal” neste versículo) se referem a esse amor que costuma existir na família. Era esse tipo de amor que Paulo estava incentivando os cristãos a mostrarem uns pelos outros. — Veja a nota de estudo em amor fraternal neste versículo.
- *Tomem a iniciativa*: Esta é a única vez que a palavra grega proegéomai aparece nas Escrituras Gregas Cristãs. Ela significa literalmente “ir antes” e aqui se refere a um forte desejo de honrar outros. Nas culturas grega, judaica e romana do século 1 d.C., as pessoas em geral faziam de tudo para serem honradas. (Lu 20:46) Mas, aqui, Paulo fala que os cristãos deviam fazer exatamente o contrário, ou seja, eles deviam fazer de tudo para honrar e respeitar os outros. Na verdade, alguns sugerem que essa expressão passa a ideia de que os cristãos deviam tentar superar uns aos outros em honrar o próximo.
====

[[v45-12-11]]

^<<v45-12-11,11>>^ Sejam diligentes, não preguiçosos.^&#42;1^ Sejam fervorosos no espírito. Trabalhem como escravos para Jeová.

[NOTE]
====
. Ou: “Não sejam preguiçosos nas suas atividades.”
====

[TIP]
====
- *Sejam diligentes*: Ou: “Sejam trabalhadores”. A palavra grega traduzida aqui como “diligentes”, spoudé, significa literalmente “rapidez de movimento ou ação; pressa; velocidade”. (Lu 1:39) Mas em muitos contextos ela passa a ideia de “seriedade; prontidão; disposição; zelo” ou de “levar a sério uma obrigação”. Essa palavra aparece em Ro 12:8 na expressão “faça-o com diligência”. Ela também foi traduzida como “diligência” em He 6:11 e aparece em 2Pe 1:5 na expressão “façam todo o esforço possível”. O verbo relacionado spoudázo foi traduzido como “sejam . . . diligentes” (2Pe 1:10), “faça(m) o máximo” (2Ti 2:15; 2Pe 3:14) e “faça todo o possível” (2Ti 4:9, 21).
- *Sejam fervorosos no espírito*: A palavra grega traduzida aqui como “fervorosos” significa literalmente “ferver”. Neste versículo, ela é usada como uma metáfora e passa a ideia de transbordar ou irradiar zelo e entusiasmo por causa da ação do “espírito” (em grego, pneúma) de Deus, sua força ativa. Esse espírito pode motivar a pessoa a fazer as coisas de acordo com a vontade de Jeová e dar a ela o poder para isso. (Veja a nota de estudo em Mr 1:12.) Além disso, o “fervor” causado pelo espírito santo de Deus também pode atuar no espírito (a força que vem do coração figurativo) da pessoa, fazendo com que ela fique cheia de zelo e entusiasmo pelo que é certo. Alguns estudiosos acreditam que a expressão grega traduzida aqui como “fervorosos no espírito” tenha sido usada simplesmente como uma expressão idiomática que passa a ideia de ser muito disposto e cheio de entusiasmo. Mas a tradução usada no texto principal deste versículo favorece o entendimento de que o “espírito” mencionado aqui seja o espírito santo de Deus. — Para uma explicação sobre alguns princípios de tradução da Bíblia que se aplicam à expressão grega traduzida aqui como “fervorosos no espírito”, veja o Apêndice A1.
- *Trabalhem como escravos para*: Ou: “Sirvam a”. O verbo grego que aparece aqui, douleúo, se refere a trabalhar como escravo, ou seja, como alguém que tem um dono a quem deve obedecer. Esse mesmo verbo foi usado em Mt 6:24 (veja a nota de estudo), onde Jesus explicou que os cristãos não podem ser escravos de Deus e, ao mesmo tempo, das Riquezas. Em alguns versículos da Septuaginta, esse verbo foi usado para traduzir expressões hebraicas que, assim como aqui, incentivam a “servir a Jeová” e que, no texto hebraico original, contêm o Tetragrama. — 1Sa 12:20; Sal 2:11; 100:2 (99:2, LXX); 102:22 (101:23, LXX).
- *Jeová*: Os manuscritos gregos disponíveis hoje dizem “para o Senhor” (toi Kyríoi) aqui. Mas, como explicado no Apêndice C1, há bons motivos para acreditar que o nome de Deus aparecia no texto original deste versículo e que mais tarde foi substituído pelo título “Senhor”. Por isso, o nome “Jeová” é usado aqui no texto principal. — Veja o Apêndice C3 (introdução e Ro 12:11).
====

[[v45-12-12]]

^<<v45-12-12,12>>^ Alegrem-se na esperança. Perseverem sob tribulação. Perseverem em oração.

[[v45-12-13]]

^<<v45-12-13,13>>^ Partilhem com os santos o que vocês têm, segundo as necessidades deles. Sempre mostrem hospitalidade.

[TIP]
====
- *Sempre mostrem hospitalidade*: A expressão grega que aparece aqui poderia ser traduzida literalmente como “persigam a hospitalidade; corram atrás da hospitalidade”. Assim, Paulo mostra que os cristãos não devem ser hospitaleiros apenas quando outros lhes pedem ajuda. Em vez disso, Paulo incentiva os cristãos a “perseguir” a hospitalidade, ou seja, a tomar a iniciativa de mostrar essa qualidade com frequência. A palavra grega para “hospitalidade” (filoxenía) significa literalmente “amor (afeição) a estranhos”. Isso indica que a pessoa não deve ser hospitaleira apenas com seus amigos mais próximos. Paulo também usa essa palavra em He 13:2, onde ele pelo visto está se referindo aos relatos registrados nos capítulos 18 e 19 de Gênesis sobre Abraão e Ló. Por terem sido hospitaleiros com estranhos, eles, sem saber, receberam anjos. O texto de Gên 18:1-8 fala que Abraão correu para cuidar de seus convidados. O adjetivo relacionado filóxenos aparece três vezes nas Escrituras Gregas Cristãs, sempre em contextos que incentivam os cristãos a mostrar hospitalidade. — 1Ti 3:2; Tit 1:8; 1Pe 4:9.
====

[[v45-12-14]]

^<<v45-12-14,14>>^ Abençoem os que perseguem vocês; abençoem, e não amaldiçoem.

[[v45-12-15]]

^<<v45-12-15,15>>^ Alegrem-se com os que se alegram; chorem com os que choram.

[[v45-12-16]]

^<<v45-12-16,16>>^ Tenham para com os outros a mesma atitude que vocês têm para consigo mesmos; não fixem a mente em coisas grandiosas,^&#42;1^ mas deixem-se guiar pelas coisas humildes. Não sejam sábios aos seus próprios olhos.

[NOTE]
====
. Ou: “não cultivem ideias grandiosas; não sejam orgulhosos”.
====

[[v45-12-17]]

^<<v45-12-17,17>>^ Não retribuam a ninguém mal com mal. Preocupem-se com o que é bom aos olhos de todas as pessoas.

[TIP]
====
- *aos olhos de todas as pessoas*: Ou: “do ponto de vista de todos os homens; diante de todos os homens”. Aqui, a palavra grega ánthropos (“homem; humano”) se refere tanto a homens como a mulheres.
====

[[v45-12-18]]

^<<v45-12-18,18>>^ Se possível, no que depender de vocês, sejam pacíficos com todos.

[[v45-12-19]]

^<<v45-12-19,19>>^ Não se vinguem, amados, mas deem lugar à ira; pois está escrito: “‘A vingança é minha; eu retribuirei’, diz Jeová.”

[TIP]
====
- *deem lugar à ira*: O contexto mostra que a “ira” mencionada aqui é a ira de Deus. Na sequência do versículo, Paulo cita as palavras de Deus registradas em Deuteronômio: “Minha é a vingança e a retribuição.” (De 32:19-35) Apesar de o texto grego de Ro 12:19 dizer apenas “ira”, muitos tradutores incluíram as palavras “de Deus” para passar o sentido correto. Assim, pelo visto a ideia deste versículo é: ‘Em vez de ficarem irados, deixem que Deus fique irado. Deixem que Deus decida de quem ele vai se vingar e quando vai fazer isso.’ Esse conselho está de acordo com outros textos das Escrituras que falam sobre a importância de controlar a ira. (Sal 37:8; Ec 7:9; Mt 5:22; Gál 5:19, 20; Ef 4:31; Tg 1:19) O livro de Provérbios também fala várias vezes sobre esse assunto. — Pr 12:16; 14:17, 29; 15:1; 16:32; 17:14; 19:11, 19; 22:24; 25:28; 29:22.
- *diz Jeová*: Aqui, Paulo está citando De 32:35. O contexto desse versículo de Deuteronômio deixa claro que as palavras citadas por Paulo foram faladas por Jeová. — De 31:16, 19, 22, 30; 32:19-34; compare com a nota de estudo em Mt 1:22; veja os Apêndices C1 e C3 (introdução e Ro 12:19).
====

[[v45-12-20]]

^<<v45-12-20,20>>^ Mas, “se o seu inimigo estiver com fome, dê-lhe algo para comer; se ele estiver com sede, dê-lhe algo para beber; pois, fazendo isso, você amontoará brasas vivas sobre a cabeça dele”.

[TIP]
====
- *se o seu inimigo estiver com fome*: Aqui, Paulo continua seu argumento citando Pr 25:21, 22.
- *amontoará brasas vivas sobre a cabeça dele*: Aqui, Paulo está citando Pr 25:21, 22. Parece que tanto as palavras em Provérbios como a aplicação que Paulo faz delas se baseiam em um antigo método usado para derreter minério. O minério era colocado sobre uma camada de brasas, e algumas brasas eram também colocadas sobre o minério. Esse processo derretia o minério e fazia com que o metal se separasse das impurezas. Da mesma forma, quando alguém é bondoso com uma pessoa que o trata mal, isso costuma amolecer o coração da pessoa, trazendo para fora o que ela tem de bom. Esse conselho de fazer o bem para os inimigos também é encontrado em muitos outros lugares das Escrituras. (Êx 23:4, 5; Mt 5:44, 45; Lu 6:27; Ro 12:14) O provérbio que Paulo estava citando diz que “Jeová recompensará” quem agir dessa forma. (Pr 25:22; nota de rodapé) Isso apoia o entendimento de que essa metáfora sobre amontoar brasas sobre a cabeça de um inimigo tem um sentido positivo. Apesar de os estudiosos terem diferentes pontos de vista sobre o significado das palavras de Paulo, o contexto de Romanos deixa claro que ele não estava se referindo a algo feito para punir ou envergonhar o inimigo.
====

[[v45-12-21]]

^<<v45-12-21,21>>^ Não se deixe vencer pelo mal, mas continue vencendo o mal com o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]