include::./index.adoc[]

[[v44-25-0]]
=== Atos dos Apóstolos, 25
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* N. Paulo fica preso em Cesareia (24:1–26:32)
* Os judeus apresentam acusações contra Paulo (24:1-9)
* Defesa de Paulo diante de Félix (24:10-21)
* O caso de Paulo é adiado por dois anos (24:22-27)
* Julgamento de Paulo diante de Festo; “Apelo para César!” (25:1-12)
* Festo consulta o rei Agripa sobre o caso de Paulo (25:13-22)
* Paulo faz sua defesa diante de Agripa (25:23–26:11)
* Em seu discurso diante de Agripa, Paulo descreve como ele se converteu (26:12-23)
* Reações de Festo e Agripa (26:24-32)
****

[[v44-25-1]]

^<<v44-25-1,1>>^ Então, três dias depois de chegar à província e assumir o governo, Festo subiu de Cesareia a Jerusalém.

[TIP]
====
- *à província*: Ou seja, a província romana da Judeia. A residência do governador dessa província ficava em Cesareia. Entende-se que a expressão grega traduzida aqui como chegar à . . . e assumir o governo se refere a Festo tomar posse como governador da província.
====

[[v44-25-2]]

^<<v44-25-2,2>>^ E os principais sacerdotes e os homens mais importantes dos judeus lhe apresentaram acusações contra Paulo. Começaram a pedir insistentemente a Festo

[[v44-25-3]]

^<<v44-25-3,3>>^ que lhes fizesse o favor^&#42;1^ de mandar trazer Paulo para Jerusalém. Mas eles estavam armando uma emboscada para matá-lo na estrada.

[NOTE]
====
. Lit.: “pedindo um favor contra ele”.
====

[[v44-25-4]]

^<<v44-25-4,4>>^ No entanto, Festo respondeu que Paulo deveria continuar detido em Cesareia e que ele mesmo voltaria para lá em breve.

[[v44-25-5]]

^<<v44-25-5,5>>^ “Portanto”, disse ele, “desçam comigo alguns dos líderes de vocês e o acusem, se é que o homem fez alguma coisa errada”.

[[v44-25-6]]

^<<v44-25-6,6>>^ Assim, depois de passar não mais do que oito ou dez dias entre eles, ele desceu a Cesareia e, no dia seguinte, se sentou no tribunal e mandou que trouxessem Paulo.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo entrou, os judeus que tinham descido de Jerusalém o rodearam, fazendo muitas acusações graves contra ele, que não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Mas Paulo disse em sua defesa: “Não cometi nenhum pecado contra a Lei dos judeus, nem contra o templo, nem contra César.”

[TIP]
====
- *César*: Ou: “o Imperador”. Nessa época, o imperador romano era Nero. O governo dele começou em 54 d.C. e terminou em 68 d.C., quando Nero, que tinha uns 31 anos, cometeu suicídio. Nos capítulos 25 a 28 de Atos, o título César sempre se refere a Nero. — Veja as notas de estudo em Mt 22:17; At 17:7 e o Glossário.
====

[[v44-25-9]]

^<<v44-25-9,9>>^ Festo, querendo ganhar o favor dos judeus, disse a Paulo, em resposta: “Você deseja subir a Jerusalém e ser julgado ali, diante de mim, a respeito dessas coisas?”

[[v44-25-10]]

^<<v44-25-10,10>>^ Mas Paulo disse: “Estou perante o tribunal de César, onde devo ser julgado. Não fiz nada de errado contra os judeus, como Vossa Excelência está percebendo muito bem.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se eu sou realmente criminoso e fiz algo que mereça a morte, não me recuso a morrer; mas, se as acusações que esses homens fazem contra mim são infundadas, ninguém tem o direito de me entregar a eles como um favor. Apelo para César!”

[TIP]
====
- *Apelo para César!*: Esta é a terceira ocasião registrada na Bíblia em que Paulo usou seus direitos de cidadão romano. (Para as outras duas ocasiões, veja as notas de estudo em At 16:37; 22:25.) A pessoa não precisava esperar pelo proferimento da sentença para apelar para César. Se desejasse, ela podia apelar em qualquer momento do julgamento. Festo tinha dado sinais de que não queria decidir o caso de Paulo, e um julgamento em Jerusalém muito provavelmente não seria justo. Por isso, Paulo fez esse pedido formal para ser julgado pelo tribunal mais alto do império. Parece que, em alguns casos, a apelação podia ser negada, como no caso de um ladrão, um pirata ou alguém incentivando rebelião contra o governo que fossem apanhados em flagrante. Foi provavelmente por isso que Festo consultou “o grupo de conselheiros” antes de aceitar a apelação. (At 25:12) Festo aproveitou a visita de Herodes Agripa II para apresentar o caso de Paulo a ele e conseguir informações mais claras para enviar ao “Augusto”, ou seja, a Nero. (At 25:12-27; 26:32; 28:19) A apelação de Paulo também serviu para levá-lo a Roma, um local para onde ele já tinha dito que pretendia ir. (At 19:21) A promessa profética que Jesus tinha feito a ele e a mensagem que ele recebeu mais tarde de um anjo mostram que Deus estava dirigindo os assuntos. — At 23:11; 27:23, 24.
====

[[v44-25-12]]

^<<v44-25-12,12>>^ Então, depois de falar com o grupo de conselheiros, Festo respondeu: “Você apelou para César, para César irá.”

[[v44-25-13]]

^<<v44-25-13,13>>^ Depois de alguns dias, o rei Agripa e Berenice chegaram a Cesareia para fazer uma visita de cortesia a Festo.

[TIP]
====
- *Agripa*: Ou seja, Herodes Agripa II, bisneto de Herodes, o Grande. Ele era filho de Herodes Agripa I com sua esposa, Cipros. — At 12:1; veja o Glossário, “Herodes”.
- *Berenice*: Esta mulher era irmã de Herodes Agripa II. Havia boatos de que ela vivia em um relacionamento incestuoso com ele. Berenice mais tarde se tornou amante de Tito, antes de ele se tornar o imperador romano.
====

[[v44-25-14]]

^<<v44-25-14,14>>^ Visto que iam passar vários dias ali, Festo apresentou ao rei o caso de Paulo, dizendo:
“Há um homem que Félix deixou como prisioneiro;

[[v44-25-15]]

^<<v44-25-15,15>>^ quando estive em Jerusalém, os principais sacerdotes e os anciãos dos judeus me trouxeram informações sobre ele e pediram que ele fosse condenado.

[TIP]
====
- *anciãos*: Neste versículo, a palavra “anciãos” se refere a homens de autoridade entre os judeus. Muitas vezes eles são mencionados junto com outros dois grupos: os principais sacerdotes e os escribas. — Veja a nota de estudo em Mt 16:21.
====

[[v44-25-16]]

^<<v44-25-16,16>>^ Mas eu lhes respondi que não é procedimento romano entregar um acusado antes que ele se encontre face a face com os seus acusadores e tenha a oportunidade de se defender da acusação.

[[v44-25-17]]

^<<v44-25-17,17>>^ Assim, quando chegaram aqui, no dia seguinte sem demora sentei no tribunal e mandei que trouxessem o homem.

[[v44-25-18]]

^<<v44-25-18,18>>^ Quando os acusadores se levantaram para falar, não o acusaram de nenhuma das coisas más que eu havia imaginado.

[[v44-25-19]]

^<<v44-25-19,19>>^ Eles simplesmente tinham divergências com ele sobre a sua própria religião^&#42;1^ e sobre um homem chamado Jesus, que morreu, mas que Paulo insistia que estava vivo.

[NOTE]
====
. Ou: “adoração da divindade”.
====

[[v44-25-20]]

^<<v44-25-20,20>>^ Sem saber como lidar com essa controvérsia, eu perguntei se ele gostaria de ir a Jerusalém e ser julgado ali a respeito dessas questões.

[[v44-25-21]]

^<<v44-25-21,21>>^ Mas, quando Paulo apelou para continuar em detenção e aguardar a decisão de Augusto, mandei que ele ficasse preso até que eu o enviasse a César.”

[TIP]
====
- *Augusto*: Este era um dos títulos do imperador romano. A palavra grega que aparece aqui, Sebastós, é uma tradução do título Augustus, em latim, e significa “digno de reverência; venerável; augusto”. Algumas Bíblias traduzem esse título como “Sua Majestade o Imperador” ou “Sua Majestade Imperial”. Neste versículo, o título se refere a Nero, o quinto imperador romano, que governou de 54 a 68 d.C. O primeiro a ter o título “Augusto” foi o imperador Otávio (Otaviano). — Veja a nota de estudo em Lu 2:1.
====

[[v44-25-22]]

^<<v44-25-22,22>>^ Então Agripa disse a Festo: “Eu mesmo gostaria de ouvir o homem.” “Amanhã o ouvirá”, disse ele.

[[v44-25-23]]

^<<v44-25-23,23>>^ Assim, no dia seguinte, Agripa e Berenice chegaram com grande pompa e entraram na sala de audiências, junto com comandantes militares e homens importantes da cidade. E, quando Festo deu a ordem, trouxeram Paulo.

[[v44-25-24]]

^<<v44-25-24,24>>^ Festo disse: “Rei Agripa e todos os aqui presentes, podem ver este homem a respeito de quem toda a comunidade judaica fez petições a mim, tanto em Jerusalém como aqui, gritando que ele não deveria mais viver.

[[v44-25-25]]

^<<v44-25-25,25>>^ Mas eu percebi que ele não tinha feito nada que merecesse a morte. Assim, quando ele mesmo apelou para Augusto, decidi enviá-lo.

[[v44-25-26]]

^<<v44-25-26,26>>^ Mas não tenho nada definido para escrever ao meu Senhor a respeito dele. Portanto, eu o trouxe diante dos senhores, e especialmente de Vossa Majestade, rei Agripa, para que, depois do interrogatório, eu tenha algo para escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Pois não me parece razoável enviar um prisioneiro sem indicar também as acusações contra ele.”

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]