include::./index.adoc[]

[[v44-14-0]]
=== Atos dos Apóstolos, 14
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* I. Primeira viagem missionária de Paulo (13:1–14:28)
* Barnabé e Saulo são enviados como missionários (13:1-3)
* Pregação em Chipre; procônsul Sérgio Paulo e feiticeiro Elimas (13:4-12)
* Discurso de Paulo em Antioquia da Pisídia (13:13-41)
* Ordem profética para se voltarem para as nações (13:42-52)
* Crescimento da obra e oposição em Icônio (14:1-7)
* O povo de Listra pensa que Paulo e Barnabé são deuses (14:8-18)
* Paulo é apedrejado em Listra, mas sobrevive (14:19, 20)
* Paulo e Barnabé fortalecem as congregações (14:21-23)
* Paulo e Barnabé voltam a Antioquia da Síria (14:24-28)
****

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio, eles entraram juntos na sinagoga dos judeus e falaram de tal maneira que uma grande multidão, tanto de judeus como de gregos, se tornou crente.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus que não creram atiçaram as pessoas das nações, instigando-as contra os irmãos.

[TIP]
====
- *as pessoas*: Ou: “as almas das pessoas”. — Veja o Apêndice A2 e o Glossário, “Alma”.
====

[[v44-14-3]]

^<<v44-14-3,3>>^ Portanto, Paulo e Barnabé passaram bastante tempo falando corajosamente com a autoridade de Jeová; e Ele confirmava a^&#42;1^ mensagem sobre a sua bondade imerecida concedendo que ocorressem sinais e milagres por meio deles.

[NOTE]
====
. Ou: “dava testemunho da”.
====

[TIP]
====
- *com a autoridade de Jeová*: Lit.: “em cima do Senhor”. (Veja o Apêndice C1.) Entende-se que aqui, em At 14:3, a preposição epí (“sobre; em cima de”) foi usada para indicar qual era a base de Paulo e Barnabé para falar corajosamente. O resto do versículo mostra que Deus estava confirmando que o que eles pregavam vinha realmente dele e que essa pregação tinha o seu apoio e a sua aprovação. (Compare com At 4:29-31.) A expressão grega que aparece aqui também foi usada na Septuaginta em frases onde o Tetragrama aparece no texto hebraico original. (Sal 31:6 [30:7, LXX]; Je 17:7) Com base no sentido dessas frases, alguns sugerem que a expressão também inclui a ideia de falar “com confiança em Jeová”. — Veja o Apêndice C3 (introdução e At 14:3).
- *milagres*: Ou: “presságios”. — Veja a nota de estudo em At 2:19.
====

[[v44-14-4]]

^<<v44-14-4,4>>^ No entanto, a multidão da cidade estava dividida: alguns eram a favor dos judeus, e outros a favor dos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Então, as pessoas das nações junto com os judeus e seus líderes resolveram maltratá-los e apedrejá-los.

[[v44-14-6]]

^<<v44-14-6,6>>^ Ao serem informados disso, fugiram para Listra e Derbe, cidades da Licaônia, e para a região ao redor.

[[v44-14-7]]

^<<v44-14-7,7>>^ Ali continuaram a declarar as boas novas.

[[v44-14-8]]

^<<v44-14-8,8>>^ Em Listra, havia um homem que tinha os pés aleijados; ele era manco de nascença, nunca tinha andado. Ele estava sentado,

[[v44-14-9]]

^<<v44-14-9,9>>^ escutando Paulo falar. Paulo, olhando para ele atentamente e vendo que ele tinha fé para ficar bom,^&#42;1^

[NOTE]
====
. Ou: “para ser salvo”.
====

[[v44-14-10]]

^<<v44-14-10,10>>^ disse bem alto: “Levante-se e fique de pé.” Então o homem deu um salto e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ Quando as multidões viram o que Paulo tinha feito, gritaram na língua licaônica: “Os deuses tomaram forma humana e desceram a nós!”

[[v44-14-12]]

^<<v44-14-12,12>>^ Eles começaram a chamar Barnabé de Zeus e Paulo de Hermes, pois era ele que lhes dirigia a palavra.

[TIP]
====
- *Zeus*: Veja o Glossário.
- *Hermes*: Este era o nome de um deus da mitologia que, segundo os gregos, era um dos filhos de Zeus. Hermes era considerado o mensageiro dos deuses, o habilidoso conselheiro dos heróis mitológicos e o deus do comércio, da oratória, da ginástica, do sono e dos sonhos. Já que foi Paulo quem dirigiu a palavra aos moradores da cidade romana de Listra, eles pensaram que ele fosse Hermes, o mensageiro dos deuses e o deus da oratória. É interessante notar que várias palavras gregas relacionadas com tradução e interpretação estão ligadas ao nome Hermes. (Alguns exemplos são o verbo grego para “traduzir”, hermeneúo, que aparece em Jo 1:42 e He 7:2, e o substantivo grego para “interpretação”, hermenía, que aparece em 1Co 12:10 e 14:26; veja também a nota de estudo em Lu 24:27.) Entre as descobertas arqueológicas feitas na região da antiga Listra estão uma estátua do deus Hermes e um altar dedicado a Zeus e a Hermes. Para os romanos, Hermes correspondia a Mercúrio, o deus romano do comércio.
====

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote de Zeus, cujo templo ficava na entrada da cidade,^&#42;1^ levou touros e grinaldas até os portões, e queria oferecer sacrifícios com as multidões.

[NOTE]
====
. Ou: “cujo templo ficava bem perto da cidade”. Lit.: “o (que) estava diante da cidade”.
====

[TIP]
====
- *grinaldas*: Ou: “coroas de flores”. Pode ser que o sacerdote de Zeus quisesse colocar essas grinaldas na cabeça de Paulo e de Barnabé, como às vezes era feito com ídolos. Outra possibilidade é que as grinaldas fossem para o próprio sacerdote, para os outros adoradores e para os animais que seriam sacrificados. Esse tipo de grinalda geralmente era feito de folhas e flores, mas algumas eram feitas de lã.
====

[[v44-14-14]]

^<<v44-14-14,14>>^ Quando os apóstolos Barnabé e Paulo souberam disso, rasgaram suas roupas, correram para o meio da multidão e gritaram:

[[v44-14-15]]

^<<v44-14-15,15>>^ “Homens, por que estão fazendo isso? Nós também somos humanos e temos as mesmas fraquezas que vocês. E estamos declarando as boas novas a vocês para que abandonem essas coisas vãs e se convertam ao Deus vivente, que fez o céu, a terra, o mar e tudo que há neles.

[[v44-14-16]]

^<<v44-14-16,16>>^ Em gerações passadas, ele permitiu que todas as nações andassem nos seus próprios caminhos,

[[v44-14-17]]

^<<v44-14-17,17>>^ embora não tenha deixado de dar testemunho de si mesmo, pois demonstrou sua bondade dando-lhes chuvas do céu e épocas de colheita abundante, satisfazendo-os com alimentos e enchendo seu coração de alegria.”

[[v44-14-18]]

^<<v44-14-18,18>>^ Mesmo dizendo essas coisas, foi muito difícil impedir que as multidões lhes oferecessem sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Mas chegaram judeus de Antioquia e de Icônio que persuadiram as multidões; então apedrejaram Paulo e o arrastaram para fora da cidade, imaginando que ele estivesse morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ No entanto, quando os discípulos se juntaram em volta dele, ele se levantou e entrou na cidade. No dia seguinte partiu com Barnabé para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ Depois de declararem as boas novas àquela cidade e fazerem um bom número de discípulos, voltaram a Listra, Icônio e Antioquia.

[[v44-14-22]]

^<<v44-14-22,22>>^ Ali, fortaleceram os discípulos, encorajando-os a permanecer na fé e dizendo-lhes: “Temos de passar por muitas dificuldades para entrar no Reino de Deus.”

[TIP]
====
- *os discípulos*: Ou: “as almas dos discípulos”. — Veja o Apêndice A2 e o Glossário, “Alma”.
====

[[v44-14-23]]

^<<v44-14-23,23>>^ Além disso, designaram anciãos para eles em cada congregação, fazendo orações e jejuando, e os entregaram aos cuidados de Jeová, em quem tinham passado a crer.

[TIP]
====
- *designaram*: Aqui, as Escrituras mostram que a designação de anciãos era feita por superintendentes viajantes, neste caso, Paulo e Barnabé. O fato de eles terem feito orações e jejuado mostra que eles encaravam a designação de anciãos como uma responsabilidade muito grande. Tito e, pelo visto, Timóteo também foram usados para fazer designações de “anciãos” nas congregações. (Tit 1:5; 1Ti 5:22) O verbo grego traduzido aqui como “designaram” (kheirotonéo) significa literalmente “estender a mão; levantar a mão”. Por causa desse significado, alguns acreditam que os membros da congregação elegiam os anciãos, indicando o seu voto por levantar a mão. Mas o verbo kheirotonéo também é usado com um sentido mais amplo, e nem sempre indica o modo como a designação foi feita. Por exemplo, o historiador judeu Josefo, do século 1 d.C., usa esse mesmo verbo ao falar de Saul ser designado por Deus como rei. (Antiquities of the Jews, livro 6, capítulos 4 e 13 [Loeb 6:54 e 6:312]) Naquele caso, não foram os israelitas que escolheram Saul, levantando as mãos em uma votação. Em vez disso, as Escrituras mostram que o profeta Samuel derramou óleo sobre a cabeça de Saul e disse: “Jeová o ungiu como líder.” (1Sa 10:1) Ao fazer isso, Samuel estava mostrando que a designação tinha sido feita por Jeová Deus. Outro fator a levar em conta é que a construção gramatical usada aqui em At 14:23 mostra que a ação de designar (lit.: “estender as mãos”) foi feita pelos apóstolos Paulo e Barnabé, e não pela congregação. Em outras ocasiões, quando homens habilitados foram designados para tarefas especiais na congregação, os apóstolos e outros irmãos autorizados impuseram literalmente as mãos sobre eles. Esse gesto servia para indicar aprovação ou para confirmar uma designação. — Compare com a nota de estudo em At 6:6.
- *anciãos*: Lit.: “homens mais velhos (idosos)”. Na Bíblia, a palavra grega presbýteros se refere principalmente a quem tem autoridade e responsabilidade numa comunidade ou nação, apesar de às vezes também ser usada para se referir a alguém idoso. (Veja a nota de estudo em Mt 16:21.) Na nação de Israel, homens mais velhos e maduros tomavam a liderança entre o povo e ajudavam na administração do país. Da mesma forma, homens espiritualmente maduros tomavam a liderança nas congregações do século 1 d.C. (1Ti 3:1-7; Tit 1:5-9) Paulo e Barnabé foram “enviados pelo espírito santo” em sua viagem missionária, mas, mesmo assim, oravam e jejuavam quando faziam designações de anciãos. Depois disso, eles ‘os entregavam aos cuidados de Jeová’. (At 13:1-4; 14:23) Paulo e Barnabé não foram os únicos usados dessa maneira. A Bíblia mostra que Tito e, pelo visto, Timóteo também foram usados para fazer designações de “anciãos” nas congregações. (Tit 1:5; 1Ti 5:22) Não existe nenhum registro nas Escrituras de que alguma congregação tenha designado anciãos por conta própria. Tudo indica que as congregações do século 1 d.C. costumavam ter dois ou mais anciãos que serviam juntos como um “corpo de anciãos”. — 1Ti 4:14; Fil 1:1.
- *os entregaram aos cuidados de Jeová*: O verbo grego traduzido aqui como “entregaram aos cuidados” também foi usado em At 20:32, onde Paulo disse para os anciãos em Éfeso: “Eu os entrego aos cuidados de Deus.” Ele também aparece em Lu 23:46, que registra as palavras de Jesus: “Pai, às tuas mãos confio o meu espírito.” Jesus estava citando o Sal 31:5, onde a Septuaginta (30:6, LXX) usa esse mesmo verbo grego. No texto hebraico original desse salmo, aparece o nome de Deus. A ideia de uma pessoa se entregar aos cuidados de Jeová é comum nas Escrituras Hebraicas. — Sal 22:8; 37:5; Pr 16:3; veja o Apêndice C3 (introdução e At 14:23).
====

[[v44-14-24]]

^<<v44-14-24,24>>^ Então passaram pela Pisídia, entraram na Panfília

[[v44-14-25]]

^<<v44-14-25,25>>^ e, depois de proclamar a palavra em Perge, desceram para Atália.

[TIP]
====
- *a palavra*: Nesta parte do versículo, há diferenças entre os manuscritos. A opção usada aqui, “a palavra” (ton lógon), tem o apoio de manuscritos muito antigos e confiáveis e é usada na maioria das traduções modernas. Mas existem outros manuscritos gregos que dizem “a palavra do Senhor” (ton lógon tou Kyríou; veja o Apêndice C1 e a nota de estudo em At 8:25). E alguns poucos manuscritos muito antigos dizem “a palavra de Deus”. Além disso, pelo menos duas traduções das Escrituras Gregas Cristãs para o hebraico (chamadas de J17, 28 no Apêndice C4) usam o nome de Deus aqui. A frase que aparece nelas poderia ser traduzida como “a palavra de Jeová”.
====

[[v44-14-26]]

^<<v44-14-26,26>>^ Dali navegaram para Antioquia, onde haviam sido entregues à bondade imerecida de Deus para a obra que agora tinham completado.

[[v44-14-27]]

^<<v44-14-27,27>>^ Depois de chegarem e reunirem a congregação, contaram as muitas coisas que Deus tinha feito por meio deles e como ele tinha aberto para as nações a porta da fé.

[TIP]
====
- *a porta da fé*: Ou: “a porta para a fé”. Jeová abriu essa “porta” quando deu para as nações, ou seja, para os não judeus, a oportunidade de terem fé. A fé mencionada nas Escrituras envolve mais do que apenas acreditar; a pessoa precisa aprender a confiar a ponto de obedecer. (Tg 2:17; veja a nota de estudo em Jo 3:16.) Em suas cartas, o apóstolo Paulo usa três vezes a palavra “porta” em sentido figurado. — 1Co 16:9; 2Co 2:12; Col 4:3.
====

[[v44-14-28]]

^<<v44-14-28,28>>^ Assim, passaram bastante tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]