include::./index.adoc[]

[[v44-16-0]]
=== Atos dos Apóstolos, 16
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* K. Segunda viagem missionária de Paulo (15:36–18:22)
* Paulo e Barnabé se separam (15:36-41)
* Paulo escolhe Timóteo como companheiro de viagem (16:1-5)
* Visão sobre o homem macedônio; a pregação chega à Europa (16:6-10)
* Em Filipos, Lídia se converte (16:11-15)
* Paulo e Silas são presos em Filipos (16:16-24)
* O carcereiro e os da sua casa são batizados (16:25-34)
* Paulo exige uma retratação oficial (16:35-40)
* Paulo e Silas em Tessalônica (17:1-9)
* Paulo e Silas em Bereia (17:10-15)
* Paulo em Atenas (17:16-22a)
* Discurso de Paulo no Areópago (17:22b-31)
* Diferentes reações ao discurso de Paulo; alguns se tornam crentes (17:32-34)
* Ministério de Paulo em Corinto (18:1-17)
* Paulo volta a Antioquia da Síria passando por Éfeso (18:18-22)
****

[[v44-16-1]]

^<<v44-16-1,1>>^ Então ele chegou a Derbe e a Listra. Havia ali um discípulo chamado Timóteo, filho de uma mulher judia crente, mas de pai grego,

[TIP]
====
- *Timóteo*: Esta é a primeira vez que a Bíblia menciona Timóteo. Em grego, esse nome significa “alguém que honra a Deus”. Não se sabe exatamente quando Timóteo se tornou cristão. O que se sabe é que, desde quando ele ainda era uma criança bem pequena, sua mãe, Eunice (que era judia), e provavelmente sua avó, Loide, já ensinavam a ele “os escritos sagrados” dos judeus, ou seja, as Escrituras Hebraicas. (2Ti 1:5; 3:15) É muito provável que Eunice e Loide tenham se tornado cristãs quando Paulo visitou Listra em sua primeira viagem missionária. Aqui, o versículo diz que o pai de Timóteo era grego. Isso pode significar que a família dele tinha vindo da Grécia ou simplesmente que ele era um não judeu. Tudo indica que ele não era cristão. Paulo voltou a visitar Listra, onde Timóteo provavelmente morava, em sua segunda viagem missionária, no fim do ano 49 ou no começo do ano 50 d.C. Nessa época, Timóteo já era cristão e “os irmãos em Listra e em Icônio falavam bem dele”. (At 16:2) Timóteo talvez estivesse no fim da adolescência ou com uns 20 e poucos anos, já que uns 10 ou 15 anos mais tarde Paulo disse a ele: “Nunca deixe que ninguém o menospreze por você ser jovem.” (1Ti 4:12) Isso indica que, quando Paulo escreveu essas palavras (provavelmente entre 61 e 64 d.C.), Timóteo ainda era relativamente jovem.
====

[[v44-16-2]]

^<<v44-16-2,2>>^ e os irmãos em Listra e em Icônio falavam bem dele.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo quis que Timóteo o acompanhasse e o circuncidou por causa dos judeus daqueles lugares, pois todos sabiam que seu pai era grego.

[TIP]
====
- *o circuncidou*: Timóteo não tinha sido circuncidado, já que seu pai não era judeu. E Paulo sabia que a circuncisão não era necessária para os cristãos. (At 15:6-29) Mas ele tinha convidado Timóteo para acompanhá-lo em sua viagem missionária e sabia que o fato de Timóteo não ser circuncidado poderia se tornar um obstáculo para a sua pregação. Por isso, Paulo pediu que Timóteo passasse por esse doloroso procedimento. Dessa forma, eles agiram de acordo com o que Paulo escreveu mais tarde aos coríntios: “Para os judeus me tornei como judeu, para ganhar os judeus.” — 1Co 9:20.
====

[[v44-16-4]]

^<<v44-16-4,4>>^ Ao viajarem pelas cidades, transmitiam aos irmãos as decisões tomadas pelos apóstolos e pelos anciãos em Jerusalém, para que obedecessem a esses decretos.

[TIP]
====
- *pelos apóstolos e pelos anciãos em Jerusalém*: Assim como alguns anciãos no Israel literal serviam em posições de responsabilidade em nível nacional, os anciãos da congregação em Jerusalém e os apóstolos serviam como um corpo governante que supervisionava todas as congregações do século 1 d.C. (Veja a nota de estudo em At 15:2.) Depois que os apóstolos e os anciãos em Jerusalém tomaram sua decisão sobre o assunto da circuncisão, eles a transmitiram às congregações, que a consideraram uma decisão definitiva.
====

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim, as congregações eram fortalecidas na fé e cresciam a cada dia.

[[v44-16-6]]

^<<v44-16-6,6>>^ Eles viajaram pela Frígia e pela região da Galácia, porque^&#42;1^ o espírito santo os havia proibido de falar a palavra na província da Ásia.

[NOTE]
====
. Ou: “e”.
====

[TIP]
====
- *na província da Ásia*: Veja o Glossário, “Ásia”.
====

[[v44-16-7]]

^<<v44-16-7,7>>^ Além disso, quando desceram à Mísia, tentaram entrar na Bitínia, mas o espírito de Jesus não lhes permitiu fazer isso.

[TIP]
====
- *o espírito de Jesus*: Pelo visto, estas palavras se referem ao espírito santo, ou força ativa, que Jesus “recebeu do Pai”. (At 2:33) Como cabeça da congregação cristã, Jesus usou o espírito para direcionar o trabalho de pregação dos cristãos do século 1 d.C., mostrando a eles onde deveriam concentrar seus esforços. Na ocasião mencionada aqui, Jesus usou “o espírito santo” para impedir que Paulo e seus companheiros de viagem pregassem nas províncias da Ásia e da Bitínia. (At 16:6-10) Mas, mais tarde, a pregação das boas novas também chegou a essas regiões. — At 18:18-21; 1Pe 1:1, 2.
====

[[v44-16-8]]

^<<v44-16-8,8>>^ De modo que passaram pela Mísia e desceram a Trôade.

[TIP]
====
- *passaram pela*: Ou: “atravessaram a”. O verbo grego parérkhomai, traduzido aqui como “passaram pela”, também pode significar “passar ao lado de”. Mas aqui ele, pelo visto, transmite a ideia de que Paulo e seus companheiros atravessaram a região. Trôade era uma cidade portuária que ficava na região da Mísia, no noroeste da Ásia Menor. Para chegar a Trôade, Paulo e seus companheiros tiveram que atravessar a Mísia. Assim, a maneira como o verbo parérkhomai é usado aqui indica que eles apenas atravessaram a região, sem se concentrar em pregar ali.
====

[[v44-16-9]]

^<<v44-16-9,9>>^ Durante a noite, Paulo teve uma visão: um macedônio estava em pé suplicando-lhe: “Venha para a Macedônia e ajude-nos.”

[TIP]
====
- *Macedônia*: Veja o Glossário.
====

[[v44-16-10]]

^<<v44-16-10,10>>^ Logo depois que ele teve a visão, procuramos ir à Macedônia, concluindo que Deus havia nos chamado para lhes declarar as boas novas.

[TIP]
====
- *procuramos*: Até At 16:9, todos os acontecimentos do livro de Atos são narrados na terceira pessoa, ou seja, Lucas relata apenas coisas que outros fizeram e disseram. Mas, aqui em At 16:10, Lucas muda seu estilo e se inclui no relato. A partir deste versículo, Lucas às vezes narra os acontecimentos na primeira pessoa. Pelo visto, ele estava entre os companheiros de Paulo nessas ocasiões. (Veja a nota de estudo em At 1:1 e “Introdução a Atos”.) A primeira viagem que Lucas fez com Paulo foi de Trôade a Filipos, por volta de 50 d.C. Mas, quando Paulo deixou Filipos, Lucas não estava mais com ele. — At 16:10-17, 40; veja as notas de estudo em At 20:5; 27:1.
- *declarar as boas novas*: Veja a nota de estudo em At 5:42.
====

[[v44-16-11]]

^<<v44-16-11,11>>^ Assim, embarcamos em Trôade e fomos diretamente para a Samotrácia, mas, no dia seguinte, fomos para Neápolis;

[[v44-16-12]]

^<<v44-16-12,12>>^ dali fomos para Filipos, colônia romana e cidade principal da região da Macedônia. Ficamos nessa cidade por alguns dias.

[TIP]
====
- *Filipos*: O nome original desta cidade era Crenides (Krenides). Por volta da metade do século 4 a.C., Filipe II, da Macedônia (pai de Alexandre, o Grande), tomou a cidade, que estava sob o domínio dos trácios, e deu a ela o seu próprio nome. Naquela região, havia minas de ouro muito produtivas, e foram feitas moedas de ouro com o nome de Filipe. Por volta de 168 a.C., o cônsul romano Lúcio Emílio Paulo derrotou Perseu, o último dos reis macedônios, e conquistou Filipos e a região em volta. Em 146 a.C., toda a Macedônia se tornou uma única província romana. Foi na planície de Filipos, em 42 a.C., que aconteceu a famosa batalha em que Otaviano (Otávio) e Marco Antônio derrotaram os exércitos de Bruto e Caio Cássio Longino, que tinham assassinado Júlio César. Para celebrar sua vitória, Otaviano deu a Filipos o status de colônia romana. Alguns anos mais tarde, quando Otaviano foi nomeado pelo Senado como imperador e passou a ser conhecido como César Augusto, ele deu a Filipos o título de Colônia Júlia Augusta Filipense. — Veja o Apêndice B13.
====

[[v44-16-13]]

^<<v44-16-13,13>>^ No dia de sábado, saímos pelo portão da cidade e fomos para junto de um rio, pois pensávamos que ali havia um lugar de oração. Então nos sentamos e começamos a falar com as mulheres que haviam se reunido ali.

[TIP]
====
- *um rio*: Muitos estudiosos acreditam que este rio seja o Gangites, que fica 2,4 quilômetros ao oeste de Filipos. Essa distância é maior do que a que os judeus podiam percorrer no sábado. Alguns acham que, por causa da natureza militar de Filipos, os judeus talvez tenham sido proibidos de se reunir para adorar dentro da cidade e precisavam fazer isso longe dali. Uma segunda opção, defendida por outros estudiosos, é que o rio mencionado aqui seja o Crenides (Krenides), um riacho que fica mais perto da cidade e que é conhecido localmente como o riacho de Lídia. Mas alguns acham improvável que o lugar de oração mencionado neste versículo ficasse ali, já que foram encontrados túmulos romanos no local e ele ficava à vista de todos. Uma terceira opção apresentada por alguns é que o lugar de oração ficasse do lado de fora do Portão de Neápolis, no local onde há hoje um riacho seco. Nesse local, foram construídas algumas igrejas no século 4 ou 5 d.C., em homenagem à visita de Paulo a Filipos.
- *um lugar de oração*: Pode ser que os judeus fossem proibidos de ter uma sinagoga em Filipos por causa da natureza militar da cidade. Ou pode ser que a cidade tivesse menos de dez homens judeus. Segundo a tradição, esse era o número mínimo exigido para se estabelecer uma sinagoga.
====

[[v44-16-14]]

^<<v44-16-14,14>>^ Uma mulher estava escutando: ela se chamava Lídia, era vendedora de púrpura, da cidade de Tiatira, e adoradora de Deus. E Jeová lhe abriu amplamente o coração para prestar atenção ao que Paulo estava falando.

[TIP]
====
- *ela se chamava Lídia*: Lídia é mencionada por nome apenas duas vezes na Bíblia: aqui e em At 16:40. Alguns acham que “Lídia” era um apelido que significava “mulher de Lídia”, mas existem documentos que mostram que Lídia também era um nome próprio. Lídia e os da sua casa se tornaram cristãos por volta de 50 d.C. em Filipos. Assim, eles estavam entre as primeiras pessoas da Europa a aceitar o cristianismo em resultado da pregação de Paulo. Pode ser que Lídia fosse viúva ou que nunca tivesse se casado. Por causa da sua generosidade, ela teve a oportunidade de passar tempo na companhia dos missionários Paulo, Silas e Lucas. — At 16:15.
- *vendedora de púrpura*: Pode ser que Lídia comercializasse artigos variados de púrpura, incluindo tecidos, roupas, tapeçarias e corantes. Ela era natural de Tiatira, uma cidade que ficava no oeste da Ásia Menor, numa região chamada Lídia. Foi encontrada em Filipos uma inscrição que comprova que havia ali uma associação de vendedores de púrpura. Desde os dias de Homero (séculos 9 ou 8 a.C.), os lídios e os povos vizinhos eram famosos por sua habilidade em usar púrpura para tingir tecidos. É bem provável que Lídia fosse uma comerciante rica e bem-sucedida, pois trabalhar com púrpura exigia investir muito dinheiro. Além disso, Lídia tinha uma casa grande o suficiente para hospedar quatro pessoas — Paulo, Silas, Timóteo e Lucas. O texto de At 16:15 fala sobre “os da sua casa”, ou seja, os da casa de Lídia. Isso pode indicar que ela morava com parentes, mas também pode significar que ela tinha escravos e servos. E o fato de Paulo e Silas, antes de deixarem a cidade, terem se encontrado com alguns irmãos na casa dessa mulher hospitaleira sugere que a casa dela se tornou um local de reuniões para os primeiros cristãos em Filipos. — At 16:40.
- *Jeová lhe abriu amplamente o coração*: Neste versículo, Lídia é chamada de adoradora de Deus, o que indica que ela era uma prosélita. (At 13:43) Ela estava reunida com outras mulheres no sábado em um lugar de oração que ficava junto de um rio, fora da cidade de Filipos. (At 16:13) Pode ser que houvesse poucos judeus em Filipos e que a cidade não tivesse uma sinagoga. Lídia talvez tenha entrado em contato com a adoração de Jeová na sua cidade de origem, Tiatira, que tinha uma grande população de judeus e um local de reuniões. Jeová, o Deus a quem Lídia adorava, percebeu que ela estava escutando com atenção o que Paulo estava falando. — Veja o Apêndice C3 (introdução e At 16:14).
====

[[v44-16-15]]

^<<v44-16-15,15>>^ Então, depois que ela e os da sua casa foram batizados, ela insistiu: “Se vocês me consideram fiel a Jeová, venham ficar na minha casa.” E ela simplesmente nos fez ir.

[TIP]
====
- *fiel a Jeová*: Como mostra a nota de estudo no versículo anterior, tudo indica que Lídia era uma prosélita. Assim, parece lógico que aqui ela estivesse se referindo a Jeová. Ela tinha acabado de ouvir a pregação de Paulo sobre Jesus Cristo e ainda não tinha tido a oportunidade de mostrar que era fiel a ele. Por isso, faz mais sentido que ela estivesse se referindo à sua fidelidade a Jeová, o Deus a quem ela adorava. — Veja o Apêndice C3 (introdução e At 16:15).
====

[[v44-16-16]]

^<<v44-16-16,16>>^ Um dia, quando íamos para o lugar de oração, veio ao nosso encontro uma serva que tinha um espírito, um demônio de adivinhação. Ela dava muito lucro aos seus senhores adivinhando o futuro.

[TIP]
====
- *um espírito, um demônio de adivinhação*: Lit.: “um espírito de píton”. Píton era o nome de uma serpente ou dragão mitológico que protegia o templo e o oráculo de Delfos, na Grécia. Com o tempo, a palavra grega pýthon passou a se referir a uma pessoa que podia prever o futuro e ao espírito que falava por meio dela. Mais tarde, pýthon também passou a se referir a ventríloquos, mas aqui em Atos a palavra foi usada para falar de um demônio que dava para a serva a capacidade de fazer predições.
- *adivinhando o futuro*: Ou: “praticando a arte da predição”. A Bíblia fala de alguns que afirmavam ter a habilidade de prever o futuro, como por exemplo sacerdotes-magos, adivinhos e astrólogos. (Le 19:31; De 18:11) Nas Escrituras Gregas Cristãs, a única passagem que fala de demônios preverem o futuro é este relato do que aconteceu em Filipos. Os demônios se opõem a Deus e aos que fazem a vontade dele. Assim, não é de admirar que Paulo e Silas tenham sofrido intensa oposição por terem expulsado esse demônio de adivinhação. — At 16:12, 17-24.
====

[[v44-16-17]]

^<<v44-16-17,17>>^ Essa moça seguia Paulo e a nós, gritando: “Estes homens são escravos do Deus Altíssimo e estão proclamando a vocês o caminho da salvação.”

[[v44-16-18]]

^<<v44-16-18,18>>^ Ela fez isso por muitos dias. Por fim, Paulo ficou cansado daquilo, virou-se e disse ao espírito: “Ordeno-lhe em nome de Jesus Cristo que saia dela.” E o espírito saiu na mesma hora.

[[v44-16-19]]

^<<v44-16-19,19>>^ Quando os senhores dela viram que sua esperança de lucro havia acabado, agarraram Paulo e Silas e os arrastaram até a praça principal, às autoridades.

[TIP]
====
- *a praça principal*: Ou: “o mercado; o foro”. A palavra grega agorá é usada aqui para se referir a uma área aberta que existia nas cidades do Antigo Oriente Próximo e de outras regiões influenciadas pelos impérios grego e romano. Esse tipo de praça servia como centro de compras e vendas e como local de reuniões públicas. Este relato do que aconteceu em Filipos parece indicar que alguns julgamentos eram realizados na praça principal. Escavações das ruínas de Filipos indicam que a Via Egnácia (uma importante estrada romana) passava pelo meio da cidade e que, ao lado dessa estrada, havia um grande foro, ou praça principal. — Veja as notas de estudo em Mt 23:7; At 17:17.
====

[[v44-16-20]]

^<<v44-16-20,20>>^ Levaram-nos aos magistrados civis e disseram: “Estes homens estão perturbando muito a nossa cidade. São judeus

[TIP]
====
- *aos magistrados civis*: A palavra grega strategós aparece aqui no plural e se refere às principais autoridades da colônia romana de Filipos. Seus deveres incluíam manter a ordem, administrar as finanças, julgar os que violavam a lei e ordenar a aplicação de punições.
====

[[v44-16-21]]

^<<v44-16-21,21>>^ e estão divulgando costumes que não nos é permitido^&#42;1^ adotar ou praticar, visto que somos romanos.”

[NOTE]
====
. Ou: “lícito”.
====

[TIP]
====
- *somos romanos*: A cidade de Filipos era uma colônia romana e seus habitantes tinham muitos privilégios. Entre esses privilégios, talvez estivesse uma espécie de cidadania que dava a eles alguns direitos de um cidadão romano. Isso talvez explique por que eles, pelo visto, eram tão apegados a Roma. — Veja a nota de estudo em At 16:12.
====

[[v44-16-22]]

^<<v44-16-22,22>>^ E toda a multidão se levantou contra eles; então os magistrados civis lhes arrancaram as roupas e mandaram que fossem espancados com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de lhes baterem muito, os lançaram na prisão e ordenaram ao carcereiro que os guardasse com segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Recebendo essa ordem, ele os lançou na prisão interior e prendeu os pés deles no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Mas, por volta da meia-noite, Paulo e Silas estavam orando e louvando a Deus com cânticos, e os prisioneiros os ouviam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, houve um terremoto tão grande que os alicerces da cadeia foram abalados. Nesse instante, todas as portas se abriram e as correntes de todos se soltaram.

[[v44-16-27]]

^<<v44-16-27,27>>^ Quando o carcereiro acordou e viu que as portas da prisão estavam abertas, ele puxou sua espada e ia se matar, pensando que os prisioneiros tinham escapado.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo gritou: “Não faça nenhum mal a si mesmo, pois estamos todos aqui!”

[[v44-16-29]]

^<<v44-16-29,29>>^ Assim, ele pediu que lhe trouxessem uma luz, entrou correndo e, tremendo, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Ele os levou para fora e perguntou: “Senhores, o que tenho de fazer para ser salvo?”

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: “Creia no Senhor Jesus e será salvo, você e os da sua casa.”

[[v44-16-32]]

^<<v44-16-32,32>>^ E falaram a palavra de Jeová a ele e a todos os da sua casa.

[TIP]
====
- *a palavra de Jeová*: Veja a nota de estudo em At 8:25 e o Apêndice C3 (introdução e At 16:32).
====

[[v44-16-33]]

^<<v44-16-33,33>>^ Ele os levou consigo naquela hora da noite e lavou seus ferimentos. Então ele e todos os da sua casa foram batizados sem demora.

[TIP]
====
- *foram batizados sem demora*: O carcereiro e os da sua casa (a sua família) eram não judeus e provavelmente não conheciam as verdades básicas das Escrituras. Paulo e Silas disseram que eles deviam ‘crer no Senhor Jesus’ e falaram a eles “a palavra de Jeová”, sem dúvida de forma detalhada. (At 16:31, 32) Isso teve um impacto tão grande neles que, naquela mesma noite, eles ‘creram em Deus’, ou seja, passaram a ter fé nele. (At 16:34) Assim, era apropriado que eles fossem batizados sem demora. O texto de At 16:40 indica que, quando Paulo e Silas partiram de Filipos, seu outro companheiro de viagem, Lucas, não foi junto com eles. (Veja a nota de estudo em At 16:10.) Pode ser que Lucas tenha ficado em Filipos por um tempo para dar ajuda aos novos cristãos ali.
====

[[v44-16-34]]

^<<v44-16-34,34>>^ Ele os levou à sua casa e pôs a mesa para eles, e ele e todos os da sua casa se alegraram muito por terem crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando o dia amanheceu, os magistrados civis enviaram os guardas para dizer ao carcereiro: “Solte esses homens.”

[TIP]
====
- *os guardas*: A palavra grega que aparece aqui, rhabdoúkhos, significa literalmente “portador de vara”. Ela se refere a um ajudante oficial que era designado para escoltar um magistrado romano em público e para executar suas instruções. Os romanos chamavam esse ajudante de lictor. Algumas das funções que esses guardas tinham eram de natureza policial, mas eles serviam apenas ao magistrado e tinham o dever de estar sempre à sua disposição. Eles não tinham a obrigação de atender os pedidos do povo e obedeciam apenas às ordens de seu magistrado.
====

[[v44-16-36]]

^<<v44-16-36,36>>^ O carcereiro transmitiu essas palavras a Paulo; disse: “Os magistrados civis mandaram soltar vocês dois. Então, saiam agora e vão em paz.”

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo lhes disse: “Eles nos açoitaram publicamente sem termos sido julgados,^&#42;1^ embora sejamos romanos, e nos lançaram na prisão. Agora nos mandam embora secretamente? Não! Que venham eles próprios e nos levem para fora.”

[NOTE]
====
. Ou: “sem um processo formal”.
====

[TIP]
====
- *embora sejamos romanos*: Ou seja, cidadãos romanos. Paulo e, pelo visto, Silas eram cidadãos romanos. Com base na lei romana, um cidadão sempre tinha o direito de ser julgado perante um tribunal e nunca deveria ser punido em público sem antes ter sido condenado. Quem era cidadão romano tinha certos direitos e privilégios em qualquer lugar para onde fosse dentro do Império Romano. O cidadão romano estava sujeito à lei romana, não às leis das províncias. Se fosse acusado, ele podia concordar em ser julgado segundo as leis locais, mas ainda assim tinha o direito de ser ouvido por um tribunal romano. E, se a acusação pudesse levar à pena de morte, ele tinha o direito de apelar para o imperador. O apóstolo Paulo pregou por todo o Império Romano. O relato bíblico registra três ocasiões em que ele usou seus direitos de cidadão romano. A primeira delas foi esta ocasião em Filipos, quando ele informou aos magistrados filipenses que eles tinham violado seus direitos ao espancá-lo. — Para ver as outras ocasiões, veja as notas de estudo em At 22:25; 25:11.
====

[[v44-16-38]]

^<<v44-16-38,38>>^ Os guardas comunicaram então essas palavras aos magistrados civis. Estes ficaram com medo quando ouviram que os homens eram romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ Assim, foram até lá e lhes pediram desculpas, e, depois de levá-los para fora, pediram-lhes que partissem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Mas Paulo e Silas, ao saírem da prisão, foram à casa de Lídia. Quando viram os irmãos, os encorajaram; depois partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]