include::./index.adoc[]

[[v44-22-0]]
=== Atos dos Apóstolos, 22
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* M. Paulo é preso em Jerusalém (21:18–23:35)
* Paulo segue o conselho dos anciãos (21:18-26)
* Tumulto no templo; os romanos prendem Paulo (21:27-36)
* Paulo recebe permissão para falar com a multidão (21:37-40)
* Paulo faz sua defesa para a multidão; ele descreve como ele se converteu (22:1-21)
* Paulo usa sua cidadania romana (22:22-29)
* O Sinédrio se reúne (22:30)
* Paulo fala diante do Sinédrio (23:1-10)
* Paulo é fortalecido pelo Senhor (23:11)
* Conspiração para matar Paulo (23:12-22)
* Soldados romanos levam Paulo a Cesareia (23:23-35)
****

[[v44-22-1]]

^<<v44-22-1,1>>^ “Homens, irmãos e pais, ouçam agora o que vou lhes dizer em minha defesa.”

[[v44-22-2]]

^<<v44-22-2,2>>^ Quando ouviram que ele estava lhes falando no idioma hebraico, ficaram ainda mais quietos. Então ele disse:

[TIP]
====
- *no idioma hebraico*: Veja a nota de estudo em Jo 5:2.
====

[[v44-22-3]]

^<<v44-22-3,3>>^ “Eu sou judeu, nascido em Tarso da Cilícia, mas educado nesta cidade, aos pés de Gamaliel. Fui instruído segundo o rigor da Lei de nossos antepassados, sendo zeloso por Deus, assim como todos vocês são hoje.

[TIP]
====
- *Gamaliel*: Este instrutor da Lei é mencionado duas vezes no livro de Atos: aqui e em At 5:34. — Veja a nota de estudo em At 5:34.
====

[[v44-22-4]]

^<<v44-22-4,4>>^ Eu perseguia até a morte os seguidores deste Caminho, amarrando e entregando à prisão tanto homens como mulheres;

[[v44-22-5]]

^<<v44-22-5,5>>^ o sumo sacerdote e toda a assembleia dos anciãos podem dar testemunho disso. Eles também me deram cartas para os irmãos de Damasco, e eu estava a caminho de lá a fim de trazer amarrados a Jerusalém, para serem punidos, os que estavam ali.

[TIP]
====
- *a assembleia dos anciãos*: Ou: “o conselho (corpo) de anciãos”. A palavra grega usada aqui, presbytérion, está relacionada com a palavra presbýteros (lit.: “homem mais velho”). Na Bíblia, presbýteros se refere principalmente a uma pessoa que tem autoridade e responsabilidade numa comunidade ou nação. Embora essa palavra possa ser usada às vezes para indicar idade (como acontece em Lu 15:25 e At 2:17), ela não se refere apenas a quem é idoso. A expressão “assembleia dos anciãos” pelo visto se refere aos membros do Sinédrio, o supremo tribunal judaico, que era composto pelos principais sacerdotes, pelos escribas e pelos anciãos. Na Bíblia, esses três grupos são mencionados juntos com frequência. — Mt 16:21; 27:41; Mr 8:31; 11:27; 14:43, 53; 15:1; Lu 9:22; 20:1; veja a nota de estudo em Lu 22:66.
====

[[v44-22-6]]

^<<v44-22-6,6>>^ “Mas, durante a viagem, por volta do meio-dia, eu estava chegando perto de Damasco quando, de repente, uma grande luz vinda do céu brilhou ao meu redor,

[[v44-22-7]]

^<<v44-22-7,7>>^ e eu caí no chão e ouvi uma voz me dizer: ‘Saulo, Saulo, por que você me persegue?’

[[v44-22-8]]

^<<v44-22-8,8>>^ Eu respondi: ‘Quem é o senhor?’ E ele me disse: ‘Eu sou Jesus, o Nazareno, a quem você persegue.’

[TIP]
====
- *o Nazareno*: Veja a nota de estudo em Mr 10:47.
====

[[v44-22-9]]

^<<v44-22-9,9>>^ E os homens que estavam comigo viram a luz, mas não ouviram a voz daquele que falava comigo.

[TIP]
====
- *não ouviram a voz*: Ou: “não entenderam a voz”. Em At 9:3-9, Lucas conta o que aconteceu com Paulo na estrada para Damasco. Juntando o relato de At 9 com as informações que aparecem aqui, é possível entender melhor o que aconteceu. A nota de estudo em At 9:7 explica que os homens que estavam com Paulo ouviram “o som de uma voz”, mas pelo visto não entenderam o que ela dizia. Eles não ouviram a voz da mesma forma que Paulo ouviu. Quando a palavra grega para “ouvir” é usada em At 22:7, onde Paulo disse “ouvi uma voz”, ela se refere a ouvir e entender. Assim, quando At 22:9 diz que os homens que estavam com Paulo “não ouviram a voz”, isso pelo visto quer dizer que eles ouviram sem entender as palavras, talvez porque a voz estivesse abafada ou distorcida. — Compare com Mr 4:33; 1Co 14:2, onde a palavra para “ouvir” poderia ser traduzida como “entender”.
====

[[v44-22-10]]

^<<v44-22-10,10>>^ Então, eu perguntei: ‘O que devo fazer, Senhor?’ O Senhor respondeu: ‘Levante-se, vá a Damasco, e ali você será informado de tudo o que foi designado para fazer.’

[[v44-22-11]]

^<<v44-22-11,11>>^ Mas, como eu não podia ver nada por causa do brilho daquela luz, cheguei a Damasco levado pela mão daqueles que estavam comigo.

[[v44-22-12]]

^<<v44-22-12,12>>^ “Então, um homem chamado Ananias, que era devoto conforme a Lei e de quem todos os judeus do lugar falavam bem,

[[v44-22-13]]

^<<v44-22-13,13>>^ veio me procurar. Ele chegou perto de mim e me disse: ‘Saulo, irmão, recupere a vista!’ E naquele instante eu recuperei a vista^&#42;1^ e o vi.

[NOTE]
====
. Ou: “levantei os olhos; olhei para cima”.
====

[TIP]
====
- *recupere a vista!*: Lit.: “olhe para cima!” A palavra grega que aparece aqui tem o sentido básico de “direcionar o olhar para cima” (Mt 14:19; Lu 19:5), mas também pode se referir a enxergar pela primeira vez (Jo 9:11, 15, 18) ou a recuperar a visão (Mr 10:52; Lu 18:42; At 9:12).
====

[[v44-22-14]]

^<<v44-22-14,14>>^ Ele disse: ‘O Deus de nossos antepassados escolheu você para conhecer a vontade dele, para ver o Justo e para ouvir a voz que sai da sua boca,

[[v44-22-15]]

^<<v44-22-15,15>>^ porque você será testemunha dele, perante todos os homens, das coisas que viu e ouviu.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora, o que está esperando? Levante-se, seja batizado e lave os seus pecados por invocar o nome dele.’

[TIP]
====
- *lave os seus pecados por invocar o nome dele*: Não é a água do batismo que lava os pecados da pessoa. Ela precisa invocar o nome Jesus, o que inclui ter fé em Jesus e demonstrar essa fé por meio de obras cristãs. — At 10:43; Tg 2:14, 18; veja a nota de estudo em Ro 10:13.
====

[[v44-22-17]]

^<<v44-22-17,17>>^ “Mas, depois de voltar a Jerusalém, eu estava orando no templo quando caí em transe

[TIP]
====
- *caí em transe*: Para uma explicação sobre a palavra grega ékstasis, traduzida aqui como “transe”, veja a nota de estudo em At 10:10. Algumas traduções das Escrituras Gregas Cristãs para o hebraico (chamadas de J14, 17, 22 no Apêndice C4) dizem “a mão de Jeová estava sobre mim”. Outra tradução (J18) diz “o espírito de Jeová me revestiu”.
====

[[v44-22-18]]

^<<v44-22-18,18>>^ e eu vi o Senhor me dizer: ‘Depressa, saia logo de Jerusalém, porque não aceitarão o seu testemunho a meu respeito.’

[[v44-22-19]]

^<<v44-22-19,19>>^ Então eu disse: ‘Senhor, eles sabem muito bem que, numa sinagoga após outra, eu prendia e açoitava os que criam no senhor.

[[v44-22-20]]

^<<v44-22-20,20>>^ E quando se derramava o sangue de Estêvão, sua testemunha, eu estava lá, aprovando aquilo e tomando conta das capas dos que o matavam.’

[TIP]
====
- *sua testemunha*: A palavra grega para “testemunha”, mártys, se refere a alguém que observa um fato ou um acontecimento. Alguns cristãos do século 1 d.C. podiam dar testemunho sobre o que eles mesmos tinham visto, confirmando fatos históricos sobre a vida, a morte e a ressurreição de Jesus. (At 1:21, 22; 10:40, 41) Outros, que se tornaram cristãos mais tarde, podiam dar testemunho por proclamar a importância da vida, da morte e da ressurreição de Jesus. (At 22:15) Por isso, Paulo podia dizer na ocasião mencionada aqui que Estêvão tinha sido “testemunha” de Jesus. Estêvão tinha dado um testemunho poderoso sobre Jesus diante do Sinédrio. Além disso, ele foi o primeiro a dar testemunho de que viu, numa visão especial, Jesus de volta no céu, à direita de Deus, como tinha sido profetizado no Sal 110:1. (At 7:55, 56) Ao dar testemunho, os cristãos muitas vezes enfrentaram oposição e foram presos, espancados ou até mesmo mortos, como aconteceu com Estêvão, Tiago e outros. Por isso, com o tempo a palavra mártys passou a ser usada com o sentido de “alguém que paga com a vida por dar testemunho; um mártir”, ou seja, alguém que prefere morrer do que renunciar sua fé. Nesse sentido, quando derramaram o sangue de Estêvão por causa do testemunho que ele tinha dado sobre Cristo, ele se tornou o primeiro mártir cristão. — Veja a nota de estudo em At 1:8.
====

[[v44-22-21]]

^<<v44-22-21,21>>^ Contudo, ele me disse: ‘Vá, porque eu o enviarei a nações distantes.’”

[[v44-22-22]]

^<<v44-22-22,22>>^ Eles o escutaram até essas palavras. Então levantaram a voz, dizendo: “Eliminem este homem da terra, pois não merece viver!”

[[v44-22-23]]

^<<v44-22-23,23>>^ Visto que gritavam, jogavam em volta suas capas e lançavam poeira para cima,

[[v44-22-24]]

^<<v44-22-24,24>>^ o comandante militar mandou levar Paulo para dentro do quartel e ordenou que fosse interrogado debaixo de açoites, para saber exatamente por que eles estavam gritando assim contra ele.

[TIP]
====
- *o comandante militar*: A palavra grega traduzida aqui como “comandante militar” é khilíarkhos (quiliarca), que significa literalmente “governante de 1.000”, ou seja, comandante de 1.000 soldados. O quiliarca era um tribuno militar romano. (Veja a nota de estudo em Jo 18:12.) Por volta de 56 d.C., Cláudio Lísias era o comandante militar da guarnição de Jerusalém. (At 23:22, 26) Como mostram os capítulos 21 a 24 de Atos, foi esse comandante que salvou Paulo dos ataques de uma turba e do tumulto no Sinédrio. Também foi ele que escreveu uma carta de esclarecimento ao governador Félix quando Paulo foi enviado secretamente a Cesareia.
====

[[v44-22-25]]

^<<v44-22-25,25>>^ Mas, depois que o amarraram para receber as chicotadas, Paulo perguntou ao oficial do exército que estava ali: “A lei permite que vocês açoitem um romano que não foi condenado?”^&#42;1^

[NOTE]
====
. Ou: “julgado”.
====

[TIP]
====
- *ao oficial do exército*: Ou: “ao centurião”. Um oficial que comandava cerca de 100 soldados do exército romano.
- *um romano*: Ou seja, um cidadão romano. Esta é a segunda das três ocasiões registradas na Bíblia em que Paulo usou seus direitos de cidadão romano. As autoridades romanas geralmente não interferiam nos assuntos internos dos judeus. Mas os romanos se envolveram no caso de Paulo por causa da confusão gerada pela visita dele ao templo e porque ele era cidadão romano. A cidadania dava à pessoa certos privilégios que eram reconhecidos e respeitados em todo o Império Romano. Por exemplo, era ilegal prender ou espancar um cidadão romano que não tivesse sido condenado. Apenas os escravos podiam ser tratados dessa forma. — Para ver as outras duas ocasiões em que Paulo usou seus direitos de cidadão romano, veja as notas de estudo em At 16:37; 25:11.
====

[[v44-22-26]]

^<<v44-22-26,26>>^ Quando o oficial ouviu isso, foi contar ao comandante, e lhe disse: “O que o senhor pretende fazer? Esse homem é romano!”

[[v44-22-27]]

^<<v44-22-27,27>>^ De modo que o comandante se aproximou dele e disse: “Diga-me, você é romano?” Ele respondeu: “Sim.”

[[v44-22-28]]

^<<v44-22-28,28>>^ O comandante disse então: “Eu comprei esses direitos de cidadão com muito dinheiro.” Paulo disse: “Mas eu já nasci com esses direitos.”

[TIP]
====
- *comprei esses direitos de cidadão*: Ou: “comprei essa cidadania”. Como mostra este relato, em certas circunstâncias era possível comprar a cidadania romana. Mas existiam outras maneiras de se tornar um cidadão romano. O imperador podia dar a cidadania como recompensa para uma pessoa ou até mesmo para toda a população livre de uma cidade ou um distrito. Os escravos que comprassem sua liberdade de um cidadão romano, ou que fossem libertados por um romano, ganhavam a cidadania. O mesmo acontecia com veteranos das forças armadas auxiliares que fossem dispensados do exército. Além disso, era possível herdar a cidadania. Paulo disse a Cláudio Lísias que tinha nascido com os direitos de cidadão, o que indica que um antepassado dele do sexo masculino tinha conseguido a cidadania romana. É provável que não houvesse muitos cidadãos romanos vivendo na Judeia no século 1 d.C. Foi só no século 3 d.C. que todos os súditos das províncias receberam cidadania romana.
====

[[v44-22-29]]

^<<v44-22-29,29>>^ Com isso, os homens que estavam prestes a interrogá-lo e torturá-lo recuaram imediatamente. E o comandante ficou com medo ao saber que ele era romano e que o havia acorrentado.

[[v44-22-30]]

^<<v44-22-30,30>>^ Assim, no dia seguinte, querendo saber ao certo por que ele estava sendo acusado pelos judeus, soltou-o e mandou que os principais sacerdotes e todo o Sinédrio se reunissem. Então ele trouxe Paulo para baixo e o colocou de pé no meio deles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]