include::./index.adoc[]

[[v44-11-0]]
=== Atos dos Apóstolos, 11
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. A pregação chega aos não judeus incircuncisos em Cesareia e Antioquia da Síria (10:1–12:25)
* Um oficial do exército chamado Cornélio tem uma visão e manda chamar Pedro (10:1-8)
* Em uma visão, Pedro vê animais que foram purificados (10:9-16)
* Pedro vai até Cornélio, que conta a ele a visão que teve (10:17-33)
* Pedro proclama as boas novas aos não judeus; “Deus não é parcial” (10:34-43)
* Não judeus recebem espírito santo e são batizados (10:44-48)
* Pedro relata aos apóstolos em Jerusalém o que aconteceu (11:1-18)
* Barnabé e Saulo pregam para pessoas de língua grega em Antioquia da Síria, onde os discípulos são chamados de cristãos pela primeira vez (11:19-26)
* O profeta cristão Ágabo prediz uma grande fome; os discípulos enviam ajuda aos irmãos na Judeia (11:27-30)
* O rei Herodes mata Tiago e prende Pedro (12:1-5)
* Um anjo de Jeová liberta Pedro da prisão (12:6-19)
* Um anjo de Jeová fere Herodes (12:20-25)
****

[[v44-11-1]]

^<<v44-11-1,1>>^ Então, os apóstolos e os irmãos que estavam na Judeia ouviram que pessoas das nações também tinham aceitado a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ Assim, quando Pedro subiu a Jerusalém, os que apoiavam a circuncisão começaram a criticá-lo,^&#42;1^

[NOTE]
====
. Ou: “começaram a discutir com ele; discordaram dele”.
====

[[v44-11-3]]

^<<v44-11-3,3>>^ dizendo: “Você entrou na casa de homens incircuncisos e comeu com eles.”

[[v44-11-4]]

^<<v44-11-4,4>>^ Em vista disso, Pedro começou a lhes explicar os detalhes do que havia acontecido:

[[v44-11-5]]

^<<v44-11-5,5>>^ “Eu estava na cidade de Jope orando e, num transe, tive uma visão de algo semelhante a um grande lençol de linho descendo do céu, preso pelas suas quatro pontas, e ele veio até perto de mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ Olhei atentamente para dentro dele e vi quadrúpedes da terra, animais selvagens, répteis^&#42;1^ e aves do céu.

[NOTE]
====
. Ou: “animais rasteiros”.
====

[[v44-11-7]]

^<<v44-11-7,7>>^ Também ouvi uma voz me dizer: ‘Levante-se, Pedro, mate e coma!’

[[v44-11-8]]

^<<v44-11-8,8>>^ Mas eu disse: ‘De jeito nenhum, Senhor, porque na minha boca nunca entrou nada aviltado ou impuro.’

[[v44-11-9]]

^<<v44-11-9,9>>^ A voz do céu falou então pela segunda vez: ‘Pare de chamar de impuras as coisas que Deus purificou.’

[[v44-11-10]]

^<<v44-11-10,10>>^ Isso ocorreu pela terceira vez, e tudo foi puxado de volta para o céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ Além disso, naquele instante, três homens que haviam sido enviados de Cesareia à minha procura chegaram à casa onde estávamos.

[[v44-11-12]]

^<<v44-11-12,12>>^ Então o espírito me disse que eu fosse com eles sem hesitar. Estes seis irmãos também foram comigo, e nós entramos na casa do homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ “Ele nos contou que tinha visto um anjo aparecer na sua casa e dizer: ‘Envie homens a Jope e mande chamar Simão, que é conhecido como Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ e ele lhe dirá as coisas pelas quais você e todos os da sua casa podem ser salvos.’

[[v44-11-15]]

^<<v44-11-15,15>>^ Quando comecei a falar, o espírito santo desceu sobre eles, da mesma forma como tinha descido sobre nós no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Em vista disso eu me lembrei das palavras do Senhor; ele dizia: ‘João batizou com água, mas vocês serão batizados com espírito santo.’

[[v44-11-17]]

^<<v44-11-17,17>>^ Portanto, se Deus deu a eles a mesma dádiva^&#42;1^ que deu a nós, que cremos no Senhor Jesus Cristo, quem era eu para poder impedir a Deus?”^&#42;2^

[NOTE]
====
. Ou: “dádiva gratuita”.
. Ou: “poder me opor a Deus”.
====

[[v44-11-18]]

^<<v44-11-18,18>>^ Quando ouviram essas coisas, não apresentaram mais objeções^&#42;1^ e glorificaram a Deus, dizendo: “Então, Deus também concedeu a pessoas das nações o arrependimento que leva à vida.”

[NOTE]
====
. Lit.: “eles ficaram em silêncio”.
====

[[v44-11-19]]

^<<v44-11-19,19>>^ Os que tinham sido espalhados pela perseguição que surgiu por causa de Estêvão foram até a Fenícia, Chipre e Antioquia, mas falavam a palavra apenas aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ No entanto, alguns homens entre eles que eram de Chipre e de Cirene foram a Antioquia e começaram a falar às pessoas de língua grega, declarando as boas novas do Senhor Jesus.

[TIP]
====
- *Antioquia*: Esta cidade ficava na Síria, às margens do rio Orontes. Partindo do porto de Selêucia, no Mediterrâneo, era possível ir até Antioquia pelo rio, num percurso de uns 32 quilômetros. No século 1 d.C., ela era a terceira maior cidade do Império Romano em tamanho e riqueza, atrás apenas de Roma e Alexandria. Nessa época, existia em Antioquia uma grande e antiga comunidade de judeus, e eles conviviam em relativa paz com os não judeus. Pelo visto, Antioquia da Síria tinha o ambiente ideal para os discípulos começarem a pregar a não judeus incircuncisos, algo totalmente novo. (Veja a nota de estudo em pessoas de língua grega neste versículo.) Essa Antioquia não é a mesma Antioquia que ficava na Pisídia, na Ásia menor. — Veja as notas de estudo em At 6:5; 13:14 e o Apêndice B13.
- *pessoas de língua grega*: Lit.: “helenistas”. O significado da palavra grega que aparece aqui, Hellenistés, varia de acordo com o contexto. Em At 6:1, tudo indica que ela signifique “judeus que falavam grego”. (Veja a nota de estudo em At 6:1.) Por isso, alguns estudiosos chegaram à conclusão de que aqui Hellenistés também deve se referir a judeus ou prosélitos que falavam grego. Mas parece que este versículo está falando de algo novo que estava acontecendo em Antioquia da Síria. O versículo anterior (At 11:19) mostra que, até então, apenas os judeus estavam recebendo testemunho em Antioquia. No entanto, agora a palavra de Deus pelo visto estava sendo pregada também aos não judeus. É provável que Barnabé tenha sido enviado para Antioquia para encorajar os novos discípulos que falavam grego. (At 11:22, 23) Existem alguns manuscritos muito antigos que usam aqui a palavra Héllenas (que significa “gregos”; veja At 16:3), em vez de Hellenistés. Por isso, várias traduções usam as expressões “os gregos” ou “os não judeus” neste versículo. Essas traduções dão a impressão de que nenhuma das pessoas que falavam grego e receberam testemunho em Antioquia era da religião judaica. Mas é possível que este versículo esteja se referindo tanto a judeus como a não judeus que falavam grego. Por esse motivo, a Tradução do Novo Mundo usa a expressão “pessoas de língua grega” neste versículo. Pode ser que essas pessoas fossem de várias nacionalidades, mas tivessem adotado a língua grega e, talvez, os costumes gregos.
====

[[v44-11-21]]

^<<v44-11-21,21>>^ E a mão de Jeová estava com eles, e muitos se tornaram crentes e se converteram ao Senhor.

[TIP]
====
- *mão de Jeová*: Esta expressão ocorre muitas vezes nas Escrituras Hebraicas como uma combinação da palavra hebraica para “mão” com o Tetragrama. (Algumas dessas ocorrências estão em Êx 9:3; Núm 11:23; Jz 2:15; Ru 1:13; 1Sa 5:6, 9; 7:13; 12:15; 1Rs 18:46; Esd 7:6; Jó 12:9; Is 19:16; 40:2 e Ez 1:3.) Na Bíblia, a palavra “mão” é muitas vezes usada para representar “poder”. Visto que o poder (força) do braço geralmente é aplicado por meio da mão, a palavra “mão” também passa a ideia de “poder aplicado”. A expressão grega traduzida aqui como “mão de Jeová” também aparece em Lu 1:66 e At 13:11. — Veja as notas de estudo em Lu 1:6, 66 e o Apêndice C3 (introdução e At 11:21).
====

[[v44-11-22]]

^<<v44-11-22,22>>^ As notícias sobre eles chegaram aos ouvidos da congregação em Jerusalém, e enviaram então Barnabé a Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Quando ele chegou e viu a bondade imerecida de Deus, alegrou-se e começou a encorajar todos a continuarem no Senhor com firmeza de coração,

[[v44-11-24]]

^<<v44-11-24,24>>^ pois era um homem bom, cheio de espírito santo e de fé. E uma multidão considerável passou a crer no Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ De modo que ele foi a Tarso a fim de procurar cuidadosamente por Saulo.

[[v44-11-26]]

^<<v44-11-26,26>>^ Depois de achá-lo, levou-o a Antioquia. Assim, por um ano inteiro, reuniram-se com a congregação e ensinaram uma numerosa multidão. E foi primeiro em Antioquia que os discípulos, por direção divina, foram chamados de cristãos.

[TIP]
====
- *por direção divina, foram chamados de*: A maioria das Bíblias diz simplesmente “foram chamados (de)”. Mas aqui não aparece nenhuma das palavras gregas que geralmente são traduzidas como “chamar”. (Mt 1:16; 2:23; Mr 11:17; Lu 1:32, 60; At 1:12, 19) A palavra grega usada neste versículo é khrematízo e, na maioria dos nove lugares onde ela aparece nas Escrituras Gregas Cristãs, ela está claramente ligada a coisas que têm origem divina. (Mt 2:12, 22; Lu 2:26; At 10:22; 11:26; Ro 7:3; He 8:5; 11:7; 12:25) Por exemplo, em At 10:22, ela é usada junto com a expressão “por meio de um anjo”. E, em Mt 2:12, 22, ela está ligada com sonhos dados por Deus. No texto de Ro 11:4, aparece o substantivo relacionado, khrematismós, que é traduzido na maioria dos léxicos e traduções da Bíblia como “declaração divina; resposta divina; resposta de Deus”. É possível que Jeová tenha orientado Saulo e Barnabé a usar o nome “cristãos”. Alguns acham que o nome “cristãos” pode ter sido um apelido criado pelos não judeus de Antioquia para zombar dos seguidores de Cristo. Mas o uso da palavra khrematízo aqui mostra claramente que os cristãos foram chamados assim pela vontade de Deus. Também parece muito improvável que tenham sido os judeus de Antioquia que inventaram esse nome. Eles tinham rejeitado Jesus como o Messias e, se dessem aos seguidores dele o nome “cristãos” (do grego) ou “messianistas” (do hebraico), estariam reconhecendo indiretamente que Jesus tinha mesmo sido o Ungido, ou Cristo.
- *cristãos*: A palavra grega Khristianós, que significa “seguidor de Cristo”, aparece apenas três vezes nas Escrituras Gregas Cristãs. (At 11:26; 26:28; 1Pe 4:16) Ela vem da palavra Khristós (Cristo), que significa “ungido”. Os cristãos seguem os ensinamentos e o exemplo de Jesus, “o Cristo”, ou seja, aquele que foi ungido por Jeová. (Lu 2:26; 4:18) É possível que os cristãos tenham recebido esse nome, que foi dado “por direção divina”, já em 44 d.C., quando os acontecimentos mencionados neste versículo ocorreram. Tudo indica que nos anos seguintes esse nome passou a ser bem usado. Por exemplo, quando Paulo foi levado ao rei Herodes Agripa II, por volta de 58 d.C., Agripa sabia quem eram os cristãos. (At 26:28) Os escritos do historiador romano Tácito indicam que, por volta do ano 64 d.C., o termo “cristão” era usado em Roma pelas pessoas em geral. Outra evidência é a primeira carta de Pedro, escrita entre 62 e 64 d.C., que foi dirigida aos cristãos espalhados pelo Império Romano. Pelo visto, a essa altura, o termo “cristão” tinha se tornado bem conhecido e servia para identificar de forma específica e inconfundível quem seguia a Cristo. (1Pe 1:1, 2; 4:16) Com esse nome dado por Deus, ninguém mais pensaria que os seguidores de Cristo pertenciam a uma seita do judaísmo.
====

[[v44-11-27]]

^<<v44-11-27,27>>^ Naqueles dias alguns profetas desceram de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ Um deles, chamado Ágabo, levantou-se e predisse, por meio do espírito, que uma grande fome estava para vir sobre toda a terra habitada. De fato, ela ocorreu no tempo de Cláudio.

[TIP]
====
- *uma grande fome*: Esta fome aconteceu por volta de 46 d.C. O historiador Josefo também fala de uma grande fome que aconteceu durante o governo do imperador romano Cláudio. Épocas de fome eram especialmente difíceis para os pobres, que não costumavam ter reservas de dinheiro ou alimento. Por isso, os cristãos em Antioquia quiseram enviar ajuda aos irmãos pobres da Judeia.
- *no tempo de Cláudio*: O imperador romano Cláudio governou de 41 a 54 d.C. No começo, ele era favorável aos judeus. Mas a sua relação com eles foi piorando e, no fim de seu governo, Cláudio expulsou todos os judeus de Roma. (At 18:2) Cláudio, segundo se diz, foi envenenado com cogumelos por sua quarta esposa. Seu sucessor foi o imperador romano Nero.
====

[[v44-11-29]]

^<<v44-11-29,29>>^ Assim, os discípulos resolveram, cada um de acordo com as suas possibilidades, enviar ajuda aos irmãos que moravam na Judeia.

[TIP]
====
- *enviar ajuda*: Ou: “ministrar”. Esta é a primeira vez que as Escrituras falam de cristãos enviarem ajuda humanitária a irmãos em outra parte do mundo. A palavra grega traduzida aqui como “ajuda”, diakonía, muitas vezes é traduzida como “ministério”, mas também pode passar a ideia de “trabalho de prestar ajuda” (At 12:25) ou “serviço de ajuda” (2Co 8:4). A maneira como a palavra diakonía é usada nas Escrituras Gregas Cristãs mostra que os cristãos têm dois tipos diferentes de ministério. Um deles é “o ministério [uma forma de diakonía] da reconciliação”, ou seja, a obra de pregação e ensino. (2Co 5:18-20; 1Ti 2:3-6) O outro, que é mencionado aqui, envolve ajudar outros cristãos. O apóstolo Paulo disse: “Há diferentes maneiras de servir [ou: “ministérios”, nota de rodapé; plural de diakonía], contudo há o mesmo Senhor.” (1Co 12:4-6, 11) Ele mostrou que os dois tipos de ministério cristão, apesar de serem diferentes, são “serviço sagrado”. — Ro 12:1, 6-8.
====

[[v44-11-30]]

^<<v44-11-30,30>>^ E fizeram isso, enviando-a aos anciãos pelas mãos de Barnabé e de Saulo.

[TIP]
====
- *anciãos*: Lit.: “homens mais velhos (idosos)”. Na Bíblia, a palavra grega presbýteros se refere principalmente a quem tem autoridade e responsabilidade numa comunidade ou nação, apesar de às vezes também ser usada para se referir a alguém idoso. (Veja a nota de estudo em Mt 16:21.) Na nação de Israel, os anciãos tomavam a liderança entre o povo e ajudavam na administração do país, tanto em nível local (De 25:7-9; Jos 20:4; Ru 4:1-12) como em nível nacional (Jz 21:16; 1Sa 4:3; 8:4; 1Rs 20:7). Esta é a primeira vez que a palavra presbýteros é usada com relação à congregação cristã. No Israel espiritual, assim como acontecia no Israel literal, os anciãos seriam responsáveis por tomar a liderança. Na ocasião mencionada aqui, as contribuições foram entregues aos anciãos, e eles supervisionaram a distribuição delas para as congregações da Judeia.
====

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]