include::./index.adoc[]

[[v44-19-0]]
=== Atos dos Apóstolos, 19
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* L. Terceira viagem missionária de Paulo (18:23–21:17)
* Paulo parte para a Galácia e a Frígia (18:23)
* Apolo, um homem eloquente, recebe ajuda de Priscila e Áquila e depois vai para a Acaia (18:24-28)
* Paulo chega a Éfeso; alguns discípulos são batizados novamente, dessa vez, em nome de Jesus (19:1-7)
* Atividades de Paulo em Éfeso (19:8-10)
* Apesar do ocultismo em Éfeso, a palavra de Jeová prevalece (19:11-20)
* Confusão em Éfeso; a multidão entra correndo no teatro (19:21-34)
* O administrador da cidade de Éfeso acalma a multidão (19:35-41)
* Paulo na Macedônia e na Grécia (20:1-6)
* Êutico é ressuscitado em Trôade (20:7-12)
* Paulo sai de Trôade e vai a Mileto (20:13-16)
* Paulo incentiva os anciãos de Éfeso a prestarem atenção a si mesmos e a todo o rebanho de Deus (20:17-38)
* Paulo continua sua viagem a Jerusalém (21:1-14)
* Chegada em Jerusalém (21:15-17)
****

[[v44-19-1]]

^<<v44-19-1,1>>^ Enquanto Apolo estava em Corinto, Paulo passou pelas regiões do interior e desceu a Éfeso. Ele encontrou ali alguns discípulos

[[v44-19-2]]

^<<v44-19-2,2>>^ e lhes perguntou: “Vocês receberam espírito santo quando se tornaram crentes?” Eles responderam: “Nós nunca ouvimos falar que há um espírito santo.”

[[v44-19-3]]

^<<v44-19-3,3>>^ Ele perguntou: “Então, em que vocês foram batizados?” Eles responderam: “No batismo de João.”

[TIP]
====
- *No batismo de João*: Veja a nota de estudo em At 18:25.
====

[[v44-19-4]]

^<<v44-19-4,4>>^ Paulo disse: “O batismo de João era o batismo em símbolo de arrependimento; ele dizia às pessoas que cressem naquele que viria depois dele, isto é, em Jesus.”

[[v44-19-5]]

^<<v44-19-5,5>>^ Depois de ouvirem isso, foram batizados em nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ E, quando Paulo lhes impôs as mãos, o espírito santo veio sobre eles, e eles começaram a falar em línguas e a profetizar.

[[v44-19-7]]

^<<v44-19-7,7>>^ Ao todo, havia cerca de 12 homens.

[[v44-19-8]]

^<<v44-19-8,8>>^ Por três meses, ele foi à sinagoga e falou com coragem, proferindo discursos e raciocinando de forma persuasiva a respeito do Reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ Mas, visto que alguns se recusavam obstinadamente a crer^&#42;1^ e falavam mal do Caminho diante da multidão, ele os deixou e separou deles os discípulos; e diariamente proferia discursos no auditório da escola de Tirano.

[NOTE]
====
. Ou: “alguns continuavam a se endurecer e a não crer”.
====

[TIP]
====
- *Caminho*: Veja as notas de estudo em At 9:2; 19:23 e o Glossário.
- *no auditório da escola de Tirano*: Ou: “na sala de palestras de Tirano”. O relato não dá detalhes sobre qual foi o objetivo da criação dessa escola. Mas tudo indica que Paulo tinha liberdade para usar suas instalações, talvez algumas horas por dia. Alguns poucos manuscritos bem antigos acrescentam as palavras “da quinta até a décima hora”, ou seja, de cerca das 11 horas da manhã até cerca das 4 horas da tarde. Mas essas palavras não aparecem na maioria dos manuscritos mais antigos, o que indica que elas não fazem parte do texto original deste versículo. No entanto, alguns sugerem que, mesmo que essas palavras não façam parte do texto original, os horários citados parecem fazer sentido e, por isso, essa talvez fosse realmente a programação de Paulo durante o tempo em que esteve em Éfeso. Nesse caso, Paulo estaria aproveitando o período mais quente do dia, que também era o mais calmo, para ensinar os discípulos. Esse era o horário em que muitos paravam de trabalhar para descansar.
====

[[v44-19-10]]

^<<v44-19-10,10>>^ Isso aconteceu por dois anos, até que todos os que moravam na província da Ásia, tanto judeus como gregos, ouviram a palavra do Senhor.

[TIP]
====
- *na província da Ásia*: Veja o Glossário, “Ásia”.
====

[[v44-19-11]]

^<<v44-19-11,11>>^ Deus realizava extraordinárias obras poderosas pelas mãos de Paulo,

[[v44-19-12]]

^<<v44-19-12,12>>^ de modo que até mesmo panos e aventais que haviam tocado o seu corpo eram levados aos doentes, e as doenças desapareciam e os espíritos maus saíam.

[TIP]
====
- *panos e aventais*: Pode ser que estes panos fossem lenços que Paulo amarrava na testa para evitar que suor caísse nos seus olhos. Naquela época, era comum os trabalhadores usarem aventais. Assim, este versículo pode indicar que Paulo estava exercendo sua profissão de fabricante de tendas no tempo livre, talvez de manhã cedo. — At 20:34, 35.
====

[[v44-19-13]]

^<<v44-19-13,13>>^ Mas alguns judeus que viajavam de um lugar a outro expulsando demônios também tentaram invocar o nome do Senhor Jesus sobre aqueles que tinham espíritos maus; diziam: “Eu lhes ordeno solenemente por Jesus, a quem Paulo prega, que saiam.”

[[v44-19-14]]

^<<v44-19-14,14>>^ Sete filhos de um dos principais sacerdotes judeus, chamado Ceva, faziam isso.

[[v44-19-15]]

^<<v44-19-15,15>>^ Mas o espírito mau lhes disse, em resposta: “Eu conheço Jesus e sei quem é Paulo. Mas quem são vocês?”

[[v44-19-16]]

^<<v44-19-16,16>>^ Assim, o homem que tinha o espírito mau pulou sobre eles, dominou um após outro e prevaleceu sobre eles, de modo que fugiram daquela casa nus e feridos.

[[v44-19-17]]

^<<v44-19-17,17>>^ Isso chegou ao conhecimento de todos, tanto dos judeus como dos gregos que moravam em Éfeso; e todos eles ficaram com medo, e o nome do Senhor Jesus continuou a ser magnificado.

[[v44-19-18]]

^<<v44-19-18,18>>^ Muitos dos que tinham se tornado crentes vinham para confessar e declarar abertamente as suas práticas.

[[v44-19-19]]

^<<v44-19-19,19>>^ Na verdade, um bom número dos que haviam praticado artes mágicas juntaram seus livros e os queimaram diante de todos. Ao calcularem o valor deles, viram que valiam 50.000 moedas de prata.

[TIP]
====
- *artes mágicas*: A palavra grega para “artes mágicas” é períerga, “curiosidades”. Um léxico diz que a palavra se refere a “curiosidade indevida ou mal direcionada . . . como na prática de magia”. (A Greek-English Lexicon of the New Testament and Other Early Christian Literature, 3.ª edição, 2000) Ela descreve as artes praticadas por pessoas que investigam coisas proibidas com a ajuda de espíritos maus. Em Éfeso, muitas pessoas praticavam artes mágicas e outras formas de ocultismo. Na carta inspirada de Paulo aos efésios, ele disse que eles precisavam vestir a armadura completa de Deus para terem condições de lutar contra as forças espirituais malignas. — Ef 6:11, 12.
- *50.000 moedas de prata*: Se as moedas mencionadas aqui forem dracmas ou denários, um trabalhador comum levaria 50.000 dias, ou seja, por volta de 137 anos, trabalhando sete dias por semana, para ganhar essa quantia.
====

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim, de modo poderoso, a palavra de Jeová crescia e prevalecia.

[TIP]
====
- *a palavra de Jeová*: Veja a nota de estudo em At 8:25 e o Apêndice C3 (introdução e At 19:20).
====

[[v44-19-21]]

^<<v44-19-21,21>>^ Depois de tudo isso ter acontecido, Paulo decidiu^&#42;1^ que, após passar pela Macedônia e pela Acaia, viajaria para Jerusalém. Ele disse: “Depois de ir para lá, tenho de ir também a Roma.”

[NOTE]
====
. Ou: “decidiu no espírito”.
====

[[v44-19-22]]

^<<v44-19-22,22>>^ Assim, enviou à Macedônia dois de seus ajudantes, Timóteo e Erasto, mas ele mesmo continuou ainda algum tempo na província da Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ Naquela época, houve um grande tumulto por causa do Caminho.

[TIP]
====
- *Caminho*: Como mostra a nota de estudo em At 9:2, o termo “Caminho” era usado para se referir à congregação cristã daquela época. O verdadeiro cristianismo não é uma adoração prestada simplesmente por formalidade nem é mera questão de aparência. É um modo de vida que gira em torno da adoração a Deus e que é guiado pelo espírito dele. (Jo 4:23, 24) Neste versículo, a Peshitta siríaca diz “caminho de Deus”; a Vulgata latina Sixto-Clementina diz “caminho do Senhor”; e algumas traduções das Escrituras Gregas Cristãs para o hebraico (chamadas de J17, 18 no Apêndice C4) usam o nome de Deus aqui e dizem “caminho de Jeová”.
====

[[v44-19-24]]

^<<v44-19-24,24>>^ Um homem chamado Demétrio, um prateiro que fabricava miniaturas de prata do santuário de Ártemis, dava muito lucro aos artífices.

[TIP]
====
- *Ártemis*: A Ártemis de Éfeso era uma deusa da fertilidade que era adorada em cidades de toda a Ásia Menor. (At 19:27) Nas estátuas de Ártemis, a parte superior do corpo era enfeitada por diversas saliências, que já foram interpretadas como ovos, seios ou testículos de touros sacrificados. A parte inferior da estátua lembrava a parte inferior de uma múmia e era decorada com vários símbolos e animais. Na mitologia grega clássica, havia uma deusa virgem chamada Ártemis, que era considerada a deusa da caça. Mas essa deusa tinha pouco a ver com a Ártemis de Éfeso. O nome romano de Ártemis era Diana.
====

[[v44-19-25]]

^<<v44-19-25,25>>^ Ele os reuniu, juntamente com outros que faziam o mesmo tipo de trabalho, e disse: “Homens, vocês sabem muito bem que a nossa prosperidade vem deste negócio.

[[v44-19-26]]

^<<v44-19-26,26>>^ Agora vocês estão vendo e ouvindo que, não somente em Éfeso, mas em quase toda a província da Ásia, esse tal de Paulo persuadiu uma multidão considerável e os fez mudar de opinião, dizendo que os deuses feitos por mãos humanas não são deuses de verdade.

[[v44-19-27]]

^<<v44-19-27,27>>^ Além disso, não somente há o perigo de que o nosso negócio caia em descrédito, mas também de que o templo da grande deusa Ártemis passe a ser considerado sem valor, e de que aquela que é adorada em toda a província da Ásia e na terra habitada seja destituída de seu esplendor.”

[[v44-19-28]]

^<<v44-19-28,28>>^ Ao ouvirem isso, os homens ficaram furiosos e começaram a gritar: “Grande é a Ártemis dos efésios!”

[[v44-19-29]]

^<<v44-19-29,29>>^ Então a confusão se espalhou pela cidade, e todos entraram correndo no teatro, arrastando junto os macedônios Gaio e Aristarco, companheiros de viagem de Paulo.

[[v44-19-30]]

^<<v44-19-30,30>>^ Paulo queria entrar e se apresentar ao povo, mas os discípulos não permitiram que ele fizesse isso.

[[v44-19-31]]

^<<v44-19-31,31>>^ Mesmo alguns dos organizadores de festividades e jogos, que lhe eram amigáveis, lhe enviaram uma mensagem, implorando que ele não se arriscasse indo ao teatro.

[TIP]
====
- *alguns dos organizadores de festividades e jogos*: Lit.: “alguns dos asiarcas”. Esses homens eram altos funcionários ou pessoas importantes da província romana da Ásia, que pelo visto eram escolhidos por causa de sua influência e riqueza. Eles organizavam e financiavam os jogos públicos realizados na província.
====

[[v44-19-32]]

^<<v44-19-32,32>>^ Enquanto isso, a assembleia estava em confusão: alguns gritavam uma coisa, outros gritavam outra, e a maioria deles nem sabia por que tinham se reunido.

[[v44-19-33]]

^<<v44-19-33,33>>^ Então fizeram Alexandre sair do meio da multidão; os judeus o empurraram para a frente. E Alexandre fez sinal com a mão, pois queria fazer a sua defesa diante do povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Mas, quando perceberam que ele era judeu, todos eles começaram a gritar, numa só voz, por cerca de duas horas: “Grande é a Ártemis dos efésios!”

[[v44-19-35]]

^<<v44-19-35,35>>^ Por fim, depois de acalmar a multidão, o administrador da cidade^&#42;1^ disse: “Homens de Éfeso, quem da humanidade não sabe realmente que a cidade dos efésios é a guardiã do templo da grande Ártemis e da imagem que caiu do céu?

[NOTE]
====
. Ou: “o escrivão”.
====

[[v44-19-36]]

^<<v44-19-36,36>>^ Visto que essas coisas são indiscutíveis, vocês devem ficar calmos e não agir precipitadamente.

[[v44-19-37]]

^<<v44-19-37,37>>^ Vocês trouxeram esses homens aqui, que não são nem ladrões de templos nem blasfemadores da nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Assim, se Demétrio e os artífices que estão com ele têm uma queixa contra alguém, há dias nos quais os tribunais se reúnem e há procônsules; que apresentem suas acusações uns contra os outros.

[TIP]
====
- *procônsules*: Procônsul era o título dado ao principal governante das províncias que ficavam debaixo da autoridade do Senado romano. Ele tinha poder judicial e militar, e sua autoridade era suprema na província, mas suas ações estavam sujeitas à avaliação do Senado. Já que cada província tinha apenas um procônsul, parece que o plural “procônsules” foi usado aqui para se referir ao cargo de maneira geral. Éfeso era a capital da província romana da Ásia e era a cidade onde o procônsul morava. — Veja o Glossário, “Ásia”.
====

[[v44-19-39]]

^<<v44-19-39,39>>^ Mas, se vocês estão querendo algo além disso, a questão tem de ser^&#42;1^ decidida numa assembleia legal.

[NOTE]
====
. Ou: “a questão será”.
====

[[v44-19-40]]

^<<v44-19-40,40>>^ Porque nós realmente corremos o risco de ser acusados de sedição pelo que aconteceu hoje, pois não há nenhum motivo que possamos apresentar para justificar este tumulto.”

[[v44-19-41]]

^<<v44-19-41,41>>^ E, depois de dizer isso, dissolveu a assembleia.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]