include::./index.adoc[]

[[v44-6-0]]
=== Atos dos Apóstolos, 6
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* E. O ministério da palavra não deve ser negligenciado (6:1–7:1)
* Reclamações sobre a distribuição de alimento às viúvas (6:1)
* Os Doze escolhem sete homens para supervisionar a distribuição de alimento às viúvas (6:2-7)
* Estêvão, um dos sete homens escolhidos, é acusado de blasfêmia e levado diante do Sinédrio (6:8–7:1)
****

[[v44-6-1]]

^<<v44-6-1,1>>^ Naqueles dias, ao aumentar o número de discípulos, os judeus que falavam grego começaram a reclamar dos judeus que falavam hebraico, porque as suas viúvas estavam sendo deixadas de lado na distribuição diária.

[TIP]
====
- *judeus que falavam grego*: Lit.: “helenistas”. A palavra grega usada aqui, Hellenistés, não aparece na literatura grega nem na literatura judaico-helenística, mas a tradução “judeus que falavam grego” está de acordo com o contexto e é apoiada por muitos léxicos. Na ocasião mencionada nesta passagem, todos os cristãos em Jerusalém, incluindo os que falavam grego, eram judeus de nascença ou prosélitos que tinham se convertido ao judaísmo. (At 10:28, 35, 44-48) A palavra traduzida como “judeus que falavam grego” é usada em contraste com a palavra traduzida como “judeus que falavam hebraico” (lit.: “hebreus”; plural do grego Ebraíos). Assim, os “helenistas” mencionados aqui eram judeus que falavam grego que tinham viajado de diferentes partes do Império Romano para Jerusalém, e talvez incluíssem pessoas de Decápolis. Por outro lado, tudo indica que a maioria dos “judeus que falavam hebraico” era da Judeia e da Galileia. É provável que existissem diferenças culturais entre os cristãos judeus que falavam grego e os cristãos judeus que falavam hebraico. — Veja a nota de estudo em At 9:29.
- *judeus que falavam hebraico*: Lit.: “hebreus”. A palavra grega Ebraíos (singular) geralmente se refere a um israelita, um hebreu. (2Co 11:22; Fil 3:5) Mas aqui neste contexto a palavra se refere a cristãos judeus que falavam hebraico, que no versículo são contrastados com os cristãos judeus que falavam grego. — Veja a nota de estudo em judeus que falavam grego neste versículo e a nota de estudo em Jo 5:2.
- *na distribuição diária*: Ou: “no serviço (ministério) diário”. A palavra grega diakonía muitas vezes é traduzida como “ministério”. Aqui, ela se refere a um aspecto específico do ministério cristão: cuidar das necessidades materiais de irmãos e irmãs da congregação que estejam precisando de ajuda. — Veja a nota de estudo em At 6:2, onde o verbo relacionado, diakonéo, foi traduzido como “para servir alimento”; veja também a nota de estudo em Lu 8:3.
====

[[v44-6-2]]

^<<v44-6-2,2>>^ De modo que os Doze reuniram a multidão dos discípulos e disseram: “Não é correto que deixemos a palavra de Deus para servir alimento às mesas.

[TIP]
====
- *correto*: Lit.: “agradável”. Se o “ministério da palavra” fosse negligenciado, isso não agradaria nem a Deus nem aos próprios apóstolos. — At 6:4.
- *para servir alimento*: Ou: “para ministrar”. Aqui, a palavra grega diakonéo se refere a um aspecto específico do ministério cristão: cuidar das necessidades materiais de irmãos e irmãs necessitados, mas merecedores. — Veja a nota de estudo em At 6:1, onde o substantivo relacionado, diakonía, foi traduzido como “distribuição”; veja também a nota de estudo em Lu 8:3.
====

[[v44-6-3]]

^<<v44-6-3,3>>^ Portanto, irmãos, escolham entre vocês sete homens de boa reputação, cheios de espírito e de sabedoria, e nós os designaremos para essa tarefa necessária.

[TIP]
====
- *homens de boa reputação*: Ou: “homens de quem se fala bem; homens de quem se dá bom testemunho”. Aqui, o verbo grego martyréo (“dar testemunho”) foi usado na voz passiva. Era preciso escolher homens qualificados porque a tarefa envolvia não apenas distribuir alimentos, mas também lidar com dinheiro, fazer compras e manter registros exatos. De acordo com o versículo, os sete homens deviam estar cheios de espírito e de sabedoria, ou seja, sua vida devia mostrar que eles eram guiados pelo espírito santo e pela sabedoria de Deus. As dificuldades e diferenças que existiam na congregação tornavam a situação delicada. Assim, era necessário escolher homens experientes que tivessem bom senso, discrição e discernimento. Um desses homens foi Estêvão, e a sua defesa diante do Sinédrio indica que ele tinha essas qualidades. — At 7:2-53.
====

[[v44-6-4]]

^<<v44-6-4,4>>^ Mas nós mesmos nos dedicaremos à oração e ao ministério da palavra.”

[TIP]
====
- *ao ministério da palavra*: A palavra grega traduzida aqui como “ministério” (diakonía) também foi usada em At 6:1. Assim, fica claro que este relato trata de dois tipos diferentes de ministério: um deles envolvia distribuir alimento físico de maneira imparcial para os necessitados e o outro envolvia dar alimento espiritual baseado na Palavra de Deus para a congregação. Os apóstolos chegaram à conclusão de que não seria apropriado que eles usassem seu tempo distribuindo alimentos em vez de se concentrar no ministério mais importante, o de dar alimento espiritual. Isso envolvia estudar com oração, pesquisar, e ensinar e pastorear a congregação. É verdade que eles sabiam que cuidar das necessidades materiais de viúvas pobres na congregação era uma parte necessária do ministério de um cristão. Mais tarde, Jeová inspirou Tiago a escrever que “cuidar dos órfãos e das viúvas nas suas dificuldades” é um requisito para adorar a Deus da maneira que ele aceita. (Tg 1:27) Mas os apóstolos reconheciam que sua prioridade era cuidar das necessidades espirituais de todos os discípulos, incluindo as viúvas.
====

[[v44-6-5]]

^<<v44-6-5,5>>^ O que eles disseram agradou a toda a multidão, e escolheram Estêvão, homem cheio de fé e de espírito santo, e também Filipe, Prócoro, Nicanor, Timão, Pármenas e Nicolau, prosélito de Antioquia.

[TIP]
====
- *Estêvão, . . . Filipe, Prócoro, Nicanor, Timão, Pármenas e Nicolau*: Todos estes sete nomes são gregos. Assim, é possível que, dentre todos os homens qualificados da congregação de Jerusalém, os apóstolos tenham escolhido judeus ou prosélitos que falavam grego. Mas Nicolau é o único sobre quem o versículo acrescenta a descrição prosélito de Antioquia, o que pode indicar que somente ele não era judeu de nascença. Os outros seis nomes gregos eram comuns mesmo entre o povo judeu. De qualquer forma, parece que os apóstolos, agindo como corpo governante, pensaram nos sentimentos dos judeus que falavam grego quando escolheram esses sete homens. — At 6:1-6.
- *Antioquia*: Esta é a primeira vez que a cidade de Antioquia da Síria é mencionada na Bíblia. Ela ficava uns 500 quilômetros ao norte de Jerusalém e se tornou a capital da província romana da Síria em 64 a.C. No século 1 d.C., ela era a terceira maior cidade do Império Romano, atrás apenas de Roma e Alexandria. Antioquia era admirada por sua beleza e grande influência política, comercial e cultural, mas ela também era conhecida por ser uma cidade muito imoral. Havia uma grande população de judeus em Antioquia e, pelo visto, muitas pessoas que falavam grego se tornaram prosélitos por causa deles. Um desses prosélitos foi Nicolau, que depois se converteu ao cristianismo. Barnabé e o apóstolo Paulo passaram um ano ensinando em Antioquia, e Paulo usou essa cidade como ponto de apoio, de onde ele partia para suas viagens missionárias. Foi primeiro em Antioquia que os seguidores de Cristo, “por direção divina, foram chamados de cristãos”. (Veja as notas de estudo em At 11:26.) Essa Antioquia não é a mesma Antioquia mencionada em At 13:14, que ficava na Pisídia. — Veja a nota de estudo em At 13:14 e o Apêndice B13.
====

[[v44-6-6]]

^<<v44-6-6,6>>^ Eles os levaram aos apóstolos, que, depois de orar, lhes impuseram as mãos.

[TIP]
====
- *lhes impuseram as mãos*: Nas Escrituras Hebraicas, o gesto de pôr as mãos sobre uma pessoa ou um animal podia ter vários significados. (Gên 48:14; Le 16:21; 24:14) Quando era feito com uma pessoa, esse gesto geralmente indicava que ela estava recebendo reconhecimento especial ou que ela estava sendo designada para uma tarefa especial. (Núm 8:10) Por exemplo, Moisés pôs suas mãos sobre Josué para mostrar que ele seria seu sucessor. Depois disso, Josué ficou “cheio do espírito de sabedoria” e foi bem-sucedido em liderar a nação de Israel. (De 34:9) Na ocasião mencionada aqui em At 6:6, os apóstolos impuseram suas mãos sobre os homens que eles designaram para cargos de responsabilidade. Mas os apóstolos só fizeram isso depois de orar sobre o assunto, mostrando que queriam a orientação de Deus. Tempos depois, o corpo de anciãos de uma congregação impôs as mãos sobre Timóteo, indicando que ele estava recebendo uma designação especial. (1Ti 4:14) O próprio Timóteo foi autorizado a designar outros por impor suas mãos sobre eles, mas ele só deveria fazer isso depois de analisar com cuidado as qualificações deles. — 1Ti 5:22.
====

[[v44-6-7]]

^<<v44-6-7,7>>^ Assim, a palavra de Deus continuava se espalhando, e o número de discípulos se multiplicava muito em Jerusalém. E uma grande multidão de sacerdotes se tornou obediente à fé.

[[v44-6-8]]

^<<v44-6-8,8>>^ Estêvão, cheio de favor divino e de poder, realizava grandes sinais e milagres entre o povo.

[TIP]
====
- *milagres*: Ou: “presságios”. — Veja a nota de estudo em At 2:19.
====

[[v44-6-9]]

^<<v44-6-9,9>>^ Mas alguns homens da chamada Sinagoga dos Libertos, junto com alguns cireneus e alexandrinos, bem como alguns da Cilícia e da Ásia, vieram para discutir com Estêvão.

[TIP]
====
- *Sinagoga dos Libertos*: Durante o domínio romano, o termo “liberto” era usado para se referir a uma pessoa que tinha sido libertada da escravidão. Alguns acreditam que os membros dessa sinagoga eram judeus que tinham sido escravizados pelos romanos e mais tarde foram libertados. Outros acreditam que eles eram prosélitos que tinham sido escravos.
====

[[v44-6-10]]

^<<v44-6-10,10>>^ Contudo, não puderam resistir à sabedoria e ao espírito com que ele falava.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então, eles secretamente persuadiram alguns homens a dizer: “Nós o ouvimos falar blasfêmias contra Moisés e contra Deus.”

[[v44-6-12]]

^<<v44-6-12,12>>^ E eles atiçaram o povo, os anciãos e os escribas; e, numa investida, agarraram-no e levaram-no ao Sinédrio.

[TIP]
====
- *anciãos*: Veja a nota de estudo em Mt 16:21.
====

[[v44-6-13]]

^<<v44-6-13,13>>^ Apresentaram então testemunhas falsas, que disseram: “Este homem não para de falar contra este lugar santo e contra a Lei.

[[v44-6-14]]

^<<v44-6-14,14>>^ Por exemplo, nós o ouvimos dizer que esse Jesus, o Nazareno, derrubará este lugar e mudará os costumes que Moisés nos transmitiu.”

[TIP]
====
- *o Nazareno*: Veja a nota de estudo em Mr 10:47.
====

[[v44-6-15]]

^<<v44-6-15,15>>^ E, quando todos os sentados no Sinédrio fixaram os olhos nele, viram que o seu rosto era como o rosto de um anjo.

[TIP]
====
- *como o rosto de um anjo*: Tanto a palavra hebraica como a palavra grega para “anjo” significam “mensageiro”. (Veja a nota de estudo em Jo 1:51.) Os anjos são mensageiros enviados por Deus e, por isso, agem sempre com coragem e serenidade, sabendo que têm o apoio dele. O rosto de Estêvão era o de um mensageiro de Deus. Ele permaneceu sereno, sabendo que era completamente inocente. Sua expressão facial refletia a sua certeza de que Jeová, “o Deus glorioso”, o apoiava. — At 7:2.
====

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]