include::./index.adoc[]

[[v44-23-0]]
=== Atos dos Apóstolos, 23
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* M. Paulo é preso em Jerusalém (21:18–23:35)
* Paulo segue o conselho dos anciãos (21:18-26)
* Tumulto no templo; os romanos prendem Paulo (21:27-36)
* Paulo recebe permissão para falar com a multidão (21:37-40)
* Paulo faz sua defesa para a multidão; ele descreve como ele se converteu (22:1-21)
* Paulo usa sua cidadania romana (22:22-29)
* O Sinédrio se reúne (22:30)
* Paulo fala diante do Sinédrio (23:1-10)
* Paulo é fortalecido pelo Senhor (23:11)
* Conspiração para matar Paulo (23:12-22)
* Soldados romanos levam Paulo a Cesareia (23:23-35)
****

[[v44-23-1]]

^<<v44-23-1,1>>^ Olhando atentamente para o Sinédrio, Paulo disse: “Homens, irmãos, eu me comportei perante Deus com uma consciência perfeitamente limpa até hoje.”

[TIP]
====
- *eu me comportei*: Ou: “eu vivi minha vida”. Aqui, foi usada uma forma do verbo politeúomai que poderia ser traduzida como “comportar-se como cidadão”. (Kingdom Interlinear) Paulo estava dizendo que tinha se comportado como um bom cidadão que seguia as leis de seu país. Os cidadãos romanos costumavam participar ativamente nas questões do Estado, já que a cidadania romana era muito valorizada e trazia tanto privilégios como responsabilidades. (At 22:25-30) Ao usar as palavras “eu me comportei” perante Deus, Paulo talvez estivesse dando a entender que era, antes de mais nada, um cidadão do Reino de Deus. — Fil 3:20; compare com Fil 1:27, onde a mesma forma do verbo politeúomai é usada.
====

[[v44-23-2]]

^<<v44-23-2,2>>^ Em vista disso, o sumo sacerdote Ananias mandou que os que estavam perto dele lhe batessem na boca.

[[v44-23-3]]

^<<v44-23-3,3>>^ Paulo lhe disse então: “Deus baterá em você, parede caiada.^&#42;1^ Você se senta para me julgar segundo a Lei e ao mesmo tempo viola a Lei, mandando que me batam?”

[NOTE]
====
. Ou: “você, hipócrita”.
====

[[v44-23-4]]

^<<v44-23-4,4>>^ Os que estavam ali disseram: “Você está insultando o sumo sacerdote de Deus?”

[[v44-23-5]]

^<<v44-23-5,5>>^ E Paulo respondeu: “Irmãos, eu não sabia que ele era o sumo sacerdote. Pois está escrito: ‘Não fale mal de uma autoridade do seu povo.’”

[[v44-23-6]]

^<<v44-23-6,6>>^ Paulo, sabendo que uma parte deles eram saduceus, mas outra parte eram fariseus, disse bem alto no Sinédrio: “Homens, irmãos, eu sou fariseu, filho de fariseus. É por causa da esperança da ressurreição dos mortos que estou sendo julgado.”

[TIP]
====
- *eu sou fariseu*: Alguns dos que estavam ali conheciam Paulo. (At 22:5) Eles com certeza entenderam que, quando Paulo afirmou que era filho de fariseus, ele estava simplesmente reconhecendo que tinha a mesma formação que eles. Por isso, os fariseus do Sinédrio não pensariam que Paulo estava fingindo ser o que não era quando disse que era fariseu. Eles sabiam que Paulo tinha se tornado um cristão zeloso. Neste contexto, as palavras de Paulo davam a entender que ele se identificava, até certo ponto, com os fariseus, e não com os saduceus, porque os fariseus acreditavam na ressurreição assim como ele. Dessa forma, Paulo mostrou que eles tinham algo em comum. Tudo indica que, ao levantar esse assunto polêmico, a intenção dele era fazer com que alguns membros do Sinédrio tomassem o seu lado, e isso funcionou. (At 23:7-9) O que Paulo disse aqui em At 23:6 também está de acordo com o que ele disse sobre si mesmo ao se defender diante do rei Agripa. (At 26:5) E, quando Paulo estava em Roma e escreveu aos cristãos em Filipos, ele novamente falou sobre o seu passado como fariseu. (Fil 3:5) Também é interessante o modo como outros cristãos que tinham sido fariseus são descritos em At 15:5. — Veja a nota de estudo em At 15:5.
====

[[v44-23-7]]

^<<v44-23-7,7>>^ Ao dizer isso, surgiu uma discussão entre os fariseus e os saduceus, e a assembleia ficou dividida.

[[v44-23-8]]

^<<v44-23-8,8>>^ Pois os saduceus dizem que não há ressurreição, nem anjo, nem espírito, mas os fariseus aceitam^&#42;1^ todas essas coisas.

[NOTE]
====
. Ou: “declaram publicamente”.
====

[[v44-23-9]]

^<<v44-23-9,9>>^ Assim, começou uma grande gritaria, e alguns dos escribas do partido dos fariseus se levantaram e se puseram a protestar energicamente: “Não achamos nada de errado neste homem; e, se um espírito ou um anjo falou com ele . . .”

[[v44-23-10]]

^<<v44-23-10,10>>^ Então a discussão se intensificou, e o comandante militar, com medo de que Paulo fosse despedaçado por eles, mandou que os soldados descessem, o arrancassem do meio deles e o levassem ao quartel.

[[v44-23-11]]

^<<v44-23-11,11>>^ Mas, naquela noite, o Senhor apareceu ao lado dele e disse: “Tenha coragem! Pois, assim como você deu um testemunho cabal sobre mim em Jerusalém, terá de dar testemunho também em Roma.”

[[v44-23-12]]

^<<v44-23-12,12>>^ Quando o dia amanheceu, os judeus formaram uma conspiração e se comprometeram, sob maldição, a não comer nem beber nada até matarem Paulo.

[TIP]
====
- *se comprometeram, sob maldição*: Ou: “se comprometeram, sob juramento”. A palavra grega anathematízo pelo visto se refere a fazer um juramento que traria maldição sobre quem o fez caso a pessoa estivesse mentido ou não cumprisse com sua palavra.
====

[[v44-23-13]]

^<<v44-23-13,13>>^ Foram mais de 40 homens que fizeram essa conspiração sob juramento.

[[v44-23-14]]

^<<v44-23-14,14>>^ Esses homens se dirigiram aos principais sacerdotes e aos anciãos, e disseram: “Nós nos comprometemos solenemente, sob maldição, a não comer nada até matarmos Paulo.

[TIP]
====
- *anciãos*: Neste versículo, a palavra “anciãos” se refere a homens de autoridade entre os judeus. Muitas vezes eles são mencionados junto com outros dois grupos: os principais sacerdotes e os escribas. — Veja a nota de estudo em Mt 16:21.
- *nos comprometemos . . . sob maldição*: Ou: “nos comprometemos . . . sob juramento”. — Veja a nota de estudo em At 23:12.
====

[[v44-23-15]]

^<<v44-23-15,15>>^ Portanto, vocês, junto com o Sinédrio, devem dizer ao comandante militar que o traga para baixo, para comparecer diante de vocês, como se quisessem examinar mais detalhadamente o caso dele. Mas, antes que ele se aproxime, estaremos prontos para matá-lo.”

[[v44-23-16]]

^<<v44-23-16,16>>^ No entanto, o filho da irmã de Paulo soube da emboscada que estavam planejando; ele entrou no quartel e contou tudo a Paulo.

[[v44-23-17]]

^<<v44-23-17,17>>^ Assim, Paulo chamou um dos oficiais do exército e disse: “Leve este jovem ao comandante militar, pois ele tem algo para lhe comunicar.”

[[v44-23-18]]

^<<v44-23-18,18>>^ Ele o levou então ao comandante militar, e disse: “O prisioneiro Paulo me chamou e pediu que eu trouxesse este jovem ao senhor, porque ele tem algo para lhe dizer.”

[[v44-23-19]]

^<<v44-23-19,19>>^ O comandante militar o pegou pela mão, o levou à parte e lhe perguntou: “O que você tem para me contar?”

[[v44-23-20]]

^<<v44-23-20,20>>^ Ele respondeu: “Os judeus combinaram pedir ao senhor que faça Paulo descer ao Sinédrio amanhã, como se quisessem saber mais detalhes sobre o caso dele.

[[v44-23-21]]

^<<v44-23-21,21>>^ Mas não deixe que eles o convençam, pois mais de 40 deles planejam ficar de emboscada contra Paulo, e eles se comprometeram, sob maldição, a não comer nem beber nada até que o tenham matado. Agora eles estão prontos, esperando que o senhor atenda ao pedido deles.”

[TIP]
====
- *se comprometeram, sob maldição*: Ou: “se comprometeram, sob juramento”. — Veja a nota de estudo em At 23:12.
====

[[v44-23-22]]

^<<v44-23-22,22>>^ Assim, o comandante militar deixou o jovem ir embora, mas antes lhe ordenou: “Não diga a ninguém que você me contou isso.”

[[v44-23-23]]

^<<v44-23-23,23>>^ Então ele convocou dois oficiais do exército e disse: “Aprontem 200 soldados, 70 cavaleiros e 200 lanceiros para irem até Cesareia à terceira hora da noite.

[TIP]
====
- *à terceira hora da noite*: A terceira hora, contando a partir do pôr do sol, seria por volta das 9 horas da noite. Os gregos e romanos dividiam a noite em períodos chamados de “vigílias”, e as Escrituras Gregas Cristãs geralmente usam essa mesma divisão ao citar o horário dos acontecimentos. (Mt 14:25; Mr 6:48; Lu 12:38) Esta é a única vez que elas se referem a uma “hora” específica das 12 horas do período da noite. — Compare com At 16:25, 33; veja a nota de estudo em Mr 13:35.
====

[[v44-23-24]]

^<<v44-23-24,24>>^ Também, providenciem cavalos para Paulo montar, a fim de levá-lo em segurança a Félix, o governador.”

[[v44-23-25]]

^<<v44-23-25,25>>^ E ele escreveu uma carta que dizia:

[[v44-23-26]]

^<<v44-23-26,26>>^ “Cláudio Lísias a Sua Excelência, o governador Félix. Saudações!

[TIP]
====
- *Cláudio Lísias a Sua Excelência, o governador Félix. Saudações!*: Na antiguidade, era costume usar esse tipo de introdução nas cartas. Primeiro, se identificava o autor da carta, depois para quem era a carta e então se incluía a palavra grega khaíro, que era um cumprimento comum. Essa palavra significa literalmente “alegrar-se” e passa a seguinte ideia: “Que tudo esteja bem com você.” Ela aparece com frequência em cartas não bíblicas escritas em papiro. Neste versículo, a palavra khaíro pode ser corretamente traduzida como “Saudações!” Outros textos que contêm introduções parecidas são At 15:23 e Tg 1:1. — Veja a nota de estudo em At 15:23.
====

[[v44-23-27]]

^<<v44-23-27,27>>^ Este homem foi agarrado pelos judeus e estava prestes a ser morto por eles, mas eu vim rapidamente com meus soldados e o resgatei, porque fiquei sabendo que ele era romano.

[TIP]
====
- *romano*: Ou seja, um cidadão romano. — Veja as notas de estudo em At 16:37; 22:25.
====

[[v44-23-28]]

^<<v44-23-28,28>>^ Então, querendo descobrir a razão por que o acusavam, eu o levei ao Sinédrio deles.

[[v44-23-29]]

^<<v44-23-29,29>>^ Verifiquei que ele estava sendo acusado por questões da Lei deles, mas não foi acusado de nem uma única coisa que merecesse morte ou prisão.

[[v44-23-30]]

^<<v44-23-30,30>>^ No entanto, visto que me foi revelada uma conspiração contra o homem, eu o estou enviando imediatamente a Vossa Excelência e mandando que os acusadores falem na sua presença o que têm contra ele.”

[[v44-23-31]]

^<<v44-23-31,31>>^ Assim, segundo as ordens que receberam, os soldados pegaram Paulo e o levaram de noite até Antipátride.

[[v44-23-32]]

^<<v44-23-32,32>>^ No dia seguinte, deixaram os cavaleiros prosseguir com ele e voltaram para o quartel.

[[v44-23-33]]

^<<v44-23-33,33>>^ Os cavaleiros entraram em Cesareia, entregaram a carta ao governador e também lhe apresentaram Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ Então o governador leu a carta e perguntou de que província ele era; foi informado de que era da Cilícia.

[[v44-23-35]]

^<<v44-23-35,35>>^ “Eu ouvirei todo o seu caso”, disse ele, “quando chegarem os seus acusadores”. E mandou que ele ficasse detido no palácio de Herodes.

[TIP]
====
- *palácio*: Ou: “pretório”. Nos Evangelhos e em Atos, a palavra grega praitórion (que vem do latim) é usada para se referir a um palácio ou a uma residência. As tendas dos comandantes do exército eram chamadas de pretório e, por isso, com o tempo esse termo passou a ser usado para se referir às residências dos governadores das províncias. Aqui, praitórion se refere ao palácio construído por Herodes, o Grande, que ficava em Cesareia. Na época deste relato, por volta de 56 d.C., esse palácio era a residência do governador romano. — Veja a nota de estudo em Mt 27:27.
====

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]