include::./index.adoc[]

[[v44-10-0]]
=== Atos dos Apóstolos, 10
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* H. A pregação chega aos não judeus incircuncisos em Cesareia e Antioquia da Síria (10:1–12:25)
* Um oficial do exército chamado Cornélio tem uma visão e manda chamar Pedro (10:1-8)
* Em uma visão, Pedro vê animais que foram purificados (10:9-16)
* Pedro vai até Cornélio, que conta a ele a visão que teve (10:17-33)
* Pedro proclama as boas novas aos não judeus; “Deus não é parcial” (10:34-43)
* Não judeus recebem espírito santo e são batizados (10:44-48)
* Pedro relata aos apóstolos em Jerusalém o que aconteceu (11:1-18)
* Barnabé e Saulo pregam para pessoas de língua grega em Antioquia da Síria, onde os discípulos são chamados de cristãos pela primeira vez (11:19-26)
* O profeta cristão Ágabo prediz uma grande fome; os discípulos enviam ajuda aos irmãos na Judeia (11:27-30)
* O rei Herodes mata Tiago e prende Pedro (12:1-5)
* Um anjo de Jeová liberta Pedro da prisão (12:6-19)
* Um anjo de Jeová fere Herodes (12:20-25)
****

[[v44-10-1]]

^<<v44-10-1,1>>^ Havia em Cesareia um homem de nome Cornélio, oficial do chamado regimento italiano.

[TIP]
====
- *oficial*: Ou: “centurião”. Um oficial que comandava cerca de 100 soldados do exército romano.
- *do chamado regimento italiano*: Tudo indica que a palavra grega speíra, traduzida aqui como “regimento”, se refira a uma coorte. As coortes eram unidades do exército que normalmente eram formadas por até 600 soldados, cerca de um décimo do tamanho de uma legião. (Veja a nota de estudo em Mt 26:53.) Parece que o regimento mencionado aqui era chamado de “italiano” para diferenciá-lo dos regimentos que faziam parte das legiões romanas padrão. Existem evidências de que em 69 d.C. uma coorte chamada de Segunda Coorte Italiana de Cidadãos Romanos Voluntários (em latim, Cohors II Italica voluntariorum civium Romanorum) estava atuando na Síria. Alguns acreditam que ela era o “regimento italiano” mencionado aqui.
====

[[v44-10-2]]

^<<v44-10-2,2>>^ Ele era um homem devoto, que temia a Deus junto com todos os da sua casa; ajudava muito os pobres entre o povo e continuamente fazia súplicas a Deus.

[TIP]
====
- *ajudava muito os pobres*: Ou: “fazia muitas dádivas de misericórdia”. — Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-10-3]]

^<<v44-10-3,3>>^ Por volta da nona hora do dia, ele viu claramente numa visão um anjo de Deus se chegar a ele e dizer: “Cornélio!”

[TIP]
====
- *Por volta da nona hora do dia*: Ou seja, por volta das 3 horas da tarde. — Veja a nota de estudo em Mt 20:3.
====

[[v44-10-4]]

^<<v44-10-4,4>>^ Apavorado, Cornélio fixou os olhos nele e perguntou: “Que é, Senhor?” Ele lhe disse: “Suas orações e a ajuda que você dá aos pobres subiram como lembrança perante Deus.

[[v44-10-5]]

^<<v44-10-5,5>>^ Assim, envie agora homens a Jope para trazerem um homem de nome Simão, conhecido como Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Esse homem está hospedado com Simão, um curtidor de couro, que tem uma casa à beira do mar.”

[TIP]
====
- *Simão, um curtidor de couro*: Os curtidores trabalhavam com a pele de animais e usavam uma solução de cal para remover completamente os pelos e restos de gordura e de carne. Depois, curtiam a pele com um líquido forte extraído de certas plantas, e assim ela podia ser usada para fazer artigos de couro. O processo de curtir o couro cheirava mal e usava uma grande quantidade de água, o que talvez explique por que Simão morava à beira do mar, provavelmente nos arredores de Jope. De acordo com a Lei mosaica, a pessoa que trabalhava com carcaças de animais ficava impura. (Le 5:2; 11:39) Por isso, muitos judeus desprezavam os curtidores e dificilmente se hospedariam na casa de um deles. Na verdade, o Talmude mais tarde classificou a profissão de curtidor como inferior à de catador de esterco. Mas Pedro não se deixou levar pelo preconceito e ficou na casa de Simão. O fato de Pedro ter a mente aberta nesse caso o preparou para a designação que ele receberia a seguir — visitar um homem de outra nação na casa dele. Alguns estudiosos entendem que a palavra grega para “curtidor” (byrseús) era o sobrenome de Simão.
====

[[v44-10-7]]

^<<v44-10-7,7>>^ Logo que o anjo que lhe falou foi embora, ele chamou dois dos seus servos e um soldado devoto dentre os seus auxiliares,

[[v44-10-8]]

^<<v44-10-8,8>>^ contou-lhes tudo e os enviou a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, enquanto eles viajavam e se aproximavam da cidade, Pedro subiu ao terraço para orar, por volta da sexta hora.

[TIP]
====
- *ao terraço*: As casas tinham um terraço que podia ser usado para várias coisas, como por exemplo, estocar materiais (Jos 2:6), descansar ou relaxar (2Sa 11:2), dormir (1Sa 9:26), celebrar as festividades religiosas (Ne 8:16-18) e ficar sozinho para orar. Quando Pedro subiu no terraço para orar, ele não estava sendo como os hipócritas que faziam questão de orar onde pudessem ser vistos. (Mt 6:5) Os terraços eram cercados por um parapeito, e isso provavelmente impediria que Pedro fosse visto por outros. (De 22:8) Algumas pessoas também usavam o terraço no fim da tarde para fugir do barulho da rua e relaxar. — Veja a nota de estudo em Mt 24:17.
- *por volta da sexta hora*: Ou seja, por volta do meio-dia. — Veja a nota de estudo em Mt 20:3.
====

[[v44-10-10]]

^<<v44-10-10,10>>^ Mas ele ficou com muita fome e quis comer. Enquanto preparavam a refeição, ele caiu em transe;

[TIP]
====
- *em transe*: A palavra grega traduzida aqui como “transe” é ékstasis (formada por ek, que significa “fora de”, e stásis, que significa “estar de pé”). Ela se refere ao que acontece com uma pessoa que sai de seu estado mental normal por causa de uma visão que recebeu de Deus ou porque algo a deixou admirada ou maravilhada. No texto de Lu 5:26, ela foi traduzida como “admiração” e, em Mr 16:8, como “tomadas de emoção”. Ela também pode ser traduzida como “êxtase”. (Veja a nota de estudo em Mr 5:42.) No livro de Atos, a palavra ékstasis está sempre ligada com a atuação de Deus. Pelo visto, o espírito santo às vezes atuava sobre a mente de uma pessoa, revelando a ela um aspecto do propósito de Deus por meio de uma imagem ou visão. Isso acontecia enquanto ela estava num estado de profunda concentração ou numa condição semelhante ao sono. Uma pessoa em transe não tinha consciência do que estava acontecendo à sua volta e estava com a mente livre para receber uma visão. — Veja a nota de estudo em At 22:17.
====

[[v44-10-11]]

^<<v44-10-11,11>>^ viu o céu aberto e algo semelhante a um grande lençol de linho descendo sobre a terra, preso pelas quatro pontas.

[[v44-10-12]]

^<<v44-10-12,12>>^ E nele havia todo tipo de quadrúpedes e de répteis^&#42;1^ da terra, e de aves do céu.

[NOTE]
====
. Ou: “animais rasteiros”.
====

[[v44-10-13]]

^<<v44-10-13,13>>^ Então uma voz lhe disse: “Levante-se, Pedro, mate^&#42;1^ e coma!”

[NOTE]
====
. Ou: “sacrifique”.
====

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro respondeu: “De jeito nenhum, Senhor, porque nunca comi nada aviltado ou impuro.”

[[v44-10-15]]

^<<v44-10-15,15>>^ E a voz falou novamente com ele, pela segunda vez: “Pare de chamar de impuras as coisas que Deus purificou.”

[[v44-10-16]]

^<<v44-10-16,16>>^ Isso ocorreu pela terceira vez e, imediatamente, o lençol foi recolhido ao céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Pedro estava perplexo, perguntando-se o que poderia significar a visão que ele havia tido. Enquanto isso, os homens enviados por Cornélio perguntaram onde era a casa de Simão e ficaram parados no portão.

[[v44-10-18]]

^<<v44-10-18,18>>^ Eles chamaram e perguntaram se Simão, conhecido como Pedro, estava hospedado ali.

[[v44-10-19]]

^<<v44-10-19,19>>^ Pedro ainda estava refletindo sobre a visão quando o espírito disse: “Escute! Três homens estão procurando você.

[[v44-10-20]]

^<<v44-10-20,20>>^ Levante-se então, desça e vá com eles, sem hesitar, porque eu os enviei.”

[[v44-10-21]]

^<<v44-10-21,21>>^ De modo que Pedro desceu ao encontro dos homens e disse: “Aqui estou, sou eu quem vocês estão procurando. Por que estão aqui?”

[[v44-10-22]]

^<<v44-10-22,22>>^ Disseram: “Cornélio, oficial do exército, homem justo e temente a Deus, de quem toda a nação dos judeus fala bem, recebeu instruções divinas por meio de um anjo para chamar o senhor à casa dele a fim de ouvir o que o senhor tem a dizer.”

[TIP]
====
- *recebeu instruções divinas*: O verbo grego que aparece aqui, khrematízo, ocorre nove vezes nas Escrituras Gregas Cristãs. (Mt 2:12, 22; Lu 2:26; At 10:22; 11:26; Ro 7:3; He 8:5; 11:7; 12:25) Na maioria das ocorrências, ele está claramente ligado a coisas que têm origem divina. Por exemplo, aqui o verbo é usado junto com a expressão “por meio de um anjo”. E, em Mt 2:12, 22, ele está ligado com sonhos dados por Deus. No texto de Ro 11:4, aparece o substantivo relacionado, khrematismós, que é traduzido na maioria dos léxicos e traduções da Bíblia como “declaração divina; resposta divina; resposta de Deus”. Aqui em At 10:22, uma tradução das Escrituras Gregas Cristãs para o hebraico (chamada de J18 no Apêndice C4) diz “recebeu uma ordem de Jeová”. — Veja a nota de estudo em At 11:26.
====

[[v44-10-23]]

^<<v44-10-23,23>>^ Assim, Pedro os convidou para entrar e lhes deu hospedagem.
No dia seguinte, levantou-se e foi com eles, e alguns dos irmãos de Jope o acompanharam.

[[v44-10-24]]

^<<v44-10-24,24>>^ No outro dia, ele entrou em Cesareia. Cornélio, naturalmente, os estava esperando, e havia reunido seus parentes e amigos íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro entrou, Cornélio foi ao seu encontro, se prostrou aos pés dele e lhe prestou homenagem.

[TIP]
====
- *lhe prestou homenagem*: Ou: “se curvou diante dele”. Quando Jesus esteve na Terra, algumas pessoas se curvaram diante dele, e ele não as repreendeu. (Lu 5:12; Jo 9:38) Jesus era o herdeiro do trono de Davi, e era correto que as pessoas se curvassem diante dele para mostrar respeito ao futuro Rei. (Mt 21:9; Jo 12:13-15) Além disso, as Escrituras Hebraicas mostram que as pessoas se curvavam ao encontrar profetas, reis ou outros representantes de Deus, e que eles aceitavam que elas fizessem isso. (1Sa 25:23, 24; 2Sa 14:4-7; 1Rs 1:16; 2Rs 4:36, 37) Mas, quando Cornélio se prostrou diante de Pedro e lhe prestou homenagem, Pedro não aceitou receber essa honra e disse: “Fique de pé! Eu também sou apenas um homem.” (At 10:26) Pelo visto, os ensinos de Cristo tinham mudado o padrão de comportamento entre os servos de Deus. Jesus ensinou aos seus discípulos: “Um só é o seu Instrutor, e todos vocês são irmãos . . . O seu Líder é um só, o Cristo.” — Mt 23:8-12.
====

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o levantou, dizendo: “Fique de pé! Eu também sou apenas um homem.”

[[v44-10-27]]

^<<v44-10-27,27>>^ Enquanto conversava com ele, entrou e encontrou muitas pessoas reunidas.

[[v44-10-28]]

^<<v44-10-28,28>>^ Ele lhes disse: “Vocês bem sabem que é proibido a um judeu se relacionar ou ter contato com um homem de outra raça. Contudo, Deus me mostrou que eu não devo chamar nenhum homem de aviltado ou impuro.

[TIP]
====
- *que é proibido a um judeu*: Os líderes religiosos dos dias de Pedro ensinavam que, se uma pessoa entrasse na casa de um não judeu, ela se tornaria impura. (Jo 18:28) Mas, na Lei de Moisés, não havia nenhuma instrução específica sobre isso. Além disso, depois que o novo pacto foi estabelecido com base no sacrifício de resgate de Jesus, o “muro” que separava os judeus dos não judeus foi destruído. Falando sobre isso, Ef 2:11-16 diz que Jesus “de dois grupos fez um só”. Mas, mesmo depois do Pentecostes de 33 d.C., os discípulos demoraram para entender plenamente o impacto do que Jesus tinha feito. Na verdade, os cristãos judeus levaram anos para conseguir deixar de lado os conceitos errados que eram ensinados pelos líderes religiosos judaicos e que estavam profundamente arraigados na sua cultura.
====

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso vim, sem nenhuma objeção, quando fui chamado. Agora pergunto por que mandaram me chamar.”

[[v44-10-30]]

^<<v44-10-30,30>>^ Cornélio respondeu: “Quatro dias atrás, eu estava orando na minha casa nesta mesma hora, a nona hora, quando apareceu na minha frente um homem com roupa brilhante;

[TIP]
====
- *a nona hora*: Ou seja, por volta das 3 horas da tarde. — Veja a nota de estudo em Mt 20:3.
====

[[v44-10-31]]

^<<v44-10-31,31>>^ ele disse: ‘Cornélio, sua oração foi ouvida, e a ajuda que você dá aos pobres foi lembrada diante de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Portanto, envie alguém a Jope para chamar Simão, conhecido como Pedro. Esse homem está hospedado na casa de Simão, um curtidor de couro, à beira do mar.’

[[v44-10-33]]

^<<v44-10-33,33>>^ Então, imediatamente mandei chamá-lo, e o senhor teve a bondade de vir para cá. Agora estamos todos presentes perante Deus para ouvir todas as coisas que Jeová lhe mandou dizer.”

[TIP]
====
- *Jeová*: A maioria dos manuscritos gregos usa aqui a expressão “o Senhor” (em grego, tou Kyríou). Mas, como explicado no Apêndice C1, há vários motivos para acreditar que o nome de Deus aparecia no texto original deste versículo e que mais tarde foi substituído pelo título “Senhor”. Por isso, o nome “Jeová” é usado aqui no texto principal. — Veja o Apêndice C3 (introdução e At 10:33).
====

[[v44-10-34]]

^<<v44-10-34,34>>^ Em vista disso, Pedro começou a falar; ele disse: “Agora eu entendo claramente que Deus não é parcial,

[TIP]
====
- *não é parcial*: A expressão grega que aparece aqui significa literalmente “não é alguém que tome (receba; aceite) faces”. Deus é imparcial e, por isso, não favorece a ninguém com base em raça, nacionalidade, classe social ou qualquer outro fator externo. Quem imita a Deus não julga pelas aparências. Em vez disso, presta atenção ao caráter e às qualidades dos outros, especialmente às qualidades que refletem a personalidade de nosso Criador.
====

[[v44-10-35]]

^<<v44-10-35,35>>^ mas, em toda nação, ele aceita aquele que o teme e faz o que é direito.

[[v44-10-36]]

^<<v44-10-36,36>>^ Ele enviou sua palavra aos filhos de Israel, declarando-lhes as boas novas de paz por meio de Jesus Cristo — este é Senhor de todos.

[TIP]
====
- *aos filhos de Israel*: Ou: “ao povo de Israel; aos israelitas”. — Veja o Glossário, “Israel”.
====

[[v44-10-37]]

^<<v44-10-37,37>>^ Vocês sabem de que assunto se falava em toda a Judeia, começando na Galileia, depois do batismo que João pregou:

[[v44-10-38]]

^<<v44-10-38,38>>^ sobre Jesus, que era de Nazaré, como Deus o ungiu com espírito santo e poder; e ele andou por toda a região fazendo o bem e curando todos os oprimidos pelo Diabo, porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ E nós somos testemunhas de todas as coisas que ele fez tanto na terra dos judeus como em Jerusalém. Mas eles o mataram, pendurando-o num madeiro.

[TIP]
====
- *num madeiro*: Veja a nota de estudo em At 5:30.
====

[[v44-10-40]]

^<<v44-10-40,40>>^ Deus o levantou no terceiro dia e permitiu que ele aparecesse,^&#42;1^

[NOTE]
====
. Ou: “se tornasse visível; fosse visto”.
====

[[v44-10-41]]

^<<v44-10-41,41>>^ não a todo o povo, mas a testemunhas designadas antecipadamente por Deus, a nós, os que comemos e bebemos com ele depois que foi levantado dentre os mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ Também, ele ordenou que pregássemos ao povo e déssemos um testemunho cabal de que é ele o designado por Deus para ser juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ É dele que todos os profetas dão testemunho, de que todo aquele que deposita fé nele recebe perdão de pecados por meio do seu nome.”

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro ainda falava essas coisas, o espírito santo desceu sobre todos os que ouviam a palavra.

[TIP]
====
- *o espírito santo desceu sobre todos os que ouviam a palavra*: Este é o único caso registrado nas Escrituras em que discípulos receberam espírito santo antes do batismo. O apóstolo Pedro participou ativamente na conversão de Cornélio e sua família, que não eram judeus, usando assim a terceira das “chaves do Reino dos céus”. Com isso, ele abriu as portas para que a pregação e a oportunidade de entrar no Reino de Deus fossem levadas a um enorme grupo: as pessoas das nações, ou seja, os que não eram judeus, prosélitos ou samaritanos. Antes Pedro tinha usado a primeira chave para abrir essa oportunidade aos judeus e prosélitos, e a segunda chave para abri-la aos samaritanos. — At 2:22-41; 8:14-17; veja a nota de estudo em Mt 16:19.
====

[[v44-10-45]]

^<<v44-10-45,45>>^ E os crentes circuncisos que tinham vindo com Pedro ficaram admirados, porque a dádiva^&#42;1^ do espírito santo também estava sendo derramada sobre pessoas das nações.

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[TIP]
====
- *os crentes circuncisos*: Ou: “os fiéis circuncisos”. Ou seja, os cristãos judeus. — At 10:23.
====

[[v44-10-46]]

^<<v44-10-46,46>>^ Pois eles as ouviram falar em línguas e magnificar a Deus. Em vista disso, Pedro disse:

[TIP]
====
- *em línguas*: Esse milagre foi uma prova clara de que agora Deus estava dando a esperança celestial também a pessoas das nações. Jeová usou seu espírito santo para mostrar que estava por trás dessa mudança, assim como tinha feito em Pentecostes. Aquilo que Pedro e os irmãos que estavam com ele viram e ouviram não deixou dúvidas disso. — Veja a nota de estudo em At 2:4.
====

[[v44-10-47]]

^<<v44-10-47,47>>^ “Estas pessoas receberam o espírito santo assim como nós; será que alguém pode negar a água, impedindo que sejam batizadas?”

[[v44-10-48]]

^<<v44-10-48,48>>^ Então, ele mandou que fossem batizados em nome de Jesus Cristo. E eles lhe pediram que ficasse ali alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]