include::./index.adoc[]

[[v44-13-0]]
=== Atos dos Apóstolos, 13
// nwtsty 2023, nwtsty - Tradução do Novo Mundo da Bíblia Sagrada (Edição de Estudo)

.Notas do capítulo
****
* I. Primeira viagem missionária de Paulo (13:1–14:28)
* Barnabé e Saulo são enviados como missionários (13:1-3)
* Pregação em Chipre; procônsul Sérgio Paulo e feiticeiro Elimas (13:4-12)
* Discurso de Paulo em Antioquia da Pisídia (13:13-41)
* Ordem profética para se voltarem para as nações (13:42-52)
* Crescimento da obra e oposição em Icônio (14:1-7)
* O povo de Listra pensa que Paulo e Barnabé são deuses (14:8-18)
* Paulo é apedrejado em Listra, mas sobrevive (14:19, 20)
* Paulo e Barnabé fortalecem as congregações (14:21-23)
* Paulo e Barnabé voltam a Antioquia da Síria (14:24-28)
****

[[v44-13-1]]

^<<v44-13-1,1>>^ Em Antioquia havia profetas e instrutores na congregação local: Barnabé; Simeão, que era chamado Níger; Lúcio, de Cirene; Manaém, que tinha sido educado com Herodes, o governador distrital; e Saulo.

[TIP]
====
- *Herodes, o governador distrital*: Veja a nota de estudo em Mt 14:1.
====

[[v44-13-2]]

^<<v44-13-2,2>>^ Enquanto estavam servindo a Jeová e jejuando, o espírito santo disse: “Separem-me Barnabé e Saulo para a obra a que os chamei.”

[TIP]
====
- *estavam servindo*: Ou: “estavam prestando serviço público”. A palavra grega usada aqui, leitourgéo, e as palavras relacionadas, leitourgía (serviço público; ministério público) e leitourgós (servidor público), eram usadas pelos gregos para se referir a serviços prestados ao governo ou a autoridades civis em benefício do povo. Por exemplo, Ro 13:6 usa o plural de leitourgós quando diz que os governantes “estão a serviço de Deus” (ou: “são servidores públicos de Deus”), porque eles prestam serviços em benefício do povo. Em Lu 1:23 (veja a nota de estudo), a palavra leitourgía foi traduzida como “serviço sagrado” (ou: “serviço público”) e se refere ao serviço prestado por Zacarias, o pai de João Batista. A palavra leitourgía foi usada ali por Lucas da mesma maneira que ela e as palavras relacionadas são usadas na Septuaginta, onde com frequência se referem ao serviço que os sacerdotes e levitas prestavam no tabernáculo (Êx 28:35; Núm 1:50; 3:31; 8:22) e no templo (2Cr 31:2; 35:3; Jl 1:9, 13; 2:17). Esse serviço podia ser considerado um serviço público em benefício do povo. Mas, dependendo do contexto, ele também era um serviço sagrado, porque os sacerdotes ensinavam a Lei de Deus (2Cr 15:3; Mal 2:7) e ofereciam sacrifícios para cobrir os pecados do povo (Le 1:3-5; De 18:1-5). Aqui, em At 13:2, a palavra grega leitourgéo foi usada em um sentido mais amplo e descreve o ministério, ou serviço, dos profetas e instrutores cristãos da congregação em Antioquia da Síria. Ela se refere aos vários atos de devoção a Deus que fazem parte do ministério cristão, como orar e ensinar. O serviço realizado por esses profetas e instrutores sem dúvida também envolvia pregar ao público. — At 13:3.
- *servindo a Jeová*: O verbo grego leitourgéo (servir; ministrar) é usado com frequência na Septuaginta em passagens onde o nome de Deus aparece no texto original das Escrituras Hebraicas. Por exemplo, a expressão grega traduzida aqui como “servindo a Jeová” foi usada na Septuaginta para traduzir as expressões hebraicas que aparecem em 2Cr 13:10 (“servindo a Jeová”) e em 2Cr 35:3 (“sirvam a Jeová”). — 1Sa 2:11; 3:1; Ez 45:4; Jl 2:17; veja o Apêndice C3 (introdução e At 13:2).
====

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, depois de jejuar e orar, eles lhes impuseram as mãos e os deixaram ir.

[[v44-13-4]]

^<<v44-13-4,4>>^ Assim, esses homens, enviados pelo espírito santo, desceram a Selêucia e dali navegaram para Chipre.

[TIP]
====
- *Selêucia*: Esta era uma cidade fortificada que ficava na costa do Mediterrâneo e servia de porto para Antioquia da Síria. Selêucia ficava uns 20 quilômetros ao sudoeste de Antioquia. Era possível ir de uma cidade para a outra por estrada ou pelo rio Orontes, que passava por Antioquia e desembocava no mar Mediterrâneo, logo ao sul de Selêucia. Seleuco I (Nicátor), um dos generais de Alexandre, o Grande, fundou a cidade e deu seu próprio nome a ela. Selêucia foi o local de onde Paulo, acompanhado por Barnabé, partiu para sua primeira viagem missionária, por volta de 47 d.C. A cidade ficava logo ao norte do local onde hoje existe a cidade de Samandag (Süveydiye), na Turquia. Os sedimentos do rio Orontes com o tempo transformaram o antigo porto de Selêucia num brejo. — Veja o Apêndice B13.
- *navegaram para Chipre*: Esta era uma viagem de uns 200 quilômetros. Um navio do século 1 d.C. conseguia cobrir uma distância de aproximadamente 150 quilômetros em um dia se os ventos estivessem a favor. Mas, se as condições não estivessem favoráveis, seria necessário um tempo muito maior. Barnabé, que estava nessa viagem, era natural de Chipre. — Veja o Apêndice B13.
====

[[v44-13-5]]

^<<v44-13-5,5>>^ Quando chegaram a Salamina, começaram a proclamar a palavra de Deus nas sinagogas dos judeus. João também estava com eles, como ajudante.^&#42;1^

[NOTE]
====
. Ou: “assistente”.
====

[TIP]
====
- *Salamina*: Esta cidade ficava na costa leste da ilha de Chipre. Embora a capital romana da ilha fosse Pafos, na costa oeste, fazia sentido começar a pregação em Salamina. Ela ficava mais perto de Antioquia da Síria, onde a viagem missionária tinha começado, e era o centro cultural, educacional e comercial da ilha. Além disso, a cidade tinha mais de uma sinagoga, o que mostra que havia uma quantidade considerável de judeus morando ali. Como Barnabé era natural de Chipre, ele deve ter sido um guia muito útil para o grupo de missionários. Ao deixar Salamina, o grupo percorreu a ilha pregando. Eles podem ter andado 150 quilômetros ou mais, dependendo do caminho escolhido. — Veja o Apêndice B13.
- *João*: Ou seja, João Marcos, “primo de Barnabé”. (Col 4:10) Ele era discípulo de Jesus e escreveu o Evangelho de Marcos. (Veja a nota de estudo em Mr Título.) Tanto aqui como em At 13:13 ele é chamado apenas de João. Os outros três versículos de Atos onde ele é mencionado incluem seu sobrenome romano e dizem que ele também era “conhecido como [ou: “chamado”] Marcos”. (At 12:12, 25; 15:37) O nome João, em português, equivale aos nomes hebraicos Jeoanã ou Joanã, que significam “Jeová mostrou favor” ou “Jeová foi bondoso”. No restante das Escrituras Gregas Cristãs, ele é chamado apenas de “Marcos”. — Col 4:10; 2Ti 4:11; Flm 24; 1Pe 5:13.
====

[[v44-13-6]]

^<<v44-13-6,6>>^ Depois de percorrerem toda a ilha até Pafos, encontraram um judeu chamado Barjesus, que era feiticeiro e falso profeta.

[[v44-13-7]]

^<<v44-13-7,7>>^ Ele estava com o procônsul Sérgio Paulo, homem inteligente. Este chamou Barnabé e Saulo, pois queria muito ouvir a palavra de Deus.

[TIP]
====
- *procônsul*: Este era o título dado aos governantes das províncias que ficavam debaixo da autoridade do Senado romano, chamadas de províncias senatoriais. Algumas províncias romanas, como a Judeia, eram províncias imperiais, ou seja, ficavam debaixo da autoridade direta do imperador, que escolhia um governador para elas. Mas Chipre tinha se tornado uma província senatorial em 22 a.C. e por isso era governada por um procônsul, e não um governador. Foi encontrada uma moeda de Chipre que tem em um lado a imagem e o título (em latim) do imperador romano Cláudio e no outro lado a inscrição (em grego) “Sob Cominius Proclus, Procônsul dos Cipriotas”. — Veja o Glossário.
====

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas Elimas, o feiticeiro (pois é assim que se traduz o seu nome), começou a se opor a eles, tentando desviar da fé o procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Então Saulo, também chamado Paulo, ficou cheio de espírito santo, olhou para ele atentamente

[TIP]
====
- *Saulo, também chamado Paulo*: A partir deste versículo, a Bíblia começa a chamar Saulo por seu outro nome, Paulo. Ele era hebreu, mas desde que nasceu também tinha cidadania romana. (At 22:27, 28; Fil 3:5) Assim, é provável que desde a infância ele tivesse o nome hebraico Saulo e o nome romano Paulo. Não era incomum que os judeus daquela época, principalmente os que viviam fora de Israel, tivessem dois nomes. (At 12:12; 13:1) Alguns dos parentes de Paulo também tinham nomes romanos ou gregos, além do nome hebraico. (Ro 16:7, 21) Paulo, como “apóstolo para as nações”, tinha a missão de levar as boas novas aos não judeus. (Ro 11:13) Parece que o próprio Paulo decidiu usar seu nome romano, talvez por pensar que isso ajudaria as pessoas das nações a aceitar sua pregação. (At 9:15; Gál 2:7, 8) Alguns sugerem que ele adotou o nome romano em homenagem a Sérgio Paulo. Mas isso parece improvável, já que ele continuou usando esse nome mesmo depois de sair de Chipre. Outros acham que Paulo evitou usar seu nome hebraico, Saulo, porque a pronúncia grega desse nome era bem parecida com a de uma palavra grega que tinha má conotação. — Veja a nota de estudo em At 7:58.
- *Paulo*: O nome grego Paúlos vem do latim Paulus e significa “pequeno”. No texto original das Escrituras Gregas Cristãs, esse nome é usado 157 vezes para se referir ao apóstolo Paulo e uma vez para se referir ao procônsul de Chipre, Sérgio Paulo. — At 13:7.
====

[[v44-13-10]]

^<<v44-13-10,10>>^ e disse: “Ó homem cheio de todo tipo de fraude e maldade, ó filho do Diabo, inimigo de tudo o que é justo, você não vai parar de distorcer os caminhos retos de Jeová?

[TIP]
====
- *caminhos . . . de Jeová*: A resposta de Paulo ao feiticeiro judeu Barjesus (registrada nos versículos 10 e 11) inclui expressões que vêm das Escrituras Hebraicas. Por exemplo, as palavras gregas traduzidas aqui como “distorcer os caminhos” aparecem na Septuaginta em Pr 10:9 (“perverte os seus caminhos”). Além disso, as palavras traduzidas aqui como “os caminhos retos de Jeová” aparecem na Septuaginta em Os 14:9. Nesse versículo de Oseias, o texto hebraico original usa o nome de Deus e diz: “Pois os caminhos de Jeová são retos.” — Veja o Apêndice C3 (introdução e At 13:10).
====

[[v44-13-11]]

^<<v44-13-11,11>>^ Escute: a mão de Jeová está sobre você, e você ficará cego, sem ver a luz do sol por um tempo.” Instantaneamente caiu sobre ele uma densa névoa e escuridão, e ele começou a andar em volta, tentando encontrar alguém que o guiasse pela mão.

[TIP]
====
- *a mão de Jeová*: Veja a nota de estudo em At 11:21 e o Apêndice C3 (introdução e At 13:11).
====

[[v44-13-12]]

^<<v44-13-12,12>>^ Então, ao ver o que tinha acontecido, o procônsul se tornou crente, pois ficou impressionado com os ensinamentos de Jeová.

[TIP]
====
- *os ensinamentos de Jeová*: Esta expressão tem o mesmo significado da expressão “a palavra de Deus”, usada em At 13:5. Ali, o versículo diz que Paulo e seus companheiros “começaram a proclamar a palavra de Deus nas sinagogas dos judeus” quando chegaram em Chipre. Isso fez com que o procônsul Sérgio Paulo ‘quisesse muito ouvir a palavra de Deus’. (At 13:7) Depois de ter presenciado o que Paulo disse e fez, Sérgio Paulo ficou impressionado com o que aprendeu sobre Jeová Deus e seus ensinamentos. — Veja o Apêndice C3 (introdução e At 13:12).
====

[[v44-13-13]]

^<<v44-13-13,13>>^ Paulo e seus companheiros embarcaram então em Pafos e chegaram a Perge, na Panfília. Mas João os deixou e voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ No entanto, eles seguiram viagem partindo de Perge e chegaram a Antioquia, na Pisídia. Entraram então na sinagoga no dia de sábado e se sentaram.

[TIP]
====
- *Antioquia, na Pisídia*: Esta cidade pertencia à província romana da Galácia e ficava na fronteira de duas regiões, a Frígia e a Pisídia. Assim, dependendo da época da história, ela talvez fosse considerada parte de uma região ou da outra. As ruínas da cidade ficam perto de Yalvaç, na Turquia. Ela também é citada em At 14:19, 21. A viagem da cidade de Perge, perto do mar Mediterrâneo, para Antioquia, não era nada fácil, já que Antioquia ficava uns 1.100 metros acima do nível do mar. (Veja o Apêndice B13.) Além disso, as estradas nas montanhas eram perigosas e acidentadas, e os viajantes corriam o risco de serem assaltados. Existia outra cidade chamada Antioquia, que ficava na Síria. (At 6:5; 11:19; 13:1; 14:26; 15:22; 18:22) Na verdade, na maioria das vezes que esse nome aparece em Atos, ele não se refere à Antioquia da Pisídia, mas à Antioquia da Síria.
====

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura pública da Lei e dos Profetas, os presidentes da sinagoga mandaram lhes dizer: “Homens, irmãos, se tiverem alguma palavra de encorajamento para o povo, falem.”

[TIP]
====
- *da leitura pública da Lei e dos Profetas*: No século 1 d.C., essa leitura pública era feita “todo sábado”. (At 15:21) Como parte das reuniões nas sinagogas, os judeus recitavam as palavras de De 6:4-9 e 11:13-21 em sua profissão (declaração) de fé conhecida como Shema. O nome Shema vem da primeira palavra hebraica do primeiro versículo que era recitado: “Escute [Shemáʽ], ó Israel: Jeová, nosso Deus, é um só Jeová.” (De 6:4) A parte mais importante da reunião era a leitura da Torá (o Pentateuco). Em muitas sinagogas, a Lei inteira era lida em um ano; em outras, essa leitura era programada para ser feita em três anos. Além disso, trechos dos Profetas eram lidos e explicados. Depois da leitura pública, era feito um discurso. Foi nessa parte da reunião que Paulo foi convidado a falar palavras de encorajamento para as pessoas que estavam na sinagoga em Antioquia, na Pisídia. — Veja a nota de estudo em Lu 4:16.
====

[[v44-13-16]]

^<<v44-13-16,16>>^ Assim, Paulo se levantou, fez sinal com a mão e disse:
“Homens, israelitas e todos os outros que temem a Deus, escutem!

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus deste povo, o Deus de Israel, escolheu os nossos antepassados; ele enalteceu o povo enquanto moravam como estrangeiros na terra do Egito e os tirou de lá com braço forte.^&#42;1^

[NOTE]
====
. Lit.: “com braço erguido”.
====

[[v44-13-18]]

^<<v44-13-18,18>>^ E, por cerca de 40 anos, ele os suportou no deserto.

[[v44-13-19]]

^<<v44-13-19,19>>^ Destruiu sete nações na terra de Canaã e deu a terra delas como herança.

[[v44-13-20]]

^<<v44-13-20,20>>^ Tudo isso ocorreu durante cerca de 450 anos.
“Depois, deu-lhes juízes até Samuel, o profeta.

[TIP]
====
- *durante cerca de 450 anos*: Em seu resumo da história dos israelitas, Paulo usou como ponto de partida um acontecimento muito importante, dizendo: “Deus . . . escolheu os nossos antepassados.” (At 13:17) Pelo visto, ele estava pensando no nascimento de Isaque como o descendente prometido. (Gên 17:19; 21:1-3; 22:17, 18) A mãe de Isaque, Sarai (Sara) era estéril (Gên 11:30) e, por isso, até o nascimento de Isaque havia dúvida sobre quem seria o descendente escolhido por Deus. Mas, quando Isaque nasceu, esse assunto foi resolvido de uma vez por todas. Partindo desse ponto, Paulo fala de várias coisas que Deus fez a favor de sua nação escolhida durante um período de “cerca de 450 anos”, antes de chegar a época em que Deus lhes deu juízes até Samuel, o profeta. Assim, tudo indica que esse período começou em 1918 a.C., o ano do nascimento de Isaque, e terminou em 1467 a.C., 46 anos depois da saída de Israel do Egito, em 1513 a.C. Isso faz sentido já que os israelitas passaram 40 anos no deserto e levaram mais 6 anos para conquistar a terra de Canaã. — Núm 9:1; 13:1, 2, 6; De 2:7; Jos 14:6, 7, 10.
====

[[v44-13-21]]

^<<v44-13-21,21>>^ Mas então exigiram um rei, e Deus lhes deu Saul, filho de Quis, homem da tribo de Benjamim, por 40 anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ Após removê-lo, levantou-lhes Davi como rei, a respeito de quem deu testemunho, dizendo: ‘Encontrei Davi, filho de Jessé, um homem que agrada ao meu coração; ele fará tudo o que desejo.’

[[v44-13-23]]

^<<v44-13-23,23>>^ Segundo a sua promessa, da descendência^&#42;1^ daquele homem Deus trouxe a Israel um salvador, Jesus.

[NOTE]
====
. Lit.: “semente”.
====

[[v44-13-24]]

^<<v44-13-24,24>>^ Antes da chegada dele, João pregou publicamente a todo o povo de Israel o batismo em símbolo de arrependimento.

[[v44-13-25]]

^<<v44-13-25,25>>^ Mas, quando estava terminando a sua missão, João dizia: ‘Quem vocês acham que eu sou? Eu não sou ele.^&#42;1^ Na verdade, depois de mim vem alguém cujas sandálias não sou digno de desamarrar.’

[NOTE]
====
. Ou: “João dizia: ‘Eu não sou quem vocês acham que eu sou’”.
====

[[v44-13-26]]

^<<v44-13-26,26>>^ “Homens, irmãos, descendentes da família de Abraão e todos os outros entre vocês que temem a Deus, essa mensagem de salvação foi enviada a nós.

[[v44-13-27]]

^<<v44-13-27,27>>^ Pois os habitantes de Jerusalém e os seus líderes não reconheceram esse salvador, mas, ao agirem como juízes, cumpriram as palavras dos Profetas, que são lidas em voz alta todo sábado.

[[v44-13-28]]

^<<v44-13-28,28>>^ Embora não achassem razão para matá-lo, exigiram que Pilatos mandasse executá-lo.

[[v44-13-29]]

^<<v44-13-29,29>>^ E, depois de realizarem todas as coisas escritas a respeito dele, tiraram-no do madeiro e o colocaram num túmulo.

[TIP]
====
- *do madeiro*: Ou: “da árvore”. — Veja a nota de estudo em At 5:30.
- *túmulo*: Ou: “túmulo memorial”. — Veja o Glossário, “Túmulo memorial”.
====

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus o levantou dentre os mortos,

[[v44-13-31]]

^<<v44-13-31,31>>^ e, durante muitos dias, ele apareceu aos que tinham subido com ele da Galileia para Jerusalém. Eles agora estão dando testemunho dele ao povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ “Assim, nós estamos declarando a vocês as boas novas a respeito da promessa feita aos nossos antepassados.

[[v44-13-33]]

^<<v44-13-33,33>>^ Deus a cumpriu plenamente para nós, os filhos, ressuscitando Jesus, como está escrito no segundo salmo: ‘Você é meu filho; hoje eu me tornei seu pai.’

[[v44-13-34]]

^<<v44-13-34,34>>^ E o fato de que Deus o ressuscitou dentre os mortos de modo que ele nunca mais tivesse um corpo perecível, Ele declarou do seguinte modo: ‘Eu lhes darei as fiéis^&#42;1^ expressões de amor leal prometidas a Davi.’

[NOTE]
====
. Ou: “fidedignas; confiáveis”.
====

[[v44-13-35]]

^<<v44-13-35,35>>^ Por isso, também se diz em outro salmo: ‘Não permitirás que o teu leal conheça a decomposição.’

[[v44-13-36]]

^<<v44-13-36,36>>^ Davi prestou serviço a Deus em sua geração, adormeceu na morte, foi enterrado com os seus antepassados e conheceu a decomposição.

[TIP]
====
- *prestou serviço a Deus*: Ou: “serviu à vontade (ao propósito) de Deus”. — Veja a nota de estudo em At 20:27.
====

[[v44-13-37]]

^<<v44-13-37,37>>^ Mas aquele a quem Deus levantou não conheceu a decomposição.

[[v44-13-38]]

^<<v44-13-38,38>>^ “Portanto, irmãos, saibam que por meio desse homem se proclama a vocês o perdão de pecados,

[[v44-13-39]]

^<<v44-13-39,39>>^ e que, por meio dele, todo aquele que crê é declarado inocente de todas as coisas das quais não podia ser declarado inocente por meio da Lei de Moisés.

[[v44-13-40]]

^<<v44-13-40,40>>^ Assim, tomem cuidado para que não venha sobre vocês aquilo que se disse nos Profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ ‘Vejam isso, zombadores, pasmem-se e desapareçam, pois estou realizando uma obra nos seus dias, uma obra em que vocês jamais acreditarão, mesmo que lhes seja contada em detalhes.’”

[[v44-13-42]]

^<<v44-13-42,42>>^ Quando eles estavam saindo, as pessoas lhes suplicaram que falassem desses assuntos no sábado seguinte.

[[v44-13-43]]

^<<v44-13-43,43>>^ Depois de acabar a reunião da sinagoga, muitos judeus e prosélitos que adoravam a Deus seguiram Paulo e Barnabé, que, ao falar com eles, os exortavam a permanecer na bondade imerecida de Deus.

[TIP]
====
- *que adoravam a Deus*: A palavra grega sébomai, traduzida aqui como “que adoravam a Deus”, tem o sentido de “adorar; reverenciar; venerar”. Neste versículo, ela também poderia ser traduzida como “tementes a Deus; devotos”. (Veja a nota de estudo em At 13:50.) Na Peshitta siríaca ela foi traduzida como “que temiam a Deus”. Uma tradução das Escrituras Gregas Cristãs para o hebraico (chamada de J18 no Apêndice C4) usa o nome de Deus aqui. A frase da J18 poderia ser traduzida como “que temiam a Jeová”.
- *na bondade imerecida de Deus*: Paulo tinha sido um opositor de Jesus e de seus seguidores (At 9:3-5) e, por isso, tinha todos os motivos para dar destaque à bondade imerecida de Jeová. (Veja o Glossário, “Bondade imerecida”.) Paulo reconhecia que era só por causa da bondade imerecida de Deus que ele era capaz de realizar seu ministério. (1Co 15:10; 1Ti 1:13, 14) Ao falar com os anciãos de Éfeso, ele mencionou essa qualidade duas vezes. (At 20:24, 32) E, em suas 14 cartas, Paulo mencionou a “bondade imerecida” umas 90 vezes, bem mais do que qualquer outro escritor bíblico. Por exemplo, Paulo fala da bondade imerecida de Deus ou de Jesus nas saudações iniciais de todas as suas cartas, menos na carta aos hebreus, e usa essa expressão nas observações finais de todas elas.
====

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, quase toda a cidade se reuniu para ouvir a palavra de Jeová.

[TIP]
====
- *a palavra de Jeová*: Veja a nota de estudo em At 8:25 e o Apêndice C3 (introdução e At 13:44).
====

[[v44-13-45]]

^<<v44-13-45,45>>^ Quando os judeus viram as multidões, ficaram cheios de ciúme e começaram a contradizer de modo blasfemo o que Paulo estava dizendo.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então, Paulo e Barnabé corajosamente lhes disseram: “Era necessário que se falasse a palavra de Deus primeiro a vocês. Visto que a rejeitam e não se julgam dignos da vida eterna, agora nos voltaremos para as nações.

[[v44-13-47]]

^<<v44-13-47,47>>^ Pois Jeová nos deu esta ordem: ‘Eu designei você como luz para as nações, para que leve salvação até os confins da terra.’”

[TIP]
====
- *Jeová nos deu esta ordem*: A citação que aparece neste versículo é de Is 49:6. No versículo anterior de Isaías (Is 49:5), o texto hebraico original mostra claramente que é Jeová quem está falando. (Veja também Is 42:6.) O trabalho feito por Jesus Cristo, o Servo de Jeová, e por seus seguidores cumpre a profecia de Isaías. — Is 42:1; veja a nota de estudo em Lu 2:32 e o Apêndice C3 (introdução e At 13:47).
- *até os confins da terra*: Ou: “até a parte mais distante da terra”. Esta é uma citação da profecia de Is 49:6. Nesse versículo de Isaías, a Septuaginta usa a mesma expressão grega que aparece aqui em Atos e que foi traduzida como “até os confins da terra”. Isaías predisse que o servo de Jeová seria uma “luz para as nações” e que a salvação da parte de Deus ‘chegaria até os confins da terra’. Na ocasião mencionada aqui, em Antioquia da Pisídia, Paulo e Barnabé indicaram que essas palavras proféticas na verdade eram também uma ordem para os seguidores de Cristo. Jeová queria que eles servissem como luz para as nações. A expressão grega que aparece aqui também foi usada em At 1:8 (veja a nota de estudo) para mostrar qual seria o alcance do testemunho que os seguidores de Jesus dariam sobre ele.
====

[[v44-13-48]]

^<<v44-13-48,48>>^ Quando as pessoas das nações ouviram isso, alegraram-se e começaram a glorificar a palavra de Jeová, e todos os que tinham a disposição correta para com a vida eterna se tornaram crentes.

[TIP]
====
- *a palavra de Jeová*: Veja a nota de estudo em At 8:25 e o Apêndice C3 (introdução e At 13:48).
- *tinham a disposição correta para com*: Estas palavras se referem a alguns não judeus em Antioquia da Pisídia que se tornaram crentes depois de ouvir a pregação de Paulo e Barnabé. A palavra grega traduzida aqui como “tinham a disposição correta para com” (uma forma do verbo tásso) pode ter vários significados, incluindo “arrumar; colocar em posição; pôr em ordem; designar”. Assim, para saber o significado dela aqui, é necessário considerar o contexto. No sábado anterior, Paulo tinha feito um discurso público empolgante, dando testemunho cabal tanto para os judeus como para os não judeus. (At 13:16-41) Mas a continuação do relato (At 13:46, 48) mostra que, no final, a reação de alguns judeus foi bem diferente da reação dos não judeus mencionados aqui. De acordo com Paulo e Barnabé, os judeus insistiram em rejeitar “a palavra de Deus” e mostraram por suas ações que ‘não se julgavam dignos da vida eterna’. (At 13:46) Por outro lado, os não judeus alegraram-se e começaram a glorificar a palavra de Jeová. Assim, neste contexto, o verbo tásso passa a ideia de que os não judeus em Antioquia, por mostrarem a atitude correta, “se colocaram em posição para” ganhar a vida eterna. Por isso, o verbo foi traduzido aqui como “tinham a disposição correta para com”. Muitas traduções da Bíblia usam aqui em At 13:48 expressões como “haviam sido destinados para; tinham sido escolhidos para”, o que pode dar a impressão de que essas pessoas tinham sido predestinadas por Deus para ganhar a vida eterna. Mas o contexto deste versículo e o restante da Bíblia não apoiam essa ideia. Esses não judeus não estavam predestinados a ganhar a vida eterna, assim como os judeus que rejeitaram a mensagem não estavam predestinados a perder a vida eterna. Paulo tentou convencer os judeus a aceitar as boas novas, e foram eles que escolheram conscientemente rejeitar a mensagem. Jesus tinha explicado que algumas pessoas mostrariam pelas suas ações que não estavam ‘aptas para o Reino de Deus’. (Lu 9:62) Mas ele também falou de outras pessoas que mostrariam pelas suas ações que eram ‘merecedoras’ das boas novas. (Mt 10:11, 13) Os não judeus mencionados aqui faziam parte desse grupo de pessoas.
====

[[v44-13-49]]

^<<v44-13-49,49>>^ Além disso, a palavra de Jeová era divulgada por toda aquela região.

[TIP]
====
- *a palavra de Jeová*: Veja a nota de estudo em At 8:25 e o Apêndice C3 (introdução e At 13:49).
====

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus instigaram as mulheres de alta posição que eram tementes a Deus, bem como os homens mais importantes da cidade; incitaram uma perseguição contra Paulo e Barnabé e os expulsaram do seu território.

[TIP]
====
- *que eram tementes a Deus*: Ou: “que adoravam a Deus”. A palavra grega sébomai também pode ser traduzida como “reverenciar; venerar”. Na Peshitta siríaca ela foi traduzida como “que temiam a Deus”. Algumas traduções das Escrituras Gregas Cristãs para o hebraico (chamadas de J7, 8, 10, 18 no Apêndice C4) usam o nome de Deus aqui. A frase em hebraico que aparece nelas poderia ser traduzida como “que temiam a Jeová”.
====

[[v44-13-51]]

^<<v44-13-51,51>>^ Estes então sacudiram o pó dos seus pés em testemunho contra eles e foram para Icônio.

[TIP]
====
- *sacudiram o pó dos seus pés em testemunho contra eles*: Paulo e Barnabé estavam seguindo a instrução de Jesus registrada em Mt 10:14; Mr 6:11 e Lu 9:5. Quando judeus devotos viajavam por outros países, eles sacudiam o pó supostamente impuro de suas sandálias antes de entrar de novo no território dos judeus. Mas o significado da instrução de Jesus era diferente. Ao sacudir o pó de seus pés, os discípulos mostrariam que não eram responsáveis pelo que aconteceria com aquelas pessoas quando fossem julgadas por Deus. Paulo fez algo parecido em Corinto, quando sacudiu sua roupa. Nessa ocasião, Paulo explicou seu gesto dizendo: “Que o sangue de vocês recaia sobre a sua própria cabeça. Eu estou limpo.” — Veja a nota de estudo em At 18:6.
====

[[v44-13-52]]

^<<v44-13-52,52>>^ E os discípulos continuavam cheios de alegria e de espírito santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]